"""Audit and rebuild: re-earning a verdict, and regrowing generated bytes
(`spec/verification.md`, `spec/claim-format.md`, `spec/identity.md`).

`audit` trusts nothing already on disk: it materializes a fresh judging
room from the pinned inputs and the generated bytes present, re-runs every
gate there sandboxed, and requires every pinned byte to reproduce. `rebuild`
starts from nothing but the pinned inputs, drives a producer to regrow the
generated outputs, then re-runs the gates the same way -- the producer
inherits the caller's own reachability and HOME (it is the caller's
oracle), while the gates stay scrubbed and sandboxed as always.

A judging room receives the recipe the root was computed from: byte-for-byte
below format 3 (the root covers the whole file), and -- from format 3 on --
rewritten as the guidance-stripped preimage, as TOML, under the canonical
name (`spec/claim-format.md`, the-room-recipe-is-toml proposal). Both verbs
share that one room-building step.

Stdlib only.
"""
import json
import os
import re
import shutil
import subprocess
import tempfile
import time

from . import core, identity, recipe, run, seal
from .core import ClaimError


# -- Building a judging room ---------------------------------------------


def _toml_string(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _toml_key(k: str) -> str:
    return k if re.fullmatch(r"[A-Za-z0-9_-]+", k) else _toml_string(k)


def _toml_scalar(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, str):
        return _toml_string(v)
    if isinstance(v, list):
        return "[" + ", ".join(_toml_scalar(x) for x in v) + "]"
    if isinstance(v, dict):
        inner = ", ".join(f"{_toml_key(k)} = {_toml_scalar(val)}" for k, val in v.items())
        return "{ " + inner + " }"
    raise ClaimError(f"cannot serialize value to TOML: {v!r}")


def _room_recipe_toml(preimage: dict) -> str:
    """The preimage recipe (`identity._preimage_recipe`), as TOML text --
    the bytes a format-3+ judging room receives under `core.RECIPE`.
    """
    lines = ["[claim]"]
    for k, v in preimage.get("claim", {}).items():
        lines.append(f"{_toml_key(k)} = {_toml_scalar(v)}")
    for step in preimage.get("step", []):
        lines.append("")
        lines.append("[[step]]")
        for k, v in step.items():
            lines.append(f"{_toml_key(k)} = {_toml_scalar(v)}")
    return "\n".join(lines) + "\n"


def _materialize(doc: dict, src: str, into: str, include_generated: bool = True) -> str:
    """Build a judging room at `into` from claim directory `src`.

    Writes the room's recipe (byte-for-byte below format 3, the
    guidance-stripped preimage as TOML from format 3 on), copies every
    pinned input, and -- when `include_generated` -- the generated bytes
    present now. Never copies a gate's pinned output: that is always
    earned fresh by running the gate in the room.
    """
    os.makedirs(into, exist_ok=True)
    if identity._claim_format(doc) >= 3:
        text = _room_recipe_toml(identity._preimage_recipe(doc))
        with open(os.path.join(into, core.RECIPE), "w", encoding="utf-8") as f:
            f.write(text)
    else:
        original = recipe.recipe_path(src)
        shutil.copy2(original, os.path.join(into, os.path.basename(original)))

    for path in recipe._inputs(src, doc):
        core._copy_into(src, into, path)
    manifest_name = doc.get("claim", {}).get("inputs_manifest")
    if manifest_name:
        core._copy_into(src, into, manifest_name)

    if include_generated:
        for out in recipe.generated_outputs(doc):
            full = core._safe(src, out)
            if os.path.isfile(full):
                core._copy_into(src, into, out)
    return into


def _compare_pin(original: str, room: str, path: str) -> bool:
    """Do the original's and the room's bytes agree at `path`?

    Tells *reproduced* (the gate re-earned the same pinned bytes) from
    *mismatch* (it earned something else) in `audit`.
    """
    try:
        a = core._hash_file(core._safe(original, path))
        b = core._hash_file(core._safe(room, path))
    except (ClaimError, OSError):
        return False
    return a == b


# -- Driving a producer ----------------------------------------------------


def _step_guidance(step: dict):
    """A produce step's hint for a rebuilder, under either spelling
    (`spec/claim-format.md`); `None` if the step carries none.
    """
    for key in core.GUIDANCE_KEYS:
        if key in step:
            return step[key]
    return None


def _read_usage(path) -> dict:
    """Usage a producer self-reported at `path` (`RETICULI_USAGE`): any of
    `usd`/`tokens`/`calls`. `seconds` is never read from here -- it is the
    kernel's own measurement (`spec/kernel-api.md`).
    """
    if not path or not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            doc = json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(doc, dict):
        return {}
    usage = {}
    for key in ("usd", "tokens", "calls"):
        v = doc.get(key)
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            usage[key] = v
    return usage


def _produce(doc: dict, room: str, producer: str, outputs: list,
             guidance: bool = True, producer_env=None) -> dict:
    """Run `producer` in `room`: the caller's own reachability and HOME,
    never the kernel's sandbox -- the producer is the caller's oracle, and
    its output faces the jailed gate regardless (`spec/claim-format.md`,
    the free-the-producer / producer-keeps-its-home proposals).

    Names the target output in `RETICULI_OUTPUT` (absolute) and lists every
    output in `RETICULI_OUTPUTS` (JSON), whether there is one or many.
    """
    claim = doc.get("claim", {})
    env = run._scrub_env()

    outs_abs = [core._safe(room, o) for o in outputs]
    env[core._ENV_OUTPUT] = outs_abs[0] if outs_abs else room
    env[core._ENV_OUTPUTS] = json.dumps(outputs)
    env[core._ENV_CLAIM] = claim.get("name", "")

    usage_path = core._safe(room, core.STORE) + os.sep + "usage.json"
    os.makedirs(os.path.dirname(usage_path), exist_ok=True)
    env[core._ENV_USAGE] = usage_path

    if guidance:
        hints = [h for h in (_step_guidance(s) for s in recipe.produces(doc)) if h]
        if hints:
            env[core._ENV_REQUEST] = "\n".join(hints)

    if producer_env:
        items = producer_env.items() if isinstance(producer_env, dict) else (
            (k, os.environ.get(k)) for k in producer_env
        )
        for k, v in items:
            if v is not None:
                env[k] = v

    result = run._run([core._SHELL, "-c", producer], room, env, core.PRODUCER_TIMEOUT)
    return {
        "returncode": result["returncode"],
        "stdout": result["stdout"].decode("utf-8", "replace"),
        "stderr": result["stderr"].decode("utf-8", "replace"),
        "timed_out": result["timed_out"],
        "usage_path": usage_path,
    }


# -- Signature verification (`spec/record.md`) -----------------------------


def _ssh_verify(allowed_signers: str, identity_name: str, namespace: str,
                 signature_path: str, data: bytes) -> bool:
    """Verify a detached ssh signature over `data`: `ssh-keygen -Y verify`
    against `allowed_signers`, for `identity_name` in `namespace`
    (`spec/record.md`). `False` on any failure to verify -- never raises.
    """
    if not shutil.which("ssh-keygen"):
        return False
    try:
        proc = subprocess.run(
            ["ssh-keygen", "-Y", "verify", "-f", allowed_signers,
             "-I", identity_name, "-n", namespace, "-s", signature_path],
            input=data, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            timeout=30,
        )
        return proc.returncode == 0
    except (OSError, subprocess.SubprocessError):
        return False


def _authorized(signer: str, allowed_signers: str) -> bool:
    """Is `signer` named in an ssh `AllowedSignersFile`?

    Trust is verifier-relative (`spec/verification.md`): authorized only
    against a file the caller names, never a global default.
    """
    if not signer or not allowed_signers or not os.path.isfile(allowed_signers):
        return False
    with open(allowed_signers, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            identities = line.split(" ", 1)[0]
            if signer in identities.split(","):
                return True
    return False


# -- audit -------------------------------------------------------------


def _components(manifest: dict) -> dict:
    comps = manifest.get("components")
    return comps if isinstance(comps, dict) else {}


def audit(d: str, shallow: bool = False) -> dict:
    """Deep re-earning: trust no verdict already on disk, re-run every
    gate cold and sandboxed in a fresh room, and require every pinned byte
    to reproduce (`spec/verification.md`). Composed claims audit
    recursively unless `shallow`.
    """
    try:
        doc = recipe.load_recipe(d)
    except ClaimError as e:
        return {"ok": False, "verdict": "broken", "reason": str(e), "gates": []}

    missing = run.preflight(doc)
    if missing:
        return {"ok": False, "verdict": "environment",
                 "reason": f"missing requirements: {missing}", "gates": []}
    try:
        run.furnish(doc, d)
    except ClaimError as e:
        return {"ok": False, "verdict": "environment", "reason": str(e), "gates": []}

    try:
        manifest = seal.read_manifest(d)
        recomputed = identity.root(doc, d)
    except ClaimError as e:
        return {"ok": False, "verdict": "broken", "reason": str(e), "gates": []}

    if recomputed != manifest["root"]:
        return {"ok": False, "verdict": "broken", "root": recomputed,
                 "reason": "identity does not hold: pinned bytes changed",
                 "gates": []}

    room = tempfile.mkdtemp(prefix="reticuli-audit-")
    try:
        _materialize(doc, d, room, include_generated=True)
        gate_results = []
        earned = True
        for step in recipe.gates(doc):
            result = run.run_gate(step["run"], room, doc)
            output = step["output"]
            if result["status"] != "ok":
                status = result["status"]
            elif not os.path.isfile(core._safe(room, output)):
                status = "mismatch"
            elif _compare_pin(d, room, output):
                status = "reproduced"
            else:
                status = "mismatch"
            if status != "reproduced":
                earned = False
            gate_results.append({
                "output": output, "status": status,
                "quarantine": result["quarantine"],
            })

        sub_ok = True
        if not shallow:
            for name, rel in _components(manifest).items():
                sub = audit(core._safe(d, rel), shallow=False)
                if not sub.get("ok"):
                    sub_ok = False
        earned = earned and sub_ok

        return {
            "ok": earned,
            "verdict": "earned" if earned else "broken",
            "root": recomputed,
            "gates": gate_results,
        }
    finally:
        shutil.rmtree(room, ignore_errors=True)


# -- rebuild -----------------------------------------------------------


def rebuild(d: str, producer: str, into: str, produce_from=None,
            input_from=None, guidance: bool = True, producer_env=None,
            vendor=None, model=None) -> dict:
    """Regrow the generated outputs of claim `d` into a fresh directory
    `into`, by driving `producer` there, then re-run the gates until they
    pass; a ledger entry is appended to the built claim.
    """
    src = input_from or d
    doc = recipe.load_recipe(src)

    if os.path.exists(into) and os.listdir(into):
        raise ClaimError(f"rebuild target is not empty: {into!r}")
    os.makedirs(into, exist_ok=True)

    missing = run.preflight(doc)
    if missing:
        raise ClaimError(f"missing requirements: {missing}")
    run.furnish(doc, src)

    _materialize(doc, src, into, include_generated=False)

    generated = recipe.generated_outputs(doc)
    started = time.time()
    prod = _produce(doc, into, producer, generated,
                     guidance=guidance, producer_env=producer_env)
    elapsed = time.time() - started
    if prod["returncode"] != 0:
        raise ClaimError(
            f"producer failed (exit {prod['returncode']}): {prod['stderr'][-500:]}"
        )

    backend = run.sandbox_backend()
    for step in recipe.gates(doc):
        gate = run.run_gate(step["run"], into, doc)
        backend = gate["quarantine"]
        if gate["status"] != "ok":
            raise ClaimError(
                f"gate {step['output']!r} did not pass during rebuild: {gate['status']}"
            )

    usage = _read_usage(prod.get("usage_path"))
    entry = {"kind": "producer", "seconds": elapsed}
    if vendor is not None:
        entry["vendor"] = vendor
    if model is not None:
        entry["model"] = model
    entry.update(usage)
    run.ledger(into, entry)

    return {"root": identity.root(doc, into), "quarantine": backend}
