"""The identity layer: a claim's root, and the build digest a signature binds
to (`spec/identity.md`).

The root is a SHA-256 over a sorted string-to-string map: the parsed recipe
(canonically serialized), the pinned inputs' bytes, and every non-generated
step output's bytes. Generated outputs never enter it, so an implementation
can be deleted and regrown byte-different without moving the root.

The build digest covers exactly the generated bytes present on disk right
now: a signature binds to what was actually produced, not to the recipe's
intent.
"""
import copy
import hashlib
import json
import os

from . import core, recipe
from .core import ClaimError


def _canonical_json(obj) -> str:
    """`json.dumps` with the rules `spec/identity.md` pins: sorted keys,
    default (non-compact) separators, ASCII escaping of non-ASCII, exact
    decimal integers, CPython `repr`-equivalent floats."""
    return json.dumps(obj, sort_keys=True)


def _claim_format(doc: dict) -> int:
    """The claim's declared format; absent means 1 (`spec/claim-format.md`)."""
    return doc.get("claim", {}).get("format", 1)


def _preimage_recipe(doc: dict) -> dict:
    """The recipe exactly as it enters `parts["recipe"]`.

    At format 3+, every step's `guidance`/`request` key is stripped: a
    producer hint cannot decide acceptance, so it is not identity-bearing.
    At format 4+, the (already-stripped) step list is re-sorted into the
    lexicographic order of each step's own canonical JSON encoding: the
    step list is a set of obligations, not an authoring sequence.
    """
    fmt = _claim_format(doc)
    out = copy.deepcopy(doc)
    steps = out.get("step", [])
    if fmt >= 3:
        for step in steps:
            step.pop("guidance", None)
            step.pop("request", None)
    if fmt >= 4:
        steps = sorted(steps, key=_canonical_json)
        out["step"] = steps
    return out


def _parts(doc: dict, d: str) -> dict:
    """The string-to-string map the root hashes (`spec/identity.md`)."""
    parts = {
        "digest": core.DIGEST,
        "recipe": _canonical_json(_preimage_recipe(doc)),
    }
    for path in recipe._inputs(d, doc):
        parts["input:" + path] = core._hash_file(core._safe(d, path))
    for step in doc.get("step", []):
        kind = step["kind"]
        cls = step.get("class")
        if kind == "produce":
            if (cls if cls is not None else "generated") in ("generated", "free"):
                continue
        path = step["output"]
        parts["pinned:" + path] = core._hash_file(core._safe(d, path))
    return parts


def root(doc: dict, d: str) -> str:
    """The claim's identity: a SHA-256 over `_parts` (`spec/identity.md`)."""
    preimage = _canonical_json(_parts(doc, d))
    return hashlib.sha256(preimage.encode("utf-8")).hexdigest()


def build_digest(d: str) -> str:
    """The digest of the generated bytes present now (`spec/identity.md`).

    One `[path, sha256]` pair per produce step whose class is generated,
    excluding any step carrying `from` (its bytes are borrowed, not
    produced here) and any output absent on disk. The digest of the empty
    list when none exist.
    """
    doc = recipe.load_recipe(d)
    entries = []
    for step in recipe.produces(doc):
        cls = step.get("class")
        if (cls if cls is not None else "generated") not in ("generated", "free"):
            continue
        if "from" in step:
            continue
        path = step["output"]
        full = core._safe(d, path)
        if not os.path.isfile(full):
            continue
        entries.append([path, core._hash_file(full)])
    entries.sort(key=lambda e: e[0])
    return hashlib.sha256(_canonical_json(entries).encode("utf-8")).hexdigest()
