"""Seal and verify: freezing a claim's identity, and confirming it
(`spec/claim-format.md`, `spec/verification.md`).

`seal` computes the root from the recipe and the bytes present, and writes
it onto `.reticuli/manifest.json` -- pure identity (`name`, `root`), plus
the part-level hashes (`spec/identity.md`'s `parts`) needed to localize a
later mismatch. `verify` recomputes the root from the bytes present and
compares it with the sealed manifest -- identity only, no gate is executed.
The root is a function of the pinned inputs and independent of the
generated bytes: editing a generated output keeps the root, editing a
pinned input moves it.
"""
import json
import os

from . import core, identity, recipe
from .core import ClaimError


def seal(d: str) -> dict:
    """Freeze claim directory `d`: compute the root, write the manifest."""
    doc = recipe.load_recipe(d)
    name = doc["claim"]["name"]
    parts = identity._parts(doc, d)
    r = identity.root(doc, d)
    manifest = {"name": name, "root": r, "parts": parts}
    os.makedirs(os.path.join(d, core.STORE), exist_ok=True)
    core._write_json(os.path.join(d, core.MANIFEST), manifest)
    return manifest


def read_manifest(d: str) -> dict:
    """Read back the manifest `seal` wrote: `{name, root}`, plus residue."""
    path = os.path.join(d, core.MANIFEST)
    try:
        with open(path, "r", encoding="utf-8") as f:
            doc = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        raise ClaimError(f"cannot read manifest {path!r}: {e}") from e
    if (
        not isinstance(doc, dict)
        or not isinstance(doc.get("name"), str)
        or not isinstance(doc.get("root"), str)
        or len(doc["root"]) != 64
    ):
        raise ClaimError(f"malformed manifest {path!r}")
    return doc


def _changed_parts(d: str) -> dict:
    """Localize a mismatch: the sealed manifest's part hashes against freshly
    recomputed ones, part key by part key.

    Returns `{key: [old, new]}` for every part whose hash differs, every part
    only the sealed manifest names, and every part only the present bytes
    name. Diagnostic only -- the root alone decides pass or fail.
    """
    manifest = read_manifest(d)
    old = manifest.get("parts", {})
    doc = recipe.load_recipe(d)
    new = identity._parts(doc, d)
    changed = {}
    for key in set(old) | set(new):
        if old.get(key) != new.get(key):
            changed[key] = [old.get(key), new.get(key)]
    return changed


def verify(d: str) -> dict:
    """Recompute the root from the bytes present and compare it with the
    sealed manifest -- identity only, no gate is executed
    (`spec/verification.md`).
    """
    manifest = read_manifest(d)
    try:
        doc = recipe.load_recipe(d)
        recomputed = identity.root(doc, d)
    except ClaimError as e:
        return {
            "ok": False,
            "name": manifest["name"],
            "root": manifest["root"],
            "recomputed": None,
            "reason": str(e),
        }
    ok = recomputed == manifest["root"]
    result = {
        "ok": ok,
        "name": manifest["name"],
        "root": manifest["root"],
        "recomputed": recomputed,
    }
    if not ok:
        result["changed"] = _changed_parts(d)
    return result
