"""The launcher: run software that exists only latently in a claim.

A runnable claim keeps its identity durable and its implementation as a cache
entry.  `run` checks a cached build (verdicts re-earned) or generates a fresh
one with the configured producer, then executes the entrypoint named in
`package.toml`; `strip` deletes the generated bytes and the claim survives.
The verification layer below (verify / audit / rebuild) answers *is this the
claimed thing, honestly earned, regrowable*; the launcher adds the questions
execution needs -- *may this run, under what confinement, accepted by whom* --
the lifecycle, the consent gate on unreviewed bytes, and the scrubbed,
sandboxed run step.

Invoked as `python3 -m reticuli.launcher {run,strip,ls}`.  Its acceptance
check is `criteria/launcher_check.py`; this module is the generated side of that
claim.  The layer sits above the kernel and below the CLI, so it calls the
kernel's PUBLIC api directly and imports nothing from a layer above it.
Stdlib only; all work happens inside functions, so importing this module has
no side effects.
"""
import argparse
import os
import shutil
import subprocess
import sys
import tomllib

from . import kernel
from ._util import copy_into, declared_inputs, hash_bytes, read_json, safe_path, write_json

#: the launcher's own cache, beside the claim's store and never part of it
STATE = ".launcher"

#: the package manifest: which file this claim runs
PACKAGE = "package.toml"

#: the producer command used to regrow an implementation that is not present
PRODUCER_ENV = "RETICULI_PRODUCER"

EPILOG = """verbs:
  run   <claim> [--accept-generated] [--signed-only] [--no-sandbox] [-- args...]
  strip <claim>
  ls    <claim>...

exit codes: the entrypoint's own when it runs; 3 not runnable; 4 newly
generated bytes (consent required: --accept-generated); 5 trust refused
(--signed-only); 6 drifted build (strip to recover); 7 latent, no producer
(RETICULI_PRODUCER).
"""


def say(msg):
    print("launcher: " + msg, file=sys.stderr)


def die(code, msg):
    say(msg)
    sys.exit(code)


def load_claim(path):
    """Parse the claim's recipe and list the outputs an implementation owns.

    Generated outputs are the produce steps the root does not hash: they are
    the cache, free to be deleted and regrown.  A produce step carrying `from`
    belongs to a component claim, not to this one.
    """
    root = os.path.abspath(path)
    try:
        recipe = kernel.load_recipe(root)
    except kernel.ClaimError as e:
        die(3, f"{path} is not a claim: {e}")
    generated = [s["output"] for s in recipe.get("step", [])
                 if s.get("kind") == "produce" and "from" not in s
                 and s.get("class") == "generated"
                 and isinstance(s.get("output"), str)]
    return root, recipe, generated


def entrypoint_of(root, recipe, generated):
    """The file `run` executes, from the claim's pinned package manifest."""
    if PACKAGE in generated:
        die(3, f"{PACKAGE} is a generated output here; it must be a pinned "
               "input, so the entrypoint the gate exercised cannot drift "
               "from the one that runs")
    if PACKAGE not in declared_inputs(recipe):
        die(3, f"not runnable: no {PACKAGE} among the claim's pinned inputs")
    try:
        with open(os.path.join(root, PACKAGE), "rb") as f:
            entry = tomllib.load(f)["package"]["entrypoint"]
    except (OSError, KeyError, TypeError, tomllib.TOMLDecodeError) as e:
        die(3, f"unreadable {PACKAGE}: {e}")
    if not isinstance(entry, str) or not entry.strip():
        die(3, f"{PACKAGE} entrypoint is not a path: {entry!r}")
    norm = os.path.normpath(entry)
    confine(root, norm, "entrypoint")
    return norm


def verify(root):
    """The kernel's shallow check: do these bytes still hash to the sealed
    root?  A claim too damaged to judge answers nothing rather than raising."""
    try:
        return kernel.verify(root)
    except kernel.ClaimError:
        return {}


def phase_of(root):
    """draft / sealed / signed, as this host is able to judge it."""
    try:
        return kernel.phase(root)
    except kernel.ClaimError:
        return "draft"


def audit(root):
    """Do the claim's verdicts re-earn from the bytes present, right now?"""
    try:
        return kernel.audit(root).get("ok") is True
    except kernel.ClaimError:
        return False


def confine(root, rel, what):
    """Every recipe-derived path stays inside the claim directory, or we
    refuse before anything is deleted, written, or executed."""
    try:
        return safe_path(root, rel)
    except ValueError:
        die(3, f"{what} {rel!r} escapes the claim root")


def generated_paths(root, generated):
    return {out: confine(root, out, "produce output") for out in generated}


def scrubbed_env(root, backend):
    """The entrypoint never inherits the caller's secrets: PATH and locale
    only, a claim-local HOME/TMPDIR, and the already-sandboxed signal when
    sandboxed -- the same hygiene the kernel gives gates."""
    keep = {}
    for k in ("PATH", "LANG", "LC_ALL", "LC_CTYPE", "TERM"):
        if k in os.environ:
            keep[k] = os.environ[k]
    home = os.path.join(root, STATE, "home")
    tmp = os.path.join(root, STATE, "tmp")
    os.makedirs(home, exist_ok=True)
    os.makedirs(tmp, exist_ok=True)
    keep["HOME"] = home
    keep["TMPDIR"] = tmp
    if backend in ("seatbelt", "bubblewrap", "inherited"):
        keep["RETICULI_JAILED"] = "1"
    return keep


def invoke(root, generated):
    """Regrow the missing implementation with the configured producer.

    The rebuild runs in a scratch workspace and only its generated outputs are
    copied back, so a producer that fails halfway cannot leave the claim in a
    half-written state.
    """
    producer = os.environ.get(PRODUCER_ENV)
    if not producer:
        die(7, "the claim is latent and no producer is configured -- set "
               f"{PRODUCER_ENV} to a rebuild producer command")
    state = os.path.join(root, STATE)
    work = os.path.join(state, "work")
    shutil.rmtree(work, ignore_errors=True)
    os.makedirs(state, exist_ok=True)
    say("latent -> regrowing with the configured producer")
    try:
        kernel.rebuild(root, producer, work)
    except kernel.ClaimError as e:
        shutil.rmtree(work, ignore_errors=True)
        die(6, "the rebuild did not land:\n" + str(e))
    for out in generated:
        copy_into(os.path.join(work, out),
                  confine(root, out, "produce output"))
    shutil.rmtree(work, ignore_errors=True)
    v = verify(root)
    if v.get("ok") is not True:
        die(6, "the regrown bytes do not verify against the sealed root")
    with open(os.path.join(state, "FRESH"), "w") as f:
        f.write("generated, not yet accepted\n")


def pick_sandbox(root, no_sandbox):
    """Which confinement this execution gets, decided by PROBE, not by PATH.

    Every candidate is run once and judged on its exit code: a sandbox that is
    installed but cannot start (unprivileged user namespaces blocked by
    AppArmor, a seatbelt profile the host refuses to apply) is not a sandbox,
    and reporting one would be a false claim about the confinement.
    """
    if no_sandbox:
        return "off", []
    if os.environ.get("RETICULI_JAILED"):
        return "inherited", []
    if sys.platform == "darwin" and shutil.which("sandbox-exec"):
        profile = (
            '(version 1)(allow default)(deny network*)(deny file-write*)'
            f'(allow file-write* (subpath "{root}"))'
            '(allow file-write* (subpath "/private/tmp"))'
            '(allow file-write* (subpath "/private/var/folders"))'
            '(allow file-write* (subpath "/dev"))')
        wrap = ["sandbox-exec", "-p", profile]
        ok = subprocess.run(wrap + ["/usr/bin/true"], capture_output=True,
                            check=False).returncode == 0
        if ok:
            return "seatbelt", wrap
    if shutil.which("bwrap"):
        wrap = ["bwrap", "--ro-bind", "/", "/", "--bind", root, root,
                "--unshare-net", "--die-with-parent"]
        # present is not functional (unprivileged userns may be blocked, as on
        # GitHub's ubuntu-24.04 runners): probe, or every run dies sandboxed
        ok = subprocess.run(wrap + ["true"], capture_output=True,
                            check=False).returncode == 0
        if ok:
            return "bubblewrap", wrap
    return "none", []


def digests(paths):
    out = {}
    for name, full in paths.items():
        with open(full, "rb") as fh:
            out[name] = hash_bytes(fh.read())
    return out


def accept(root, paths, state_fresh):
    """Consent binds bytes: record what was accepted, clear the marker."""
    write_json(os.path.join(root, STATE, "ACCEPTED"), digests(paths))
    if os.path.exists(state_fresh):
        os.remove(state_fresh)


def run(a):
    root, recipe, generated = load_claim(a.claim)
    entry = entrypoint_of(root, recipe, generated)
    paths = generated_paths(root, generated)
    state_fresh = os.path.join(root, STATE, "FRESH")
    state_accept = os.path.join(root, STATE, "ACCEPTED")

    if not all(os.path.exists(p) for p in paths.values()):
        invoke(root, generated)
        if not a.accept_generated:
            die(4, "these bytes were generated just now and accepted by no "
                   "one. re-run with --accept-generated to execute and "
                   "accept them")
        accept(root, paths, state_fresh)
    else:
        if os.path.exists(state_accept):
            accepted = read_json(state_accept)
            if accepted != digests(paths):
                die(6, "the implementation has drifted from the bytes you "
                       "accepted -- an unreviewed substitution, even if it "
                       "still passes the gate. nothing executed, nothing "
                       "modified; `strip` and re-run to recover, or "
                       "investigate first")
        if not audit(root):
            die(6, "the implementation has drifted: its verdicts no longer "
                   "re-earn from these bytes. nothing was executed or "
                   "modified; `strip` and re-run to recover, or investigate "
                   "first")
        if os.path.exists(state_fresh):
            if not a.accept_generated:
                die(4, "these bytes were generated earlier and accepted by "
                       "no one. re-run with --accept-generated to execute "
                       "and accept them")
            accept(root, paths, state_fresh)

    phase = phase_of(root)
    if a.signed_only and phase != "signed":
        die(5, f"phase = {phase}; --signed-only refuses everything below a "
               "signature verified against your trust anchor")
    if phase != "signed":
        say(f"phase = {phase} -- authorized by no one; the gates vouch, "
            "a human has not")

    backend, wrap = pick_sandbox(root, a.no_sandbox)
    say(f'quarantine = "{backend}"')
    cmd = wrap + [sys.executable, os.path.join(root, entry)] + a.args
    child = subprocess.run(cmd, cwd=root, env=scrubbed_env(root, backend),
                           check=False)
    sys.exit(child.returncode)


def strip(a):
    root, _recipe, generated = load_claim(a.claim)
    for p in generated_paths(root, generated).values():
        if os.path.exists(p):
            os.remove(p)
    shutil.rmtree(os.path.join(root, STATE), ignore_errors=True)
    say("generated bytes deleted; the claim remains")
    sys.exit(0)


def ls(a):
    for path in a.claim:
        try:
            root, recipe, generated = load_claim(path)
        except SystemExit:
            print(f"{os.path.basename(path):<20} {'?':<14} not a claim")
            continue
        v = verify(root)
        present = ("materialized"
                   if all(os.path.exists(os.path.join(root, f))
                          for f in generated)
                   else "latent")
        name = recipe.get("claim", {}).get("name") or os.path.basename(root)
        print(f"{name:<20} "
              f"{(v.get('root') or '?')[:12]:<14} "
              f"{phase_of(root):<8} {present}")
    sys.exit(0)


def main(argv=None):
    ap = argparse.ArgumentParser(
        prog="launcher", epilog=EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="run software that exists only latently: run regrows or "
                    "checks a claim's implementation and executes the "
                    "entrypoint its package.toml names; strip deletes the "
                    "generated bytes; ls lists what is on hand.")
    sub = ap.add_subparsers(dest="verb", required=True)

    r = sub.add_parser("run", help="materialize (if needed) and execute")
    r.add_argument("claim")
    r.add_argument("--accept-generated", action="store_true",
                   help="execute and accept bytes no one has reviewed")
    r.add_argument("--signed-only", action="store_true",
                   help="refuse anything below a trusted signature")
    r.add_argument("--no-sandbox", action="store_true",
                   help="run unconfined (reported honestly)")
    r.add_argument("args", nargs="*")
    r.set_defaults(fn=run)

    s = sub.add_parser("strip",
                       help="delete the generated bytes, keep the claim")
    s.add_argument("claim")
    s.set_defaults(fn=strip)

    ll = sub.add_parser("ls", help="list claims: root, phase, bytes on hand")
    ll.add_argument("claim", nargs="+")
    ll.set_defaults(fn=ls)

    # split the program's own argv off ourselves: argparse's handling of `--`
    # inside a subparser differs across 3.11/3.12/3.13 (3.11 rejects it)
    argv = list(sys.argv[1:] if argv is None else argv)
    tail = []
    if "--" in argv:
        cut = argv.index("--")
        argv, tail = argv[:cut], argv[cut + 1:]
    a = ap.parse_args(argv)
    if tail:
        if not hasattr(a, "args"):
            ap.error("arguments after -- belong to run")
        a.args = list(a.args) + tail
    a.fn(a)


if __name__ == "__main__":
    main()
