"""Records: one machine's results, frozen as the one stable interchange file.

Implements spec/record.md. A record states what this machine established
about one claim -- the identity recomputed, the generated bytes found, the
gate verdicts earned by running them, the production cost where one was
measured -- as a small JSON document whose bytes are canonical, whose digest
cites it, and whose signature lives in a namespace of its own.

The exchange layer AUTHORS records; consuming them in place of claim
directories is `crosscheck`'s side and arrives with the kernel's v2.2
revision. Everything else under `.reticuli/` stays private: this document is
the only file other programs may parse, so its member set is closed and every
refusal is in band.

Stdlib only.
"""
import hashlib
import json
import os
import platform
import re
import subprocess
import sys
import time

from . import kernel

#: The signature namespace. Distinct from `reticuli` (attestation) and
#: `reticuli.mint` (authorization) so a statement of results can never be
#: presented as either of the other two.
NAMESPACE = "reticuli.record"

#: The record-format version this module writes and understands.
FORMAT = 1

_HEX64 = re.compile(r"^[0-9a-f]{64}$")
_WHEN = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")

_MEMBERS = frozenset({"record", "name", "root", "build_digest", "gates",
                      "cost", "producer", "environment", "when", "tool"})
_REQUIRED = frozenset({"record", "name", "root", "build_digest", "gates",
                       "environment", "when"})
_GATE_MEMBERS = frozenset({"output", "status", "sandbox"})
_STATUSES = frozenset({"ok", "failed", "timeout", "mismatch", "environment"})
_SANDBOXES = frozenset({"none", "seatbelt", "bubblewrap", "inherited"})
_COST_KEYS = frozenset(kernel.COST_UNITS)
_PRODUCER_MEMBERS = frozenset({"vendor", "model", "blind", "cutoff"})
_ENVIRONMENT_MEMBERS = frozenset({"platform", "machine", "runtime"})


# ------------------------------------------------------------- the document

def emit(claimdir: str) -> dict:
    """The record of this claim, earned now: verify, then run every gate.

    Refuses unless the bytes present recompute to the sealed root -- a record
    is about a root, and a drifted claim has nothing to be about. A failing
    gate is the opposite case: it is stated, never refused, because a failed
    rebuild is evidence about the claim.
    """
    checked = kernel.verify(claimdir)
    if not checked["ok"]:
        raise kernel.ClaimError(
            "the bytes present do not recompute to the sealed root "
            f"({checked['recomputed']} != {checked['root']}): a record is "
            "about a root, and this claim has none to be about")

    audited = kernel.audit(claimdir)
    doc = {
        "record": FORMAT,
        "name": checked["name"],
        "root": checked["root"],
        "build_digest": kernel.build_digest(claimdir),
        "gates": [{"output": g.get("output"),
                   "status": g.get("status"),
                   "sandbox": g.get("quarantine") or "none"}
                  for g in audited.get("gates", [])],
        "environment": {
            "platform": sys.platform,
            "machine": platform.machine(),
            "runtime": (f"{platform.python_implementation()} "
                        f"{platform.python_version()}"),
        },
        "when": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "tool": _tool(),
    }
    cost = kernel.cost(claimdir)
    if cost:
        doc["cost"] = cost           # absent means unmeasured, never zero
    told = _producer(claimdir)
    if told:
        doc["producer"] = told       # relayed as declared, never invented
    validate(doc)
    return doc


def _tool() -> str:
    try:
        from . import __version__
        return f"reticuli {__version__}"
    except ImportError:
        return "reticuli"


def _producer(claimdir: str) -> dict:
    """The last producer declaration on the ledger, relayed as given."""
    told = {}
    for event in kernel.ledger_events(claimdir) or []:
        if event.get("event") != "producer":
            continue
        told = {}
        for key in ("vendor", "model", "cutoff"):
            value = event.get(key)
            if isinstance(value, str) and value:
                told[key] = value
        if isinstance(event.get("blind"), bool):
            told["blind"] = event["blind"]
    return told


# ------------------------------------------- canonical bytes and the digest

def canonical(doc) -> bytes:
    """The record's canonical bytes: the identity serialization, verbatim.

    Sorted keys, default separators, non-ASCII escaped -- the same rules
    spec/identity.md states for the root preimage, so an implementation of
    one has implemented the other.
    """
    return json.dumps(doc, sort_keys=True).encode("utf-8")


def digest(doc) -> str:
    """How a record is cited: sha256 hex of its canonical bytes."""
    return hashlib.sha256(canonical(doc)).hexdigest()


# --------------------------------------------------------------- validation

def _refuse(reason: str):
    raise kernel.ClaimError(f"not a record: {reason}")


def validate(doc) -> None:
    """Refuse, with a reason, anything that is not a version-1 record.

    The member set is closed on purpose: extension is a version bump, never a
    quiet extra field under an old version number. Hostile bytes surface as a
    refusal here, not as a KeyError three layers down.
    """
    if not isinstance(doc, dict):
        _refuse("a record is a JSON object")
    unknown = set(doc) - _MEMBERS
    if unknown:
        _refuse(f"unknown member(s) {sorted(unknown)} -- the member set is "
                "closed, and extension is a version bump")
    missing = _REQUIRED - set(doc)
    if missing:
        _refuse(f"missing member(s) {sorted(missing)}")

    version = doc["record"]
    if isinstance(version, bool) or not isinstance(version, int) or version < 1:
        _refuse(f"version must be a positive integer, got {version!r}")
    if version > FORMAT:
        _refuse(f"version {version} is newer than this reader understands "
                f"(version {FORMAT}); upgrade reticuli to read it")

    if not isinstance(doc["name"], str) or not doc["name"].strip():
        _refuse("name must be a non-empty string")
    for member in ("root", "build_digest"):
        value = doc[member]
        if not isinstance(value, str) or not _HEX64.match(value):
            _refuse(f"{member} must be 64 lowercase hex characters")

    if not isinstance(doc["gates"], list):
        _refuse("gates must be a list")
    for entry in doc["gates"]:
        if not isinstance(entry, dict):
            _refuse("each gate entry is an object")
        extra = set(entry) - _GATE_MEMBERS
        if extra:
            _refuse(f"unknown gate member(s) {sorted(extra)} -- per-gate "
                    "wall-clock is deliberately outside the document")
        if _GATE_MEMBERS - set(entry):
            _refuse(f"a gate entry needs {sorted(_GATE_MEMBERS)}")
        if not isinstance(entry["output"], str) or not entry["output"]:
            _refuse("a gate's output must be a non-empty string")
        if entry["status"] not in _STATUSES:
            _refuse(f"unknown gate status {entry['status']!r} "
                    f"(the vocabulary is {sorted(_STATUSES)})")
        if entry["sandbox"] not in _SANDBOXES:
            _refuse(f"unknown sandbox {entry['sandbox']!r} "
                    f"(the vocabulary is {sorted(_SANDBOXES)})")

    if "cost" in doc:
        cost = doc["cost"]
        if not isinstance(cost, dict) or not cost:
            _refuse("an unmeasured cost is omitted, never empty")
        unknown = set(cost) - _COST_KEYS
        if unknown:
            _refuse(f"unknown cost unit(s) {sorted(unknown)} "
                    f"(the units are {sorted(_COST_KEYS)})")
        for unit, value in cost.items():
            if isinstance(value, bool) or not isinstance(value, (int, float)) \
                    or value < 0:
                _refuse(f"cost {unit} must be a non-negative number, "
                        f"got {value!r}")

    if "producer" in doc:
        told = doc["producer"]
        if not isinstance(told, dict) or not told:
            _refuse("an absent producer declaration is omitted, never empty")
        unknown = set(told) - _PRODUCER_MEMBERS
        if unknown:
            _refuse(f"unknown producer member(s) {sorted(unknown)}")
        for key in ("vendor", "model", "cutoff"):
            if key in told and (not isinstance(told[key], str) or not told[key]):
                _refuse(f"producer {key} must be a non-empty string")
        if "blind" in told and not isinstance(told["blind"], bool):
            _refuse("producer blind must be a boolean")

    environment = doc["environment"]
    if not isinstance(environment, dict) or set(environment) != _ENVIRONMENT_MEMBERS:
        _refuse(f"environment holds exactly {sorted(_ENVIRONMENT_MEMBERS)}")
    for key, value in environment.items():
        if not isinstance(value, str) or not value:
            _refuse(f"environment {key} must be a non-empty string")

    if not isinstance(doc["when"], str) or not _WHEN.match(doc["when"]):
        _refuse("when must be a UTC time, YYYY-MM-DDTHH:MM:SSZ")
    if "tool" in doc and (not isinstance(doc["tool"], str) or not doc["tool"]):
        _refuse("tool, when present, is a non-empty string")


# ----------------------------------------------------------- files on disk

def write(doc, path: str) -> str:
    """Validate, then put exactly the canonical bytes on disk.

    The file IS the canonical form -- no trailing newline, no pretty
    printing -- so the digest of the file's bytes is the record's digest and
    a detached signature covers precisely what a reader hashes.
    """
    validate(doc)
    payload = canonical(doc)
    tmp = path + ".tmp"
    try:
        with open(tmp, "wb") as f:
            f.write(payload)
        os.replace(tmp, path)
    except OSError as exc:
        raise kernel.ClaimError(f"cannot write record {path}: {exc}") from None
    return path


def read(path: str) -> dict:
    """Parse and validate a record file. Damaged bytes refuse in band."""
    try:
        with open(path, "rb") as f:
            doc = json.loads(f.read().decode("utf-8"))
    except (OSError, UnicodeDecodeError, ValueError) as exc:
        raise kernel.ClaimError(f"unreadable record {path}: {exc}") from None
    validate(doc)
    return doc


# ------------------------------------------------------------------ signing

def sign(path: str, key: str) -> str:
    """Detached ssh signature over the file's bytes, in the record namespace.

    An existing signature is replaced: the file's bytes are the authority,
    and a stale signature beside fresh bytes would verify nothing anyway.
    """
    signature = path + ".sig"
    try:
        os.remove(signature)
    except OSError:
        pass
    try:
        done = subprocess.run(
            ["ssh-keygen", "-Y", "sign", "-f", key, "-n", NAMESPACE, path],
            capture_output=True, check=False, timeout=60)
    except (OSError, subprocess.SubprocessError) as exc:
        raise kernel.ClaimError(f"cannot sign {path}: {exc}") from None
    if done.returncode != 0 or not os.path.isfile(signature):
        why = (done.stderr or done.stdout or b"").decode("utf-8", "replace")
        raise kernel.ClaimError(f"signing failed for {path}: {why.strip()[-300:]}")
    return signature


def signer(path: str, anchor: str):
    """Who, per this anchor, signed the record -- or None.

    Trust is verifier-relative: the answer depends on the allowed_signers
    file the caller names, and a record signed by a key the anchor does not
    hold is a document, not evidence. Verification is tried against every
    principal the anchor lists; the namespace must be the record's own, so an
    attestation or a mint signature over the same bytes answers None.
    """
    signature = path + ".sig"
    if not os.path.isfile(signature) or not os.path.isfile(anchor):
        return None
    try:
        with open(path, "rb") as f:
            payload = f.read()
        with open(anchor, encoding="utf-8") as f:
            lines = f.read().splitlines()
    except (OSError, UnicodeDecodeError):
        return None
    principals = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        for name in line.split()[0].split(","):
            if name and name not in principals:
                principals.append(name)
    for principal in principals:
        try:
            done = subprocess.run(
                ["ssh-keygen", "-Y", "verify", "-f", anchor, "-I", principal,
                 "-n", NAMESPACE, "-s", signature],
                input=payload, capture_output=True, check=False, timeout=60)
        except (OSError, subprocess.SubprocessError):
            return None
        if done.returncode == 0:
            return principal
    return None
