"""Skipping work already done here, without ever trusting a stored verdict.

The kernel does not memoize: `audit` re-runs the gates, always. That is not an
oversight to be optimized away -- a stored "it passed" is exactly the testimony
this whole system exists to replace, and a kernel that believed one would be
believing the thing it was built to check.

But *this machine* re-running *identical work* it has already done is a
different proposition, and content addressing makes it checkable. This module
is that, kept deliberately OUTSIDE the kernel and OFF by default, so the
kernel's guarantee stays unconditional and the shortcut is something a user
asks for by name.

THE KEY IS NOT THE ROOT. A root deliberately excludes the implementation, so
two different programs share one -- that is the entire point of the format.
Reusing on the root alone would skip a gate for bytes that had never been run.
The key is therefore:

    root            the claim: criteria, fixtures, recipe
    build digest    the concrete generated bytes now present
    platform        darwin/linux, and the sandbox actually applied
    interpreter     the running python

Change any of those and the entry does not match, so the work is done again.

What this still cannot see: a gate that reaches outside the sandbox -- the
clock, the network, a file elsewhere on the host. Such a gate is not a pure
function of the claim, and reuse would hide that. Hence opt-in, hence reported
as `reused` and never as `earned`, and hence a record of when the work was
really done so a reader can judge for themselves.
"""
from __future__ import annotations

import hashlib
import json
import os
import platform
import sys
import time

from . import kernel

CACHE_ENV = "RETICULI_CACHE"


def cache_dir() -> str:
    """Where earned verdicts are remembered for this user."""
    override = os.environ.get(CACHE_ENV)
    if override:
        return override
    base = os.environ.get("XDG_CACHE_HOME") or os.path.join(
        os.path.expanduser("~"), ".cache")
    return os.path.join(base, "reticuli", "earned")


def fingerprint(claimdir: str) -> dict:
    """Everything that would have to be identical for a re-run to be a no-op."""
    recipe = kernel.load_recipe(claimdir)
    return {
        "root": kernel.root(recipe, claimdir),
        "build": kernel.build_digest(claimdir),
        "platform": sys.platform,
        "machine": platform.machine(),
        "python": platform.python_version(),
        "sandbox": kernel.sandbox_backend() if hasattr(kernel, "sandbox_backend") else None,
    }


def _path(fp: dict) -> str:
    digest = hashlib.sha256(
        json.dumps(fp, sort_keys=True).encode("utf-8")).hexdigest()
    return os.path.join(cache_dir(), digest + ".json")


def lookup(claimdir: str) -> dict | None:
    """A previous local run of exactly this work, or None."""
    try:
        fp = fingerprint(claimdir)
    except kernel.ClaimError:
        return None
    try:
        with open(_path(fp), encoding="utf-8") as f:
            entry = json.load(f)
    except (OSError, ValueError):
        return None
    if not isinstance(entry, dict) or entry.get("fingerprint") != fp:
        return None                      # a hash collision, or a stale format
    return entry


def remember(claimdir: str, verdict: dict) -> None:
    """Record that this exact work was earned here. Only ever records a PASS:
    a failure is cheap to reproduce and often environmental, and nobody should
    have a stale 'it was broken' skip a run that would now succeed."""
    if not verdict.get("ok"):
        return
    try:
        fp = fingerprint(claimdir)
    except kernel.ClaimError:
        return
    path = _path(fp)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    payload = {"fingerprint": fp,
               "earned": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
               "gates": [{"output": g.get("output"), "status": g.get("status")}
                         for g in verdict.get("gates", [])]}
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(payload, f, sort_keys=True, indent=2)
    os.replace(tmp, path)
