"""Skipping work already done here, without ever trusting a stored verdict.

The kernel does not memoize: `audit` re-runs the gates, always. That is not an
oversight to be optimized away -- a stored "it passed" is exactly the testimony
this whole system exists to replace, and a kernel that believed one would be
believing the thing it was built to check.

But *this machine* re-running *identical work* it has already done is a
different proposition, and content addressing makes it checkable. This module
is that, kept deliberately OUTSIDE the kernel and OFF by default, so the
kernel's guarantee stays unconditional and the shortcut is something a user
asks for by name.

THE KEY IS NOT THE ROOT. A root deliberately excludes the implementation, so
two different programs share one -- that is the entire point of the format.
Reusing on the root alone would skip a gate for bytes that had never been run.
The key is therefore:

    root            the claim: criteria, fixtures, recipe
    build digest    the concrete generated bytes now present
    platform        darwin/linux, and the sandbox actually applied
    interpreter     the running python

Change any of those and the entry does not match, so the work is done again.

What this still cannot see: a gate that reaches outside the sandbox -- the
clock, the network, a file elsewhere on the host. Such a gate is not a pure
function of the claim, and reuse would hide that. Hence opt-in, hence reported
as `reused` and never as `earned`, and hence a record of when the work was
really done so a reader can judge for themselves.
"""
from __future__ import annotations

import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile
import time

from . import kernel

CACHE_ENV = "RETICULI_CACHE"


def cache_dir() -> str:
    """Where earned verdicts are remembered for this user."""
    override = os.environ.get(CACHE_ENV)
    if override:
        return override
    base = os.environ.get("XDG_CACHE_HOME") or os.path.join(
        os.path.expanduser("~"), ".cache")
    return os.path.join(base, "reticuli", "earned")


def fingerprint(claimdir: str) -> dict:
    """Everything that would have to be identical for a re-run to be a no-op."""
    recipe = kernel.load_recipe(claimdir)
    return {
        "root": kernel.root(recipe, claimdir),
        "build": kernel.build_digest(claimdir),
        "platform": sys.platform,
        "machine": platform.machine(),
        "python": platform.python_version(),
        "sandbox": kernel.sandbox_backend() if hasattr(kernel, "sandbox_backend") else None,
    }


def _path(fp: dict) -> str:
    digest = hashlib.sha256(
        json.dumps(fp, sort_keys=True).encode("utf-8")).hexdigest()
    return os.path.join(cache_dir(), digest + ".json")


def _lookup_fp(fp: dict) -> dict | None:
    """The earned entry for an exact fingerprint, or None."""
    try:
        with open(_path(fp), encoding="utf-8") as f:
            entry = json.load(f)
    except (OSError, ValueError):
        return None
    if not isinstance(entry, dict) or entry.get("fingerprint") != fp:
        return None                      # a hash collision, or a stale format
    return entry


def _remember_fp(fp: dict, verdict: dict) -> None:
    """Record a PASS for an exact fingerprint. Only a pass: a failure is cheap
    to reproduce and often environmental, and nobody should have a stale 'it
    was broken' skip a run that would now succeed."""
    if not verdict.get("ok"):
        return
    path = _path(fp)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    payload = {"fingerprint": fp,
               "earned": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
               "gates": [{"output": g.get("output"), "status": g.get("status")}
                         for g in verdict.get("gates", [])]}
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(payload, f, sort_keys=True, indent=2)
    os.replace(tmp, path)


def lookup(claimdir: str) -> dict | None:
    """A previous local run of exactly this work, or None."""
    try:
        return _lookup_fp(fingerprint(claimdir))
    except kernel.ClaimError:
        return None


def remember(claimdir: str, verdict: dict) -> None:
    """Record that this exact work was earned here."""
    try:
        _remember_fp(fingerprint(claimdir), verdict)
    except kernel.ClaimError:
        return


def _supplied_digest(supplied: dict) -> str:
    """Hash of the bytes a dependent ships for a component's outputs — the
    implementation actually under test when the component is re-earned with
    those bytes substituted."""
    h = hashlib.sha256()
    for name in sorted(supplied):
        h.update(name.encode("utf-8") + b"\0")
        with open(supplied[name], "rb") as f:
            h.update(f.read())
        h.update(b"\0")
    return h.hexdigest()


def component_fingerprint(claimdir: str, supplied: dict) -> dict:
    """Like `fingerprint`, but keyed on the SUBSTITUTED bytes a dependent
    ships for this component, not the component's own sealed bytes — the
    verdict being cached is 'these shipped bytes pass this component's gate
    here'."""
    recipe = kernel.load_recipe(claimdir)
    return {
        "root": kernel.root(recipe, claimdir),
        "build": _supplied_digest(supplied),
        "platform": sys.platform,
        "machine": platform.machine(),
        "python": platform.python_version(),
        "sandbox": kernel.sandbox_backend() if hasattr(kernel, "sandbox_backend") else None,
    }


def reusing_auditor(policy: str = "self"):
    """An auditor for `registry.audit_deep` that skips a component already
    earned on this machine. On a hit it returns a verdict marked `reused`
    (never `earned`); on a miss it re-earns cold through `kernel.audit` and
    records the result. Trust is `self` — this machine's own past earns; the
    shared, cross-signer policies (signed, quorum) are the next increment and
    are deliberately not yet offered, so a hit never rests on trust this
    machine did not itself establish.

    The policy rides in the returned verdict so a caller can echo it: a
    cheaper audit is a louder statement about whose word it stands on, never
    a quieter one."""
    if policy != "self":
        raise kernel.ClaimError(
            f"reuse policy {policy!r} not available yet; only 'self' "
            "(this machine's own earns) is implemented")

    def auditor(claimdir: str, produce_from=None, strict: bool = False) -> dict:
        supplied = produce_from or {}
        try:
            fp = component_fingerprint(claimdir, supplied)
            hit = _lookup_fp(fp)
        except (kernel.ClaimError, OSError):
            hit = None
        if hit:
            return {"ok": True, "reused": hit["earned"], "claim_ok": True,
                    "root": kernel.read_manifest(claimdir).get("root"),
                    "recomputed": kernel.read_manifest(claimdir).get("root"),
                    "environment": [], "gates": hit["gates"], "policy": policy}
        verdict = kernel.audit(claimdir, produce_from=produce_from, strict=strict)
        try:
            _remember_fp(component_fingerprint(claimdir, supplied), verdict)
        except (kernel.ClaimError, OSError):
            pass
        return verdict

    return auditor


def _layer_fingerprint(layer: dict) -> dict:
    """Content key for one layer: the bytes of its check and of every file
    it is judged against, plus this host. Same inputs → same key → a reuse;
    change any byte of check or judged file → a new key → the work is redone.
    No root: a layer here is a check over a file set, not a sealed claim."""
    h = hashlib.sha256()
    with open(layer["check"][1], "rb") as f:
        h.update(b"check\0" + f.read() + b"\0")
    for room_rel in sorted(layer["files"]):
        h.update(room_rel.encode("utf-8") + b"\0")
        with open(layer["files"][room_rel], "rb") as f:
            h.update(f.read())
        h.update(b"\0")
    return {
        "layer": layer["name"],
        "build": h.hexdigest(),
        "platform": sys.platform,
        "machine": platform.machine(),
        "python": platform.python_version(),
        "sandbox": kernel.sandbox_backend() if hasattr(kernel, "sandbox_backend") else None,
    }


def layered_audit(layers: list, strict: bool = False, reuse: bool = True,
                  timeout: float = 1800.0, progress=None) -> dict:
    """Audit a layered project by re-earning each layer's check against the
    bytes it judges, paying only for what changed.

    A layer is ``{"name", "files": {room_path: source_path, ...},
    "check": (room_path, source_path), "gate": command, "verdict": name}``.
    Each layer is staged in its own room (its judged files and its check),
    and the gate command is run there with the room on ``PYTHONPATH`` — the
    same plain run the repository gate gives each criterion, the one
    difference being that a layer already earned on this host (same check,
    same judged bytes) is skipped and reported ``reused`` rather than
    ``earned``. A failed layer stops the audit, as a failed gate stops the
    gate run.

    This is the audit-side twin of the reuse primitive: the kernel still
    never trusts a stored verdict, and this is opt-in (``reuse=False`` earns
    every layer cold). Trust is this host's own earns only — the shared,
    cross-signer cache is a later increment."""
    rows: list[dict] = []
    ok = True
    scratch = tempfile.mkdtemp(prefix="reticuli-layered-")
    try:
        for index, layer in enumerate(layers, 1):
            if progress is not None:
                progress(index, len(layers), layer["name"])
            fp = _layer_fingerprint(layer)
            hit = _lookup_fp(fp) if reuse else None
            if hit:
                rows.append({"name": layer["name"], "status": "reused",
                             "reused": hit["earned"], "seconds": 0.0})
                continue
            room = os.path.join(scratch, layer["name"].replace("/", "_"))
            for room_rel, src in layer["files"].items():
                dst = os.path.join(room, room_rel)
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copyfile(src, dst)
            check_rel, check_src = layer["check"]
            cdst = os.path.join(room, check_rel)
            os.makedirs(os.path.dirname(cdst), exist_ok=True)
            shutil.copyfile(check_src, cdst)
            env = dict(os.environ, PYTHONPATH=room, NO_COLOR="1",
                       PYTHONDONTWRITEBYTECODE="1")
            started = time.time()
            try:
                r = subprocess.run(layer["gate"], shell=True, cwd=room, env=env,
                                   capture_output=True, text=True,
                                   timeout=timeout, check=False)
                passed = r.returncode == 0
                tail = (r.stderr or r.stdout or "").strip().splitlines()[-1:]
                detail = "" if passed else (tail[0][:200] if tail else "")
            except subprocess.TimeoutExpired:
                passed, detail = False, "timeout"
            seconds = round(time.time() - started, 2)
            row = {"name": layer["name"],
                   "status": "earned" if passed else "failed",
                   "seconds": seconds}
            if not passed:
                row["detail"] = detail
            rows.append(row)
            if passed and reuse:
                _remember_fp(fp, {"ok": True,
                                  "gates": [{"output": layer.get("verdict"),
                                             "status": "ok"}]})
            if not passed:
                ok = False
                break
        return {"ok": ok, "layers": rows}
    finally:
        shutil.rmtree(scratch, ignore_errors=True)
