"""Portability: pack a claim into a deterministic tar, and unpack it back.

The tar is byte-deterministic (mtime 0, uid/gid 0, sorted) so the same claim
exports to the same bytes. Import unpacks into a fresh directory and verifies —
the claim travels by content and re-derives its own root, exactly like a
git-cloned claim.
"""
from __future__ import annotations

import io
import os
import sys
import tarfile

from . import kernel
from ._util import declared_inputs


def export(d: str, tar_path: str, blind: bool = False) -> dict:
    """Deterministic tar of THE CLAIM — its declared content only: recipe,
    manifest, pinned inputs, produce and gate outputs, and attestations.
    Neighbors in the working tree (git history, environments, residue) never leak
    into the tar, and volatile history (the trace, the cost ledger) stays home —
    identity travels, events don't.

    `blind` exports the rebuilder's room instead: the same claim minus its
    generated outputs and minus signing residue — criteria, pinned verdicts,
    and the manifest naming the root a rebuild must land on. The identity
    travels whole either way, because the root never covered the
    implementation; what a blind tar withholds is exactly what a producer is
    asked to regrow.

    A blind tar carries the recipe the SAME way the kernel's blind rebuild
    room does (`build._materialize`): at format 3+ it is rewritten from the
    parsed tables with producer guidance stripped — guidance is outside the
    root, so the room still re-derives it — and at formats 1 and 2 the file
    travels whole, because there guidance is identity. One name, one room:
    an exported blind room and a locally materialized one expose the same
    information, or experiments run against the two are not comparable."""
    from . import registry
    from .attest import ATTEST

    d = os.path.abspath(d)
    if registry._phase(d) == "draft":
        raise kernel.ClaimError(f"no claim in {d} (pack first)")
    recipe = kernel.load_recipe(d)
    # The recipe travels under the name it actually carries. Naming it by the
    # constant would silently omit it from the tar for any claim sealed under
    # the older name, and the importer would receive a directory that is not a
    # claim at all.
    recipe_name = os.path.basename(kernel.recipe_path(d))
    strip = blind and kernel._claim_format(recipe) >= 3
    rels = ([] if strip else [recipe_name]) + [kernel.MANIFEST]
    rels += declared_inputs(recipe)
    rels += [s["output"] for s in recipe.get("step", [])
             if not (blind and s.get("class") == "generated")]
    # signed residue about the claim travels with it: attestations and the
    # signing ceremony's statements. The directory names come from the layer
    # that owns them, never from a literal here — spec/verification.md leaves
    # the concrete filenames implementation-defined. A blind room carries
    # neither: signatures bind builds, and the room has none.
    if not blind:
        for box_rel in (ATTEST, kernel.SIGN_DIR):
            box = os.path.join(d, box_rel)
            if os.path.isdir(box):
                rels += [os.path.join(box_rel, f) for f in sorted(os.listdir(box))]
    members = []
    if strip:
        # the preimage recipe, exactly as a blind rebuild room receives it:
        # parsed tables, guidance stripped. Same root — guidance is outside
        # the format-3 preimage — but no producer words in the room.
        members.append((recipe_name,
                        kernel._dump_recipe(
                            kernel._preimage_recipe(recipe)).encode("utf-8")))
    for rel in sorted(set(rels)):
        full = os.path.join(d, rel)
        if os.path.isfile(full):
            members.append((rel.replace(os.sep, "/"), full))
    # a composed claim travels with its component CLAIMS — each layer's recipe,
    # manifest, inputs, and pinned verdicts under .reticuli/deps/<name>/ — never
    # their generated bytes (the dependent's stand in). Identity travels; so the
    # importer can re-earn every layer's verdict on the bytes it received.
    for c in registry.chain(d):
        if not c["path"]:
            raise kernel.ClaimError(
                f"export: component {c['name']}@{c['root'][:12]}… is not in the registry")
        cr = kernel.load_recipe(c["path"])
        c_recipe = os.path.basename(kernel.recipe_path(c["path"]))
        c_strip = blind and kernel._claim_format(cr) >= 3
        crels = ([] if c_strip else [c_recipe]) + [kernel.MANIFEST]
        crels += declared_inputs(cr)
        crels += [s["output"] for s in cr.get("step", [])
                  if s.get("class", "pinned") != "generated"]
        if c_strip:
            # same rule as the top claim: a component's recipe travels
            # guidance-stripped in a blind tar when its format allows it
            members.append(("/".join([kernel.STORE, registry.DEPS, c["name"],
                                      c_recipe]),
                            kernel._dump_recipe(
                                kernel._preimage_recipe(cr)).encode("utf-8")))
        for rel in sorted(set(crels)):
            full = os.path.join(c["path"], rel)
            if os.path.isfile(full):
                members.append(("/".join([kernel.STORE, registry.DEPS, c["name"],
                                          rel.replace(os.sep, "/")]), full))
    members.sort()
    def _fill(tar) -> None:
        for rel, src in members:
            info = tarfile.TarInfo(rel)
            info.mtime = 0
            info.uid = info.gid = 0
            info.uname = info.gname = ""
            info.mode = 0o644
            if isinstance(src, bytes):
                info.size = len(src)
                tar.addfile(info, io.BytesIO(src))
            else:
                info.size = os.path.getsize(src)
                with open(src, "rb") as fh:
                    tar.addfile(info, fh)

    # `-` is the standard stream, the tar idiom itself: `ret export -o - | ...`
    if tar_path == "-":
        with tarfile.open(fileobj=sys.stdout.buffer, mode="w|") as tar:
            _fill(tar)
    else:
        with tarfile.open(tar_path, "w") as tar:
            _fill(tar)
    return {"ok": True, "tar": tar_path, "members": len(members), "blind": blind}


def _extract(tar, into: str) -> None:
    """Members are untrusted: files only, no absolute names, no `..`."""
    for m in tar:
        name = m.name.replace("\\", "/")
        parts = name.split("/")
        if not m.isfile() or name.startswith("/") or ".." in parts:
            raise kernel.ClaimError(f"import: unsafe member: {name}")
        src = tar.extractfile(m)
        if src is None:
            continue
        dst = os.path.join(into, *parts)
        os.makedirs(os.path.dirname(dst) or into, exist_ok=True)
        with open(dst, "wb") as f:
            f.write(src.read())


def import_(tar_path: str, into: str) -> dict:
    """Unpack a claim into a fresh directory and verify it."""
    into = os.path.abspath(into)
    if os.path.exists(into):
        raise kernel.ClaimError(f"import: target exists: {into}")
    # the archive is untrusted input: a missing or non-tar file is a refusal
    # with a reason, never a raw crash. `-` reads the standard stream.
    if tar_path == "-":
        os.makedirs(into)
        try:
            with tarfile.open(fileobj=sys.stdin.buffer, mode="r|*") as tar:
                _extract(tar, into)
        except tarfile.TarError as e:
            raise kernel.ClaimError(f"import: stdin is not a readable archive ({e})") from None
    else:
        try:
            with tarfile.open(tar_path, "r"):
                pass
        except FileNotFoundError:
            raise kernel.ClaimError(f"import: no archive at {tar_path}") from None
        except (OSError, tarfile.TarError) as e:
            raise kernel.ClaimError(
                f"import: not a readable archive: {tar_path} ({e})") from None
        os.makedirs(into)
        with tarfile.open(tar_path, "r") as tar:
            _extract(tar, into)
    v = kernel.verify(into)
    return {"ok": v["ok"], "into": into, "root": v["root"],
            "verdict": "fresh" if v["ok"] else "broken"}
