"""Audit: deep re-earning, earned versus carried (spec/verification.md).

`audit` deletes nothing but trusts nothing. It recomputes the root from the
bytes present (a tampered pinned input refuses before any gate runs), then
materializes a fresh room -- pinned inputs and present generated bytes only,
never a previously earned gate verdict -- and re-runs every gate there, cold
and sandboxed. A gate's output is **reproduced** only when it byte-matches
what is pinned in the claim directory; anything else is a broken claim, not
a verdict carried from the past. Composed claims (`.reticuli/manifest.json`
`components`) audit recursively unless `shallow=True`.

When a `producer` is supplied, `audit` regrows each `produce` step's output
in the room first -- the producer's guidance travels over the environment
(`RETICULI_REQUEST`), never through the room's recipe, so it cannot decide
acceptance (spec/identity.md, "Format 3"). With no producer, the bytes
already present in the claim stand as the candidate.

Stdlib only.
"""
import json
import os
import shutil
import subprocess
import tempfile

from . import core, identity, recipe, run, seal

# --- room recipe: a minimal TOML writer for the one shape load_recipe reads


def _toml_string(s: str) -> str:
    escaped = (
        s.replace("\\", "\\\\").replace('"', '\\"')
        .replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    )
    return f'"{escaped}"'


def _toml_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, str):
        return _toml_string(v)
    if isinstance(v, list):
        return "[" + ", ".join(_toml_value(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{k} = {_toml_value(x)}" for k, x in v.items()) + " }"
    raise core.ClaimError(f"cannot serialize {v!r} into a room recipe")


def _dump_recipe_toml(doc: dict) -> str:
    """The `[claim]` table and `[[step]]` array -- the one shape `load_recipe`
    ever parses back."""
    lines = ["[claim]"]
    for k, v in doc.get("claim", {}).items():
        lines.append(f"{k} = {_toml_value(v)}")
    for step in doc.get("step", []):
        lines.append("")
        lines.append("[[step]]")
        for k, v in step.items():
            lines.append(f"{k} = {_toml_value(v)}")
    return "\n".join(lines) + "\n"


def _write_room_recipe(parsed: dict, src: str, into: str) -> None:
    """Write the room's recipe: guidance-stripped at format >= 3 -- exactly
    the recipe serialized into the root's preimage (spec/identity.md) -- or
    byte-for-byte at formats 1/2, whose roots cover the whole recipe file."""
    fmt = parsed["claim"].get("format", 1)
    dest = os.path.join(into, core.RECIPE)
    if fmt >= 3:
        with open(dest, "w", encoding="utf-8") as f:
            f.write(_dump_recipe_toml(identity._preimage_recipe(parsed)))
        return
    with open(recipe.recipe_path(src), "rb") as f:
        raw = f.read()
    with open(dest, "wb") as f:
        f.write(raw)


def _step_guidance(step: dict):
    """A produce step's guidance, under either spelling (spec/claim-format.md).

    `None` when the step carries neither key.
    """
    for key in core.GUIDANCE_KEYS:
        value = step.get(key)
        if value is not None:
            return value
    return None


def _materialize(parsed: dict, src: str, into: str, *, include_generated: bool = True) -> None:
    """Build a fresh room at `into`: pinned inputs, present generated bytes,
    and the room recipe -- never a previously earned gate verdict, so a
    gate must re-earn its own output rather than have it carried in."""
    os.makedirs(into, exist_ok=True)
    for path in recipe._inputs(parsed):
        core._copy_into(os.path.join(src, path), os.path.join(into, path))
    if include_generated:
        for path in recipe.generated_outputs(parsed):
            source_path = os.path.join(src, path)
            if os.path.isfile(source_path):
                core._copy_into(source_path, os.path.join(into, path))
    _write_room_recipe(parsed, src, into)


def _run_producer(cmd, room: str, extra_env: dict, timeout: float) -> dict:
    backend = run.sandbox_backend()
    scratch = None
    if backend != "none":
        run_store = os.path.join(room, core.STORE, "run")
        os.makedirs(run_store, exist_ok=True)
        scratch = tempfile.mkdtemp(prefix="produce-", dir=run_store)
    try:
        env = run._scrub_env(scratch)
        env.update(extra_env)
        argv = run._sandbox_argv(backend, cmd, room, scratch)
        result = run._run(argv, cwd=room, env=env, timeout=timeout)
    finally:
        if scratch is not None:
            shutil.rmtree(scratch, ignore_errors=True)

    if result["timed_out"]:
        status = "timeout"
    elif result["returncode"] == 0:
        status = "ok"
    else:
        status = "failed"
    return {
        "status": status,
        "quarantine": backend,
        "returncode": result["returncode"],
        "stdout": result["stdout"],
        "stderr": result["stderr"],
    }


def _produce(step: dict, room: str, producer, parsed: dict, guidance=None) -> dict:
    """Invoke `producer` (a shell command) to write `step`'s output into
    `room`, confined and bounded the same way a gate runs, but on
    `core.PRODUCER_TIMEOUT` and handed the step's identity and guidance over
    the environment -- never through the room's recipe."""
    extra_env = {
        core._ENV_CLAIM: parsed["claim"]["name"],
        core._ENV_OUTPUT: step["output"],
        core._ENV_OUTPUTS: "\n".join(recipe.generated_outputs(parsed)),
    }
    if guidance is not None:
        extra_env[core._ENV_REQUEST] = guidance
    return _run_producer(producer, room, extra_env, core.PRODUCER_TIMEOUT)


def _compare_pin(produced_path: str, pinned_path: str) -> bool:
    """Byte-for-byte: does a freshly produced file match the bytes that
    entered the root at seal time?"""
    if not os.path.isfile(produced_path) or not os.path.isfile(pinned_path):
        return False
    return core._hash_file(produced_path) == core._hash_file(pinned_path)


def _read_usage(room: str) -> dict:
    """A producer's self-reported cost, from `core.USAGE` in the room.

    Only `usd`/`tokens`/`calls` are accepted from a usage payload --
    `seconds` is the kernel's own measurement and is never taken from a
    producer's report (`spec/kernel-api.md`). Malformed or missing usage is
    quietly empty, never a crash: a producer's bookkeeping is untrusted
    input, like everything else it hands back.
    """
    path = os.path.join(room, core.USAGE)
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            doc = json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(doc, dict):
        return {}
    usage = {}
    for key in ("usd", "tokens", "calls"):
        value = doc.get(key)
        if isinstance(value, (int, float)) and not isinstance(value, bool) and value >= 0:
            usage[key] = value
    return usage


def _ssh_verify(allowed_signers: str, signer: str, namespace: str, sig_path: str, data: bytes) -> bool:
    """Verify a detached `ssh-keygen -Y` signature over `data`.

    A probe, not a gate: any missing tool, missing file, or failed
    verification is `False`, never an exception.
    """
    if not run._have("ssh-keygen") or not os.path.isfile(allowed_signers) or not os.path.isfile(sig_path):
        return False
    try:
        result = subprocess.run(
            ["ssh-keygen", "-Y", "verify", "-f", allowed_signers, "-I", signer,
             "-n", namespace, "-s", sig_path],
            input=data, capture_output=True, timeout=10, check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return result.returncode == 0


def _authorized(d: str, parsed: dict, signers: str = None) -> dict:
    """Whether the generated bytes present carry a valid `SIGN_NAMESPACE`
    signature, under an anchor the caller supplies.

    Observational, like `run.independence`: a missing or unverifiable
    signature is reported, never enforced -- `audit`'s pass/fail rests on
    the root and the gates, not on who is willing to vouch for the bytes.
    Trust is verifier-relative (spec/verification.md): with no `signers`
    anchor, nothing here is authorized to *this* caller.
    """
    signers = signers or os.environ.get(core._ENV_SIGNERS)
    sign_dir = os.path.join(d, core.SIGN_DIR)
    if not signers or not os.path.isdir(sign_dir):
        return {"authorized": False, "reason": "no signer anchor configured"}
    digest = identity.build_digest(d).encode("ascii")
    for name in sorted(os.listdir(sign_dir)):
        if not name.endswith(".sign.json"):
            continue
        signer = name[: -len(".sign.json")]
        sig_path = os.path.join(sign_dir, name)
        if _ssh_verify(signers, signer, core.SIGN_NAMESPACE, sig_path, digest):
            return {"authorized": True, "signer": signer}
    return {"authorized": False, "reason": "no verifiable signature"}


def audit(d: str, producer=None, *, shallow: bool = False, signers: str = None) -> dict:
    """Re-execute every gate, cold and sandboxed; the only verb that
    re-earns a verdict (spec/verification.md).

    Refuses before running anything if the bytes present no longer recompute
    the sealed root, or if the host cannot furnish what the claim declares.
    Otherwise materializes a fresh room, regrows each `produce` step only if
    `producer` is given, and runs every gate there. A gate's status is
    `reproduced` when its output byte-matches the pinned copy in `d`,
    `mismatch` when it runs clean but differs, and the ordinary failure
    classes otherwise. Composed claims (`components` in the manifest) audit
    recursively unless `shallow`.
    """
    manifest = seal.read_manifest(d)
    parsed = recipe.load_recipe(d)
    recomputed = identity.root(parsed, d)
    if recomputed != manifest["root"]:
        return {
            "ok": False, "verdict": "mismatch", "name": manifest.get("name"),
            "root": manifest["root"], "recomputed": recomputed, "gates": [],
        }

    missing = run.preflight(parsed)
    if missing:
        return {
            "ok": False, "verdict": "environment", "name": manifest["name"],
            "root": manifest["root"], "missing": missing, "gates": [],
        }

    furnished = run.furnish(d, parsed)
    if not furnished["ok"]:
        return {
            "ok": False, "verdict": "environment", "name": manifest["name"],
            "root": manifest["root"], "reason": furnished["reason"], "gates": [],
        }

    ok = True
    component_results = {}
    components = manifest.get("components") or {}
    if components and not shallow:
        for name, rel in components.items():
            sub = audit(os.path.join(d, rel), producer, shallow=shallow, signers=signers)
            component_results[name] = sub
            ok = ok and sub["ok"]

    store = os.path.join(d, core.STORE)
    os.makedirs(store, exist_ok=True)
    room = tempfile.mkdtemp(prefix="audit-", dir=store)
    try:
        _materialize(parsed, d, room)
        if producer is not None:
            for step in recipe.produces(parsed):
                _produce(step, room, producer, parsed, _step_guidance(step))

        gate_results = []
        for step in recipe.gates(parsed):
            result = run.run_gate(step["run"], room, parsed)
            status = result["status"]
            if status == "ok":
                out_path = os.path.join(room, step["output"])
                pinned_path = os.path.join(d, step["output"])
                status = "reproduced" if _compare_pin(out_path, pinned_path) else "mismatch"
            gate_results.append({
                "output": step["output"], "status": status, "sandbox": result["quarantine"],
            })
            if status not in ("ok", "reproduced"):
                ok = False
    finally:
        shutil.rmtree(room, ignore_errors=True)

    return {
        "ok": ok,
        "verdict": "earned" if ok else "broken",
        "name": manifest["name"],
        "root": manifest["root"],
        "gates": gate_results,
        "authorized": _authorized(d, parsed, signers),
        **({"components": component_results} if component_results else {}),
    }
