"""Identity: the root hash and the build digest (`spec/identity.md`).

A claim's root is a SHA-256 digest over what the claim *is* -- its parsed
recipe (with producer guidance stripped and, from format 4, its step list
canonicalized) and the bytes of every pinned input and non-generated step
output. It never covers the bytes of a generated output, so an
implementation can be deleted and regrown byte-different without moving the
root.

The build digest is a separate SHA-256, over the bytes of the generated
outputs actually present on disk (a `from`-sourced output excluded, since it
was not produced by this build) -- what a signature over concrete bytes
binds.

Both use the same canonical JSON: `json.dumps(x, sort_keys=True)` with every
other argument left at its default -- sorted keys, default (non-compact)
separators, ASCII escaping of everything non-ASCII, exact-decimal integers,
`repr`-shortest floats. A TOML date/time value has no such form and is
refused.

Stdlib only.
"""
import datetime
import hashlib
import json
import os

from .core import DIGEST, FORMAT, GUIDANCE_KEYS, ClaimError, _hash_file, _safe
from . import recipe as _recipe


def _canonical_json(obj) -> str:
    """The one serialization identity.md pins: sorted keys, default
    separators, ASCII-escaped, encoded as a str (callers encode to UTF-8)."""
    def _refuse(o):
        if isinstance(o, (datetime.date, datetime.time)):
            raise ClaimError(
                "TOML date/time values are refused at sealing: "
                "JSON gives them no canonical form"
            )
        raise TypeError(f"object of type {type(o).__name__} is not JSON serializable")

    return json.dumps(obj, sort_keys=True, default=_refuse)


def _sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _claim_format(parsed: dict) -> int:
    """The claim's declared format: an absent `[claim] format` means 1.

    Refuses a format newer than this kernel understands, in words.
    """
    fmt = parsed.get("claim", {}).get("format", 1)
    if isinstance(fmt, bool) or not isinstance(fmt, int) or fmt < 1:
        raise ClaimError("[claim] format must be a positive integer")
    if fmt > FORMAT:
        raise ClaimError(
            f"claim format {fmt} is newer than this kernel understands "
            f"(format {FORMAT}); upgrade reticuli to read it"
        )
    return fmt


def _preimage_recipe(parsed: dict) -> dict:
    """The recipe as it enters the root preimage: at format 3+, every
    step's guidance (`guidance` / `request`) is stripped; at format 4+, the
    step list is further sorted into the lexicographic order of each
    step's own canonical encoding, so step order is no longer identity."""
    fmt = _claim_format(parsed)
    preimage = dict(parsed)
    steps = [dict(s) for s in parsed.get("step", [])]
    if fmt >= 3:
        for step in steps:
            for key in GUIDANCE_KEYS:
                step.pop(key, None)
    if fmt >= 4:
        steps.sort(key=_canonical_json)
    preimage["step"] = steps
    return preimage


def _parts(parsed: dict, d: str) -> dict:
    """The string-to-string map the root is computed over: the algorithm
    name, the preimage recipe (serialized once, embedded as a string), and
    the hash of every pinned input and every non-generated step output."""
    parts = {"digest": DIGEST, "recipe": _canonical_json(_preimage_recipe(parsed))}

    for path in _recipe._inputs(parsed, d):
        parts[f"input:{path}"] = _hash_file(_safe(d, path))

    for step in parsed.get("step", []):
        default_class = "generated" if step.get("kind") == "produce" else "pinned"
        if step.get("class", default_class) != "generated":
            output = step["output"]
            parts[f"pinned:{output}"] = _hash_file(_safe(d, output))

    return parts


def root(parsed: dict, d: str) -> str:
    """The claim's identity: `sha256(canonical_json(_parts(parsed, d)))`."""
    return _sha256_hex(_canonical_json(_parts(parsed, d)).encode("utf-8"))


def build_digest(d: str) -> str:
    """The digest of the generated bytes present under claim directory `d`:
    sha256 of the canonical JSON of a sorted `[output, sha256(bytes)]` list,
    one entry per produce step whose class is `generated` and which has no
    `from` (a `from`-sourced output was not produced by this build). An
    output declared but absent on disk is omitted; no generated outputs at
    all gives the digest of the empty list."""
    parsed = _recipe.load_recipe(d)
    pairs = []
    for step in parsed.get("step", []):
        if step.get("kind") != "produce":
            continue
        if step.get("class", "generated") != "generated":
            continue
        if "from" in step:
            continue
        output = step["output"]
        path = _safe(d, output)
        if not os.path.exists(path):
            continue
        pairs.append([output, _hash_file(path)])
    pairs.sort()
    return _sha256_hex(_canonical_json(pairs).encode("utf-8"))
