"""Seal and verify: freezing identity onto the manifest, and confirming it.

`seal` computes a claim's root (`spec/identity.md`) and writes it, with the
claim's name, to `.reticuli/manifest.json` -- the file this layer treats as
identity. `verify` recomputes the root from the bytes present and reports
whether it still matches what was sealed: editing a generated output leaves
the root untouched, because the root preimage never covers generated bytes;
editing a pinned input or the recipe moves it. `_changed_parts` names which
root-preimage entries moved between the sealed snapshot and the bytes
present now, for a verifier that wants to say more than "mismatch".

Stdlib only.
"""
import json
import os

from .core import ClaimError, MANIFEST, STORE, _write_json
from . import identity as _identity
from . import recipe as _recipe


def _manifest_path(d: str) -> str:
    return os.path.join(d, MANIFEST)


def seal(d: str) -> dict:
    """Freeze `d` into a claim: compute the root and write the manifest.

    Refuses, as a `ClaimError`, a recipe that does not parse or validate;
    the identity computation itself refuses whatever its file-hashing and
    canonical-JSON rules reject (an unhashable file, a TOML date/time).
    """
    parsed = _recipe.load_recipe(d)
    parts = _identity._parts(parsed, d)
    r = _identity.root(parsed, d)
    manifest = {
        "name": parsed["claim"]["name"],
        "root": r,
        "parts": parts,
    }
    os.makedirs(os.path.join(d, STORE), exist_ok=True)
    _write_json(_manifest_path(d), manifest)
    return manifest


def read_manifest(d: str) -> dict:
    """Read back the manifest `seal` wrote: at minimum `{name, root}`.

    Refuses malformed bytes -- not a JSON object, or missing/wrong-shaped
    `name`/`root` -- as a `ClaimError`, never a raw parse crash.
    """
    path = _manifest_path(d)
    try:
        with open(path, "r", encoding="utf-8") as f:
            manifest = json.load(f)
    except (OSError, json.JSONDecodeError) as exc:
        raise ClaimError(f"no readable manifest at {path!r}: {exc}") from exc
    if not isinstance(manifest, dict):
        raise ClaimError(f"malformed manifest at {path!r}: not a JSON object")
    if not isinstance(manifest.get("name"), str):
        raise ClaimError(f"malformed manifest at {path!r}: missing name")
    root = manifest.get("root")
    if not isinstance(root, str) or len(root) != 64:
        raise ClaimError(f"malformed manifest at {path!r}: missing root")
    return manifest


def _changed_parts(d: str, manifest: dict) -> dict:
    """Which root-preimage entries differ between the sealed snapshot in
    `manifest` and the bytes present now under `d`: `{key: (sealed, current)}`
    for every key where the two disagree, `None` standing in for a key
    present on only one side."""
    sealed_parts = manifest.get("parts")
    parsed = _recipe.load_recipe(d)
    try:
        current_parts = _identity._parts(parsed, d)
    except ClaimError:
        current_parts = {}
    if not isinstance(sealed_parts, dict):
        return {key: (None, value) for key, value in current_parts.items()}
    changed = {}
    for key in sealed_parts.keys() | current_parts.keys():
        before = sealed_parts.get(key)
        after = current_parts.get(key)
        if before != after:
            changed[key] = (before, after)
    return changed


def verify(d: str) -> dict:
    """Recompute the root from the bytes present and compare it with the
    sealed manifest -- identity only; no gate is executed.

    `root` is the value `seal` wrote; `recomputed` is what the bytes
    present hash to now; `ok` is whether the two agree.
    """
    manifest = read_manifest(d)
    parsed = _recipe.load_recipe(d)
    recomputed = _identity.root(parsed, d)
    return {
        "ok": recomputed == manifest["root"],
        "root": manifest["root"],
        "recomputed": recomputed,
        "name": manifest["name"],
    }
