"""Host-local cache of earned verdicts and audits of ordered layers.

Cache entries are residue.  Their keys cover the concrete build as well as the
claim root and judging host; a failed verdict is never stored.
"""

from __future__ import annotations

import datetime
import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile

from . import kernel


def _canonical(value):
    return json.dumps(value, sort_keys=True).encode("utf-8")


def _cache_dir():
    return os.environ.get("RETICULI_CACHE", os.path.join(
        os.path.expanduser("~"), ".cache", "reticuli", "verdicts"))


def _host():
    return {"platform": platform.platform(), "python": sys.version}


def fingerprint(directory):
    """Identify the claim, present generated bytes, and judging host."""
    checked = kernel.verify(directory)
    if not checked["ok"]:
        raise kernel.ClaimError("claim identity mismatch")
    return {"root": checked["root"], "build": kernel.build_digest(directory),
            **_host()}


def _path(key):
    digest = hashlib.sha256(_canonical(key)).hexdigest()
    return os.path.join(_cache_dir(), digest + ".json")


def _passing(verdict):
    return (isinstance(verdict, dict) and verdict.get("ok") is True
            and isinstance(verdict.get("gates", []), list)
            and all(isinstance(row, dict) and row.get("status") == "ok"
                    for row in verdict.get("gates", [])))


def _write(key, verdict, source=None):
    if not _passing(verdict):
        return None
    path = _path(key)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    entry = {"fingerprint": key, "verdict": verdict,
             "source": source or {"when": datetime.datetime.now(
                 datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}}
    fd, temporary = tempfile.mkstemp(prefix="verdict-", dir=os.path.dirname(path))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            json.dump(entry, stream, sort_keys=True)
            stream.write("\n")
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)
    return entry


def _read(key):
    try:
        with open(_path(key), encoding="utf-8") as stream:
            entry = json.load(stream)
    except (OSError, ValueError):
        return None
    if (not isinstance(entry, dict) or entry.get("fingerprint") != key
            or not _passing(entry.get("verdict"))):
        return None
    return entry


def remember(directory, verdict):
    """Remember a passing verdict; failures leave no reusable entry."""
    return _write(fingerprint(directory), verdict)


def lookup(directory):
    """Return a matching passing verdict, or None when work must be redone."""
    entry = _read(fingerprint(directory))
    return entry["verdict"] if entry else None


def _layer_key(layer, dependency_keys):
    files = dict(layer.get("files", {}))
    check_name, check_path = layer["check"]
    files[check_name] = check_path
    hashes = {}
    for name, path in files.items():
        with open(path, "rb") as stream:
            hashes[name] = hashlib.sha256(stream.read()).hexdigest()
    return {"layer": layer["name"], "files": hashes, "gate": layer["gate"],
            "verdict": layer.get("verdict"), "dependencies": dependency_keys,
            **_host()}


def layered_audit(layers):
    """Run ordered layer gates cold, or explicitly report matching cached work.

    Each layer receives only its declared files and check.  A later layer's
    cache key includes the preceding layers' keys, so changing a foundation
    invalidates the verdicts that depended on it.
    """
    rows = []
    dependencies = []
    for layer in layers:
        key = _layer_key(layer, dependencies)
        cached = _read(key)
        if cached:
            row = {"name": layer["name"], "ok": True, "status": "reused",
                   "reused": True, "source": cached["source"]}
        else:
            with tempfile.TemporaryDirectory(prefix="reticuli-layer-") as room:
                files = dict(layer.get("files", {}))
                check_name, check_path = layer["check"]
                files[check_name] = check_path
                for name, path in files.items():
                    if (not name or os.path.isabs(name)
                            or any(part in ("", ".", "..") for part in name.split("/"))):
                        raise kernel.ClaimError(f"unsafe layer path: {name!r}")
                    destination = os.path.join(room, name)
                    os.makedirs(os.path.dirname(destination), exist_ok=True)
                    shutil.copy2(path, destination)
                try:
                    done = subprocess.run(layer["gate"], shell=True, cwd=room,
                                          capture_output=True, text=True, timeout=120)
                    ok = done.returncode == 0
                    detail = done.stderr if not ok else ""
                except subprocess.TimeoutExpired:
                    ok, detail = False, "gate timed out"
            row = {"name": layer["name"], "ok": ok,
                   "status": "earned" if ok else "failed", "reused": False}
            if detail:
                row["detail"] = detail
            if ok:
                source = {"when": datetime.datetime.now(datetime.timezone.utc).strftime(
                    "%Y-%m-%dT%H:%M:%SZ"),
                    "dependencies": [prior["name"] for prior in rows]}
                _write(key, {"ok": True, "gates": []}, source)
        rows.append(row)
        if not row["ok"]:
            return {"ok": False, "layers": rows}
        dependencies.append(hashlib.sha256(_canonical(key)).hexdigest())
    return {"ok": True, "layers": rows}
