"""A claim's identity: the root hash and the build digest (spec/identity.md).

The root is a SHA-256 over a canonical JSON map built from the recipe (with
producer guidance stripped at format 3+ and the step list canonicalized to a
set at format 4+), the claim's pinned inputs, and its pinned/validated step
outputs -- never the bytes of a `generated` output. The build digest is a
SHA-256 over the concrete bytes of the generated outputs actually present on
disk (a step with `from` is excluded; an absent output is omitted). Both use
the same canonical JSON: sorted keys, default separators, ASCII-escaped,
encoded UTF-8 -- `json.dumps(x, sort_keys=True)`.
"""
import hashlib
import json
import os
import stat

from . import core
from . import recipe as _recipe
from .core import ClaimError


def _canonical_json(obj) -> str:
    """`spec/identity.md`'s canonical serialization."""
    return json.dumps(obj, sort_keys=True)


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _hashed(d: str, path: str) -> str:
    """sha256 of a declared file's bytes; refuses anything but a regular
    file with a single hard link (spec/identity.md: file hashing rules)."""
    full = core._safe(d, path)
    try:
        st = os.stat(full, follow_symlinks=False)
    except OSError as e:
        raise ClaimError(f"cannot stat {path!r}: {e}") from e
    if not stat.S_ISREG(st.st_mode):
        raise ClaimError(f"refused {path!r}: not a regular file")
    if st.st_nlink != 1:
        raise ClaimError(f"refused {path!r}: has more than one hard link")
    return core._hash_file(full)


def _claim_format(parsed: dict) -> int:
    """The recipe's declared format; absent means 1 (spec/claim-format.md)."""
    return parsed.get("claim", {}).get("format", 1)


def _preimage_recipe(parsed: dict) -> dict:
    """The recipe exactly as it enters the root preimage: guidance stripped
    at format 3+, the step list canonicalized to a set at format 4+."""
    fmt = _claim_format(parsed)
    doc = dict(parsed)
    if "step" in doc:
        steps = [dict(s) for s in doc["step"]]
        if fmt >= 3:
            for step in steps:
                step.pop("guidance", None)
                step.pop("request", None)
        if fmt >= 4:
            steps.sort(key=_canonical_json)
        doc["step"] = steps
    return doc


def _parts(parsed: dict, d: str) -> dict:
    """The string-to-string map the root is computed from."""
    parts = {
        "digest": core.DIGEST,
        "recipe": _canonical_json(_preimage_recipe(parsed)),
    }
    for path in _recipe._inputs(d, parsed):
        parts[f"input:{path}"] = _hashed(d, path)

    for step in parsed.get("step", []):
        output = step.get("output")
        if not isinstance(output, str):
            continue
        cls = step.get("class")
        if cls is None:
            cls = "generated" if step.get("kind") == "produce" else "pinned"
        if cls == "generated":
            continue
        parts[f"pinned:{output}"] = _hashed(d, output)

    return parts


def root(recipe: dict, d: str) -> str:
    """The claim's identity: a SHA-256 over the canonical `parts` map."""
    return _sha256_text(_canonical_json(_parts(recipe, d)))


def build_digest(d: str) -> str:
    """The digest of the generated bytes present in `d`."""
    parsed = _recipe.load_recipe(d)
    entries = []
    for step in _recipe.produces(parsed):
        if step.get("class", "generated") != "generated":
            continue
        if step.get("from") is not None:
            continue
        output = step.get("output")
        full = core._safe(d, output)
        if not os.path.isfile(full):
            continue
        entries.append([output, _hashed(d, output)])
    entries.sort()
    return _sha256_text(_canonical_json(entries))
