"""Kernel core: the two boundaries and the primitives beneath everything.

The path boundary (`_safe`) refuses a name that escapes the claim directory
or crosses a symlink. The bytes boundary (`_hash_file`) is a plain sha256 of
a file's bytes. `_write_json` is an atomic, round-tripping JSON write. The
rest of this module is the protocol vocabulary every higher layer imports by
name: the on-disk/environment contract (`spec/claim-format.md`,
`spec/kernel-api.md`) and the refusal type every kernel error is raised as.

Stdlib only, never the network.
"""
import datetime
import hashlib
import json
import os
import platform
import shutil
import sys
import tempfile

# -- the on-disk / environment contract (shared verbatim with higher layers
# and with the record format) --------------------------------------------
NAMESPACE = "reticuli"
DIGEST = "sha256"
FORMAT = 4
STORE = ".reticuli"
MANIFEST = ".reticuli/manifest.json"
RECIPE = "reticuli.toml"
LEGACY_RECIPE = "claim.toml"
LEDGER = ".reticuli/ledger.jsonl"
USAGE = ".reticuli/usage.json"
MUTATION_RESIDUE = ".reticuli/mutation_score.json"
SIGN_DIR = ".reticuli/mint"
SIGN_NAMESPACE = "reticuli.mint"

_JAILED = "RETICULI_JAILED"
_ENV_CACHE = "RETICULI_ENV_CACHE"
_ENV_CLAIM = "RETICULI_CLAIM"
_ENV_MODEL = "RETICULI_MODEL"
_ENV_OUTPUT = "RETICULI_OUTPUT"
_ENV_OUTPUTS = "RETICULI_OUTPUTS"
_ENV_REQUEST = "RETICULI_REQUEST"
_ENV_SIGNERS = "RETICULI_SIGNERS"
_ENV_TIMEOUT = "RETICULI_GATE_TIMEOUT"
_ENV_TOLERANCE = "RETICULI_TOLERANCE"
_ENV_USAGE = "RETICULI_USAGE"
_ENV_VENDOR = "RETICULI_VENDOR"
_KEEP_ENV = ("PATH", "HOME", "TMPDIR", "LANG", "LC_ALL", "TZ", "RETICULI_JAILED")

# -- tuning constants and host-derived values -----------------------------
GATE_TIMEOUT = 120.0
FURNISH_TIMEOUT = 300.0
PRODUCER_TIMEOUT = 900.0
TOLERANCE = 2.0
MUTANT_CEILING = 64.0
MUTANT_FLOOR = 8.0
MUTANT_HEADROOM = 1.25
COST_KEYS = ("usd", "tokens", "calls", "seconds")
COST_LADDER = ("usd", "tokens", "calls", "seconds")
COST_UNITS = ("usd", "tokens", "calls", "seconds")
GUIDANCE_KEYS = ("guidance", "request")
KINDS = frozenset({"produce", "gate"})
_SHELL = "/bin/sh"


class ClaimError(Exception):
    """A refusal with a reason -- the only error this kernel raises."""


def _safe(base: str, name: str) -> str:
    """Resolve `name` as a path inside `base`; refuse any escape.

    Refused: an empty name, an absolute path, a `..` component, and any
    component that is a symlink -- even one whose target stays inside the
    claim, which could alias generated bytes as a pinned name.
    """
    if not name:
        raise ClaimError("empty path refused")
    if os.path.isabs(name):
        raise ClaimError(f"absolute path refused: {name!r}")
    parts = name.split("/")
    if any(part in ("", ".", "..") for part in parts):
        raise ClaimError(f"path escapes the claim: {name!r}")

    base_real = os.path.realpath(base)
    cur = base_real
    for part in parts:
        cur = os.path.join(cur, part)
        if os.path.islink(cur):
            raise ClaimError(f"symlink component refused: {name!r}")

    resolved = os.path.realpath(cur)
    if resolved != base_real and not resolved.startswith(base_real + os.sep):
        raise ClaimError(f"path escapes the claim: {name!r}")
    return resolved


def _hash_file(path: str) -> str:
    """The bytes boundary: a plain sha256 of the file's bytes."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _write_json(path: str, obj) -> None:
    """Write `obj` as JSON atomically: a temp file, then a rename."""
    d = os.path.dirname(path) or "."
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".tmp-", suffix=".json")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(obj, f, sort_keys=True)
        os.replace(tmp, path)
    except Exception:
        try:
            os.remove(tmp)
        except OSError:
            pass
        raise


def _now() -> str:
    """UTC time of recording, `YYYY-MM-DDTHH:MM:SSZ` (`spec/record.md`)."""
    return datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ")


def _copy_into(src_dir: str, dst_dir: str, names) -> None:
    """Copy each pinned name from `src_dir` into `dst_dir`, via `_safe`."""
    for name in names:
        s = _safe(src_dir, name)
        d = _safe(dst_dir, name)
        os.makedirs(os.path.dirname(d), exist_ok=True)
        shutil.copy2(s, d)


def _judging_host() -> dict:
    """`environment` for a record: `platform`, `machine`, `runtime`."""
    return {
        "platform": sys.platform,
        "machine": platform.machine(),
        "runtime": f"{platform.python_implementation()} "
                   f"{platform.python_version()}",
    }
