"""Crosscheck: rebuild, audit, the three-machine test, and their helpers.

This module assembles the public verbs that compose the primitives in the
sibling modules (`core`, `recipe`, `identity`, `seal`, `run`, `build`,
`attest`) into the full kernel surface: `rebuild` (regrow generated outputs
until the gates pass, with a scrubbed producer environment and a snapshot
that refuses a producer that rewrites pinned bytes or the recipe), `audit`
(re-earn every gate cold, judging a format-3+ claim against the same
guidance-stripped recipe the room would see), `crosscheck` (the three-machine
test, over directories or frozen records interchangeably), `phase` (the
signature state machine), `sign_node` (the bottom-anchored signature fold),
`mutation_score` (deterministic mutants of the generated code, drawn from the
root), `vacuous_gates` / `gate_deciders` (which files a gate's run line
actually reads), and the record-transport functions re-specified to cover
the version-2 declared-obligations extension the lower `attest` module does
not yet implement.

Stdlib only, never the network.
"""
import ast
import contextlib
import hashlib
import json
import os
import platform
import random
import re
import shlex
import shutil
import subprocess
import sys
import time
import tomllib

from . import attest, build, core, identity, recipe, run, seal as _seal_mod
from .core import ClaimError

# == interchange / interop constants shared with higher layers ==============
RECORD_NAMESPACE = attest.RECORD_NAMESPACE
RECORD_FORMAT = 2   # this module understands record versions 1 and 2


# =============================================================================
# seal: sealing never hashes generated bytes, so a generated output that
# happens to be a symlink must not block it -- only `recipe.load_recipe`
# (given, applies the path-safety boundary to every declared output
# regardless of class) would otherwise refuse the whole recipe at parse
# time. Hide any such symlink for the DURATION of the parse that sealing
# needs; `audit` (which actually reads/copies the output) is given no such
# accommodation and refuses it, per spec.
# =============================================================================

def _probe_generated_outputs(d: str) -> list:
    try:
        path = recipe.recipe_path(d)
    except ClaimError:
        return []
    try:
        with open(path, "rb") as f:
            doc = tomllib.load(f)
    except Exception:
        return []
    claim = doc.get("claim")
    if not isinstance(claim, dict):
        return []
    outs = []
    for step in doc.get("step", []) or []:
        if not isinstance(step, dict) or step.get("kind") != "produce":
            continue
        if step.get("class", "generated") == "generated":
            out = step.get("output")
            if isinstance(out, str):
                outs.append(out)
    return outs


@contextlib.contextmanager
def _hide_generated_symlinks(d: str):
    hidden = []
    for name in _probe_generated_outputs(d):
        path = os.path.join(d, name)
        if os.path.islink(path):
            tmp = path + ".reticuli-hidden"
            os.rename(path, tmp)
            hidden.append((path, tmp))
    try:
        yield
    finally:
        for path, tmp in hidden:
            os.rename(tmp, path)


# =============================================================================
# the file boundary, enforced on every path `root()` touches: a hashed file
# must be a regular file with a single hard link (spec/identity.md). `core.
# _safe` already refuses an escaping or symlinked path; this adds the checks
# a path check cannot see -- hardlinks to an outside inode, FIFOs, devices.
# =============================================================================

def _check_file_boundary(d: str, name: str) -> str:
    path = core._safe(d, name)
    try:
        st = os.lstat(path)
    except OSError as e:
        raise ClaimError(f"cannot stat {name!r}: {e}") from e
    if not os.path.isfile(path):
        raise ClaimError(f"{name!r} is not a regular file")
    if st.st_nlink != 1:
        raise ClaimError(f"{name!r} has more than one hard link; refused")
    return path


def _full_parts(parsed: dict, d: str) -> dict:
    """The root preimage, boundary-checked, with the declared `[claim]
    environment` file counted as an automatically pinned input
    (`spec/claim-format.md`) -- `identity._parts` (given) does not know
    about it, so it is added here, on top of the same `_parts` map, rather
    than by rewriting the recipe's own declared `inputs`. Shared by `root`
    and `seal` so a sealed manifest and a later `verify` agree."""
    for path in recipe._inputs(d, parsed):
        _check_file_boundary(d, path)
    for step in recipe._steps(parsed):
        cls = step.get("class", recipe._default_class(step))
        if cls != "generated":
            _check_file_boundary(d, step["output"])
    parts = identity._parts(parsed, d)
    env_file = parsed.get("claim", {}).get("environment")
    if env_file is not None:
        env_path = _check_file_boundary(d, env_file)
        parts[f"input:{env_file}"] = core._hash_file(env_path)
    return parts


def root(parsed: dict, d: str) -> str:
    """The claim's identity, with the filesystem-aliasing boundary enforced."""
    try:
        parts = _full_parts(parsed, d)
        return identity._sha256_text(identity._canonical_json(parts))
    except ClaimError:
        raise
    except Exception as e:
        raise ClaimError(str(e)) from e


def seal(d: str, **kwargs) -> dict:
    try:
        with _hide_generated_symlinks(d):
            parsed = load_recipe(d)
            name = parsed["claim"]["name"]
            parts = _full_parts(parsed, d)
            root_value = identity._sha256_text(identity._canonical_json(parts))
            manifest = {"name": name, "root": root_value, "parts": parts}
            os.makedirs(os.path.join(d, core.STORE), exist_ok=True)
            core._write_json(os.path.join(d, core.MANIFEST), manifest)
            return manifest
    except ClaimError:
        raise
    except Exception as e:
        raise ClaimError(str(e)) from e


build_digest = identity.build_digest


def load_recipe(d: str) -> dict:
    """`recipe.load_recipe` plus the `[claim]` fields it does not validate:
    `envelope`, `tolerance`, `mutation_floor` -- the same obligations a
    record's `claim` member relays and validates on the other transport."""
    parsed = recipe.load_recipe(d)
    claim = parsed.get("claim", {})
    for key in ("tolerance", "mutation_floor"):
        if key in claim:
            _validate_nonneg_number(claim[key], f"[claim] {key}")
    if "envelope" in claim:
        _validate_envelope(claim["envelope"], "[claim] envelope")
    return parsed


# =============================================================================
# verify / phase: robust wrappers -- a damaged or incomplete claim refuses in
# band (ClaimError), never crashes raw and never answers a positive verdict
# about wreckage it cannot parse.
# =============================================================================

def verify(d: str) -> dict:
    try:
        manifest = _seal_mod.read_manifest(d)
        parsed = load_recipe(d)
        recomputed = root(parsed, d)
        return {"ok": recomputed == manifest["root"], "root": manifest["root"],
                "recomputed": recomputed, "name": manifest["name"]}
    except ClaimError:
        raise
    except Exception as e:
        raise ClaimError(f"cannot verify {d!r}: {e}") from e


def _ssh_identities(anchor: str):
    try:
        with open(anchor, encoding="utf-8") as f:
            lines = f.readlines()
    except OSError:
        return []
    out = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        out.append(line.split()[0])
    return out


def _signed(d: str, claim_root: str) -> bool:
    allowed_signers = os.environ.get(core._ENV_SIGNERS)
    if not allowed_signers or not os.path.isfile(allowed_signers):
        return False
    manifest = _seal_mod.read_manifest(d)
    if not manifest.get("proof"):
        return False
    sign_dir = os.path.join(d, core.SIGN_DIR)
    if not os.path.isdir(sign_dir):
        return False
    try:
        current_digest = identity.build_digest(d)
    except Exception:
        return False
    for fn in sorted(os.listdir(sign_dir)):
        if not fn.endswith(".sign.json"):
            continue
        spath = os.path.join(sign_dir, fn)
        sig_path = spath + ".sig"
        if not os.path.isfile(sig_path):
            continue
        try:
            with open(spath, "r", encoding="utf-8") as f:
                stmt = json.load(f)
        except (OSError, json.JSONDecodeError):
            continue
        if stmt.get("root") != claim_root:
            continue
        signer = stmt.get("identity")
        if not isinstance(signer, str):
            continue
        packet_file = fn[: -len(".sign.json")] + ".packet.json"
        ppath = os.path.join(sign_dir, packet_file)
        if not os.path.isfile(ppath):
            continue
        with open(ppath, "rb") as f:
            raw = f.read()
        if hashlib.sha256(raw).hexdigest() != stmt.get("packet_digest"):
            continue
        try:
            packet = json.loads(raw)
        except json.JSONDecodeError:
            continue
        if packet.get("root") != claim_root:
            continue
        if packet.get("build_digest") != current_digest:
            continue
        if not packet.get("proof"):
            continue
        with open(spath, "rb") as f:
            data = f.read()
        with open(sig_path, "rb") as f:
            signature = f.read()
        if attest._ssh_verify(core.SIGN_NAMESPACE, allowed_signers, signer,
                               signature, data):
            return True
    return False


def phase(d: str) -> str:
    if not os.path.isfile(os.path.join(d, core.MANIFEST)):
        return "draft"
    v = verify(d)
    if not v["ok"]:
        return "sealed"
    if not _signed(d, v["root"]):
        return "sealed"
    return "signed"


# =============================================================================
# sign_node: the bottom-anchored signature fold
# =============================================================================

def sign_node(root_value: str, build_digest_value: str, links) -> str:
    payload = {"root": root_value, "build_digest": build_digest_value,
               "links": sorted(links)}
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest()


# =============================================================================
# run_gate: THE SENDING HALF of the sandbox contract. `run.run_gate` (given)
# sets RETICULI_JAILED to a placeholder ("1") rather than the backend name,
# so a gate that is itself a claim runner cannot tell which jail it is
# inside and would try to re-apply one and nest. Reproduced here from the
# same private pieces (`run.sandbox_backend`, `run._sandbox_argv`,
# `run._scrub_env`, `run._run`, `run.gate_timeout`, `run._in_band`), fixing
# only the signal's value.
# =============================================================================

def _furnish(d: str, parsed: dict) -> dict:
    """`run.furnish` (given) installs from the declared `environment` file
    with no `cwd` for the pip subprocess, so a relative wheel path in the
    lock file resolves against the CALLER's cwd rather than the claim's --
    wrong whenever the caller is not already sitting in `d`. Furnish from
    inside `d`."""
    cwd0 = os.getcwd()
    os.chdir(d)
    try:
        return run.furnish(d, parsed)
    finally:
        os.chdir(cwd0)


def run_gate(cmd: str, d: str, recipe_doc=None) -> dict:
    backend = run.sandbox_backend()
    scratch = os.path.join(d, core.STORE, "scratch")
    os.makedirs(scratch, exist_ok=True)

    extra_env = {}
    if backend in ("seatbelt", "bubblewrap"):
        extra_env["TMPDIR"] = scratch
        extra_env["HOME"] = scratch
        extra_env[core._JAILED] = backend
    env = run._scrub_env(extra_env)

    try:
        argv = run._sandbox_argv(backend, d, scratch, cmd)
        timeout = run.gate_timeout(recipe_doc)
        result = run._run(argv, env, d, timeout)
    except OSError as e:
        return run._in_band(e, backend)

    if result["timed_out"]:
        status = "timeout"
    elif result["returncode"] == 0:
        status = "ok"
    else:
        status = "failed"
    return {"status": status, "quarantine": backend,
            "returncode": result["returncode"]}


# =============================================================================
# sandbox(cmd, d): a convenience probe/execution, distinct from run.sandbox()
# =============================================================================

def sandbox(cmd: str, d: str):
    result = run_gate(cmd, d)
    return (result["status"] == "ok", result["quarantine"])


# =============================================================================
# the producer: a scrubbed environment (never the caller's inherited
# secrets), the room's own output/usage/guidance variables, and whatever the
# caller deliberately hands over via producer_env.
# =============================================================================

def _produce(room: str, producer: str, parsed: dict, *,
             guidance: bool = True, producer_env: dict = None) -> None:
    outputs = recipe.generated_outputs(parsed)
    os.makedirs(os.path.join(room, core.STORE), exist_ok=True)
    extra = {}
    if outputs:
        extra[core._ENV_OUTPUT] = os.path.join(os.path.realpath(room), outputs[0])
        extra[core._ENV_OUTPUTS] = json.dumps(outputs)
    extra[core._ENV_USAGE] = os.path.join(os.path.realpath(room), core.USAGE)
    if guidance:
        hints = [h for h in (build._step_guidance(s)
                              for s in recipe.produces(parsed)) if h is not None]
        if hints:
            extra[core._ENV_REQUEST] = "\n".join(hints)
    if producer_env:
        extra.update(producer_env)
    env = run._scrub_env(extra)
    try:
        result = subprocess.run([core._SHELL, "-c", producer], cwd=room, env=env,
                                 timeout=core.PRODUCER_TIMEOUT, capture_output=True)
    except subprocess.TimeoutExpired as e:
        raise ClaimError(f"producer timed out: {e}") from e
    if result.returncode != 0:
        raise ClaimError(
            f"producer failed (exit {result.returncode}): "
            f"{result.stderr.decode('utf-8', 'replace')}")


def _venv_path_prepend(venv_dir):
    class _Ctx:
        def __enter__(self):
            self.old = os.environ.get("PATH", "")
            if venv_dir:
                os.environ["PATH"] = os.path.join(venv_dir, "bin") + os.pathsep + self.old
        def __exit__(self, *exc):
            os.environ["PATH"] = self.old
    return _Ctx()


# =============================================================================
# rebuild: materialize a fresh room, run the producer, judge, seal.
# =============================================================================

def rebuild(d: str, producer: str, into: str, *, produce_from: dict = None,
            input_from: dict = None, guidance: bool = True,
            producer_env: dict = None) -> dict:
    parsed = load_recipe(d)
    missing = run.preflight(parsed)
    if missing:
        raise ClaimError(f"environment: this host is missing {missing}")
    furnished = _furnish(d, parsed)
    if furnished["status"] != "ok":
        raise ClaimError(f"environment: {furnished.get('reason')}")

    if os.path.isdir(into):
        if os.listdir(into):
            raise ClaimError(f"rebuild target already holds bytes: {into!r}")
    elif os.path.exists(into):
        raise ClaimError(f"rebuild target already exists: {into!r}")
    else:
        os.makedirs(into)

    build._materialize(d, into, parsed)

    if input_from:
        for name, src in input_from.items():
            dst = core._safe(into, name)
            os.makedirs(os.path.dirname(dst) or into, exist_ok=True)
            shutil.copy2(src, dst)

    if produce_from:
        for output, src in produce_from.items():
            dst = core._safe(into, output)
            os.makedirs(os.path.dirname(dst) or into, exist_ok=True)
            shutil.copy2(src, dst)
            run.ledger(into, {"event": "reuse", "output": output})

    snapshot_names = list(recipe._inputs(into, parsed))
    room_recipe_name = os.path.relpath(recipe.recipe_path(into), into)
    snapshot_names = snapshot_names + [room_recipe_name]
    before = {n: core._hash_file(core._safe(into, n)) for n in snapshot_names}

    start = time.monotonic()
    _produce(into, producer, parsed, guidance=guidance, producer_env=producer_env)
    entry = {"calls": 1}
    entry.update(build._read_usage(into))
    entry["seconds"] = time.monotonic() - start
    run.ledger(into, entry)

    vendor = os.environ.get(core._ENV_VENDOR)
    model = os.environ.get(core._ENV_MODEL)
    if vendor or model:
        run.ledger(into, {"event": "producer", "vendor": vendor,
                           "model": model, "blind": True})

    after = {n: core._hash_file(core._safe(into, n)) for n in snapshot_names}
    if before != after:
        changed = sorted(n for n in before if before[n] != after.get(n))
        raise ClaimError(f"producer rewrote pinned bytes: {changed}")

    furnished_venv = furnished.get("venv")
    quarantine = None
    for step in recipe.gates(parsed):
        with _venv_path_prepend(furnished_venv):
            result = run_gate(step["run"], into, parsed)
        quarantine = result["quarantine"]
        run.ledger(into, {"event": "gate", "output": step["output"],
                           "status": result["status"], "quarantine": quarantine})
        if result["status"] != "ok":
            raise ClaimError(f"gate {step['output']!r} {result['status']}")

    manifest = seal(into)
    run.ledger(into, {"event": "environment", "python": platform.python_version(),
                       "platform": sys.platform, "quarantine": quarantine})
    return {"root": manifest["root"], "quarantine": quarantine}


# =============================================================================
# audit: re-earn every gate, cold, against the guidance-stripped room name.
# =============================================================================

def _environment_gate_rows(parsed):
    return [{"output": s["output"], "status": "environment", "quarantine": None}
            for s in recipe.gates(parsed)]


def audit(d: str, produce_from: dict = None) -> dict:
    parsed = load_recipe(d)
    v = verify(d)
    if not v["ok"]:
        return {"ok": False, "verdict": "mismatch", "gates": []}

    missing = run.preflight(parsed)
    if missing:
        return {"ok": False, "verdict": "environment",
                "gates": _environment_gate_rows(parsed), "environment": missing}

    furnished = _furnish(d, parsed)
    if furnished["status"] != "ok":
        return {"ok": False, "verdict": "environment",
                "gates": _environment_gate_rows(parsed),
                "reason": furnished.get("reason")}

    manifest = _seal_mod.read_manifest(d)
    fmt = identity._claim_format(parsed)
    recipe_path = recipe.recipe_path(d)
    backup_recipe = None
    substituted = {}
    try:
        if fmt >= 3:
            with open(recipe_path, "r", encoding="utf-8") as f:
                backup_recipe = f.read()
            preimage = identity._preimage_recipe(parsed)
            with open(recipe_path, "w", encoding="utf-8") as f:
                f.write(build._toml_dumps(preimage))

        if produce_from:
            for output, src in produce_from.items():
                path = core._safe(d, output)
                if os.path.isfile(path):
                    with open(path, "rb") as f:
                        substituted[output] = f.read()
                else:
                    substituted[output] = None
                shutil.copy2(src, path)

        gate_rows = []
        ok = True
        venv_dir = furnished.get("venv")
        for step in recipe.gates(parsed):
            output = step["output"]
            path = core._safe(d, output)
            pinned_backup = None
            if os.path.isfile(path):
                with open(path, "rb") as f:
                    pinned_backup = f.read()
                os.remove(path)
            try:
                with _venv_path_prepend(venv_dir):
                    result = run_gate(step["run"], d, parsed)
                status = result["status"]
                if status == "ok" and not build._compare_pin(d, output, manifest):
                    status = "mismatch"
            finally:
                # audit judges; it must not leave the claim worse than it
                # found it -- a gate that fails to reproduce its pinned
                # bytes must not permanently erase them.
                if pinned_backup is not None:
                    with open(path, "wb") as f:
                        f.write(pinned_backup)
                elif os.path.isfile(path):
                    os.remove(path)
            gate_rows.append({"output": output, "status": status,
                               "quarantine": result["quarantine"]})
            if status != "ok":
                ok = False
        return {"ok": ok, "verdict": "accept" if ok else "reject", "gates": gate_rows}
    finally:
        for output, original in substituted.items():
            path = core._safe(d, output)
            if original is None:
                if os.path.isfile(path):
                    os.remove(path)
            else:
                with open(path, "wb") as f:
                    f.write(original)
        if backup_recipe is not None:
            with open(recipe_path, "w", encoding="utf-8") as f:
                f.write(backup_recipe)


# =============================================================================
# independence: declared producer identity of a directory leg
# =============================================================================

def independence(d: str) -> dict:
    vendor = model = blind = None
    for event in reversed(run.ledger_events(d)):
        if event.get("event") == "producer":
            vendor, model, blind = (event.get("vendor"), event.get("model"),
                                     event.get("blind"))
            break
    return {"vendor": vendor, "model": model, "blind": blind}


def _record_producer(doc):
    prod = doc.get("producer") or {}
    return {"vendor": prod.get("vendor"), "model": prod.get("model"),
            "blind": prod.get("blind")}


# =============================================================================
# the record transport, re-specified to cover version 2 (declared
# obligations) which the lower `attest` module does not implement.
# =============================================================================

_RECORD_MEMBERS = frozenset({
    "record", "name", "root", "build_digest", "gates", "cost", "producer",
    "environment", "when", "tool", "claim",
})
_RECORD_REQUIRED_BASE = frozenset({
    "record", "name", "root", "build_digest", "gates", "environment", "when",
})
_CLAIM_OBLIGATIONS = frozenset({"tolerance", "envelope", "mutation_floor"})


def _validate_nonneg_number(value, label: str) -> None:
    if isinstance(value, bool) or not isinstance(value, (int, float)) or value < 0:
        raise ClaimError(f"{label} must be a non-negative number, got {value!r}")


def _validate_envelope(env, label: str = "envelope") -> None:
    if not isinstance(env, dict) or not env:
        raise ClaimError(f"{label} must be a non-empty table, got {env!r}")
    for unit, ceiling in env.items():
        if unit not in core.COST_KEYS:
            raise ClaimError(
                f"{label} unit must be one of {sorted(core.COST_KEYS)}, got {unit!r}")
        if isinstance(ceiling, bool) or not isinstance(ceiling, (int, float)) or ceiling <= 0:
            raise ClaimError(f"{label} ceiling must be a positive number, got {ceiling!r}")


def _validate_claim_obligations(claim) -> None:
    if not isinstance(claim, dict):
        raise ClaimError(f"claim must be an object, got {claim!r}")
    unknown = set(claim) - _CLAIM_OBLIGATIONS
    if unknown:
        raise ClaimError(f"claim carries unknown obligations: {sorted(unknown)}")
    for key in ("tolerance", "mutation_floor"):
        if key in claim:
            _validate_nonneg_number(claim[key], f"claim {key}")
    if "envelope" in claim:
        _validate_envelope(claim["envelope"], "claim envelope")


def record_validate(doc) -> dict:
    if not isinstance(doc, dict):
        raise ClaimError(f"a record must be a JSON object, got {doc!r}")
    unknown = set(doc) - _RECORD_MEMBERS
    if unknown:
        raise ClaimError(f"a record carries unknown members: {sorted(unknown)}")

    version = doc.get("record")
    if not isinstance(version, int) or isinstance(version, bool):
        raise ClaimError(f"record version must be an integer, got {version!r}")
    if version > RECORD_FORMAT:
        raise ClaimError(
            f"record version {version} is newer than this reader understands "
            f"(record {RECORD_FORMAT}); upgrade to read it")
    if version < 1:
        raise ClaimError(f"record version must be at least 1, got {version!r}")

    required = set(_RECORD_REQUIRED_BASE)
    if version >= 2:
        required.add("claim")
    missing = required - set(doc)
    if missing:
        raise ClaimError(f"a record is missing required members: {sorted(missing)}")
    if version == 1 and "claim" in doc:
        raise ClaimError("a version-1 record must not carry claim")

    attest._require_str(doc.get("name"), "a record's name")
    root_v = doc.get("root")
    if not isinstance(root_v, str) or not attest._RECORD_HEX.match(root_v):
        raise ClaimError(f"root must be 64 lowercase hex characters, got {root_v!r}")
    bd = doc.get("build_digest")
    if not isinstance(bd, str) or not attest._RECORD_HEX.match(bd):
        raise ClaimError(f"build_digest must be 64 lowercase hex characters, got {bd!r}")

    gates = doc.get("gates")
    if not isinstance(gates, list):
        raise ClaimError(f"gates must be an array, got {gates!r}")
    for entry in gates:
        attest._validate_gate(entry)
    attest._validate_environment(doc.get("environment"))

    when = doc.get("when")
    if not isinstance(when, str) or not attest._RECORD_WHEN.match(when):
        raise ClaimError(f"when must be YYYY-MM-DDTHH:MM:SSZ, got {when!r}")

    if "cost" in doc:
        attest._validate_cost(doc["cost"])
    if "producer" in doc:
        attest._validate_producer(doc["producer"])
    if "tool" in doc:
        attest._require_str(doc["tool"], "tool")
    if "claim" in doc:
        _validate_claim_obligations(doc["claim"])
    return doc


record_canonical = attest.record_canonical
record_digest = attest.record_digest


def record_read(path: str) -> dict:
    try:
        with open(path, "rb") as f:
            raw = f.read()
    except OSError as e:
        raise ClaimError(f"cannot read record {path!r}: {e}") from e
    try:
        doc = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as e:
        raise ClaimError(f"malformed record {path!r}: {e}") from e
    validated = record_validate(doc)
    if raw != record_canonical(doc):
        raise ClaimError(f"record {path!r} is not canonical bytes")
    return validated


def record_signer(path: str, anchor: str):
    sig_path = path + ".sig"
    if not anchor or not os.path.isfile(anchor) or not os.path.isfile(sig_path):
        return None
    try:
        with open(sig_path, "rb") as f:
            signature = f.read()
        with open(path, "rb") as f:
            data = f.read()
    except OSError:
        return None
    for identity_id in _ssh_identities(anchor):
        if attest._ssh_verify(RECORD_NAMESPACE, anchor, identity_id, signature, data):
            return identity_id
    return None


# =============================================================================
# record_proof: run the crosscheck; on a pass, seal the proof onto M1.
# =============================================================================

def record_proof(m1: str, m2, m3) -> dict:
    if not os.path.isdir(m1):
        raise ClaimError("a proof requires M1 to be a directory")
    result = crosscheck(m1, m2, m3)
    proof_recorded = result["satisfied"]
    proof = None
    if proof_recorded:
        proof = {"kind": "crosscheck", "roots": result["roots"]}
        records = []
        allowed_signers = os.environ.get(core._ENV_SIGNERS)
        for label, leg_path in (("M2", m2), ("M3", m3)):
            if os.path.isfile(leg_path):
                if not allowed_signers:
                    raise ClaimError("a proof from unanchored records must refuse")
                signer = record_signer(leg_path, allowed_signers)
                if signer is None:
                    raise ClaimError(
                        f"{label} record does not verify against the anchor")
                doc = record_read(leg_path)
                records.append({"leg": label, "signer": signer,
                                 "digest": record_digest(doc)})
        if records:
            proof["records"] = records
        manifest = _seal_mod.read_manifest(m1)
        manifest["proof"] = proof
        core._write_json(os.path.join(m1, core.MANIFEST), manifest)
    return {"proof_recorded": proof_recorded, "proof": proof, "crosscheck": result}


# =============================================================================
# gate_deciders / vacuous_gates: which files a gate's run line actually reads
# =============================================================================

_INTERPRETERS = frozenset({'Rscript', 'awk', 'lua', 'python', 'python3', 'python2',
                            'node', 'ruby', 'perl', 'dash', 'deno', 'py.test', 'zsh',
                            'tclsh', 'php', 'sh', 'bash', 'py', 'pytest'})
_OPERATORS = frozenset({'&', '\n', '|', '||', '&&', ';'})
_SKIP_VALUE = frozenset({'-m', '-p', '--module', '-X', '-c', '-e'})


def _split_operators(cmd: str):
    non_nl = sorted((op for op in _OPERATORS if op != "\n"), key=len, reverse=True)
    pattern = "|".join(re.escape(op) for op in non_nl) + r"|\n"
    return [seg for seg in re.split(pattern, cmd) if seg.strip()]


def gate_deciders(cmd: str) -> list:
    deciders = []
    for segment in _split_operators(cmd):
        if ">" in segment or "<" in segment:
            continue
        try:
            tokens = shlex.split(segment)
        except ValueError:
            continue
        if not tokens:
            continue
        head, rest = tokens[0], tokens[1:]
        if "/" in head:
            name = head[2:] if head.startswith("./") else head
            deciders.append(name)
            continue
        if head not in _INTERPRETERS:
            continue
        i = 0
        while i < len(rest):
            tok = rest[i]
            if tok.startswith("-"):
                i += 2 if tok in _SKIP_VALUE else 1
                continue
            deciders.append(tok)
            i += 1
    return deciders


def vacuous_gates(parsed: dict) -> list:
    generated = set(recipe.generated_outputs(parsed))
    result = []
    for step in recipe.gates(parsed):
        deciders = gate_deciders(step.get("run", ""))
        if deciders and all(dec in generated for dec in deciders):
            result.append(step["output"])
    return result


# =============================================================================
# mutation testing: deterministic mutants of the generated code, drawn from
# the root, re-audited against the gate.
# =============================================================================

_ARITHMETIC = ("+", "-", "*", "/", "//", "%")
_COMPARISON = ('>', '<', '>=', '<=', '==', '!=')
_OP_KIND = {}
_OP_ALTS = {}
for _group, _kind in ((_ARITHMETIC, "arithmetic"), (_COMPARISON, "comparison")):
    for _i, _sym in enumerate(_group):
        _OP_KIND[_sym] = _kind
        _OP_ALTS[_sym] = _group[(_i + 1) % len(_group)]
del _group, _kind, _i, _sym

_WORD_ALTS = {"True": "False", "False": "True", "and": "or", "or": "and",
              "break": "continue", "continue": "break"}
_STRING_LITERAL = re.compile(r"'[^'\\\n]*'|\"[^\"\\\n]*\"")

_BINOP_SYMBOL = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*", ast.Div: "/",
                 ast.FloorDiv: "//", ast.Mod: "%"}
_CMPOP_SYMBOL = {ast.Gt: ">", ast.Lt: "<", ast.GtE: ">=", ast.LtE: "<=",
                 ast.Eq: "==", ast.NotEq: "!="}


def _line_offsets(src: str) -> list:
    offsets = [0]
    for line in src.splitlines(keepends=True):
        offsets.append(offsets[-1] + len(line))
    return offsets


def _node_span(node, offsets):
    start = offsets[node.lineno - 1] + node.col_offset
    end = offsets[node.end_lineno - 1] + node.end_col_offset
    return (start, end)


def _span_text(src: str, span) -> str:
    return src[span[0]:span[1]]


def _splice(src: str, span, replacement: str) -> str:
    return src[:span[0]] + replacement + src[span[1]:]


def _edit(src: str, site: dict) -> str:
    return _splice(src, site["span"], site["new"])


def _named(site: dict) -> str:
    return f"{site['file']}:{site['lineno']}"


def _label(site: dict) -> str:
    return f"{_named(site)}: {site['old']!r} -> {site['new']!r}"


def _docstring_spans(tree, offsets) -> list:
    spans = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            body = getattr(node, "body", [])
            if body and isinstance(body[0], ast.Expr) and \
                    isinstance(body[0].value, ast.Constant) and \
                    isinstance(body[0].value.value, str):
                spans.append(_node_span(body[0].value, offsets))
    return spans


def _within(start, end, spans) -> bool:
    return any(s <= start and end <= e for s, e in spans)


def _op_token_span(src, offsets, left, right):
    lend = offsets[left.end_lineno - 1] + left.end_col_offset
    rstart = offsets[right.lineno - 1] + right.col_offset
    between = src[lend:rstart]
    stripped = between.strip()
    if not stripped:
        return None
    pad = len(between) - len(between.lstrip())
    start = lend + pad
    return (start, start + len(stripped))


def _structural_mutants(tree, src, offsets, filename) -> list:
    sites = []
    for node in ast.walk(tree):
        if isinstance(node, ast.BinOp):
            sym = _BINOP_SYMBOL.get(type(node.op))
            if sym and sym in _OP_ALTS:
                span = _op_token_span(src, offsets, node.left, node.right)
                if span and _span_text(src, span) == sym:
                    sites.append({"file": filename, "span": span, "old": sym,
                                  "new": _OP_ALTS[sym], "lineno": node.lineno})
        elif isinstance(node, ast.Compare) and len(node.ops) == 1:
            sym = _CMPOP_SYMBOL.get(type(node.ops[0]))
            if sym and sym in _OP_ALTS:
                span = _op_token_span(src, offsets, node.left, node.comparators[0])
                if span and _span_text(src, span) == sym:
                    sites.append({"file": filename, "span": span, "old": sym,
                                  "new": _OP_ALTS[sym], "lineno": node.lineno})
    return sites


def _token_mutants(src, doc_spans, filename) -> list:
    sites = []
    for m in re.finditer(r"\b([A-Za-z_]+)\b", src):
        word = m.group(1)
        if word in _WORD_ALTS and not _within(m.start(), m.end(), doc_spans):
            sites.append({"file": filename, "span": (m.start(), m.end()),
                          "old": word, "new": _WORD_ALTS[word],
                          "lineno": src.count("\n", 0, m.start()) + 1})
    for m in _STRING_LITERAL.finditer(src):
        if _within(m.start(), m.end(), doc_spans):
            continue
        old = m.group(0)
        inner = old[1:-1]
        if not inner:
            continue
        new = old[0] + inner[::-1] + old[-1]
        if new == old:
            continue
        sites.append({"file": filename, "span": (m.start(), m.end()),
                      "old": old, "new": new,
                      "lineno": src.count("\n", 0, m.start()) + 1})
    return sites


def _mutants(d: str, parsed: dict) -> list:
    sites = []
    for output in recipe.generated_outputs(parsed):
        if not output.endswith(".py"):
            continue
        path = core._safe(d, output)
        if not os.path.isfile(path):
            continue
        with open(path, encoding="utf-8") as f:
            src = f.read()
        try:
            tree = ast.parse(src)
        except SyntaxError:
            continue
        offsets = _line_offsets(src)
        doc_spans = _docstring_spans(tree, offsets)
        sites.extend(_structural_mutants(tree, src, offsets, output))
        sites.extend(_token_mutants(src, doc_spans, output))
    return sites


def _machine(seed: str):
    digest = hashlib.sha256(str(seed).encode("utf-8")).digest()
    return random.Random(int.from_bytes(digest[:8], "big"))


def _draw_order(n: int, seed: str) -> list:
    order = list(range(n))
    _machine(seed).shuffle(order)
    return order


def _mutant_order(sites: list, seed: str) -> list:
    order = _draw_order(len(sites), seed)
    return [sites[i] for i in order]


def _clear_pycache(d: str) -> None:
    """Force a cold re-import: a stale `__pycache__` entry keyed on an mtime
    that two rapid rewrites of the same file can share would otherwise let
    a mutant run on the PREVIOUS bytecode, under-reporting the kill rate."""
    for base, dirs, _files in os.walk(d):
        if "__pycache__" in dirs:
            shutil.rmtree(os.path.join(base, "__pycache__"), ignore_errors=True)
            dirs.remove("__pycache__")


def mutation_score(d: str, max_mutants: int = None) -> dict:
    parsed = load_recipe(d)
    manifest = _seal_mod.read_manifest(d)
    cap = int(max_mutants) if max_mutants is not None else int(core.MUTANT_CEILING)
    sites = _mutants(d, parsed)
    ordered = _mutant_order(sites, manifest["root"])
    selected = ordered[:cap]

    survivors = []
    killed = 0
    for site in selected:
        path = core._safe(d, site["file"])
        with open(path, encoding="utf-8") as f:
            original = f.read()
        mutated = _edit(original, site)
        try:
            with open(path, "w", encoding="utf-8") as f:
                f.write(mutated)
            _clear_pycache(d)
            gate_ok = True
            for step in recipe.gates(parsed):
                result = run_gate(step["run"], d, parsed)
                if result["status"] != "ok":
                    gate_ok = False
                    break
            if gate_ok:
                survivors.append(_label(site))
            else:
                killed += 1
        finally:
            with open(path, "w", encoding="utf-8") as f:
                f.write(original)
            _clear_pycache(d)

    total = len(selected)
    rate = (killed / total) if total else 0.0
    report = {"mutants": total, "rate": rate, "survivors": survivors}
    core._write_json(os.path.join(d, core.MUTATION_RESIDUE), report)
    return report


# =============================================================================
# crosscheck: the three-machine test, over directories or frozen records
# =============================================================================

def _leg(path: str) -> dict:
    if os.path.isfile(path):
        doc = record_read(path)
        claim_known = doc.get("record", 1) >= 2
        gates_list = doc.get("gates", [])
        audited_ok = all(g["status"] == "ok" for g in gates_list) if gates_list else True
        return {
            "kind": "record", "root": doc["root"], "build_digest": doc["build_digest"],
            "audited_ok": audited_ok, "cost": doc.get("cost"),
            "claim": doc.get("claim", {}) if claim_known else {},
            "claim_known": claim_known, "producer": _record_producer(doc),
            "path": None,
        }
    v = verify(path)
    parsed = load_recipe(path)
    claim_decl = parsed.get("claim", {})
    declared = {k: claim_decl[k] for k in _CLAIM_OBLIGATIONS if k in claim_decl}
    a = audit(path)
    return {
        "kind": "dir", "root": v["root"], "build_digest": identity.build_digest(path),
        "audited_ok": a["ok"], "cost": run.cost(path), "claim": declared,
        "claim_known": True, "producer": independence(path), "path": path,
    }


def _compare_cost(cost1, cost3, tolerance):
    if not cost1 or not cost3:
        return None
    for unit in core.COST_LADDER:
        if unit in cost1 and unit in cost3:
            v1, v3 = cost1[unit], cost3[unit]
            if v1 == v3:
                return True
            lo, hi = min(v1, v3), max(v1, v3)
            if lo <= 0:
                return False
            return (hi / lo) <= tolerance
    return None


def crosscheck(m1, m2, m3, mutants: int = None) -> dict:
    reals = {os.path.realpath(m1), os.path.realpath(m2), os.path.realpath(m3)}
    if len(reals) < 3:
        raise ClaimError("crosscheck requires three distinct machines")

    legs = {"M1": _leg(m1), "M2": _leg(m2), "M3": _leg(m3)}
    roots = {k: legs[k]["root"] for k in legs}
    equivalence = len(set(roots.values())) == 1
    reuse = legs["M1"]["build_digest"] == legs["M2"]["build_digest"]
    audited = {k: legs[k]["audited_ok"] for k in legs}

    hard_fail, incomplete = [], []
    if not equivalence:
        hard_fail.append("root")
    if not reuse:
        hard_fail.append("reuse")
    for k in ("M1", "M2", "M3"):
        if not audited[k]:
            hard_fail.append(f"audit {k}")

    claim_known = legs["M1"]["claim_known"]
    declared = legs["M1"]["claim"] if claim_known else {}

    cost1, cost3 = legs["M1"]["cost"], legs["M3"]["cost"]
    tolerance = declared.get("tolerance", core.TOLERANCE)
    comparable = _compare_cost(cost1, cost3, tolerance)

    envelope_report = {}
    if claim_known and "envelope" in declared:
        for unit, ceiling in declared["envelope"].items():
            measured = cost3.get(unit) if cost3 else None
            if measured is None:
                envelope_report[unit] = {"within": None}
                incomplete.append(f"envelope {unit}")
            else:
                within = measured <= ceiling
                envelope_report[unit] = {"within": within}
                if not within:
                    hard_fail.append(f"envelope {unit}")

    if claim_known and "tolerance" in declared:
        if comparable is None:
            incomplete.append("cost band")
        elif comparable is False:
            hard_fail.append("cost band")

    mutation_report = None
    if claim_known and "mutation_floor" in declared:
        floor = declared["mutation_floor"]
        if mutants is not None and legs["M3"]["kind"] == "dir":
            score = mutation_score(legs["M3"]["path"], max_mutants=mutants)
            ok = score["rate"] >= floor
            mutation_report = dict(score, ok=ok)
            if not ok:
                hard_fail.append("mutation floor")
        else:
            incomplete.append("mutation floor")

    if not claim_known:
        incomplete.append("declared conditions")

    if hard_fail:
        verdict = "reject"
    elif incomplete:
        verdict = "incomplete"
    else:
        verdict = "accept"

    prod3 = legs["M3"]["producer"] or {}
    if prod3.get("vendor") and prod3.get("model"):
        workspace = "blind" if prod3.get("blind") else "sighted"
        independence_str = (f"declared: {prod3['vendor']}/{prod3['model']}, "
                             f"{workspace} workspace (not proven)")
    else:
        independence_str = "unestablished (no producer declared)"

    return {
        "satisfied": verdict == "accept",
        "verdict": verdict,
        "rejected": hard_fail,
        "incomplete": incomplete,
        "roots": roots,
        "equivalence": equivalence,
        "reuse": reuse,
        "audited": audited,
        "cost": {"comparable": comparable, "envelope": envelope_report},
        "mutation_score": mutation_report,
        "independence": independence_str,
    }
