"""Attestation: a keyholder's signed statement of a build, and the signing
ceremony for accountable authorization over a chain (`spec/layers.md`'s
exchange layer).

Two distinct signatures live here, in two namespaces, over two different
documents:

- `attest`/`check` -- a signed statement that a PARTICULAR BUILD (this
  root, these exact generated bytes) re-earns its own verdicts right now.
  Signs only what audits clean; never signs a carried verdict (bytes that
  pass identity but fail a re-run gate) or a broken claim (bytes that fail
  identity outright). Stored under `ATTEST`, signed in `kernel.NAMESPACE`.

- `sign`/`sign_check` -- the ceremony: a human signs the folded
  signature-chain root over a review packet (the root, build digest,
  chain fold, and full audit the signer reviewed). SIGNED means
  AUTHORIZED (a trusted signer's signature) AND PROVEN (a recorded proof)
  -- `kernel.phase` only promotes a claim to `signed` once both hold.
  Stored under `kernel.SIGN_DIR`, signed in `kernel.SIGN_NAMESPACE`. One
  ceremony per claim directory: re-signing overwrites the prior statement,
  packet, and signature in place, so a verifier checking "the" signed
  statement is never looking at a stale one.

Every refusal here is `kernel.ClaimError` -- the one error vocabulary the
kernel and everything above it shares.

Stdlib only.
"""
import hashlib
import json
import os
import subprocess

from . import _util
from . import kernel
from . import registry

ATTEST = ".reticuli/attest"

_ATTEST_BASE = "build"
_MINT_BASE = "ceremony"


# ---------------------------------------------------------------------------
# attest / check: a signed statement of one build
# ---------------------------------------------------------------------------

def _generated_outputs_present(d: str) -> list:
    recipe = kernel.load_recipe(d)
    out = []
    for step in recipe.get("step", []):
        if step.get("kind") != "produce":
            continue
        cls = step.get("class", "generated")
        if cls not in ("generated", "free"):
            continue
        output = step.get("output")
        if output and os.path.isfile(os.path.join(d, output)):
            out.append(output)
    return sorted(out)


def attest(d: str, key: str, identity: str) -> dict:
    """Sign a statement of this build: refuses unless the claim's verdicts
    re-earn cold right now (`kernel.audit`) -- never a carried verdict,
    never a broken claim.
    """
    d = os.path.abspath(d)
    result = kernel.audit(d)
    if not result.get("ok"):
        raise kernel.ClaimError(
            f"refused: cannot attest a claim whose verdicts do not reproduce: "
            f"{result.get('verdict')}"
        )
    manifest = kernel.read_manifest(d)
    root_value = manifest["root"]
    digest = kernel.build_digest(d)
    statement = {
        "identity": identity,
        "root": root_value,
        "build_digest": digest,
        "outputs": {path: _util.hash_bytes(os.path.join(d, path))
                   for path in _generated_outputs_present(d)},
    }
    stmt_bytes = json.dumps(statement, sort_keys=True).encode("utf-8")

    attest_dir = os.path.join(d, ATTEST)
    os.makedirs(attest_dir, exist_ok=True)
    stmt_path = os.path.join(attest_dir, _ATTEST_BASE + ".json")
    with open(stmt_path, "wb") as f:
        f.write(stmt_bytes)
    sig_path = stmt_path + ".sig"
    if os.path.isfile(sig_path):
        os.remove(sig_path)
    subprocess.run(
        ["ssh-keygen", "-Y", "sign", "-f", key, "-n", kernel.NAMESPACE, stmt_path],
        check=True, capture_output=True,
    )
    return {"statement": os.path.relpath(stmt_path, d),
            "signature": os.path.relpath(sig_path, d),
            "root": root_value}


def check(d: str, signers: str = None) -> dict:
    """Check every attestation under `d`: intact (root/build-digest/output
    bytes still match what was signed), and -- when `signers` is given --
    anchored to a trusted identity.
    """
    d = os.path.abspath(d)
    try:
        manifest = kernel.read_manifest(d)
        current_root = manifest["root"]
        current_digest = kernel.build_digest(d)
    except kernel.ClaimError:
        return {"ok": False, "attestations": []}

    attest_dir = os.path.join(d, ATTEST)
    attestations = []
    overall_ok = False
    if os.path.isdir(attest_dir):
        for name in sorted(os.listdir(attest_dir)):
            if not name.endswith(".json") or name.endswith(".sig"):
                continue
            stmt_path = os.path.join(attest_dir, name)
            sig_path = stmt_path + ".sig"
            row = {"statement": name, "verdict": "unsigned", "drifted": False}
            try:
                with open(stmt_path, "rb") as f:
                    stmt_bytes = f.read()
                statement = json.loads(stmt_bytes)
            except (OSError, json.JSONDecodeError):
                attestations.append(row)
                continue
            if not isinstance(statement, dict):
                attestations.append(row)
                continue

            root_matches = statement.get("root") == current_root
            digest_matches = statement.get("build_digest") == current_digest
            bytes_ok = True
            for path, expected_hash in (statement.get("outputs") or {}).items():
                full = os.path.join(d, path)
                if not os.path.isfile(full) or _util.hash_bytes(full) != expected_hash:
                    bytes_ok = False
                    break
            intact = root_matches and digest_matches and bytes_ok
            row["drifted"] = root_matches and not (digest_matches and bytes_ok)
            if not intact:
                attestations.append(row)
                continue

            if signers is None:
                row["verdict"] = "intact"
                overall_ok = True
            else:
                identity_name = statement.get("identity")
                verified = False
                if (isinstance(identity_name, str) and os.path.isfile(sig_path)
                        and os.path.isfile(signers)):
                    try:
                        done = subprocess.run(
                            ["ssh-keygen", "-Y", "verify", "-f", signers,
                             "-I", identity_name, "-n", kernel.NAMESPACE, "-s", sig_path],
                            input=stmt_bytes, capture_output=True, timeout=10,
                        )
                        verified = done.returncode == 0
                    except OSError:
                        verified = False
                row["verdict"] = "signed" if verified else "untrusted"
                if verified:
                    overall_ok = True
            attestations.append(row)

    return {"ok": overall_ok, "attestations": attestations, "root": current_root}


# ---------------------------------------------------------------------------
# The signing ceremony: authorized AND proven
# ---------------------------------------------------------------------------

def review_packet(d: str, ws: str = None) -> dict:
    """What a signer reviews before authorizing: the root, the build
    digest, the folded signature-chain root, the full (own + deep) audit,
    and whether a proof is already recorded."""
    d = os.path.abspath(d)
    manifest = kernel.read_manifest(d)
    root_value = manifest["root"]
    digest = kernel.build_digest(d)
    own_audit = kernel.audit(d)
    deep_audit = registry.audit_deep(d)
    audit_ok = bool(own_audit.get("ok")) and bool(deep_audit.get("ok"))
    sign_root_value = registry.sign_root(d, ws)
    return {
        "root": root_value,
        "build_digest": digest,
        "sign_root": sign_root_value,
        "audit": {"ok": audit_ok, "own": own_audit, "deep": deep_audit},
        "proof": manifest.get("proof"),
    }


def sign(d: str, key: str, identity: str, ws: str = None) -> dict:
    """The ceremony: refuse a claim whose verdicts do not reproduce, sign
    the chain root and the review packet (`RETICULI_CLAIM_BASIN_V1`).
    Re-signing overwrites the prior statement/packet/signature in place.
    """
    d = os.path.abspath(d)
    packet = review_packet(d, ws)
    if not packet["audit"]["ok"]:
        raise kernel.ClaimError(
            "refused: cannot sign a claim whose verdicts do not reproduce"
        )
    packet_bytes = json.dumps(packet, sort_keys=True).encode("utf-8")

    sign_dir = os.path.join(d, kernel.SIGN_DIR)
    os.makedirs(sign_dir, exist_ok=True)
    packet_path = os.path.join(sign_dir, _MINT_BASE + ".packet.json")
    with open(packet_path, "wb") as f:
        f.write(packet_bytes)

    statement = {
        "ceremony": "RETICULI_CLAIM_BASIN_V1",
        "identity": identity,
        "root": packet["root"],
        "build_digest": packet["build_digest"],
        "proof_recorded": bool(packet.get("proof")),
        "packet_digest": hashlib.sha256(packet_bytes).hexdigest(),
    }
    stmt_path = os.path.join(sign_dir, _MINT_BASE + ".sign.json")
    stmt_bytes = json.dumps(statement, sort_keys=True).encode("utf-8")
    with open(stmt_path, "wb") as f:
        f.write(stmt_bytes)

    sig_path = stmt_path + ".sig"
    if os.path.isfile(sig_path):
        os.remove(sig_path)
    subprocess.run(
        ["ssh-keygen", "-Y", "sign", "-f", key, "-n", kernel.SIGN_NAMESPACE, stmt_path],
        check=True, capture_output=True,
    )
    return {"ceremony": statement["ceremony"],
            "signature": os.path.relpath(sig_path, d),
            "statement": os.path.relpath(stmt_path, d),
            "packet": os.path.relpath(packet_path, d)}


def sign_check(d: str, ws: str = None, signers: str = None) -> dict:
    """Check every authorization statement under `d`: the packet it cites
    still matches the claim's current root/build-digest/chain fold, and --
    when `signers` is given -- the statement's signature verifies against
    a trusted identity.
    """
    d = os.path.abspath(d)
    manifest = kernel.read_manifest(d)
    current_root = manifest["root"]
    current_digest = kernel.build_digest(d)
    try:
        current_sign_root = registry.sign_root(d, ws)
    except kernel.ClaimError:
        current_sign_root = None

    sign_dir = os.path.join(d, kernel.SIGN_DIR)
    authorizations = []
    ok_any = False
    if os.path.isdir(sign_dir):
        for name in sorted(os.listdir(sign_dir)):
            if not name.endswith(".sign.json"):
                continue
            base = name[: -len(".sign.json")]
            stmt_path = os.path.join(sign_dir, name)
            sig_path = stmt_path + ".sig"
            packet_path = os.path.join(sign_dir, base + ".packet.json")
            row = {"statement": name, "verdict": "unauthorized",
                   "packet_holds": False, "proof_recorded": False}
            try:
                with open(stmt_path, "rb") as f:
                    stmt_bytes = f.read()
                statement = json.loads(stmt_bytes)
            except (OSError, json.JSONDecodeError):
                authorizations.append(row)
                continue
            if not isinstance(statement, dict):
                authorizations.append(row)
                continue
            row["proof_recorded"] = bool(statement.get("proof_recorded"))

            packet_holds = False
            if os.path.isfile(packet_path):
                with open(packet_path, "rb") as f:
                    packet_bytes = f.read()
                if hashlib.sha256(packet_bytes).hexdigest() == statement.get("packet_digest"):
                    try:
                        packet = json.loads(packet_bytes)
                        packet_holds = (
                            isinstance(packet, dict)
                            and packet.get("root") == current_root
                            and packet.get("build_digest") == current_digest
                            and packet.get("sign_root") == current_sign_root
                        )
                    except json.JSONDecodeError:
                        packet_holds = False
            row["packet_holds"] = packet_holds

            identity_name = statement.get("identity")
            if (signers and os.path.isfile(signers) and isinstance(identity_name, str)
                    and statement.get("root") == current_root
                    and os.path.isfile(sig_path) and packet_holds):
                try:
                    done = subprocess.run(
                        ["ssh-keygen", "-Y", "verify", "-f", signers, "-I", identity_name,
                         "-n", kernel.SIGN_NAMESPACE, "-s", sig_path],
                        input=stmt_bytes, capture_output=True, timeout=10,
                    )
                    if done.returncode == 0:
                        row["verdict"] = "authorized"
                        ok_any = True
                except OSError:
                    pass
            authorizations.append(row)

    return {"ok": ok_any, "authorizations": authorizations}
