"""The kernel's public surface (`spec/kernel-api.md`).

This module is the one thing above the kernel ever imports: it wires the
primitives in `_kernel/` (path/byte boundaries, recipe parsing, identity,
seal/verify, gate execution, rebuild/audit, records, crosscheck) into the
~21 pinned names a conforming kernel exposes, and fixes the handful of
seams those primitives deliberately leave to the façade:

- every directory argument is resolved to an absolute path before it
  reaches a lower layer, so a caller's relative `into` (after `os.chdir`)
  cannot alias itself through a child process's own cwd;
- `run_gate`/`sandbox` apply the host sandbox and, when one is really
  applied, tell the wrapped process which backend it is inside
  (`RETICULI_JAILED` = the backend name, not a bare flag) -- the sending
  half of the no-nesting contract (`checks/kernel_check.py`'s
  `_apply_battery`);
- `rebuild` ledgers what `_kernel/build.py` computes but does not itself
  record: the gate's sandbox, the judging environment, the producer's
  declared vendor/model/call count, and component-supplied reuse;
- `audit` and `phase` turn a damaged claim into a refusal, never a raw
  exception, and translate the audit engine's internal vocabulary
  (`reproduced`) to the kernel's pinned success spelling (`ok`);
- `phase` additionally evaluates `signed`: a trusted (anchored) ssh
  signature over a packet whose root and build digest still match the
  claim's current bytes, binding a recorded proof.

Stdlib only, never the network.
"""
import hashlib
import json
import os
import platform
import subprocess
import sys
import tempfile

from ._kernel import attest
from ._kernel import build as build_mod
from ._kernel import core
from ._kernel import crosscheck as crosscheck_mod
from ._kernel import identity
from ._kernel import recipe as recipe_mod
from ._kernel import run as run_mod
from ._kernel import seal as seal_mod

# -- constants (`spec/kernel-api.md`) ---------------------------------------
RECIPE = core.RECIPE
LEGACY_RECIPE = core.LEGACY_RECIPE
STORE = core.STORE
MANIFEST = core.MANIFEST
LEDGER = core.LEDGER
NAMESPACE = core.NAMESPACE
SIGN_DIR = core.SIGN_DIR
SIGN_NAMESPACE = core.SIGN_NAMESPACE
RECORD_NAMESPACE = attest.RECORD_NAMESPACE
RECORD_FORMAT = crosscheck_mod.RECORD_FORMAT

_JAILED = core._JAILED
_ENV_SIGNERS = core._ENV_SIGNERS
_ENV_VENDOR = core._ENV_VENDOR
_ENV_MODEL = core._ENV_MODEL

ClaimError = core.ClaimError
_hash_file = core._hash_file

_in_band = crosscheck_mod._in_band


def _abs(path: str) -> str:
    return os.path.abspath(path)


# -- identity -----------------------------------------------------------

def root(recipe: dict, d: str) -> str:
    """The claim's identity (`spec/identity.md`)."""
    return _in_band(crosscheck_mod.root, recipe, _abs(d))


def build_digest(d: str) -> str:
    """The digest of the generated bytes present (`spec/identity.md`)."""
    return _in_band(identity.build_digest, _abs(d))


def load_recipe(d: str) -> dict:
    """Parse and validate `reticuli.toml` (or legacy `claim.toml`).

    `_kernel/crosscheck.py`'s parser, not `_kernel/recipe.py`'s: the
    latter checks path confinement on every step's OUTPUT regardless of
    class, which refuses a GENERATED output that happens to be a symlink
    at load time -- before a producer has even regrown it, and before
    `audit`'s own confinement check (which does cover generated outputs,
    at the moment it copies one) gets a chance to be the one that
    refuses. Confinement on a generated output belongs to the gates that
    touch its bytes, not to parsing.
    """
    return _in_band(crosscheck_mod.load_recipe, _abs(d))


def read_manifest(d: str) -> dict:
    """`.reticuli/manifest.json`: `{name, root}`."""
    return _in_band(seal_mod.read_manifest, _abs(d))


def seal(d: str) -> dict:
    """Compute the root and write the manifest; returns it.

    Uses this module's own `load_recipe`, not `_kernel/seal.py`'s (which
    calls the stricter parser) -- see `load_recipe`'s docstring.
    """
    d = _abs(d)

    def _run():
        recipe = load_recipe(d)
        root_value = crosscheck_mod.root(recipe, d)
        name = recipe["claim"]["name"]
        manifest = {"name": name, "root": root_value}
        os.makedirs(os.path.join(d, core.STORE), exist_ok=True)
        core._write_json(os.path.join(d, core.MANIFEST), manifest)
        return manifest
    return _in_band(_run)


def verify(d: str) -> dict:
    """Identity only -- recompute the root and compare to the sealed one."""
    d = _abs(d)

    def _run():
        manifest = seal_mod.read_manifest(d)
        recipe = load_recipe(d)
        recomputed = crosscheck_mod.root(recipe, d)
        return {"ok": recomputed == manifest["root"], "root": manifest["root"],
                "recomputed": recomputed, "name": manifest["name"]}
    return _in_band(_run)


# -- gate execution -------------------------------------------------------

def run_gate(cmd: str, d: str, recipe: dict = None) -> dict:
    """Run one gate command: scrubbed, sandboxed, bounded.

    Unlike `_kernel/run.py`'s internal helper, when a real sandbox is
    applied the wrapped process is told WHICH one
    (`RETICULI_JAILED` = the backend name) -- the sending half of the
    no-nesting contract; a gate that is itself a claim runner must be able
    to inherit rather than re-apply.
    """
    d = _abs(d)
    backend = run_mod.sandbox_backend()
    timeout = run_mod.gate_timeout(recipe)
    extra_env = {}
    scratch = None
    if backend in ("seatbelt", "bubblewrap"):
        room = os.path.join(d, core.STORE, "room")
        os.makedirs(room, exist_ok=True)
        scratch = tempfile.mkdtemp(dir=room)
        extra_env["TMPDIR"] = scratch
        extra_env["HOME"] = scratch
        extra_env[core._JAILED] = backend
    env = run_mod._scrub_env(extra_env)
    argv = run_mod._sandbox_argv(backend, d, scratch, [core._SHELL, "-c", cmd])
    result = _in_band(run_mod._run, argv, cwd=d, env=env, timeout=timeout)
    if result["timed_out"]:
        status = "timeout"
    elif result["returncode"] == 0:
        status = "ok"
    else:
        status = "failed"
    return {"status": status, "quarantine": backend}


def sandbox(cmd: str, d: str, recipe: dict = None):
    """A functional probe of the host sandbox, applied to `cmd` in `d`:
    `(status, backend)`."""
    result = run_gate(cmd, d, recipe)
    return (result["status"], result["quarantine"])


def preflight(recipe: dict) -> list:
    """Missing `[claim] requires` entries."""
    return run_mod.preflight(recipe)


# -- cost ledger ----------------------------------------------------------

def ledger(d: str, entry: dict) -> None:
    run_mod.ledger(_abs(d), entry)


def ledger_events(d: str) -> list:
    return run_mod.ledger_events(_abs(d))


def cost(d: str):
    """Ledger totals per unit; `None` when nothing was ever measured."""
    totals = run_mod.cost(_abs(d))
    return totals or None


def independence(d: str) -> dict:
    """The declared producer of a redo: `{"vendor", "model", "blind"}`,
    all `None` when nothing was declared."""
    return crosscheck_mod._read_producer(_abs(d))


# -- rebuild / audit --------------------------------------------------------

def _scrubbed_produce(step: dict, into: str, producer: str, outs: list,
                      guidance: bool, producer_env: dict) -> None:
    """Run one produce step with the CALLER's ambient environment reduced
    to the same host allowlist a gate gets, for the window of the
    producer's own subprocess call only -- an inherited secret must never
    reach a producer unhanded, but furnishing and gate execution (which
    read their own `RETICULI_*` controls from the real process
    environment) run outside this window, untouched.
    """
    saved = dict(os.environ)
    try:
        for key in list(os.environ):
            if key not in core._KEEP_ENV:
                del os.environ[key]
        build_mod._produce(step, into, producer, outs, guidance, producer_env)
    finally:
        os.environ.clear()
        os.environ.update(saved)


def rebuild(d: str, producer: str, into: str, produce_from: dict = None,
            input_from: str = None, guidance: bool = True,
            producer_env: dict = None) -> dict:
    """Regrow a claim's generated outputs into `into` until its gates pass
    (v1: `realize`).

    A reimplementation of `_kernel/build.py`'s `rebuild`, not a delegation:
    the producer's own subprocess call runs with a scrubbed ambient
    environment (`_scrubbed_produce`), and this layer ledgers what the
    build layer computes but does not itself record -- the gate's
    sandbox and judging environment, the declared producer
    (vendor/model, and a call count the kernel itself measures), and a
    reuse event per component-supplied output.
    """
    d = _abs(d)
    into = _abs(into)
    vendor = os.environ.get(core._ENV_VENDOR)
    model = os.environ.get(core._ENV_MODEL)

    def _run():
        recipe = load_recipe(d)
        missing = build_mod._authorized(recipe)
        if missing:
            raise ClaimError(
                f"refused: environment requirement(s) missing: {missing}"
            )
        if os.path.isdir(into) and os.listdir(into):
            raise ClaimError(f"refused: rebuild target is not empty: {into!r}")
        os.makedirs(into, exist_ok=True)

        recipe_src = recipe_mod.recipe_path(d)
        core._copy_into(recipe_src, os.path.join(into, os.path.basename(recipe_src)))
        crosscheck_mod._rewrite_room_recipe(d, into, recipe)
        threaded = input_from or {}
        for path in recipe_mod._inputs(d, recipe):
            alt = threaded.get(path)
            source = alt if alt is not None else core._safe(d, path)
            core._copy_into(source, core._safe(into, path))
        env_file = recipe.get("claim", {}).get("environment")
        if env_file:
            core._copy_into(core._safe(d, env_file), core._safe(into, env_file))
        os.makedirs(os.path.join(into, core.STORE), exist_ok=True)

        # A producer cannot change the question: snapshot every pinned
        # path (the recipe and the declared inputs, as materialized --
        # deliberate threading via `input_from` included) and refuse if
        # the producer rewrote any of them, rather than silently sealing
        # a different, self-consistent claim.
        pinned_paths = [os.path.join(into, os.path.basename(recipe_src))]
        pinned_paths += [core._safe(into, p) for p in recipe_mod._inputs(d, recipe)]
        snapshot = {p: core._hash_file(p) for p in pinned_paths if os.path.isfile(p)}

        outs = recipe_mod.generated_outputs(recipe)
        supplied = produce_from or {}
        n_invoked = 0
        for step in recipe_mod.produces(recipe):
            output = step["output"]
            source = supplied.get(output)
            if source is not None:
                core._copy_into(source, core._safe(into, output))
                run_mod.ledger(into, {"event": "reuse", "output": output})
                continue
            if "from" in step:
                continue
            n_invoked += 1
            _scrubbed_produce(step, into, producer, outs, guidance, producer_env)

        for path, digest in snapshot.items():
            if not os.path.isfile(path) or core._hash_file(path) != digest:
                raise ClaimError(
                    f"refused: the producer rewrote a pinned path: {path!r}"
                )

        furnished = crosscheck_mod.furnish(into, recipe)
        quarantine = "none"
        with crosscheck_mod._prepended_path((furnished or {}).get("path")):
            for step in recipe_mod.gates(recipe):
                result = run_mod.run_gate(step["run"], into, recipe)
                quarantine = result["quarantine"]
                if result["status"] != "ok":
                    raise ClaimError(
                        f"refused: rebuild's gate did not pass: "
                        f"{step['output']!r} ({result['status']})"
                    )
        manifest = seal(into)
        return ({"root": manifest["root"], "name": manifest["name"],
                "quarantine": quarantine}, n_invoked)

    result, n_invoked = _in_band(_run)

    run_mod.ledger(into, {"event": "gate", "when": core._now(),
                          "quarantine": result["quarantine"]})
    run_mod.ledger(into, {"event": "environment", "when": core._now(),
                          "python": platform.python_version(),
                          "platform": sys.platform,
                          "quarantine": result["quarantine"]})
    run_mod.ledger(into, {"event": "producer", "when": core._now(),
                          "calls": n_invoked, "vendor": vendor, "model": model,
                          "blind": True})
    return result


def audit(d: str, produce_from: dict = None) -> dict:
    """Re-earn a claim's verdict cold (`spec/verification.md`)."""
    return crosscheck_mod._audit_dir(_abs(d), produce_from)


# -- the claim boundary -----------------------------------------------------

def vacuous_gates(recipe: dict) -> list:
    return crosscheck_mod.vacuous_gates(recipe)


def gate_deciders(cmd: str) -> list:
    return crosscheck_mod.gate_deciders(cmd)


def mutation_score(d: str, max_mutants: int = None) -> dict:
    return _in_band(crosscheck_mod.mutation_score, _abs(d), max_mutants)


# -- the three-machine test -------------------------------------------------

def crosscheck(leg1: str, leg2: str, leg3: str, mutants: int = None) -> dict:
    return crosscheck_mod.crosscheck(leg1, leg2, leg3, mutants)


def record_proof(m1: str, m2: str, m3: str) -> dict:
    """Run the crosscheck; on a pass, seal the proof onto M1's manifest.

    M1 must be a directory -- a proof is residue on a manifest. Any
    record leg among M2/M3 must verify against the anchor
    (`RETICULI_SIGNERS`); directory legs need none. A durable proof
    embeds each record leg's digest and signer identity.
    """
    m1_abs = _abs(m1)
    if not os.path.isdir(m1_abs):
        raise ClaimError("refused: a proof must land on a directory M1")

    records_trail = []
    anchor = os.environ.get(core._ENV_SIGNERS)
    for leg in (m2, m3):
        if os.path.isdir(leg):
            continue
        if not anchor or not os.path.isfile(anchor):
            raise ClaimError(
                f"refused: record leg {leg!r} has no trust anchor"
            )
        signer = crosscheck_mod.record_signer(leg, anchor)
        doc = crosscheck_mod._record_read(leg)
        records_trail.append({"digest": crosscheck_mod.record_digest(doc), "signer": signer})

    result = crosscheck(m1, m2, m3)
    proof_recorded = result["satisfied"]
    if proof_recorded:
        manifest = read_manifest(m1_abs)
        proof = {"kind": "crosscheck"}
        if records_trail:
            proof["records"] = records_trail
        manifest["proof"] = proof
        core._write_json(os.path.join(m1_abs, core.MANIFEST), manifest)

    out = dict(result)
    out["proof_recorded"] = proof_recorded
    return out


# -- phase: draft / sealed / signed ------------------------------------------

def _packet_bytes_valid(sign_dir: str, base: str, statement: dict,
                        current_root: str, current_digest: str) -> bool:
    packet_path = os.path.join(sign_dir, base + ".packet.json")
    if not os.path.isfile(packet_path):
        return False
    with open(packet_path, "rb") as f:
        packet_bytes = f.read()
    if hashlib.sha256(packet_bytes).hexdigest() != statement.get("packet_digest"):
        return False
    try:
        packet = json.loads(packet_bytes)
    except json.JSONDecodeError:
        return False
    if not isinstance(packet, dict):
        return False
    if packet.get("root") != current_root or packet.get("build_digest") != current_digest:
        return False
    return bool(packet.get("proof"))


def _is_signed(d: str, current_root: str, current_digest: str, manifest: dict) -> bool:
    if not manifest.get("proof"):
        return False
    anchor = os.environ.get(core._ENV_SIGNERS)
    if not anchor or not os.path.isfile(anchor):
        return False
    sign_dir = os.path.join(d, core.SIGN_DIR)
    if not os.path.isdir(sign_dir):
        return False
    for name in sorted(os.listdir(sign_dir)):
        if not name.endswith(".sign.json"):
            continue
        spath = os.path.join(sign_dir, name)
        sig_path = spath + ".sig"
        if not os.path.isfile(sig_path):
            continue
        try:
            with open(spath, "rb") as f:
                stmt_bytes = f.read()
            statement = json.loads(stmt_bytes)
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(statement, dict):
            continue
        identity_name = statement.get("identity")
        if not isinstance(identity_name, str):
            continue
        if statement.get("root") != current_root or not statement.get("proof_recorded"):
            continue
        base = name[: -len(".sign.json")]
        if not _packet_bytes_valid(sign_dir, base, statement, current_root, current_digest):
            continue
        try:
            done = subprocess.run(
                ["ssh-keygen", "-Y", "verify", "-f", anchor, "-I", identity_name,
                 "-n", core.SIGN_NAMESPACE, "-s", sig_path],
                input=stmt_bytes, capture_output=True, timeout=10,
            )
        except OSError:
            continue
        if done.returncode == 0:
            return True
    return False


def phase(d: str) -> str:
    """`draft` / `sealed` / `signed` (`spec/verification.md`)."""
    d = _abs(d)
    recipe = load_recipe(d)
    manifest_path = os.path.join(d, core.MANIFEST)
    if not os.path.isfile(manifest_path):
        return "draft"
    manifest = _in_band(seal_mod.read_manifest, d)
    verified = _in_band(seal_mod.verify, d)
    if not verified["ok"]:
        return "sealed"
    current_digest = _in_band(identity.build_digest, d)
    if _is_signed(d, manifest["root"], current_digest, manifest):
        return "signed"
    return "sealed"


# -- signature-chain nodes ----------------------------------------------

def sign_node(root_value: str, digest: str, links: list) -> str:
    """One node of the bottom-anchored signature chain: a deterministic
    fold of a layer's root, its build digest, and the SET of signatures
    beneath it (order-independent)."""
    payload = {"root": root_value, "build_digest": digest, "links": sorted(links)}
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True).encode("utf-8")
    ).hexdigest()


# -- records (`spec/record.md`) ------------------------------------------

def record_canonical(doc) -> bytes:
    return crosscheck_mod.record_canonical(doc)


def record_digest(doc) -> str:
    return crosscheck_mod.record_digest(doc)


def record_validate(doc) -> None:
    crosscheck_mod.record_validate(doc)


def record_read(path: str) -> dict:
    """Read a record file: valid per `spec/record.md`, and byte-identical
    to its own canonical serialization -- a reformatted file is not the
    record it claims to be."""
    return crosscheck_mod._record_read(path)


def record_signer(path: str, anchor: str) -> str:
    return crosscheck_mod.record_signer(path, anchor)
