"""A second, independent implementation of the identity computation
(`spec/identity.md`), built from the spec alone.

`root(d)` loads the recipe under claim directory `d` (`reticuli.toml`,
preferring it over the legacy `claim.toml`) and computes the claim's
identity: a SHA-256 digest over a string-to-string map built from the
canonically-serialized recipe, every pinned input's file digest, and
every pinned/validated step output's file digest. `build_digest(d)`
computes the digest of the generated bytes present, the thing a
signature over concrete bytes binds.

Run as a script, this module is the conformance runner's "any
implementation": `python -m reticuli.reference root <dir>` prints the
root; `python -m reticuli.reference digest <dir>` prints the build
digest.

Stdlib only.
"""
import hashlib
import json
import os
import sys
import tomllib

RECIPE = "reticuli.toml"
LEGACY_RECIPE = "claim.toml"
GENERATED_CLASSES = frozenset({"generated", "free"})
GUIDANCE_KEYS = ("guidance", "request")


class ReferenceError(Exception):
    """A refusal with a reason."""


def _refuse_datetime(obj):
    raise ReferenceError(
        f"refused: TOML date/time values cannot enter the root preimage: {obj!r}"
    )


def _canonical_json(obj) -> str:
    """`json.dumps(obj, sort_keys=True)`: sorted keys, default (non-compact)
    separators, ASCII-escaped non-ASCII, arbitrary-precision integers,
    floats as CPython's `repr` -- all of that is already this call's
    default behavior. Refuses any value (a TOML date/time) it cannot
    otherwise serialize."""
    return json.dumps(obj, sort_keys=True, default=_refuse_datetime)


def _hash_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _safe(root: str, name: str) -> str:
    """Resolve `name` under `root`, refusing an absolute path, an empty
    path, or any `..`/`.`/empty component."""
    if not name or os.path.isabs(name):
        raise ReferenceError(f"refused: bad path {name!r}")
    parts = name.split("/")
    if any(p in ("", ".", "..") for p in parts):
        raise ReferenceError(f"refused: path escapes the claim: {name!r}")
    return os.path.join(root, *parts)


def _recipe_path(d: str) -> str:
    primary = os.path.join(d, RECIPE)
    if os.path.isfile(primary):
        return primary
    legacy = os.path.join(d, LEGACY_RECIPE)
    if os.path.isfile(legacy):
        return legacy
    raise ReferenceError(f"refused: no recipe found in {d!r}")


def load_recipe(d: str) -> dict:
    """Parse the recipe under claim directory `d`: either filename, the
    legacy `[record]` table name folded into `claim`."""
    path = _recipe_path(d)
    with open(path, "rb") as f:
        raw = tomllib.load(f)
    claim = raw.get("claim")
    if claim is None:
        claim = raw.get("record")
    if not isinstance(claim, dict):
        raise ReferenceError("refused: recipe is missing its [claim] table")
    raw = dict(raw)
    raw["claim"] = claim
    return raw


def _read_input_manifest(path: str) -> list:
    entries = []
    with open(path, "r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            head, _, tail = line.partition(" ")
            if len(head) == 64 and tail.strip() and all(
                c in "0123456789abcdef" for c in head
            ):
                entries.append(tail.strip())
            else:
                entries.append(line)
    return entries


def _inputs(d: str, recipe: dict) -> list:
    """The declared pinned inputs: an explicit list, or an
    `inputs_manifest` (itself a pinned input), plus a declared
    `environment` file."""
    claim = recipe.get("claim", {})
    manifest_name = claim.get("inputs_manifest")
    if manifest_name is not None:
        manifest_path = _safe(d, manifest_name)
        paths = [manifest_name]
        if os.path.isfile(manifest_path):
            paths.extend(_read_input_manifest(manifest_path))
    else:
        paths = list(claim.get("inputs", []))

    environment = claim.get("environment")
    if environment is not None and environment not in paths:
        paths.append(environment)
    return paths


def _claim_format(recipe: dict) -> int:
    return recipe.get("claim", {}).get("format", 1)


def _strip_guidance(step: dict) -> dict:
    return {k: v for k, v in step.items() if k not in GUIDANCE_KEYS}


def _preimage_recipe(recipe: dict) -> dict:
    """The recipe as it enters the root preimage (`spec/identity.md`).

    Format >= 3 strips every step's guidance keys (`guidance`, `request`).
    Format >= 4 additionally canonicalizes the step list -- a SET of
    obligations, not an authoring-order sequence -- sorting steps by their
    own canonical JSON encodings.
    """
    fmt = _claim_format(recipe)
    steps = list(recipe.get("step", []))
    if fmt >= 3:
        steps = [_strip_guidance(s) for s in steps]
    if fmt >= 4:
        steps = sorted(steps, key=_canonical_json)
    doc = dict(recipe)
    doc["step"] = steps
    return doc


def _step_class(step: dict) -> str:
    default = "generated" if step.get("kind") == "produce" else "pinned"
    return step.get("class", default)


def _parts(recipe: dict, d: str) -> dict:
    parts = {"digest": "sha256", "recipe": _canonical_json(_preimage_recipe(recipe))}
    for path in _inputs(d, recipe):
        full = _safe(d, path)
        parts["input:" + path] = _hash_file(full)
    for step in recipe.get("step", []):
        if _step_class(step) in GENERATED_CLASSES:
            continue
        output = step["output"]
        full = _safe(d, output)
        parts["pinned:" + output] = _hash_file(full)
    return parts


def root(d: str) -> str:
    """The claim's identity (`spec/identity.md`)."""
    recipe = load_recipe(d)
    parts = _parts(recipe, d)
    return hashlib.sha256(_canonical_json(parts).encode("utf-8")).hexdigest()


def _produces(recipe: dict) -> list:
    return [s for s in recipe.get("step", []) if s.get("kind") == "produce"]


def build_digest(d: str) -> str:
    """The digest of the generated bytes present (`spec/identity.md`).

    Only `produce` steps whose class is generated/free, and that do not
    declare `from`, contribute. An absent output is omitted, not an error.
    """
    recipe = load_recipe(d)
    pairs = []
    for step in _produces(recipe):
        if "from" in step:
            continue
        if _step_class(step) not in GENERATED_CLASSES:
            continue
        output = step["output"]
        full = _safe(d, output)
        if not os.path.isfile(full):
            continue
        pairs.append([output, _hash_file(full)])
    pairs.sort(key=lambda p: p[0])
    return hashlib.sha256(_canonical_json(pairs).encode("utf-8")).hexdigest()


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if len(argv) != 2 or argv[0] not in ("root", "digest"):
        print("usage: python -m reticuli.reference (root|digest) <dir>",
              file=sys.stderr)
        return 2
    verb, d = argv
    try:
        print(root(d) if verb == "root" else build_digest(d))
    except ReferenceError as e:
        print(e, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
