"""Transfer: deterministic export, verify-on-import (`spec/layers.md`'s
exchange layer).

`export` writes a tar containing exactly a claim's DECLARED content --
never a directory walk, so an undeclared stray file cannot ride along and
`.reticuli/ledger.jsonl` (volatile, host-local history) never travels.
Generated bytes travel too, unless `blind=True` withholds them -- the
rebuilder's room, carrying only what a producer must regrow. A sealed
component (`.reticuli/sealed/<name>`) always travels blind, recursively:
its claim (recipe, inputs, manifest) but never its own generated bytes.
Attestations (`attest.ATTEST`) travel as residue about the claim. Two
exports of the same, unchanged claim are byte-identical.

`import_` extracts into a fresh directory and verifies identity on the
received bytes alone -- the one thing a transfer must prove.

Stdlib only.
"""
import io
import os
import shutil
import tarfile

from . import attest as attest_mod
from . import kernel

_GENERATED = frozenset({"generated", "free"})


def _recipe_name(d: str) -> str:
    if os.path.isfile(os.path.join(d, kernel.RECIPE)):
        return kernel.RECIPE
    if os.path.isfile(os.path.join(d, kernel.LEGACY_RECIPE)):
        return kernel.LEGACY_RECIPE
    raise kernel.ClaimError(f"refused: no recipe found in {d!r}")


def _step_class(step: dict) -> str:
    return step.get("class", "generated" if step.get("kind") == "produce" else "pinned")


def _claim_entries(d: str, recipe: dict, blind: bool) -> list:
    """`(arcname, abspath)` pairs for a claim's own declared content."""
    entries = []
    recipe_name = _recipe_name(d)
    entries.append((recipe_name, os.path.join(d, recipe_name)))

    for inp in recipe.get("claim", {}).get("inputs", []):
        full = os.path.join(d, inp)
        if os.path.isfile(full):
            entries.append((inp, full))

    env_file = recipe.get("claim", {}).get("environment")
    if env_file:
        full = os.path.join(d, env_file)
        if os.path.isfile(full):
            entries.append((env_file, full))

    for step in recipe.get("step", []):
        output = step.get("output")
        if not output:
            continue
        generated = _step_class(step) in _GENERATED
        if generated and blind:
            continue
        full = os.path.join(d, output)
        if os.path.isfile(full):
            entries.append((output, full))
    return entries


def _component_blind(comp_dir: str, prefix: str) -> list:
    """A sealed component's claim, always blind, recursed into its own
    nested components."""
    try:
        recipe = kernel.load_recipe(comp_dir)
    except kernel.ClaimError:
        return []
    out = [(f"{prefix}/{arc}", full) for arc, full in _claim_entries(comp_dir, recipe, blind=True)]

    manifest_path = os.path.join(comp_dir, kernel.MANIFEST)
    if os.path.isfile(manifest_path):
        out.append((f"{prefix}/{kernel.MANIFEST}", manifest_path))

    nested_sealed = os.path.join(comp_dir, kernel.STORE, "sealed")
    if os.path.isdir(nested_sealed):
        for name in sorted(os.listdir(nested_sealed)):
            nd = os.path.join(nested_sealed, name)
            if os.path.isdir(nd):
                out.extend(_component_blind(nd, f"{prefix}/.reticuli/sealed/{name}"))
    return out


def _attest_entries(d: str) -> list:
    attest_dir = os.path.join(d, attest_mod.ATTEST)
    out = []
    if not os.path.isdir(attest_dir):
        return out
    for dirpath, _, files in sorted(os.walk(attest_dir)):
        for fname in sorted(files):
            full = os.path.join(dirpath, fname)
            arc = os.path.relpath(full, d).replace(os.sep, "/")
            out.append((arc, full))
    return out


def _write_deterministic_tar(entries: list, tar_path: str) -> None:
    seen = {}
    for arcname, full in entries:
        seen[arcname] = full
    with tarfile.open(tar_path, "w", format=tarfile.USTAR_FORMAT) as t:
        for arcname in sorted(seen):
            full = seen[arcname]
            with open(full, "rb") as f:
                data = f.read()
            info = tarfile.TarInfo(name=arcname)
            info.size = len(data)
            info.mtime = 0
            info.mode = 0o644
            info.uid = 0
            info.gid = 0
            info.uname = ""
            info.gname = ""
            info.type = tarfile.REGTYPE
            t.addfile(info, io.BytesIO(data))


def export(d: str, tar_path: str, blind: bool = False) -> dict:
    """Write a deterministic tar of `d`'s declared content; `blind=True`
    withholds generated bytes (the rebuilder's room)."""
    d = os.path.abspath(d)
    recipe = kernel.load_recipe(d)

    entries = _claim_entries(d, recipe, blind)

    manifest_path = os.path.join(d, kernel.MANIFEST)
    if os.path.isfile(manifest_path):
        entries.append((kernel.MANIFEST, manifest_path))

    sealed_root = os.path.join(d, kernel.STORE, "sealed")
    if os.path.isdir(sealed_root):
        for name in sorted(os.listdir(sealed_root)):
            comp_dir = os.path.join(sealed_root, name)
            if os.path.isdir(comp_dir):
                entries.extend(_component_blind(comp_dir, f".reticuli/deps/{name}"))

    entries.extend(_attest_entries(d))

    _write_deterministic_tar(entries, tar_path)
    return {"path": tar_path, "blind": blind}


def import_(tar_path: str, into: str) -> dict:
    """Extract `tar_path` into a fresh directory `into` and verify identity
    from the received bytes alone."""
    into = os.path.abspath(into)
    os.makedirs(into, exist_ok=True)
    with tarfile.open(tar_path, "r") as t:
        for member in t.getmembers():
            name = member.name
            if name.startswith("/") or os.path.isabs(name) or ".." in name.split("/"):
                raise kernel.ClaimError(f"refused: unsafe tar member {name!r}")
        try:
            t.extractall(into, filter="data")
        except TypeError:
            t.extractall(into)

    # the tar's `.reticuli/deps/<name>` naming is the archive's own
    # convention; on disk, a vendored component lives in the registry's
    # `.reticuli/sealed/<name>` convention, where the rest of the exchange
    # layer looks for it.
    deps_root = os.path.join(into, kernel.STORE, "deps")
    if os.path.isdir(deps_root):
        sealed_root = os.path.join(into, kernel.STORE, "sealed")
        os.makedirs(sealed_root, exist_ok=True)
        for name in sorted(os.listdir(deps_root)):
            src = os.path.join(deps_root, name)
            dst = os.path.join(sealed_root, name)
            if os.path.isdir(src) and not os.path.exists(dst):
                shutil.move(src, dst)
        shutil.rmtree(deps_root, ignore_errors=True)

    try:
        verified = kernel.verify(into)
    except kernel.ClaimError as e:
        return {"ok": False, "error": str(e)}
    return {"ok": verified["ok"], "root": verified["root"], "name": verified.get("name")}
