"""The argv grammar (`spec/layers.md`'s surface layer, the half of it that
is pure structure -- no layer call happens here, only `argparse` wiring).

Fourteen porcelain verbs (`PORCELAIN`), grouped in `_DESC` the same way
`ret -h` prints them; the folded aliases that keep an older spelling
working (`ALIASES`); and the plumbing every porcelain verb sits beside --
`hook` (the coding-agent event sink `hooks.main` wires up), `help`
(`_help_topic`/`_help_all`, reading `_FULL_HELP`), and `completion`
(`_completion`, generated from `verbs()` so it cannot drift from the
grammar it describes). `verbs()` is the one place that union is written
down; the conformance check asserts `_parser()`'s subcommands agree with
it.

A few verbs still carry a retired sibling's job as a flag, not a
separate word -- `pack --accept` (was `seal`), `status --tree` / `status
--claims` (were `tree` / `claims`), `record --key --as` / `record
--check` (was `attest`) -- so the word is gone from `verbs()` but the
behavior is not gone from the CLI.

Stdlib only.
"""
import argparse
import sys

_DESC = "Reticuli records and reproduces software claims.\n\nAuthoring\n    init        initialize a workspace\n    run         run and observe a command\n    status      show work, claims, and unresolved inputs\n    pack        create a claim from a project\n\nComposition and transport\n    pull        add another claim as a dependency\n    export      write a portable claim archive\n    import      restore a claim archive\n\nVerification\n    verify      verify claim identity\n    audit       rerun acceptance criteria\n    assess      measure specification strength\n\nReconstruction\n    rebuild     rebuild an implementation from a claim\n    crosscheck  compare independent realizations\n\nEvidence\n    record      write an execution record\n    sign        authorize a claim or proof"

_EPILOG = "See 'ret <command> -h' for command usage.\nSee 'ret help <command>' for detailed help; 'ret help -a' lists everything,\nincluding accepted older spellings."

# -- the grammar --------------------------------------------------------

PORCELAIN = (
    "init", "run", "status", "pack",
    "pull", "export", "import",
    "verify", "audit", "assess",
    "rebuild", "crosscheck",
    "record", "sign",
)

# Older spellings still accepted, folded onto the porcelain verb that now
# does the job -- distinct from RETIRED (`checks/parser_check.py`), whose
# names must never parse again, not even as an alias.
ALIASES = {}

_PLUMBING = ("hook", "help", "completion")

_FULL_HELP = {
    "init": (
        "ret init [path] [--name NAME] [--no-agent]\n\n"
        "Mark PATH (default: the current directory) as an authoring\n"
        "session: a .reticuli/ workspace marker, plus -- unless\n"
        "--no-agent -- the coding-agent hooks that let a producer's\n"
        "trace feed `status` and `pack`. Older spelling: `hooks` wired\n"
        "this separately; it is now init's default behavior."
    ),
    "run": (
        "ret run <cmd> [--ws DIR]\n\n"
        "Run CMD for real in the session at --ws (default: the current\n"
        "directory), appending a trace entry, and exit with CMD's own\n"
        "exit code -- usable as a predicate in a session script."
    ),
    "status": (
        "ret status [path] [--tree] [--claims] [--deps] [--structure]\n\n"
        "Show a session's trace and unresolved inputs by default. With\n"
        "--tree, show a sealed claim's dependency tree (older spelling:\n"
        "`tree`). With --claims, list the sealed claims a workspace\n"
        "holds (older spelling: `claims`). With --deps, show the\n"
        "registry's dependency map; with --structure, show a claim's\n"
        "anatomy."
    ),
    "pack": (
        "ret pack <root> <name> [--generated PAT...] [--inputs PAT...]\n"
        "          [--gate CMD] [--accept]\n\n"
        "Seal ROOT as a claim named NAME: GENERATED/INPUTS are glob\n"
        "patterns naming the implementation and the pinned acceptance\n"
        "surface. --accept also seals the result into the local store\n"
        "immediately (older spelling: `seal`)."
    ),
    "pull": (
        "ret pull <claim> <ws>\n\n"
        "Add CLAIM as a dependency of the session at WS, recording it\n"
        "in the session's registry."
    ),
    "export": (
        "ret export <claim> <tar-path> [--blind]\n\n"
        "Write CLAIM as a portable, deterministic archive at TAR-PATH.\n"
        "--blind omits a component's own generated bytes, carrying only\n"
        "what rebuilds them."
    ),
    "import": (
        "ret import <tar-path> <into>\n\n"
        "Restore a claim archive written by `export` into INTO."
    ),
    "verify": (
        "ret verify <claim>\n\n"
        "Recompute CLAIM's root and build digest and compare them\n"
        "against what is on disk."
    ),
    "audit": (
        "ret audit <claim>\n\n"
        "Rerun CLAIM's acceptance criteria against its current bytes."
    ),
    "assess": (
        "ret assess <claim> [--mutants N]\n\n"
        "Measure how strongly CLAIM's acceptance criteria pin its\n"
        "implementation, by mutation: N mutants (default: the module's\n"
        "own ceiling) are tried against the gate."
    ),
    "rebuild": (
        "ret rebuild <claim> <producer> <into> [--ws DIR] [--reuse]\n"
        "            [--no-guidance]\n\n"
        "Regrow CLAIM's generated outputs into INTO using PRODUCER\n"
        "(a named producer, or a literal shell command) until its gates\n"
        "pass. --ws makes this DAG-aware: every declared component is\n"
        "regrown first, leaf first; --reuse threads an existing sealed\n"
        "component's bytes through instead of regrowing it.\n"
        "--no-guidance withholds the recipe's own guidance text from\n"
        "the producer (v1: `realize`)."
    ),
    "crosscheck": (
        "ret crosscheck <leg1> <leg2> <leg3> [--mutants N] [--deep]\n\n"
        "Compare three independent realizations of the same claim for\n"
        "agreement. --deep also crosschecks each leg's own declared\n"
        "components (v1: `prove`)."
    ),
    "record": (
        "ret record <claim> [--out PATH]\n"
        "            [--key KEY --as IDENTITY] [--check [SIGNERS]]\n\n"
        "Write an execution record for CLAIM, to PATH if given. With\n"
        "--key and --as, authorize CLAIM as IDENTITY instead (older\n"
        "spelling: `attest`). With --check, verify CLAIM's existing\n"
        "signatures, optionally against SIGNERS (older spelling:\n"
        "`attest --check`)."
    ),
    "sign": (
        "ret sign <target> <key> [--as IDENTITY] [--ws DIR] [--proof]\n\n"
        "Authorize TARGET with KEY: a sealed claim as IDENTITY (v1:\n"
        "`mint`), or -- with --proof -- a proof document written by\n"
        "`record`."
    ),
    "hook": (
        "ret hook\n\n"
        "Internal: reads one event as JSON on stdin and appends it to\n"
        "the calling session's trace. Wired into a coding agent's own\n"
        "hook configuration by `init`; not for interactive use."
    ),
    "help": (
        "ret help [topic] [-a]\n\n"
        "Print detailed help for TOPIC (a command name). With -a / \n"
        "--all, list every command, including accepted older\n"
        "spellings."
    ),
    "completion": (
        "ret completion [bash|zsh]\n\n"
        "Print a shell completion script for the full grammar, so\n"
        "completion can never drift from the commands this parser\n"
        "actually registers."
    ),
}


def _add_verbose_json(sp: argparse.ArgumentParser) -> None:
    """Add the three flags every verb's output contract reads
    (`_cli/output.py`'s `_finish`/`_use_color`): `--json` (the machine
    envelope, and nothing else on stdout), `--verbose` (print result
    detail under the human line), `--color` (`always`/`never`/`auto`).
    """
    sp.add_argument("--json", action="store_true",
                     help="emit the machine-readable envelope, and nothing else")
    sp.add_argument("--verbose", action="store_true",
                     help="print result detail under the human-facing line")
    sp.add_argument("--color", choices=("auto", "always", "never"), default="auto",
                     help="color the human-facing line (default: auto)")


def _parser():
    """The top-level `ArgumentParser`, and a `dict` of every registered
    verb name (porcelain, alias, and plumbing) to the subparser that
    parses it -- `_help_topic`/`_completion` read the same dict so help
    and completion cannot drift from the grammar `_parser` builds.
    """
    p = argparse.ArgumentParser(
        prog="ret", description=_DESC, epilog=_EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--version", action="store_true", help="print the version and exit")
    sub = p.add_subparsers(dest="verb", metavar="<command>")
    subparsers = {}

    def add(name: str, help_text: str) -> argparse.ArgumentParser:
        canonical = ALIASES.get(name, name)
        sp = sub.add_parser(name, help=help_text, description=_FULL_HELP.get(canonical),
                             formatter_class=argparse.RawDescriptionHelpFormatter)
        subparsers[name] = sp
        return sp

    sp = add("init", "initialize a workspace")
    sp.add_argument("path", nargs="?", default=".")
    sp.add_argument("--name")
    sp.add_argument("--no-agent", action="store_true")
    _add_verbose_json(sp)

    sp = add("run", "run and observe a command")
    sp.add_argument("cmd")
    sp.add_argument("--ws", default=".")
    _add_verbose_json(sp)

    sp = add("status", "show work, claims, and unresolved inputs")
    sp.add_argument("path", nargs="?", default=".")
    sp.add_argument("--tree", action="store_true")
    sp.add_argument("--claims", action="store_true")
    sp.add_argument("--deps", action="store_true")
    sp.add_argument("--structure", action="store_true")
    _add_verbose_json(sp)

    sp = add("pack", "create a claim from a project")
    sp.add_argument("root")
    sp.add_argument("name")
    sp.add_argument("--generated", nargs="*", default=[], metavar="PATTERN")
    sp.add_argument("--inputs", nargs="*", default=[], metavar="PATTERN")
    sp.add_argument("--gate")
    sp.add_argument("--accept", action="store_true",
                     help="also seal the result into the local store (was: `seal`)")
    _add_verbose_json(sp)

    sp = add("pull", "add another claim as a dependency")
    sp.add_argument("claim")
    sp.add_argument("ws")
    _add_verbose_json(sp)

    sp = add("export", "write a portable claim archive")
    sp.add_argument("claim")
    sp.add_argument("tar_path", metavar="tar-path")
    sp.add_argument("--blind", action="store_true")
    _add_verbose_json(sp)

    sp = add("import", "restore a claim archive")
    sp.add_argument("tar_path", metavar="tar-path")
    sp.add_argument("into")
    _add_verbose_json(sp)

    sp = add("verify", "verify claim identity")
    sp.add_argument("claim")
    _add_verbose_json(sp)

    sp = add("audit", "rerun acceptance criteria")
    sp.add_argument("claim")
    _add_verbose_json(sp)

    sp = add("assess", "measure specification strength")
    sp.add_argument("claim")
    sp.add_argument("--mutants", type=int)
    _add_verbose_json(sp)

    sp = add("rebuild", "rebuild an implementation from a claim")
    sp.add_argument("claim")
    sp.add_argument("producer")
    sp.add_argument("into")
    sp.add_argument("--ws", help="rebuild every declared component first, leaf first")
    sp.add_argument("--reuse", action="store_true",
                     help="thread an existing sealed component through instead of regrowing it")
    sp.add_argument("--no-guidance", dest="guidance", action="store_false", default=True)
    _add_verbose_json(sp)

    sp = add("crosscheck", "compare independent realizations")
    sp.add_argument("leg1")
    sp.add_argument("leg2")
    sp.add_argument("leg3")
    sp.add_argument("--mutants", type=int)
    sp.add_argument("--deep", action="store_true",
                     help="also crosscheck each leg's own declared components")
    _add_verbose_json(sp)

    sp = add("record", "write an execution record")
    sp.add_argument("claim")
    sp.add_argument("--out", metavar="PATH")
    sp.add_argument("--key", help="authorize instead of recording (was: `attest`)")
    sp.add_argument("--as", dest="identity", metavar="IDENTITY")
    sp.add_argument("--check", nargs="?", const="", default=None, metavar="SIGNERS",
                     help="verify existing signatures instead of recording")
    _add_verbose_json(sp)

    sp = add("sign", "authorize a claim or proof")
    sp.add_argument("target")
    sp.add_argument("key")
    sp.add_argument("--as", dest="identity", metavar="IDENTITY")
    sp.add_argument("--ws")
    sp.add_argument("--proof", action="store_true",
                     help="target is a proof document written by `record`, not a claim")
    _add_verbose_json(sp)

    sp = add("hook", "internal: the coding-agent event hook")
    _add_verbose_json(sp)

    sp = add("help", "show detailed help for a command")
    sp.add_argument("topic", nargs="?")
    sp.add_argument("-a", "--all", action="store_true",
                     help="list every command, including accepted older spellings")

    sp = add("completion", "print a shell completion script")
    sp.add_argument("shell", nargs="?", default="bash", choices=("bash", "zsh"))

    return p, subparsers


def verbs() -> set:
    """Every verb name this parser registers: the porcelain, the folded
    aliases, and the plumbing -- the one place that union is written
    down; `_parser()`'s subcommands are asserted to agree with it."""
    return set(PORCELAIN) | set(ALIASES) | set(_PLUMBING)


# -- help and completion, both read back from the grammar above ------------

def _help_topic(name: str) -> None:
    """Print `name`'s detailed help -- `ret help <command>`. An alias
    resolves to its canonical verb's text, named as what it is."""
    canonical = ALIASES.get(name, name)
    text = _FULL_HELP.get(canonical)
    if text is None:
        sys.stderr.write(f"ret: help: no such command: {name!r}\n")
        return
    if canonical != name:
        print(f"{name!r} is an older spelling of {canonical!r}.\n")
    print(text)


def _help_all() -> None:
    """`ret help -a`: every porcelain verb, grouped as `_DESC` groups
    them, then the accepted older spellings."""
    print(_DESC)
    if ALIASES:
        print("\nOlder spellings\n" + "\n".join(
            f"    {alias:<10}  (now: {canonical})"
            for alias, canonical in sorted(ALIASES.items())
        ))


def _completion(shell: str) -> None:
    """A shell completion script for the full grammar, generated from
    `verbs()` so it cannot drift from the commands this module actually
    registers."""
    names = sorted(verbs())
    if shell == "zsh":
        print("#compdef ret")
        print("_ret() {")
        print(f"    compadd {' '.join(names)}")
        print("}")
        print("compdef _ret ret")
        return
    words = " ".join(names)
    print("_ret_complete() {")
    print('    local cur="${COMP_WORDS[COMP_CWORD]}"')
    print(f'    COMPREPLY=( $(compgen -W "{words}" -- "$cur") )')
    print("}")
    print("complete -F _ret_complete ret")
