"""Build: rebuilding generated outputs, and auditing a claim cold.

`rebuild` materializes a fresh room holding only the recipe and the pinned
inputs, runs a producer -- free of the gate's sandbox and environment scrub,
so it keeps the caller's network and HOME -- once per produce step, then
runs every gate in the room (scrubbed, sandboxed, bounded) until the claim
seals. `audit` re-earns a claim's verdict cold: identity first (a tampered
pinned input fails here, before any gate runs), then every gate re-run in a
fresh room against the generated bytes present, classifying each result as
`reproduced` (clean run, pinned bytes match what was sealed) or `mismatch`
(clean run, different bytes) rather than trusting what is already on disk.

Stdlib only, never the network -- except inside a producer's own room,
which this module deliberately leaves open (`spec/claim-format.md`).
"""
import json
import os
import shutil
import subprocess
import tempfile
import time

from . import core
from . import recipe as recipe_mod
from . import run as run_mod
from . import seal

sandbox_backend = run_mod.sandbox_backend


def _ssh_verify() -> bool:
    """A functional probe of `ssh-keygen -Y verify`: present on `PATH` is
    not enough to call it usable, the same honesty the sandbox probes in
    `run.py` apply to `sandbox-exec` / `bwrap`."""
    if not shutil.which("ssh-keygen"):
        return False
    try:
        done = subprocess.run(
            ["ssh-keygen", "-Y", "verify", "-f", os.devnull, "-I", "x",
             "-n", "x", "-s", os.devnull],
            input=b"", capture_output=True, timeout=10,
        )
    except OSError:
        return False
    return b"unknown option" not in (done.stderr or b"").lower()


def _authorized(recipe: dict) -> list:
    """Requirements this host cannot meet for this claim
    (`spec/claim-format.md`'s `[claim] requires`). An `ssh-keygen`
    requirement is additionally probed functionally via `_ssh_verify`,
    rather than merely checked for presence.
    """
    missing = list(run_mod.preflight(recipe))
    claim = (recipe or {}).get("claim", {})
    if "ssh-keygen" in claim.get("requires", []) and "ssh-keygen" not in missing:
        if not _ssh_verify():
            missing.append("ssh-keygen")
    return missing


def _step_guidance(step: dict):
    """A produce step's hint for a producer, under either spelling
    (`guidance`, older `request`); `None` when the step carries neither."""
    for key in core.GUIDANCE_KEYS:
        if key in step:
            return step[key]
    return None


def _materialize(d: str, into: str, recipe: dict, include_generated: bool = False,
                 input_from: str = None) -> None:
    """Build a fresh room at `into`: the recipe and every pinned input,
    copied byte for byte from `input_from or d`, so a cold run cannot read
    anything the claim did not declare. Pinned/validated step outputs are
    never copied in -- the room must earn them again. Generated outputs are
    copied in only to audit bytes already present (`include_generated`); a
    rebuild grows them fresh through a producer instead.
    """
    source = input_from or d
    recipe_src = recipe_mod.recipe_path(d)
    core._copy_into(recipe_src, os.path.join(into, os.path.basename(recipe_src)))
    for path in recipe_mod._inputs(d, recipe):
        core._copy_into(core._safe(source, path), core._safe(into, path))
    env_file = recipe.get("claim", {}).get("environment")
    if env_file:
        core._copy_into(core._safe(source, env_file), core._safe(into, env_file))
    if include_generated:
        for output in recipe_mod.generated_outputs(recipe):
            full = core._safe(d, output)
            if os.path.isfile(full):
                core._copy_into(full, core._safe(into, output))


def _read_usage(path: str) -> dict:
    """A producer's self-reported cost, read from the scratch file named by
    `RETICULI_USAGE`: any subset of `usd`/`tokens`/`calls`, each a
    non-negative number. Absent or malformed reports nothing -- unmeasured
    is never guessed at as zero."""
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(data, dict):
        return {}
    usage = {}
    for key in ("usd", "tokens", "calls"):
        value = data.get(key)
        if isinstance(value, (int, float)) and not isinstance(value, bool) and value >= 0:
            usage[key] = value
    return usage


def _produce(step: dict, into: str, producer: str, outs: list,
             guidance: bool, producer_env: dict) -> None:
    """Run the producer for one produce step: the caller's own environment,
    unscrubbed and unsandboxed (the producer is the caller's oracle, not a
    gate), with the target named absolutely and every generated output
    listed, named relatively (`spec/kernel-api.md`)."""
    output = step["output"]
    target = core._safe(into, output)
    os.makedirs(os.path.dirname(target) or into, exist_ok=True)

    usage_path = os.path.join(into, core.USAGE)
    env = dict(os.environ)
    env[core._ENV_OUTPUT] = target
    env[core._ENV_OUTPUTS] = json.dumps(outs)
    env[core._ENV_USAGE] = usage_path
    if guidance:
        hint = _step_guidance(step)
        if hint is not None:
            env[core._ENV_REQUEST] = hint
    if producer_env:
        env.update(producer_env)

    started = time.monotonic()
    try:
        done = subprocess.run([core._SHELL, "-c", producer], cwd=into, env=env,
                              capture_output=True, timeout=core.PRODUCER_TIMEOUT,
                              check=False)
    except subprocess.TimeoutExpired as e:
        raise core.ClaimError(f"refused: producer timed out for {output!r}") from e
    elapsed = time.monotonic() - started
    if done.returncode != 0:
        raise core.ClaimError(
            f"refused: producer failed for {output!r}: exit {done.returncode}"
        )

    entry = {"when": core._now(), "output": output, "seconds": elapsed}
    entry.update(_read_usage(usage_path))
    run_mod.ledger(into, entry)


def rebuild(d: str, producer: str, into: str, produce_from: dict = None,
            input_from: str = None, guidance: bool = True,
            producer_env: dict = None) -> dict:
    """Regrow a claim's generated outputs into `into` until its gates pass,
    then seal the result (v1: `realize`).

    `produce_from` supplies bytes directly for named outputs instead of
    invoking the producer -- the road a composed claim's `from`-sourced step
    travels. `input_from` reads the pinned inputs from an alternate
    directory. `guidance` withholds every producer hint when false, so a
    pass measures what the acceptance criteria alone carry.
    """
    recipe = recipe_mod.load_recipe(d)
    missing = _authorized(recipe)
    if missing:
        raise core.ClaimError(f"refused: missing requirement(s): {missing}")

    if os.path.isdir(into) and os.listdir(into):
        raise core.ClaimError(f"refused: rebuild target is not empty: {into!r}")
    os.makedirs(into, exist_ok=True)
    _materialize(d, into, recipe, input_from=input_from)
    os.makedirs(os.path.join(into, core.STORE), exist_ok=True)

    outs = recipe_mod.generated_outputs(recipe)
    produce_from = produce_from or {}
    for step in recipe_mod.produces(recipe):
        output = step["output"]
        source = produce_from.get(output)
        if source is not None:
            core._copy_into(source, core._safe(into, output))
            continue
        if "from" in step:
            continue  # sourced from a component this rebuild was not given
        _produce(step, into, producer, outs, guidance, producer_env)

    run_mod.furnish(into, recipe)
    quarantine = "none"
    for step in recipe_mod.gates(recipe):
        result = run_mod.run_gate(step["run"], into, recipe)
        quarantine = result["quarantine"]
        if result["status"] != "ok":
            raise core.ClaimError(
                f"refused: rebuild's gate did not pass: {step['output']!r} "
                f"({result['status']})"
            )

    manifest = seal.seal(into)
    return {"root": manifest["root"], "name": manifest["name"], "quarantine": quarantine}


def _compare_pin(path: str, expected_hash: str) -> str:
    """Compare a freshly re-earned output's bytes against its previously
    pinned hash: `reproduced` when they match, `mismatch` when they do not
    (`spec/verification.md`'s failure-class vocabulary)."""
    if not os.path.isfile(path):
        return "mismatch"
    return "reproduced" if core._hash_file(path) == expected_hash else "mismatch"


def audit(d: str) -> dict:
    """Re-earn a claim's verdict cold, trusting nothing recorded
    (`spec/verification.md`).

    Identity first: a tampered pinned input fails here, before any gate
    runs. Then every gate is re-run in a fresh room, built from the recipe
    and pinned inputs plus the generated bytes present now (no producer is
    invoked) -- never against the claim directory itself, so a gate's own
    writes cannot leak into what is being judged. Returns
    `{"ok", "verdict", "root", "gates": [{"output", "status", "quarantine"}]}`.
    """
    recipe = recipe_mod.load_recipe(d)
    missing = _authorized(recipe)
    if missing:
        return {"ok": False, "verdict": "environment", "missing": missing, "gates": []}

    manifest = seal.read_manifest(d)
    verified = seal.verify(d)
    if not verified["ok"]:
        return {"ok": False, "verdict": "broken", "root": manifest["root"],
                "recomputed": verified["recomputed"], "gates": []}

    room = tempfile.mkdtemp(prefix="reticuli-audit-")
    try:
        _materialize(d, room, recipe, include_generated=True)
        try:
            run_mod.furnish(room, recipe)
        except core.ClaimError:
            return {"ok": False, "verdict": "environment", "root": manifest["root"],
                    "gates": []}

        gate_rows = []
        earned = True
        for step in recipe_mod.gates(recipe):
            output = step["output"]
            expected_path = core._safe(d, output)
            expected_hash = (core._hash_file(expected_path)
                             if os.path.isfile(expected_path) else None)
            result = run_mod.run_gate(step["run"], room, recipe)
            status = result["status"]
            if status == "ok":
                fresh_path = core._safe(room, output)
                status = (_compare_pin(fresh_path, expected_hash)
                          if expected_hash is not None else "mismatch")
            gate_rows.append({"output": output, "status": status,
                              "quarantine": result["quarantine"]})
            if status not in ("ok", "reproduced"):
                earned = False
        return {"ok": earned, "verdict": "earned" if earned else "broken",
                "root": manifest["root"], "gates": gate_rows}
    finally:
        shutil.rmtree(room, ignore_errors=True)
