"""Kernel core: the two boundaries and the primitives beneath everything.

The path boundary (`_safe`) refuses a recipe-declared name that escapes the
claim directory or aliases through a symlink. The bytes boundary
(`_hash_file`) is a plain sha256 of a regular file's bytes. `_write_json`
writes a JSON document atomically. `ClaimError` is the one refusal type the
kernel raises, always with a reason. Everything else here is a protocol
constant or a small host-facing helper that the layers above import.

Stdlib only, never the network.
"""
import hashlib
import json
import os
import platform
import shutil
import sys
import tempfile
from datetime import datetime, timezone

# -- Protocol constants: the on-disk / environment contract, shared verbatim
#    across the kernel and with the record format. ----------------------
NAMESPACE = "reticuli"
DIGEST = "sha256"
FORMAT = 4
STORE = ".reticuli"
MANIFEST = ".reticuli/manifest.json"
RECIPE = "reticuli.toml"
LEGACY_RECIPE = "claim.toml"
LEDGER = ".reticuli/ledger.jsonl"
USAGE = ".reticuli/usage.json"
MUTATION_RESIDUE = ".reticuli/mutation_score.json"
SIGN_DIR = ".reticuli/mint"
SIGN_NAMESPACE = "reticuli.mint"

_JAILED = "RETICULI_JAILED"
_ENV_CACHE = "RETICULI_ENV_CACHE"
_ENV_CLAIM = "RETICULI_CLAIM"
_ENV_MODEL = "RETICULI_MODEL"
_ENV_OUTPUT = "RETICULI_OUTPUT"
_ENV_OUTPUTS = "RETICULI_OUTPUTS"
_ENV_REQUEST = "RETICULI_REQUEST"
_ENV_SIGNERS = "RETICULI_SIGNERS"
_ENV_TIMEOUT = "RETICULI_GATE_TIMEOUT"
_ENV_TOLERANCE = "RETICULI_TOLERANCE"
_ENV_USAGE = "RETICULI_USAGE"
_ENV_VENDOR = "RETICULI_VENDOR"

_KEEP_ENV = ("PATH", "HOME", "TMPDIR", "LANG", "LC_ALL", "TZ", "RETICULI_JAILED")

# -- Tuning constants and host-derived values; their KIND is the seam, not
#    their exact value. ---------------------------------------------------
GATE_TIMEOUT = 120.0
FURNISH_TIMEOUT = 300.0
PRODUCER_TIMEOUT = 600.0
TOLERANCE = 2.0
MUTANT_CEILING = 64
MUTANT_FLOOR = 8
MUTANT_HEADROOM = 1.25

COST_KEYS = ("usd", "tokens", "calls", "seconds")
COST_LADDER = ("usd", "tokens", "calls", "seconds")
COST_UNITS = ("usd", "tokens", "calls", "seconds")
GUIDANCE_KEYS = ("guidance", "request")

# The step-kind vocabulary: exactly the two kinds the claim format defines.
KINDS = frozenset({"produce", "gate"})

_SHELL = "/bin/sh"


class ClaimError(Exception):
    """A refusal with a reason -- the only error the kernel raises."""


def _hash_file(path: str) -> str:
    """The bytes boundary: a plain sha256 of a regular file's bytes.

    Refuses anything that is not a regular file with a single hard link --
    the filesystem-aliasing cases a content address cannot tolerate.
    """
    st = os.lstat(path)
    if not os.path.isfile(path) or os.path.islink(path):
        raise ClaimError(f"refused: not a regular file: {path!r}")
    if st.st_nlink != 1:
        raise ClaimError(f"refused: hashed file must have a single hard link: {path!r}")
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _safe(root: str, name: str) -> str:
    """The path boundary: resolve `name` under `root`, or refuse.

    Refused: an absolute path, an empty path, any `..` component, and any
    component that is a symlink -- even one whose target stays inside the
    claim, which could alias generated bytes as a pinned name.
    """
    if not name:
        raise ClaimError("refused: empty path")
    if os.path.isabs(name):
        raise ClaimError(f"refused: absolute path {name!r}")
    parts = name.split("/")
    for part in parts:
        if part in ("", ".", ".."):
            raise ClaimError(f"refused: path escapes the claim: {name!r}")

    realroot = os.path.realpath(root)
    cur = realroot
    for part in parts:
        cur = os.path.join(cur, part)
        if os.path.islink(cur):
            raise ClaimError(f"refused: symlink component in {name!r}")

    if not (cur == realroot or cur.startswith(realroot + os.sep)):
        raise ClaimError(f"refused: path escapes the claim: {name!r}")
    return cur


def _write_json(path: str, obj) -> None:
    """Atomic JSON write: build the bytes off to the side, then rename in."""
    d = os.path.dirname(path) or "."
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".tmp-", suffix=".json")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(obj, f, sort_keys=True, indent=2)
            f.write("\n")
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _now() -> str:
    """UTC time of recording, `YYYY-MM-DDTHH:MM:SSZ` (spec/record.md)."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _judging_host() -> dict:
    """The host that judges a gate: `platform`, `machine`, `runtime`."""
    return {
        "platform": sys.platform,
        "machine": platform.machine(),
        "runtime": f"{platform.python_implementation()} {platform.python_version()}",
    }


def _copy_into(src: str, dst: str) -> str:
    """Copy a file or directory tree from `src` to `dst`, refusing symlinks."""
    if os.path.islink(src):
        raise ClaimError(f"refused: symlink {src!r}")
    if os.path.isdir(src):
        os.makedirs(dst, exist_ok=True)
        for entry in sorted(os.listdir(src)):
            _copy_into(os.path.join(src, entry), os.path.join(dst, entry))
    else:
        parent = os.path.dirname(dst) or "."
        os.makedirs(parent, exist_ok=True)
        shutil.copy2(src, dst)
    return dst
