"""Crosscheck: the three-machine test, cold audit, and mutation testing.

`_audit_dir` re-earns a claim's verdict cold (identity first, then every
gate re-run in a fresh room against the generated bytes present); it is the
one place "earned vs. carried" is decided, and both `kernel.audit` and this
module's own leg inspection in `crosscheck` share it. `gate_deciders` /
`vacuous_gates` read a gate's `run` command to name the workspace files that
decide it, so a gate whose every decider is itself generated can be told
apart from a claim. `mutation_score` draws deterministic mutants of the
generated code from the claim's root and re-audits each one, cold, to
measure what the pinned criteria actually catch. `crosscheck` composes all
of this into the three-machine test (`spec/verification.md`): one root
across all three legs, byte reuse from M1 to M2, every verdict earned, the
cost band and every condition the claim itself declares -- a three-valued
verdict, because a declared condition nobody measured is neither proven nor
disproven.

A leg is a claim directory (judged live) or a signed record file
(`spec/record.md`, judged as relayed fact) -- the two transports mix freely
and must reach the same verdict.

Stdlib only, never the network.
"""
import ast
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import tempfile
import tomllib

from . import attest
from . import build as build_mod
from . import core
from . import identity as identity_mod
from . import recipe as recipe_mod
from . import run as run_mod
from . import seal as seal_mod


def _in_band(fn, *args, **kwargs):
    try:
        return fn(*args, **kwargs)
    except core.ClaimError:
        raise
    except (OSError, ValueError, KeyError, TypeError, UnicodeDecodeError,
            json.JSONDecodeError) as e:
        raise core.ClaimError(f"refused: {e}") from e


import contextlib


@contextlib.contextmanager
def _prepended_path(bin_dir):
    """Put `bin_dir` first on `PATH` for the duration of the block --
    `furnish` builds a private venv and hands back its bin directory, but
    nothing downstream (`run_gate`'s environment scrub keeps `PATH`
    verbatim) puts it on the gate's `PATH` unless a caller does."""
    if not bin_dir:
        yield
        return
    saved = os.environ.get("PATH", "")
    os.environ["PATH"] = bin_dir + os.pathsep + saved
    try:
        yield
    finally:
        os.environ["PATH"] = saved


def furnish(d: str, recipe: dict) -> dict:
    """`_kernel/run.py`'s `furnish`, run with the claim directory as the
    working directory.

    The given `furnish` invokes `pip install -r <absolute path>` without
    setting the subprocess's `cwd`, so a `[claim] environment` file (the
    standard pip requirements format) naming an artifact by a RELATIVE
    path -- `./some.whl --hash=...`, the ordinary shape for a claim that
    ships its own wheel as a pinned input -- resolves against whatever
    directory the calling process happened to be in, not the room
    actually being furnished. Furnishing is the one gate-adjacent action
    this project deliberately lets reach the network; running it from the
    room is what makes a room-relative artifact path mean what it says.
    """
    cwd = os.getcwd()
    try:
        os.chdir(d)
        return run_mod.furnish(d, recipe)
    finally:
        os.chdir(cwd)


def load_recipe(d: str) -> dict:
    """Parse and validate a recipe, exempting GENERATED-class step outputs
    from the path-confinement check.

    `_kernel/recipe.py`'s own `load_recipe` checks every step's output
    regardless of class, which refuses a generated output that happens to
    be a symlink before a producer has regrown it and before `audit`'s own
    confinement check (which DOES cover generated outputs, at the moment
    it copies one) gets a chance to be the one that refuses. Confinement
    on a generated output belongs to the gates that touch its bytes, not
    to parsing; everything else here matches `_kernel/recipe.py` exactly.
    """
    d = os.path.abspath(d)

    def _run():
        path = recipe_mod.recipe_path(d)
        try:
            with open(path, "rb") as f:
                raw = tomllib.load(f)
        except tomllib.TOMLDecodeError as e:
            raise core.ClaimError(f"refused: malformed recipe {path!r}: {e}") from e
        except OSError as e:
            raise core.ClaimError(f"refused: cannot read recipe {path!r}: {e}") from e

        claim = raw.get("claim")
        if claim is None:
            claim = raw.get("record")
        if not isinstance(claim, dict):
            raise core.ClaimError("refused: recipe is missing its [claim] table")
        raw = dict(raw)
        raw["claim"] = claim

        name = claim.get("name")
        if not isinstance(name, str):
            raise core.ClaimError("refused: [claim] name is required and must be a string")

        fmt = claim.get("format", 1)
        if not isinstance(fmt, int) or isinstance(fmt, bool) or fmt < 1:
            raise core.ClaimError("refused: [claim] format must be a positive integer")
        if fmt > core.FORMAT:
            raise core.ClaimError(
                f"claim format {fmt} is newer than this kernel understands "
                f"(format {core.FORMAT}); upgrade reticuli to read it"
            )

        steps = raw.get("step", [])
        if not isinstance(steps, list):
            raise core.ClaimError("refused: [[step]] must be an array of tables")
        for step in steps:
            if not isinstance(step, dict):
                raise core.ClaimError("refused: each step must be a table")
            kind = step.get("kind")
            if kind not in core.KINDS:
                raise core.ClaimError(
                    f"refused: step kind must be one of {sorted(core.KINDS)}: {kind!r}"
                )
            output = step.get("output")
            if not isinstance(output, str) or not output:
                raise core.ClaimError("refused: every step needs a string output")
            if identity_mod._step_class(step) not in recipe_mod.GENERATED_CLASSES:
                core._safe(d, output)
            if kind == "gate" and not isinstance(step.get("run"), str):
                raise core.ClaimError("refused: a gate step needs a string 'run'")

        for input_path in recipe_mod._inputs(d, raw):
            core._safe(d, input_path)

        environment = claim.get("environment")
        if environment is not None:
            if not isinstance(environment, str):
                raise core.ClaimError("refused: [claim] environment must be a string path")
            core._safe(d, environment)

        envelope = claim.get("envelope")
        if envelope is not None:
            if not isinstance(envelope, dict) or not envelope:
                raise core.ClaimError(
                    "refused: [claim] envelope must be a non-empty table"
                )
            for unit, ceiling in envelope.items():
                if unit not in core.COST_UNITS:
                    raise core.ClaimError(
                        f"refused: [claim] envelope names an unknown unit: {unit!r}"
                    )
                if (isinstance(ceiling, bool) or not isinstance(ceiling, (int, float))
                        or ceiling <= 0):
                    raise core.ClaimError(
                        f"refused: [claim] envelope.{unit} must be a positive number"
                    )

        return raw
    return _in_band(_run)


def root(recipe: dict, d: str) -> str:
    """The claim's identity, with `[claim] environment` folded in as an
    implicit pinned input (`spec/claim-format.md`: "automatically a pinned
    input").

    `_kernel/identity.py`'s own `root`/`_parts` never look at
    `[claim] environment` at all, so two claims differing only in which
    dependency versions they pin would share a root -- exactly the gap
    the environment pin exists to close. This hashes the declared
    environment file the same way `_parts` hashes any other declared
    input, under the same `input:` prefix, then hashes the augmented
    parts map exactly as `_kernel/identity.py` does.
    """
    d = os.path.abspath(d)

    def _run():
        parts = dict(identity_mod._parts(recipe, d))
        env_file = (recipe.get("claim") or {}).get("environment")
        if env_file:
            full = core._safe(d, env_file)
            parts["input:" + env_file] = core._hash_file(full)
        return hashlib.sha256(
            identity_mod._canonical_json(parts).encode("utf-8")
        ).hexdigest()
    return _in_band(_run)


def _rewrite_room_recipe(d: str, into: str, recipe: dict) -> None:
    """At format >= 3, overwrite the room's copied recipe file with
    exactly the guidance-stripped serialization that entered the root
    preimage (`spec/identity.md`'s format-3 rule).

    A judging room must match the name the root names: a gate that reads
    its own recipe file (as this project's own format-3 conformance gate
    deliberately does) must find exactly what the root hashed, or two
    claims sharing a root -- differing only in a producer hint's wording
    -- could accept differently for the same identity. Formats 1 and 2
    keep the room's recipe byte-identical to the claim's, as before.
    """
    fmt = recipe.get("claim", {}).get("format", 1)
    if fmt < 3:
        return
    recipe_name = os.path.basename(recipe_mod.recipe_path(d))
    stripped = identity_mod._preimage_recipe(recipe)
    text = identity_mod._canonical_json(stripped)
    with open(os.path.join(into, recipe_name), "w", encoding="utf-8") as f:
        f.write(text)


# ---------------------------------------------------------------------------
# Gate deciders: which workspace files a gate's shell command treats as
# deciding its verdict -- an interpreter's script argument, or a workspace
# executable invoked directly. A bare system tool (grep, printf) names
# nothing; it is not a workspace script.
# ---------------------------------------------------------------------------

_INTERPRETERS = frozenset({'Rscript', 'awk', 'lua', 'python', 'python3', 'python2',
                           'node', 'ruby', 'perl', 'dash', 'deno', 'py.test', 'zsh',
                           'tclsh', 'php', 'sh', 'bash', 'py', 'pytest'})
_OPERATORS = frozenset({'&', '\n', '|', '||', '&&', ';'})
_SKIP_VALUE = frozenset({'-m', '-p', '--module', '-X', '-c', '-e'})
_REDIRECTS = frozenset({'>', '>>', '<', '1>', '2>', '2>>', '&>'})

_SEGMENT_SPLIT = re.compile(r'\|\||&&|[;&|\n]')


def gate_deciders(cmd: str) -> list:
    """The workspace files a gate's `run` command treats as deciding its
    verdict -- an interpreter's script argument (module/`-c` values
    excluded), or a workspace-relative executable invoked directly. A bare
    system command (no path, no known interpreter) names nothing."""
    deciders = []
    for segment in _SEGMENT_SPLIT.split(cmd):
        segment = segment.strip()
        if not segment:
            continue
        try:
            tokens = shlex.split(segment)
        except ValueError:
            continue
        if not tokens:
            continue
        first = tokens[0]
        base = os.path.basename(first)
        if base in _INTERPRETERS:
            i = 0
            rest = tokens[1:]
            while i < len(rest):
                tok = rest[i]
                if tok in _REDIRECTS:
                    break
                if tok in _SKIP_VALUE:
                    i += 2
                    continue
                if tok.startswith("-"):
                    i += 1
                    continue
                deciders.append(tok)
                i += 1
        elif "/" in first:
            deciders.append(first[2:] if first.startswith("./") else first)
    return deciders


def vacuous_gates(recipe: dict) -> list:
    """Gate outputs whose every decider is itself generated -- the verdict
    depends on no claim; a gate that names no workspace script decides by
    the recipe text alone, and is not vacuous."""
    generated = set(recipe_mod.generated_outputs(recipe))
    vacuous = []
    for step in recipe_mod.gates(recipe):
        deciders = gate_deciders(step.get("run", ""))
        if deciders and all(d in generated for d in deciders):
            vacuous.append(step["output"])
    return vacuous


# ---------------------------------------------------------------------------
# Mutation testing: deterministic mutants of generated Python source, drawn
# from the claim's root, re-audited cold.
# ---------------------------------------------------------------------------

_COMPARISON = ('>', '<', '>=', '<=', '==', '!=')
_ARITHMETIC = ('+', '-', '*', '/', '//', '%', '**')

_OP_ALTS = {
    '>': ('<', '>=', '=='), '<': ('>', '<=', '=='),
    '>=': ('<=', '>', '<'), '<=': ('>=', '<', '>'),
    '==': ('!=',), '!=': ('==',),
    '+': ('-',), '-': ('+',),
    '*': ('/',), '/': ('*',),
    '//': ('/',), '%': ('*',), '**': ('*',),
}
_OP_KIND = {op: "comparison" for op in _COMPARISON}
_OP_KIND.update({op: "arithmetic" for op in _ARITHMETIC})

_STRING_LITERAL = re.compile(
    r"('''(?:[^\\]|\\.)*?'''|\"\"\"(?:[^\\]|\\.)*?\"\"\"|"
    r"'(?:[^'\\\n]|\\.)*'|\"(?:[^\"\\\n]|\\.)*\")",
    re.DOTALL,
)
_WORD_ALTS = {
    'and': 'or', 'or': 'and',
    'True': 'False', 'False': 'True',
    'break': 'continue', 'continue': 'break',
    'any': 'all', 'all': 'any',
    'min': 'max', 'max': 'min',
}
_WORD_RE = re.compile(r'\b[A-Za-z_][A-Za-z0-9_]*\b')

_CMP_SYMBOLS = {ast.Gt: '>', ast.Lt: '<', ast.GtE: '>=', ast.LtE: '<=',
                ast.Eq: '==', ast.NotEq: '!='}
_BIN_SYMBOLS = {ast.Add: '+', ast.Sub: '-', ast.Mult: '*', ast.Div: '/',
                ast.FloorDiv: '//', ast.Mod: '%', ast.Pow: '**'}


def _splice(source: str, start: int, end: int, replacement: str) -> str:
    """Replace `source[start:end]` with `replacement` -- the one text edit
    every mutant is built from."""
    return source[:start] + replacement + source[end:]


def _label(kind: str, *parts) -> str:
    """A deterministic, human-readable name for one mutation."""
    return kind + ":" + ":".join(str(p) for p in parts)


def _edit(source: str, start: int, end: int, replacement: str, label: str) -> dict:
    """One candidate mutant: the spliced source text, and its label."""
    return {"text": _splice(source, start, end, replacement), "label": label}


def _docstring_spans(source: str) -> list:
    """Every string-literal span in `source` (docstrings included) -- text
    a token mutant must not rewrite inside."""
    return [m.span() for m in _STRING_LITERAL.finditer(source)]


def _line_offsets(source: str) -> list:
    """Cumulative byte offset of the start of each line, for converting an
    ast node's (lineno, col_offset) into a flat character offset."""
    offsets = [0]
    for line in source.splitlines(keepends=True):
        offsets.append(offsets[-1] + len(line))
    return offsets


def _node_span(offsets: list, lineno: int, col: int) -> int:
    """A flat character offset for one (1-indexed line, 0-indexed column)."""
    return offsets[lineno - 1] + col


def _span_text(source: str, start: int, end: int) -> str:
    """The literal text of one span -- used to locate an operator symbol."""
    return source[start:end]


def _op_between(source: str, offsets: list, left, right, candidates) -> tuple:
    """Find an operator symbol (one of `candidates`) between two AST
    operands; returns `(start, end, symbol)` or `None`."""
    start = _node_span(offsets, left.end_lineno, left.end_col_offset)
    stop = _node_span(offsets, right.lineno, right.col_offset)
    window = _span_text(source, start, stop)
    for sym in sorted(candidates, key=len, reverse=True):
        idx = window.find(sym)
        if idx != -1:
            return start + idx, start + idx + len(sym), sym
    return None


def _structural_mutants(source: str) -> list:
    """AST-level mutants: each comparison or arithmetic operator spliced
    for one alternative of the same kind."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    offsets = _line_offsets(source)
    mutants = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Compare):
            operands = [node.left] + list(node.comparators)
            for i, op in enumerate(node.ops):
                sym = _CMP_SYMBOLS.get(type(op))
                if sym is None:
                    continue
                found = _op_between(source, offsets, operands[i], operands[i + 1],
                                    _COMPARISON)
                if not found:
                    continue
                start, end, text = found
                for alt in _OP_ALTS.get(text, ()):
                    mutants.append(_edit(source, start, end, alt,
                                         _label("cmp", text, alt, start)))
        elif isinstance(node, ast.BinOp):
            sym = _BIN_SYMBOLS.get(type(node.op))
            if sym is None:
                continue
            found = _op_between(source, offsets, node.left, node.right, _ARITHMETIC)
            if not found:
                continue
            start, end, text = found
            for alt in _OP_ALTS.get(text, ()):
                mutants.append(_edit(source, start, end, alt,
                                     _label("bin", text, alt, start)))
    return mutants


def _token_mutants(source: str) -> list:
    """Text-level mutants: a whole word swapped for its alternative
    (`_WORD_ALTS`), skipping any occurrence inside a string literal."""
    protected = _docstring_spans(source)
    mutants = []
    for m in _WORD_RE.finditer(source):
        alt = _WORD_ALTS.get(m.group(0))
        if alt is None:
            continue
        if any(s <= m.start() < e for s, e in protected):
            continue
        mutants.append(_edit(source, m.start(), m.end(), alt,
                             _label("word", m.group(0), alt, m.start())))
    return mutants


def _named(mutants: list) -> list:
    """Deduplicate mutants by resulting text, keeping the first label."""
    seen = set()
    out = []
    for m in mutants:
        if m["text"] in seen:
            continue
        seen.add(m["text"])
        out.append(m)
    return out


def _mutants(source: str) -> list:
    """Every candidate mutant of one source file: structural, then token,
    deduplicated."""
    return _named(_structural_mutants(source) + _token_mutants(source))


def _machine(seed: bytes):
    """A deterministic draw function seeded from `seed`: `machine(n)`
    returns a reproducible pseudo-random integer in `[0, n)`, built from a
    SHA-256 counter stream rather than the stdlib `random` module, so the
    sequence cannot drift across interpreter versions."""
    counter = [0]

    def draw(n: int) -> int:
        counter[0] += 1
        digest = hashlib.sha256(seed + counter[0].to_bytes(8, "big")).digest()
        return int.from_bytes(digest[:8], "big") % n
    return draw


def _draw_order(seed: bytes, n: int) -> list:
    """A deterministic permutation of `range(n)`, Fisher-Yates shuffled by
    `_machine(seed)`."""
    order = list(range(n))
    if n <= 1:
        return order
    draw = _machine(seed)
    for i in range(n - 1, 0, -1):
        j = draw(i + 1)
        order[i], order[j] = order[j], order[i]
    return order


def _mutant_order(root: str, n: int) -> list:
    """The deterministic draw order for `n` mutants of a claim named `root`."""
    return _draw_order(root.encode("utf-8"), n)


def mutation_score(d: str, max_mutants: int = None) -> dict:
    """Mutation-test a claim's generated Python outputs: draw mutants of
    each deterministically from the root, re-audit each cold, and report
    the kill rate as residue (`spec/claim-format.md`'s teeth).

    Never touches the root: `mutation_score.json` is store residue only.
    """
    d = os.path.abspath(d)
    recipe = load_recipe(d)
    manifest = seal_mod.read_manifest(d)
    root_value = manifest["root"]

    pool = []
    for output in recipe_mod.generated_outputs(recipe):
        if not output.endswith(".py"):
            continue
        full = core._safe(d, output)
        if not os.path.isfile(full):
            continue
        with open(full, "r", encoding="utf-8") as f:
            source = f.read()
        for m in _mutants(source):
            pool.append((output, m))

    n = len(pool)
    cap = core.MUTANT_CEILING if max_mutants is None else max_mutants
    cap = max(0, min(cap, n))
    order = _mutant_order(root_value, n)[:cap]
    chosen = [pool[i] for i in order]

    killed = 0
    survivors = []
    for output, mutant in chosen:
        room = tempfile.mkdtemp(prefix="reticuli-mutant-")
        try:
            build_mod._materialize(d, room, recipe, include_generated=True)
            _rewrite_room_recipe(d, room, recipe)
            with open(core._safe(room, output), "w", encoding="utf-8") as f:
                f.write(mutant["text"])
            try:
                furnished = furnish(room, recipe)
            except core.ClaimError:
                survivors.append(mutant["label"])
                continue
            dead = False
            with _prepended_path((furnished or {}).get("path")):
                for step in recipe_mod.gates(recipe):
                    result = run_mod.run_gate(step["run"], room, recipe)
                    if result["status"] != "ok":
                        dead = True
                        break
            if dead:
                killed += 1
            else:
                survivors.append(mutant["label"])
        finally:
            shutil.rmtree(room, ignore_errors=True)

    rate = (killed / len(chosen)) if chosen else 0.0
    result = {"mutants": len(chosen), "killed": killed, "rate": rate,
              "survivors": sorted(survivors)}
    floor = recipe.get("claim", {}).get("mutation_floor")
    if floor is not None:
        result["ok"] = rate >= floor
    core._write_json(os.path.join(d, core.MUTATION_RESIDUE), result)
    return result


# ---------------------------------------------------------------------------
# Cold audit: the deep re-earning both `kernel.audit` and the crosscheck's
# leg inspection share.
# ---------------------------------------------------------------------------

def _audit_dir(d: str, produce_from: dict = None) -> dict:
    """Re-earn a claim's verdict cold: identity first, then every gate
    re-run in a fresh room holding the recipe, pinned inputs, and the
    generated bytes present (optionally substituted per `produce_from`).

    Returns `{"ok", "verdict", "root", "gates": [...]}`; an environment
    failure additionally carries `"environment"` (missing requirements, or
    the unfurnishable environment file), with one gate row per declared
    gate, each `status: "environment"`, `quarantine: None`.
    """
    def _run():
        recipe = load_recipe(d)
        gate_steps = recipe_mod.gates(recipe)
        missing = build_mod._authorized(recipe)
        if missing:
            return {"ok": False, "verdict": "environment", "environment": missing,
                    "root": None,
                    "gates": [{"output": s["output"], "status": "environment",
                              "quarantine": None} for s in gate_steps]}

        manifest = seal_mod.read_manifest(d)
        recomputed = root(recipe, d)
        if recomputed != manifest["root"]:
            return {"ok": False, "verdict": "broken", "root": manifest["root"],
                    "recomputed": recomputed, "gates": []}

        room = tempfile.mkdtemp(prefix="reticuli-audit-")
        try:
            build_mod._materialize(d, room, recipe, include_generated=True)
            _rewrite_room_recipe(d, room, recipe)
            if produce_from:
                for output, source in produce_from.items():
                    core._copy_into(source, core._safe(room, output))
            try:
                furnished = furnish(room, recipe)
            except core.ClaimError:
                env_file = recipe.get("claim", {}).get("environment")
                return {"ok": False, "verdict": "environment",
                        "environment": [env_file] if env_file else [],
                        "root": manifest["root"],
                        "gates": [{"output": s["output"], "status": "environment",
                                  "quarantine": None} for s in gate_steps]}

            gate_rows = []
            earned = True
            with _prepended_path((furnished or {}).get("path")):
                for step in gate_steps:
                    output = step["output"]
                    expected_path = core._safe(d, output)
                    expected_hash = (core._hash_file(expected_path)
                                    if os.path.isfile(expected_path) else None)
                    result = run_mod.run_gate(step["run"], room, recipe)
                    status = result["status"]
                    if status == "ok":
                        fresh_path = core._safe(room, output)
                        if expected_hash is None or not os.path.isfile(fresh_path):
                            status = "mismatch"
                        elif core._hash_file(fresh_path) != expected_hash:
                            status = "mismatch"
                        else:
                            status = "ok"
                    gate_rows.append({"output": output, "status": status,
                                      "quarantine": result["quarantine"]})
                    if status != "ok":
                        earned = False
            return {"ok": earned, "verdict": "earned" if earned else "broken",
                    "root": manifest["root"], "gates": gate_rows}
        finally:
            shutil.rmtree(room, ignore_errors=True)

    return _in_band(_run)


# ---------------------------------------------------------------------------
# Records as frozen legs (`spec/record.md`), read strictly -- the file must
# be its own canonical bytes, or it is not the record it claims to be.
#
# `_kernel/attest.py`'s `record_validate` understands only record version 1
# -- it refuses the `claim` member and any `record` value but 1, so a
# version-2 record (which carries the claim's declared obligations,
# `spec/record.md`'s 2026-09-28 revision) never reads back as one. This
# module owns the full version 1/2 vocabulary instead, reusing attest's
# per-field patterns and sets where the shape is identical.
# ---------------------------------------------------------------------------

RECORD_FORMAT = 2
_RECORD_MEMBERS_V1 = frozenset({
    "record", "name", "root", "build_digest", "gates", "cost", "producer",
    "environment", "when", "tool",
})
_RECORD_MEMBERS_V2 = _RECORD_MEMBERS_V1 | {"claim"}
_RECORD_REQUIRED_V1 = frozenset({
    "record", "name", "root", "build_digest", "gates", "environment", "when",
})
_RECORD_REQUIRED_V2 = _RECORD_REQUIRED_V1 | {"claim"}
_CLAIM_OBLIGATIONS = frozenset({"tolerance", "envelope", "mutation_floor"})


def _refuse_number(value, label: str) -> None:
    if isinstance(value, bool) or not isinstance(value, (int, float)) or value < 0:
        raise core.ClaimError(f"refused: {label} must be a non-negative number")


def record_validate(doc) -> None:
    """Refuse, in band and with a reason, any record this kernel does not
    accept (`spec/record.md`, versions 1 and 2): not an object, an unknown
    member, a missing required member, a version newer than understood, a
    value outside its vocabulary, or (version 2) a `claim` obligation this
    spec does not name."""
    if not isinstance(doc, dict):
        raise core.ClaimError("refused: a record must be a JSON object")

    version = doc.get("record")
    if not isinstance(version, int) or isinstance(version, bool):
        raise core.ClaimError("refused: record 'record' (version) must be an integer")
    if version not in (1, 2):
        raise core.ClaimError(
            f"refused: record version {version} is newer than this kernel "
            f"understands (version {RECORD_FORMAT})"
        )
    members = _RECORD_MEMBERS_V2 if version == 2 else _RECORD_MEMBERS_V1
    required = _RECORD_REQUIRED_V2 if version == 2 else _RECORD_REQUIRED_V1

    unknown = set(doc) - members
    if unknown:
        raise core.ClaimError(f"refused: unknown record member(s): {sorted(unknown)}")
    missing = required - set(doc)
    if missing:
        raise core.ClaimError(f"refused: record missing required member(s): {sorted(missing)}")

    if not isinstance(doc.get("name"), str):
        raise core.ClaimError("refused: record 'name' must be a string")
    for key in ("root", "build_digest"):
        value = doc.get(key)
        if not isinstance(value, str) or not attest._RECORD_HEX.match(value):
            raise core.ClaimError(
                f"refused: record {key!r} must be 64 lowercase hex characters"
            )
    when = doc.get("when")
    if not isinstance(when, str) or not attest._RECORD_WHEN.match(when):
        raise core.ClaimError("refused: record 'when' must be UTC YYYY-MM-DDTHH:MM:SSZ")

    environment = doc.get("environment")
    if (not isinstance(environment, dict)
            or set(environment) != attest._RECORD_ENVIRONMENT
            or not all(isinstance(v, str) for v in environment.values())):
        raise core.ClaimError(
            "refused: record 'environment' must hold platform/machine/runtime strings"
        )

    gates = doc.get("gates")
    if not isinstance(gates, list):
        raise core.ClaimError("refused: record 'gates' must be an array")
    for gate in gates:
        if not isinstance(gate, dict) or set(gate) != attest._RECORD_GATE:
            raise core.ClaimError(f"refused: malformed gate entry: {gate!r}")
        if not isinstance(gate.get("output"), str):
            raise core.ClaimError("refused: a gate's 'output' must be a string")
        if gate.get("status") not in attest._RECORD_STATUSES:
            raise core.ClaimError(f"refused: unknown gate status: {gate.get('status')!r}")
        if gate.get("sandbox") not in attest._RECORD_SANDBOXES:
            raise core.ClaimError(f"refused: unknown gate sandbox: {gate.get('sandbox')!r}")

    if "cost" in doc:
        cost = doc["cost"]
        if not isinstance(cost, dict) or not set(cost) <= set(core.COST_KEYS):
            raise core.ClaimError("refused: record 'cost' carries an unknown key")
        for key, value in cost.items():
            _refuse_number(value, f"record 'cost.{key}'")

    if "producer" in doc:
        producer = doc["producer"]
        if not isinstance(producer, dict) or not set(producer) <= attest._RECORD_PRODUCER:
            raise core.ClaimError("refused: record 'producer' carries an unknown key")
        if "vendor" in producer and not isinstance(producer["vendor"], str):
            raise core.ClaimError("refused: producer 'vendor' must be a string")
        if "model" in producer and not isinstance(producer["model"], str):
            raise core.ClaimError("refused: producer 'model' must be a string")
        if "blind" in producer and not isinstance(producer["blind"], bool):
            raise core.ClaimError("refused: producer 'blind' must be a boolean")
        if "cutoff" in producer and not isinstance(producer["cutoff"], str):
            raise core.ClaimError("refused: producer 'cutoff' must be a string")

    if "tool" in doc and not isinstance(doc["tool"], str):
        raise core.ClaimError("refused: record 'tool' must be a string")

    if version == 2:
        claim = doc["claim"]
        if not isinstance(claim, dict) or not set(claim) <= _CLAIM_OBLIGATIONS:
            raise core.ClaimError("refused: record 'claim' carries an unknown obligation")
        if "tolerance" in claim:
            _refuse_number(claim["tolerance"], "record 'claim.tolerance'")
        if "mutation_floor" in claim:
            _refuse_number(claim["mutation_floor"], "record 'claim.mutation_floor'")
        if "envelope" in claim:
            envelope = claim["envelope"]
            if (not isinstance(envelope, dict) or not envelope
                    or not set(envelope) <= set(core.COST_KEYS)):
                raise core.ClaimError(
                    "refused: record 'claim.envelope' must be a non-empty "
                    "table of known units"
                )
            for unit, ceiling in envelope.items():
                if (isinstance(ceiling, bool) or not isinstance(ceiling, (int, float))
                        or ceiling <= 0):
                    raise core.ClaimError(
                        f"refused: record 'claim.envelope.{unit}' must be a "
                        "positive number"
                    )


def record_canonical(doc) -> bytes:
    return attest.record_canonical(doc)


def record_digest(doc) -> str:
    return attest.record_digest(doc)


def record_signer(path: str, anchor: str) -> str:
    """Verify a record's detached ssh signature against an allowed-signers
    anchor and return the signer's identity.

    `_kernel/attest.py`'s `record_signer` reads the record through its own
    version-1-only `record_read` first, so it refuses every version-2
    record before it ever reaches `ssh-keygen`; this reads through this
    module's `_record_read` instead and otherwise verifies exactly as
    `_kernel/attest.py` does (`spec/record.md`: canonical bytes, the
    `reticuli.record` namespace, an anchored identity).
    """
    doc = _record_read(path)
    canon = record_canonical(doc)
    sig_path = path + ".sig"
    if not os.path.isfile(sig_path):
        raise core.ClaimError(f"refused: no signature at {sig_path!r}")
    if not os.path.isfile(anchor):
        raise core.ClaimError(f"refused: no allowed-signers file at {anchor!r}")
    ident = attest._allowed_identity(anchor)
    try:
        done = subprocess.run(
            ["ssh-keygen", "-Y", "verify", "-f", anchor, "-I", ident,
             "-n", attest.RECORD_NAMESPACE, "-s", sig_path],
            input=canon, capture_output=True, timeout=10,
        )
    except OSError as e:
        raise core.ClaimError(f"refused: ssh-keygen unavailable: {e}") from e
    if done.returncode != 0:
        raise core.ClaimError(f"refused: signature at {sig_path!r} does not verify")
    return ident


def _record_read(path: str) -> dict:
    if not os.path.isfile(path):
        raise core.ClaimError(f"refused: no record at {path!r}")
    with open(path, "rb") as f:
        raw = f.read()
    try:
        doc = json.loads(raw)
    except json.JSONDecodeError as e:
        raise core.ClaimError(f"refused: malformed record {path!r}: {e}") from e
    record_validate(doc)
    if record_canonical(doc) != raw:
        raise core.ClaimError(
            f"refused: {path!r} is not its own canonical bytes -- "
            "the file is its canonical bytes or it is not a record"
        )
    return doc


def _read_producer(d: str) -> dict:
    """The last declared producer event on a directory's ledger
    (vendor/model/blind), or an all-`None` dict when nothing was declared."""
    for event in reversed(run_mod.ledger_events(d)):
        if event.get("event") == "producer":
            return {"vendor": event.get("vendor"), "model": event.get("model"),
                    "blind": event.get("blind")}
    return {"vendor": None, "model": None, "blind": None}


def _independence_string(producer: dict) -> str:
    vendor = (producer or {}).get("vendor")
    if not vendor:
        return "unestablished: vendor not declared"
    model = producer.get("model")
    blind = "blind" if producer.get("blind") else "non-blind"
    return f"declared: {vendor}/{model}, {blind} workspace (not proven)"


def _leg_info(leg: str) -> dict:
    """Normalize one crosscheck leg -- a claim directory or a record file
    -- into `{"kind", "root", "build_digest", "audited", "cost",
    "producer"}`."""
    if os.path.isdir(leg):
        leg = os.path.abspath(leg)
        recipe = load_recipe(leg)
        root_value = root(recipe, leg)
        build_digest = _in_band(identity_mod.build_digest, leg)
        audited = bool(_audit_dir(leg).get("ok"))
        totals = run_mod.cost(leg) or None
        producer = _read_producer(leg)
        return {"kind": "dir", "path": leg, "root": root_value,
                "build_digest": build_digest, "audited": audited,
                "cost": totals, "producer": producer}
    doc = _record_read(leg)
    gates_ok = all(g.get("status") == "ok" for g in doc.get("gates", []))
    return {"kind": "record", "path": leg, "root": doc["root"],
            "build_digest": doc["build_digest"], "audited": gates_ok,
            "cost": doc.get("cost"), "producer": doc.get("producer")}


def _declared(leg: str, is_dir: bool) -> tuple:
    """The declared obligations (`tolerance`/`envelope`/`mutation_floor`)
    at the M1 position: `("known", {...})`, or `("unknown", None)` when M1
    is a version-1 record, which cannot say what was declared."""
    if is_dir:
        recipe = load_recipe(os.path.abspath(leg))
        claim = recipe.get("claim", {})
        return "known", {k: claim[k] for k in
                         ("tolerance", "envelope", "mutation_floor") if k in claim}
    doc = _record_read(leg)
    if doc.get("record") == 1:
        return "unknown", None
    return "known", dict(doc.get("claim") or {})


def crosscheck(leg1: str, leg2: str, leg3: str, mutants: int = None) -> dict:
    """The three-machine test (`spec/verification.md`): one root across
    M1/M2/M3, byte reuse from M1 to M2, every verdict earned, the cost band
    and every condition the claim declares. Legs mix directories and
    records freely. `mutants`, when given, bounds a mutation re-audit of
    M3 for a declared `mutation_floor`; omitted, that condition is
    unmeasured.
    """
    raw = (leg1, leg2, leg3)
    resolved = []
    for leg in raw:
        if not (os.path.isdir(leg) or os.path.isfile(leg)):
            raise core.ClaimError(f"refused: no such crosscheck leg: {leg!r}")
        resolved.append(os.path.realpath(leg))
    if len(set(resolved)) < 3:
        raise core.ClaimError(
            "refused: crosscheck legs must be three distinct machines"
        )

    labels = ("M1", "M2", "M3")
    infos = {label: _leg_info(leg) for label, leg in zip(labels, raw)}

    roots = {label: infos[label]["root"] for label in labels}
    equivalence = len(set(roots.values())) == 1
    reuse = infos["M1"]["build_digest"] == infos["M2"]["build_digest"]
    audited = {label: infos[label]["audited"] for label in labels}

    rejected = []
    incomplete = []
    if not equivalence:
        rejected.append("equivalence")
    if not reuse:
        rejected.append("reuse")
    for label in labels:
        if not audited[label]:
            rejected.append(f"audited:{label}")

    cost_report = {}
    mutation_result = None
    kind, declared = _declared(leg1, infos["M1"]["kind"] == "dir")

    if kind == "unknown":
        incomplete.append("declared-conditions")
    else:
        c1 = infos["M1"]["cost"] or {}
        c3 = infos["M3"]["cost"] or {}
        unit = next((u for u in core.COST_LADDER if u in c1 and u in c3), None)
        comparable = None
        if unit is not None:
            v1, v3 = c1[unit], c3[unit]
            if v1 and v3:
                ratio = max(v1, v3) / min(v1, v3)
                comparable = ratio <= declared.get("tolerance", core.TOLERANCE)
            else:
                comparable = v1 == v3
        cost_report["comparable"] = comparable

        tolerance_declared = declared.get("tolerance")
        if tolerance_declared is not None:
            if comparable is None:
                incomplete.append("tolerance")
            elif not comparable:
                rejected.append("tolerance")

        envelope_declared = declared.get("envelope") or {}
        if envelope_declared:
            envelope_report = {}
            for unit_name, ceiling in envelope_declared.items():
                measured = c3.get(unit_name)
                within = None if measured is None else measured <= ceiling
                envelope_report[unit_name] = {
                    "within": within, "ceiling": ceiling, "measured": measured,
                }
                if within is None:
                    incomplete.append(f"envelope {unit_name}")
                elif not within:
                    rejected.append(f"envelope {unit_name}")
            cost_report["envelope"] = envelope_report

        floor = declared.get("mutation_floor")
        if floor is not None:
            if mutants is not None and infos["M3"]["kind"] == "dir":
                mutation_result = mutation_score(infos["M3"]["path"],
                                                 max_mutants=mutants)
                mutation_result["ok"] = mutation_result["rate"] >= floor
                if not mutation_result["ok"]:
                    rejected.append("mutation_floor")
            else:
                incomplete.append("mutation_floor")

    if "comparable" not in cost_report:
        cost_report["comparable"] = None

    if rejected:
        verdict = "reject"
    elif incomplete:
        verdict = "incomplete"
    else:
        verdict = "accept"

    return {
        "satisfied": verdict == "accept",
        "verdict": verdict,
        "rejected": rejected,
        "incomplete": incomplete,
        "roots": roots,
        "equivalence": equivalence,
        "reuse": reuse,
        "audited": audited,
        "cost": cost_report,
        "mutation_score": mutation_result,
        "independence": _independence_string(infos["M3"]["producer"]),
    }
