"""Identity: the root hash and the build digest (`spec/identity.md`).

`root(recipe, d)` computes a claim's identity from what the claim *is* --
the parsed recipe, its pinned inputs, and its pinned/validated step
outputs -- never from the generated (regrowable) bytes. `build_digest(d)`
computes a digest over exactly the generated bytes present, the thing a
signature over concrete bytes binds.

Both hash a canonical JSON serialization: sorted keys, default (non-compact)
separators, ASCII-escaped, arbitrary-precision integers, floats as
CPython's `repr` -- plain `json.dumps(x, sort_keys=True)` encoded UTF-8.
TOML date/time values cannot enter a preimage and are refused.

Stdlib only.
"""
import hashlib
import json
import os

from . import core
from . import recipe as recipe_mod


def _refuse_datetime(obj):
    raise core.ClaimError(
        f"refused: TOML date/time values cannot enter the root preimage: {obj!r}"
    )


def _canonical_json(obj) -> str:
    """`json.dumps(obj, sort_keys=True)`, ASCII-escaped, refusing date/time values."""
    return json.dumps(obj, sort_keys=True, default=_refuse_datetime)


def _claim_format(recipe: dict) -> int:
    """The claim's declared format, or 1 when absent (`spec/claim-format.md`)."""
    return recipe.get("claim", {}).get("format", 1)


def _strip_guidance(step: dict) -> dict:
    return {k: v for k, v in step.items() if k not in core.GUIDANCE_KEYS}


def _preimage_recipe(recipe: dict) -> dict:
    """The recipe as it enters the root preimage, format-dependent.

    Format >= 3 strips every step's guidance keys (`guidance`, `request`):
    a hint for a producer, never a condition on acceptance. Format >= 4
    additionally canonicalizes the step list -- a SET of obligations, not
    an authoring-order sequence -- by sorting steps on their own canonical
    JSON encodings.
    """
    fmt = _claim_format(recipe)
    steps = list(recipe.get("step", []))
    if fmt >= 3:
        steps = [_strip_guidance(s) for s in steps]
    if fmt >= 4:
        steps = sorted(steps, key=_canonical_json)
    doc = dict(recipe)
    doc["step"] = steps
    return doc


def _step_class(step: dict) -> str:
    default = "generated" if step.get("kind") == "produce" else "pinned"
    return step.get("class", default)


def _parts(recipe: dict, d: str) -> dict:
    """The string-to-string map the root hashes (`spec/identity.md`)."""
    parts = {"digest": core.DIGEST, "recipe": _canonical_json(_preimage_recipe(recipe))}
    for path in recipe_mod._inputs(d, recipe):
        full = core._safe(d, path)
        parts["input:" + path] = core._hash_file(full)
    for step in recipe.get("step", []):
        if _step_class(step) in recipe_mod.GENERATED_CLASSES:
            continue
        output = step["output"]
        full = core._safe(d, output)
        parts["pinned:" + output] = core._hash_file(full)
    return parts


def root(recipe: dict, d: str) -> str:
    """The claim's identity: a SHA-256 digest over what the claim *is*."""
    parts = _parts(recipe, d)
    return hashlib.sha256(_canonical_json(parts).encode("utf-8")).hexdigest()


def build_digest(d: str) -> str:
    """The digest of the generated bytes present (`spec/identity.md`, `spec/record.md`).

    Only `produce` steps whose class is generated (v2) / free (v1) and that
    do not declare `from` (sourced from elsewhere, not independently
    produced) contribute. An output that is not present on disk is
    omitted, not an error. With none present, this is the digest of the
    empty list.
    """
    parsed = recipe_mod.load_recipe(d)
    pairs = []
    for step in recipe_mod.produces(parsed):
        if "from" in step:
            continue
        if _step_class(step) not in recipe_mod.GENERATED_CLASSES:
            continue
        output = step["output"]
        full = core._safe(d, output)
        if not os.path.isfile(full):
            continue
        pairs.append([output, core._hash_file(full)])
    pairs.sort(key=lambda p: p[0])
    return hashlib.sha256(_canonical_json(pairs).encode("utf-8")).hexdigest()
