"""reticuli._cli.parser -- the `ret` argv grammar.

Porcelain/plumbing, git's own split: `PORCELAIN` is the fourteen verbs a
person actually reaches for (`_DESC`'s four groups -- Authoring,
Composition and transport, Verification, Reconstruction, Evidence);
`ALIASES` is where an accepted-but-secondary spelling of one of them would
live, kept as its own dict so the grammar can grow one without ever
touching `PORCELAIN`'s count; `hook`, `help`, and `completion` are
plumbing -- machinery the porcelain verbs stand on rather than claim
things about a project. `verbs()` is the one place all three are
combined, so the parser and `ret help -a` can never drift apart.

Several v1 verbs were retired outright (`condense`, `realize`, `prove`,
`mint`, `records`, `hydrate`, `inspect`); a second, 2026-09-22 wave folded
what remained of the old verb surface into flags on a porcelain verb
instead of leaving it a command of its own: `seal` into `pack --accept`
(`reticuli.pack.pack` already seals in place), `hooks` into `init` (wired
automatically unless `--no-agent`, `reticuli._cli.handlers.init`),
`tree`/`claims`/`deps`/`structure` into `status --tree` / `--claims` /
`--deps` / `--structure`, and `attest` into `record --key --as` /
`record --check`. None of those retired spellings are registered below;
`checks/parser_check.py` pins that they stay gone.

Every verb ends through `_cli.output._finish` (the `--json` envelope) or
its refusal through `_cli.output._err` -- this module only wires argv to
the function that already knows how to do that; it decides nothing about
a claim itself.

Stdlib only. Never the network.
"""
import argparse
import json
import os
import sys

from . import handlers
from . import output
from . import report as _report
from . import statusview as _statusview
from .. import hooks as _hooks
from .. import kernel

PORCELAIN = (
    "init", "run", "status", "pack",
    "pull", "export", "import",
    "verify", "audit", "assess",
    "rebuild", "crosscheck",
    "record", "sign",
)

# No secondary spelling is accepted today; the dict stays here, empty, so
# one can be added later without ever touching `PORCELAIN`'s shape or its
# count of fourteen.
ALIASES = {}

_PLUMBING = ("hook", "help", "completion")

_DESC = 'Reticuli records and reproduces software claims.\n\nAuthoring\n    init        initialize a workspace\n    run         run and observe a command\n    status      show work, claims, and unresolved inputs\n    pack        create a claim from a project\n\nComposition and transport\n    pull        add another claim as a dependency\n    export      write a portable claim archive\n    import      restore a claim archive\n\nVerification\n    verify      verify claim identity\n    audit       rerun acceptance criteria\n    assess      measure specification strength\n\nReconstruction\n    rebuild     rebuild an implementation from a claim\n    crosscheck  compare independent realizations\n\nEvidence\n    record      write an execution record\n    sign        authorize a claim or proof'

_EPILOG = "See 'ret <command> -h' for command usage.\nSee 'ret help <command>' for detailed help; 'ret help -a' lists everything,\nincluding accepted older spellings."

_FULL_HELP = {
    "init": "Create a workspace's `.reticuli` store and, unless --no-agent, "
            "wire the coding-agent hooks so its prompts and tool calls are traced.",
    "run": "Run one shell command inside a session, tracing it into the "
           "workspace's draft trace, and return the child's exit code unchanged.",
    "status": "Show a claim's name, root, phase, verdict, gates, and "
              "signatures; --tree/--claims/--deps/--structure switch to the "
              "workspace-scope views the retired tree/claims/deps/structure "
              "verbs used to be.",
    "pack": "Declare a project's boundary directly -- which files are the "
            "regrowable implementation, which are the claim, and what gate "
            "decides -- run the gate once, and seal.",
    "pull": "Copy a claim's declared content into another workspace, making "
            "it a dependency of that workspace.",
    "export": "Write a claim's declared content to a portable tar archive; "
              "--blind withholds generated bytes.",
    "import": "Extract a portable tar archive into a directory and verify "
              "the claim it reconstitutes.",
    "verify": "Recompute a sealed claim's root from the bytes present and "
              "compare it to the manifest -- identity only, no gate re-run.",
    "audit": "Re-execute every gate, cold and sandboxed, composed claims "
             "included -- the only verb that re-earns a verdict.",
    "assess": "Mutate a claim's generated Python source and report how many "
              "mutants its own tests tell apart from the original.",
    "rebuild": "Regrow a claim's generated bytes with a producer into a "
               "fresh directory.",
    "crosscheck": "Compare three independent realizations of a claim and "
                  "report whether their verdicts and ledgers agree.",
    "record": "Emit a signed statement of one machine's results; --key --as "
              "attests instead (a build attestation), --check reports "
              "whether that attestation still holds.",
    "sign": "Authorize the chain root over a reviewed packet; --review "
            "shows the packet without signing it, --check reports whether "
            "an existing signature is trustworthy.",
    "hook": "Read one coding-agent hook payload from stdin and trace it, if "
            "it names a session -- the plumbing `init` wires into "
            ".claude/settings.json.",
    "help": "Print the top-level help, or -a for every accepted spelling, "
            "or detailed help for one command.",
    "completion": "Print a shell completion script for the grammar above.",
}


# ---------------------------------------------------------------------------
# Small shared argument groups
# ---------------------------------------------------------------------------
def _add_verbose_json(sp: argparse.ArgumentParser) -> None:
    """Add the flags every verb's output shares: `-v/--verbose` for a
    fuller human render, `--json` for the machine envelope, and `--color`
    for whether to paint the human one."""
    sp.add_argument("-v", "--verbose", action="store_true",
                     help="show a fuller human-readable render")
    sp.add_argument("--json", action="store_true",
                     help="print the five-field machine envelope and nothing else")
    sp.add_argument("--color", choices=("auto", "always", "never"), default="auto",
                     help="colorize human output (default: auto)")


def _add_claim(sp: argparse.ArgumentParser, help_="the claim directory (default: current directory)") -> None:
    sp.add_argument("claim", nargs="?", default=None, help=help_)


def _json_map_arg(path: str):
    """argparse `type=`: a JSON file's parsed object, read at parse time --
    used for `rebuild`'s substitution maps so `_report._r_rebuild` sees a
    plain dict without knowing it ever came from a file."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Dispatchers that fold a retired verb's behavior onto a porcelain one
# ---------------------------------------------------------------------------
def _v_init(args) -> int:
    """`init`: create the store and, unless `--no-agent`, wire the agent
    hooks -- the 2026-09-22 fold of the old `hooks` verb."""
    d = args.claim if args.claim else os.getcwd()
    data = handlers.init(d, no_agent=getattr(args, "no_agent", False))
    if not getattr(args, "json", False):
        output._line(f"initialized {data['claim']}", args, color="cyan")
    return output._finish("init", data, True, "initialized", args)


def _v_run(args) -> int:
    """`run`: trace one shell command scoped to the session workspace."""
    ws = args.claim if args.claim else os.getcwd()
    rc = handlers.run(args.cmd, ws)
    ok = rc == 0
    data = {"claim": ws, "cmd": args.cmd, "exit": rc}
    return output._finish("run", data, ok, ("ok" if ok else "failed"), args)


def _v_status(args) -> int:
    """`status`: the per-claim view by default; `--tree`, `--claims`,
    `--deps`, `--structure` switch to the workspace-scope views the
    retired `tree`/`claims`/`deps`/`structure` verbs used to be."""
    if getattr(args, "tree", False):
        return _statusview._r_tree(args)
    if getattr(args, "claims", False):
        return _statusview._r_claims(args)
    if getattr(args, "deps", False):
        return _statusview._r_deps(args)
    if getattr(args, "structure", False):
        return _statusview._r_structure(args)
    return _statusview._r_status_draft(args)


def _v_record(args) -> int:
    """`record`: emit and (optionally) sign a record by default; `--key`
    together with `--as` attests instead (the 2026-09-22 fold of the old
    `attest` verb), and `--check` reports whether that attestation holds."""
    if getattr(args, "check", False):
        return _report._r_attest_check(args)
    if getattr(args, "key", None) and getattr(args, "identity", None):
        return _report._r_attest(args)
    return _report._r_record(args)


def _v_sign(args) -> int:
    """`sign`: run the signing ceremony by default; `--review` shows the
    packet a keyholder would review without signing it, `--check` reports
    whether an existing signature is trustworthy."""
    if getattr(args, "review", False):
        return _report._r_review(args)
    if getattr(args, "check", False):
        return _report._r_sign_check(args)
    return _report._r_sign(args)


def _v_hook(args) -> int:
    """`hook`: the plumbing counterpart to `python3 -m reticuli.hooks` --
    read one hook payload from stdin, trace it if it names a session, and
    always exit clean; a hook must never block the agent's tool call."""
    try:
        payload = json.load(sys.stdin)
    except (ValueError, TypeError):
        return 0
    try:
        _hooks.event(payload)
    except kernel.ClaimError:
        pass
    return 0


# ---------------------------------------------------------------------------
# Building the grammar
# ---------------------------------------------------------------------------
def _build_authoring(sub) -> None:
    sp = sub.add_parser("init", help="initialize a workspace")
    _add_claim(sp, "the workspace to initialize (default: current directory)")
    sp.add_argument("--no-agent", action="store_true",
                     help="skip wiring the coding-agent hooks")
    _add_verbose_json(sp)
    sp.set_defaults(func=_v_init)

    sp = sub.add_parser("run", help="run and observe a command")
    sp.add_argument("cmd", help="the shell command to run and trace")
    _add_claim(sp, "the session workspace (default: current directory)")
    _add_verbose_json(sp)
    sp.set_defaults(func=_v_run)

    sp = sub.add_parser("status", help="show work, claims, and unresolved inputs")
    _add_claim(sp)
    sp.add_argument("--tree", action="store_true",
                     help="show the claim's declared files as a tree (retired: tree)")
    sp.add_argument("--claims", action="store_true",
                     help="list claims sealed in the workspace's store (retired: claims)")
    sp.add_argument("--deps", action="store_true",
                     help="show the workspace's store as a dependency graph")
    sp.add_argument("--structure", action="store_true",
                     help="show the workspace's store as claims and their edges")
    _add_verbose_json(sp)
    sp.set_defaults(func=_v_status)

    sp = sub.add_parser("pack", help="create a claim from a project")
    _add_claim(sp)
    sp.add_argument("--name", required=True, help="the claim's name")
    sp.add_argument("--generated", nargs="+", required=True, metavar="PATTERN",
                     help="glob patterns naming the regrowable implementation")
    sp.add_argument("--inputs", nargs="+", required=True, metavar="PATTERN",
                     help="glob patterns naming the claim's own pinned files")
    sp.add_argument("--run", required=True, metavar="CMD", help="the gate command")
    sp.add_argument("--output", required=True, metavar="NAME",
                     help="the gate's declared output")
    _add_verbose_json(sp)
    sp.set_defaults(func=_report._r_pack)


def _build_composition(sub) -> None:
    sp = sub.add_parser("pull", help="add another claim as a dependency")
    _add_claim(sp, "the claim to pull (default: current directory)")
    sp.add_argument("--into", required=True, metavar="WORKSPACE",
                     help="the workspace that gains the dependency")
    _add_verbose_json(sp)
    sp.set_defaults(func=_report._r_pull)

    sp = sub.add_parser("export", help="write a portable claim archive")
    _add_claim(sp)
    sp.add_argument("--out", required=True, metavar="TAR", help="the archive to write")
    sp.add_argument("--blind", action="store_true",
                     help="withhold generated bytes -- the rebuilder's room")
    _add_verbose_json(sp)
    sp.set_defaults(func=_report._r_export)

    sp = sub.add_parser("import", help="restore a claim archive")
    sp.add_argument("tar", help="the archive to extract")
    _add_claim(sp, "the directory to extract into (default: current directory)")
    _add_verbose_json(sp)
    sp.set_defaults(func=_report._r_import)


def _build_verification(sub) -> None:
    sp = sub.add_parser("verify", help="verify claim identity")
    _add_claim(sp)
    _add_verbose_json(sp)
    sp.set_defaults(func=_report._r_verify)

    sp = sub.add_parser("audit", help="rerun acceptance criteria")
    _add_claim(sp)
    _add_verbose_json(sp)
    sp.set_defaults(func=_report._r_audit)

    sp = sub.add_parser("assess", help="measure specification strength")
    _add_claim(sp)
    sp.add_argument("--mutants", type=int, default=None, metavar="N",
                     help="cap the number of mutants drawn")
    _add_verbose_json(sp)
    sp.set_defaults(func=_report._r_assess)


def _build_reconstruction(sub) -> None:
    sp = sub.add_parser("rebuild", help="rebuild an implementation from a claim")
    sp.add_argument("producer", help="the producer command (or a known name)")
    sp.add_argument("into", help="the directory to rebuild into")
    _add_claim(sp)
    sp.add_argument("--produce-from", dest="produce_from", type=_json_map_arg,
                     default=None, metavar="FILE",
                     help="JSON file mapping a generated output to a substituted source")
    sp.add_argument("--input-from", dest="input_from", type=_json_map_arg,
                     default=None, metavar="FILE",
                     help="JSON file mapping a pinned input to a substituted source")
    _add_verbose_json(sp)
    sp.set_defaults(func=_report._r_rebuild)

    sp = sub.add_parser("crosscheck", help="compare independent realizations")
    sp.add_argument("m2", help="the second machine's claim directory")
    sp.add_argument("m3", help="the third machine's claim directory")
    _add_claim(sp, "the first machine's claim directory (default: current directory)")
    sp.add_argument("--mutants", type=int, default=None, metavar="N",
                     help="cap the number of mutants drawn")
    _add_verbose_json(sp)
    sp.set_defaults(func=_report._r_crosscheck)


def _build_evidence(sub) -> None:
    sp = sub.add_parser("record", help="write an execution record")
    _add_claim(sp)
    sp.add_argument("--out", default=None, metavar="PATH", help="where to write the record")
    sp.add_argument("--key", default=None, metavar="KEYFILE", help="an ssh private key")
    sp.add_argument("--as", dest="identity", default=None, metavar="IDENTITY",
                     help="attest as this identity (with --key)")
    sp.add_argument("--check", action="store_true",
                     help="report whether the recorded attestation still holds")
    sp.add_argument("--signers", default=None, metavar="FILE",
                     help="an ssh allowed_signers file, to verify --check against")
    _add_verbose_json(sp)
    sp.set_defaults(func=_v_record)

    sp = sub.add_parser("sign", help="authorize a claim or proof")
    _add_claim(sp)
    sp.add_argument("--key", default=None, metavar="KEYFILE", help="an ssh private key")
    sp.add_argument("--identity", default=None, metavar="IDENTITY",
                     help="sign as this identity")
    sp.add_argument("--workspace", default=None, metavar="WORKSPACE",
                     help="the workspace a component's sign root is resolved against")
    sp.add_argument("--review", action="store_true",
                     help="show the packet a keyholder would review, without signing")
    sp.add_argument("--check", action="store_true",
                     help="report whether an existing signature is trustworthy")
    sp.add_argument("--signers", default=None, metavar="FILE",
                     help="an ssh allowed_signers file, to verify --check against")
    _add_verbose_json(sp)
    sp.set_defaults(func=_v_sign)


def _build_plumbing(sub) -> None:
    sp = sub.add_parser("hook", help="the coding-agent hook entry point (plumbing)")
    sp.set_defaults(func=_v_hook)

    sp = sub.add_parser("help", help="show help, including retired spellings")
    sp.add_argument("topic", nargs="?", default=None, help="a command to show detailed help for")
    sp.add_argument("-a", "--all", action="store_true",
                     help="list every command, including accepted older spellings")
    sp.set_defaults(func=_v_help)

    sp = sub.add_parser("completion", help="print a shell completion script")
    sp.add_argument("shell", nargs="?", default="bash", choices=("bash", "zsh"),
                     help="the shell to generate a completion script for (default: bash)")
    sp.set_defaults(func=lambda args: _completion(args.shell) or 0)


def _parser():
    """The top-level `ret` parser and its subparsers action -- `(parser,
    subparsers)`, so a caller can look a verb's own parser up by name
    (`subparsers.choices`) without rebuilding the grammar."""
    p = argparse.ArgumentParser(
        prog="ret",
        description=_DESC,
        epilog=_EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--version", action="version",
                    version=handlers._version_line())
    sub = p.add_subparsers(dest="verb", metavar="<command>")
    _build_authoring(sub)
    _build_composition(sub)
    _build_verification(sub)
    _build_reconstruction(sub)
    _build_evidence(sub)
    _build_plumbing(sub)
    return p, sub


def verbs() -> tuple:
    """Every name the grammar accepts: the fourteen porcelain verbs, any
    accepted alternate spelling in `ALIASES`, and the plumbing -- the one
    set `ret help -a` and the parser itself are both built from."""
    return tuple(PORCELAIN) + tuple(ALIASES) + _PLUMBING


# ---------------------------------------------------------------------------
# help / completion (plumbing)
# ---------------------------------------------------------------------------
def _help_all() -> str:
    """Every accepted command, one line each, plus the v1/v2-transition
    spellings that are no longer accepted -- named for orientation, not
    because they work."""
    lines = ["All accepted commands:", ""]
    for name in sorted(verbs()):
        lines.append(f"  {name:<12} {_FULL_HELP.get(name, '')}")
    lines.append("")
    lines.append(
        "No longer accepted (retired): condense, realize, prove, mint, "
        "records, hydrate, inspect, seal, hooks, tree, claims, attest.")
    return "\n".join(lines)


def _help_topic(name: str) -> str:
    """The detailed help for one command: its own `-h` text, or a plain
    refusal sentence when `name` names nothing this parser accepts."""
    _, sub = _parser()
    target = sub.choices.get(name)
    if target is None:
        return f"no such command: {name!r}"
    return target.format_help()


def _completion(shell: str) -> None:
    """Print a shell completion script covering every verb `verbs()`
    reports -- generated from the grammar itself, so it cannot drift from
    what the parser actually accepts."""
    names = " ".join(sorted(verbs()))
    if shell == "zsh":
        print(f"#compdef ret\ncompadd {names}")
        return
    print(
        "_ret_complete() {\n"
        '    local cur="${COMP_WORDS[COMP_CWORD]}"\n'
        f'    COMPREPLY=( $(compgen -W "{names}" -- "$cur") )\n'
        "}\n"
        "complete -F _ret_complete ret"
    )


def _v_help(args) -> int:
    if getattr(args, "all", False):
        print(_help_all())
        return 0
    topic = getattr(args, "topic", None)
    if topic:
        print(_help_topic(topic))
        return 0
    p, _sub = _parser()
    p.print_help()
    return 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main(argv=None) -> int:
    p, _sub = _parser()
    args = p.parse_args(argv)
    func = getattr(args, "func", None)
    if func is None:
        p.print_help()
        return 1
    try:
        return func(args)
    except kernel.ClaimError as exc:
        output._err(getattr(args, "verb", "ret") or "ret", str(exc))
        return 1


if __name__ == "__main__":
    sys.exit(main())
