"""reticuli._cli.verbs -- the verb-handler surface.

Each verb's handler (`_handle_*`) and the composite dispatches (`_dispatch_*`,
the ones that branch on a mode flag before picking which underlying
operation to run -- `pack`'s old `seal` fold, `status`'s tree/claims/deps/
structure views, `audit` and `crosscheck`'s claim-vs-dependency scope) live
here; `main()` routes argv to them through the grammar this module builds.

Most handlers are thin: the work already lives in `reticuli.kernel` and the
layers above it, and in this package's own `report`/`statusview`/`handlers`
modules, which already render it through the shared `--json` envelope
(`_cli.output`). `_handle_run` is the one handler with its own contract
worth stating plainly: it returns the child's exit code *unchanged*, not an
envelope, so a caller can use it as a predicate. `_dispatch_pack` is the
other -- it refuses, in words, before building anything, when `--accept`
is given without `-o` (the accepted output has no name to seal under).

Stdlib only. Never the network.
"""
import argparse
import os
import sys

from . import handlers
from . import output
from . import parser as _parser
from . import report as _report
from . import statusview as _statusview
from .. import kernel
from .. import pack as _pack


def _usage_error(verb: str, message: str) -> int:
    """Speak a usage refusal in the one-voice error line and return the
    conventional argument-error exit code (2) -- used for a malformed
    invocation caught before any work starts, never for a claim's own
    refusal (which is `kernel.ClaimError`, caught in `main`)."""
    output._err(verb, message)
    return 2


# ---------------------------------------------------------------------------
# Plain handlers
# ---------------------------------------------------------------------------
def _handle_help(args) -> int:
    """`help`: the top-level help, `-a` for every accepted spelling, or
    detailed help for one command."""
    return _parser._v_help(args)


def _handle_init(args) -> int:
    """`init`: create the workspace's store and, unless `--no-agent`, wire
    the coding-agent hooks."""
    return _parser._v_init(args)


def _handle_completion(args) -> int:
    """`completion`: print a shell completion script for the grammar."""
    _parser._completion(getattr(args, "shell", "bash"))
    return 0


def _handle_hook(args) -> int:
    """`hook`: read one coding-agent hook payload from stdin and trace it,
    if it names a session; always exits clean, so a hook never blocks the
    agent's tool call."""
    return _parser._v_hook(args)


def _handle_run(args):
    """`run`: run one shell command scoped to the session workspace and
    return the child's exit code UNCHANGED -- the predicate contract a
    session script relies on (`ret run "pytest" && ret seal`).

    Accepts either shape a caller may hand it: `args.command` (a list of
    argv tokens, joined into one shell command) and `args.workspace`, or
    the single-string `args.cmd` and `args.claim` the grammar built here
    actually parses argv into."""
    command = getattr(args, "command", None)
    if command:
        cmd = " ".join(command)
    else:
        cmd = getattr(args, "cmd", "") or ""
    ws = getattr(args, "workspace", None) or getattr(args, "claim", None) or os.getcwd()
    return handlers.run(cmd, ws)


def _handle_verify(args) -> int:
    """`verify`: recompute a sealed claim's root from the bytes present and
    compare it to the manifest -- identity only, no gate re-run."""
    return _report._r_verify(args)


def _handle_assess(args) -> int:
    """`assess`: mutate a claim's generated Python source and report how
    many mutants its own tests tell apart from the original."""
    return _report._r_assess(args)


def _handle_rebuild(args) -> int:
    """`rebuild`: regrow a claim's generated bytes with a producer into a
    fresh directory."""
    return _report._r_rebuild(args)


def _handle_pull(args) -> int:
    """`pull`: copy a claim's declared content into another workspace,
    making it a dependency of that workspace."""
    return _report._r_pull(args)


def _handle_sign(args) -> int:
    """`sign`: run the signing ceremony by default; `--review` shows the
    packet without signing it, `--check` reports whether an existing
    signature is trustworthy."""
    return _parser._v_sign(args)


def _handle_export(args) -> int:
    """`export`: write a claim's declared content to a portable tar
    archive; `--blind` withholds generated bytes."""
    return _report._r_export(args)


def _handle_record(args) -> int:
    """`record`: emit a signed statement of one machine's results by
    default; `--key --as` attests instead, `--check` reports whether that
    attestation still holds."""
    return _parser._v_record(args)


def _handle_import(args) -> int:
    """`import`: extract a portable tar archive into a directory and
    verify the claim it reconstitutes."""
    return _report._r_import(args)


# ---------------------------------------------------------------------------
# Dispatches: verbs that branch on a mode flag before picking which
# underlying operation to run.
# ---------------------------------------------------------------------------
def _dispatch_status(args) -> int:
    """`status`: the per-claim view by default; `--tree`, `--claims`,
    `--deps`, `--structure` switch to the workspace-scope views the
    retired `tree`/`claims`/`deps`/`structure` verbs used to be."""
    return _parser._v_status(args)


def _dispatch_audit(args) -> int:
    """`audit`: re-execute every gate, cold and sandboxed -- the only verb
    that re-earns a verdict."""
    return _report._r_audit(args)


def _dispatch_crosscheck(args) -> int:
    """`crosscheck`: compare three independent realizations of a claim and
    report whether their verdicts and ledgers agree."""
    return _report._r_crosscheck(args)


def _dispatch_pack(args) -> int:
    """`pack`: declare a project's boundary directly and seal it, or --
    with `--accept` -- fold the old `seal` verb: accept the claim's
    current bytes in place, without re-running a gate. `--accept` without
    `-o/--output` naming what is being accepted is a usage error, refused
    in words before anything is built."""
    accept = getattr(args, "accept", None)
    output_name = getattr(args, "output", None)
    if accept and not output_name:
        return _usage_error(
            "pack", "--accept requires -o/--output naming the accepted gate output")

    path = getattr(args, "path", None) or getattr(args, "claim", None) or os.getcwd()

    if accept:
        try:
            manifest = kernel.seal(path)
        except kernel.ClaimError as exc:
            output._err("pack", str(exc))
            return 1
        if not getattr(args, "json", False):
            output._line(f"pack: sealed ({manifest.get('root')})", args, color="green")
        return output._finish("pack", manifest, True, "sealed", args)

    name = getattr(args, "name", None)
    if not name:
        return _usage_error("pack", "--name is required")
    generated = getattr(args, "generated", None)
    if not generated:
        return _usage_error("pack", "--generated PATTERN... is required")
    gate = getattr(args, "gate", None)
    if not gate and getattr(args, "pytest", None):
        gate = "python3 -m pytest -q"
    if not gate:
        return _usage_error("pack", "--gate CMD (or --pytest) is required")
    if not output_name:
        return _usage_error("pack", "-o/--output NAME is required")
    inputs = getattr(args, "root", None) or []

    try:
        data = _pack.pack(path, name, generated, inputs, gate, output_name)
    except kernel.ClaimError as exc:
        output._err("pack", str(exc))
        return 1
    if not getattr(args, "json", False):
        output._line(f"pack: packed ({data.get('root')})", args, color="green")
    return output._finish("pack", data, data.get("ok", True), "packed", args)


# ---------------------------------------------------------------------------
# Entry point: an argv grammar routed through the handlers above.
# ---------------------------------------------------------------------------
_DISPATCH = {
    "init": _handle_init,
    "run": _handle_run,
    "status": _dispatch_status,
    "pack": _dispatch_pack,
    "pull": _handle_pull,
    "export": _handle_export,
    "import": _handle_import,
    "verify": _handle_verify,
    "audit": _dispatch_audit,
    "assess": _handle_assess,
    "rebuild": _handle_rebuild,
    "crosscheck": _dispatch_crosscheck,
    "record": _handle_record,
    "sign": _handle_sign,
    "hook": _handle_hook,
    "help": _handle_help,
    "completion": _handle_completion,
}


def _build_parser():
    """The `ret` argv grammar for this module's own routing: every verb
    parser.py already builds, reused as-is (their field names are exactly
    what the handlers above -- delegating straight into `report`/
    `statusview`/`parser` -- already expect), plus a `run`/`pack` pair
    matching `_handle_run`/`_dispatch_pack`'s own field names."""
    p = argparse.ArgumentParser(
        prog="ret",
        description=_parser._DESC,
        epilog=_parser._EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--version", action="version", version=handlers._version_line())
    sub = p.add_subparsers(dest="verb", metavar="<command>")

    sp = sub.add_parser("init", help="initialize a workspace")
    _parser._add_claim(sp, "the workspace to initialize (default: current directory)")
    sp.add_argument("--no-agent", action="store_true", help="skip wiring the coding-agent hooks")
    _parser._add_verbose_json(sp)
    sp.set_defaults(func=_handle_init)

    sp = sub.add_parser("run", help="run and observe a command")
    sp.add_argument("command", nargs=argparse.REMAINDER, help="the shell command to run and trace")
    sp.add_argument("--workspace", default=None, help="the session workspace (default: current directory)")
    _parser._add_verbose_json(sp)
    sp.set_defaults(func=_handle_run)

    sp = sub.add_parser("status", help="show work, claims, and unresolved inputs")
    _parser._add_claim(sp)
    sp.add_argument("--tree", action="store_true", help="show the claim's declared files as a tree")
    sp.add_argument("--claims", action="store_true", help="list claims sealed in the workspace's store")
    sp.add_argument("--deps", action="store_true", help="show the workspace's store as a dependency graph")
    sp.add_argument("--structure", action="store_true", help="show the workspace's store as claims and their edges")
    _parser._add_verbose_json(sp)
    sp.set_defaults(func=_dispatch_status)

    sp = sub.add_parser("pack", help="create a claim from a project, or accept it as-is")
    sp.add_argument("--path", default=None, help="the project directory (default: current directory)")
    sp.add_argument("--name", default=None, help="the claim's name")
    sp.add_argument("--root", nargs="+", default=None, metavar="PATTERN",
                     help="glob patterns naming the claim's own pinned files")
    sp.add_argument("--generated", nargs="+", default=None, metavar="PATTERN",
                     help="glob patterns naming the regrowable implementation")
    sp.add_argument("--gate", default=None, metavar="CMD", help="the gate command")
    sp.add_argument("--pytest", action="store_true", help="use pytest as the gate command")
    sp.add_argument("-o", "--output", default=None, metavar="NAME", help="the gate's declared output")
    sp.add_argument("--accept", nargs="+", default=None, metavar="OUTPUT",
                     help="accept the claim's current bytes in place, without re-running a gate")
    sp.add_argument("--into", default=None, metavar="WORKSPACE", help="also pull the packed claim into a workspace")
    sp.add_argument("--force", action="store_true", help="overwrite an existing recipe")
    _parser._add_verbose_json(sp)
    sp.set_defaults(func=_dispatch_pack)

    for builder in (_parser._build_composition, _parser._build_verification,
                    _parser._build_reconstruction, _parser._build_evidence,
                    _parser._build_plumbing):
        builder(sub)

    for name, handler in _DISPATCH.items():
        target = sub.choices.get(name)
        if target is not None:
            target.set_defaults(func=handler)

    return p, sub


def main(argv=None) -> int:
    """The `ret` entry point: parse argv against this module's grammar and
    route to the verb's handler, speaking any `kernel.ClaimError` in the
    one-voice error line rather than letting it crash."""
    p, _sub = _build_parser()
    args = p.parse_args(argv)
    func = getattr(args, "func", None)
    if func is None:
        p.print_help()
        return 1
    try:
        return func(args)
    except kernel.ClaimError as exc:
        output._err(getattr(args, "verb", "ret") or "ret", str(exc))
        return 1


if __name__ == "__main__":
    sys.exit(main())
