"""Held-out measurement: does a claim's implementation satisfy tests it
never saw pinned into its root?

A claim's gates are inside its root, visible to whatever produced the
generated bytes. A held-out check is run against those bytes without ever
joining the claim's own pinned inputs -- copied into a scratch room, run
there under the same confined gate runner every pinned gate uses, and
discarded -- so a pass is evidence of generalizing past the visible suite,
not of having targeted it (`spec/layers.md`: "measuring a claim's
strength").

Stdlib only.
"""
import os
import shutil
import tempfile

from reticuli import kernel, _util


def run(d: str, check_path: str, run_cmd: str) -> dict:
    """Run `run_cmd` against claim `d`'s current generated bytes, with
    `check_path` present alongside them -- never written into `d`, never
    added to its recipe or root.
    """
    doc = kernel.load_recipe(d)
    room = tempfile.mkdtemp(prefix="reticuli-heldout-")
    try:
        for rel in _util.claim_files(doc, d, include_generated=True):
            _util.copy_into(d, room, rel)
        shutil.copy2(check_path, os.path.join(room, os.path.basename(check_path)))
        result = kernel.run_gate(run_cmd, room)
        return {"ok": result["status"] == "ok", "status": result["status"]}
    finally:
        shutil.rmtree(room, ignore_errors=True)


def score(d: str, cases: dict) -> dict:
    """Run every held-out case (`name -> (check_path, run_cmd)`) against
    claim `d`'s current bytes; report how many passed and which did not.
    """
    results = {name: run(d, check_path, run_cmd)
               for name, (check_path, run_cmd) in cases.items()}
    passed = sum(1 for r in results.values() if r["ok"])
    failed = sorted(name for name, r in results.items() if not r["ok"])
    return {"passed": passed, "total": len(results), "failed": failed, "results": results}
