"""pack: a project already on disk becomes a self-claim (`spec/layers.md`).

The boundary is declared, never inferred from provenance: `generated` and
`inputs` are a symmetric pair of pattern lists (expanded into the literal
files they name), the implementation is regrowable and the rest is pinned,
by the caller's word alone. `gate`/`gate_output` name the one verdict this
claim pins. A `component` link records that part of this claim's generated
bytes are carried, by content, `from` a claim already sealed elsewhere --
that component's own declared bytes (never its generated ones) travel
inside this claim's own store, so a deep audit can re-earn it later
(`registry.audit_deep`).

A claim is born at format 3 by default: producer guidance is a hint, not a
criterion, and cannot decide acceptance, so it does not belong in the root
(`spec/identity.md`). `claim_format=1` opts out, writing the keyless
era-1 recipe every pre-format claim still verifies under.

Every gate here runs through `kernel.run_gate` -- scrubbed, sandboxed,
bounded -- never `kernel.sandbox` directly.

Stdlib only.
"""
import glob
import os
import shutil

from reticuli import _util, kernel, registry, render

DEFAULT_FORMAT = 3


def _expand(root_dir: str, patterns: list) -> list:
    """`generated`/`inputs` patterns, expanded into the literal files they
    name (`spec/claim-format.md`): a fixed list, never a pattern, once in
    the recipe.
    """
    out = []
    for pattern in patterns:
        for match in sorted(glob.glob(pattern, root_dir=root_dir)):
            if match not in out:
                out.append(match)
    return out


def _guidance_key(fmt: int) -> str:
    return "request" if fmt < 3 else "guidance"


def _write_manifest_file(root_dir: str, manifest_name: str, inputs: list) -> None:
    lines = [f"{kernel._hash_file(os.path.join(root_dir, p))}  {p}"
             for p in sorted(inputs)]
    with open(os.path.join(root_dir, manifest_name), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + ("\n" if lines else ""))


def _copy_component(root_dir: str, component: dict) -> list:
    """Copy `component`'s own declared, non-generated bytes into this
    claim's own store, and return the link record(s)
    `registry.audit_deep` reads back.
    """
    comp_name = component["name"]
    comp_dir = component["claim"]
    comp_outputs = sorted(set(component.get("outputs", [])))

    comp_root = kernel.read_manifest(comp_dir)["root"]
    comp_doc = kernel.load_recipe(comp_dir)

    dest = os.path.join(root_dir, kernel.STORE, "sealed", comp_name)
    if os.path.isdir(dest):
        shutil.rmtree(dest)
    os.makedirs(dest, exist_ok=True)
    for rel in _util.claim_files(comp_doc, comp_dir, include_generated=False):
        _util.copy_into(comp_dir, dest, rel)

    return [{"input": output, "component": comp_name, "root": comp_root, "output": output}
            for output in comp_outputs]


def pack(root_dir: str, name: str, generated: list, inputs: list, gate: str,
         gate_output: str, component=None, claim_format=None, envelope=None,
         mutation_floor=None, requires=None, by=None, inputs_manifest=None,
         environment=None) -> dict:
    """Declare `root_dir` a claim: `generated`/`inputs` are pattern lists,
    `gate` is the one command whose `gate_output` this claim pins.
    `component`, if given (`{"name", "claim", "outputs"}`), names another
    claim already sealed at `component["claim"]` whose `component["outputs"]`
    this claim carries `from` it.
    """
    fmt = claim_format if claim_format is not None else DEFAULT_FORMAT
    gkey = _guidance_key(fmt)

    generated_files = _expand(root_dir, generated)
    input_files = _expand(root_dir, inputs)
    comp_name = component["name"] if component else None
    comp_outputs = set(component.get("outputs", [])) if component else set()

    steps = []
    for p in generated_files:
        step = {"kind": "produce", "output": p, "class": "generated"}
        if p in comp_outputs:
            step["from"] = comp_name
        else:
            step[gkey] = f"regenerate {p} to pass the gate"
        steps.append(step)
    steps.append({"kind": "gate", "output": gate_output, "class": "validated", "run": gate})

    claim = {"name": name}
    if fmt != 1:
        claim["format"] = fmt
    if inputs_manifest:
        _write_manifest_file(root_dir, inputs_manifest, input_files)
        claim["inputs_manifest"] = inputs_manifest
    else:
        claim["inputs"] = input_files
    if envelope is not None:
        claim["envelope"] = envelope
    if mutation_floor is not None:
        claim["mutation_floor"] = mutation_floor
    if requires is not None:
        claim["requires"] = requires
    if environment is not None:
        claim["environment"] = environment

    doc = {"claim": claim, "step": steps}

    vacuous = kernel.vacuous_gates(doc)
    if vacuous:
        raise kernel.ClaimError(
            f"gate(s) {vacuous} are vacuous: every decider is generated code, "
            "so no pinned byte can reject a realization")

    links = _copy_component(root_dir, component) if component else []

    with open(os.path.join(root_dir, kernel.RECIPE), "w", encoding="utf-8") as f:
        f.write(render.dump_recipe(doc))

    gate_result = kernel.run_gate(gate, root_dir, doc)
    if gate_result["status"] != "ok" or \
            not os.path.isfile(os.path.join(root_dir, gate_output)):
        raise kernel.ClaimError(f"gate {gate_output!r} did not pass: {gate_result['status']}")

    manifest = registry.seal_with(root_dir, components=links or None)

    if by:
        _util.ledger_add(root_dir, {"event": "producer", "model": by})

    return {"ok": True, "root": manifest["root"]}
