"""Transfer: deterministic tar, verify-on-import, volatile history stays home
(`spec/layers.md`).

`export` packs exactly a claim's declared content -- never a tree walk, so
undeclared bytes sitting in the workspace never travel -- plus, for every
component the claim declares, a blind copy of that component's OWN claim
(its recipe, inputs, and pinned outputs; never its generated bytes) under
`.reticuli/deps/<name>/...`, so an importer can re-earn every layer from
bytes alone. `blind=True` additionally withholds the TOP claim's own
generated outputs, for the rebuilder's room. `import_` extracts the tar,
restores `.reticuli/deps/*` to the `.reticuli/sealed/*` convention the
registry reads, and reports whether the received bytes still verify.

Two exports of one claim, taken at different times, are byte-identical:
every tar entry is written with a zeroed mtime/uid/gid, in a fixed sort
order. Stdlib only.
"""
import os
import shutil
import tarfile

from reticuli import _util, kernel

_DEPS_DIR = ".reticuli/deps"
_SEALED_DIR = ".reticuli/sealed"


def _add_deterministic(tf: tarfile.TarFile, path: str, arcname: str) -> None:
    info = tf.gettarinfo(path, arcname=arcname)
    info.mtime = 0
    info.uid = 0
    info.gid = 0
    info.uname = ""
    info.gname = ""
    info.mode = 0o644
    with open(path, "rb") as f:
        tf.addfile(info, f)


def _pack_deps(tf: tarfile.TarFile, d: str, prefix: str, seen: set) -> None:
    """Pack every component `d` declares, blind, under `prefix/<name>/...`,
    recursing into each component's own declared components in turn.
    """
    try:
        manifest = kernel.read_manifest(d)
    except kernel.ClaimError:
        return
    names = []
    for link in manifest.get("components") or []:
        if link["component"] not in names:
            names.append(link["component"])

    for name in names:
        key = f"{prefix}/{name}"
        if key in seen:
            continue
        seen.add(key)
        comp_dir = os.path.join(d, ".reticuli", "sealed", name)
        if not os.path.isdir(comp_dir):
            continue
        try:
            comp_doc = kernel.load_recipe(comp_dir)
        except kernel.ClaimError:
            continue
        for rel in _util.claim_files(comp_doc, comp_dir, include_generated=False):
            _add_deterministic(tf, os.path.join(comp_dir, rel), f"{key}/{rel}")
        _pack_deps(tf, comp_dir, key, seen)


def export(d: str, tar_path: str, blind: bool = False) -> dict:
    """Pack claim `d`'s declared content into a deterministic tar at
    `tar_path`. `blind=True` withholds `d`'s own generated outputs (the
    rebuilder's room); a declared component's generated bytes are always
    withheld, regardless of `blind`.
    """
    doc = kernel.load_recipe(d)
    tmp = tar_path + ".tmp"
    with tarfile.open(tmp, "w") as tf:
        for rel in _util.claim_files(doc, d, include_generated=not blind):
            _add_deterministic(tf, os.path.join(d, rel), rel)
        _pack_deps(tf, d, _DEPS_DIR, set())
    os.replace(tmp, tar_path)
    return {"exported": True, "path": tar_path}


def import_(tar_path: str, into: str) -> dict:
    """Extract `tar_path` into fresh directory `into`, restore any packed
    `.reticuli/deps/*` to the `.reticuli/sealed/*` convention the registry
    reads, and report whether the received bytes verify.
    """
    os.makedirs(into, exist_ok=True)
    with tarfile.open(tar_path, "r") as tf:
        try:
            tf.extractall(into, filter="data")
        except TypeError:
            tf.extractall(into)

    deps_dir = os.path.join(into, _DEPS_DIR)
    if os.path.isdir(deps_dir):
        sealed_dir = os.path.join(into, _SEALED_DIR)
        os.makedirs(sealed_dir, exist_ok=True)
        for name in os.listdir(deps_dir):
            src = os.path.join(deps_dir, name)
            if not os.path.isdir(src):
                continue
            dst = os.path.join(sealed_dir, name)
            if os.path.isdir(dst):
                shutil.rmtree(dst)
            shutil.move(src, dst)
        shutil.rmtree(deps_dir, ignore_errors=True)

    try:
        result = kernel.verify(into)
    except kernel.ClaimError as e:
        return {"ok": False, "reason": str(e)}
    return {"ok": result["ok"], "root": result["root"], "name": result.get("name")}
