"""Authoring: sessions become claims (`spec/layers.md`).

A session is a workspace with a hook-written trace (`TRACE`,
`.reticuli/draft.jsonl`): one JSON object per line, each an `event` --
`prompt` (an instruction), `write` (a file the agent wrote), `read` (a file
the agent read), `bash` (a shell command it ran). `propose(ws, outputs,
name, ...)` reads that trace and drafts a recipe (v1: `draft`) -- it does
not touch disk beyond the trace itself. `build_claim(ws, outputs, rec,
...)` certifies cold (v1: `condense`): it re-earns every gate in a fresh
room built only from the declared bytes, refusing a verdict that does not
reproduce, then seals the result at `rec` and accounts the session's own
production cost (C1) as the one ledger entry a redo's cost is ever
compared against.

Provenance never decides a path's class, only a caller's declaration does:
a path the trace shows written is generated by default, and anything else
the gate touches that is not an explicit input is not declared at all --
unless `claim=` or `generated=` says otherwise. This is deliberate: the
README flow (an agent writes both the solver and its own check) would
otherwise let a vacuous check seal a wrong solver at the same root as a
correct one.

Gates run only through `kernel.run_gate` -- never `kernel.sandbox`
directly -- so every certification gets the same scrub, sandbox, and
wall-clock bound a seal would give it. Confinement (`_util.safe_path`) is
checked on every trace-derived path before anything is ever copied: a
traced read that escapes the session is refused at the boundary, not
copied out of the workspace on the way to a refusal.

Stdlib only.
"""
import json
import os
import re
import shlex
import shutil
import tempfile

from reticuli import _util, kernel, render

TRACE = ".reticuli/draft.jsonl"

_OPERATORS = ("&&", "||", ";", "|")
_REDIRECTS = (">>", ">", "<")


# =============================================================================
# the trace: one JSON object per line
# =============================================================================

def read_trace(ws: str) -> list:
    """Every event in `ws`'s trace, in order; `[]` if there is none yet."""
    path = os.path.join(ws, TRACE)
    if not os.path.isfile(path):
        return []
    events = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                events.append(json.loads(line))
    return events


# =============================================================================
# candidate inputs: real directory entries, matched case-exactly -- never
# `os.path.isfile`, which folds case on macOS and Windows (`spec/identity.md`)
# =============================================================================

def _real_files(ws: str) -> set:
    names = set()
    for base, dirs, files in os.walk(ws):
        if kernel.STORE in dirs:
            dirs.remove(kernel.STORE)
        rel_base = os.path.relpath(base, ws)
        for fn in files:
            rel = fn if rel_base == "." else os.path.join(rel_base, fn)
            names.add(rel.replace(os.sep, "/"))
    return names


def _segments(cmd: str) -> list:
    ops = sorted(_OPERATORS, key=len, reverse=True)
    pattern = "|".join(re.escape(op) for op in ops) + r"|\n"
    return [s for s in re.split(pattern, cmd) if s.strip()]


def _tokens_without_redirects(segment: str) -> list:
    try:
        tokens = shlex.split(segment)
    except ValueError:
        return []
    out = []
    skip_next = False
    for tok in tokens:
        if skip_next:
            skip_next = False
            continue
        if tok in _REDIRECTS:
            skip_next = True
            continue
        out.append(tok)
    return out


def _path_candidates(cmd: str, real_names: set) -> set:
    """Tokens of `cmd` that name a real directory entry, case included --
    the command name and its flags are never candidates."""
    candidates = set()
    for segment in _segments(cmd):
        tokens = _tokens_without_redirects(segment)
        for tok in tokens[1:]:
            if tok.startswith("-"):
                continue
            if tok in real_names:
                candidates.add(tok)
    return candidates


# =============================================================================
# propose: draft a recipe from a session's trace (v1: `draft`)
# =============================================================================

def propose(ws: str, outputs: list, name: str, *, claim=None, generated=None) -> dict:
    """Draft a claim's recipe from `ws`'s trace; touches no disk but the
    trace itself. `outputs` names the gate's verdict file(s); `claim`/
    `generated` override the trace-derived input/implementation split."""
    events = read_trace(ws)
    written = [e["path"] for e in events if e.get("event") == "write" and e.get("path")]
    reads = [e["path"] for e in events if e.get("event") == "read" and e.get("path")]
    bash_cmds = [e["cmd"] for e in events if e.get("event") == "bash" and e.get("cmd")]

    declared = (list(written) + list(reads) + list(outputs)
                + list(claim or []) + list(generated or []))
    for p in declared:
        _util.safe_path(ws, p)

    real_names = _real_files(ws)
    written_set = set(written)
    output_set = set(outputs)

    candidates = set(reads)
    for cmd in bash_cmds:
        candidates |= _path_candidates(cmd, real_names)
    candidates -= output_set
    candidates -= written_set

    if claim is not None:
        input_paths = sorted(set(claim))
    else:
        input_paths = sorted(
            p for p in candidates
            if p in real_names and os.path.isfile(_util.safe_path(ws, p)))

    if generated is not None:
        gen_paths = sorted(set(generated) - set(input_paths))
    else:
        gen_paths = sorted(written_set - set(input_paths))

    claim_table = {"name": name, "format": 3, "inputs": input_paths}
    steps = [{"kind": "produce", "output": g, "class": "generated"} for g in gen_paths]
    gate_cmd = bash_cmds[-1] if bash_cmds else None
    for out in outputs:
        steps.append({"kind": "gate", "output": out, "class": "validated",
                      "run": gate_cmd})

    return {"claim": claim_table, "step": steps}


# =============================================================================
# build_claim: certify cold, then seal (v1: `condense`)
# =============================================================================

def _file_digest(path: str) -> str:
    with open(path, "rb") as f:
        return _util.hash_bytes(f.read())


def build_claim(ws: str, outputs: list, rec: str, *, name: str = None,
                 claim=None, generated=None) -> dict:
    """Certify `ws`'s session cold and seal the result at `rec`.

    Re-earns every declared gate in a fresh room built only from the
    declared inputs and generated bytes; a gate that does not reproduce the
    same verdict bytes there (nondeterministic, or a pinned byte the
    session itself never earned) refuses rather than seals. A gate whose
    every decider is generated is vacuous and refused by name.
    """
    if name is None:
        name = os.path.basename(os.path.normpath(rec))
    doc = propose(ws, outputs, name, claim=claim, generated=generated)

    gate_steps = [s for s in doc["step"] if s["kind"] == "gate"]
    if not gate_steps or any(s.get("run") is None for s in gate_steps):
        raise kernel.ClaimError(
            "no gate command found in the session trace: nothing to certify")

    vacuous = set(kernel.vacuous_gates(doc))
    requested_vacuous = sorted(vacuous & set(outputs))
    if requested_vacuous:
        raise kernel.ClaimError(
            f"gate(s) {requested_vacuous} are vacuous: every decider is a "
            f"generated file -- a check the agent also wrote cannot be its "
            f"own criterion")

    input_paths = doc["claim"]["inputs"]
    gen_paths = [s["output"] for s in doc["step"] if s["kind"] == "produce"]
    for p in list(input_paths) + list(gen_paths) + list(outputs):
        _util.safe_path(ws, p)

    room = tempfile.mkdtemp(prefix="reticuli-build-")
    try:
        with open(os.path.join(room, kernel.RECIPE), "w", encoding="utf-8") as f:
            f.write(render.dump_recipe(doc))
        _util.copy_into(ws, room, input_paths)
        _util.copy_into(ws, room, gen_paths)

        for step in gate_steps:
            result = kernel.run_gate(step["run"], room, doc)
            if result["status"] != "ok":
                raise kernel.ClaimError(
                    f"gate {step['output']!r} did not reproduce cold "
                    f"({result['status']})")
            out_path = _util.safe_path(room, step["output"])
            orig_path = _util.safe_path(ws, step["output"])
            if not os.path.isfile(orig_path):
                raise kernel.ClaimError(
                    f"declared output {step['output']!r} was never produced "
                    f"in the session")
            if _file_digest(out_path) != _file_digest(orig_path):
                raise kernel.ClaimError(
                    f"gate {step['output']!r} did not reproduce the same "
                    f"verdict bytes cold -- the gate is nondeterministic")

        parent = os.path.dirname(rec)
        if parent:
            os.makedirs(parent, exist_ok=True)
        if os.path.exists(rec):
            raise kernel.ClaimError(f"build target already exists: {rec!r}")
        shutil.move(room, rec)
        room = None

        events = read_trace(ws)
        calls = sum(1 for e in events if e.get("event") == "prompt")
        timestamps = [e["ts"] for e in events
                      if isinstance(e.get("ts"), (int, float))
                      and not isinstance(e.get("ts"), bool)]
        seconds = (max(timestamps) - min(timestamps)) if len(timestamps) >= 2 else 0.0
        kernel.ledger(rec, {"calls": calls, "seconds": seconds})

        manifest = kernel.seal(rec)
        return {"ok": True, "root": manifest["root"]}
    finally:
        if room is not None:
            shutil.rmtree(room, ignore_errors=True)
