"""The launcher: run software that exists only latently in a claim
(`spec/layers.md`).

A runnable claim is an ordinary Reticuli claim whose pinned inputs include
`package.toml`, naming an `entrypoint` file inside the claim. `run` makes the
claim executable: if the entrypoint's generated bytes are present and trusted,
it runs them; if they were only ever regrown by this launcher and not yet
accepted, it refuses and offers `--accept-generated`; if they drifted since
acceptance, it refuses and points at `strip`; if nothing is materialized, it
regrows them with the producer named by `RETICULI_PRODUCER`. `strip` deletes
the generated bytes back to latency -- always safe, because the claim's
identity never depended on them. `ls` reports a claim's name, root, phase,
and materialization without running anything.

Consent state (which generated bytes this launcher has itself regrown but
not yet accepted, or has accepted) lives under `<claim>/.launcher/`, never
inside the claim's identity.

Stdlib only.
"""
import hashlib
import json
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
import tomllib

from reticuli import kernel, _util
from reticuli._kernel import core as _kcore
from reticuli._kernel import run as _krun

LAUNCHER_DIR = ".launcher"
STATE_FILE = "state.json"

HELP = """usage: python3 -m reticuli.launcher <verb> [args...]

verbs:
  run   <claim> [--accept-generated] [--signed-only] [--no-sandbox] [-- args...]
  strip <claim>
  ls    <claim>...

run executes a claim's package.toml entrypoint; exit code 3 means the claim
is not runnable, 4 means freshly generated bytes await --accept-generated,
5 means --signed-only refused an unsigned claim, 6 means a drifted build was
refused, 7 means the claim is latent and RETICULI_PRODUCER is unset.
"""


def _err(message: str) -> None:
    print(message, file=sys.stderr)


# -- the claim's recipe: generated outputs, nothing else needed here --------

def _generated_outputs(parsed: dict) -> list:
    outputs = []
    for step in parsed.get("step", []):
        if not isinstance(step, dict) or step.get("kind") != "produce":
            continue
        if step.get("class", "generated") == "generated":
            outputs.append(step["output"])
    return outputs


def _materialized(d: str, generated: list) -> bool:
    return all(os.path.isfile(os.path.join(d, p)) for p in generated)


# -- the package contract: package.toml, pinned, naming a confined entrypoint

def _check_package(d: str) -> str:
    """Return the claim's entrypoint path, or raise `kernel.ClaimError`."""
    inputs = _util.declared_inputs(d)
    if "package.toml" not in inputs:
        raise kernel.ClaimError(
            "claim is not runnable: package.toml is not a pinned input "
            "(declare it under [claim] inputs)")
    path = os.path.join(d, "package.toml")
    if not os.path.isfile(path):
        raise kernel.ClaimError(
            "claim is not runnable: package.toml is missing")
    try:
        with open(path, "rb") as f:
            doc = tomllib.load(f)
    except tomllib.TOMLDecodeError as e:
        raise kernel.ClaimError(f"malformed package.toml: {e}") from e
    pkg = doc.get("package")
    if not isinstance(pkg, dict):
        raise kernel.ClaimError(
            "claim is not runnable: package.toml needs a [package] table")
    entrypoint = pkg.get("entrypoint")
    if not isinstance(entrypoint, str) or not entrypoint:
        raise kernel.ClaimError(
            "claim is not runnable: package.toml [package] entrypoint "
            "must be a non-empty string")
    _util.safe_path(d, entrypoint)
    return entrypoint


# -- launcher state: which generated bytes this launcher regrew/accepted ----

def _state_path(d: str) -> str:
    return os.path.join(d, LAUNCHER_DIR, STATE_FILE)


def _load_state(d: str) -> dict:
    path = _state_path(d)
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            doc = json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}
    return doc if isinstance(doc, dict) else {}


def _save_state(d: str, state: dict) -> None:
    os.makedirs(os.path.join(d, LAUNCHER_DIR), exist_ok=True)
    with open(_state_path(d), "w", encoding="utf-8") as f:
        json.dump(state, f, sort_keys=True)


def _sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _digests(d: str, generated: list) -> dict:
    return {p: _sha256_file(os.path.join(d, p)) for p in generated}


# -- regrowing latent bytes with the configured producer --------------------

def _regrow(d: str, producer: str, generated: list, accept_generated: bool):
    """Regrow `d`'s generated outputs with `producer`.

    Returns an exit code to return immediately (4 on a landed-but-unaccepted
    rebuild, 1 on producer/gate failure), or `None` meaning the caller should
    fall through and execute -- only possible when `accept_generated` was
    already given, so the newly regrown bytes are accepted on the spot.
    """
    room = tempfile.mkdtemp(prefix="reticuli-launcher-")
    try:
        kernel.rebuild(d, producer, room)
    except kernel.ClaimError as e:
        _err(f"rebuild failed: {e}")
        return 1
    finally:
        pass
    try:
        digests = {}
        for output in generated:
            src = os.path.join(room, output)
            dst = os.path.join(d, output)
            os.makedirs(os.path.dirname(dst) or d, exist_ok=True)
            shutil.copy2(src, dst)
            digests[output] = _sha256_file(dst)
    finally:
        shutil.rmtree(room, ignore_errors=True)

    state = _load_state(d)
    if accept_generated:
        state.pop("pending", None)
        state["accepted"] = digests
        _save_state(d, state)
        return None
    state["pending"] = digests
    _save_state(d, state)
    _err("newly generated bytes landed; pass --accept-generated to "
         "execute and accept them")
    return 4


# -- executing the entrypoint: scrubbed, sandboxed, honestly reported -------

def _execute(d: str, entrypoint: str, entry_args: list, no_sandbox: bool) -> int:
    scratch = os.path.join(d, LAUNCHER_DIR, "scratch")
    os.makedirs(scratch, exist_ok=True)

    backend = "off" if no_sandbox else _krun.sandbox_backend()

    env = {k: os.environ[k] for k in _kcore._KEEP_ENV if k in os.environ}
    env["HOME"] = scratch
    env["TMPDIR"] = scratch
    if backend in ("seatbelt", "bubblewrap"):
        env[_kcore._JAILED] = backend

    inner = [sys.executable, entrypoint] + list(entry_args)
    cmd = shlex.join(inner)
    argv = _krun._sandbox_argv(backend, d, scratch, cmd)

    _err(f'phase = "{kernel.phase(d)}"')
    _err(f'quarantine = "{backend}"')
    sys.stderr.flush()

    result = subprocess.run(argv, cwd=d, env=env)
    return result.returncode


# -- run ----------------------------------------------------------------------

def _parse_run_args(rest: list):
    accept_generated = signed_only = no_sandbox = False
    claim_arg = None
    entry_args = []
    i, n = 0, len(rest)
    while i < n:
        tok = rest[i]
        if tok == "--":
            entry_args = list(rest[i + 1:])
            break
        if tok == "--accept-generated":
            accept_generated = True
        elif tok == "--signed-only":
            signed_only = True
        elif tok == "--no-sandbox":
            no_sandbox = True
        elif claim_arg is None:
            claim_arg = tok
        i += 1
    return accept_generated, signed_only, no_sandbox, claim_arg, entry_args


def cmd_run(rest: list) -> int:
    accept_generated, signed_only, no_sandbox, claim_arg, entry_args = \
        _parse_run_args(rest)
    if claim_arg is None:
        _err("run requires a claim path")
        return 3

    d = os.path.abspath(claim_arg)

    try:
        parsed = kernel.load_recipe(d)
    except kernel.ClaimError as e:
        _err(str(e))
        return 3

    try:
        entrypoint = _check_package(d)
    except kernel.ClaimError as e:
        _err(str(e))
        return 3

    generated = _generated_outputs(parsed)

    if not _materialized(d, generated):
        producer = os.environ.get("RETICULI_PRODUCER")
        if not producer:
            _err("claim is latent and no producer is configured; "
                 "set RETICULI_PRODUCER to regrow it")
            return 7
        rc = _regrow(d, producer, generated, accept_generated)
        if rc is not None:
            return rc
    else:
        state = _load_state(d)
        current = _digests(d, generated)
        if "pending" in state:
            if state["pending"] != current:
                _err("drifted build: generated bytes no longer match what "
                     "was pending; run strip to recover")
                return 6
            if accept_generated:
                state["accepted"] = state.pop("pending")
                _save_state(d, state)
            else:
                _err("newly generated bytes await consent; pass "
                     "--accept-generated to execute and accept them")
                return 4
        elif "accepted" in state:
            if state["accepted"] != current:
                _err("drifted build: an accepted implementation's bytes no "
                     "longer match what was accepted; run strip to recover")
                return 6
        # else: no launcher state -- an implementation the launcher never
        # generated or accepted runs on audit alone.

    if signed_only and kernel.phase(d) != "signed":
        _err("--signed-only refused: this claim is not signed to you")
        return 5

    return _execute(d, entrypoint, entry_args, no_sandbox)


# -- strip --------------------------------------------------------------------

def cmd_strip(rest: list) -> int:
    if not rest:
        _err("strip requires a claim path")
        return 3
    d = os.path.abspath(rest[0])

    try:
        parsed = kernel.load_recipe(d)
    except kernel.ClaimError as e:
        _err(str(e))
        return 3

    for output in _generated_outputs(parsed):
        path = os.path.join(d, output)
        if os.path.isfile(path):
            os.remove(path)

    launcher_dir = os.path.join(d, LAUNCHER_DIR)
    if os.path.isdir(launcher_dir):
        shutil.rmtree(launcher_dir, ignore_errors=True)

    _err("stripped generated bytes back to latency")
    return 0


# -- ls -------------------------------------------------------------------

def _print_ls_line(d: str) -> None:
    try:
        manifest = kernel.read_manifest(d)
        ph = kernel.phase(d)
    except kernel.ClaimError as e:
        print(f"{d}  <{e}>")
        return
    try:
        parsed = kernel.load_recipe(d)
        generated = _generated_outputs(parsed)
    except kernel.ClaimError:
        generated = []
    status = "materialized" if _materialized(d, generated) else "latent"
    print(f"{manifest.get('name', '')}  {manifest.get('root', '')[:8]}  "
          f"{ph}  {status}")


def cmd_ls(rest: list) -> int:
    if not rest:
        _err("ls requires at least one claim path")
        return 3
    for claim_arg in rest:
        _print_ls_line(os.path.abspath(claim_arg))
    return 0


# -- entry point --------------------------------------------------------------

def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv or argv[0] in ("-h", "--help"):
        sys.stdout.write(HELP)
        return 0

    verb, rest = argv[0], argv[1:]
    try:
        if verb == "run":
            return cmd_run(rest)
        if verb == "strip":
            return cmd_strip(rest)
        if verb == "ls":
            return cmd_ls(rest)
    except kernel.ClaimError as e:
        _err(str(e))
        return 3

    _err(f"unknown verb: {verb!r}")
    return 3


if __name__ == "__main__":
    sys.exit(main())
