"""Transfer: deterministic export, verify-on-import (`spec/layers.md`).

`export(d, tar_path, blind=False)` packages exactly a claim's DECLARED
content -- its recipe, pinned inputs, and (unless `blind`) its generated
outputs -- never a stray file dropped in its directory, and never the
volatile ledger (`spec/claim-format.md`: the store carries residue, not
identity). A `blind` export withholds every generated byte, so what it
withholds is exactly what a producer is asked to regrow. Every declared
component (`.reticuli/manifest.json`'s `components`) travels too, nested
under `.reticuli/deps/<name>/...`, recursively, and always blind -- a
component's own claim (recipe, inputs, pins) travels so an importer can
re-earn every layer from bytes alone, but never a component's generated
bytes. Two exports of the same claim are byte-identical: fixed tar
metadata, sorted entries.

`import_(tar_path, into)` extracts and verifies identity on the received
bytes -- the room's own criteria never travel with it; what does is what
`spec/identity.md` already names.

Stdlib only.
"""
import io
import os
import tarfile

from reticuli import _util, kernel

ATTEST_DIR = ".reticuli/attest"


def _locate_component(d: str, name: str):
    for sub in ("sealed", "deps"):
        cand = os.path.join(d, kernel.STORE, sub, name)
        if os.path.isdir(cand):
            return cand
    return None


def _own_relnames(d: str, blind: bool) -> list:
    parsed = kernel.load_recipe(d)
    names = [_util.recipe_name(d)]
    if os.path.isfile(os.path.join(d, kernel.MANIFEST)):
        names.append(kernel.MANIFEST)
    for name in _util.declared_inputs(d):
        if os.path.isfile(_util.safe_path(d, name)):
            names.append(name)
    for step in parsed.get("step", []):
        output = step.get("output")
        if not output:
            continue
        cls = step.get("class") or (
            "generated" if step.get("kind") == "produce" else "pinned")
        path = _util.safe_path(d, output)
        if not os.path.isfile(path):
            continue
        if cls == "generated" and blind:
            continue
        names.append(output)
    return names


def _dep_entries(d: str, prefix: str = "") -> list:
    entries = []
    try:
        manifest = kernel.read_manifest(d)
    except kernel.ClaimError:
        return entries
    seen = set()
    for link in manifest.get("components") or []:
        name = link["component"]
        if name in seen:
            continue
        seen.add(name)
        comp_dir = _locate_component(d, name)
        if comp_dir is None:
            continue
        dep_prefix = f"{prefix}.reticuli/deps/{name}/"
        for rel in _own_relnames(comp_dir, blind=True):
            entries.append((dep_prefix + rel, os.path.join(comp_dir, rel)))
        entries.extend(_dep_entries(comp_dir, prefix=dep_prefix))
    return entries


def _attest_entries(d: str) -> list:
    entries = []
    base = os.path.join(d, ATTEST_DIR)
    if os.path.isdir(base):
        for root_dir, _dirs, files in os.walk(base):
            for fn in sorted(files):
                full = os.path.join(root_dir, fn)
                rel = os.path.relpath(full, d).replace(os.sep, "/")
                entries.append((rel, full))
    return entries


def export(d: str, tar_path: str, blind: bool = False) -> None:
    """Write a deterministic tar of `d`'s declared content."""
    entries = [(rel, os.path.join(d, rel)) for rel in _own_relnames(d, blind)]
    entries += _attest_entries(d)
    entries += _dep_entries(d)

    by_name = {}
    for arcname, path in entries:
        by_name[arcname] = path
    ordered = sorted(by_name.items(), key=lambda kv: kv[0])

    with tarfile.open(tar_path, "w", format=tarfile.USTAR_FORMAT) as tar:
        for arcname, path in ordered:
            with open(path, "rb") as f:
                data = f.read()
            info = tarfile.TarInfo(name=arcname)
            info.size = len(data)
            info.mtime = 0
            info.uid = 0
            info.gid = 0
            info.uname = ""
            info.gname = ""
            info.mode = 0o644
            tar.addfile(info, io.BytesIO(data))


def import_(tar_path: str, into: str) -> dict:
    """Extract `tar_path` into `into` and verify identity on received bytes."""
    os.makedirs(into, exist_ok=True)
    with tarfile.open(tar_path, "r") as tar:
        tar.extractall(into)
    result = kernel.verify(into)
    return {"ok": result["ok"], "root": result["root"]}
