"""Cold audits and independent rebuilds of sealed claims."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from . import core, identity, recipe, run, seal


sandbox_backend = run.sandbox_backend


def _compare_pin(original, rebuilt, name):
    """Compare a declared pinned file in two rooms."""
    try:
        return (core._hash_file(core._safe(original, name)) ==
                core._hash_file(core._safe(rebuilt, name)))
    except core.ClaimError:
        return False


def _step_guidance(step):
    return step.get("guidance", step.get("request", ""))


def _read_usage(directory):
    """Read an optional producer usage report, ignoring unsupported units."""
    path = core._safe(directory, core.USAGE)
    try:
        with open(path, encoding="utf-8") as source:
            report = json.load(source)
    except (OSError, UnicodeError, ValueError):
        return {}
    if not isinstance(report, dict):
        return {}
    return {key: value for key, value in report.items()
            if key in ("usd", "tokens", "calls")
            and type(value) in (int, float) and value >= 0}


def _ssh_verify(data, signature, allowed_signers, namespace=core.SIGN_NAMESPACE,
                principal="reticuli"):
    """Verify a detached SSH signature against the caller's trust anchor."""
    try:
        result = subprocess.run(
            ["ssh-keygen", "-Y", "verify", "-f", os.fspath(allowed_signers),
             "-I", principal, "-n", namespace, "-s", os.fspath(signature)],
            input=data, capture_output=True, check=False)
    except OSError:
        return False
    return result.returncode == 0


def _authorized(*args, **kwargs):
    """Test an authorization signature if an anchor is supplied."""
    if len(args) < 3:
        return False
    return _ssh_verify(*args, **kwargs)


def _room_recipe(source, destination, parsed):
    source_path = recipe.recipe_path(source)
    target = core._safe(destination, os.path.basename(source_path))
    if parsed["claim"].get("format", 1) < 3:
        core._copy_into(source_path, target)
        return
    # Guidance is an authoring hint outside format-3 identity. A gate sees
    # only the acceptance-bearing recipe; the producer gets the hint in env.
    with open(source_path, encoding="utf-8") as source_file:
        lines = source_file.readlines()
    with open(target, "w", encoding="utf-8") as room_file:
        for line in lines:
            if line.lstrip().startswith(("guidance =", "request =")):
                continue
            room_file.write(line)


def _materialize(source, destination, parsed=None, *, generated=True):
    """Copy declared files into a fresh judging room, omitting old verdicts."""
    parsed = parsed or recipe.load_recipe(source)
    os.makedirs(destination, exist_ok=True)
    _room_recipe(source, destination, parsed)
    names = recipe._inputs(parsed, source)
    for step in recipe.produces(parsed):
        classification = step.get("class", "generated")
        if classification != "generated" or "from" in step or generated:
            names.append(step["output"])
    for name in dict.fromkeys(names):
        source_path = core._safe(source, name)
        if not os.path.isfile(source_path):
            if name in recipe.generated_outputs(parsed):
                continue
            raise core.ClaimError(f"missing declared file: {name}")
        core._hash_file(source_path)
        core._copy_into(source_path, core._safe(destination, name))
    return destination


def _gate_rows(source, room, parsed):
    rows = []
    for step in recipe.gates(parsed):
        name = step["output"]
        result = run.run_gate(step["run"], room, parsed)
        row = {"output": name, "status": result["status"],
               "quarantine": result["quarantine"]}
        if result["status"] == "ok":
            row["status"] = "reproduced" if _compare_pin(source, room, name) else "mismatch"
        for key in ("stderr", "stdout", "missing", "error", "returncode"):
            if key in result:
                row[key] = result[key]
        rows.append(row)
    return rows


def audit(directory, *, shallow=False):
    """Re-run gates on the present generated bytes in a fresh room."""
    checked = seal.verify(directory)
    if not checked["ok"]:
        return {"ok": False, "root": checked["root"], "gates": [],
                "verdict": "identity mismatch", "quarantine": sandbox_backend()}
    parsed = recipe.load_recipe(directory)
    with tempfile.TemporaryDirectory(prefix="reticuli-audit-") as room:
        _materialize(directory, room, parsed)
        try:
            run.furnish(room, parsed)
        except core.ClaimError as exc:
            return {"ok": False, "root": checked["root"], "gates": [],
                    "verdict": f"environment: {exc}",
                    "quarantine": sandbox_backend()}
        rows = _gate_rows(directory, room, parsed)
    good = all(row["status"] == "reproduced" for row in rows)
    return {"ok": good, "root": checked["root"], "gates": rows,
            "verdict": "earned" if good else "carried or broken",
            "quarantine": sandbox_backend()}


def _produce(command, directory, parsed, step, *, guidance=True,
             producer_env=None):
    outputs = recipe.generated_outputs(parsed)
    target = core._safe(directory, step["output"])
    os.makedirs(os.path.dirname(target), exist_ok=True)
    env = run._scrub_env(directory, "none")
    env[core._ENV_OUTPUT] = target
    env[core._ENV_OUTPUTS] = json.dumps(outputs)
    env[core._ENV_CLAIM] = os.path.realpath(directory)
    if guidance:
        env[core._ENV_REQUEST] = _step_guidance(step)
    if producer_env:
        env.update(producer_env)
    try:
        return run._run([core._SHELL, "-c", command], directory,
                        env, core.PRODUCER_TIMEOUT)
    except OSError as exc:
        return {"status": "environment", "error": str(exc), "seconds": 0.0}


def rebuild(directory, producer, into, *, produce_from=None, input_from=None,
            guidance=True, producer_env=None):
    """Regrow generated files, re-earn gates, and seal a fresh claim room."""
    original = seal.verify(directory)
    if not original["ok"]:
        raise core.ClaimError("source claim identity mismatch")
    parsed = recipe.load_recipe(directory)
    destination = os.path.realpath(into)
    if os.path.exists(destination) and os.listdir(destination):
        raise core.ClaimError(f"rebuild destination is not empty: {destination}")
    _materialize(directory, destination, parsed, generated=False)
    producer_results = []
    for step in recipe.produces(parsed):
        if step.get("class", "generated") != "generated" or "from" in step:
            continue
        result = _produce(producer, destination, parsed, step,
                          guidance=guidance, producer_env=producer_env)
        producer_results.append(result)
        event = {"seconds": result.get("seconds", 0.0), "calls": 1,
                 "quarantine": "none", "status": result["status"]}
        event.update(_read_usage(destination))
        run.ledger(destination, event)
        if result["status"] != "ok":
            raise core.ClaimError(f"producer failed for {step['output']}: "
                                  f"{result.get('stderr', result.get('error', ''))}")
    try:
        run.furnish(destination, parsed)
    except core.ClaimError as exc:
        raise core.ClaimError(f"rebuild environment: {exc}") from exc
    rows = _gate_rows(directory, destination, parsed)
    if any(row["status"] != "reproduced" for row in rows):
        raise core.ClaimError(f"rebuild gates did not reproduce: {rows}")
    manifest = seal.seal(destination)
    if manifest["root"] != original["root"]:
        raise core.ClaimError("rebuild root differs from source")
    return {"root": manifest["root"], "name": manifest["name"],
            "build_digest": identity.build_digest(destination),
            "gates": rows, "quarantine": sandbox_backend(),
            "producer": producer_results}
