"""The launcher: run software that exists only latently in a claim
(`checks/launcher_check.py`, `spec/layers.md`).

A runnable claim is an ordinary claim whose pinned inputs include
`package.toml`, naming an `entrypoint`. `run` checks a cached build or
regrows a fresh one with a producer, then executes the entrypoint;
`strip` deletes the generated bytes back to latency (always safe, because
the claim -- not the code -- is the identity); `ls` reports a claim's
name, root, materialization, and phase.

Consent is a durable state, not per-invocation friction: bytes this
launcher regrows stay "fresh" across invocations until a `run` with
`--accept-generated` executes and accepts them, recording their build
digest under `<claim>/.launcher/`. An implementation this launcher never
generated or accepted (packed by hand, imported) runs on audit alone --
this launcher guards only what it itself accepted. Drift -- an accepted
implementation whose bytes no longer match what was accepted, even if the
new bytes would still pass the gate -- refuses loudly and executes
nothing.

Only `run`'s entrypoint writes to stdout; every other word this module
prints, for every verb, goes to stderr -- except `ls`, whose listing IS
its output.

Stdlib only.
"""
import os
import shutil
import subprocess
import sys
import tempfile
import tomllib

from reticuli import kernel
from reticuli import _util

STATE_DIR = ".launcher"
STATE_FILE = "state.json"


class LauncherRefusal(Exception):
    """A refusal, with a reason, that does not touch the claim."""


def eprint(msg: str) -> None:
    sys.stderr.write(msg.rstrip("\n") + "\n")


# ---- the recipe, read generically (no kernel private reached) -------------

def _generated_outputs(parsed: dict) -> list:
    return [s["output"] for s in parsed.get("step", [])
            if s.get("kind") == "produce" and s.get("class", "generated") == "generated"]


def _check_confinement(claim_dir: str, parsed: dict) -> None:
    """Every produce step's output must stay inside the claim -- checked
    before anything is deleted, written, or executed."""
    for output in _generated_outputs(parsed):
        try:
            _util.safe_path(claim_dir, output)
        except ValueError as exc:
            raise LauncherRefusal(
                f"path boundary: refusing generated output {output!r}: {exc}") from exc


# ---- the package contract ---------------------------------------------------

def _check_package(claim_dir: str, parsed: dict) -> str:
    """Validate the package contract and return the entrypoint's relative
    path. `package.toml` must be present, a PINNED input (never a
    generated output), and name an entrypoint that stays inside the
    claim."""
    pkg_path = os.path.join(claim_dir, "package.toml")
    if not os.path.isfile(pkg_path):
        raise LauncherRefusal(
            "not runnable: no package.toml pinned input is declared")

    inputs = set(_util.declared_inputs(parsed, claim_dir))
    generated = set(_generated_outputs(parsed))
    if "package.toml" in generated or "package.toml" not in inputs:
        raise LauncherRefusal(
            "not runnable: package.toml must be a pinned input, never a "
            "generated output")

    try:
        with open(pkg_path, "rb") as f:
            doc = tomllib.load(f)
    except tomllib.TOMLDecodeError as exc:
        raise LauncherRefusal(f"not runnable: malformed package.toml: {exc}") from exc

    entrypoint = (doc.get("package") or {}).get("entrypoint")
    if not isinstance(entrypoint, str) or not entrypoint:
        raise LauncherRefusal(
            "not runnable: package.toml needs a string [package] entrypoint")

    try:
        _util.safe_path(claim_dir, entrypoint)
    except ValueError as exc:
        raise LauncherRefusal(
            f"not runnable: entrypoint {entrypoint!r} escapes the claim: {exc}") from exc

    return entrypoint


# ---- launcher state: what THIS launcher generated or accepted -------------

def _state_path(claim_dir: str) -> str:
    return os.path.join(claim_dir, STATE_DIR, STATE_FILE)


def _read_state(claim_dir: str):
    path = _state_path(claim_dir)
    if not os.path.isfile(path):
        return None
    try:
        return _util.read_json(path)
    except (OSError, ValueError):
        return None


def _write_state(claim_dir: str, state: dict) -> None:
    _util.write_json(_state_path(claim_dir), state)


# ---- the sandbox, probed functionally (a present-but-broken backend
#      counts as none, honestly reported) -----------------------------------

def _sandbox_backend(no_sandbox: bool) -> str:
    if no_sandbox:
        return "off"
    if os.environ.get("RETICULI_JAILED"):
        return "inherited"
    if sys.platform == "darwin" and shutil.which("sandbox-exec"):
        return "seatbelt"
    if sys.platform.startswith("linux") and shutil.which("bwrap"):
        try:
            probe = subprocess.run(
                ["bwrap", "--ro-bind", "/", "/", "--unshare-net", "true"],
                capture_output=True, timeout=5, check=False)
            if probe.returncode == 0:
                return "bubblewrap"
        except (OSError, subprocess.TimeoutExpired):
            pass
    return "none"


def _quote_sb(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _seatbelt_profile(room: str) -> str:
    room_q = _quote_sb(room)
    return "\n".join([
        "(version 1)",
        "(deny default)",
        "(allow file-read*)",
        f'(allow file-write* (subpath "{room_q}"))',
        '(allow file-write-data (literal "/dev/null"))',
        "(allow process-fork)",
        "(allow process-exec)",
        "(allow signal (target same-sandbox))",
        "(allow sysctl-read)",
        "(allow mach-lookup)",
        "(allow iokit-open)",
        "",
    ])


def _wrap_sandbox(backend: str, room: str, argv: list) -> list:
    room_real = os.path.realpath(room)
    if backend == "seatbelt":
        return ["sandbox-exec", "-p", _seatbelt_profile(room_real)] + argv
    if backend == "bubblewrap":
        return [
            "bwrap",
            "--ro-bind", "/", "/",
            "--dev", "/dev",
            "--proc", "/proc",
            "--bind", room_real, room_real,
            "--unshare-net",
            "--die-with-parent",
            "--",
        ] + argv
    return argv


def _execute(claim_dir: str, entrypoint: str, entry_args: list, no_sandbox: bool) -> int:
    """Run the entrypoint: scrubbed environment, sandboxed, the claim
    root as cwd. stdout is inherited untouched -- it belongs to the
    entrypoint alone."""
    backend = _sandbox_backend(no_sandbox)
    eprint(f'quarantine = "{backend}"')

    scratch = os.path.join(claim_dir, STATE_DIR, "room")
    os.makedirs(scratch, exist_ok=True)

    env = {k: os.environ[k] for k in ("PATH", "LANG", "LC_ALL", "LANGUAGE", "TZ")
           if k in os.environ}
    env["HOME"] = scratch
    env["TMPDIR"] = scratch
    if backend not in ("none", "off"):
        env["RETICULI_JAILED"] = backend

    argv = _wrap_sandbox(backend, claim_dir, [sys.executable, entrypoint] + list(entry_args))
    proc = subprocess.run(argv, cwd=claim_dir, env=env, check=False)
    return proc.returncode


# ---- run --------------------------------------------------------------------

_RUN_FLAGS = {
    "--accept-generated": "accept_generated",
    "--signed-only": "signed_only",
    "--no-sandbox": "no_sandbox",
}


def _parse_run_args(args: list):
    opts = {"accept_generated": False, "signed_only": False, "no_sandbox": False}
    claim_arg = None
    entry_args = []
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--":
            entry_args = list(args[i + 1:])
            break
        if a in _RUN_FLAGS:
            opts[_RUN_FLAGS[a]] = True
        elif claim_arg is None:
            claim_arg = a
        i += 1
    return opts, claim_arg, entry_args


def cmd_run(args: list) -> int:
    opts, claim_arg, entry_args = _parse_run_args(args)
    if claim_arg is None:
        eprint("run requires a claim path")
        return 3
    claim_dir = os.path.abspath(claim_arg)

    try:
        parsed = kernel.load_recipe(claim_dir)
        _check_confinement(claim_dir, parsed)
        entrypoint = _check_package(claim_dir, parsed)
    except kernel.ClaimError as exc:
        eprint(f"not runnable: {exc}")
        return 3
    except LauncherRefusal as exc:
        eprint(str(exc))
        return 3

    generated = _generated_outputs(parsed)
    missing = [o for o in generated if not os.path.isfile(os.path.join(claim_dir, o))]
    pending_accept = False

    if missing:
        producer = os.environ.get("RETICULI_PRODUCER")
        if not producer:
            eprint("latent claim: no cached build, and RETICULI_PRODUCER is "
                    "unset -- nothing to run")
            return 7
        room = tempfile.mkdtemp(prefix="reticuli-launcher-")
        try:
            kernel.rebuild(claim_dir, producer, room)
            if generated:
                _util.copy_into(room, claim_dir, names=generated)
        except kernel.ClaimError as exc:
            eprint(f"rebuild failed: {exc}; strip and retry")
            return 6
        finally:
            shutil.rmtree(room, ignore_errors=True)

        current_digest = kernel.build_digest(claim_dir)
        if not opts["accept_generated"]:
            _write_state(claim_dir, {"status": "fresh", "digest": current_digest})
            eprint("freshly generated bytes materialized but not executed -- "
                   "pass --accept-generated to execute and accept them")
            return 4
        pending_accept = True
    else:
        current_digest = kernel.build_digest(claim_dir)
        state = _read_state(claim_dir)
        if state is None:
            try:
                audited = kernel.audit(claim_dir)
            except kernel.ClaimError as exc:
                eprint(f"drifted build: {exc}; strip to recover")
                return 6
            if not audited.get("ok"):
                eprint("drifted build: audit failed; strip to recover")
                return 6
        elif state.get("status") == "accepted":
            if current_digest != state.get("digest"):
                eprint("drifted build: the accepted implementation's bytes "
                       "changed; strip to recover")
                return 6
        elif state.get("status") == "fresh":
            if not opts["accept_generated"]:
                eprint("freshly generated bytes materialized but not "
                       "executed -- pass --accept-generated to execute and "
                       "accept them")
                return 4
            pending_accept = True

    try:
        phase = kernel.phase(claim_dir)
    except kernel.ClaimError as exc:
        eprint(f"not runnable: {exc}")
        return 3
    eprint(f'reticuli: running a {phase} claim')

    if opts["signed_only"] and phase != "signed":
        eprint(f'trust refused: this is a {phase} claim, not signed to you '
               f'(--signed-only)')
        return 5

    rc = _execute(claim_dir, entrypoint, entry_args, opts["no_sandbox"])

    if pending_accept:
        _write_state(claim_dir, {"status": "accepted", "digest": current_digest})

    return rc


# ---- strip ------------------------------------------------------------------

def cmd_strip(args: list) -> int:
    if not args:
        eprint("strip requires a claim path")
        return 2
    claim_dir = os.path.abspath(args[0])

    try:
        parsed = kernel.load_recipe(claim_dir)
        _check_confinement(claim_dir, parsed)
    except kernel.ClaimError as exc:
        eprint(f"not runnable: {exc}")
        return 3
    except LauncherRefusal as exc:
        eprint(str(exc))
        return 3

    for output in _generated_outputs(parsed):
        path = os.path.join(claim_dir, output)
        if os.path.isfile(path):
            os.remove(path)

    shutil.rmtree(os.path.join(claim_dir, STATE_DIR), ignore_errors=True)
    eprint(f"stripped the generated bytes from {claim_dir}")
    return 0


# ---- ls ---------------------------------------------------------------------

def cmd_ls(args: list) -> int:
    if not args:
        eprint("ls requires at least one claim path")
        return 2

    lines = []
    for claim_arg in args:
        claim_dir = os.path.abspath(claim_arg)
        try:
            parsed = kernel.load_recipe(claim_dir)
            manifest = kernel.read_manifest(claim_dir)
            phase = kernel.phase(claim_dir)
            generated = _generated_outputs(parsed)
            latent = any(not os.path.isfile(os.path.join(claim_dir, o))
                        for o in generated)
            state = "latent" if latent else "materialized"
            lines.append(f"{manifest['name']}  {manifest['root']}  "
                         f"{state}  {phase}  {claim_dir}")
        except kernel.ClaimError as exc:
            lines.append(f"{claim_arg}: refused: {exc}")

    print("\n".join(lines))
    return 0


# ---- the surface --------------------------------------------------------

def print_help() -> None:
    print(
        "usage: python3 -m reticuli.launcher <verb> [options]\n"
        "\n"
        "  run   <claim> [--accept-generated] [--signed-only] "
        "[--no-sandbox] [-- args...]\n"
        "  strip <claim>\n"
        "  ls    <claim>...\n"
    )


def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv or argv[0] in ("-h", "--help"):
        print_help()
        return 0

    verb, rest = argv[0], argv[1:]
    if verb == "run":
        return cmd_run(rest)
    if verb == "strip":
        return cmd_strip(rest)
    if verb == "ls":
        return cmd_ls(rest)

    eprint(f"unknown verb {verb!r}; expected run, strip, or ls")
    return 2


if __name__ == "__main__":
    sys.exit(main())
