"""heldout: measuring a claim against tests it was never asked to pass.

A claim's own gate is pinned into its root; running it again proves nothing
new -- it is the same question, asked of the same answer. A held-out test
lives outside the claim entirely: a second acceptance script, written
independently of the bytes being judged. `score` runs each one against a
claim's present generated bytes, in a scratch room, so the claim directory
itself is never touched and the claim's own root never enters the question.
"""
import os
import shutil
import subprocess
import tempfile

from reticuli import _util, kernel

HELDOUT_TIMEOUT = 120.0


def run_one(d: str, test_path: str, *, timeout: float = HELDOUT_TIMEOUT) -> dict:
    """Run one held-out test script against `d`'s current bytes.

    Every regular file in `d` (its store excluded) is copied into a fresh
    room alongside the test script, which is then run with that room as
    its working directory. Nothing is written back to `d`.
    """
    room = tempfile.mkdtemp()
    try:
        for name in os.listdir(d):
            if name == kernel.STORE:
                continue
            src = os.path.join(d, name)
            if os.path.isfile(src) and not os.path.islink(src):
                _util.copy_into(src, os.path.join(room, name))
        test_name = os.path.basename(test_path)
        _util.copy_into(test_path, os.path.join(room, test_name))
        try:
            result = subprocess.run(["python3", test_name], cwd=room,
                                     capture_output=True, timeout=timeout)
            ok = result.returncode == 0
            status = "ok" if ok else "failed"
        except subprocess.TimeoutExpired:
            ok, status = False, "timeout"
        return {"test": test_path, "status": status, "ok": ok}
    finally:
        shutil.rmtree(room, ignore_errors=True)


def score(d: str, tests: list, *, timeout: float = HELDOUT_TIMEOUT) -> dict:
    """Run every held-out test in `tests` against `d`; report each result
    and the overall held-out rate -- a number the claim's own pinned gate
    has no way to inflate, because none of these tests are in it.
    """
    results = [run_one(d, t, timeout=timeout) for t in tests]
    total = len(results)
    passed = sum(1 for r in results if r["ok"])
    rate = None if total == 0 else passed / total
    return {"results": results, "passed": passed, "total": total, "rate": rate}
