"""Deep re-earning and blind regrowth: `audit` and `rebuild`.

`audit` trusts nothing already on disk: every gate's pinned output is
deleted and the gate re-run cold, in place, so a verdict is either earned
fresh on present bytes or the claim is reported broken -- never a carried
"passed" from the past (spec/verification.md). Identity is then recomputed
and compared against the sealed manifest, which is what catches a tampered
*input* even though no gate command reads it.

`rebuild` regrows a claim's generated outputs into a fresh, otherwise-empty
room: `_materialize` furnishes the room with exactly the bytes a producer is
allowed to see (pinned inputs, and -- at format 3+ -- the guidance-stripped,
step-canonicalized preimage recipe as real TOML, never the raw file); `_produce`
then runs the caller's producer command once per generated output, inheriting
the caller's own environment and reachability (a producer is the caller's
oracle, not a jailed gate) while naming its target absolutely. The room's
gates are run the same way any gate runs, and a room that earns them is
sealed -- landing the same root as the claim it was grown from, because the
root never depended on generated bytes to begin with.
"""
import json
import os
import subprocess
import tempfile
import time

from . import core
from . import identity
from . import recipe as recipe_module
from . import run as run_module
from . import seal
from .core import ClaimError


# --------------------------------------------------------------- audit --

def audit(d: str) -> dict:
    """Re-earn every gate's verdict cold, in place, then re-check identity.

    Deletes each gate's pinned output before re-running its command, so a
    `reproduced` status means this machine just earned those bytes, not that
    it found them already sitting there. A gate that fails, times out, or
    writes different bytes than the sealed hash marks the claim broken; so
    does a root that no longer matches the manifest once the gates are done
    -- which is how a tampered pinned *input* is caught even when no gate
    command happens to read it.
    """
    recipe = recipe_module.load_recipe(d)
    manifest = seal.read_manifest(d)

    missing = run_module.preflight(recipe)
    if missing:
        return {"ok": False, "verdict": f"environment: missing {missing}", "gates": []}

    gates_result = []
    ok = True
    for step in recipe_module.gates(recipe):
        output = step["output"]
        path = core._safe(d, output)
        before = core._hash_file(path) if os.path.isfile(path) else None
        if os.path.isfile(path):
            os.remove(path)

        result = run_module.run_gate(step["run"], d, recipe)
        quarantine = result["quarantine"]

        if result["status"] != "ok":
            ok = False
            gates_result.append({"output": output, "status": result["status"],
                                  "quarantine": quarantine})
            continue
        if not os.path.isfile(path):
            ok = False
            gates_result.append({"output": output, "status": "failed",
                                  "quarantine": quarantine})
            continue
        if before is not None and not _compare_pin(path, before):
            ok = False
            gates_result.append({"output": output, "status": "mismatch",
                                  "quarantine": quarantine})
            continue
        gates_result.append({"output": output, "status": "reproduced",
                              "quarantine": quarantine})

    recomputed = identity.root(recipe, d)
    if recomputed != manifest["root"]:
        ok = False

    return {
        "ok": ok,
        "root": manifest["root"],
        "recomputed": recomputed,
        "gates": gates_result,
        "verdict": "earned" if ok else "broken",
    }


def _compare_pin(path: str, expected: str) -> bool:
    """Does the file at `path` hash to `expected` right now?"""
    return os.path.isfile(path) and core._hash_file(path) == expected


# ------------------------------------------------------------- rebuild --

def rebuild(d: str, producer: str, into: str, *, produce_from: dict = None,
            input_from: str = None, guidance: bool = True,
            producer_env: dict = None) -> dict:
    """Regrow `d`'s generated outputs into the fresh directory `into`.

    `input_from` sources the pinned inputs and recipe (default: `d` itself).
    `produce_from` supplies bytes for a produce step that names a `from`
    claim, bypassing the producer for that output. `guidance` withholds
    every producer hint from the room's environment when false, for a blind
    measurement of what the criteria alone carry. `producer_env` is merged
    into the producer's environment past the host's own, the one road an
    inherited credential may travel by the caller's deliberate hand.
    """
    source = input_from or d
    recipe = recipe_module.load_recipe(source)
    if os.path.isdir(into) and os.listdir(into):
        raise ClaimError(f"refuses a non-empty rebuild target: {into!r}")

    _materialize(source, into, recipe)

    outs = recipe_module.generated_outputs(recipe)
    usage_total = {}
    for step in recipe_module.produces(recipe):
        if step.get("class", "generated") != "generated":
            continue
        output = step["output"]
        if "from" in step:
            src = (produce_from or {}).get(output) or step.get("from")
            if src and os.path.isfile(src):
                core._copy_into(src, core._safe(into, output))
            continue
        usage = _produce(into, recipe, step, outs, producer,
                          guidance=guidance, producer_env=producer_env)
        for key, value in usage.items():
            usage_total[key] = usage_total.get(key, 0) + value

    quarantine = "none"
    gates_result = []
    ok = True
    for step in recipe_module.gates(recipe):
        output = step["output"]
        path = core._safe(into, output)
        if os.path.isfile(path):
            os.remove(path)
        result = run_module.run_gate(step["run"], into, recipe)
        quarantine = result["quarantine"]
        gates_result.append({"output": output, "status": result["status"],
                              "quarantine": quarantine})
        if result["status"] != "ok":
            ok = False

    if not ok:
        raise ClaimError(f"rebuild did not earn its gates: {gates_result!r}")

    manifest = seal.seal(into)
    run_module.ledger(into, {
        "when": core._now(),
        "quarantine": quarantine,
        "environment": core._judging_host(),
        **usage_total,
    })
    return {"root": manifest["root"], "name": manifest["name"],
            "quarantine": quarantine, "gates": gates_result}


def _materialize(source: str, into: str, recipe: dict) -> None:
    """Furnish `into` with exactly what a producer is allowed to see.

    The pinned inputs, byte for byte; any already-pinned (non-generated)
    produce output; and the recipe itself -- raw, byte for byte, at format
    1-2, or (format 3+) the guidance-stripped, step-canonicalized preimage,
    re-serialized as real TOML under the canonical filename, so the room's
    own recipe is the one the root was computed from, not a reconstruction
    of it. Every *generated* byte is deliberately absent: the room is blind.
    """
    os.makedirs(into, exist_ok=True)

    fmt = identity._claim_format(recipe)
    if fmt >= 3:
        preimage = identity._preimage_recipe(recipe)
        _write_recipe_toml(os.path.join(into, core.RECIPE), preimage)
    else:
        src_path = recipe_module.recipe_path(source)
        core._copy_into(src_path, os.path.join(into, os.path.basename(src_path)))

    for path in recipe_module._inputs(recipe, source):
        core._copy_into(core._safe(source, path), core._safe(into, path))

    for step in recipe_module.produces(recipe):
        if step.get("class", "generated") == "generated":
            continue
        output = step["output"]
        src_file = core._safe(source, output)
        if os.path.isfile(src_file):
            core._copy_into(src_file, core._safe(into, output))


def _step_guidance(step: dict):
    """The producer hint on a produce step, under either spelling, or
    `None` if the step carries neither."""
    for key in core.GUIDANCE_KEYS:
        value = step.get(key)
        if value is not None:
            return value
    return None


def _produce(into: str, recipe: dict, step: dict, outs: list, producer: str,
             *, guidance: bool = True, producer_env: dict = None) -> dict:
    """Run `producer` once for one produce step: the caller's own
    environment and reachability, with the target named absolutely in
    `RETICULI_OUTPUT` and every generated output listed in
    `RETICULI_OUTPUTS`. Returns whatever production cost was measured
    (reported usd/tokens/calls, plus wall-clock measured here)."""
    output = step["output"]
    target = core._safe(into, output)
    os.makedirs(os.path.dirname(target) or into, exist_ok=True)

    env = dict(os.environ)
    env[core._ENV_OUTPUT] = target
    env[core._ENV_OUTPUTS] = json.dumps(outs)
    env[core._ENV_CLAIM] = recipe.get("claim", {}).get("name", "")
    env.pop(core._ENV_REQUEST, None)
    if guidance:
        hint = _step_guidance(step)
        if hint is not None:
            env[core._ENV_REQUEST] = hint

    fd, usage_path = tempfile.mkstemp(prefix=".reticuli-usage-", suffix=".json")
    os.close(fd)
    env[core._ENV_USAGE] = usage_path
    if producer_env:
        env.update(producer_env)

    try:
        start = time.monotonic()
        result = subprocess.run(
            [core._SHELL, "-c", producer], cwd=into, env=env,
            capture_output=True, text=True, timeout=core.PRODUCER_TIMEOUT,
        )
        elapsed = time.monotonic() - start
        if result.returncode != 0:
            raise ClaimError(
                f"producer failed for {output!r}: exit {result.returncode}: "
                f"{(result.stderr or result.stdout).strip()[-300:]}"
            )
        usage = _read_usage(usage_path)
        usage["seconds"] = elapsed
        return usage
    finally:
        try:
            os.unlink(usage_path)
        except OSError:
            pass


def _read_usage(path: str) -> dict:
    """A producer's self-reported cost, if it wrote one to `path`: any of
    usd/tokens/calls, each a non-negative number. `seconds` is never read
    from here -- it is always the kernel's own measurement."""
    if not path or not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, ValueError):
        return {}
    if not isinstance(data, dict):
        return {}
    usage = {}
    for key in ("usd", "tokens", "calls"):
        value = data.get(key)
        if isinstance(value, (int, float)) and not isinstance(value, bool) and value >= 0:
            usage[key] = value
    return usage


# -------------------------------------------------------- a minimal TOML writer --

def _toml_key(key: str) -> str:
    if key and all(c.isalnum() or c in "_-" for c in key):
        return key
    return _toml_string(key)


def _toml_string(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20:
            out.append("\\u%04x" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return _toml_string(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{" + ", ".join(f"{_toml_key(k)} = {_toml_value(v)}"
                               for k, v in value.items()) + "}"
    raise ClaimError(f"cannot serialize value to TOML: {value!r}")


def _write_recipe_toml(path: str, doc: dict) -> None:
    """Write a parsed recipe dict back out as real TOML -- tables as
    `[name]`, the step list as `[[step]]` array-of-tables, nested maps and
    lists as inline TOML -- so a reader (this kernel or anyone else's) can
    `tomllib.load` it back into the same tables it started from."""
    lines = []
    for key, value in doc.items():
        if key == "step":
            continue
        if isinstance(value, dict):
            lines.append(f"[{_toml_key(key)}]")
            for k, v in value.items():
                lines.append(f"{_toml_key(k)} = {_toml_value(v)}")
            lines.append("")
        else:
            lines.append(f"{_toml_key(key)} = {_toml_value(value)}")

    for step in doc.get("step", []):
        lines.append("[[step]]")
        for k, v in step.items():
            lines.append(f"{_toml_key(k)} = {_toml_value(v)}")
        lines.append("")

    text = "\n".join(lines).rstrip() + "\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


# ------------------------------------------------------- ssh signer checks --

def _authorized(allowed_signers: str, principal: str) -> bool:
    """Does `allowed_signers` (the ssh allowed_signers file format) name
    `principal` as an authorized signer?"""
    if not os.path.isfile(allowed_signers):
        return False
    with open(allowed_signers, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            who = line.split(None, 1)[0]
            if principal in who.split(","):
                return True
    return False


def _ssh_verify(data: bytes, signature_path: str, allowed_signers: str,
                 namespace: str, principal: str) -> bool:
    """Verify a detached ssh signature over `data` against
    `allowed_signers` in the given signature namespace
    (`ssh-keygen -Y verify`); refuses a principal the signers file does not
    authorize without ever invoking the binary."""
    if not _authorized(allowed_signers, principal) or not os.path.isfile(signature_path):
        return False
    result = subprocess.run(
        ["ssh-keygen", "-Y", "verify", "-f", allowed_signers,
         "-I", principal, "-n", namespace, "-s", signature_path],
        input=data, capture_output=True, timeout=30,
    )
    return result.returncode == 0
