"""The innermost layer: two boundaries and the refusal vocabulary.

The path boundary (`_safe`) refuses a recipe-declared name that escapes the
claim or crosses a symlink. The bytes boundary (`_hash_file`) is a plain
sha256 of a file's content, refusing anything that is not an ordinary,
singly-linked regular file. `_write_json` is an atomic write so a reader
never observes a half-written file. `ClaimError` is the one error a claim
caller sees: every refusal in this tool carries a reason, never a raw
traceback from untrusted input.

Everything else here is the protocol's shared vocabulary -- on-disk names,
environment variable names, and tuning constants -- that every layer above
`core` imports rather than restates. Stdlib only, never the network: this
module sits beneath the boundary where a claim's own bytes are untrusted.
"""
import datetime
import hashlib
import json
import os
import platform
import shutil
import stat
import sys
import tempfile

# Protocol constants: the on-disk / environment contract, shared verbatim
# with the record format and every layer above this one.
NAMESPACE = "reticuli"
DIGEST = "sha256"
FORMAT = 4
STORE = ".reticuli"
MANIFEST = ".reticuli/manifest.json"
RECIPE = "reticuli.toml"
LEGACY_RECIPE = "claim.toml"
LEDGER = ".reticuli/ledger.jsonl"
USAGE = ".reticuli/usage.json"
MUTATION_RESIDUE = ".reticuli/mutation_score.json"
SIGN_DIR = ".reticuli/mint"
SIGN_NAMESPACE = "reticuli.mint"

_JAILED = "RETICULI_JAILED"
_ENV_CACHE = "RETICULI_ENV_CACHE"
_ENV_CLAIM = "RETICULI_CLAIM"
_ENV_MODEL = "RETICULI_MODEL"
_ENV_OUTPUT = "RETICULI_OUTPUT"
_ENV_OUTPUTS = "RETICULI_OUTPUTS"
_ENV_REQUEST = "RETICULI_REQUEST"
_ENV_SIGNERS = "RETICULI_SIGNERS"
_ENV_TIMEOUT = "RETICULI_GATE_TIMEOUT"
_ENV_TOLERANCE = "RETICULI_TOLERANCE"
_ENV_USAGE = "RETICULI_USAGE"
_ENV_VENDOR = "RETICULI_VENDOR"
_KEEP_ENV = ("PATH", "HOME", "TMPDIR", "LANG", "LC_ALL", "TZ", "RETICULI_JAILED")

# Tuning constants: the name and kind are the seam, the value is policy.
GATE_TIMEOUT = 120.0
FURNISH_TIMEOUT = 600.0
PRODUCER_TIMEOUT = 900.0
TOLERANCE = 2.0
MUTANT_CEILING = 50
MUTANT_FLOOR = 5
MUTANT_HEADROOM = 1.25
COST_KEYS = ("usd", "tokens", "calls", "seconds")
COST_LADDER = ("usd", "tokens", "calls", "seconds")
COST_UNITS = ("usd", "tokens", "calls", "seconds")
GUIDANCE_KEYS = ("guidance", "request")
# The step-kind vocabulary: content, not just type -- exactly what the
# claim format defines (spec/claim-format.md).
KINDS = frozenset({"produce", "gate"})
_SHELL = "/bin/sh"


class ClaimError(Exception):
    """A refusal with a reason -- the only error this kernel raises."""


def _safe(root: str, name: str) -> str:
    """Resolve a recipe-declared name under `root`, or refuse.

    Refuses an absolute or empty name, a `.` or `..` component, and any
    component that is a symlink -- even one whose target stays inside the
    claim (spec/identity.md: an internal symlink can alias generated bytes
    as a pinned name).
    """
    if not isinstance(name, str) or not name:
        raise ClaimError(f"refuses an empty path: {name!r}")
    if os.path.isabs(name):
        raise ClaimError(f"refuses an absolute path: {name!r}")
    parts = name.split("/")
    if any(part in ("", ".", "..") for part in parts):
        raise ClaimError(f"path escapes the claim: {name!r}")
    resolved = os.path.realpath(root)
    for part in parts:
        resolved = os.path.join(resolved, part)
        if os.path.islink(resolved):
            raise ClaimError(f"path crosses a symlink: {name!r}")
    return resolved


def _hash_file(path: str) -> str:
    """The bytes boundary: a plain sha256 of a file's content.

    Refuses anything that is not a regular, singly-linked file -- a FIFO,
    device, socket, directory, symlink, or a hardlink to an outside inode
    is refused, not hashed (spec/identity.md).
    """
    st = os.lstat(path)
    if stat.S_ISLNK(st.st_mode):
        raise ClaimError(f"refuses a symlink: {path!r}")
    if not stat.S_ISREG(st.st_mode):
        raise ClaimError(f"refuses a non-regular file: {path!r}")
    if st.st_nlink != 1:
        raise ClaimError(f"refuses a hard-linked file: {path!r}")
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def _write_json(path: str, obj) -> None:
    """Write JSON atomically: a reader never observes a half-written file."""
    d = os.path.dirname(path) or "."
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".tmp-", suffix=".json")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(obj, f, sort_keys=True)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _now() -> str:
    """UTC time of recording, `YYYY-MM-DDTHH:MM:SSZ` (spec/record.md)."""
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _copy_into(src: str, dst: str) -> str:
    """Copy a file or directory tree's bytes from `src` to `dst`."""
    parent = os.path.dirname(dst) or "."
    os.makedirs(parent, exist_ok=True)
    if os.path.isdir(src):
        shutil.copytree(src, dst, dirs_exist_ok=True)
    else:
        shutil.copy2(src, dst)
    return dst


def _judging_host() -> dict:
    """`platform`, `machine`, `runtime` describing the host (spec/record.md)."""
    return {
        "platform": sys.platform,
        "machine": platform.machine(),
        "runtime": f"{platform.python_implementation()} {platform.python_version()}",
    }
