"""The three-machine test, mutation testing, and the gate-decider heuristic.

`crosscheck` is the three-machine test (spec/verification.md): given three
legs -- each either a claim directory (a live execution) or a signed record
(spec/record.md), one predicate either transport -- it decides `accept` /
`reject` / `incomplete` from one root across all three, byte reuse, every
gate earned, the cost band, and whatever the claim itself declares
(envelope ceilings, a mutation floor). `record_proof` runs the same test and,
on a pass, seals the proof onto M1's manifest as residue; `sign_node` is the
pure fold a signature chain binds a layer's root and build digest to its
components' signatures by.

`mutation_score` measures the equivalence class's width: deterministic
mutants of a claim's generated Python, drawn in an order seeded by the
claim's own root, re-audited one at a time with every touched file restored
before the next -- residue only, never the root. `vacuous_gates` and
`gate_deciders` name which gates decide by generated bytes alone: a shell
command's leading interpreter and flags are skipped, and what remains is the
script or module it runs.
"""
import ast
import hashlib
import io
import json
import os
import re
import shlex
import tokenize

from . import attest as attest_module
from . import build as build_module
from . import core
from . import identity
from . import recipe as recipe_module
from . import run as run_module
from . import seal as seal_module
from .core import ClaimError

# -------------------------------------------------------------- records --

def record_read(path: str) -> dict:
    """Read a record off disk: refuses malformed bytes, and refuses any
    file whose bytes are not exactly its own canonical serialization -- a
    reformatted record is not a record (spec/record.md: the reader is
    pinned to canonical bytes, not merely to the JSON they happen to
    parse as)."""
    try:
        with open(path, "rb") as f:
            raw = f.read()
    except OSError as exc:
        raise ClaimError(f"malformed record {path!r}: {exc}") from exc
    try:
        doc = json.loads(raw)
    except ValueError as exc:
        raise ClaimError(f"malformed record {path!r}: {exc}") from exc
    attest_module.record_validate(doc)
    if raw != attest_module.record_canonical(doc):
        raise ClaimError(f"record {path!r} is not its own canonical bytes")
    return doc


# ---------------------------------------------------------- gate deciders --

_INTERPRETERS = frozenset({'Rscript', 'awk', 'lua', 'python', 'python3', 'python2', 'node', 'ruby', 'perl', 'dash', 'deno', 'py.test', 'zsh', 'tclsh', 'php', 'sh', 'bash', 'py', 'pytest'})
_OPERATORS = frozenset({'&', '\n', '|', '||', '&&', ';'})
_SKIP_VALUE = frozenset({'-m', '-p', '--module', '-X', '-c', '-e'})

_SEGMENT_SPLIT = re.compile(
    "|".join(re.escape(op) for op in sorted(_OPERATORS, key=len, reverse=True))
)
_SCRIPT_EXT = (".py", ".sh", ".pl", ".rb", ".js", ".lua", ".php", ".r")


def _split_segments(run: str) -> list:
    """The command string cut at its own operators -- `&&`/`||` before the
    single-character forms, so a compound gate is judged one sub-command at
    a time."""
    return [seg for seg in _SEGMENT_SPLIT.split(run) if seg.strip()]


def gate_deciders(run: str) -> list:
    """Which workspace files a gate's own command decides by: the script or
    module named after a recognized interpreter's flags are skipped, or a
    bare command that is itself a path (`./x`, a path with a `/`, or a
    recognized script extension). A bare utility name (`printf`, `grep`)
    decides by no file of its own -- the recipe's own words decide instead
    (spec/verification.md: the heuristic beyond the pinned vectors is
    implementation-defined)."""
    deciders = []
    for segment in _split_segments(run):
        try:
            tokens = shlex.split(segment)
        except ValueError:
            continue
        if not tokens:
            continue
        head = tokens[0]
        headname = os.path.basename(head)
        if headname in _INTERPRETERS:
            i = 1
            while i < len(tokens):
                tok = tokens[i]
                if tok.startswith("-"):
                    i += 2 if tok in _SKIP_VALUE else 1
                    continue
                deciders.append(os.path.basename(tok))
                i += 1
        elif (head.startswith("./") or head.startswith("../") or "/" in head
              or head.lower().endswith(_SCRIPT_EXT)):
            deciders.append(os.path.basename(head))
    seen = set()
    ordered = []
    for dec in deciders:
        if dec not in seen:
            seen.add(dec)
            ordered.append(dec)
    return ordered


def vacuous_gates(recipe: dict) -> list:
    """Gates whose every decider is a generated output -- the verdict
    depends on no claimed byte, so the root fits any implementation that
    prints the pinned verdict. A gate that executes no workspace script
    (an empty decider list) decides by the recipe's own words instead, and
    is not vacuous."""
    claim = recipe.get("claim", {}) or {}
    generated = set(recipe_module.generated_outputs(recipe))
    generated_names = generated | {os.path.basename(g) for g in generated}
    vacuous = []
    for step in recipe_module.gates(recipe):
        deciders = gate_deciders(step.get("run", ""))
        if deciders and all(dec in generated_names for dec in deciders):
            vacuous.append(step["output"])
    return vacuous


# --------------------------------------------------------- mutation engine --

_COMPARISON = ('>', '<', '>=', '<=', '==', '!=')
_ARITHMETIC = ('+', '-', '*', '/', '//', '%', '**')
_OP_KIND = {op: "comparison" for op in _COMPARISON}
_OP_KIND.update({op: "arithmetic" for op in _ARITHMETIC})
_OP_ALTS = {
    '>': '<=', '<': '>=', '>=': '<', '<=': '>', '==': '!=', '!=': '==',
    '+': '-', '-': '+', '*': '/', '/': '*', '//': '*', '%': '*', '**': '*',
}
_WORD_ALTS = {"True": "False", "False": "True", "and": "or", "or": "and"}
_STRING_LITERAL = re.compile(r"""('([^'\\]|\\.)*'|"([^"\\]|\\.)*")""")


def _line_offsets(source: str) -> list:
    offsets = [0]
    for line in source.splitlines(keepends=True):
        offsets.append(offsets[-1] + len(line))
    return offsets


def _node_span(node, source: str) -> tuple:
    """The `(start, end)` character offsets of an AST node's own text."""
    offsets = _line_offsets(source)
    start = offsets[node.lineno - 1] + node.col_offset
    end = offsets[node.end_lineno - 1] + node.end_col_offset
    return (start, end)


def _span_text(source: str, span: tuple) -> str:
    return source[span[0]:span[1]]


def _edit(source: str, span: tuple, replacement: str) -> str:
    """One text substitution over `span`."""
    return source[:span[0]] + replacement + source[span[1]:]


def _splice(source: str, edits: list) -> str:
    """Several non-overlapping `(span, replacement)` edits applied at once."""
    for span, replacement in sorted(edits, key=lambda e: e[0][0], reverse=True):
        source = _edit(source, span, replacement)
    return source


def _docstring_spans(source: str) -> list:
    """Spans of module/class/function docstrings -- mutating inside one
    changes no behavior, so token mutants skip them."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    spans = []
    candidates = [tree] + [n for n in ast.walk(tree)
                           if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))]
    for node in candidates:
        body = getattr(node, "body", [])
        if (body and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, ast.Constant)
                and isinstance(body[0].value.value, str)):
            spans.append(_node_span(body[0], source))
    return spans


def _named(node) -> bool:
    """Is this AST node a bare name that a word-level mutant can flip
    (`True`/`False`/`and`/`or`)?"""
    return isinstance(node, ast.Name) and node.id in _WORD_ALTS


def _token_mutants(source: str) -> list:
    """One mutant per occurrence of a replaceable operator or boolean
    keyword, outside any docstring."""
    skip = _docstring_spans(source)

    def _in_skip(pos: int) -> bool:
        return any(a <= pos < b for a, b in skip)

    try:
        tokens = list(tokenize.generate_tokens(io.StringIO(source).readline))
    except (tokenize.TokenizeError, IndentationError, SyntaxError, ValueError):
        return []

    offsets = _line_offsets(source)

    def to_offset(row, col):
        return offsets[row - 1] + col

    out = []
    for tok in tokens:
        text = tok.string
        alt = None
        if tok.type == tokenize.OP and text in _OP_ALTS:
            alt = _OP_ALTS[text]
        elif tok.type == tokenize.NAME and text in _WORD_ALTS:
            alt = _WORD_ALTS[text]
        if alt is None:
            continue
        start = to_offset(*tok.start)
        end = to_offset(*tok.end)
        if _in_skip(start):
            continue
        mutated = _edit(source, (start, end), alt)
        out.append((f"token@{start}:{text}->{alt}", mutated))
    return out


def _structural_mutants(source: str) -> list:
    """One mutant per `if` test (negated) and per non-empty `return` (its
    value replaced by a constant) -- both syntactically valid by
    construction, whatever the original expression was."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    out = []
    for node in ast.walk(tree):
        if isinstance(node, ast.If):
            span = _node_span(node.test, source)
            text = _span_text(source, span)
            mutated = _edit(source, span, f"not ({text})")
            out.append((f"negate-if@{span[0]}", mutated))
        elif isinstance(node, ast.Return) and node.value is not None:
            span = _node_span(node.value, source)
            mutated = _edit(source, span, "0")
            out.append((f"nullify-return@{span[0]}", mutated))
    return out


def _mutants(source: str) -> list:
    """Every mutant this engine can draw from one source file: structural
    edits first, then token-level operator/keyword swaps."""
    return _structural_mutants(source) + _token_mutants(source)


def _draw_order(seed: str, items: list) -> list:
    """A deterministic permutation of `items`, keyed off `seed` -- the same
    seed and the same items always draw the same order, with no dependence
    on wall-clock or process state."""
    keyed = [
        (hashlib.sha256(f"{seed}|{i}|{item!r}".encode("utf-8")).hexdigest(), i)
        for i, item in enumerate(items)
    ]
    keyed.sort()
    return [items[i] for _, i in keyed]


def _mutant_order(seed: str, mutants: list) -> list:
    return _draw_order(seed, mutants)


def _label(mutant) -> str:
    return mutant[0]


def _machine(d: str, recipe: dict) -> bool:
    """Run every gate step fresh against whatever is on disk right now;
    `True` the moment one fails to earn `ok` -- the mutant is killed."""
    for step in recipe_module.gates(recipe):
        path = os.path.join(d, step["output"])
        if os.path.isfile(path):
            try:
                os.remove(path)
            except OSError:
                pass
        result = run_module.run_gate(step["run"], d, recipe)
        if result["status"] != "ok":
            return True
    return False


def mutation_score(d: str, max_mutants: int = core.MUTANT_CEILING, floor: float = None) -> dict:
    """Deterministic mutants of `d`'s generated Python, drawn in an order
    seeded by the claim's own root, each tried and every touched file
    restored before the next -- residue (`core.MUTATION_RESIDUE`) only,
    never the root. `ok` (rate >= floor) is included only when `floor` is
    given."""
    recipe = recipe_module.load_recipe(d)
    targets = [out for out in recipe_module.generated_outputs(recipe)
               if out.endswith(".py") and os.path.isfile(os.path.join(d, out))]

    sources = {}
    pool = []
    for out in targets:
        path = os.path.join(d, out)
        with open(path, "r", encoding="utf-8") as f:
            sources[out] = f.read()
        for label, mutated in _mutants(sources[out]):
            pool.append((out, label, mutated))

    seed = identity.root(recipe, d)
    ordered = _mutant_order(seed, pool)
    chosen = ordered[:max(max_mutants, 0)]

    gate_backups = {}
    for step in recipe_module.gates(recipe):
        p = os.path.join(d, step["output"])
        if os.path.isfile(p):
            with open(p, "rb") as f:
                gate_backups[step["output"]] = f.read()

    killed = 0
    survivors = []
    for out, label, mutated in chosen:
        path = os.path.join(d, out)
        with open(path, "w", encoding="utf-8") as f:
            f.write(mutated)
        try:
            died = _machine(d, recipe)
        finally:
            with open(path, "w", encoding="utf-8") as f:
                f.write(sources[out])
            for gout, data in gate_backups.items():
                with open(os.path.join(d, gout), "wb") as f:
                    f.write(data)
        if died:
            killed += 1
        else:
            survivors.append(label)

    total = len(chosen)
    rate = (killed / total) if total else 1.0
    result = {"mutants": total, "killed": killed, "rate": rate, "survivors": survivors}
    if floor is not None:
        result["ok"] = rate >= floor
    core._write_json(os.path.join(d, core.MUTATION_RESIDUE), result)
    return result


# -------------------------------------------------------------- crosscheck --

_UNKNOWN = object()


def _declared(m1_path: str):
    """The obligations M1's claim declares -- `{}` states none, `_UNKNOWN`
    means an M1 record cannot say (a version-1 record never carried
    `claim`), so a check that would otherwise apply is incomplete rather
    than silently skipped."""
    if os.path.isdir(m1_path):
        claim = recipe_module.load_recipe(m1_path).get("claim", {}) or {}
        return {k: claim[k] for k in ("tolerance", "envelope", "mutation_floor") if k in claim}
    doc = record_read(m1_path)
    if doc.get("record", 1) >= 2:
        return doc.get("claim") or {}
    return _UNKNOWN


def _dir_producer(path: str) -> dict:
    for event in reversed(run_module.ledger_events(path)):
        if event.get("event") == "producer":
            return {"vendor": event.get("vendor"), "model": event.get("model"),
                     "blind": event.get("blind")}
    return {}


def independence(path: str) -> dict:
    """Which vendor/model declared the bytes at `path`, and whether its
    workspace was blind -- relayed from the claim's own ledger (a
    directory) or its `producer` block (a record), never enforced."""
    if os.path.isdir(path):
        return _dir_producer(path) or {"vendor": None, "model": None, "blind": None}
    doc = record_read(path)
    producer = doc.get("producer") or {}
    return {"vendor": producer.get("vendor"), "model": producer.get("model"),
             "blind": producer.get("blind")}


def _independence_string(m1_ind: dict, m3_ind: dict) -> str:
    if not m3_ind.get("vendor"):
        return "unestablished: no producer declared for the rebuild"
    if m3_ind.get("vendor") == m1_ind.get("vendor") and m3_ind.get("model") == m1_ind.get("model"):
        return "unestablished: same vendor and model as the original producer"
    blind_word = "blind workspace" if m3_ind.get("blind") else "workspace not blind"
    return f"declared: {m3_ind['vendor']}/{m3_ind['model']}, {blind_word}, not proven"


def _leg_facts(path: str) -> dict:
    """Normalize one crosscheck leg -- a claim directory or a frozen
    record -- to the facts the comparison needs, so the rest of
    `crosscheck` is transport-agnostic."""
    if os.path.isdir(path):
        recipe = recipe_module.load_recipe(path)
        # Root/build-digest recompute is not guaranteed to refuse a missing
        # pinned byte in band (a gate that fails to recreate a pinned
        # output can surface a raw FileNotFoundError from identity.root's
        # own file hashing) -- a leg this broken is simply never equal to
        # another leg's real root, and never earns its gates.
        try:
            root = identity.root(recipe, path)
        except Exception:
            root = f"<unreadable:{os.path.realpath(path)}>"
        try:
            bd = identity.build_digest(path)
        except Exception:
            bd = None
        try:
            audited = build_module.audit(path)["ok"]
        except Exception:
            audited = False
        return {
            "kind": "dir", "root": root, "audited": audited,
            "build_digest": bd,
            "cost": run_module.cost(path),
            "producer": _dir_producer(path),
        }
    doc = record_read(path)
    audited = bool(doc["gates"]) and all(g["status"] == "ok" for g in doc["gates"])
    return {
        "kind": "record", "root": doc["root"], "audited": audited,
        "build_digest": doc["build_digest"], "cost": doc.get("cost"),
        "producer": doc.get("producer") or {},
    }


def _tolerance_for(declared) -> float:
    override = os.environ.get(core._ENV_TOLERANCE)
    if override:
        try:
            return float(override)
        except ValueError:
            pass
    if declared is not _UNKNOWN and declared.get("tolerance") is not None:
        return float(declared["tolerance"])
    return core.TOLERANCE


def _cost_comparable(c1, c3, tolerance: float):
    """Whether C3/C1 lands in `[1/tolerance, tolerance]`, in the strongest
    unit both ledgers measured (usd > tokens > calls > seconds); `None`
    when nothing is shared (unmeasured, reported rather than failed)."""
    if not c1 or not c3:
        return None
    for unit in core.COST_LADDER:
        if unit in c1 and unit in c3:
            v1, v3 = c1[unit], c3[unit]
            if v1 == 0:
                ratio = 1.0 if v3 == 0 else float("inf")
            else:
                ratio = v3 / v1
            return (1.0 / tolerance) <= ratio <= tolerance
    return None


def crosscheck(m1, m2, m3, *, mutants: int = None) -> dict:
    """The three-machine test (spec/verification.md): one root across all
    three legs, byte reuse between M1 and M2, every gate earned, the cost
    band, and every condition the claim itself declares. The verdict is
    `accept` / `reject` / `incomplete`; `satisfied` is `verdict ==
    "accept"`."""
    paths = {"M1": m1, "M2": m2, "M3": m3}
    reals = {k: os.path.realpath(v) for k, v in paths.items()}
    if len(set(reals.values())) < len(reals):
        raise ClaimError("crosscheck requires three distinct machines; refuses identical paths")

    facts = {k: _leg_facts(v) for k, v in paths.items()}
    roots = {k: facts[k]["root"] for k in paths}
    equivalence = len(set(roots.values())) == 1
    audited = {k: facts[k]["audited"] for k in paths}

    reuse = None
    if equivalence:
        reuse = facts["M1"]["build_digest"] == facts["M2"]["build_digest"]

    declared = _declared(m1)

    rejected = []
    incomplete = []

    if not equivalence:
        rejected.append("equivalence")
    if reuse is False:
        rejected.append("reuse")
    for k in ("M1", "M2", "M3"):
        if not audited[k]:
            rejected.append(f"{k} earned")

    tolerance = _tolerance_for(declared)
    comparable = _cost_comparable(facts["M1"]["cost"], facts["M3"]["cost"], tolerance)
    tolerance_declared = declared is not _UNKNOWN and declared.get("tolerance") is not None
    if tolerance_declared:
        if comparable is None:
            incomplete.append("cost band")
        elif comparable is False:
            rejected.append("cost band")

    envelope_report = {}
    envelope_decl = {} if declared is _UNKNOWN else (declared.get("envelope") or {})
    c3 = facts["M3"]["cost"] or {}
    for unit, ceiling in envelope_decl.items():
        measured = c3.get(unit)
        within = None if measured is None else measured <= ceiling
        envelope_report[unit] = {"ceiling": ceiling, "measured": measured, "within": within}
        if within is None:
            incomplete.append(f"envelope {unit}")
        elif within is False:
            rejected.append(f"envelope {unit}")

    if declared is _UNKNOWN:
        incomplete.append("declared conditions unknown (pre-v2 record)")

    floor = None if declared is _UNKNOWN else declared.get("mutation_floor")
    mscore = None
    if floor is not None:
        if mutants is not None and facts["M3"]["kind"] == "dir":
            mscore = mutation_score(m3, max_mutants=mutants, floor=floor)
            if not mscore["ok"]:
                rejected.append("mutation floor")
        else:
            incomplete.append("mutation floor")

    if rejected:
        verdict = "reject"
    elif incomplete:
        verdict = "incomplete"
    else:
        verdict = "accept"

    ind = _independence_string(facts["M1"].get("producer") or {}, facts["M3"].get("producer") or {})

    return {
        "roots": roots, "satisfied": verdict == "accept", "verdict": verdict,
        "rejected": rejected, "incomplete": incomplete,
        "equivalence": equivalence, "reuse": reuse, "audited": audited,
        "cost": {"comparable": comparable, "envelope": envelope_report},
        "mutation_score": mscore, "independence": ind,
    }


def sign_node(root: str, digest: str, links: list) -> str:
    """One signature-chain node: a layer's root and build digest folded
    with the SET of its components' signatures below -- deterministic,
    and indifferent to the order `links` is given in."""
    payload = {"root": root, "build_digest": digest, "links": sorted(links)}
    return hashlib.sha256(json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest()


def record_proof(m1, m2, m3) -> dict:
    """Run the crosscheck; on a pass, seal the proof onto M1's manifest as
    residue. M1 must be a directory (a proof is residue on a manifest, and
    only a directory has one); a frozen leg among M2/M3 must verify against
    the `RETICULI_SIGNERS` anchor, and its digest and signer identity are
    embedded in the proof."""
    if not os.path.isdir(m1):
        raise ClaimError("a proof can only be recorded on a directory M1")

    result = crosscheck(m1, m2, m3)
    if not result["satisfied"]:
        return {"proof_recorded": False, "crosscheck": result}

    proof = {"kind": "crosscheck", "m2": result["roots"]["M2"], "m3": result["roots"]["M3"]}
    records = []
    for label, path in (("M2", m2), ("M3", m3)):
        if os.path.isdir(path):
            continue
        anchor = os.environ.get(core._ENV_SIGNERS)
        if not anchor:
            raise ClaimError(f"a proof from an unanchored record ({label}) must refuse")
        signer = attest_module.record_signer(path, anchor)
        if not signer:
            raise ClaimError(f"record leg {label} does not verify against the signer anchor")
        doc = record_read(path)
        records.append({"signer": signer, "digest": attest_module.record_digest(doc)})
    if records:
        proof["records"] = records

    manifest = seal_module.read_manifest(m1)
    manifest["proof"] = proof
    core._write_json(os.path.join(m1, core.MANIFEST), manifest)
    return {"proof_recorded": True, "crosscheck": result}
