"""The kernel's attest layer: the record format — the one interchange file third parties may parse."""
import hashlib
import json
import os
import re

from .build import (
    _ssh_verify,
)
from .core import (  # noqa: F401
    COST_UNITS,
    FORMAT,
    NAMESPACE,
    SIGN_NAMESPACE,
    ClaimError,
)
from .identity import (  # noqa: F401
    build_digest,
    root,
)
from .recipe import (  # noqa: F401
    gates,
)
from .run import (  # noqa: F401
    cost,
    ledger,
    sandbox,
)

# ------------------------------------------------------------------ records
#
# A RECORD is one machine's results, frozen: the identity it recomputed, the
# generated bytes it found, the gate verdicts it earned by running them, and
# the production cost where one was measured.  It is the one file format
# other programs may parse -- the manifest and the ledger stay private -- and
# it is `crosscheck`'s second transport: a leg whose machine is gone.  The
# kernel owns the FORMAT (reading, validation, the signature namespace);
# authoring a record (emitting it, signing it) is the exchange layer's.  The
# specification is spec/record.md.

#: The record's signature namespace.  Distinct from NAMESPACE (attestation)
#: and SIGN_NAMESPACE (authorization) so a statement of results can never be
#: presented as either of the other two acts.
RECORD_NAMESPACE = "reticuli.record"

#: The record-format version this kernel reads and understands.
RECORD_FORMAT = 1

_RECORD_HEX = re.compile(r"^[0-9a-f]{64}$")
_RECORD_WHEN = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")
_RECORD_MEMBERS = frozenset({"record", "name", "root", "build_digest", "gates",
                             "cost", "producer", "environment", "when", "tool"})
_RECORD_REQUIRED = frozenset({"record", "name", "root", "build_digest",
                              "gates", "environment", "when"})
_RECORD_GATE = frozenset({"output", "status", "sandbox"})
_RECORD_STATUSES = frozenset({"ok", "failed", "timeout", "mismatch",
                              "environment"})
_RECORD_SANDBOXES = frozenset({"none", "seatbelt", "bubblewrap", "inherited"})
_RECORD_PRODUCER = frozenset({"vendor", "model", "blind", "cutoff"})
_RECORD_ENVIRONMENT = frozenset({"platform", "machine", "runtime"})


def record_canonical(doc) -> bytes:
    """A record's canonical bytes: the identity serialization, verbatim.

    Sorted keys, default separators, non-ASCII escaped -- the same rules the
    root preimage uses (spec/identity.md), so an implementation of one has
    implemented the other.
    """
    return json.dumps(doc, sort_keys=True).encode("utf-8")


def record_digest(doc) -> str:
    """How a record is cited: sha256 hex of its canonical bytes."""
    return hashlib.sha256(record_canonical(doc)).hexdigest()


def record_validate(doc) -> None:
    """Refuse, with a reason, anything that is not a version-1 record.

    The member set is closed on purpose: extension is a version bump, never a
    quiet extra field under an old version number.  Hostile bytes surface as
    a refusal here, not as a KeyError three layers down.
    """
    def refuse(reason: str):
        raise ClaimError(f"not a record: {reason}")

    if not isinstance(doc, dict):
        refuse("a record is a JSON object")
    unknown = set(doc) - _RECORD_MEMBERS
    if unknown:
        refuse(f"unknown member(s) {sorted(unknown)} -- the member set is "
               "closed, and extension is a version bump")
    missing = _RECORD_REQUIRED - set(doc)
    if missing:
        refuse(f"missing member(s) {sorted(missing)}")

    version = doc["record"]
    if isinstance(version, bool) or not isinstance(version, int) or version < 1:
        refuse(f"version must be a positive integer, got {version!r}")
    if version > RECORD_FORMAT:
        refuse(f"version {version} is newer than this reader understands "
               f"(version {RECORD_FORMAT}); upgrade reticuli to read it")

    if not isinstance(doc["name"], str) or not doc["name"].strip():
        refuse("name must be a non-empty string")
    for member in ("root", "build_digest"):
        value = doc[member]
        if not isinstance(value, str) or not _RECORD_HEX.match(value):
            refuse(f"{member} must be 64 lowercase hex characters")

    if not isinstance(doc["gates"], list):
        refuse("gates must be a list")
    for entry in doc["gates"]:
        if not isinstance(entry, dict):
            refuse("each gate entry is an object")
        extra = set(entry) - _RECORD_GATE
        if extra:
            refuse(f"unknown gate member(s) {sorted(extra)} -- per-gate "
                   "wall-clock is deliberately outside the document")
        if _RECORD_GATE - set(entry):
            refuse(f"a gate entry needs {sorted(_RECORD_GATE)}")
        if not isinstance(entry["output"], str) or not entry["output"]:
            refuse("a gate's output must be a non-empty string")
        if entry["status"] not in _RECORD_STATUSES:
            refuse(f"unknown gate status {entry['status']!r} "
                   f"(the vocabulary is {sorted(_RECORD_STATUSES)})")
        if entry["sandbox"] not in _RECORD_SANDBOXES:
            refuse(f"unknown sandbox {entry['sandbox']!r} "
                   f"(the vocabulary is {sorted(_RECORD_SANDBOXES)})")

    if "cost" in doc:
        totals = doc["cost"]
        if not isinstance(totals, dict) or not totals:
            refuse("an unmeasured cost is omitted, never empty")
        unknown = set(totals) - set(COST_UNITS)
        if unknown:
            refuse(f"unknown cost unit(s) {sorted(unknown)} "
                   f"(the units are {sorted(COST_UNITS)})")
        for unit, value in totals.items():
            if isinstance(value, bool) or not isinstance(value, (int, float)) \
                    or value < 0:
                refuse(f"cost {unit} must be a non-negative number, "
                       f"got {value!r}")

    if "producer" in doc:
        told = doc["producer"]
        if not isinstance(told, dict) or not told:
            refuse("an absent producer declaration is omitted, never empty")
        unknown = set(told) - _RECORD_PRODUCER
        if unknown:
            refuse(f"unknown producer member(s) {sorted(unknown)}")
        for key in ("vendor", "model", "cutoff"):
            if key in told and (not isinstance(told[key], str) or not told[key]):
                refuse(f"producer {key} must be a non-empty string")
        if "blind" in told and not isinstance(told["blind"], bool):
            refuse("producer blind must be a boolean")

    environment = doc["environment"]
    if not isinstance(environment, dict) \
            or set(environment) != _RECORD_ENVIRONMENT:
        refuse(f"environment holds exactly {sorted(_RECORD_ENVIRONMENT)}")
    for key, value in environment.items():
        if not isinstance(value, str) or not value:
            refuse(f"environment {key} must be a non-empty string")

    if not isinstance(doc["when"], str) or not _RECORD_WHEN.match(doc["when"]):
        refuse("when must be a UTC time, YYYY-MM-DDTHH:MM:SSZ")
    if "tool" in doc and (not isinstance(doc["tool"], str) or not doc["tool"]):
        refuse("tool, when present, is a non-empty string")


def record_read(path: str) -> dict:
    """Parse and validate a record file.  Damaged bytes refuse in band.

    The file must hold EXACTLY its canonical bytes: the digest is defined
    over the canonical form and a signature covers the file's bytes, so a
    pretty-printed copy would make the two authorities disagree about what
    one record is.  One representation, one digest, one signed thing.
    """
    try:
        with open(path, "rb") as f:
            raw = f.read()
        doc = json.loads(raw.decode("utf-8"))
    except (OSError, UnicodeDecodeError, ValueError) as exc:
        raise ClaimError(f"unreadable record {path}: {exc}") from None
    record_validate(doc)
    if raw != record_canonical(doc):
        raise ClaimError(f"not a record: {path} does not hold its canonical "
                         "bytes -- reformatting a record breaks the bond "
                         "between its digest and its signature")
    return doc


def record_signer(path: str, anchor):
    """Who, per this anchor, signed the record -- or None.

    Trust is verifier-relative: the answer depends on the allowed_signers
    file the caller names, and a record signed by a key the anchor does not
    hold is a document, not evidence.  The namespace must be the record's
    own, so an attestation or a mint signature over the same bytes answers
    None.
    """
    signature = path + ".sig"
    if not isinstance(anchor, str) or not os.path.isfile(anchor) \
            or not os.path.isfile(signature):
        return None
    try:
        with open(anchor, encoding="utf-8") as f:
            lines = f.read().splitlines()
    except (OSError, UnicodeDecodeError):
        return None
    principals = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        for name in line.split()[0].split(","):
            if name and name not in principals:
                principals.append(name)
    for principal in principals:
        if _ssh_verify(anchor, principal, RECORD_NAMESPACE, signature, path):
            return principal
    return None
