"""The kernel's build layer: materialize a blind room, produce into it, re-earn every verdict, and the signed phase."""
import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile

from .core import (
    _ENV_CLAIM,
    _ENV_MODEL,
    _ENV_OUTPUT,
    _ENV_OUTPUTS,
    _ENV_REQUEST,
    _ENV_SIGNERS,
    _ENV_USAGE,
    _ENV_VENDOR,
    _SHELL,
    COST_KEYS,
    MANIFEST,
    PRODUCER_TIMEOUT,
    SIGN_DIR,
    SIGN_NAMESPACE,
    STORE,
    USAGE,
    ClaimError,
    _copy_into,
    _hash_file,
    _judging_host,
    _now,
    _safe,
)
from .identity import (
    build_digest,
    root,
)
from .recipe import (
    _inputs,
    gates,
    generated_outputs,
    load_recipe,
    produces,
    recipe_path,
)
from .run import (  # noqa: F401
    _ledger_path,
    _run,
    _scrub_env,
    cost,
    furnish,
    gate_timeout,
    ledger,
    preflight,
    run_gate,
    sandbox_backend,
)
from .seal import (  # noqa: F401
    read_manifest,
    seal,
    verify,
)

# ------------------------------------------------------------ the workspace

def _materialize(claimdir: str, recipe, dest: str, produce_from=None,
                 input_from=None, include_generated=True) -> list:
    """Lay the claim out in a fresh workspace, every path crossing `_safe`.

    Gate outputs are never copied: a gate must re-earn its own output from the
    bytes present, and a stale copy would let a failed gate look answered.
    """
    produce_from = produce_from or {}
    input_from = input_from or {}
    os.makedirs(dest, exist_ok=True)
    # Materialise the recipe under the name it actually has: a claim sealed as
    # claim.toml must arrive in the workspace as claim.toml, or a gate that
    # names it would not find it.
    found = recipe_path(claimdir)
    _copy_into(found, os.path.join(dest, os.path.basename(found)))

    for name in _inputs(recipe, claimdir):
        threaded = input_from.get(name)
        source = os.path.abspath(threaded) if threaded else _safe(claimdir, name)
        if not os.path.isfile(source):
            raise ClaimError(f"declared input is missing: {name}")
        _copy_into(source, _safe(dest, name))

    reused = []
    for step in produces(recipe):
        name = step.get("output")
        if not isinstance(name, str) or not name:
            continue
        supplied = produce_from.get(name)
        if supplied is not None:
            _copy_into(os.path.abspath(supplied), _safe(dest, name))
            reused.append(name)
            continue
        if step.get("class") == "generated" and not include_generated:
            continue                       # the producer will write it
        source = _safe(claimdir, name)      # refuses an output symlinked out
        if os.path.exists(source):
            _copy_into(source, _safe(dest, name))
    return reused


# ---------------------------------------------------------------- the audit

def audit(claimdir: str, produce_from=None, timeout=None, strict=False,
          progress=None) -> dict:
    """THE DEEP CHECK: re-earn every verdict on the bytes actually present.

    Claim-deep, not gate-shallow.  The root must still recompute (a spec
    substituted after sealing is caught even when the gate stays green), and
    every gate is re-run in a fresh workspace: a gate that fails is `failed`, a
    gate that passes but does not reproduce the pinned bytes is a `mismatch` (a
    carried verdict), a host that lacks a declared requirement is
    `environment` -- untested, not disproven.

    `produce_from` substitutes generated bytes, so gates COMPOSE: a dependent's
    shipped code is judged by the component's own claim rather than by the
    component's sealed copy of itself.

    `timeout` tightens the wall-clock ceiling for this audit only, never
    loosening what the claim or the environment already allow.  It exists for
    mutation testing: a mutated loop condition does not terminate, and a run of
    twenty such mutants against the standing ten-minute ceiling is three hours
    of waiting for an answer that was available in a second.

    `progress`, when given, is called as progress(i, total, name) before each
    gate runs — presentation plumbing for a caller that wants to narrate a
    long audit. It is never consulted for anything; a callback that raises is
    the caller's own bug and deliberately not swallowed.
    """
    _judging_host()
    recipe = load_recipe(claimdir)
    manifest = read_manifest(claimdir)
    declared_gates = gates(recipe)

    missing = preflight(recipe)
    if missing:
        return {
            "ok": False,
            "claim_ok": None,
            "root": manifest.get("root"),
            "environment": missing,
            "gates": [{"output": g.get("output"), "status": "environment",
                       "quarantine": None, "returncode": None, "seconds": None,
                       "detail": f"host lacks {', '.join(missing)}"}
                      for g in declared_gates],
        }

    recomputed = root(recipe, claimdir)
    claim_ok = recomputed == manifest.get("root")

    scratch = tempfile.mkdtemp(prefix="reticuli-audit-")
    try:
        work = os.path.join(scratch, "work")
        _materialize(claimdir, recipe, work, produce_from=produce_from)
        # Furnish the room before judging in it. A room that cannot be
        # furnished is an ENVIRONMENT failure -- the gates were not run, so
        # nothing was proven and nothing was disproven.
        try:
            venv_bin = furnish(recipe, work)
        except ClaimError as exc:
            return {
                "ok": False,
                "claim_ok": claim_ok,
                "root": manifest.get("root"),
                "recomputed": recomputed,
                "environment": [str(exc)],
                "gates": [{"output": g.get("output"), "status": "environment",
                           "quarantine": None, "returncode": None,
                           "seconds": None, "detail": str(exc)[-400:]}
                          for g in declared_gates],
            }
        results = []
        for index, step in enumerate(declared_gates, 1):
            name = step.get("output")
            if progress is not None:
                progress(index, len(declared_gates), name)
            # min(), never max(): a caller may tighten this gate's ceiling but
            # must not raise one the claim or the host has already set.
            limit = gate_timeout(recipe)
            if timeout is not None:
                limit = min(limit, float(timeout))
            outcome = run_gate(step["run"], work, recipe, timeout=limit,
                               extra_path=venv_bin, strict=strict)
            entry = {
                "output": name,
                "status": outcome["status"],
                "quarantine": outcome["quarantine"],
                "returncode": outcome["returncode"],
                "seconds": round(outcome["seconds"], 3),
                "detail": "",
            }
            if outcome["status"] == "ok":
                entry.update(_compare_pin(claimdir, work, step))
            else:
                entry["detail"] = (outcome["stderr"] or outcome["stdout"])[-400:]
            results.append(entry)
        return {
            "ok": bool(claim_ok and all(g["status"] == "ok" for g in results)),
            "claim_ok": claim_ok,
            "root": manifest.get("root"),
            "recomputed": recomputed,
            "environment": [],
            "gates": results,
        }
    finally:
        shutil.rmtree(scratch, ignore_errors=True)


def _compare_pin(claimdir: str, work: str, step) -> dict:
    """Did the gate reproduce the bytes the claim pins for it?"""
    name = step.get("output")
    if not isinstance(name, str) or not name:
        return {"status": "ok"}
    produced = os.path.join(work, name)
    if not os.path.exists(produced):
        return {"status": "failed", "detail": f"the gate produced no {name}"}
    if step.get("class") == "generated":
        return {"status": "ok"}            # nothing is pinned to compare against
    try:
        pinned_path = _safe(claimdir, name)
    except ClaimError:
        return {"status": "mismatch", "detail": f"{name} escapes the claim"}
    if not os.path.exists(pinned_path):
        return {"status": "mismatch", "detail": f"the claim pins no {name}"}
    try:
        same = _hash_file(pinned_path) == _hash_file(produced)
    except ClaimError as exc:
        return {"status": "mismatch", "detail": str(exc)}
    if same:
        return {"status": "ok"}
    return {"status": "mismatch",
            "detail": f"the gate passed but {name} is not the bytes it produces"}


def phase(claimdir: str) -> str:
    """draft -> sealed -> signed, and only ever for a well-formed claim.

    phase agrees with verify on validity: a claim verify refuses (a corrupt
    recipe or manifest, an input that escapes or is missing) is one phase
    refuses too, rather than answering a positive an auditor would misread.

    SIGNED = AUTHORIZED (a signature from a key this verifier anchors) AND
    PROVEN (a recorded proof) AND COHERENT (the stored packet matches both the
    signature and the bytes on disk).  Trust is verifier-relative.
    """
    recipe = load_recipe(claimdir)
    if not os.path.isfile(os.path.join(claimdir, MANIFEST)):
        return "draft"
    manifest = read_manifest(claimdir)
    recomputed = root(recipe, claimdir)
    if _authorized(claimdir, manifest, recomputed):
        return "signed"
    return "sealed"


def _authorized(claimdir: str, manifest, recomputed: str) -> bool:
    if manifest.get("root") != recomputed:
        return False                       # drifted claim: nothing is authorized
    proof = manifest.get("proof")
    if not proof:
        return False                       # authorized but not proven
    signdir = os.path.join(claimdir, SIGN_DIR)
    if not os.path.isdir(signdir):
        return False
    anchor = os.environ.get(_ENV_SIGNERS)
    if not anchor or not os.path.isfile(anchor):
        return False                       # no trust anchor: not signed TO YOU
    if not shutil.which("ssh-keygen"):
        return False
    try:
        digest = build_digest(claimdir)
    except ClaimError:
        return False
    for entry in sorted(os.listdir(signdir)):
        if not entry.endswith(".sign.json"):
            continue
        statement_path = os.path.join(signdir, entry)
        signature_path = statement_path + ".sig"
        if not os.path.isfile(signature_path):
            continue
        try:
            with open(statement_path, "rb") as f:
                statement = json.loads(f.read().decode("utf-8"))
        except (OSError, UnicodeDecodeError, ValueError):
            continue
        if not isinstance(statement, dict):
            continue
        identity = statement.get("identity")
        if not isinstance(identity, str) or not identity:
            continue
        packet_path = os.path.join(
            signdir, entry[:-len(".sign.json")] + ".packet.json")
        if not os.path.isfile(packet_path):
            continue
        try:
            with open(packet_path, "rb") as f:
                raw = f.read()
            packet = json.loads(raw.decode("utf-8"))
        except (OSError, UnicodeDecodeError, ValueError):
            continue
        if not isinstance(packet, dict):
            continue
        # the STORED packet is authoritative: the reviewable bundle on disk is
        # what the signature binds, so a swapped packet demotes even though the
        # live claim is untouched.
        if hashlib.sha256(raw).hexdigest() != statement.get("packet_digest"):
            continue
        if packet.get("root") != manifest.get("root"):
            continue
        if statement.get("root") != manifest.get("root"):
            continue
        # the signature froze the generated bytes: a rebuild after signing drifts
        if packet.get("build_digest") != digest:
            continue
        if not packet.get("proof") or packet.get("proof") != proof:
            continue
        # domain separation: an attestation must not authorize a mint
        if _ssh_verify(anchor, identity, SIGN_NAMESPACE,
                       signature_path, statement_path):
            return True
    return False


def _ssh_verify(anchor: str, identity: str, namespace: str,
                signature: str, data: str) -> bool:
    try:
        with open(data, "rb") as f:
            payload = f.read()
    except OSError:
        return False
    try:
        proc = subprocess.run(
            ["ssh-keygen", "-Y", "verify", "-f", anchor, "-I", identity,
             "-n", namespace, "-s", signature],
            input=payload, capture_output=True, check=False, timeout=60)
    except (OSError, subprocess.SubprocessError):
        return False
    return proc.returncode == 0


# --------------------------------------------------------------- the rebuild

def rebuild(src: str, command: str, into: str, produce_from=None,
            input_from=None, guidance=True, producer_env=None) -> dict:
    """Redo the claim in a blind workspace and seal what comes out.

    The workspace carries the claim and its pinned bytes but not its generated
    ones -- the producer writes those from the request alone (unless a
    component supplies them, which is ledgered as a reuse).  Every gate is run;
    the cost is accounted as residue; the verdict environment is ledgered.
    """
    _judging_host()
    recipe = load_recipe(src)
    missing = preflight(recipe)
    if missing:
        raise ClaimError("environment: this host cannot test the claim, it "
                         f"lacks {', '.join(missing)}")
    if not isinstance(command, str) or not command.strip():
        raise ClaimError("a rebuild needs a producer command")

    dest = os.path.abspath(into)
    if os.path.exists(dest) and (not os.path.isdir(dest) or os.listdir(dest)):
        raise ClaimError(f"the target already holds a claim: {dest}")
    os.makedirs(os.path.join(dest, STORE), exist_ok=True)

    backend = sandbox_backend()
    ledger(dest, {"event": "environment", "when": _now(),
                  "python": platform.python_version(),
                  "implementation": platform.python_implementation(),
                  "platform": sys.platform, "machine": platform.machine(),
                  "quarantine": backend, "shell": _SHELL})

    reused = _materialize(src, recipe, dest, produce_from=produce_from,
                          input_from=input_from, include_generated=False)
    for name in reused:
        ledger(dest, {"event": "reuse", "when": _now(), "output": name,
                      "note": "supplied by a component, not regenerated"})
    for name in input_from or {}:
        ledger(dest, {"event": "thread", "when": _now(), "input": name,
                      "note": "threaded from a rebuilt component"})

    # Furnish before producing: the producer iterates against the gate, and
    # the gate needs the room's environment. A refusal here propagates -- an
    # unfurnishable room cannot host a rebuild.
    venv_bin = furnish(recipe, dest)

    _produce(recipe, dest, command, produce_from, extra_path=venv_bin,
             guidance=guidance, producer_env=producer_env)

    for step in gates(recipe):
        name = step.get("output")
        outcome = run_gate(step["run"], dest, recipe, extra_path=venv_bin)
        ledger(dest, {"event": "gate", "when": _now(), "output": name,
                      "status": outcome["status"],
                      "returncode": outcome["returncode"],
                      "quarantine": outcome["quarantine"],
                      "seconds": round(outcome["seconds"], 3)})
        if outcome["status"] != "ok":
            # the exception, not the traceback: the last line names what went
            # wrong; the full dump would splice a multi-line traceback into the
            # one-line error contract (docs/cli-style.md).
            out = (outcome["stderr"] or outcome["stdout"] or "").strip()
            last = out.splitlines()[-1].strip() if out else \
                f"exit {outcome['returncode']}"
            raise ClaimError(f"gate {name!r} {outcome['status']}: {last}")
        if name and not os.path.exists(os.path.join(dest, name)):
            raise ClaimError(f"gate {name!r} passed but produced no {name}")

    manifest = seal(dest)
    return {"root": manifest["root"], "claim": dest, "reused": reused,
            "ledger": _ledger_path(dest), "quarantine": backend}


def _step_guidance(step) -> str | None:
    """A step's producer guidance under either key name.  `guidance` is the
    format-3 spelling; `request` is the older one, still read so a claim
    sealed under it keeps guiding its producer."""
    for key in ("guidance", "request"):
        value = step.get(key)
        if isinstance(value, str) and value:
            return value
    return None


def _produce(recipe, dest: str, command: str, produce_from,
             extra_path=None, guidance=True, producer_env=None) -> None:
    """Run the oracle with cwd=dest and account what it cost.

    `guidance=False` is the guidance-blind rebuild: the producer is handed
    the output to write but NOT the hint for how, so a pass measures what the
    acceptance criteria alone carry.  Guidance is not in the format-3 root,
    so a blind rebuild targets the same root a guided one does.

    `producer_env` is what the CALLER deliberately hands the producer over
    the scrub — a vendor credential for a producer the user named, a model
    choice.  The scrub still strips everything inherited: gates never see
    any of this, and nothing arrives that the caller did not place here.
    """
    outputs = generated_outputs(recipe)
    pending = [o for o in outputs
               if not os.path.exists(os.path.join(dest, o))]
    usage = os.path.join(dest, USAGE)
    try:
        os.remove(usage)
    except OSError:
        pass
    extra = {_ENV_CLAIM: dest,
             _ENV_USAGE: usage,                     # ABSOLUTE: `into` may be relative
             _ENV_OUTPUTS: json.dumps(outputs)}
    target = (pending or outputs or [None])[0]
    if target:
        extra[_ENV_OUTPUT] = _safe(dest, target)
        if guidance:
            for step in produces(recipe):
                if step.get("output") == target:
                    hint = _step_guidance(step)
                    if hint is not None:
                        extra[_ENV_REQUEST] = hint
    if producer_env:
        extra.update({k: str(v) for k, v in producer_env.items() if v})
    env = _scrub_env(extra)
    if extra_path:
        env["PATH"] = extra_path + os.pathsep + env["PATH"]

    outcome = _run([_SHELL, "-c", command], cwd=dest, env=env,
                   timeout=PRODUCER_TIMEOUT)
    event = {"event": "oracle", "when": _now(), "calls": 1,
             "seconds": round(outcome["seconds"], 3),
             "status": outcome["status"]}
    for key, value in _read_usage(usage).items():
        if key in COST_KEYS and not isinstance(value, bool) \
                and isinstance(value, (int, float)):
            event[key] = value
    ledger(dest, event)
    ledger(dest, {"event": "producer", "when": _now(),
                  "vendor": os.environ.get(_ENV_VENDOR),
                  "model": os.environ.get(_ENV_MODEL),
                  "blind": not bool(produce_from),
                  "guidance": bool(guidance),
                  "command": command})
    if outcome["status"] != "ok":
        raise ClaimError(
            f"the producer {outcome['status']} (rc={outcome['returncode']}): "
            f"{(outcome['stderr'] or outcome['stdout'])[-400:]}")


def _read_usage(path: str) -> dict:
    """A producer's self-reported cost.  Junk pollutes nothing."""
    try:
        with open(path, "rb") as f:
            raw = f.read()
    except OSError:
        return {}
    try:
        payload = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, ValueError):
        return {}
    if not isinstance(payload, dict):
        return {}                          # a list is refused, not totalled
    return payload
