"""The kernel's crosscheck layer: the three-machine test, the vacuity boundary, and mutation."""
import ast
import io
import os
import random
import re
import shlex
import shutil
import tempfile
import tokenize

from .attest import (
    record_digest,
    record_read,
    record_signer,
)
from .build import (
    audit,
)
from .core import (
    _ENV_SIGNERS,
    _ENV_TOLERANCE,
    COST_LADDER,
    MANIFEST,
    MUTANT_CEILING,
    MUTANT_FLOOR,
    MUTANT_HEADROOM,
    MUTATION_RESIDUE,
    TOLERANCE,
    ClaimError,
    _judging_host,
    _now,
    _safe,
    _write_json,
)
from .identity import (
    build_digest,
    root,
)
from .recipe import (  # noqa: F401
    _steps,
    gates,
    load_recipe,
    produces,
)
from .run import (  # noqa: F401
    _in_band,
    _independence_line,
    cost,
    independence,
    ledger,
    sandbox,
)
from .seal import (
    read_manifest,
    verify,
)

# ------------------------------------------------------- the three machines

def _machine(label: str, path):
    """One leg of the three-machine test: computed from a claim directory, or
    thawed from a record file.  A record is a frozen leg -- the same facts on
    a second transport -- so the comparison downstream cannot tell them
    apart, which is the point: one predicate, two transports.
    """
    if isinstance(path, str) and os.path.isdir(path):
        try:
            digest = build_digest(path)
        except ClaimError:
            digest = None
        return {"kind": "directory", "where": os.path.realpath(path),
                "root": verify(path)["root"],
                "audited": bool(audit(path)["ok"]),
                "digest": digest, "cost": cost(path),
                "declaration": independence(path), "record": None}
    if isinstance(path, str) and os.path.isfile(path):
        doc = record_read(path)
        told = doc.get("producer") or {}
        return {"kind": "record", "where": os.path.realpath(path),
                "root": doc["root"],
                "audited": all(g["status"] == "ok" for g in doc["gates"]),
                "digest": doc["build_digest"], "cost": doc.get("cost"),
                "declaration": {"vendor": told.get("vendor"),
                                "model": told.get("model"),
                                "blind": told.get("blind"),
                                "declared": bool(told)},
                "record": {"path": os.path.realpath(path),
                           "digest": record_digest(doc)}}
    raise ClaimError(f"{label} is not a claim directory or a record file: "
                     f"{path!r}")


def crosscheck(m1, m2, m3, mutants=None, tolerance=None) -> dict:
    """THE THREE-MACHINE TEST.

    One root across an original (M1), a byte-reuse that travelled by content
    (M2), and an independent redo (M3) -- with every verdict re-earned on its
    own bytes.  Three DISTINCT machines: one machine presented thrice agrees
    with itself and proves nothing.  Root equality is identity, not soundness:
    a fabricated machine that shares the root but whose gates cannot reproduce
    its verdicts neither crosschecks nor signs.

    A machine may be handed as a claim DIRECTORY (a leg computed here, by
    running its gates) or as a RECORD file (a frozen leg, spec/record.md);
    the transports mix freely and reach the same verdict, because a record is
    an input to this comparison, not a second definition of it.  A frozen leg
    is someone's signed statement: its signature status against the caller's
    anchor is reported per leg, and `record_proof` below refuses to build
    durable evidence from one the anchor does not verify.
    """
    machines = {"M1": m1, "M2": m2, "M3": m3}
    legs = {label: _machine(label, path) for label, path in machines.items()}
    resolved = {label: leg["where"] for label, leg in legs.items()}
    if len(set(resolved.values())) != 3:
        raise ClaimError("the three-machine test needs three distinct machines; "
                         "the same machine presented twice proves nothing")

    roots = {label: legs[label]["root"] for label in machines}
    audited = {label: legs[label]["audited"] for label in machines}
    digests = {label: legs[label]["digest"] for label in machines}

    equivalence = (all(isinstance(r, str) and r for r in roots.values())
                   and len(set(roots.values())) == 1)
    # REUSE is byte-reuse: M2 must be M1's generated bytes, not a second redo
    # that merely lands the same root.
    reuse = bool(digests["M1"] and digests["M2"]
                 and digests["M1"] == digests["M2"])

    claim_table = {}
    if legs["M1"]["kind"] == "directory":
        claim_table = load_recipe(m1).get("claim") or {}
    band = tolerance
    if band is None:
        band = claim_table.get("tolerance")
    if band is None:
        band = os.environ.get(_ENV_TOLERANCE)
    try:
        band = float(band) if band is not None else TOLERANCE
    except (TypeError, ValueError):
        band = TOLERANCE
    if band <= 0:
        band = TOLERANCE

    original, redo = legs["M1"]["cost"], legs["M3"]["cost"]
    shared = {k for k in set(original or {}) & set(redo or {})
              if original[k] and redo[k]}
    unit = next((u for u in COST_LADDER if u in shared), None)
    comparable = None                      # unmeasured is REPORTED, not failed
    if unit is not None:
        comparable = _in_band(original[unit], redo[unit], band)

    # THE PINNED ENVELOPE: ceilings the claim itself declares, inside the
    # root -- "these tests determine this software within this budget". The
    # band above compares two ledgers; this compares the redo to the claim's
    # own commitment, so it works when M1 was never rebuilt and carries no
    # ledger at all. A measured overrun fails the test; a unit the redo did
    # not measure is untested, reported rather than failed; an under-run
    # passes but stays visible -- a redo far cheaper than the commitment is
    # a signal to read, never an error to raise.
    declared = claim_table.get("envelope") or None
    envelope = None
    if declared:
        envelope = {}
        for name in sorted(declared):
            paid = (redo or {}).get(name)
            envelope[name] = {
                "limit": declared[name], "spent": paid,
                "within": None if paid is None else bool(paid <= declared[name]),
            }

    score = None
    if mutants:
        if legs["M1"]["kind"] != "directory":
            raise ClaimError("a mutation score needs M1's bytes to mutate, "
                             "and a record carries none")
        score = mutation_score(m1, max_mutants=int(mutants))

    # THE VERDICT IS THREE-VALUED. A hard condition must be TRUE to accept
    # and rejects on FALSE. A hard condition the claim DECLARED but this run
    # did not measure is neither: the test is INCOMPLETE, and incomplete can
    # never accept, because unknown evidence is not evidence. Observations
    # (independence, a cost band with no shared unit) never decide.
    # Declared conditions are read from M1's recipe, so they can only be
    # evaluated when M1 is a claim directory; a record carries no recipe.
    rejected = []
    if not equivalence:
        rejected.append("equivalence")
    if not reuse:
        rejected.append("reuse")
    rejected += [f"audited {label}" for label in sorted(audited)
                 if not audited[label]]
    # THE BAND IS HARD ONLY WHEN THE CLAIM DECLARED IT (v2.4). A tolerance
    # written into the recipe is inside the root, so exceeding it rejects,
    # like any declared condition. With no declared tolerance the ratio is
    # still computed and reported at the default band -- an observation a
    # reader weighs, never a verdict. The first real three-machine proof
    # demanded this: only declared conditions are hard.
    if comparable is False and claim_table.get("tolerance") is not None:
        rejected.append("cost band")
    incomplete = []
    if envelope:
        for name in sorted(envelope):
            if envelope[name]["within"] is False:
                rejected.append(f"envelope {name}")
            elif envelope[name]["within"] is None:
                incomplete.append(f"envelope {name} declared but not measured")
    if score is not None and not score["ok"]:
        rejected.append("mutation floor")
    elif score is None and claim_table.get("mutation_floor") is not None:
        incomplete.append("mutation_floor declared but not measured")
    verdict = "reject" if rejected else ("incomplete" if incomplete else "accept")
    satisfied = verdict == "accept"
    result = {
        "satisfied": satisfied,
        "verdict": verdict,
        "rejected": rejected,
        "incomplete": incomplete,
        "roots": roots,
        "equivalence": equivalence,
        "reuse": reuse,
        "audited": audited,
        "digests": digests,
        "cost": {"comparable": comparable, "M1": original, "M3": redo,
                 "unit": unit, "compared": sorted(shared), "tolerance": band,
                 "envelope": envelope},
        "mutation_score": score,
        "independence": _independence_line(legs["M3"]["declaration"]),
        "machines": resolved,
    }
    frozen = {}
    anchor = os.environ.get(_ENV_SIGNERS)
    for label, leg in legs.items():
        if leg["record"] is None:
            continue
        frozen[label] = {"digest": leg["record"]["digest"],
                         "signer": record_signer(leg["record"]["path"], anchor)}
    if frozen:
        result["records"] = frozen
    return result


def record_proof(m1, m2, m3, mutants=None) -> dict:
    """Record a passing three-machine test as residue on M1's manifest.

    A recorded proof is not an authorization: it is the evidence a signature
    later binds.  A test that is not satisfied records nothing.

    M1 must be a claim DIRECTORY -- the proof is residue on its manifest, and
    a frozen record has no manifest to land on.  Frozen legs may stand as M2
    or M3, but only ANCHORED ones: comparison is free (crosscheck judges
    whatever it is handed, as it always has for directories), durable
    evidence is not.  The boundary is the transport -- directory legs are the
    caller's own executions and need no anchor; record legs are relayed
    statements whose only provenance is a signature -- and a proof embeds the
    digests and signer identities of the records it consumed, so a reader can
    walk from the verdict to the statements beneath it.  "Unverified" in that
    walk would poison it, so it is refused instead.
    """
    if not (isinstance(m1, str) and os.path.isdir(m1)):
        raise ClaimError("a proof is residue on M1's manifest, so M1 must be "
                         f"a claim directory: {m1!r}")
    result = crosscheck(m1, m2, m3, mutants=mutants)
    embedded = []
    for label in ("M2", "M3"):
        frozen = (result.get("records") or {}).get(label)
        if frozen is None:
            continue
        if not frozen.get("signer"):
            raise ClaimError(
                f"{label} is a record whose signature does not verify against "
                f"the anchor ({_ENV_SIGNERS}): durable evidence embeds signer "
                "identities, and unverified is not one")
        embedded.append({"digest": frozen["digest"],
                         "signer": frozen["signer"]})
    recorded = False
    if result["satisfied"]:
        manifest = read_manifest(m1)
        proof = {
            "kind": "crosscheck",
            "root": result["roots"]["M1"],
            "m2": result["digests"]["M2"] or "",
            "m3": result["digests"]["M3"] or "",
            "independence": result["independence"],
            "recorded": _now(),
        }
        if embedded:
            proof["records"] = sorted(embedded, key=lambda r: r["digest"])
        manifest["proof"] = proof
        _write_json(os.path.join(m1, MANIFEST), manifest)
        recorded = True
    out = dict(result)
    out["proof_recorded"] = recorded
    return out


# --------------------------------------------------------- the claim boundary

_INTERPRETERS = frozenset({
    "python", "python2", "python3", "py", "pytest", "py.test", "sh", "bash",
    "zsh", "dash", "node", "deno", "ruby", "perl", "lua", "php", "Rscript",
    "tclsh", "awk",
})
_OPERATORS = frozenset({"&&", "||", ";", "|", "&", "\n"})
_SKIP_VALUE = frozenset({"-m", "-c", "-e", "-X", "--module", "-p"})


def gate_deciders(run: str) -> list:
    """The workspace things a gate command EXECUTES, in order.

    A script the gate runs decides the verdict; a file a tool merely reads does
    not (that gate decides by the recipe).  This is what tells a claimed check
    from a generated one.
    """
    if not isinstance(run, str):
        return []
    try:
        tokens = shlex.split(run, comments=False)
    except ValueError:
        tokens = run.split()
    segments, current = [], []
    for token in tokens:
        if token in _OPERATORS:
            segments.append(current)
            current = []
        else:
            current.append(token)
    segments.append(current)

    found = []
    for segment in segments:
        words = []
        skip = False
        for token in segment:
            if skip:
                skip = False
                continue
            if token in (">", ">>", "<", "<<", "2>", "2>>", "&>", "1>"):
                skip = True                # drop a redirection and its target
                continue
            if token[:1] in (">", "<") or token[:2] in ("2>", "1>"):
                continue
            words.append(token)
        if not words:
            continue
        command, args = words[0], words[1:]
        if command.startswith("./") or (
                "/" in command and not os.path.isabs(command)):
            found.append(command.removeprefix("./"))
        base = os.path.basename(command)
        if base in _INTERPRETERS:
            index = 0
            while index < len(args):
                arg = args[index]
                if arg == "--":
                    index += 1
                    continue
                if arg.startswith("-"):
                    index += 2 if arg in _SKIP_VALUE else 1
                    continue
                found.append(arg.removeprefix("./"))
                index += 1
    seen, ordered = set(), []
    for name in found:
        if name not in seen:
            seen.add(name)
            ordered.append(name)
    return ordered


def vacuous_gates(recipe) -> list:
    """Gates whose every decider is generated -- so they decide nothing.

    If the checker is itself free, the root fits any implementation that prints
    ok: the verdict depends on no claim.  The kernel names such gates so that
    authoring can refuse them.
    """
    claim = (recipe or {}).get("claim") or {}
    declared = claim.get("inputs") or []
    claimed = {name for name in declared if isinstance(name, str)}
    generated = set()
    for step in _steps(recipe):
        output = step.get("output")
        if not isinstance(output, str):
            continue
        if step.get("class") == "generated":
            generated.add(output)
        else:
            claimed.add(output)

    vacuous = []
    for step in _steps(recipe):
        if step.get("kind") != "gate":
            continue
        deciders = gate_deciders(step.get("run"))
        if not deciders:
            continue                       # decides by the recipe, not by code
        if any(_named(d, claimed) for d in deciders):
            continue
        if all(_named(d, generated) for d in deciders):
            vacuous.append(step.get("output"))
    return vacuous


def _named(decider: str, names) -> bool:
    plain = decider.removeprefix("./")
    return decider in names or plain in names


# -------------------------------------------------------- the width measured

# ------------------------------------------------------------ fault injection
#
# A mutation score is only ever as wide as the faults the injector can write,
# and that width does not appear anywhere in the number it prints. The first
# version of this table swapped operators and nothing else. examples/weak
# scored 0.80 under it while differing from its sibling implementation ONLY in
# two constants -- because no mutation the injector could express ever touched
# a constant. The score was measuring the injector.
#
# Hence a wider fault model below, and a rate broken down BY KIND: "the tests
# catch operator swaps and miss boundary constants" is actionable in a way a
# single rate is not.
#
# Two biases remain, and neither is fixable here:
#
#   EQUIVALENT MUTANTS change the text without changing the behaviour -- a
#   constant that is never read, a branch that cannot be taken. They survive
#   every suite, so they depress the rate for reasons that have nothing to do
#   with the tests. Recognising them in general is undecidable. Docstrings are
#   skipped because they are the one large, cheap source of them.
#
#   THE COMPETENT PROGRAMMER HYPOTHESIS: all of this assumes a real fault is a
#   small deviation from correct code. Model-written code often fails the other
#   way -- a clean implementation of the wrong specification -- and no mutation
#   of an implementation can detect a misreading of what was wanted. That is
#   why `assess` has rungs above this one.

_COMPARISON = (">", "<", ">=", "<=", "==", "!=")
_ARITHMETIC = ("+", "-", "*", "/", "//", "%")

_OP_ALTS = {
    ">": ("<", "<=", ">=", "==", "!="),
    "<": (">", ">=", "<=", "==", "!="),
    ">=": ("<", ">", "<=", "==", "!="),
    "<=": ("<", ">", ">=", "==", "!="),
    "==": ("!=", "<", ">", "<=", ">="),
    "!=": ("==", "<", ">", "<=", ">="),
    "+": ("-", "*", "/", "//", "%"),
    "-": ("+", "*", "/", "//", "%"),
    "*": ("+", "-", "/", "//", "%"),
    "/": ("+", "-", "*", "//", "%"),
    "//": ("+", "-", "*", "/", "%"),
    "%": ("+", "-", "*", "/", "//"),
}

_OP_KIND = dict.fromkeys(_COMPARISON, "comparison")
_OP_KIND.update(dict.fromkeys(_ARITHMETIC, "arithmetic"))

#: Operators Python spells as words. These arrive as NAME tokens, not OP
#: tokens, so the table above never saw one: every boolean-logic fault in every
#: program this has scored went unmeasured, and silently.
_WORD_ALTS = {
    "and": (("or", "boolean"),),
    "or": (("and", "boolean"),),
    "True": (("False", "boolean"),),
    "False": (("True", "boolean"),),
    "not": (("", "boolean"),),           # `not x` -> `x`, and `is not` -> `is`
    "is": (("is not", "comparison"),),
    "in": (("not in", "comparison"),),   # `for x in y` will not compile: dropped
}

#: A string literal this injector understands well enough to empty. f-strings
#: and byte strings are left alone: replacing either with `""` changes a type
#: rather than a value, and a suite that catches the resulting TypeError has
#: demonstrated nothing about how closely it reads.
_STRING_LITERAL = re.compile(r"^([rR]?)('''|\"\"\"|'|\")(.*)\2$", re.DOTALL)


def _splice(text: str, start, end, replacement: str):
    """Replace one (row, col)..(row, col) span. Rows 1-based, columns 0-based."""
    lines = text.splitlines(keepends=True)
    (srow, scol), (erow, ecol) = start, end
    if not 1 <= srow <= erow <= len(lines):
        return None
    return ("".join(lines[:srow - 1]) + lines[srow - 1][:scol] + replacement
            + lines[erow - 1][ecol:] + "".join(lines[erow:]))


def _span_text(text: str, start, end) -> str:
    """The source lying between two positions -- so an argument swap moves the
    bytes that are actually there, rather than a reconstruction of them."""
    lines = text.splitlines(keepends=True)
    (srow, scol), (erow, ecol) = start, end
    if srow == erow:
        return lines[srow - 1][scol:ecol]
    return (lines[srow - 1][scol:] + "".join(lines[srow:erow - 1])
            + lines[erow - 1][:ecol])


def _label(text: str, width: int = 24) -> str:
    """A mutant id has to survive being printed, so flatten and cap it."""
    flat = " ".join(str(text).split())
    return (flat[:width] + "…") if len(flat) > width else (flat or "(removed)")


def _edit(output: str, kind: str, frm, to, *edits) -> dict:
    """One candidate fault, as the spans to overwrite -- never as mutated text.

    A wide fault model over a large file runs to thousands of candidates, and
    the narrow injector kept a whole mutated copy of the file with each one.
    At the old width that was already tens of megabytes per scored claim.
    """
    start = edits[0][0]
    return {
        "id": f"{output}:{start[0]}:{start[1]}:{kind}:{_label(frm)}->{_label(to)}",
        "output": output, "line": start[0], "column": start[1],
        "kind": kind, "frm": frm, "to": to, "edits": list(edits),
    }


def _docstring_spans(tree) -> set:
    """Where the docstrings start, so the injector can leave them alone.

    A mutated docstring is an equivalent mutant by construction: it survives
    every conceivable suite. Left in, they would be a large share of the pool
    of any documented program, and a well-tested one would score worse for
    being well documented."""
    spans = set()
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef,
                                 ast.AsyncFunctionDef)):
            continue
        body = getattr(node, "body", None) or []
        first = body[0] if body else None
        if (isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant)
                and isinstance(first.value.value, str)):
            spans.add((first.value.lineno, first.value.col_offset))
    return spans


def _token_mutants(output: str, tokens: list, docstrings: set) -> list:
    """Faults a token scan can express: operators, keywords, and literals."""
    out = []
    for token in tokens:
        alternatives: tuple = ()
        if token.type == tokenize.OP:
            alternatives = tuple((alt, _OP_KIND[token.string])
                                 for alt in _OP_ALTS.get(token.string, ()))
        elif token.type == tokenize.NAME:
            alternatives = _WORD_ALTS.get(token.string, ())
        elif token.type == tokenize.NUMBER:
            # n+1, n-1 and 0: the off-by-one and the degenerate value. These
            # are the faults a threshold gets wrong, and the whole class the
            # operator table could not reach.
            alternatives = tuple(
                (alt, "constant")
                for alt in (f"{token.string}+1", f"{token.string}-1", "0")
                if alt != token.string)
        elif token.type == tokenize.STRING and token.start not in docstrings:
            matched = _STRING_LITERAL.match(token.string)
            alternatives = (('""', "string"),) if matched and matched.group(3) else ()
        for alternative, kind in alternatives:
            out.append(_edit(output, kind, token.string, alternative,
                             (token.start, token.end, alternative)))
    return out


def _node_span(node):
    """A syntax node's source extent, when it has one."""
    if getattr(node, "end_lineno", None) is None:
        return None
    return ((node.lineno, node.col_offset), (node.end_lineno, node.end_col_offset))


def _structural_mutants(output: str, tree, text: str) -> list:
    """Faults with a shape rather than a spelling, which need the syntax tree.

    Forcing a branch, dropping a return value and transposing two arguments are
    the ones worth having: each is a fault that occurs in real code, and none
    of the three can be written as a swap of adjacent characters.
    """
    out = []
    for node in ast.walk(tree):
        if isinstance(node, ast.If | ast.While):
            if isinstance(node.test, ast.Constant) and isinstance(node.test.value, bool):
                continue                   # already constant: nothing to force
            span = _node_span(node.test)
            for alternative in ("True", "False") if span else ():
                out.append(_edit(output, "branch", "<test>", alternative,
                                 (span[0], span[1], alternative)))
        elif isinstance(node, ast.Return) and node.value is not None:
            if isinstance(node.value, ast.Constant) and node.value.value is None:
                continue
            span = _node_span(node.value)
            if span:
                out.append(_edit(output, "return", "<value>", "None",
                                 (span[0], span[1], "None")))
        elif isinstance(node, ast.Call) and len(node.args) >= 2:
            first, second = node.args[0], node.args[1]
            if isinstance(first, ast.Starred) or isinstance(second, ast.Starred):
                continue                   # a splat has no position to swap
            here, there = _node_span(first), _node_span(second)
            if not here or not there:
                continue
            stays, moved = _span_text(text, *here), _span_text(text, *there)
            if moved == stays:
                continue                   # swapping equals is not a fault
            out.append(_edit(output, "argument", stays, moved,
                             (here[0], here[1], moved), (there[0], there[1], stays)))
    return out


def _mutants(output: str, text: str) -> list:
    """Every fault this injector can express in one generated file."""
    try:
        tree = ast.parse(text)
        tokens = list(tokenize.generate_tokens(io.StringIO(text).readline))
    except (tokenize.TokenError, SyntaxError, ValueError, MemoryError,
            RecursionError):
        return []                          # not Python, or not parseable
    docstrings = _docstring_spans(tree)
    return (_token_mutants(output, tokens, docstrings)
            + _structural_mutants(output, tree, text))


def _mutant_order(mutant: dict) -> tuple:
    return (mutant["output"], mutant["line"], mutant["column"], mutant["kind"],
            str(mutant["frm"]), str(mutant["to"]))


def _draw_order(candidates: list, seed: str) -> list:
    """Deterministic, and STRATIFIED: round-robin across the fault kinds.

    A uniform draw is dominated by whatever the program has most of, which is
    usually arithmetic. A twenty-mutant sample of a large file could then
    contain no boundary constant at all, and the per-kind breakdown would be
    empty in exactly the place a reader most needs it. Round-robin spends the
    budget across the fault model instead of across the source.
    """
    groups: dict = {}
    for candidate in sorted(candidates, key=_mutant_order):
        groups.setdefault(candidate["kind"], []).append(candidate)
    rng = random.Random(seed)
    for kind in sorted(groups):
        rng.shuffle(groups[kind])
    order: list = []
    while any(groups.values()):
        for kind in sorted(groups):
            if groups[kind]:
                order.append(groups[kind].pop())
    return order


def mutation_score(claimdir: str, max_mutants: int = 8, floor=None) -> dict:
    """How WIDE is the equivalence class?  Mutate the generated code and re-audit.

    The sample is drawn deterministically from the root, so the measurement is
    reproducible and cannot be shopped for.  A mutant that still audits clean
    is a SURVIVOR: the claim did not pin the behaviour it changed.  The score
    is residue -- it never touches the root -- and a declared
    `[claim] mutation_floor` turns it into a gate on the three-machine test.

    THE RATE IS ONLY AS BROAD AS THE FAULT MODEL, so the report carries the
    model with it: `by_kind` gives the kill rate per kind of fault injected
    and `pool_by_kind` the sites available for each.  A claim that kills every
    arithmetic mutant and no constant has a rate that means something quite
    different from one that kills half of everything, and a bare 0.50 cannot
    tell the reader which they are holding.

    `candidates` counts sites the injector found, not mutants it could run:
    some do not compile (`for x in y` has no `not in` form), and `unparseable`
    counts those passed over while filling the sample.
    """
    _judging_host()
    recipe = load_recipe(claimdir)
    identity = root(recipe, claimdir)
    if floor is None:
        floor = (recipe.get("claim") or {}).get("mutation_floor")

    candidates, sources = [], {}
    for step in produces(recipe):
        if step.get("class") != "generated":
            continue
        name = step.get("output")
        if not isinstance(name, str) or not name:
            continue
        path = _safe(claimdir, name)
        if not os.path.isfile(path):
            continue
        try:
            with open(path, encoding="utf-8") as f:
                text = f.read()
        except (OSError, UnicodeDecodeError):
            continue
        sources[name] = text
        candidates.extend(_mutants(name, text))

    pool: dict = {}
    for candidate in candidates:
        pool[candidate["kind"]] = pool.get(candidate["kind"], 0) + 1

    # Draw, write and syntax-check together, passing over anything that will
    # not compile: `for x in y` cannot become `for x not in y`, and a mutant
    # that does not parse is noise rather than evidence. The narrow injector
    # spent this check at enumeration time, which is why it had to hold a
    # mutated copy of every file for every site it found.
    budget = max(0, int(max_mutants or 0))
    sample, unparseable = [], 0
    for candidate in _draw_order(candidates, identity):
        if len(sample) >= budget:
            break
        source = sources.get(candidate["output"])
        for start, end, replacement in sorted(candidate["edits"], reverse=True):
            if source is None:
                break
            source = _splice(source, start, end, replacement)
        if source is None:
            unparseable += 1
            continue
        try:
            compile(source, "<mutant>", "exec")
        except (SyntaxError, ValueError):
            unparseable += 1
            continue
        sample.append(dict(candidate, text=source))
    sample.sort(key=_mutant_order)

    # TIME-BOX EACH MUTANT against how long the GATE takes when it is healthy.
    # Mutating a loop condition routinely produces a program that does not
    # terminate, and the standing ceiling is ten minutes: twenty such mutants
    # is three hours spent on an answer that was available in a second.
    #
    # The baseline is the gate's own wall time, not the audit's. Measuring the
    # whole call folds in materialisation and sandbox setup, which are fixed
    # overhead and can dwarf a fast check -- a real claim whose suite ran in
    # 1.05s was handing its mutants a hundred seconds each, because the audit
    # around it took ten. The ceiling is there for the opposite case: a claim
    # slow enough that generous headroom is not affordable.
    healthy = audit(claimdir)
    gate_seconds = max((g.get("seconds") or 0.0) for g in healthy["gates"]) \
        if healthy.get("gates") else 0.0
    limit = (min(MUTANT_CEILING, max(MUTANT_FLOOR, MUTANT_HEADROOM * gate_seconds))
             if healthy["ok"] else None)

    survivors, killed, by_kind, expired = [], 0, {}, 0
    for mutant in sample:
        scratch = tempfile.mkdtemp(prefix="reticuli-mutant-")
        try:
            staged = os.path.join(scratch, os.path.basename(mutant["output"]))
            with open(staged, "w", encoding="utf-8") as f:
                f.write(mutant["text"])
            verdict = audit(claimdir, produce_from={mutant["output"]: staged},
                            timeout=limit)
        finally:
            shutil.rmtree(scratch, ignore_errors=True)
        tally = by_kind.setdefault(mutant["kind"],
                                   {"mutants": 0, "killed": 0, "survivors": []})
        tally["mutants"] += 1
        if verdict["ok"]:
            survivors.append(mutant["id"])
            tally["survivors"].append(mutant["id"])
        else:
            killed += 1
            tally["killed"] += 1
            # A mutant that runs out of clock counts as detected -- the suite
            # did notice the fault -- but it is a weaker kind of detection than
            # an assertion failing, so the count is reported rather than folded
            # away. A rate made mostly of timeouts is a rate about a machine.
            if any(g.get("status") == "timeout" for g in verdict.get("gates", [])):
                expired += 1
    for tally in by_kind.values():
        tally["rate"] = tally["killed"] / tally["mutants"]

    rate = (killed / len(sample)) if sample else 0.0
    try:
        bar = float(floor) if floor is not None else None
    except (TypeError, ValueError):
        bar = None
    score = {
        "mutants": len(sample),
        "killed": killed,
        "survivors": survivors,
        "rate": rate,
        "by_kind": by_kind,
        "pool_by_kind": pool,
        "unparseable": unparseable,
        "timed_out": expired,
        "mutant_timeout": limit,
        "floor": bar,
        "ok": True if bar is None else rate >= bar,
        "candidates": len(candidates),
        "root": identity,
        "measured": _now(),
    }
    _write_json(os.path.join(claimdir, MUTATION_RESIDUE), score)
    return score
