"""Attestation: a keyholder's signed statement of a build (spec/layers.md,
"exchange").

Two ceremonies live here. `attest`/`check` are a lightweight signed
statement of one build -- signs only a claim whose verdicts reproduce
right now (never a carried verdict), refuses when the signed statement
itself is tampered, and reports drift honestly when the generated bytes
move out from under it. `sign`/`sign_check`/`review_packet` are the
accountable ceremony: a human signs the folded chain root over a review
packet (the audit, the chain signature, the recorded proof), and SIGNED
means AUTHORIZED (a trusted signature) AND PROVEN (a recorded proof) --
`kernel.phase` reads exactly this structure back.
"""
import hashlib
import json
import os
import shutil
import subprocess

from reticuli import kernel
from reticuli import registry

ATTEST = ".reticuli/attest"
CEREMONY = "RETICULI_CLAIM_BASIN_V1"


def _canonical(obj) -> bytes:
    return json.dumps(obj, sort_keys=True).encode("utf-8")


def _ssh_verify(data: bytes, sig_path: str, namespace: str, signers_path, principal: str) -> bool:
    if not (signers_path and os.path.isfile(signers_path) and os.path.isfile(sig_path)
            and shutil.which("ssh-keygen")):
        return False
    done = subprocess.run(
        ["ssh-keygen", "-Y", "verify", "-f", signers_path, "-I", principal,
         "-n", namespace, "-s", sig_path],
        input=data, capture_output=True, timeout=10, check=False,
    )
    return done.returncode == 0


# ===========================================================================
# attest / check: a signed statement of one build.
# ===========================================================================


def attest(d: str, key: str, principal: str) -> dict:
    """Sign a statement of `d`'s current build: refuses unless every
    gate re-earns its verdict right now (`kernel.audit`) -- never
    notarizing a carried verdict or a broken claim.
    """
    aud = kernel.audit(d)
    if not aud.get("ok"):
        raise kernel.ClaimError("attest refuses a claim whose verdicts do not reproduce")
    vr = kernel.verify(d)

    statement = {
        "root": vr["root"],
        "build_digest": kernel.build_digest(d),
        "name": vr["name"],
        "principal": principal,
    }
    stem = principal.replace("/", "_")
    attest_dir = os.path.join(d, ATTEST)
    os.makedirs(attest_dir, exist_ok=True)
    stmt_path = os.path.join(attest_dir, f"{stem}.attest.json")
    with open(stmt_path, "wb") as f:
        f.write(_canonical(statement))

    sig_path = stmt_path + ".sig"
    if os.path.isfile(sig_path):
        os.remove(sig_path)  # ssh-keygen -Y sign prompts before overwriting one
    subprocess.run(["ssh-keygen", "-Y", "sign", "-f", key, "-n", kernel.NAMESPACE, stmt_path],
                   check=True, capture_output=True)

    return {
        "root": vr["root"],
        "build_digest": statement["build_digest"],
        "statement": os.path.relpath(stmt_path, d),
        "signature": os.path.relpath(sig_path, d),
    }


def check(d: str, signers=None) -> dict:
    """Whether every attestation on `d` still names the build present:
    not drifted (the statement's digests match the bytes present now),
    and -- when `signers` is given -- verified against that anchor.
    """
    vr = kernel.verify(d)
    current_digest = kernel.build_digest(d)
    attest_dir = os.path.join(d, ATTEST)

    attestations = []
    ok_all = True
    if os.path.isdir(attest_dir):
        for fname in sorted(os.listdir(attest_dir)):
            if not fname.endswith(".attest.json"):
                continue
            stmt_path = os.path.join(attest_dir, fname)
            sig_path = stmt_path + ".sig"
            with open(stmt_path, "rb") as f:
                data = f.read()
            try:
                statement = json.loads(data)
            except json.JSONDecodeError:
                attestations.append({"statement": fname, "verdict": "malformed", "drifted": None})
                ok_all = False
                continue

            drifted = (statement.get("root") != vr["root"]
                       or statement.get("build_digest") != current_digest)
            verdict = None
            if signers is not None:
                principal = statement.get("principal", "attestor")
                verdict = "signed" if _ssh_verify(data, sig_path, kernel.NAMESPACE, signers,
                                                  principal) else "unsigned"

            entry = {"statement": os.path.relpath(stmt_path, d),
                     "principal": statement.get("principal"),
                     "root": statement.get("root"), "build_digest": statement.get("build_digest"),
                     "drifted": drifted, "verdict": verdict}
            attestations.append(entry)
            if drifted or (signers is not None and verdict != "signed"):
                ok_all = False

    return {"ok": ok_all and bool(attestations), "root": vr["root"], "attestations": attestations}


# ===========================================================================
# review_packet / sign / sign_check: the accountable ceremony.
# ===========================================================================


def review_packet(d: str, ws=None) -> dict:
    """The packet a signer reviews: the audit re-earned now, the folded
    chain signature, and whether a proof is currently recorded.
    """
    vr = kernel.verify(d)
    aud = kernel.audit(d)
    manifest = kernel.read_manifest(d)
    return {
        "root": vr["root"],
        "build_digest": kernel.build_digest(d),
        "sign_root": registry.sign_root(d, ws),
        "audit": {"ok": bool(aud.get("ok"))},
        "proof": manifest.get("proof"),
    }


def sign(d: str, key: str, principal: str, ws=None) -> dict:
    """The signing ceremony: refuses a claim whose verdicts do not
    reproduce, then signs the chain root over a freshly assembled review
    packet, binding the signed statement to the packet's own digest.
    """
    aud = kernel.audit(d)
    if not aud.get("ok"):
        raise kernel.ClaimError("sign refuses a claim whose verdicts do not reproduce")

    packet = review_packet(d, ws=ws)
    packet_bytes = _canonical(packet)
    packet_digest = hashlib.sha256(packet_bytes).hexdigest()

    stem = principal.replace("/", "_")
    sign_dir = os.path.join(d, kernel.SIGN_DIR)
    os.makedirs(sign_dir, exist_ok=True)

    packet_path = os.path.join(sign_dir, f"{stem}.packet.json")
    with open(packet_path, "wb") as f:
        f.write(packet_bytes)

    statement = {
        "ceremony": CEREMONY,
        "root": packet["root"],
        "build_digest": packet["build_digest"],
        "packet_digest": packet_digest,
        "principal": principal,
    }
    stmt_path = os.path.join(sign_dir, f"{stem}.sign.json")
    with open(stmt_path, "wb") as f:
        f.write(_canonical(statement))

    sig_path = stmt_path + ".sig"
    if os.path.isfile(sig_path):
        os.remove(sig_path)  # ssh-keygen -Y sign prompts before overwriting one
    subprocess.run(["ssh-keygen", "-Y", "sign", "-f", key, "-n", kernel.SIGN_NAMESPACE, stmt_path],
                   check=True, capture_output=True)

    return {
        "ceremony": CEREMONY,
        "root": packet["root"],
        "sign_root": packet["sign_root"],
        "statement": os.path.relpath(stmt_path, d),
        "signature": os.path.relpath(sig_path, d),
        "packet": os.path.relpath(packet_path, d),
    }


def sign_check(d: str, ws=None, signers=None) -> dict:
    """Verify every authorization on `d`: a trusted signature over the
    statement, and the statement's digest binding the stored packet file
    that packet currently holds on disk.
    """
    vr = kernel.verify(d)
    sign_dir = os.path.join(d, kernel.SIGN_DIR)

    authorizations = []
    ok_all = True
    if os.path.isdir(sign_dir):
        for fname in sorted(os.listdir(sign_dir)):
            if not fname.endswith(".sign.json"):
                continue
            prefix = fname[: -len(".sign.json")]
            stmt_path = os.path.join(sign_dir, fname)
            sig_path = stmt_path + ".sig"
            packet_path = os.path.join(sign_dir, prefix + ".packet.json")

            with open(stmt_path, "rb") as f:
                stmt_bytes = f.read()
            try:
                stmt = json.loads(stmt_bytes)
            except json.JSONDecodeError:
                authorizations.append({"principal": prefix, "verdict": "malformed",
                                       "packet_holds": False, "proof_recorded": False})
                ok_all = False
                continue

            principal = stmt.get("principal", prefix)
            verdict = "unauthorized"
            if signers and _ssh_verify(stmt_bytes, sig_path, kernel.SIGN_NAMESPACE, signers,
                                       principal):
                verdict = "authorized"

            packet_holds = False
            proof_recorded = False
            if os.path.isfile(packet_path):
                with open(packet_path, "rb") as f:
                    packet_bytes = f.read()
                packet_holds = hashlib.sha256(packet_bytes).hexdigest() == stmt.get("packet_digest")
                if packet_holds:
                    try:
                        proof_recorded = bool(json.loads(packet_bytes).get("proof"))
                    except json.JSONDecodeError:
                        packet_holds = False

            authorizations.append({"principal": principal, "verdict": verdict,
                                   "packet_holds": packet_holds, "proof_recorded": proof_recorded})
            if not (verdict == "authorized" and packet_holds):
                ok_all = False

    return {"ok": ok_all and bool(authorizations), "root": vr["root"],
            "authorizations": authorizations}
