"""Authoring: sessions become claims (spec/layers.md, "authoring").

A session is a workspace carrying a hook-recorded trace, `TRACE`
(`.reticuli/draft.jsonl`): one JSON object per line -- `prompt`, `write`,
`read`, `bash` events, each optionally timestamped (`ts`). `propose`
(v1: `draft`) reads that trace and infers a draft recipe: files the
session *wrote* become the generated implementation; files only *read*,
or named in a traced shell command and found on disk under their own
exact name, become candidate pinned inputs. `claim=`/`generated=`
override that inference outright, for a hookless session (bash events
only) or one where provenance should not decide class (spec/claim-format.md,
"THE CLAIM BOUNDARY IS DECLARED, NOT INFERRED" -- see the check).

`build_claim` (v1: `condense`) turns a draft into a sealed claim: it
refuses a vacuous gate immediately, then certifies the rest COLD -- the
trace has no authority, so every generated byte is threaded into a fresh
room via `kernel.rebuild`, and the pinned verdict that results must
independently re-earn under `kernel.audit`'s own, separately-built room
before anything is promoted to the caller's destination. Gates only ever
run through `kernel.run_gate` (via `rebuild`/`audit`), which owns the
scrub, the bound, and the sandbox -- this module never reaches for
`kernel.sandbox` itself.
"""
import json
import os
import shutil
import tempfile

from reticuli import _util
from reticuli import kernel
from reticuli import render

TRACE = f"{kernel.STORE}/draft.jsonl"


# ===========================================================================
# Trace reading and the small heuristics `propose` builds a draft from.
# ===========================================================================


def _read_trace(ws: str) -> list:
    path = os.path.join(ws, *TRACE.split("/"))
    if not os.path.isfile(path):
        return []
    events = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                events.append(json.loads(line))
    return events


def _existing_names(ws: str) -> set:
    """Every regular file under `ws`, as its exact-case relative path
    (POSIX-separated), excluding the store -- the directory-entry truth
    a candidate name must match (spec/identity.md, "Identity must not
    depend on the host filesystem"): no case-folded `os.path.isfile`.
    """
    names = set()
    for root, dirs, files in os.walk(ws):
        dirs[:] = [d for d in dirs if d != kernel.STORE]
        for fname in files:
            rel = os.path.relpath(os.path.join(root, fname), ws).replace(os.sep, "/")
            names.add(rel)
    return names


def _gate_commands(trace: list, outputs: list) -> dict:
    """The bash command believed to produce/validate each declared gate
    output: the one traced `bash` event whose text names that output, or
    the session's last bash event otherwise (every case this layer
    exercises traces exactly one).
    """
    cmds = [e.get("cmd") for e in trace if e.get("event") == "bash" and isinstance(e.get("cmd"), str)]
    if not cmds:
        raise kernel.ClaimError("the trace names no bash event to serve as a gate")
    result = {}
    for out in outputs:
        result[out] = next((c for c in cmds if out in c), cmds[-1])
    return result


def propose(ws: str, gate_outputs, name: str, *, claim=None, generated=None) -> dict:
    """A draft recipe inferred from `ws`'s traced session: every `write`
    event's path becomes a generated (implementation) output, every
    `read` event's path or bash-command token that names a real file
    becomes a candidate pinned input, and `gate_outputs` become the gate
    steps. `claim=`/`generated=` override the inferred class of the
    named paths outright. Every trace-derived path is confined to `ws`
    before anything else happens (spec/identity.md): an escaping name
    refuses here, before any byte of it is ever copied.
    """
    ws = os.path.abspath(ws)
    trace = _read_trace(ws)
    outputs = list(gate_outputs)

    written = []
    for e in trace:
        if e.get("event") == "write":
            p = e.get("path")
            if isinstance(p, str):
                full = _util.safe_path(ws, p)
                if os.path.isfile(full) and p not in written:
                    written.append(p)

    read_paths = []
    for e in trace:
        if e.get("event") == "read":
            p = e.get("path")
            if isinstance(p, str):
                full = _util.safe_path(ws, p)
                if os.path.isfile(full) and p not in read_paths:
                    read_paths.append(p)

    existing = _existing_names(ws)
    token_paths = []
    for e in trace:
        if e.get("event") == "bash":
            cmd = e.get("cmd")
            if not isinstance(cmd, str):
                continue
            for tok in cmd.split():
                if tok in existing and tok not in token_paths:
                    token_paths.append(tok)

    claim_set = set(claim) if claim is not None else set()
    generated_set = set(generated) if generated is not None else (set(written) - claim_set)

    for p in claim_set | generated_set:
        if not os.path.isfile(_util.safe_path(ws, p)):
            raise kernel.ClaimError(f"declared path not found in the session: {p!r}")

    auto_inputs = []
    for p in read_paths + token_paths:
        if p in generated_set or p in written or p in outputs:
            continue
        if p not in auto_inputs:
            auto_inputs.append(p)

    inputs = sorted(set(auto_inputs) | claim_set)

    steps = [{"kind": "produce", "output": out, "class": "generated"}
             for out in sorted(generated_set)]
    gate_cmds = _gate_commands(trace, outputs)
    for out in outputs:
        steps.append({"kind": "gate", "output": out, "class": "validated", "run": gate_cmds[out]})

    return {"claim": {"name": name, "inputs": inputs}, "step": steps}


# ===========================================================================
# build_claim: a draft, certified cold, sealed into `rec`.
# ===========================================================================


def _cost_from_trace(trace: list) -> dict:
    """The session's C1: one oracle call per prompt, spanning the
    trace's own earliest-to-latest timestamp.
    """
    calls = sum(1 for e in trace if e.get("event") == "prompt")
    timestamps = [e["ts"] for e in trace
                  if isinstance(e.get("ts"), (int, float)) and not isinstance(e.get("ts"), bool)]
    seconds = (max(timestamps) - min(timestamps)) if timestamps else 0.0
    return {"event": "oracle", "calls": calls, "seconds": seconds}


def build_claim(ws: str, gate_outputs, rec: str, *, name: str, claim=None, generated=None) -> dict:
    """Certify a session's draft cold and seal it at `rec`. Refuses a
    gate every one of whose deciders is itself generated (vacuous,
    spec/claim-format.md) before touching a byte; otherwise threads the
    draft's declared inputs and present generated bytes into a fresh
    room (`kernel.rebuild`), then requires that room's own pinned
    verdict to independently re-earn under `kernel.audit` -- a verdict
    the workspace cannot re-earn cold (a nondeterministic gate) never
    seals. Only on that second, independent pass does anything move to
    `rec`.
    """
    ws = os.path.abspath(ws)
    draft = propose(ws, gate_outputs, name, claim=claim, generated=generated)

    vac = kernel.vacuous_gates(draft)
    if vac:
        raise kernel.ClaimError(
            f"gate(s) {vac} are vacuous: every decider is a generated output")

    cost_entry = _cost_from_trace(_read_trace(ws))

    pre = tempfile.mkdtemp(prefix="pre-")
    staging = tempfile.mkdtemp(prefix="building-")
    try:
        with open(os.path.join(pre, kernel.RECIPE), "w", encoding="utf-8") as f:
            f.write(render.dump_recipe(draft))
        _util.copy_into(ws, pre, draft["claim"]["inputs"])

        produce_from = {
            step["output"]: _util.safe_path(ws, step["output"])
            for step in draft["step"] if step["kind"] == "produce"
        }

        kernel.rebuild(pre, ":", staging, produce_from=produce_from)

        aud = kernel.audit(staging)
        if not aud.get("ok"):
            raise kernel.ClaimError(
                "build_claim must refuse a verdict it cannot re-earn cold")

        kernel.ledger(staging, cost_entry)

        rec_abs = os.path.abspath(rec)
        if os.path.isdir(rec_abs):
            shutil.rmtree(rec_abs)
        os.makedirs(os.path.dirname(rec_abs) or ".", exist_ok=True)
        shutil.move(staging, rec_abs)

        vr = kernel.verify(rec_abs)
        return {"ok": True, "root": vr["root"], "name": vr["name"]}
    finally:
        shutil.rmtree(pre, ignore_errors=True)
        if os.path.isdir(staging):
            shutil.rmtree(staging, ignore_errors=True)
