"""The launcher: run software that exists only latently in a claim
(spec/layers.md, "launcher"; enforced by checks/launcher_check.py).

A runnable claim is an ordinary Reticuli claim whose pinned inputs include
`package.toml` (`[package] entrypoint = "<file>"`). `run` makes the claim
executable -- checking a standing implementation, regrowing one with a
producer, or running whatever is already on disk when the launcher itself
never touched it -- and `strip` deletes the generated bytes back to
latency. Deleting is always safe because the claim's root, not its code,
is the identity (spec/identity.md).

State describing what the launcher has generated or accepted for a claim
lives under `<claim>/.launcher/`, outside the claim's own `.reticuli/`
store and outside its root -- launcher consent is bookkeeping about a
realization, never part of the claim's identity. Two mutually exclusive
records may live there: `fresh.json` (bytes the launcher just regrew, not
yet accepted) and `accepted.json` (bytes a human consented to, by their
digest). Neither is written for an implementation the launcher never
generated or accepted -- "packed by hand" bytes simply run.

Only `reticuli.kernel`'s pinned surface is used here (spec/kernel-api.md);
path confinement and sandbox wrapping are reimplemented to the same rules
(spec/identity.md, spec/claim-format.md) rather than reaching into a
kernel private, the same discipline `reticuli/_util.py` already follows.
"""
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import tomllib

from reticuli import kernel

LAUNCHER_STORE = ".launcher"
_FRESH = "fresh.json"
_ACCEPTED = "accepted.json"

_HELP = """\
reticuli.launcher -- run software that is only latent in a claim

usage:
  python3 -m reticuli.launcher run <claim> [--accept-generated] \
[--signed-only] [--no-sandbox] [-- args...]
  python3 -m reticuli.launcher strip <claim>
  python3 -m reticuli.launcher ls <claim>...
"""


class Refuse(Exception):
    """A launcher refusal: an exit code and a message for stderr."""

    def __init__(self, code: int, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message


def _die(exc: Refuse) -> int:
    sys.stderr.write(f"launcher: {exc.message}\n")
    return exc.code


# ===========================================================================
# Recipe introspection: generated outputs and declared pinned inputs, read
# from the dict `kernel.load_recipe` already parsed and validated.
# ===========================================================================


def _generated_outputs(parsed: dict) -> list:
    return [
        s["output"] for s in parsed.get("step", [])
        if s.get("kind") == "produce" and s.get("class", "generated") == "generated"
    ]


def _declared_inputs(parsed: dict) -> list:
    claim = parsed.get("claim", {})
    manifest = claim.get("inputs_manifest")
    if manifest is not None:
        return [manifest] + list(parsed.get("_manifest_inputs", []))
    return list(claim.get("inputs", []))


# ===========================================================================
# The package contract: package.toml must be a pinned input naming a
# confined entrypoint (THE PACKAGE CONTRACT, checks/launcher_check.py).
# ===========================================================================


def _safe_entry(claim_dir: str, name: str) -> str:
    """Resolve `name` under `claim_dir`, or refuse: no absolute path, no
    `..`/empty component, and the resolved path must stay inside the claim.
    """
    if not isinstance(name, str) or name == "" or os.path.isabs(name):
        raise Refuse(3, f"entrypoint path is invalid: {name!r}")
    parts = name.split("/")
    for part in parts:
        if part in ("", ".", ".."):
            raise Refuse(3, f"entrypoint escapes the claim root: {name!r}")
    base_real = os.path.realpath(claim_dir)
    candidate = os.path.join(base_real, *parts)
    real = os.path.realpath(candidate)
    if real != candidate or not (real == base_real or real.startswith(base_real + os.sep)):
        raise Refuse(3, f"entrypoint escapes the claim root: {name!r}")
    return real


def _check_package(parsed: dict, claim_dir: str):
    """Validate the package contract; return `(entrypoint_rel, entrypoint_abs)`."""
    inputs = _declared_inputs(parsed)
    generated = _generated_outputs(parsed)
    pkg_path = os.path.join(claim_dir, "package.toml")

    if "package.toml" in generated:
        raise Refuse(3, "package.toml must be a pinned input, not a generated output")
    if "package.toml" not in inputs or not os.path.isfile(pkg_path):
        raise Refuse(3, "no pinned package.toml found in the claim")

    try:
        with open(pkg_path, "rb") as f:
            doc = tomllib.load(f)
    except (tomllib.TOMLDecodeError, OSError) as exc:
        raise Refuse(3, f"malformed package.toml: {exc}") from exc

    package = doc.get("package")
    entrypoint = package.get("entrypoint") if isinstance(package, dict) else None
    if not isinstance(entrypoint, str) or entrypoint == "":
        raise Refuse(3, "package.toml needs a [package] entrypoint")

    entry_abs = _safe_entry(claim_dir, entrypoint)
    return entrypoint, entry_abs


# ===========================================================================
# Launcher state: `<claim>/.launcher/{fresh,accepted}.json`, a map of
# generated-output path -> sha256 digest. Consent binds bytes, not a mood.
# ===========================================================================


def _state_dir(claim_dir: str) -> str:
    return os.path.join(claim_dir, LAUNCHER_STORE)


def _digest_outputs(claim_dir: str, generated: list) -> dict:
    digests = {}
    for name in generated:
        path = os.path.join(claim_dir, name)
        if os.path.isfile(path):
            with open(path, "rb") as f:
                digests[name] = hashlib.sha256(f.read()).hexdigest()
    return digests


def _read_state(claim_dir: str):
    d = _state_dir(claim_dir)
    for status, fname in (("accepted", _ACCEPTED), ("fresh", _FRESH)):
        path = os.path.join(d, fname)
        if os.path.isfile(path):
            with open(path, "r", encoding="utf-8") as f:
                digests = json.load(f)
            return {"status": status, "digests": digests}
    return None


def _write_state(claim_dir: str, status: str, digests: dict) -> None:
    d = _state_dir(claim_dir)
    os.makedirs(d, exist_ok=True)
    fname, other = (_ACCEPTED, _FRESH) if status == "accepted" else (_FRESH, _ACCEPTED)
    with open(os.path.join(d, fname), "w", encoding="utf-8") as f:
        json.dump(digests, f, sort_keys=True)
    other_path = os.path.join(d, other)
    if os.path.isfile(other_path):
        os.remove(other_path)


# ===========================================================================
# Regrowing: run the external producer in a scratch room, then land only
# the generated bytes on the claim -- the pinned bytes and the root never
# move (spec/identity.md: generated bytes are outside the root preimage).
# ===========================================================================


def _rebuild_into_claim(claim_dir: str, producer: str, generated: list) -> None:
    tmp = tempfile.mkdtemp(prefix="launcher-rebuild-")
    try:
        kernel.rebuild(claim_dir, producer, tmp)
        for name in generated:
            src = os.path.join(tmp, name)
            if os.path.isfile(src):
                dest = os.path.join(claim_dir, name)
                os.makedirs(os.path.dirname(dest) or claim_dir, exist_ok=True)
                shutil.copy2(src, dest)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


# ===========================================================================
# Execution: scrubbed environment, sandboxed, honest about its quarantine.
# ===========================================================================

_SEATBELT_PROFILE = """(version 1)
(deny default)
(allow process-fork)
(allow process-exec)
(allow file-read*)
(allow file-write* (subpath "{room}"))
(allow file-write* (subpath "{scratch}"))
(allow mach-lookup)
(allow sysctl-read)
"""


def _quote_sb(path: str) -> str:
    return path.replace("\\", "\\\\").replace('"', '\\"')


def _sandbox_argv(backend: str, argv: list, room: str, scratch: str) -> list:
    if backend == "seatbelt":
        profile = _SEATBELT_PROFILE.format(
            room=_quote_sb(os.path.realpath(room)),
            scratch=_quote_sb(os.path.realpath(scratch)),
        )
        return ["sandbox-exec", "-p", profile, *argv]
    if backend == "bubblewrap":
        return [
            "bwrap",
            "--ro-bind", "/", "/",
            "--dev", "/dev",
            "--proc", "/proc",
            "--bind", room, room,
            "--bind", scratch, scratch,
            "--unshare-net",
            "--die-with-parent",
            "--",
            *argv,
        ]
    return list(argv)


def _execute(claim_dir: str, entry_rel: str, entry_args: list, no_sandbox: bool,
             claim_name: str) -> int:
    scratch_root = os.path.join(_state_dir(claim_dir), "scratch")
    os.makedirs(scratch_root, exist_ok=True)
    scratch = tempfile.mkdtemp(prefix="run-", dir=scratch_root)
    try:
        if no_sandbox:
            backend = "off"
        else:
            _, backend = kernel.sandbox()

        env = {k: os.environ[k] for k in ("PATH", "LANG", "LC_ALL", "TZ") if k in os.environ}
        env["HOME"] = scratch
        env["TMPDIR"] = scratch
        if backend in ("seatbelt", "bubblewrap"):
            env["RETICULI_JAILED"] = backend
        elif backend == "inherited":
            prior = os.environ.get("RETICULI_JAILED")
            if prior:
                env["RETICULI_JAILED"] = prior

        try:
            phase = kernel.phase(claim_dir)
        except kernel.ClaimError:
            phase = "draft"

        argv = [sys.executable, entry_rel] + list(entry_args)
        wrapped = _sandbox_argv(backend, argv, claim_dir, scratch)

        sys.stderr.write(
            f'launcher: running {claim_name!r} (phase={phase}); quarantine = "{backend}"\n'
        )
        sys.stderr.flush()
        proc = subprocess.run(wrapped, cwd=claim_dir, env=env, check=False)
        return proc.returncode
    finally:
        shutil.rmtree(scratch, ignore_errors=True)


# ===========================================================================
# Verbs.
# ===========================================================================


def cmd_run(args: list) -> int:
    if not args:
        return _die(Refuse(3, "run requires a claim path"))
    claim_dir = os.path.abspath(args[0])
    rest = args[1:]

    accept = signed_only = no_sandbox = False
    if "--" in rest:
        idx = rest.index("--")
        flags, entry_args = rest[:idx], rest[idx + 1:]
    else:
        flags, entry_args = rest, []
    for flag in flags:
        if flag == "--accept-generated":
            accept = True
        elif flag == "--signed-only":
            signed_only = True
        elif flag == "--no-sandbox":
            no_sandbox = True
        else:
            return _die(Refuse(3, f"unknown option: {flag}"))

    try:
        parsed = kernel.load_recipe(claim_dir)
    except kernel.ClaimError as exc:
        return _die(Refuse(3, str(exc)))

    try:
        entry_rel, entry_abs = _check_package(parsed, claim_dir)
    except Refuse as exc:
        return _die(exc)

    name = parsed.get("claim", {}).get("name", "")
    generated = _generated_outputs(parsed)
    materialized = os.path.isfile(entry_abs) and all(
        os.path.isfile(os.path.join(claim_dir, g)) for g in generated
    )

    if not materialized:
        producer = os.environ.get("RETICULI_PRODUCER")
        if not producer:
            return _die(Refuse(
                7, "claim is latent and no producer is configured; set RETICULI_PRODUCER"
            ))
        try:
            _rebuild_into_claim(claim_dir, producer, generated)
        except kernel.ClaimError as exc:
            return _die(Refuse(1, f"rebuild failed: {exc}"))
        digests = _digest_outputs(claim_dir, generated)
        _write_state(claim_dir, "fresh", digests)
        if not accept:
            sys.stderr.write(
                f"launcher: generated bytes regrown for {name!r}; "
                "pass --accept-generated to execute and accept them\n"
            )
            return 4
        _write_state(claim_dir, "accepted", digests)
    else:
        rec = _read_state(claim_dir)
        if rec is not None:
            digests = _digest_outputs(claim_dir, generated)
            if rec["digests"] != digests:
                verb = "regrown" if rec["status"] == "fresh" else "accepted"
                return _die(Refuse(
                    6, f"the {verb} implementation has drifted from its bytes; "
                    "run `strip` to recover"
                ))
            if rec["status"] == "fresh":
                if not accept:
                    sys.stderr.write(
                        f"launcher: generated bytes for {name!r} are pending "
                        "acceptance; pass --accept-generated to execute and accept them\n"
                    )
                    return 4
                _write_state(claim_dir, "accepted", digests)
        # rec is None: an implementation the launcher never generated or
        # accepted (packed by hand, imported) -- it runs on audit alone.

    if signed_only:
        try:
            phase = kernel.phase(claim_dir)
        except kernel.ClaimError as exc:
            return _die(Refuse(5, f"cannot establish trust: {exc}"))
        if phase != "signed":
            return _die(Refuse(
                5, "claim is not signed to a trusted key; --signed-only refuses it"
            ))

    return _execute(claim_dir, entry_rel, entry_args, no_sandbox, name)


def cmd_strip(args: list) -> int:
    if not args:
        return _die(Refuse(3, "strip requires a claim path"))
    claim_dir = os.path.abspath(args[0])

    try:
        parsed = kernel.load_recipe(claim_dir)
    except kernel.ClaimError as exc:
        return _die(Refuse(3, str(exc)))

    for name in _generated_outputs(parsed):
        path = os.path.join(claim_dir, name)
        if os.path.isfile(path) or os.path.islink(path):
            os.remove(path)

    state_dir = _state_dir(claim_dir)
    if os.path.isdir(state_dir):
        shutil.rmtree(state_dir)

    sys.stderr.write(f"launcher: stripped generated bytes from {claim_dir}\n")
    return 0


def cmd_ls(args: list) -> int:
    if not args:
        sys.stderr.write("launcher: ls requires at least one claim path\n")
        return 3

    lines = []
    for claim_arg in args:
        claim_dir = os.path.abspath(claim_arg)
        try:
            parsed = kernel.load_recipe(claim_dir)
        except kernel.ClaimError as exc:
            lines.append(f"{claim_arg}: refused -- {exc}")
            continue

        name = parsed.get("claim", {}).get("name", "")
        try:
            manifest = kernel.read_manifest(claim_dir)
            root = manifest.get("root", "")
        except kernel.ClaimError:
            root = ""

        try:
            phase = kernel.phase(claim_dir)
        except kernel.ClaimError:
            phase = "draft"

        generated = _generated_outputs(parsed)
        materialized = all(os.path.isfile(os.path.join(claim_dir, g)) for g in generated)
        status = "materialized" if materialized else "latent"
        root_display = root[:12] if root else "-"

        lines.append(f"{name}  {root_display}  {phase}  {status}  {claim_dir}")

    sys.stdout.write("\n".join(lines) + "\n")
    return 0


def _print_help() -> None:
    sys.stdout.write(_HELP)


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if not argv or argv[0] in ("-h", "--help"):
        _print_help()
        return 0

    verb, rest = argv[0], argv[1:]
    if verb == "run":
        return cmd_run(rest)
    if verb == "strip":
        return cmd_strip(rest)
    if verb == "ls":
        return cmd_ls(rest)

    sys.stderr.write(f"launcher: unknown verb {verb!r}\n")
    _print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
