"""Reuse: a verdict cache keyed by identity, build, and host (surface layer).

A cold `audit` re-earns a verdict by re-running every gate on present
bytes -- correct, and O(whole claim) every time. `reuse` lets a caller
skip that cost when nothing could have changed: the fingerprint is the
claim's root (what it is), its build digest (which generated bytes are
actually present), the platform, and the interpreter -- the same four
things an audit's outcome can possibly depend on. Two runs that agree on
all four will re-earn the same verdict, so the second one may reuse the
first's.

A verdict is remembered only when it passed. Caching a failure would let
a transient problem (a flaky gate, a half-written file) poison every
later lookup with a verdict that never re-earns anything; a miss simply
costs what it always cost, a fresh audit. The cache is residue -- stored
under the claim's own store, never hashed into identity.
"""
import hashlib
import json
import os
import platform
import sys
import tempfile

from . import kernel

_RESIDUE = os.path.join(kernel.STORE, "reuse.json")


def fingerprint(d: str) -> dict:
    """The key a verdict is cached under: identity, build, and host --
    root+build+platform+python, the four things an audit's outcome can
    depend on.
    """
    parsed = kernel.load_recipe(d)
    return {
        "root": kernel.root(parsed, d),
        "build": kernel.build_digest(d),
        "platform": sys.platform,
        "python": platform.python_version(),
    }


def _key(fp: dict) -> str:
    blob = json.dumps(fp, sort_keys=True).encode("utf-8")
    return hashlib.sha256(blob).hexdigest()


def _path(d: str) -> str:
    return os.path.join(d, _RESIDUE)


def _load(d: str) -> dict:
    path = _path(d)
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}


def _write(d: str, cache: dict) -> None:
    path = _path(d)
    directory = os.path.dirname(path)
    os.makedirs(directory, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=directory, prefix=".tmp-", suffix=".json")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(cache, f, sort_keys=True)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _passing(verdict) -> bool:
    if not isinstance(verdict, dict) or not verdict.get("ok"):
        return False
    for gate in verdict.get("gates", []):
        if isinstance(gate, dict) and gate.get("status", "ok") != "ok":
            return False
    return True


def remember(d: str, verdict: dict) -> None:
    """Cache `verdict` under `d`'s current fingerprint -- but only when it
    passed. A failing verdict is never recorded.
    """
    if not _passing(verdict):
        return
    cache = _load(d)
    cache[_key(fingerprint(d))] = verdict
    _write(d, cache)


def lookup(d: str):
    """The cached verdict for `d`'s current fingerprint, or `None` on a
    miss -- a different root, different bytes present, or a host that
    never ran this claim before.
    """
    cache = _load(d)
    return cache.get(_key(fingerprint(d)))
