"""Transfer: deterministic tar, verify-on-import, volatile history stays
home (spec/layers.md, "exchange").

`export` packs exactly a claim's declared content -- its recipe, its
pinned inputs, every step output present on disk, its attestation
residue, and (self-contained) every declared component's own claim,
minus that component's generated bytes -- never the ledger, never a
stray file dropped in the claim's own directory. `import_` unpacks it
and immediately re-verifies identity from the received bytes.
"""
import os
import tarfile

from reticuli import _util
from reticuli import kernel

_DEPS_PREFIX = f"{kernel.STORE}/deps/"
_SEALED_PREFIX = f"{kernel.STORE}/sealed/"
_ATTEST_DIR = f"{kernel.STORE}/attest"


def _claim_files(d: str, blind: bool) -> set:
    """The declared file names of the claim at `d`: its recipe, its
    pinned inputs, and every step output present on disk -- `blind`
    withholds every GENERATED produce step's output (spec/identity.md:
    exactly the bytes a rebuilder is asked to regrow).
    """
    parsed = kernel.load_recipe(d)
    names = {_util.recipe_name(d)}
    names.update(_util.declared_inputs(parsed))
    for step in parsed.get("step", []):
        output = step["output"]
        if blind and step.get("kind") == "produce" and step.get("class", "generated") == "generated":
            continue
        if os.path.isfile(os.path.join(d, output)):
            names.add(output)
    return names


def _add(tar: tarfile.TarFile, arcname: str, path: str) -> None:
    info = tar.gettarinfo(path, arcname=arcname)
    info.mtime = 0
    info.uid = 0
    info.gid = 0
    info.uname = ""
    info.gname = ""
    info.mode = 0o644
    with open(path, "rb") as f:
        tar.addfile(info, f)


def export(d: str, tar_path: str, blind: bool = False) -> dict:
    """Pack `d`'s declared content into a deterministic tar at
    `tar_path`. `blind` withholds every generated output -- the room a
    rebuilder is handed.
    """
    entries = {}
    for name in _claim_files(d, blind):
        entries[name] = os.path.join(d, name)

    if os.path.isfile(os.path.join(d, kernel.MANIFEST)):
        entries[kernel.MANIFEST] = os.path.join(d, kernel.MANIFEST)

    attest_abs = os.path.join(d, _ATTEST_DIR)
    if os.path.isdir(attest_abs):
        for root_dir, _dirs, files in os.walk(attest_abs):
            for fname in files:
                full = os.path.join(root_dir, fname)
                rel = os.path.relpath(full, d).replace(os.sep, "/")
                entries[rel] = full

    try:
        manifest = kernel.read_manifest(d)
    except kernel.ClaimError:
        manifest = {}
    for link in manifest.get("components", []):
        comp_name = link["component"]
        comp_dir = os.path.join(d, kernel.STORE, "sealed", comp_name)
        if not os.path.isdir(comp_dir):
            continue
        comp_names = _claim_files(comp_dir, blind=True)
        if os.path.isfile(os.path.join(comp_dir, kernel.MANIFEST)):
            comp_names.add(kernel.MANIFEST)
        for name in comp_names:
            entries[f"{_DEPS_PREFIX}{comp_name}/{name}"] = os.path.join(comp_dir, name)

    with tarfile.open(tar_path, "w") as tar:
        for arcname in sorted(entries):
            _add(tar, arcname, entries[arcname])
    return {"path": tar_path, "count": len(entries)}


def import_(tar_path: str, into: str) -> dict:
    """Unpack `tar_path` into `into` (a component's bundled `deps/<name>`
    subtree lands back at `sealed/<name>`) and verify identity
    immediately from the received bytes.
    """
    into_abs = os.path.abspath(into)
    os.makedirs(into_abs, exist_ok=True)

    with tarfile.open(tar_path, "r") as tar:
        members = tar.getmembers()
        for m in members:
            if os.path.isabs(m.name) or ".." in m.name.split("/"):
                raise kernel.ClaimError(f"refusing unsafe tar member {m.name!r}")
        for m in members:
            arcname = m.name
            if arcname.startswith(_DEPS_PREFIX):
                rest = arcname[len(_DEPS_PREFIX):]
                comp_name, _, tail = rest.partition("/")
                dest_rel = f"{_SEALED_PREFIX}{comp_name}/{tail}"
            else:
                dest_rel = arcname
            dest_path = os.path.join(into_abs, dest_rel)
            os.makedirs(os.path.dirname(dest_path), exist_ok=True)
            src = tar.extractfile(m)
            with open(dest_path, "wb") as f:
                f.write(src.read())

    try:
        vr = kernel.verify(into_abs)
        ok, root = vr["ok"], vr["root"]
    except kernel.ClaimError:
        ok, root = False, None
    return {"ok": ok, "root": root}
