"""reticuli.assess -- measuring how much a claim's tests prove (spec/layers.md).

Passing the gates says a claim's criteria are SATISFIED; it says nothing
about how much they would have caught if the generated bytes were wrong.
Mutation testing asks that second question directly (`kernel.mutation_score`,
spec/verification.md): every generated Python output is perturbed and
re-judged, and a mutant the gates fail to kill is a hole in the acceptance
criteria, not a bug in the implementation.

`assess` buckets each generated output by whether that question was actually
asked of it:

- `measured`       -- a generated `.py` output present on disk, and the
                       mutation sample drawn for this claim was non-empty.
- `not_measured`    -- a generated `.py` output present on disk, but the
                       sample came back empty (raise `mutants`, or the file
                       has nothing left to mutate).
- `not_applicable`  -- not a generated Python file, or not present at all;
                       mutation testing has nothing to ask of it.
"""
import os

from reticuli import kernel


def _generated_outputs(parsed: dict) -> list:
    """Every `produce` step's output name, in recipe order."""
    outputs = []
    for step in parsed.get("step", []):
        if step.get("kind") != "produce":
            continue
        output = step.get("output")
        cls = step.get("class")
        if cls is None:
            cls = "generated"
        if cls == "generated" and isinstance(output, str):
            outputs.append(output)
    return outputs


def assess(d: str, mutants: int = 50) -> dict:
    """Bucket `d`'s generated outputs by whether mutation testing measured
    them, drawing at most `mutants` mutants (spec/verification.md:
    `mutation_floor`, `kernel.mutation_score`)."""
    parsed = kernel.load_recipe(d)
    score = kernel.mutation_score(d, max_mutants=mutants)

    measured, not_measured, not_applicable = [], [], []
    for output in _generated_outputs(parsed):
        full = os.path.join(d, output)
        if not output.endswith(".py") or not os.path.isfile(full):
            not_applicable.append(output)
        elif score["mutants"] > 0:
            measured.append(output)
        else:
            not_measured.append(output)

    return {
        "measured": measured,
        "not_measured": not_measured,
        "not_applicable": not_applicable,
        "mutation_score": score,
        "vacuous_gates": kernel.vacuous_gates(parsed),
    }
