"""reticuli.launcher -- run software that exists only latently in a claim
(spec/layers.md: the launcher layer; checks/launcher_check.py is this
module's definition).

A runnable claim is an ordinary claim whose pinned inputs include
`package.toml` (`[package] entrypoint = "..."`). `run` checks a cached
build or regrows a fresh one with a producer, then executes the
entrypoint; `strip` deletes the generated bytes back to latency; `ls`
reports identity, phase, and whether an implementation is on hand.

State -- which generated bytes the launcher has itself produced and which
of those a human has accepted -- lives under `<claim>/.launcher/` as two
small digest maps: `fresh.json` (landed, awaiting --accept-generated) and
`accepted.json` (consented to; drift is a mismatch against this map).
Bytes present that the launcher never wrote either file for are
"unmanaged" (packed by hand) and run on a fresh `kernel.audit` alone,
since there is no consent record to check them against.
"""
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
import tomllib

from reticuli import kernel
from reticuli import _util as util

LAUNCH_DIR = ".launcher"
FRESH_FILE = "fresh.json"
ACCEPTED_FILE = "accepted.json"
PACKAGE_FILE = "package.toml"
EXEC_TIMEOUT = 120.0

_KEEP_ENV = ("PATH", "LANG", "LC_ALL", "TZ")

HELP = """\
reticuli.launcher -- run software that is only latent in a claim

usage:
  python3 -m reticuli.launcher run   <claim> [--accept-generated] [--signed-only] [--no-sandbox] [-- args...]
  python3 -m reticuli.launcher strip <claim>
  python3 -m reticuli.launcher ls    <claim>...

verbs:
  run    materialize (or check) the implementation and execute its entrypoint
  strip  delete the generated bytes, keep the claim latent
  ls     list a claim's name, root, phase, and whether it is materialized

flags (run):
  --accept-generated  consent to execute and accept freshly regrown bytes
  --signed-only       refuse to run a claim that is not signed to you
  --no-sandbox        run the entrypoint unconfined (reports quarantine = "off")

exit codes:
  0  the entrypoint ran; this is its own exit code
  3  not runnable (no/unpinned package.toml, escaping entrypoint or path)
  4  newly generated bytes, consent required (pass --accept-generated)
  5  trust refused (--signed-only on a claim not signed to you)
  6  drifted build (an accepted implementation's bytes changed); strip to recover
  7  latent and no producer configured (set RETICULI_PRODUCER)
"""


class LauncherRefusal(Exception):
    """Not runnable: the package contract or a path confinement rule failed."""


def _stderr(text: str) -> None:
    sys.stderr.write(text.rstrip("\n") + "\n")


# -- the recipe's step list, read through the public kernel surface -------

def _generated_outputs(parsed: dict) -> list:
    outputs = []
    for step in parsed.get("step", []):
        if step.get("kind") != "produce" or step.get("from"):
            continue
        output, cls = util.step_output(step)
        if cls == "generated" and isinstance(output, str):
            outputs.append(output)
    return outputs


def _confined(d: str, names) -> dict:
    """Every name resolved inside `d`; a climbing or absolute name refuses
    with a reason before anything is read, written, or deleted."""
    result = {}
    for name in names:
        try:
            result[name] = util.safe_path(d, name)
        except kernel.ClaimError as e:
            raise LauncherRefusal(f"refused generated path {name!r}: {e}") from e
    return result


# -- the package contract --------------------------------------------------

def _package_contract(d: str, parsed: dict):
    """Validate the pinned `package.toml` and its entrypoint; return
    `(entrypoint, generated_outputs)`."""
    generated = _generated_outputs(parsed)
    if PACKAGE_FILE in generated:
        raise LauncherRefusal(
            f"{PACKAGE_FILE} must be a pinned input, not a generated output"
        )
    try:
        declared = set(util.declared_inputs(d))
    except kernel.ClaimError as e:
        raise LauncherRefusal(str(e)) from e
    package_path = os.path.join(d, PACKAGE_FILE)
    if PACKAGE_FILE not in declared or not os.path.isfile(package_path):
        raise LauncherRefusal(f"no pinned {PACKAGE_FILE} found in the claim")

    try:
        with open(package_path, "rb") as f:
            doc = tomllib.load(f)
    except (OSError, tomllib.TOMLDecodeError) as e:
        raise LauncherRefusal(f"cannot read {PACKAGE_FILE}: {e}") from e

    entrypoint = doc.get("package", {}).get("entrypoint") if isinstance(doc, dict) else None
    if not isinstance(entrypoint, str) or not entrypoint:
        raise LauncherRefusal(f"{PACKAGE_FILE} has no [package] entrypoint")

    try:
        util.safe_path(d, entrypoint)
    except kernel.ClaimError as e:
        raise LauncherRefusal(f"entrypoint {entrypoint!r} escapes the claim root") from e

    return entrypoint, generated


# -- freshness / drift state, under <claim>/.launcher/ ---------------------

def _state_paths(d: str):
    base = os.path.join(d, LAUNCH_DIR)
    return os.path.join(base, FRESH_FILE), os.path.join(base, ACCEPTED_FILE)


def _digests(paths: dict) -> dict:
    return {name: util.hash_bytes(full) for name, full in paths.items() if os.path.isfile(full)}


def _determine_state(d: str, generated: list):
    """`(status, current_digests)`; status is one of `latent`, `fresh`,
    `accepted`, `drift`, `unmanaged`."""
    paths = _confined(d, generated)
    if not paths or not all(os.path.isfile(p) for p in paths.values()):
        return "latent", {}

    current = _digests(paths)
    fresh_path, accepted_path = _state_paths(d)
    if os.path.isfile(fresh_path):
        fresh = util.read_json(fresh_path)
        return ("fresh" if fresh == current else "drift"), current
    if os.path.isfile(accepted_path):
        accepted = util.read_json(accepted_path)
        return ("accepted" if accepted == current else "drift"), current
    return "unmanaged", current


def _land(d: str, producer: str, generated: list) -> None:
    """Regrow `generated` with `producer` and land the bytes on `d`,
    recording them as fresh -- awaiting consent."""
    room = tempfile.mkdtemp(prefix="reticuli-launcher-")
    try:
        kernel.rebuild(d, producer, room)
        fresh = {}
        for name in generated:
            src = util.safe_path(room, name)
            if not os.path.isfile(src):
                continue
            dst = util.safe_path(d, name)
            os.makedirs(os.path.dirname(dst) or d, exist_ok=True)
            shutil.copy2(src, dst)
            fresh[name] = util.hash_bytes(dst)
        fresh_path, _ = _state_paths(d)
        os.makedirs(os.path.dirname(fresh_path), exist_ok=True)
        util.write_json(fresh_path, fresh)
    finally:
        shutil.rmtree(room, ignore_errors=True)


def _accept(d: str, generated: list) -> None:
    """Record the present bytes' digests as consented to; consent binds
    bytes, not a mood."""
    paths = _confined(d, generated)
    current = _digests(paths)
    fresh_path, accepted_path = _state_paths(d)
    os.makedirs(os.path.dirname(accepted_path), exist_ok=True)
    util.write_json(accepted_path, current)
    if os.path.isfile(fresh_path):
        os.remove(fresh_path)


# -- execution: scrubbed environment, sandboxed by default -----------------

def _scrubbed_env(d: str) -> dict:
    env = {k: os.environ[k] for k in _KEEP_ENV if k in os.environ}
    env.setdefault("PATH", "/usr/bin:/bin:/usr/sbin:/sbin")
    scratch = os.path.join(d, LAUNCH_DIR, "scratch")
    os.makedirs(scratch, exist_ok=True)
    env["HOME"] = scratch
    env["TMPDIR"] = scratch
    return env


def _run_entrypoint(d: str, entrypoint: str, args, no_sandbox: bool):
    """`(returncode, stdout, stderr, quarantine)`."""
    if no_sandbox:
        env = _scrubbed_env(d)
        try:
            done = subprocess.run(
                [sys.executable, entrypoint, *args], cwd=d, env=env,
                capture_output=True, text=True, timeout=EXEC_TIMEOUT, check=False,
            )
            return done.returncode, done.stdout, done.stderr, "off"
        except subprocess.TimeoutExpired as e:
            return 1, e.stdout or "", (e.stderr or "") + "\ntimed out", "off"

    command = " ".join(shlex.quote(part) for part in (sys.executable, entrypoint, *args))
    res, backend = kernel.sandbox(command, d)
    return res["returncode"], res["stdout"], res["stderr"], backend


# -- `run` -------------------------------------------------------------

def _parse_run_args(rest):
    claim = None
    accept_generated = False
    signed_only = False
    no_sandbox = False
    entry_args = []
    i = 0
    while i < len(rest):
        a = rest[i]
        if a == "--":
            entry_args = list(rest[i + 1:])
            break
        if a == "--accept-generated":
            accept_generated = True
        elif a == "--signed-only":
            signed_only = True
        elif a == "--no-sandbox":
            no_sandbox = True
        elif claim is None:
            claim = a
        else:
            raise LauncherRefusal(f"unexpected argument: {a!r}")
        i += 1
    if claim is None:
        raise LauncherRefusal("run requires a claim path")
    return claim, accept_generated, signed_only, no_sandbox, entry_args


def cmd_run(rest) -> int:
    try:
        claim, accept_generated, signed_only, no_sandbox, entry_args = _parse_run_args(rest)
    except LauncherRefusal as e:
        _stderr(f"not runnable: {e}")
        return 3

    d = os.path.abspath(claim)
    try:
        parsed = kernel.load_recipe(d)
    except kernel.ClaimError as e:
        _stderr(f"not runnable: {e}")
        return 3

    try:
        entrypoint, generated = _package_contract(d, parsed)
    except LauncherRefusal as e:
        _stderr(f"not runnable: {e}")
        return 3

    if signed_only:
        try:
            ph = kernel.phase(d)
        except kernel.ClaimError as e:
            _stderr(f"not runnable: {e}")
            return 3
        if ph != "signed":
            _stderr(f"refused: --signed-only requires a signed claim; phase is {ph!r}")
            return 5

    try:
        status, _current = _determine_state(d, generated)
    except LauncherRefusal as e:
        _stderr(f"not runnable: {e}")
        return 3

    if status == "latent":
        producer = os.environ.get("RETICULI_PRODUCER")
        if not producer:
            _stderr(
                "latent claim and no producer configured; "
                "set RETICULI_PRODUCER to regrow it"
            )
            return 7
        try:
            _land(d, producer, generated)
        except kernel.ClaimError as e:
            _stderr(f"producer could not earn the gate: {e}")
            return 1
        status = "fresh"

    if status == "fresh":
        if not accept_generated:
            _stderr(
                "freshly generated implementation is not yet accepted; "
                "pass --accept-generated to execute and accept it"
            )
            return 4
        _accept(d, generated)
        status = "accepted"

    elif status == "drift":
        _stderr(
            "drifted build: an accepted implementation's bytes changed; "
            f"run `python3 -m reticuli.launcher strip {claim}` to recover"
        )
        return 6

    elif status == "unmanaged":
        try:
            verdict = kernel.audit(d)
        except kernel.ClaimError as e:
            _stderr(f"not runnable: {e}")
            return 3
        if not verdict.get("ok"):
            _stderr(
                "implementation does not re-earn its own gate; "
                f"run `python3 -m reticuli.launcher strip {claim}` to recover"
            )
            return 6

    rc, out, err, quarantine = _run_entrypoint(d, entrypoint, entry_args, no_sandbox)

    try:
        ph = kernel.phase(d)
        name = parsed.get("claim", {}).get("name", "")
    except kernel.ClaimError:
        ph, name = "sealed", ""
    _stderr(f'reticuli: running {name!r} phase={ph} quarantine = "{quarantine}"')
    if err:
        _stderr(err)

    sys.stdout.write(out)
    sys.stdout.flush()
    return rc


# -- `strip` -------------------------------------------------------------

def cmd_strip(rest) -> int:
    if not rest:
        _stderr("strip requires a claim path")
        return 3
    d = os.path.abspath(rest[0])
    try:
        parsed = kernel.load_recipe(d)
    except kernel.ClaimError as e:
        _stderr(f"not runnable: {e}")
        return 3

    generated = _generated_outputs(parsed)
    try:
        paths = _confined(d, generated)
    except LauncherRefusal as e:
        _stderr(f"not runnable: {e}")
        return 3

    for full in paths.values():
        if os.path.isfile(full) or os.path.islink(full):
            os.remove(full)

    launch_dir = os.path.join(d, LAUNCH_DIR)
    if os.path.isdir(launch_dir):
        shutil.rmtree(launch_dir)
    return 0


# -- `ls` -------------------------------------------------------------

def cmd_ls(rest) -> int:
    if not rest:
        _stderr("ls requires at least one claim path")
        return 3

    lines = []
    for claim in rest:
        d = os.path.abspath(claim)
        try:
            parsed = kernel.load_recipe(d)
            manifest = kernel.read_manifest(d)
            ph = kernel.phase(d)
        except kernel.ClaimError as e:
            lines.append(f"{claim}: error: {e}")
            continue

        name = manifest.get("name", "")
        root = manifest.get("root", "")
        generated = _generated_outputs(parsed)
        try:
            paths = _confined(d, generated)
        except LauncherRefusal:
            paths = {}
        materialized = bool(paths) and all(os.path.isfile(p) for p in paths.values())
        state_word = "materialized" if materialized else "latent"
        lines.append(f"{name}  {root[:8]}  phase={ph}  {state_word}")

    sys.stdout.write("\n".join(lines) + "\n")
    return 0


# -- entry point -------------------------------------------------------------

def main(argv) -> int:
    if not argv or argv[0] in ("--help", "-h"):
        _stderr(HELP)
        return 0

    verb, rest = argv[0], argv[1:]
    try:
        if verb == "run":
            return cmd_run(rest)
        if verb == "strip":
            return cmd_strip(rest)
        if verb == "ls":
            return cmd_ls(rest)
    except Exception as e:  # a refusal with a reason, never a raw traceback
        _stderr(f"launcher error: {e}")
        return 1

    _stderr(f"unknown verb: {verb!r}\n\n{HELP}")
    return 3


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
