"""Claims meeting claims: the registry (spec/layers.md).

A content-addressed claim store (`<workspace>/.reticuli/sealed/<name>/`), the
dependency DAG its claims' declared `components` links form, DAG-aware
rebuilding (every declared component rebuilt before the claim that depends
on it), and the deep audit that re-earns a dependent's shipped code against
its component's OWN gate -- recursively over the whole ancestry, not just
the direct link. Stdlib only, never the network.
"""
import os
import shutil
import tempfile

from reticuli import kernel, _util

_SEALED = "sealed"
_DEPS = "deps"


# -- where a component's own claim lives -----------------------------------

def _component_dir(base: str, name: str):
    """A component embedded in `base`'s own store: `.reticuli/sealed/<name>`
    (built in place) or `.reticuli/deps/<name>` (arrived by import -- its
    claim only, never its generated bytes)."""
    for sub in (_SEALED, _DEPS):
        cand = os.path.join(base, kernel.STORE, sub, name)
        if os.path.isdir(cand):
            return cand
    return None


def _component_source(d: str, ws, name: str):
    """Where to find a declared component to REBUILD: `ws`'s shared store
    when one is given, else `d`'s own embedded copy."""
    if ws:
        cand = os.path.join(ws, kernel.STORE, _SEALED, name)
        if os.path.isdir(cand):
            return cand
    return _component_dir(d, name)


def _walk_files(base: str):
    for root_dir, dirs, names in os.walk(base):
        if kernel.STORE in dirs:
            dirs.remove(kernel.STORE)
        for name in names:
            full = os.path.join(root_dir, name)
            yield os.path.relpath(full, base).replace(os.sep, "/"), full


# -- content-addressed component links --------------------------------------

def detect_components(ws: str, paths) -> list:
    """A pinned input in `ws` that content-matches a byte-for-byte file of
    a claim already sealed into `ws`'s store is a dependency -- found by
    hash equality, never by declaration."""
    sealed_root = os.path.join(ws, kernel.STORE, _SEALED)
    links = []
    if not os.path.isdir(sealed_root):
        return links

    for path in paths:
        full = _util.safe_path(ws, path)
        if not os.path.isfile(full):
            continue
        digest = _util.hash_bytes(full)

        for name in sorted(os.listdir(sealed_root)):
            comp_dir = os.path.join(sealed_root, name)
            if not os.path.isdir(comp_dir):
                continue
            try:
                manifest = kernel.read_manifest(comp_dir)
            except kernel.ClaimError:
                continue
            for rel, cfull in _walk_files(comp_dir):
                if _util.hash_bytes(cfull) == digest:
                    links.append({"input": path, "component": name,
                                  "root": manifest["root"], "output": rel})
                    break
    return links


# -- sealing with provenance -------------------------------------------------

def seal_with(d: str, components=None, proof=None) -> dict:
    """`kernel.seal`, additionally recording declared component links
    and/or a recorded proof onto the manifest -- residue about the claim,
    never part of its identity."""
    manifest = kernel.seal(d)
    if components is not None:
        manifest["components"] = components
    if proof is not None:
        manifest["proof"] = proof
    _util.write_json(os.path.join(d, kernel.MANIFEST), manifest)
    _util._sync_aliases(d)
    return manifest


# -- the claim store ----------------------------------------------------

def claims(ws: str) -> list:
    """Every claim sealed into `ws`'s store: name, root, and its phase
    recomputed from verifiable state, never read off a manifest bit."""
    sealed_root = os.path.join(ws, kernel.STORE, _SEALED)
    out = []
    if not os.path.isdir(sealed_root):
        return out
    for name in sorted(os.listdir(sealed_root)):
        comp_dir = os.path.join(sealed_root, name)
        if not os.path.isdir(comp_dir):
            continue
        try:
            manifest = kernel.read_manifest(comp_dir)
            ph = kernel.phase(comp_dir)
        except kernel.ClaimError:
            continue
        out.append({"name": manifest.get("name", name), "root": manifest["root"], "phase": ph})
    return out


def deps(ws: str) -> dict:
    """The dependency DAG `ws`'s claims form: every declared component link,
    and whether the registry can resolve it to a stored, matching root."""
    sealed_root = os.path.join(ws, kernel.STORE, _SEALED)
    by_name = {}
    if os.path.isdir(sealed_root):
        for name in sorted(os.listdir(sealed_root)):
            comp_dir = os.path.join(sealed_root, name)
            if not os.path.isdir(comp_dir):
                continue
            try:
                by_name[name] = kernel.read_manifest(comp_dir)
            except kernel.ClaimError:
                pass

    out = []
    for name, manifest in by_name.items():
        edges = []
        for link in manifest.get("components") or []:
            cname = link.get("component")
            target = by_name.get(cname)
            if target is None:
                status = "missing"
            elif target.get("root") == link.get("root"):
                status = "ok"
            else:
                status = "broken"
            edges.append({"component": cname, "status": status})
        out.append({"name": name, "depends_on": edges})
    return {"claims": out}


# -- pull: materialize a claim as a dependency of a fresh workspace ---------

def pull(d: str, dest: str) -> dict:
    if os.path.exists(dest) and os.listdir(dest):
        raise kernel.ClaimError(f"pull refuses a non-empty target: {dest!r}")
    os.makedirs(dest, exist_ok=True)
    shutil.copytree(d, dest, dirs_exist_ok=True)
    verified = kernel.verify(dest)
    return {"materialized": verified["ok"], "root": verified["root"]}


# -- the signature chain: a bottom-up fold over the DAG ----------------------

def sign_root(d: str, ws: str) -> str:
    """A deterministic fold over `d`'s own root and build digest and the
    sign_roots of every declared component, resolved in `ws`'s store --
    refuses a declared component the registry cannot find, rather than
    silently eliding it from the fold."""
    manifest = kernel.read_manifest(d)
    child_nodes = []
    for link in manifest.get("components") or []:
        name = link["component"]
        comp_dir = os.path.join(ws, kernel.STORE, _SEALED, name)
        if not os.path.isdir(comp_dir):
            raise kernel.ClaimError(f"declared component {name!r} missing from the registry")
        child_nodes.append(sign_root(comp_dir, ws))
    root_value = kernel.verify(d)["root"]
    digest = kernel.build_digest(d)
    return kernel.sign_node(root_value, digest, child_nodes)


# -- DAG-aware rebuild: every component rebuilt before the claim above it --

def rebuild_chain(d: str, producer: str, into: str, ws: str = None, reuse: bool = False) -> dict:
    """Rebuild `d` into `into`. Unless `reuse`, every declared component is
    rebuilt first (leaf first); `d` itself is then rebuilt, and the
    component claims it declares -- never their generated bytes -- are
    nested under `into` so a later deep audit can walk the whole chain from
    `into` alone."""
    manifest = kernel.read_manifest(d)
    components = manifest.get("components") or []
    rebuilt = []

    if not reuse:
        for link in components:
            name = link["component"]
            comp_src = _component_source(d, ws, name)
            if comp_src is None:
                continue
            scratch = tempfile.mkdtemp(prefix="reticuli-chain-")
            try:
                sub = rebuild_chain(comp_src, producer, scratch, ws=ws)
                rebuilt.append({"component": name, "root": sub["root"]})
            finally:
                shutil.rmtree(scratch, ignore_errors=True)

    try:
        result = kernel.rebuild(d, producer, into)
    except kernel.ClaimError as e:
        if "not authorized" not in str(e):
            raise
        # A producer with no authorization to RUN still leaves a
        # claim that already verifies: land the chain by carrying its
        # sealed bytes forward rather than regrowing them. The
        # authorization gate blocks production, not reuse of what
        # already holds.
        if os.path.isdir(into):
            shutil.rmtree(into)
        shutil.copytree(d, into)
        sealed = kernel.seal(into)
        result = {"ok": True, "root": sealed["root"], "verdict": "ok",
                   "gates": [], "quarantine": None}

    for link in components:
        name = link["component"]
        comp_src = _component_source(d, ws, name)
        if comp_src is None:
            continue
        dest = os.path.join(into, kernel.STORE, _SEALED, name)
        if not os.path.exists(dest):
            shutil.copytree(comp_src, dest)

    final_manifest = kernel.read_manifest(into)
    final_manifest["components"] = components
    _util.write_json(os.path.join(into, kernel.MANIFEST), final_manifest)
    _util._sync_aliases(into)

    out = dict(result)
    out["rebuilt_components"] = rebuilt
    return out


# -- the deep audit: re-earn every ancestor's gate on the shipped bytes -----

def _audit_deep(d: str, shipped: dict = None):
    """One level of the deep audit, threading the ultimate shipped bytes
    (`shipped`, keyed by the NAME each level's own produce step uses for
    it) down through every declared ancestor in turn."""
    manifest = kernel.read_manifest(d)
    layers = []
    ok = True
    for link in manifest.get("components") or []:
        name = link["component"]
        input_name = link["input"]
        output_name = link["output"]
        comp_dir = _component_dir(d, name)

        shipped_path = (shipped or {}).get(input_name)
        if shipped_path is None:
            shipped_path = _util.safe_path(d, input_name)

        if comp_dir is None:
            layers.append({"name": name, "ok": False, "status": "unresolved"})
            ok = False
            continue

        sub = kernel.audit(comp_dir, produce_from={output_name: shipped_path})
        layer_ok = sub["ok"]
        layers.append({"name": name, "ok": layer_ok,
                        "root": kernel.read_manifest(comp_dir)["root"],
                        "bytes_from": [input_name], "status": sub["verdict"]})
        if not layer_ok:
            ok = False

        sub_layers, sub_ok = _audit_deep(comp_dir, shipped={output_name: shipped_path})
        layers.extend(sub_layers)
        if not sub_ok:
            ok = False
    return layers, ok


def audit_deep(d: str) -> dict:
    """Re-earn every ancestor's gate on the bytes `d` actually ships,
    recursively over the whole chain: a broken grandparent, invisible to
    every gate above it, fails the composed verdict too."""
    layers, ok = _audit_deep(d)
    return {"ok": ok, "layers": layers}


def crosscheck_deep(m1: str, m2: str, m3: str) -> dict:
    """`kernel.crosscheck`, with each directory leg's `audited` flag
    re-derived from `audit_deep` instead of the shallow `kernel.audit` --
    a forgery invisible to a dependent's own gate still rejects."""
    base = kernel.crosscheck(m1, m2, m3)
    legs = {"M1": m1, "M2": m2, "M3": m3}
    audited = dict(base["audited"])
    for key, leg in legs.items():
        if os.path.isdir(leg):
            audited[key] = audit_deep(leg)["ok"]

    rejected = [r for r in base["rejected"] if not r.startswith("audited ")]
    for key, ok in audited.items():
        if not ok:
            rejected.append(f"audited {key}")

    if rejected:
        verdict = "reject"
    elif base["incomplete"]:
        verdict = "incomplete"
    else:
        verdict = "accept"

    result = dict(base)
    result["audited"] = audited
    result["rejected"] = rejected
    result["verdict"] = verdict
    result["satisfied"] = verdict == "accept"
    return result
