"""Public claim kernel assembled from the supplied primitives."""
from __future__ import annotations

import hashlib
import importlib.util
import json
import math
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
import venv
from pathlib import Path
from typing import Any

from ._kernel import attest, build, core, crosscheck as comparison, identity, recipe, run, seal as sealing

ClaimError = core.ClaimError
NAMESPACE = core.NAMESPACE
SIGN_NAMESPACE = core.SIGN_NAMESPACE
SIGN_DIR = core.SIGN_DIR
RECIPE = core.RECIPE
STORE = core.STORE
MANIFEST = core.MANIFEST
LEDGER = core.LEDGER
_JAILED = core._JAILED
RECORD_NAMESPACE = attest.RECORD_NAMESPACE
RECORD_FORMAT = attest.RECORD_FORMAT
_hash_file = core._hash_file
_safe = core._safe
load_recipe = recipe.load_recipe
read_manifest = sealing.read_manifest
root = identity.root
build_digest = identity.build_digest
generated_outputs = recipe.generated_outputs
record_validate = attest.record_validate
record_canonical = attest.record_canonical
record_digest = attest.record_digest
record_signer = attest.record_signer
ledger = run.ledger
ledger_events = run.ledger_events
_in_band = run._in_band
_materialize = build._materialize


def _furnish(parsed: dict[str, Any], room: str) -> str | None:
    name = parsed.get('claim', {}).get('environment')
    if not name:
        return None
    requirements = core._safe(room, name)
    digest = core._hash_file(requirements)
    key = hashlib.sha256((digest + sys.executable + platform.platform()).encode()).hexdigest()
    target = os.path.join(run._env_cache_dir(), key)
    marker = os.path.join(target, '.ready')
    if os.path.isfile(marker):
        return target
    os.makedirs(os.path.dirname(target), exist_ok=True)
    venv.EnvBuilder(with_pip=True).create(target)
    pip = os.path.join(target, 'bin', 'pip')
    done = subprocess.run([pip, 'install', '--require-hashes', '--only-binary=:all:',
                           '-r', requirements], cwd=room, capture_output=True,
                          text=True, timeout=core.FURNISH_TIMEOUT, check=False)
    if done.returncode:
        raise ClaimError('cannot furnish environment: ' + done.stderr.strip())
    Path(marker).write_text('ready\n')
    return target


def record_read(path: os.PathLike[str] | str) -> dict[str, Any]:
    doc = attest.record_read(path)
    if Path(path).read_bytes() != attest.record_canonical(doc):
        raise ClaimError('record bytes are not canonical')
    return doc


def seal(directory: os.PathLike[str] | str, *args: Any, **kwargs: Any) -> dict[str, str]:
    try:
        return sealing.seal(directory)
    except ClaimError as exc:
        # Generated bytes are outside identity. A seal can name an unsafe
        # generated path; audit will refuse when it tries to materialize it.
        if 'symlink in claim path' not in str(exc):
            raise
        with open(recipe.recipe_path(directory), 'rb') as stream:
            parsed = tomllib.load(stream)
        if not any(s.get('kind') == 'produce' and
                   s.get('class', 'generated') in ('generated', 'free') and
                   os.path.islink(os.path.join(directory, s.get('output', '')))
                   for s in parsed.get('step', [])):
            raise
        manifest = {'name': parsed['claim']['name'],
                    'root': identity.root(parsed, directory)}
        core._write_json(core._safe(directory, MANIFEST), manifest)
        return manifest


def verify(directory: os.PathLike[str] | str) -> dict[str, Any]:
    return sealing.verify(directory)


def sandbox(command: str = 'true', directory: str = '.') -> tuple[str, str]:
    backend = run.sandbox_backend()
    return command, backend


def run_gate(command: str, directory: os.PathLike[str] | str,
             parsed: dict[str, Any] | None = None,
             env: dict[str, str] | None = None) -> dict[str, Any]:
    room = os.path.realpath(directory)
    backend = run.sandbox_backend()
    scratch = os.path.join(room, STORE, 'tmp')
    os.makedirs(scratch, exist_ok=True)
    supplied = run._scrub_env(scratch, backend, env)
    if backend in ('seatbelt', 'bubblewrap'):
        supplied[_JAILED] = backend
    timeout = run.gate_timeout(parsed)
    host = os.environ.get(core._ENV_TIMEOUT)
    if host:
        try:
            timeout = min(timeout, float(host))
        except ValueError:
            pass
    outcome = run._run(run._sandbox_argv(command, room, backend), room, supplied, timeout)
    outcome['quarantine'] = backend
    return outcome


def preflight(parsed: dict[str, Any]) -> list[str]:
    absent = []
    for item in parsed.get('claim', {}).get('requires', []):
        if item.startswith('python') and re.fullmatch(r'python\s*(<=|>=|==|!=|~=|<|>)\s*[\d.]+', item):
            if not run._version_ok('.'.join(map(str, sys.version_info[:3])), item[len('python'):]):
                absent.append(item)
        elif shutil.which(item) is None:
            try:
                found = importlib.util.find_spec(item)
            except (ValueError, ModuleNotFoundError):
                found = None
            if found is None:
                absent.append(item)
    return absent


def _audit_room(source: str, room: str, parsed: dict[str, Any]) -> dict[str, Any]:
    missing = preflight(parsed)
    furnished = None
    if not missing:
        try:
            furnished = _furnish(parsed, room)
        except (ClaimError, OSError, subprocess.SubprocessError) as exc:
            missing = [str(exc)]
    extra = None
    if furnished:
        extra = {'PATH': os.path.join(furnished, 'bin') + os.pathsep + os.environ.get('PATH', os.defpath)}
    rows = []
    for step in recipe.gates(parsed):
        name = step['output']
        if missing:
            rows.append({'output': name, 'status': 'environment', 'quarantine': None,
                         'detail': ', '.join(missing)})
            continue
        output = core._safe(room, name)
        if os.path.exists(output):
            os.unlink(output)
        outcome = run_gate(step['run'], room, parsed, extra)
        status = outcome['status']
        if status == 'ok':
            try:
                status = 'ok' if core._hash_file(output) == core._hash_file(core._safe(source, name)) else 'mismatch'
            except ClaimError:
                status = 'ok' if not os.path.exists(core._safe(source, name)) else 'mismatch'
        rows.append({'output': name, 'status': status, 'quarantine': outcome['quarantine'],
                     'stdout': outcome.get('stdout', ''), 'stderr': outcome.get('stderr', '')})
        ledger(source, {'event': 'gate', 'output': name, 'status': status,
                        'quarantine': outcome['quarantine']})
    return {'ok': bool(not missing and all(r['status'] == 'ok' for r in rows)),
            'gates': rows, 'environment': missing,
            'verdict': 'earned' if not missing and all(r['status'] == 'ok' for r in rows) else 'carried or broken'}


def audit(directory: os.PathLike[str] | str, *, produce_from: dict[str, str] | None = None,
          **kwargs: Any) -> dict[str, Any]:
    source = os.path.realpath(directory)
    checked = verify(source)
    if not checked['ok']:
        return {'ok': False, 'root': checked['root'], 'gates': [], 'environment': [],
                'verdict': 'identity mismatch'}
    with tempfile.TemporaryDirectory(prefix='reticuli-audit-') as room:
        parsed = _materialize(source, room)
        for name, path in (produce_from or {}).items():
            if name not in generated_outputs(parsed):
                raise ClaimError(f'not a generated output: {name}')
            core._copy_into(path, core._safe(room, name))
        result = _audit_room(source, room, parsed)
    result['root'] = checked['root']
    return result


def _producer_env(room: str, parsed: dict[str, Any], guidance: bool,
                  supplied: dict[str, str] | None) -> dict[str, str]:
    outputs = [s['output'] for s in recipe.produces(parsed) if 'from' not in s]
    extra = {core._ENV_CLAIM: room, core._ENV_OUTPUT: outputs[0] if outputs else '',
             core._ENV_OUTPUTS: json.dumps(outputs),
             core._ENV_USAGE: core._safe(room, core.USAGE)}
    if guidance:
        extra[core._ENV_REQUEST] = '\n'.join(s.get('guidance', s.get('request', '')) for s in recipe.produces(parsed))
    if supplied:
        extra.update(supplied)
    env = run._scrub_env(room, 'none', extra)
    env.pop(_JAILED, None)
    return env


def rebuild(directory: os.PathLike[str] | str, producer: str, into: os.PathLike[str] | str,
            *, produce_from: dict[str, str] | None = None,
            input_from: dict[str, str] | None = None, guidance: bool = True,
            producer_env: dict[str, str] | None = None) -> dict[str, Any]:
    source, target = os.path.realpath(directory), os.path.realpath(into)
    try:
        checked = verify(source)
    except ClaimError as exc:
        if 'cannot read manifest' not in str(exc):
            raise
        checked = None
    if checked is not None and not checked['ok']:
        raise ClaimError('source identity mismatch')
    if os.path.exists(target) and (not os.path.isdir(target) or os.listdir(target)):
        raise ClaimError('rebuild target is not empty')
    parsed = _materialize(source, target, generated=False)
    missing = preflight(parsed)
    if missing:
        raise ClaimError('environment: ' + ', '.join(missing))
    for name, path in (input_from or {}).items():
        if name not in recipe._inputs(parsed, source):
            raise ClaimError('not a declared input: ' + name)
        core._copy_into(path, core._safe(target, name))
    for name, path in (produce_from or {}).items():
        if name not in generated_outputs(parsed):
            raise ClaimError('not a generated output: ' + name)
        core._copy_into(path, core._safe(target, name))
        ledger(target, {'event': 'reuse', 'output': name})
    watched = {name: core._hash_file(core._safe(target, name)) for name in recipe._inputs(parsed, target)}
    rname = os.path.basename(recipe.recipe_path(target))
    watched[rname] = core._hash_file(core._safe(target, rname))
    os.makedirs(os.path.dirname(core._safe(target, core.USAGE)), exist_ok=True)
    outcome = run._run([core._SHELL, '-c', producer], target,
                       _producer_env(target, parsed, guidance, producer_env), core.PRODUCER_TIMEOUT)
    if outcome['status'] != 'ok':
        raise ClaimError(f"producer {outcome['status']}: {outcome.get('stderr','')}")
    for name, before in watched.items():
        if core._hash_file(core._safe(target, name)) != before:
            raise ClaimError('producer changed pinned bytes: ' + name)
    result = _audit_room(source, target, parsed)
    if not result['ok']:
        raise ClaimError('rebuild gates did not reproduce: ' + repr(result['gates']))
    manifest = sealing.seal(target)
    if checked is not None and not input_from and manifest['root'] != checked['root']:
        raise ClaimError('rebuild root differs from source')
    usage = build._read_usage(target)
    costs = {k: v for k, v in usage.items() if k in ('usd', 'tokens', 'calls')
             and type(v) in (int, float) and math.isfinite(v) and v >= 0}
    costs.setdefault('calls', 1)
    costs['seconds'] = outcome['seconds']
    ledger(target, {'event': 'oracle', 'kind': 'producer', 'when': core._now(),
                    'quarantine': 'none', **costs})
    ledger(target, {'event': 'environment', 'python': sys.version, 'platform': sys.platform,
                    'quarantine': result['gates'][0]['quarantine'] if result['gates'] else 'none'})
    declared = {k: os.environ[k] for k in (core._ENV_VENDOR, core._ENV_MODEL) if k in os.environ}
    if declared:
        ledger(target, {'event': 'producer', 'vendor': declared.get(core._ENV_VENDOR),
                        'model': declared.get(core._ENV_MODEL), 'blind': True})
    return {'root': manifest['root'], 'name': manifest['name'], 'gates': result['gates'],
            'quarantine': result['gates'][0]['quarantine'] if result['gates'] else 'none'}


def cost(directory: os.PathLike[str] | str) -> dict[str, float] | None:
    totals: dict[str, float] = {}
    for event in ledger_events(directory):
        if event.get('event') not in ('oracle', 'producer') and event.get('kind') != 'producer':
            continue
        for key in core.COST_KEYS:
            value = event.get(key)
            if type(value) in (int, float) and math.isfinite(value):
                totals[key] = totals.get(key, 0) + value
    return totals or None


def independence(directory: os.PathLike[str] | str) -> dict[str, Any]:
    for event in reversed(ledger_events(directory)):
        if event.get('event') == 'producer':
            return {k: event[k] for k in ('vendor', 'model', 'blind') if k in event}
    return {}


def sign_node(root_value: str, digest: str, links: list[str]) -> str:
    return hashlib.sha256(json.dumps({'root': root_value, 'build_digest': digest,
                                      'links': sorted(links)}, sort_keys=True).encode()).hexdigest()


def _trusted_signature(directory: str, manifest: dict[str, Any]) -> bool:
    anchor = os.environ.get(core._ENV_SIGNERS)
    if not anchor or not manifest.get('proof'):
        return False
    sdir = os.path.join(directory, SIGN_DIR)
    if not os.path.isdir(sdir):
        return False
    try:
        principals = [line.split()[0] for line in Path(anchor).read_text().splitlines()
                      if line.strip() and not line.lstrip().startswith('#')]
        for filename in os.listdir(sdir):
            if not filename.endswith('.sign.json'):
                continue
            statement = json.loads(Path(os.path.join(sdir, filename)).read_text())
            packet_path = os.path.join(sdir, filename[:-10] + '.packet.json')
            packet = json.loads(Path(packet_path).read_text())
            digest = hashlib.sha256(json.dumps(packet, sort_keys=True).encode()).hexdigest()
            if (statement.get('packet_digest') != digest or
                statement.get('root') != manifest['root'] or
                not statement.get('proof_recorded') or
                packet.get('proof') != manifest['proof'] or
                packet.get('root') != manifest['root'] or
                packet.get('build_digest') != build_digest(directory)):
                continue
            for principal in principals:
                done = subprocess.run(['ssh-keygen', '-Y', 'verify', '-f', anchor,
                                       '-I', principal, '-n', SIGN_NAMESPACE,
                                       '-s', os.path.join(sdir, filename + '.sig')],
                                      input=Path(os.path.join(sdir, filename)).read_bytes(),
                                      capture_output=True, check=False)
                if done.returncode == 0:
                    return True
    except (OSError, ValueError, KeyError, subprocess.SubprocessError):
        return False
    return False


def phase(directory: os.PathLike[str] | str) -> str:
    path = core._safe(directory, MANIFEST)
    if not os.path.exists(path):
        load_recipe(directory)
        return 'draft'
    checked = verify(directory)
    if not checked['ok']:
        raise ClaimError('claim identity mismatch')
    return 'signed' if _trusted_signature(os.path.realpath(directory), read_manifest(directory)) else 'sealed'


def gate_deciders(command: str) -> list[str]:
    import shlex
    result = []
    words = shlex.split(command.replace('&&', ' ').replace(';', ' '))
    for i, word in enumerate(words):
        if word in ('python', 'python3', 'pytest', 'py.test'):
            for nextword in words[i+1:]:
                if nextword == '-m':
                    continue
                if nextword in ('pytest', 'py.test', '-q'):
                    continue
                if not nextword.startswith('-'):
                    result.append(nextword.removeprefix('./'))
                    break
        elif word.startswith('./'):
            result.append(word[2:])
    return list(dict.fromkeys(result))


def vacuous_gates(parsed: dict[str, Any]) -> list[str]:
    generated = set(generated_outputs(parsed))
    inputs = set(parsed.get('claim', {}).get('inputs', []))
    result = []
    for step in recipe.gates(parsed):
        deciders = gate_deciders(step['run'])
        if deciders and all(d in generated and d not in inputs for d in deciders):
            result.append(step['output'])
    return result


mutation_score = comparison.mutation_score
crosscheck = comparison.crosscheck


def record_proof(m1: str, m2: str, m3: str) -> dict[str, Any]:
    if not os.path.isdir(m1):
        raise ClaimError('proof needs a directory for M1')
    records = []
    for path in (m2, m3):
        if os.path.isfile(path):
            anchor = os.environ.get(core._ENV_SIGNERS)
            if not anchor:
                raise ClaimError('record proof needs a trust anchor')
            signer = record_signer(path, anchor)
            records.append({'digest': record_digest(record_read(path)), 'signer': signer})
    result = crosscheck(m1, m2, m3)
    result['proof_recorded'] = result['satisfied']
    if result['satisfied']:
        manifest = read_manifest(m1)
        manifest['proof'] = {'kind': 'crosscheck', 'roots': result['roots'], 'records': records}
        core._write_json(core._safe(m1, MANIFEST), manifest)
    return result
