"""Run, list, and strip runnable Reticuli claims."""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

from . import kernel
from ._kernel import recipe as recipe_tools, run as execution


STATE = ".launcher"


def _say(message: str) -> None:
    print(message, file=sys.stderr)


def _claim(directory: str):
    directory = os.path.realpath(os.path.abspath(directory))
    parsed = kernel.load_recipe(directory)
    # Check every declared output before any operation can remove or create one.
    for step in parsed.get("step", []):
        kernel._safe(directory, step["output"])
    return directory, parsed


def _outputs(directory: str, parsed: dict) -> list[tuple[str, str]]:
    return [(name, kernel._safe(directory, name))
            for name in recipe_tools.generated_outputs(parsed)]


def _state_path(directory: str) -> str:
    return os.path.join(directory, STATE, "state.json")


def _read_state(directory: str) -> dict:
    try:
        with open(_state_path(directory), encoding="utf-8") as stream:
            value = json.load(stream)
        return value if isinstance(value, dict) else {}
    except (OSError, ValueError):
        return {}


def _write_state(directory: str, status: str, digest: str) -> None:
    path = _state_path(directory)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as stream:
        json.dump({"status": status, "digest": digest}, stream, sort_keys=True)
        stream.write("\n")


def _package(directory: str, parsed: dict) -> str:
    if "package.toml" not in recipe_tools._inputs(parsed, directory):
        raise ValueError("package.toml must be a pinned input")
    path = kernel._safe(directory, "package.toml")
    try:
        with open(path, "rb") as stream:
            package = tomllib.load(stream)
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise ValueError(f"cannot read package.toml: {exc}") from exc
    entry = package.get("package", {}).get("entrypoint")
    if not isinstance(entry, str):
        raise ValueError("package.toml needs [package] entrypoint")
    return kernel._safe(directory, entry)


def strip(directory: str) -> int:
    directory, parsed = _claim(directory)
    outputs = _outputs(directory, parsed)
    for _, path in outputs:
        if os.path.lexists(path):
            if os.path.isdir(path) and not os.path.islink(path):
                raise ValueError(f"generated output is a directory: {path}")
            os.unlink(path)
    shutil.rmtree(os.path.join(directory, STATE), ignore_errors=True)
    _say("stripped generated bytes")
    return 0


def _execute(directory: str, entry: str, args: list[str], no_sandbox: bool) -> int:
    backend = "off" if no_sandbox else execution.sandbox_backend()
    scratch = os.path.join(directory, STATE, "tmp")
    os.makedirs(scratch, exist_ok=True)
    env = execution._scrub_env(scratch, backend)
    if no_sandbox:
        env.pop(kernel._JAILED, None)
    elif backend in ("seatbelt", "bubblewrap"):
        env[kernel._JAILED] = "1"
    command = [sys.executable, entry, *args]
    if backend == "seatbelt":
        command = ["sandbox-exec", "-p", execution._seatbelt_profile(directory), *command]
    elif backend == "bubblewrap":
        command = ["bwrap", "--unshare-net", "--ro-bind", "/", "/",
                   "--dev-bind", "/dev", "/dev", "--proc", "/proc",
                   "--bind", directory, directory, "--chdir", directory,
                   "--", *command]
    _say(f'quarantine = "{backend}"')
    return subprocess.run(command, cwd=directory, env=env, check=False).returncode


def run(directory: str, args: list[str], accept_generated: bool,
        signed_only: bool, no_sandbox: bool) -> int:
    directory, parsed = _claim(directory)
    entry = _package(directory, parsed)
    checked = kernel.verify(directory)
    if not checked["ok"]:
        _say("claim identity drifted; strip or restore its pinned bytes")
        return 6
    phase = kernel.phase(directory)
    if signed_only and phase != "signed":
        _say("signed claim required")
        return 5
    outputs = _outputs(directory, parsed)
    complete = all(os.path.isfile(path) for _, path in outputs)
    state = _read_state(directory)
    if complete and state.get("status") == "accepted":
        if kernel.build_digest(directory) != state.get("digest"):
            _say("accepted build drifted; run strip to recover")
            return 6
    if not complete:
        producer = os.environ.get("RETICULI_PRODUCER")
        if not producer:
            _say("latent claim needs RETICULI_PRODUCER")
            return 7
        with tempfile.TemporaryDirectory(prefix="reticuli-launch-") as room:
            try:
                kernel.rebuild(directory, producer, room)
                for name, target in outputs:
                    source = kernel._safe(room, name)
                    if not os.path.isfile(source):
                        raise kernel.ClaimError(f"producer omitted {name}")
                for name, target in outputs:
                    os.makedirs(os.path.dirname(target), exist_ok=True)
                    shutil.copyfile(kernel._safe(room, name), target)
            except (kernel.ClaimError, OSError) as exc:
                _say(f"rebuild failed: {exc}; strip to recover")
                return 6
        _write_state(directory, "fresh", kernel.build_digest(directory))
        state = _read_state(directory)
    if not complete or state.get("status") == "fresh":
        if not accept_generated:
            _say("newly generated bytes need --accept-generated before execution")
            return 4
    # An imported build has no launcher acceptance state; its gates decide.
    audit = kernel.audit(directory)
    if not audit.get("ok"):
        _say("build audit failed; strip to recover")
        return 6
    if state.get("status") == "fresh" and accept_generated:
        _write_state(directory, "accepted", kernel.build_digest(directory))
    _say(f"{phase} claim {checked['root'][:12]}")
    return _execute(directory, entry, args, no_sandbox)


def ls(directories: list[str]) -> int:
    for directory in directories:
        directory, parsed = _claim(directory)
        manifest = kernel.read_manifest(directory)
        outputs = _outputs(directory, parsed)
        presence = "materialized" if all(os.path.isfile(path) for _, path in outputs) else "latent"
        print(f"{manifest['name']} {manifest['root'][:12]} {kernel.phase(directory)} {presence} {directory}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Reticuli claim launcher",
                                     epilog="run: --accept-generated --signed-only --no-sandbox")
    verbs = parser.add_subparsers(dest="verb", required=True)
    run_parser = verbs.add_parser("run", help="run a packaged claim")
    run_parser.add_argument("claim")
    run_parser.add_argument("--accept-generated", action="store_true")
    run_parser.add_argument("--signed-only", action="store_true")
    run_parser.add_argument("--no-sandbox", action="store_true")
    strip_parser = verbs.add_parser("strip", help="remove generated bytes")
    strip_parser.add_argument("claim")
    ls_parser = verbs.add_parser("ls", help="list claims")
    ls_parser.add_argument("claims", nargs="+")
    words = list(sys.argv[1:] if argv is None else argv)
    arguments: list[str] = []
    if words[:1] == ["run"] and "--" in words:
        divider = words.index("--")
        arguments = words[divider + 1:]
        words = words[:divider]
    options = parser.parse_args(words)
    try:
        if options.verb == "run":
            return run(options.claim, arguments, options.accept_generated,
                       options.signed_only, options.no_sandbox)
        if options.verb == "strip":
            return strip(options.claim)
        return ls(options.claims)
    except (kernel.ClaimError, ValueError, OSError) as exc:
        _say(f"not runnable: {exc}")
        return 3


if __name__ == "__main__":
    raise SystemExit(main())
