"""Independent, standard-library implementation of claim identity.

The root covers the parsed recipe and declared pinned bytes.  The build
digest covers the generated bytes that are present in a realization.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import tomllib
from typing import Any


class ClaimError(ValueError):
    """A claim cannot be interpreted without ambiguity."""


def _canonical(value: Any) -> bytes:
    try:
        return json.dumps(value, sort_keys=True).encode("utf-8")
    except (TypeError, ValueError) as exc:
        raise ClaimError(f"value has no canonical JSON form: {exc}") from exc


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _path(directory: os.PathLike[str] | str, name: str) -> Path:
    if not isinstance(name, str) or not name or os.path.isabs(name):
        raise ClaimError(f"unsafe claim path: {name!r}")
    components = name.split("/")
    if any(part in ("", ".", "..") for part in components):
        raise ClaimError(f"unsafe claim path: {name!r}")
    base = Path(directory).resolve()
    current = base
    for part in components:
        current = current / part
        if current.is_symlink():
            raise ClaimError(f"symlink in claim path: {name!r}")
    path = current.resolve()
    if base not in path.parents:
        raise ClaimError(f"claim path escapes directory: {name!r}")
    return path


def _hash_file(path: Path) -> str:
    try:
        info = path.lstat()
        if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1:
            raise ClaimError(f"not a single-link regular file: {path}")
        digest = hashlib.sha256()
        with path.open("rb") as stream:
            for chunk in iter(lambda: stream.read(1024 * 1024), b""):
                digest.update(chunk)
        return digest.hexdigest()
    except OSError as exc:
        raise ClaimError(f"cannot hash {path}: {exc}") from exc


def _recipe_path(directory: os.PathLike[str] | str) -> Path:
    for name in ("reticuli.toml", "claim.toml"):
        candidate = _path(directory, name)
        if candidate.is_file():
            return candidate
    raise ClaimError(f"no recipe in {directory}")


def _load(directory: os.PathLike[str] | str) -> dict[str, Any]:
    path = _recipe_path(directory)
    try:
        with path.open("rb") as stream:
            recipe = tomllib.load(stream)
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise ClaimError(f"cannot read recipe {path}: {exc}") from exc
    claim = recipe.get("claim")
    if not isinstance(claim, dict) or not isinstance(claim.get("name"), str) or not claim["name"]:
        raise ClaimError("recipe needs a nonempty claim.name")
    version = claim.get("format", 1)
    if type(version) is not int or version < 1 or version > 3:
        raise ClaimError(f"unsupported claim format: {version!r}")
    steps = recipe.get("step", [])
    if not isinstance(steps, list):
        raise ClaimError("step must be an array of tables")
    for step in steps:
        if not isinstance(step, dict) or step.get("kind") not in ("produce", "gate"):
            raise ClaimError("step needs a valid kind")
        _path(directory, step.get("output"))
        if step["kind"] == "gate" and not isinstance(step.get("run"), str):
            raise ClaimError("gate needs a run command")
    return recipe


def _inputs(recipe: dict[str, Any], directory: os.PathLike[str] | str) -> list[str]:
    claim = recipe["claim"]
    names = claim.get("inputs", [])
    if not isinstance(names, list) or any(not isinstance(name, str) for name in names):
        raise ClaimError("claim.inputs must be a list of paths")
    result = list(names)
    manifest = claim.get("inputs_manifest")
    if manifest is not None:
        manifest_path = _path(directory, manifest)
        result.append(manifest)
        for raw in manifest_path.read_text(encoding="utf-8").splitlines():
            entry = raw.strip()
            if not entry or entry.startswith("#"):
                continue
            if re.match(r"^[0-9a-fA-F]{64}  ", entry):
                entry = entry[66:]
            elif re.match(r"^[0-9a-fA-F]{64}\s", entry):
                raise ClaimError(f"invalid digest entry in {manifest}")
            if not entry or entry != entry.strip():
                raise ClaimError(f"invalid input in {manifest}")
            result.append(entry)
    if "environment" in claim:
        result.append(claim["environment"])
    return list(dict.fromkeys(result))


def _preimage_recipe(recipe: dict[str, Any]) -> dict[str, Any]:
    if recipe["claim"].get("format", 1) < 3:
        return recipe
    cleaned = dict(recipe)
    cleaned["step"] = []
    for original in recipe.get("step", []):
        step = dict(original)
        if step["kind"] == "produce":
            step.pop("guidance", None)
            step.pop("request", None)
        cleaned["step"].append(step)
    return cleaned


def root(directory: os.PathLike[str] | str) -> str:
    """Return the SHA-256 identity of a claim directory."""
    recipe = _load(directory)
    parts = {"digest": "sha256", "recipe": _canonical(_preimage_recipe(recipe)).decode("utf-8")}
    for name in _inputs(recipe, directory):
        parts["input:" + name] = _hash_file(_path(directory, name))
    for step in recipe.get("step", []):
        classification = step.get("class", "generated" if step["kind"] == "produce" else "pinned")
        if classification not in ("generated", "free"):
            name = step["output"]
            parts["pinned:" + name] = _hash_file(_path(directory, name))
    return _sha256(_canonical(parts))


def build_digest(directory: os.PathLike[str] | str) -> str:
    """Return the digest of present, locally produced generated outputs."""
    recipe = _load(directory)
    outputs = []
    for step in recipe.get("step", []):
        if step["kind"] != "produce" or "from" in step:
            continue
        if step.get("class", "generated") not in ("generated", "free"):
            continue
        name = step["output"]
        path = _path(directory, name)
        if path.exists():
            outputs.append([name, _hash_file(path)])
    outputs.sort(key=lambda item: item[0])
    return _sha256(_canonical(outputs))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Reference claim identity")
    parser.add_argument("operation", choices=("root", "digest", "build-digest"))
    parser.add_argument("directory")
    args = parser.parse_args(argv)
    try:
        print(root(args.directory) if args.operation == "root" else build_digest(args.directory))
    except (ClaimError, OSError, UnicodeError) as exc:
        parser.exit(1, f"reference: {exc}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
