"""reticuli.attest -- a keyholder's signed statement of a build, and the
signing ceremony (`spec/layers.md`, `spec/verification.md`).

Two distinct signatures live here, in namespaces of their own
(`spec/claim-format.md`, "Still open" -- namespaces are the keyholder's
call, decided for this layer):

  * `attest` / `check` -- a build attestation: "I audited this claim and
    its verdicts reproduced, on these exact bytes" -- signed in the
    `reticuli` namespace, stored under `ATTEST`. It never notarizes a
    carried verdict (it refuses unless `kernel.audit` earns clean) and it
    is about a *build*: the statement freezes the concrete `build_digest`,
    and a later change to the generated bytes leaves the claim's root
    untouched but drifts the attestation, which then refuses.
  * `sign` / `sign_check` -- the signing ceremony: a human authorizes the
    chain root over a reviewed packet (root, chain node, audit, recorded
    proof), signed in `kernel.SIGN_NAMESPACE`. Authorization and proof are
    independent facts, coupled only by `kernel.phase`: `sign_check` reports
    whether the signature is trustworthy and the packet unforged; whether
    that authorization is also *signed* (phase) additionally needs a
    recorded proof, which `kernel.phase` (not this module) decides.
"""
import hashlib
import json
import os
import subprocess
from datetime import datetime, timezone

from . import kernel
from . import registry

ATTEST = ".reticuli/attest"
_STATEMENT = "attest.json"

CEREMONY = "RETICULI_CLAIM_BASIN_V1"
_CEREMONY_PREFIX = "review"


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _digest_json(obj) -> str:
    return hashlib.sha256(json.dumps(obj, sort_keys=True).encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# attest / check: a signed statement of one build
# ---------------------------------------------------------------------------
def _paths(d: str):
    stmt = os.path.join(d, ATTEST, _STATEMENT)
    return stmt, stmt + ".sig"


def attest(d: str, key: str, identity: str) -> dict:
    """Sign a statement that `d`'s verdicts reproduce, on these exact
    bytes. Refuses (raises `kernel.ClaimError`) any claim whose audit does
    not earn clean -- attest never notarizes a carried verdict."""
    aud = kernel.audit(d)
    if not aud.get("ok"):
        raise kernel.ClaimError(
            f"cannot attest an unearned build: {aud.get('verdict')!r}")

    manifest = kernel.read_manifest(d)
    statement = {
        "root": manifest["root"],
        "build_digest": kernel.build_digest(d),
        "identity": identity,
        "when": _now(),
    }
    stmt_path, sig_path = _paths(d)
    os.makedirs(os.path.dirname(stmt_path), exist_ok=True)
    with open(stmt_path, "wb") as f:
        f.write(json.dumps(statement, sort_keys=True).encode("utf-8"))
    if os.path.exists(sig_path):
        os.remove(sig_path)
    subprocess.run(
        ["ssh-keygen", "-Y", "sign", "-f", key, "-n", kernel.NAMESPACE, stmt_path],
        check=True, capture_output=True,
    )
    return {
        "root": manifest["root"],
        "statement": os.path.relpath(stmt_path, d),
        "signature": os.path.relpath(sig_path, d),
    }


def check(d: str, signers=None) -> dict:
    """Whether `d`'s attestation (if any) is intact: not drifted from the
    bytes present, and -- when `signers` is given -- verified against it."""
    stmt_path, sig_path = _paths(d)
    if not os.path.isfile(stmt_path):
        return {"ok": False, "attestations": []}

    with open(stmt_path, "rb") as f:
        raw = f.read()
    try:
        statement = json.loads(raw.decode("utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError):
        return {"ok": False, "attestations": [{"ok": False, "drifted": True}]}

    current_digest = kernel.build_digest(d)
    drifted = statement.get("build_digest") != current_digest
    entry = {
        "root": statement.get("root"),
        "identity": statement.get("identity"),
        "drifted": drifted,
    }

    ok = not drifted
    if signers:
        verified = False
        identity = statement.get("identity")
        if os.path.isfile(sig_path) and os.path.isfile(signers) and isinstance(identity, str):
            done = subprocess.run(
                ["ssh-keygen", "-Y", "verify", "-f", signers, "-I", identity,
                 "-n", kernel.NAMESPACE, "-s", sig_path],
                input=raw, capture_output=True, timeout=30, check=False,
            )
            verified = done.returncode == 0
        entry["verdict"] = "signed" if verified else "untrusted"
        ok = ok and verified

    entry["ok"] = ok
    return {"ok": ok, "root": statement.get("root"), "attestations": [entry]}


# ---------------------------------------------------------------------------
# review_packet / sign / sign_check: the signing ceremony
# ---------------------------------------------------------------------------
def review_packet(d: str, ws=None) -> dict:
    """What a keyholder reviews before signing: the root, the chain node
    over the DAG, a fresh audit, and any recorded proof."""
    v = kernel.verify(d)
    if not v["ok"]:
        raise kernel.ClaimError(f"claim identity does not hold: {d!r}")
    aud = kernel.audit(d)
    manifest = kernel.read_manifest(d)
    return {
        "root": v["root"],
        "build_digest": kernel.build_digest(d),
        "sign_root": registry.sign_root(d, ws),
        "audit": {"ok": bool(aud.get("ok")), "verdict": aud.get("verdict")},
        "proof": manifest.get("proof"),
    }


def sign(d: str, key: str, identity: str, ws=None) -> dict:
    """The ceremony: sign the review packet, authorizing the chain root.
    Refuses a claim whose verdicts do not reproduce."""
    packet = review_packet(d, ws=ws)
    if not packet["audit"]["ok"]:
        raise kernel.ClaimError("sign refuses: verdicts do not reproduce")

    sign_dir = os.path.join(d, kernel.SIGN_DIR)
    os.makedirs(sign_dir, exist_ok=True)

    packet_bytes = json.dumps(packet, sort_keys=True).encode("utf-8")
    packet_path = os.path.join(sign_dir, _CEREMONY_PREFIX + ".packet.json")
    with open(packet_path, "wb") as f:
        f.write(packet_bytes)

    statement = {
        "root": packet["root"],
        "proof_recorded": bool(packet.get("proof")),
        "identity": identity,
        "packet_digest": _digest_json(packet),
        "when": _now(),
    }
    stmt_path = os.path.join(sign_dir, _CEREMONY_PREFIX + ".sign.json")
    with open(stmt_path, "wb") as f:
        f.write(json.dumps(statement, sort_keys=True).encode("utf-8"))

    sig_path = stmt_path + ".sig"
    if os.path.exists(sig_path):
        os.remove(sig_path)
    subprocess.run(
        ["ssh-keygen", "-Y", "sign", "-f", key, "-n", kernel.SIGN_NAMESPACE, stmt_path],
        check=True, capture_output=True,
    )

    return {
        "ceremony": CEREMONY,
        "root": packet["root"],
        "statement": os.path.relpath(stmt_path, d),
        "signature": os.path.relpath(sig_path, d),
        "packet": os.path.relpath(packet_path, d),
    }


def sign_check(d: str, ws=None, signers=None) -> dict:
    """Whether the ceremony's authorization(s) are trustworthy: a verified
    signature over a statement whose `packet_digest` still names the
    exact stored packet."""
    v = kernel.verify(d)
    sign_dir = os.path.join(d, kernel.SIGN_DIR)
    authorizations = []
    ok = False
    if os.path.isdir(sign_dir):
        for fname in sorted(os.listdir(sign_dir)):
            if not fname.endswith(".sign.json"):
                continue
            spath = os.path.join(sign_dir, fname)
            sig_path = spath + ".sig"
            with open(spath, "rb") as f:
                raw = f.read()
            try:
                statement = json.loads(raw.decode("utf-8"))
            except (json.JSONDecodeError, UnicodeDecodeError):
                continue

            identity = statement.get("identity")
            verified = False
            if signers and os.path.isfile(sig_path) and os.path.isfile(signers) \
                    and isinstance(identity, str):
                done = subprocess.run(
                    ["ssh-keygen", "-Y", "verify", "-f", signers, "-I", identity,
                     "-n", kernel.SIGN_NAMESPACE, "-s", sig_path],
                    input=raw, capture_output=True, timeout=30, check=False,
                )
                verified = done.returncode == 0

            prefix = fname[: -len(".sign.json")]
            packet_path = os.path.join(sign_dir, prefix + ".packet.json")
            packet_holds = False
            if os.path.isfile(packet_path):
                with open(packet_path, "rb") as f:
                    praw = f.read()
                try:
                    packet = json.loads(praw.decode("utf-8"))
                    packet_holds = _digest_json(packet) == statement.get("packet_digest")
                except (json.JSONDecodeError, UnicodeDecodeError):
                    packet_holds = False

            entry_ok = verified and packet_holds and bool(v.get("ok"))
            authorizations.append({
                "identity": identity,
                "verdict": "authorized" if verified else "untrusted",
                "packet_holds": packet_holds,
                "proof_recorded": bool(statement.get("proof_recorded")),
                "ok": entry_ok,
            })
            if entry_ok:
                ok = True
    return {"ok": ok, "authorizations": authorizations}
