"""reticuli.kernel -- the public surface of the innermost layer.

Everything here is a thin facade over `reticuli._kernel`: identity
(`root`, `seal`, `verify`, `build_digest`), the deep re-earning verbs
(`audit`, `rebuild`, `crosscheck`, `record_proof`), and the small pieces a
caller needs directly (`run_gate`, `sandbox`, `preflight`, `cost`,
`phase`, `sign_node`, `vacuous_gates`, `gate_deciders`, `independence`,
`mutation_score`, the record reader). No layer above may depend on a name
this module does not export -- that is the whole point of having a facade
instead of letting every layer reach into `_kernel` directly.

Stdlib only. Never the network.
"""
import hashlib
import json
import os
import shutil
import stat
import subprocess
import tempfile
import time

from ._kernel import attest as _attest
from ._kernel import build as _build
from ._kernel import core
from ._kernel import identity
from ._kernel import recipe as _recipe
from ._kernel import run as _run
from ._kernel import seal as _seal
from ._kernel.crosscheck import (
    crosscheck,
    gate_deciders,
    independence,
    mutation_score,
    record_read,
    record_signer,
    record_validate,
    vacuous_gates,
)
from ._kernel.crosscheck import RECORD_FORMAT, RECORD_NAMESPACE

# ---------------------------------------------------------------------------
# Protocol constants
# ---------------------------------------------------------------------------
NAMESPACE = core.NAMESPACE
DIGEST = core.DIGEST
FORMAT = core.FORMAT
STORE = core.STORE
MANIFEST = core.MANIFEST
RECIPE = core.RECIPE
LEGACY_RECIPE = core.LEGACY_RECIPE
LEDGER = core.LEDGER
USAGE = core.USAGE
MUTATION_RESIDUE = core.MUTATION_RESIDUE
SIGN_DIR = core.SIGN_DIR
SIGN_NAMESPACE = core.SIGN_NAMESPACE
_JAILED = core._JAILED

ClaimError = core.ClaimError
_hash_file = core._hash_file

# ---------------------------------------------------------------------------
# Identity and the store
#
# `core._safe` resolves a declared name via `realpath` and refuses an
# escape -- but realpath FOLLOWS symlinks, so a pinned name that is itself
# a symlink to a file inside the claim resolves to a path inside the
# claim and passes. That is exactly the alias `spec/identity.md` refuses:
# it lets sealing hash generated bytes into the root through the pinned
# name. `_check_declared_path` adds the stricter boundary in front of
# `identity.root` -- no `..` component regardless of where it lexically
# ends up (a `..` next to a symlink resolves against the link's target,
# so no `..` path is trustworthy), no symlink component anywhere along
# the path, and the named file itself must be a regular file with a
# single hard link (never a FIFO, device, directory, or a hardlink to an
# inode outside the claim).
# ---------------------------------------------------------------------------
def _check_declared_path(d: str, name: str) -> None:
    core._safe(d, name)
    parts = name.split(os.sep)
    if ".." in parts:
        raise core.ClaimError(f"'..' component refused: {name!r}")
    partial = d
    for part in parts:
        partial = os.path.join(partial, part)
        if os.path.islink(partial):
            raise core.ClaimError(f"symlink component refused: {name!r}")
    if os.path.exists(partial):
        st = os.stat(partial, follow_symlinks=False)
        if not stat.S_ISREG(st.st_mode):
            raise core.ClaimError(f"not a regular file: {name!r}")
        if st.st_nlink != 1:
            raise core.ClaimError(f"file has more than one hard link: {name!r}")


# `[claim] environment` names a file that is "automatically a pinned
# input" (`spec/claim-format.md`): dependency versions decide what a
# gate's pass means, so the file's bytes must be in the root even when
# the recipe's own `inputs` list forgets to name it. `identity.root`
# (given, unmodifiable) only ever hashes `claim.inputs` -- it has no
# notion of `environment` at all -- so the augmentation happens here,
# in front of it.
_raw_identity_root = identity.root


def _augmented_recipe(recipe: dict) -> dict:
    env_file = recipe.get("claim", {}).get("environment")
    if not env_file:
        return recipe
    inputs = list(recipe.get("claim", {}).get("inputs", []))
    if env_file in inputs:
        return recipe
    augmented = dict(recipe)
    augmented["claim"] = {**recipe.get("claim", {}), "inputs": inputs + [env_file]}
    return augmented


def root(recipe: dict, d: str) -> str:
    recipe = _augmented_recipe(recipe)
    for path in recipe.get("claim", {}).get("inputs", []):
        _check_declared_path(d, path)
    for step in recipe.get("step", []):
        cls = step.get("class")
        if cls is None:
            cls = "generated" if step.get("kind") == "produce" else "pinned"
        if cls == "generated":
            continue
        _check_declared_path(d, step["output"])
    return _raw_identity_root(recipe, d)


build_digest = identity.build_digest


_COST_UNITS = frozenset({"usd", "tokens", "calls", "seconds"})


def _validate_envelope(envelope) -> None:
    if not isinstance(envelope, dict) or not envelope:
        raise core.ClaimError(f"[claim] envelope must be a non-empty table, got {envelope!r}")
    for unit, ceiling in envelope.items():
        if unit not in _COST_UNITS:
            raise core.ClaimError(f"[claim] envelope has an unknown unit: {unit!r}")
        if isinstance(ceiling, bool) or not isinstance(ceiling, (int, float)) or ceiling <= 0:
            raise core.ClaimError(
                f"[claim] envelope.{unit} must be a positive number, got {ceiling!r}")


def load_recipe(d: str) -> dict:
    """`_recipe.load_recipe` plus the validation rules it does not itself
    enforce (`spec/claim-format.md`): `[claim] name` is required and must
    be a string, and a declared `[claim] envelope` must be a non-empty
    table of positive numbers over a known cost unit."""
    parsed = _recipe.load_recipe(d)
    name = parsed.get("claim", {}).get("name")
    if not isinstance(name, str):
        raise core.ClaimError(f"[claim] name must be a string, got {name!r}")
    envelope = parsed.get("claim", {}).get("envelope")
    if envelope is not None:
        _validate_envelope(envelope)
    return parsed


def _wrap_claim_errors(func):
    """Hostile claim bytes are refused in band, never a raw traceback.
    `_seal.read_manifest`/`verify` already catch OSError and
    JSONDecodeError, but not a manifest whose bytes are not valid UTF-8
    at all -- one more way a corrupt file can crash a naive reader."""
    def wrapped(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except core.ClaimError:
            raise
        except (UnicodeDecodeError, ValueError, TypeError, KeyError,
                AttributeError, LookupError) as exc:
            raise core.ClaimError(f"malformed claim bytes: {exc}") from exc
    return wrapped


read_manifest = _wrap_claim_errors(_seal.read_manifest)


def seal(d: str, **kwargs) -> dict:
    """`_seal.seal`, but computing the root through `root()` above so an
    `environment` pin is honored -- `_seal.seal` calls `identity.root`
    directly and knows nothing about it."""
    parsed = load_recipe(d)
    name = parsed.get("claim", {}).get("name")
    manifest = {"name": name, "root": root(parsed, d)}
    path = core._safe(d, core.MANIFEST)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    core._write_json(path, manifest)
    return manifest


def verify(d: str) -> dict:
    """`_seal.verify`, but recomputing through `root()` for the same
    reason `seal` does."""
    manifest = read_manifest(d)
    parsed = load_recipe(d)
    recomputed = root(parsed, d)
    return {
        "ok": recomputed == manifest["root"],
        "root": manifest["root"],
        "recomputed": recomputed,
        "name": manifest["name"],
    }


verify = _wrap_claim_errors(verify)

# ---------------------------------------------------------------------------
# The record reader (spec/record.md)
# ---------------------------------------------------------------------------
record_canonical = _attest.record_canonical
record_digest = _attest.record_digest

# ---------------------------------------------------------------------------
# Gate execution, sandbox probing, and the environment contract
# ---------------------------------------------------------------------------
preflight = _run.preflight

# The claim's own recognized RETICULI_* variables -- the allowlist a gate's
# scrubbed environment is built from. `_run._scrub_env` copies through ANY
# `RETICULI_*`-prefixed variable, inherited secret included, since it has
# no way to tell a claim's own from a hostile passenger riding the same
# prefix; the gate contract needs the narrower list.
_KNOWN_RETICULI_VARS = frozenset({
    core._ENV_CLAIM, core._ENV_MODEL, core._ENV_OUTPUT, core._ENV_OUTPUTS,
    core._ENV_REQUEST, core._ENV_SIGNERS, core._ENV_TIMEOUT, core._ENV_TOLERANCE,
    core._ENV_USAGE, core._ENV_VENDOR, core._JAILED,
})


def _gate_env() -> dict:
    """A minimal host allowlist plus only the claim's OWN recognized
    variables -- never an arbitrary `RETICULI_*`-prefixed passenger."""
    env = {k: v for k, v in os.environ.items() if k in core._KEEP_ENV}
    for k, v in os.environ.items():
        if k in _KNOWN_RETICULI_VARS:
            env[k] = v
    return env


def _effective_timeout(declared=None) -> float:
    """`min(declared, host ceiling)`, reading the host ceiling from
    `RETICULI_GATE_TIMEOUT` FRESH on every call. `core.GATE_TIMEOUT` (and
    so `_run.gate_timeout`) reads that variable once, at import time, so
    a caller that sets it at runtime -- as a producer's own test harness
    would -- has no effect through that path."""
    ceiling = float(os.environ.get(core._ENV_TIMEOUT, 300))
    if declared is None:
        return ceiling
    try:
        declared = float(declared)
    except (TypeError, ValueError) as exc:
        raise core.ClaimError(f"gate_timeout must be a number, got {declared!r}") from exc
    return min(declared, ceiling)


def run_gate(cmd: str, d: str, recipe: dict = None) -> dict:
    """Run one gate command in `d`: scrubbed environment, sandboxed,
    bounded by `recipe`'s declared `gate_timeout` (or the host ceiling).

    THE SENDING HALF of the sandbox contract: where this call really
    applies a fresh sandbox (the host has one, and we are not already
    inside one -- `sandbox_backend()` would say `inherited` otherwise),
    the wrapped process is told which jail it is in via `RETICULI_JAILED`,
    so a gate that is itself a claim runner inherits instead of nesting.
    `_run.run_gate` cannot make that promise: it only copies whatever
    `RETICULI_JAILED` already sits in this process's own environment, and
    never sets a fresh one for a backend it just now decided to apply.
    """
    timeout = None
    if isinstance(recipe, dict):
        timeout = recipe.get("claim", {}).get("gate_timeout")

    backend = _run.sandbox_backend()
    eff_timeout = _effective_timeout(timeout)
    env = _gate_env()
    if backend in ("seatbelt", "bubblewrap"):
        env[core._JAILED] = backend

    scratch_root = os.path.join(d, core.STORE, "scratch")
    os.makedirs(scratch_root, exist_ok=True)
    scratch = tempfile.mkdtemp(dir=scratch_root)
    try:
        base_argv = ["/bin/sh", "-c", cmd]
        if backend in ("seatbelt", "bubblewrap"):
            env["TMPDIR"] = scratch
            env["HOME"] = scratch
            argv = _run._sandbox_argv(backend, base_argv, d, scratch)
        else:
            argv = base_argv
        returncode, timed_out = _run._run(argv, d, env, eff_timeout)
    finally:
        shutil.rmtree(scratch, ignore_errors=True)

    if timed_out:
        status = "timeout"
    elif returncode == 0:
        status = "ok"
    else:
        status = "failed"
    return {"status": status, "quarantine": backend}


def sandbox(cmd: str = "true", d: str = None):
    """A functional probe of the host sandbox: run `cmd` in `d` through
    `run_gate` and return `(status, backend)`."""
    if d is None:
        d = os.getcwd()
    result = _run.run_gate(cmd, d)
    return (result["status"], result["quarantine"])


def cost(d: str):
    """Ledger totals per unit; `None` if nothing was measured."""
    totals = _run.cost(d)
    return totals if totals else None


# ---------------------------------------------------------------------------
# audit: build.audit, plus the `[claim] environment` furnish step and a
# corrected shape for the environment-failure case (build.audit's own
# shape there predates furnishing and never populated `gates`).
# ---------------------------------------------------------------------------
def _relabel_reproduced(result: dict) -> dict:
    """`build.audit` spells a clean, byte-reproducing gate `reproduced`;
    the passing spelling this check pins is `ok` (the failure classes
    are pinned, the success spelling is not -- but a spelling still has
    to be picked, and one comparable across kernels has to be the same
    word `run_gate` already uses for a clean run)."""
    for gate in result.get("gates", []):
        if gate.get("status") == "reproduced":
            gate["status"] = "ok"
    return result


def audit(d: str, produce_from: dict = None, **kwargs) -> dict:
    """`build.audit` plus two things it does not itself do: honor
    `produce_from` (a claim judges substituted generated bytes -- a
    dependent's shipped code, re-earned by the component's own check),
    and furnish `[claim] environment` before judging."""
    if produce_from:
        def _substitute(step, room):
            src = produce_from.get(step["output"])
            if src is not None:
                with open(src, "rb") as f:
                    return f.read()
            original = core._safe(d, step["output"])
            if os.path.isfile(original):
                with open(original, "rb") as f:
                    return f.read()
            return b""
        kwargs = {**kwargs, "producer": _substitute}

    recipe = _recipe.load_recipe(d)
    manifest = read_manifest(d)
    missing = list(_run.preflight(recipe))

    env_file = recipe.get("claim", {}).get("environment")
    venv_dir = None
    if env_file:
        # `furnish` installs `-r <requirements file>` without setting `cwd`,
        # and pip resolves a requirement file's relative local paths (a
        # wheel named by a bare relative path, as ours are) against the
        # process's cwd, not the requirements file's own directory -- so
        # furnishing must run from `d`.
        old_cwd = os.getcwd()
        try:
            os.chdir(d)
            venv_dir = _run.furnish(env_file, d)
        except (core.ClaimError, OSError, subprocess.CalledProcessError,
                subprocess.TimeoutExpired):
            missing.append(env_file)
        finally:
            os.chdir(old_cwd)

    if missing:
        recomputed = root(recipe, d)
        gate_steps = [s for s in recipe.get("step", []) if s.get("kind") == "gate"]
        return {
            "ok": False,
            "verdict": "environment",
            "name": manifest["name"],
            "root": manifest["root"],
            "recomputed": recomputed,
            "gates": [{"output": s["output"], "status": "environment", "quarantine": None}
                      for s in gate_steps],
            "environment": missing,
        }

    # `build.audit` re-derives identity itself, via `identity.root(recipe, d)`
    # called on the module directly -- it has no way to know about the
    # `environment` augmentation `root()` applies above. Patch the module
    # attribute for the span of this one call so its internal check sees
    # exactly the root `seal()`/`verify()` computed; the saved reference
    # (`_raw_identity_root`) means `root()` itself never recurses through
    # the patched name.
    old_path = os.environ.get("PATH", "")
    if venv_dir is not None:
        os.environ["PATH"] = os.path.join(venv_dir, "bin") + os.pathsep + old_path
    identity.root = root
    try:
        return _relabel_reproduced(_build.audit(d, **kwargs))
    finally:
        identity.root = _raw_identity_root
        if venv_dir is not None:
            os.environ["PATH"] = old_path


# ---------------------------------------------------------------------------
# phase: draft / sealed / signed
# ---------------------------------------------------------------------------
def _signed(d: str, verified_root: str) -> bool:
    sign_dir = core._safe(d, core.SIGN_DIR)
    if not os.path.isdir(sign_dir):
        return False
    manifest = read_manifest(d)
    if not manifest.get("proof"):
        return False
    signers_path = os.environ.get(core._ENV_SIGNERS)
    if not signers_path or not os.path.isfile(signers_path):
        return False

    recipe = _recipe.load_recipe(d)
    current_digest = identity.build_digest(d)

    for fname in sorted(os.listdir(sign_dir)):
        if not fname.endswith(".sign.json"):
            continue
        spath = os.path.join(sign_dir, fname)
        sig_path = spath + ".sig"
        if not os.path.isfile(sig_path):
            continue
        try:
            with open(spath, "r", encoding="utf-8") as f:
                statement = json.load(f)
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(statement, dict):
            continue
        if statement.get("root") != verified_root or not statement.get("proof_recorded"):
            continue
        signer_id = statement.get("identity")
        if not isinstance(signer_id, str):
            continue
        with open(spath, "rb") as f:
            data = f.read()
        if not _build._ssh_verify(data, sig_path, signers_path, core.SIGN_NAMESPACE,
                                   signer=signer_id):
            continue

        prefix = fname[: -len(".sign.json")]
        packet_path = os.path.join(sign_dir, prefix + ".packet.json")
        if not os.path.isfile(packet_path):
            continue
        try:
            with open(packet_path, "r", encoding="utf-8") as f:
                packet = json.load(f)
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(packet, dict):
            continue
        packet_digest = hashlib.sha256(
            json.dumps(packet, sort_keys=True).encode("utf-8")).hexdigest()
        if packet_digest != statement.get("packet_digest"):
            continue
        if packet.get("root") != verified_root:
            continue
        if packet.get("build_digest") != current_digest:
            continue
        if not packet.get("proof"):
            continue
        return True
    return False


def phase(d: str) -> str:
    manifest_path = core._safe(d, core.MANIFEST)
    if not os.path.isfile(manifest_path):
        _recipe.load_recipe(d)
        return "draft"
    v = verify(d)
    if not v["ok"]:
        raise core.ClaimError(f"claim identity does not match its sealed manifest: {d!r}")
    if _signed(d, v["root"]):
        return "signed"
    return "sealed"


# ---------------------------------------------------------------------------
# sign_node: the signature-chain fold, bottom-anchored
# ---------------------------------------------------------------------------
def sign_node(root_hash: str, digest: str, links) -> str:
    payload = {"root": root_hash, "build_digest": digest, "links": sorted(links)}
    return hashlib.sha256(json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# rebuild: regrow the generated outputs until the gates pass
# ---------------------------------------------------------------------------
def _snapshot_room(room: str, exclude_names) -> dict:
    snapshot = {}
    for dirpath, dirnames, filenames in os.walk(room):
        dirnames[:] = [dn for dn in dirnames if dn != ".reticuli"]
        for fn in filenames:
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, room)
            if rel in exclude_names:
                continue
            snapshot[rel] = core._hash_file(full)
    return snapshot


def _invoke_producer(step: dict, producer_cmd: str, room: str, guidance: str) -> None:
    output_abs = os.path.abspath(core._safe(room, step["output"]))
    os.makedirs(os.path.dirname(output_abs) or room, exist_ok=True)
    usage_path = os.path.abspath(os.path.join(room, core.USAGE))
    os.makedirs(os.path.dirname(usage_path), exist_ok=True)
    if os.path.isfile(usage_path):
        os.remove(usage_path)

    env = dict(os.environ)
    env[core._ENV_OUTPUT] = output_abs
    env[core._ENV_REQUEST] = guidance or ""
    env[core._ENV_USAGE] = usage_path

    t0 = time.monotonic()
    done = subprocess.run(producer_cmd, shell=True, cwd=os.path.abspath(room), env=env,
                          capture_output=True, timeout=core.PRODUCER_TIMEOUT, check=False)
    elapsed = time.monotonic() - t0
    if done.returncode != 0:
        detail = (done.stderr or done.stdout or b"").decode("utf-8", errors="replace")
        raise core.ClaimError(
            f"producer failed for {step['output']!r}: {detail[-300:]}")

    event = {"event": "oracle", "calls": 1, "seconds": elapsed}
    vendor = os.environ.get(core._ENV_VENDOR)
    model = os.environ.get(core._ENV_MODEL)
    if vendor:
        event["vendor"] = vendor
    if model:
        event["model"] = model
    if vendor or model:
        event["blind"] = True

    if os.path.isfile(usage_path):
        usage = None
        try:
            with open(usage_path, "r", encoding="utf-8") as f:
                usage = json.load(f)
        except (OSError, json.JSONDecodeError):
            usage = None
        if isinstance(usage, dict):
            for key in ("tokens", "usd", "calls"):
                v = usage.get(key)
                if isinstance(v, (int, float)) and not isinstance(v, bool):
                    event[key] = v

    _run.ledger(room, event)


def rebuild(d: str, producer_cmd: str, into: str, *, produce_from=None, input_from=None) -> dict:
    produce_from = produce_from or {}
    input_from = input_from or {}
    into_abs = os.path.abspath(into)

    if os.path.isdir(into_abs):
        if os.listdir(into_abs):
            raise core.ClaimError(f"rebuild target already holds bytes: {into!r}")
    else:
        os.makedirs(into_abs)

    recipe = _recipe.load_recipe(d)
    missing = _run.preflight(recipe)
    if missing:
        raise core.ClaimError(f"environment: host is missing {missing}")

    _build._materialize(d, into_abs, recipe)
    for name, src in input_from.items():
        core._copy_into(into_abs, name, src)

    outputs = {s["output"] for s in recipe.get("step", []) if s.get("kind") == "produce"}
    before = _snapshot_room(into_abs, outputs)

    for step in recipe.get("step", []):
        if step.get("kind") != "produce":
            continue
        output = step["output"]
        if output in produce_from:
            core._copy_into(into_abs, output, produce_from[output])
            _run.ledger(into_abs, {"event": "reuse", "output": output})
            continue
        guidance = step.get("guidance") or step.get("request") or ""
        _invoke_producer(step, producer_cmd, into_abs, guidance)

    after = _snapshot_room(into_abs, outputs)
    if before != after:
        raise core.ClaimError(
            "a producer rewrote pinned bytes outside its declared output")

    host = core._judging_host()
    backend = _run.sandbox_backend()
    _run.ledger(into_abs, {"event": "environment", "python": host["python"],
                           "quarantine": backend})

    for step in recipe.get("step", []):
        if step.get("kind") != "gate":
            continue
        result = run_gate(step["run"], into_abs, recipe)
        _run.ledger(into_abs, {"event": "gate", "output": step["output"],
                               "status": result["status"],
                               "quarantine": result["quarantine"]})
        if result["status"] != "ok":
            raise core.ClaimError(f"gate {step['output']!r} did not pass: {result['status']}")

    return _seal.seal(into_abs)


# ---------------------------------------------------------------------------
# record_proof: run the crosscheck; on a pass, seal the proof onto M1
# ---------------------------------------------------------------------------
def _anchor_principals(anchor_path: str) -> list:
    principals = []
    with open(anchor_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            principals.append(line.split()[0])
    return principals


def record_proof(m1: str, m2: str, m3: str) -> dict:
    if not os.path.isdir(m1):
        raise core.ClaimError("a proof requires M1 to be a directory")
    result = crosscheck(m1, m2, m3)
    if not result["satisfied"]:
        return {"proof_recorded": False, **result}

    records_trail = []
    for leg_path in (m2, m3):
        if os.path.isdir(leg_path):
            continue
        anchor = os.environ.get(core._ENV_SIGNERS)
        if not anchor or not os.path.isfile(anchor):
            raise core.ClaimError(f"no trust anchor for record leg {leg_path!r}")
        signer_id = None
        for candidate in _anchor_principals(anchor):
            try:
                record_signer(leg_path, anchor, signer=candidate)
                signer_id = candidate
                break
            except core.ClaimError:
                continue
        if signer_id is None:
            raise core.ClaimError(f"record leg {leg_path!r} has no anchored signature")
        doc = record_read(leg_path)
        records_trail.append({"digest": record_digest(doc), "signer": signer_id})

    proof = {"kind": "crosscheck"}
    if records_trail:
        proof["records"] = records_trail
    manifest = read_manifest(m1)
    manifest["proof"] = proof
    core._write_json(core._safe(m1, core.MANIFEST), manifest)
    return {"proof_recorded": True, **result}
