"""reticuli.registry -- claims meet claims: the claim store, content-
addressed component links, and DAG-aware rebuild (`spec/layers.md`).

A **workspace** is a directory whose `.reticuli/sealed/<name>/` holds
claims the way a claim's own `.reticuli/sealed/<name>/` holds the
components it was built on -- the same on-disk shape at two scales.
`detect_components` finds a content-addressed link from a workspace's
plain file to a sealed claim's pinned output; `seal_with` records such
links (and a recorded proof) onto a claim's manifest; `claims` / `deps`
read the store back as a table and a dependency graph; `rebuild_chain`
regrows a claim's generated bytes leaf-first over its declared
components, either independently re-deriving each one or (`reuse=True`)
threading through the bytes already sealed; `audit_deep` / `crosscheck_deep`
re-earn every composed layer, not just the top one; `sign_root` folds a
bottom-anchored signature-chain node over the same DAG; `pull` and
`structure` round out the surface.
"""
import os
import shutil
import tempfile

from . import _util
from . import kernel

_SEALED = "sealed"


def _sealed_root(ws: str) -> str:
    return os.path.join(ws, kernel.STORE, _SEALED)


def _components_of(manifest: dict) -> list:
    return manifest.get("components") or []


# ---------------------------------------------------------------------------
# Content-addressed component discovery
# ---------------------------------------------------------------------------
def detect_components(ws: str, names) -> list:
    """Which of `names` (files in `ws`) content-match a pinned/validated
    output of a claim already sealed in `ws`'s store -- a link a claim can
    then be sealed with (`seal_with`)."""
    catalog = []
    sealed_root = _sealed_root(ws)
    if os.path.isdir(sealed_root):
        for entry in sorted(os.listdir(sealed_root)):
            comp_dir = os.path.join(sealed_root, entry)
            if not os.path.isdir(comp_dir):
                continue
            try:
                manifest = kernel.read_manifest(comp_dir)
                recipe = kernel.load_recipe(comp_dir)
            except kernel.ClaimError:
                continue
            for step in recipe.get("step", []):
                cls = step.get("class")
                if cls is None:
                    cls = "generated" if step.get("kind") == "produce" else "pinned"
                if cls == "generated":
                    continue
                output = step.get("output")
                path = os.path.join(comp_dir, output)
                if os.path.isfile(path):
                    catalog.append((entry, output, kernel._hash_file(path), manifest["root"]))

    links = []
    for name in names:
        path = os.path.join(ws, name)
        if not os.path.isfile(path):
            continue
        digest = kernel._hash_file(path)
        for comp_name, output, comp_digest, comp_root in catalog:
            if comp_digest == digest:
                links.append({"input": name, "component": comp_name,
                              "root": comp_root, "output": output})
                break
    return links


# ---------------------------------------------------------------------------
# Sealing with extra manifest residue: component links, a recorded proof
# ---------------------------------------------------------------------------
def seal_with(d: str, *, components=None, proof=None) -> dict:
    """`kernel.seal(d)`, plus recording `components` and/or `proof` onto
    the manifest (`spec/claim-format.md`: the manifest may carry both)."""
    manifest = kernel.seal(d)
    if components is not None:
        manifest["components"] = components
    if proof is not None:
        manifest["proof"] = proof
    if components is not None or proof is not None:
        _util.write_json(_util.safe_path(d, kernel.MANIFEST), manifest)
    return manifest


# ---------------------------------------------------------------------------
# The claim store, read back as a table and as a dependency graph
# ---------------------------------------------------------------------------
def claims(ws: str) -> list:
    """One row per claim sealed in `ws`'s store: `{name, root, phase}`."""
    rows = []
    sealed_root = _sealed_root(ws)
    if not os.path.isdir(sealed_root):
        return rows
    for entry in sorted(os.listdir(sealed_root)):
        comp_dir = os.path.join(sealed_root, entry)
        if not os.path.isdir(comp_dir):
            continue
        try:
            manifest = kernel.read_manifest(comp_dir)
            phase = kernel.phase(comp_dir)
        except kernel.ClaimError:
            continue
        rows.append({"name": manifest["name"], "root": manifest["root"], "phase": phase})
    return rows


def deps(ws: str) -> dict:
    """The store as a dependency graph: one entry per claim, each with
    `depends_on`, one entry per declared component link and whether it
    resolves (`ok`/`broken`/`missing`) against the store."""
    sealed_root = _sealed_root(ws)
    rows = []
    if os.path.isdir(sealed_root):
        for entry in sorted(os.listdir(sealed_root)):
            comp_dir = os.path.join(sealed_root, entry)
            if not os.path.isdir(comp_dir):
                continue
            try:
                manifest = kernel.read_manifest(comp_dir)
            except kernel.ClaimError:
                continue
            depends_on = []
            for link in _components_of(manifest):
                comp_name = link.get("component")
                target_dir = os.path.join(sealed_root, comp_name)
                status = "missing"
                if os.path.isdir(target_dir):
                    try:
                        target_manifest = kernel.read_manifest(target_dir)
                        status = "ok" if target_manifest["root"] == link.get("root") else "broken"
                    except kernel.ClaimError:
                        status = "broken"
                depends_on.append({"component": comp_name, "status": status})
            rows.append({"name": manifest["name"], "root": manifest["root"],
                         "depends_on": depends_on})
    return {"claims": rows}


def structure(ws: str) -> dict:
    """A small structural summary of `ws`'s store: claims and their edges."""
    return deps(ws)


# ---------------------------------------------------------------------------
# Resolving a declared component to an actual directory: a workspace's
# store, or a claim's own embedded store, in that order.
# ---------------------------------------------------------------------------
def _resolve_component_dir(d: str, ws, name: str):
    if ws:
        candidate = os.path.join(_sealed_root(ws), name)
        if os.path.isdir(candidate):
            return candidate
    candidate = os.path.join(d, kernel.STORE, _SEALED, name)
    if os.path.isdir(candidate):
        return candidate
    return None


# ---------------------------------------------------------------------------
# pull: materialize a claim's declared content into a fresh workspace
# ---------------------------------------------------------------------------
def pull(d: str, ws2: str) -> dict:
    """Copy `d`'s declared content (inputs and every present step output)
    into `ws2`, flat -- `d` becomes a dependency of the fresh workspace."""
    os.makedirs(ws2, exist_ok=True)
    manifest = kernel.read_manifest(d)
    recipe = kernel.load_recipe(d)
    names = set(_util.declared_inputs(d))
    for step in recipe.get("step", []):
        output = step.get("output")
        if output:
            names.add(output)
    for name in names:
        src = os.path.join(d, name)
        if os.path.isfile(src):
            dest = os.path.join(ws2, name)
            os.makedirs(os.path.dirname(dest) or ws2, exist_ok=True)
            shutil.copyfile(src, dest)
    return {"materialized": True, "root": manifest["root"]}


# ---------------------------------------------------------------------------
# sign_root: the bottom-anchored signature-chain fold
# ---------------------------------------------------------------------------
def sign_root(d: str, ws=None) -> str:
    v = kernel.verify(d)
    if not v["ok"]:
        raise kernel.ClaimError(f"claim identity does not hold: {d!r}")
    digest = kernel.build_digest(d)
    manifest = kernel.read_manifest(d)
    links = []
    for link in _components_of(manifest):
        comp_dir = _resolve_component_dir(d, ws, link["component"])
        if comp_dir is None:
            raise kernel.ClaimError(
                f"declared component missing from the registry: {link['component']!r}")
        links.append(sign_root(comp_dir, ws))
    return kernel.sign_node(v["root"], digest, links)


# ---------------------------------------------------------------------------
# rebuild_chain: DAG-aware rebuild, leaf-first
# ---------------------------------------------------------------------------
def rebuild_chain(d: str, producer_cmd: str, into: str, *, ws=None, reuse: bool = False) -> dict:
    into_abs = os.path.abspath(into)
    recipe = kernel.load_recipe(d)
    manifest = kernel.read_manifest(d)
    produce_outputs = {s["output"] for s in recipe.get("step", []) if s.get("kind") == "produce"}

    produce_from = {}
    input_from = {}
    rebuilt_components = []
    embed = []
    updated_components = []
    scratch_dirs = []

    try:
        for link in _components_of(manifest):
            name = link["component"]
            local_name = link["input"]
            comp_output = link.get("output", local_name)
            comp_dir = _resolve_component_dir(d, ws, name)
            if comp_dir is None:
                raise kernel.ClaimError(f"missing declared component: {name!r}")

            if reuse:
                source_dir = comp_dir
            else:
                tmp_into = tempfile.mkdtemp(prefix="reticuli-chain-")
                scratch_dirs.append(tmp_into)
                sub = rebuild_chain(comp_dir, producer_cmd, tmp_into, ws=ws, reuse=False)
                rebuilt_components.extend(sub["rebuilt_components"])
                rebuilt_components.append({"component": name, "root": sub["root"]})
                source_dir = tmp_into

            source_path = os.path.join(source_dir, comp_output)
            if local_name in produce_outputs:
                produce_from[local_name] = source_path
            else:
                input_from[local_name] = source_path

            source_manifest = kernel.read_manifest(source_dir)
            updated_components.append({"input": local_name, "component": name,
                                       "root": source_manifest["root"], "output": comp_output})
            embed.append((name, source_dir))

        result = kernel.rebuild(d, producer_cmd, into_abs,
                                produce_from=produce_from or None,
                                input_from=input_from or None)

        for name, source_dir in embed:
            dest = os.path.join(into_abs, kernel.STORE, _SEALED, name)
            if os.path.isdir(dest):
                shutil.rmtree(dest)
            shutil.copytree(source_dir, dest)

        if updated_components:
            manifest_now = seal_with(into_abs, components=updated_components)
        else:
            manifest_now = result

        return {"root": manifest_now["root"], "rebuilt_components": rebuilt_components}
    finally:
        for tmp in scratch_dirs:
            shutil.rmtree(tmp, ignore_errors=True)


# ---------------------------------------------------------------------------
# audit_deep: re-earn every composed layer, not just the top one
# ---------------------------------------------------------------------------
def audit_deep(d: str) -> dict:
    top = kernel.audit(d)
    manifest = kernel.read_manifest(d)
    ok = bool(top.get("ok"))
    layers = []
    for link in _components_of(manifest):
        name = link["component"]
        local_name = link["input"]
        comp_output = link.get("output", local_name)
        comp_dir = os.path.join(d, kernel.STORE, _SEALED, name)
        if not os.path.isdir(comp_dir):
            layers.append({"name": name, "root": link.get("root"), "ok": False,
                           "status": "unresolved", "bytes_from": [local_name]})
            ok = False
            continue
        try:
            comp_root = kernel.read_manifest(comp_dir)["root"]
        except kernel.ClaimError:
            comp_root = None
        local_path = os.path.join(d, local_name)
        aud = kernel.audit(comp_dir, produce_from={comp_output: local_path})
        layer_ok = bool(aud.get("ok"))
        layers.append({"name": name, "root": comp_root, "ok": layer_ok,
                       "status": "ok" if layer_ok else "broken", "bytes_from": [local_name]})
        if not layer_ok:
            ok = False
    return {"ok": ok, "layers": layers, "top": top}


def crosscheck_deep(m1: str, m2: str, m3: str, mutants=None) -> dict:
    if mutants is not None:
        shallow = kernel.crosscheck(m1, m2, m3, mutants=mutants)
    else:
        shallow = kernel.crosscheck(m1, m2, m3)
    deep_ok = True
    for leg in (m1, m2, m3):
        if os.path.isdir(leg) and not audit_deep(leg)["ok"]:
            deep_ok = False
    result = dict(shallow)
    result["satisfied"] = bool(shallow["satisfied"]) and deep_ok
    result["deep_ok"] = deep_ok
    return result


def record_proof_deep(m1: str, m2: str, m3: str) -> dict:
    tm = crosscheck_deep(m1, m2, m3)
    if not tm["satisfied"]:
        return {"proof_recorded": False, **tm}
    return kernel.record_proof(m1, m2, m3)
