"""reticuli.transfer -- deterministic export/import of a claim
(`spec/layers.md`).

`export` walks the recipe, never the filesystem, so only declared bytes
travel: the recipe itself, declared inputs, every present step output
(withheld when `blind=True` and the step is `generated` -- the rebuilder's
room), the manifest, and any attestation residue. A claim's own generated
bytes never leave home for a *component* it ships: a declared component's
claim (recipe, inputs, pins, its own manifest) travels under
`.reticuli/deps/<name>/`, its generated bytes excluded regardless of the
top claim's own `blind` flag. `import_` is the inverse -- it also turns
`.reticuli/deps/<name>/` back into `.reticuli/sealed/<name>/`, so an
imported claim's component layers stay walkable -- and verifies on
arrival. Two exports of the same claim are byte-identical: entries are
gathered from the recipe, sorted, and written with a fixed, fully-zeroed
header (no timestamp, no host-specific uid/gid/mode).
"""
import io
import os
import shutil
import tarfile

from . import _util
from . import attest as _attest
from . import kernel

_SEALED = "sealed"
_DEPS = "deps"


def _own_members(d: str, blind: bool) -> list:
    """`(arcname, abs_path)` pairs for `d`'s own declared content."""
    members = []
    for recipe_name in (kernel.RECIPE, kernel.LEGACY_RECIPE):
        p = os.path.join(d, recipe_name)
        if os.path.isfile(p):
            # the transfer format's own canonical recipe name (`_util.RECIPE`)
            # -- distinct from whichever of the two live on-disk names this
            # claim happens to use -- so a claim rebuilt under one name and
            # a claim authored under the other export identically.
            members.append((_util.RECIPE, p))
            break

    recipe = kernel.load_recipe(d)
    for name in _util.declared_inputs(d):
        p = os.path.join(d, name)
        if os.path.isfile(p):
            members.append((name, p))

    for step in recipe.get("step", []):
        output = step.get("output")
        if not output:
            continue
        cls = step.get("class")
        if cls is None:
            cls = "generated" if step.get("kind") == "produce" else "pinned"
        if cls == "generated" and blind:
            continue
        p = os.path.join(d, output)
        if os.path.isfile(p):
            members.append((output, p))

    manifest_path = os.path.join(d, kernel.MANIFEST)
    if os.path.isfile(manifest_path):
        members.append((kernel.MANIFEST, manifest_path))

    attest_dir = os.path.join(d, _attest.ATTEST)
    if os.path.isdir(attest_dir):
        for dirpath, _dirnames, filenames in os.walk(attest_dir):
            for fn in filenames:
                fp = os.path.join(dirpath, fn)
                members.append((os.path.relpath(fp, d), fp))

    return members


def _dep_members(base: str, name: str) -> list:
    """`(arcname, abs_path)` pairs for a declared component `name`,
    embedded within `base`'s own store -- always blind, rooted under
    `.reticuli/deps/<name>/`, recursing into any components of its own."""
    comp_dir = os.path.join(base, kernel.STORE, _SEALED, name)
    if not os.path.isdir(comp_dir):
        return []
    out = []
    prefix = f"{kernel.STORE}/{_DEPS}/{name}"
    for rel, p in _own_members(comp_dir, blind=True):
        out.append((f"{prefix}/{rel}", p))
    try:
        comp_manifest = kernel.read_manifest(comp_dir)
    except kernel.ClaimError:
        comp_manifest = {}
    for link in comp_manifest.get("components", []) or []:
        for rel, p in _dep_members(comp_dir, link["component"]):
            out.append((f"{prefix}/{rel}", p))
    return out


def export(d: str, tar_path: str, blind: bool = False) -> None:
    """Write `d`'s declared content to `tar_path`, deterministically."""
    members = _own_members(d, blind)
    manifest_path = os.path.join(d, kernel.MANIFEST)
    if os.path.isfile(manifest_path):
        manifest = kernel.read_manifest(d)
        for link in manifest.get("components", []) or []:
            members.extend(_dep_members(d, link["component"]))

    by_name = {}
    for arcname, path in members:
        by_name[arcname] = path

    with tarfile.open(tar_path, "w") as tar:
        for arcname in sorted(by_name):
            path = by_name[arcname]
            with open(path, "rb") as f:
                data = f.read()
            info = tarfile.TarInfo(name=arcname)
            info.size = len(data)
            info.mtime = 0
            info.mode = 0o644
            info.uid = 0
            info.gid = 0
            info.uname = ""
            info.gname = ""
            tar.addfile(info, io.BytesIO(data))


def import_(tar_path: str, dest_dir: str) -> dict:
    """Extract `tar_path` into `dest_dir`, reconstitute any component
    layers, and verify the received bytes."""
    os.makedirs(dest_dir, exist_ok=True)
    dest_real = os.path.realpath(dest_dir)
    with tarfile.open(tar_path) as tar:
        for member in tar.getmembers():
            target = os.path.realpath(os.path.join(dest_dir, member.name))
            if target != dest_real and not target.startswith(dest_real + os.sep):
                raise kernel.ClaimError(f"tar member escapes destination: {member.name!r}")
        try:
            tar.extractall(dest_dir, filter="data")
        except TypeError:
            tar.extractall(dest_dir)

    deps_root = os.path.join(dest_dir, kernel.STORE, _DEPS)
    if os.path.isdir(deps_root):
        sealed_root = os.path.join(dest_dir, kernel.STORE, _SEALED)
        os.makedirs(sealed_root, exist_ok=True)
        for name in os.listdir(deps_root):
            src = os.path.join(deps_root, name)
            dst = os.path.join(sealed_root, name)
            if os.path.isdir(dst):
                shutil.rmtree(dst)
            shutil.copytree(src, dst)
        shutil.rmtree(deps_root)

    v = kernel.verify(dest_dir)
    return {"ok": v["ok"], "root": v["root"]}
