"""Building rooms: audit (re-earn, cold) and rebuild (regrow, then earn).

A room is a fresh directory holding exactly what a judge or a producer is
entitled to see: the recipe as the root reads it, every pinned input, and
every already-pinned (`pinned`-class) step output -- never a validated
(gate) output, which must be earned fresh inside the room.

`_materialize` builds that room. At format < 3 the recipe is copied byte
for byte, under its original name, because formats 1-2 hash the whole
file; at format >= 3 the room instead receives the PREIMAGE recipe,
written out as TOML under the canonical name -- the recipe the root was
actually computed from, with producer guidance stripped and (format 4)
its step list already a canonical set. Either way the room's recipe is
provably the one the identity names, not a reconstruction a gate could be
fooled by.

`audit` materializes a judging room with the claim's current generated
bytes already in place, re-runs every gate inside it, and classifies each
outcome against the bytes already pinned at the claim's own root
(`_compare_pin`) -- earned fresh and matching is `reproduced`; earned
fresh and different is `mismatch`; the audit's gate rows carry the jail
that earned them. A tampered pinned input moves the root before any gate
runs, so audit refuses at the identity check and never reaches a gate.

`rebuild` materializes a production room with no generated bytes at all,
runs the caller's producer command inside it (`_produce`) -- unsandboxed,
the caller's own environment and network reachability, told which output
to write over `RETICULI_OUTPUT`/`RETICULI_OUTPUTS` -- then runs every
gate and seals the room. The producer is the caller's oracle: the kernel
scrubs its environment to the same minimal allowlist a gate gets (which
already keeps `HOME`, so credentials living there travel too) but adds no
sandbox of its own, so the producer's reach is exactly the caller's.
`producer_env` is the one other road a credential may travel, filtered by
`_authorized` so a caller cannot use it to override a name the kernel
itself controls.

`_ssh_verify` is the generic `ssh-keygen -Y verify` primitive the record
and signing layers build on (`spec/record.md`); unexercised by this gate,
implemented to the letter of that document.

Stdlib only, never the network except through a caller's own producer.
"""
import json
import os
import shutil
import subprocess
import tempfile
import time

from .core import (
    ClaimError,
    PRODUCER_TIMEOUT,
    RECIPE,
    USAGE,
    _ENV_CLAIM,
    _ENV_OUTPUT,
    _ENV_OUTPUTS,
    _ENV_REQUEST,
    _ENV_USAGE,
    _KEEP_ENV,
    _copy_into,
    _hash_file,
    _safe,
)
from .identity import _claim_format, _preimage_recipe, build_digest, root as _root
from .recipe import _inputs, _steps, gates, load_recipe, produces, recipe_path
from .run import _scrub_env, ledger, preflight, run_gate, sandbox_backend
from .seal import read_manifest, seal


# ----------------------------------------------------------------- TOML out
def _toml_string(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20:
            out.append("\\u%04x" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return _toml_string(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(v) for v in value) + "]"
    if isinstance(value, dict):
        inner = ", ".join(f"{k} = {_toml_value(v)}" for k, v in value.items())
        return "{ " + inner + " }"
    raise ClaimError(f"cannot serialize recipe value to TOML: {value!r}")


def _recipe_to_toml(doc: dict) -> str:
    """The preimage recipe, written out as TOML a conforming reader parses
    back to the same tables -- the room's recipe, at format >= 3."""
    lines = []
    for key, value in doc.items():
        if key == "step":
            continue
        if isinstance(value, dict):
            lines.append(f"[{key}]")
            for k, v in value.items():
                lines.append(f"{k} = {_toml_value(v)}")
            lines.append("")
        else:
            lines.append(f"{key} = {_toml_value(value)}")
    for step in doc.get("step", []):
        lines.append("[[step]]")
        for k, v in step.items():
            lines.append(f"{k} = {_toml_value(v)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# --------------------------------------------------------------- the room
def _materialize(recipe: dict, src: str, dest: str, *,
                  include_generated: bool = False, input_from: dict = None) -> None:
    """Build a room at `dest`: the recipe as the root reads it, every
    pinned input, every already-`pinned`-class step output, and -- when
    `include_generated` -- every generated output present now. Never a
    validated (gate) output: those are earned fresh inside the room.
    """
    if os.path.exists(dest) and os.listdir(dest):
        raise ClaimError(f"refused non-empty room target: {dest!r}")
    os.makedirs(dest, exist_ok=True)

    if _claim_format(recipe) >= 3:
        with open(os.path.join(dest, RECIPE), "w", encoding="utf-8") as f:
            f.write(_recipe_to_toml(_preimage_recipe(recipe)))
    else:
        src_recipe = recipe_path(src)
        _copy_into(src_recipe, os.path.join(dest, os.path.basename(src_recipe)))

    for path in _inputs(recipe, src):
        source = (input_from or {}).get(path) or _safe(src, path)
        _copy_into(source, _safe(dest, path))

    for step in _steps(recipe):
        if step["kind"] == "produce" and step.get("class", "generated") == "pinned":
            source = _safe(src, step["output"])
            if os.path.isfile(source):
                _copy_into(source, _safe(dest, step["output"]))

    if include_generated:
        for step in produces(recipe):
            if step.get("class", "generated") != "generated":
                continue
            source = _safe(src, step["output"])
            if os.path.isfile(source):
                _copy_into(source, _safe(dest, step["output"]))


def _compare_pin(d: str, room: str, output: str) -> bool:
    """Whether a gate output just earned in `room` hashes the same as the
    bytes already pinned at `d` -- `reproduced` versus `mismatch`."""
    return _hash_file(_safe(d, output)) == _hash_file(_safe(room, output))


# ------------------------------------------------------------- producing
def _step_guidance(step: dict):
    """A produce step's hint for a producer, under either spelling; `None`
    if the step carries neither."""
    for key in ("guidance", "request"):
        if key in step:
            return step[key]
    return None


def _authorized(name: str) -> bool:
    """Whether a caller-supplied `producer_env` key may enter a producer's
    environment: anything except a name the kernel itself controls."""
    return name not in _KEEP_ENV and not name.startswith("RETICULI_")


def _read_usage(path: str) -> dict:
    """A producer's self-reported usage from `RETICULI_USAGE`. Absent or
    unreadable is empty, never guessed at; `seconds` is never read here --
    it is the kernel's own measurement, added by the caller."""
    if not path or not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            doc = json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(doc, dict):
        return {}
    usage = {}
    for key in ("usd", "tokens", "calls"):
        value = doc.get(key)
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            usage[key] = value
    for key in ("vendor", "model", "blind", "cutoff"):
        if key in doc:
            usage[key] = doc[key]
    return usage


def _produce(recipe: dict, room: str, producer: str, *,
             guidance: bool = True, producer_env: dict = None) -> dict:
    """Run the producer command inside `room`: unsandboxed, the caller's
    own environment and reachability, told which output(s) to write.
    Returns the producer's self-reported usage, plus the kernel's own
    wall-clock measurement of the call.
    """
    env = _scrub_env()

    outputs = [s["output"] for s in produces(recipe)
               if s.get("class", "generated") == "generated" and "from" not in s]
    env[_ENV_OUTPUTS] = json.dumps(outputs)
    if outputs:
        env[_ENV_OUTPUT] = os.path.join(os.path.realpath(room), outputs[0])
    env[_ENV_CLAIM] = recipe.get("claim", {}).get("name", "")

    usage_path = os.path.join(room, USAGE)
    os.makedirs(os.path.dirname(usage_path), exist_ok=True)
    env[_ENV_USAGE] = usage_path

    if guidance:
        for step in produces(recipe):
            text = _step_guidance(step)
            if text is not None:
                env[_ENV_REQUEST] = text
                break

    for key, value in (producer_env or {}).items():
        if _authorized(key):
            env[key] = value

    start = time.monotonic()
    try:
        proc = subprocess.run(
            ["/bin/sh", "-c", producer], cwd=room, env=env,
            timeout=PRODUCER_TIMEOUT, capture_output=True,
        )
    except subprocess.TimeoutExpired as e:
        raise ClaimError(f"producer timed out: {producer!r}") from e
    elapsed = time.monotonic() - start

    if proc.returncode != 0:
        raise ClaimError(
            f"producer failed (exit {proc.returncode}): {producer!r}: "
            f"{proc.stderr.decode('utf-8', 'replace')}"
        )

    usage = _read_usage(usage_path)
    usage["seconds"] = elapsed
    return usage


# ------------------------------------------------------------------- audit
def audit(d: str) -> dict:
    """Re-earn every gate, cold: nothing regrown, nothing trusted.

    A tampered pinned input moves the root before any gate runs, so this
    refuses at the identity check. Otherwise every gate is re-run inside a
    fresh judging room and classified against the bytes already pinned at
    `d`'s own root. See `spec/verification.md`.
    """
    recipe = load_recipe(d)
    manifest = read_manifest(d)
    recomputed = _root(recipe, d)
    if recomputed != manifest["root"]:
        return {
            "ok": False,
            "verdict": "identity mismatch: the bytes present no longer "
                       "recompute the sealed root",
            "root": recomputed,
            "gates": [],
        }

    missing = preflight(recipe)
    room = tempfile.mkdtemp()
    try:
        _materialize(recipe, d, room, include_generated=True)
        results = []
        for step in gates(recipe):
            output = step["output"]
            if missing:
                results.append({"output": output, "status": "environment",
                                 "quarantine": "none"})
                continue
            outcome = run_gate(step["run"], room, recipe)
            if outcome["status"] == "ok":
                status = "reproduced" if _compare_pin(d, room, output) else "mismatch"
            else:
                status = outcome["status"]
            results.append({"output": output, "status": status,
                             "quarantine": outcome["quarantine"]})
        ok = all(g["status"] == "reproduced" for g in results)
        return {
            "ok": ok,
            "verdict": "earned" if ok else "broken",
            "root": recomputed,
            "gates": results,
        }
    finally:
        shutil.rmtree(room, ignore_errors=True)


# ----------------------------------------------------------------- rebuild
def rebuild(d: str, producer, into: str, *, produce_from: dict = None,
            input_from: dict = None, guidance: bool = True,
            producer_env: dict = None) -> dict:
    """Regrow `d`'s generated outputs into a fresh room at `into`, via
    `producer`, until every gate passes there; seal the room and append
    its ledger. See `spec/verification.md` and `spec/kernel-api.md`.
    """
    recipe = load_recipe(d)
    _materialize(recipe, d, into, include_generated=False, input_from=input_from)

    for output, source in (produce_from or {}).items():
        _copy_into(source, _safe(into, output))

    usage = {}
    if producer is not None:
        usage = _produce(recipe, into, producer, guidance=guidance,
                          producer_env=producer_env)

    missing = preflight(recipe)
    results = []
    for step in gates(recipe):
        output = step["output"]
        if missing:
            results.append({"output": output, "status": "environment",
                             "quarantine": "none"})
            continue
        outcome = run_gate(step["run"], into, recipe)
        status = "reproduced" if outcome["status"] == "ok" else outcome["status"]
        results.append({"output": output, "status": status,
                         "quarantine": outcome["quarantine"]})

    if not all(g["status"] == "reproduced" for g in results):
        raise ClaimError(f"rebuild did not earn its gates: {results!r}")

    manifest = seal(into)
    ledger(into, dict(usage))

    return {
        "root": manifest["root"],
        "name": manifest["name"],
        "build_digest": build_digest(into),
        "gates": results,
        "quarantine": results[0]["quarantine"] if results else sandbox_backend(),
    }


# --------------------------------------------------------------- ssh verify
def _ssh_verify(allowed_signers: str, identity: str, namespace: str,
                 message: bytes, signature: bytes) -> bool:
    """Verify a detached `ssh-keygen -Y` signature over `message`, in
    `namespace` for `identity`, against `allowed_signers`. False on any
    failure -- an unverifiable signature is simply not trusted, never a
    crash (`spec/record.md`).
    """
    try:
        with tempfile.NamedTemporaryFile(suffix=".sig") as sig_f:
            sig_f.write(signature)
            sig_f.flush()
            proc = subprocess.run(
                ["ssh-keygen", "-Y", "verify", "-f", allowed_signers,
                 "-I", identity, "-n", namespace, "-s", sig_f.name],
                input=message, capture_output=True, timeout=30,
            )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return proc.returncode == 0
