"""Identity: the root hash and the build digest (`spec/identity.md`).

A claim's root is a SHA-256 digest of a string-to-string map: the recipe
(canonically serialized, with producer `guidance`/`request` stripped at
format >= 3 and the step list canonicalized to a set at format >= 4), the
bytes of every pinned input, and the bytes of every non-generated step
output. The build digest is a SHA-256 over the sorted (path, hash) pairs of
every *present* generated output that does not carry a `from` key -- an
absent generated file is omitted, never an error, and a claim with none
digests the empty list.

`canonical_json` is exactly `json.dumps(obj, sort_keys=True)` with default
separators and ASCII escaping -- the one serialization both the root and the
build digest are built from, and the one the record format (`spec/record.md`)
reuses.
"""
import hashlib
import json
import os

from .core import DIGEST, GUIDANCE_KEYS, _hash_file, _safe
from .recipe import _inputs, _steps, load_recipe


def _canonical_json(obj) -> str:
    """The one serialization every preimage is built from."""
    return json.dumps(obj, sort_keys=True, ensure_ascii=True)


def _claim_format(recipe: dict) -> int:
    """The claim's declared format; absent means 1."""
    return recipe.get("claim", {}).get("format", 1)


def _preimage_recipe(recipe: dict) -> dict:
    """The recipe as it enters the root preimage: guidance stripped at
    format >= 3, the step list canonicalized to a set at format >= 4."""
    fmt = _claim_format(recipe)
    if fmt < 3 or "step" not in recipe:
        return recipe
    doc = dict(recipe)
    steps = [
        {k: v for k, v in step.items() if k not in GUIDANCE_KEYS}
        for step in recipe["step"]
    ]
    if fmt >= 4:
        steps = sorted(steps, key=_canonical_json)
    doc["step"] = steps
    return doc


def _parts(recipe: dict, d: str) -> dict:
    """The string-to-string map the root hashes."""
    parts = {"digest": DIGEST, "recipe": _canonical_json(_preimage_recipe(recipe))}
    for path in _inputs(recipe, d):
        parts["input:" + path] = _hash_file(_safe(d, path))
    for step in _steps(recipe):
        default = "generated" if step["kind"] == "produce" else "pinned"
        if step.get("class", default) != "generated":
            output = step["output"]
            parts["pinned:" + output] = _hash_file(_safe(d, output))
    return parts


def root(recipe: dict, d: str) -> str:
    """The claim's identity: sha256 of the canonical preimage."""
    preimage = _canonical_json(_parts(recipe, d)).encode("utf-8")
    return hashlib.sha256(preimage).hexdigest()


def build_digest(d: str) -> str:
    """The digest a signature binds: sha256 over the generated bytes
    present on disk, `from`-sourced outputs excluded, absent outputs
    omitted, the empty list's digest when none are present."""
    recipe = load_recipe(d)
    pairs = []
    for step in _steps(recipe):
        if step["kind"] != "produce" or "from" in step:
            continue
        if step.get("class", "generated") != "generated":
            continue
        output = step["output"]
        path = _safe(d, output)
        if not os.path.isfile(path):
            continue
        pairs.append([output, _hash_file(path)])
    pairs.sort(key=lambda pair: pair[0])
    return hashlib.sha256(_canonical_json(pairs).encode("utf-8")).hexdigest()
