"""The argv grammar: fourteen porcelain verbs, their folded aliases, and the
plumbing (`hook`, `help`, `completion`) -- `checks/parser_check.py`, this
module's definition.

`PORCELAIN` and `ALIASES` are the single source of truth: `_parser()` builds
every subcommand from them (plus the three plumbing verbs), and `verbs()`
reads the names back off the parser it built -- so the registered grammar
and the advertised one cannot drift apart. `_completion` does the same: it
lists `verbs()`, not a second hand-written roster, so a shell's completion
script always matches whatever is actually registered.

A handful of v1-era verbs were retired outright (`seal`, `hooks`, `tree`,
`claims`, `attest`, and the still-older `condense`, `realize`, `prove`,
`mint`, `records`, `hydrate`, `inspect`): each was folded into a flag on a
surviving porcelain verb rather than kept as its own top-level word. `_FOLDED`
records where each one went, so `ret help -a` can still explain an old
spelling instead of just failing on it.

Built from the standard library only -- this module parses argv, it does not
dispatch to the kernel or any layer above it.
"""
import argparse

PORCELAIN = (
    "init", "run", "status", "pack",
    "pull", "export", "import",
    "verify", "audit", "assess",
    "rebuild", "crosscheck",
    "record", "sign",
)

# Short, convenient alternate spellings for a still-live porcelain verb --
# distinct from the retired v1 spellings in `_FOLDED` below, which name no
# verb at all any more.
ALIASES = {
    "ls": "status",
    "check": "verify",
}

_PLUMBING = ("hook", "help", "completion")

_SHORT_HELP = {
    "init": "initialize a workspace",
    "run": "run and observe a command",
    "status": "show work, claims, and unresolved inputs",
    "pack": "create a claim from a project",
    "pull": "add another claim as a dependency",
    "export": "write a portable claim archive",
    "import": "restore a claim archive",
    "verify": "verify claim identity",
    "audit": "rerun acceptance criteria",
    "assess": "measure specification strength",
    "rebuild": "rebuild an implementation from a claim",
    "crosscheck": "compare independent realizations",
    "record": "write an execution record",
    "sign": "authorize a claim or proof",
    "hook": "report one coding-agent event (plumbing)",
    "help": "show detailed help for a command",
    "completion": "print a shell completion script",
}

_FULL_HELP = {
    "init": "Marks a workspace as a session: creates its store directory "
            "and, unless --no-agent, wires the coding-agent handshake.",
    "run": "Runs a command inside a workspace and records it to the "
           "session's trace, the same way a hook-reported tool call would.",
    "status": "Shows a workspace's unresolved inputs and known claims. "
               "--tree shows the dependency tree; --claims lists claims.",
    "pack": "Builds a claim from a project's traced session. --accept "
             "seals the claim once it is packed.",
    "pull": "Adds another claim as a dependency of the workspace at --into.",
    "export": "Writes a claim (and its dependency closure) to a portable "
               "archive at --out. --blind omits generated bytes.",
    "import": "Restores a claim archive into --into.",
    "verify": "Checks a claim's identity: that its root matches its "
               "recorded manifest and inputs.",
    "audit": "Reruns a claim's acceptance criteria against its generated "
              "bytes.",
    "assess": "Measures how strongly a claim's acceptance criteria pin its "
               "generated bytes, by sampling mutants.",
    "rebuild": "Rebuilds a claim's generated bytes from a producer, into "
                "--into.",
    "crosscheck": "Compares three independent manifests for the same "
                   "claim and reports where they agree or diverge.",
    "record": "Writes an execution record for a claim. --key and --as "
               "authorize it; --check verifies an existing record instead "
               "of writing one.",
    "sign": "Authorizes a claim or a proof with --key.",
    "hook": "Reports one coding-agent event, read as JSON from stdin.",
    "help": "Shows detailed help for a command. -a lists everything, "
             "including accepted older spellings.",
    "completion": "Prints a shell completion script.",
}

# v1-era verbs that no longer name anything: each was folded into a flag on
# a surviving porcelain verb (or, for the still-older names, into the verb
# that eventually replaced it). Kept here only so `ret help -a` can explain
# an old spelling rather than just refusing it.
_FOLDED = {
    "seal": "pack --accept",
    "hooks": "init (wires the agent)",
    "tree": "status --tree",
    "claims": "status --claims",
    "attest": "record --key --as / --check",
    "condense": "pack",
    "realize": "rebuild",
    "prove": "crosscheck",
    "mint": "sign",
    "records": "status --claims",
    "hydrate": "rebuild",
    "inspect": "status",
}

_DESC = """Reticuli records and reproduces software claims.

Authoring
    init        initialize a workspace
    run         run and observe a command
    status      show work, claims, and unresolved inputs
    pack        create a claim from a project

Composition and transport
    pull        add another claim as a dependency
    export      write a portable claim archive
    import      restore a claim archive

Verification
    verify      verify claim identity
    audit       rerun acceptance criteria
    assess      measure specification strength

Reconstruction
    rebuild     rebuild an implementation from a claim
    crosscheck  compare independent realizations

Evidence
    record      write an execution record
    sign        authorize a claim or proof"""

_EPILOG = """See 'ret <command> -h' for command usage.
See 'ret help <command>' for detailed help; 'ret help -a' lists everything,
including accepted older spellings."""


def _add_verbose_json(sp) -> None:
    """Add the two flags every porcelain subcommand accepts: `--json` for
    machine-readable output and `-v/--verbose` for progress detail."""
    sp.add_argument("--json", action="store_true",
                     help="emit machine-readable JSON")
    sp.add_argument("-v", "--verbose", action="store_true",
                     help="emit progress detail")


def _setup_init(sp) -> None:
    sp.add_argument("path", nargs="?", default=".", help="workspace to initialize")
    sp.add_argument("--no-agent", action="store_true",
                     help="skip wiring the coding-agent handshake")


def _setup_run(sp) -> None:
    sp.add_argument("cmd", nargs=argparse.REMAINDER,
                     help="the command to run and observe")
    sp.add_argument("--workspace", "-w", default=".",
                     help="the session workspace")


def _setup_status(sp) -> None:
    sp.add_argument("path", nargs="?", default=".", help="workspace to inspect")
    sp.add_argument("--tree", action="store_true",
                     help="show the dependency tree (folded from the retired `tree` verb)")
    sp.add_argument("--claims", action="store_true",
                     help="list known claims (folded from the retired `claims` verb)")


def _setup_pack(sp) -> None:
    sp.add_argument("path", nargs="?", default=".", help="project to pack into a claim")
    sp.add_argument("--name", help="the claim's name")
    sp.add_argument("--gate", help="the acceptance command")
    sp.add_argument("--accept", action="store_true",
                     help="seal the claim once packed (folded from the retired `seal` verb)")


def _setup_pull(sp) -> None:
    sp.add_argument("claim", help="the claim to add as a dependency")
    sp.add_argument("--into", default=".", help="the workspace to pull into")


def _setup_export(sp) -> None:
    sp.add_argument("path", nargs="?", default=".", help="claim to export")
    sp.add_argument("--out", required=True, help="the archive path to write")
    sp.add_argument("--blind", action="store_true",
                     help="omit generated bytes from the archive")


def _setup_import(sp) -> None:
    sp.add_argument("archive", help="the archive to restore")
    sp.add_argument("--into", default=".", help="where to restore it")


def _setup_verify(sp) -> None:
    sp.add_argument("path", nargs="?", default=".", help="claim to verify")


def _setup_audit(sp) -> None:
    sp.add_argument("path", nargs="?", default=".",
                     help="claim to rerun acceptance criteria for")


def _setup_assess(sp) -> None:
    sp.add_argument("path", nargs="?", default=".", help="claim to measure")
    sp.add_argument("--mutants", type=int, default=None,
                     help="how many mutants to sample")


def _setup_rebuild(sp) -> None:
    sp.add_argument("claim", help="the claim to rebuild")
    sp.add_argument("producer", help="the producer command or named producer")
    sp.add_argument("--into", default=".", help="where to materialize the rebuild")


def _setup_crosscheck(sp) -> None:
    sp.add_argument("manifests", nargs=3, metavar="MANIFEST",
                     help="the three independent manifests to compare")


def _setup_record(sp) -> None:
    sp.add_argument("path", nargs="?", default=".", help="claim to record against")
    sp.add_argument("--key", help="the signing key (folded from the retired `attest` verb)")
    sp.add_argument("--as", dest="identity", help="the identity to sign as")
    sp.add_argument("--check", action="store_true",
                     help="verify an existing record instead of writing one")


def _setup_sign(sp) -> None:
    sp.add_argument("path", nargs="?", default=".", help="claim or proof to authorize")
    sp.add_argument("--key", help="the signing key")


_VERB_SETUP = {
    "init": _setup_init,
    "run": _setup_run,
    "status": _setup_status,
    "pack": _setup_pack,
    "pull": _setup_pull,
    "export": _setup_export,
    "import": _setup_import,
    "verify": _setup_verify,
    "audit": _setup_audit,
    "assess": _setup_assess,
    "rebuild": _setup_rebuild,
    "crosscheck": _setup_crosscheck,
    "record": _setup_record,
    "sign": _setup_sign,
}


def _parser():
    """Build the top-level parser and every subparser it registers.
    Returns `(parser, subparsers)` where `subparsers` maps every registered
    verb name (porcelain, alias, and plumbing) to its subparser -- the
    thing `verbs()` and `_help_topic` both read from, so nothing here can
    disagree with what argv actually accepts.
    """
    p = argparse.ArgumentParser(
        prog="ret",
        description=_DESC,
        epilog=_EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = p.add_subparsers(dest="verb", metavar="<command>")
    subs = {}

    for name in PORCELAIN:
        sp = sub.add_parser(name, help=_SHORT_HELP[name])
        _add_verbose_json(sp)
        _VERB_SETUP[name](sp)
        subs[name] = sp

    for alias, target in ALIASES.items():
        sp = sub.add_parser(alias, help=f"alias for {target!r}")
        _add_verbose_json(sp)
        _VERB_SETUP[target](sp)
        subs[alias] = sp

    hook_sp = sub.add_parser("hook", help=_SHORT_HELP["hook"])
    subs["hook"] = hook_sp

    help_sp = sub.add_parser("help", help=_SHORT_HELP["help"])
    help_sp.add_argument("topic", nargs="?", help="the command to explain")
    help_sp.add_argument("-a", "--all", action="store_true",
                          help="list everything, including accepted older spellings")
    subs["help"] = help_sp

    completion_sp = sub.add_parser("completion", help=_SHORT_HELP["completion"])
    completion_sp.add_argument("shell", nargs="?", default="bash",
                                choices=("bash", "zsh"))
    subs["completion"] = completion_sp

    return p, subs


def verbs():
    """Every name argv accepts as a command: the porcelain verbs, their
    aliases, and the plumbing -- read directly off `_parser()`'s
    subparsers so this can never drift from what is actually registered.
    """
    _, subs = _parser()
    return tuple(subs.keys())


def _completion(shell: str = "bash") -> None:
    """Print a completion script for `shell`, generated from `verbs()` --
    never a separately maintained list -- so it always matches the actual
    grammar.
    """
    names = " ".join(sorted(verbs()))
    if shell == "zsh":
        script = (
            "#compdef ret\n"
            "_reticuli_completion() {\n"
            f"    local -a commands\n"
            f"    commands=({names})\n"
            "    _describe 'command' commands\n"
            "}\n"
            "compdef _reticuli_completion ret\n"
        )
    else:
        script = (
            "_reticuli_completion() {\n"
            '    local cur="${COMP_WORDS[COMP_CWORD]}"\n'
            f'    COMPREPLY=( $(compgen -W "{names}" -- "${{cur}}") )\n'
            "}\n"
            "complete -F _reticuli_completion ret\n"
        )
    print(script)


def _help_topic(topic: str) -> None:
    """Print detailed help for one command: a retired spelling's
    replacement, a registered verb's usage plus its long-form help, or a
    plain "no such command" for anything else.
    """
    if topic in _FOLDED:
        print(f"{topic!r} is retired; use {_FOLDED[topic]} instead.")
        return
    _, subs = _parser()
    sp = subs.get(topic)
    if sp is None:
        print(f"no such command: {topic!r}")
        return
    print(sp.format_help())
    detail = _FULL_HELP.get(topic)
    if detail:
        print(detail)


def _help_all() -> None:
    """Print the full top-level help, then every retired spelling and what
    replaced it -- the listing `ret help -a` promises in `_EPILOG`.
    """
    p, _ = _parser()
    print(p.format_help())
    print("Accepted older spellings (retired; shown for reference):")
    for old in sorted(_FOLDED):
        print(f"  {old:<10} -> {_FOLDED[old]}")
