"""The kernel's public surface (spec/kernel-api.md).

Most verbs here are thin re-exports of `_kernel`'s submodules. Three are
reimplemented rather than delegated, because the public contract grew past
what the lower layer alone provides:

- `run_gate`/`sandbox` fix the sending half of the sandbox-signal contract
  (spec/claim-format.md): a gate this process actually confines must see
  `RETICULI_JAILED` named *as its backend* (`"seatbelt"`/`"bubblewrap"`),
  not a bare flag, so a gate that is itself a claim runner inherits rather
  than nests.
- `rebuild` adds what the recipe alone cannot promise: a produce step may
  be supplied generated bytes directly (`produce_from`), not only one that
  names a `from` component; a pinned input may be threaded from elsewhere
  (`input_from`, by name); a producer's own cost is counted as one oracle
  call; and the pinned bytes a producer was handed are snapshotted and
  checked unchanged afterward, so a producer cannot rewrite the question it
  was judged against.
- `audit` furnishes a claim's declared `[claim] environment` before judging
  in it (spec/claim-format.md), and supports judging substituted generated
  bytes (`produce_from`) for a dependent's re-earning of a component's gate.
"""
import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile
import time
import tomllib

from ._kernel import attest as _attest
from ._kernel import build as _build
from ._kernel import core as _core
from ._kernel import crosscheck as _crosscheck
from ._kernel import identity as _identity
from ._kernel import recipe as _recipe
from ._kernel import run as _run
from ._kernel import seal as _seal
from ._kernel.core import ClaimError


def _in_band(fn, *args, **kwargs):
    """Call `fn`, turning any exception the lower layer leaves unwrapped
    (a missing pinned input surfaces as a raw `FileNotFoundError` from
    `_hash_file`, for one) into a `ClaimError` -- the claim's own bytes are
    untrusted input all the way up to this surface, not only where the
    lower layer happened to catch it itself."""
    try:
        return fn(*args, **kwargs)
    except ClaimError:
        raise
    except Exception as exc:
        raise ClaimError(f"{getattr(fn, '__name__', fn)} failed: {exc}") from exc

# -------------------------------------------------------------- constants --
NAMESPACE = _core.NAMESPACE
DIGEST = _core.DIGEST
FORMAT = _core.FORMAT
STORE = _core.STORE
MANIFEST = _core.MANIFEST
RECIPE = _core.RECIPE
LEGACY_RECIPE = _core.LEGACY_RECIPE
LEDGER = _core.LEDGER
SIGN_DIR = _core.SIGN_DIR
SIGN_NAMESPACE = _core.SIGN_NAMESPACE
RECORD_NAMESPACE = _attest.RECORD_NAMESPACE
RECORD_FORMAT = _attest.RECORD_FORMAT

_JAILED = _core._JAILED

# ------------------------------------------------------------- identity ----

def _safe_lexical(name: str) -> None:
    """Path-string safety only -- no absolute path, no empty component, no
    `..` -- deliberately WITHOUT the symlink-crossing refusal: used for a
    GENERATED output, whose bytes are never hashed into the root, so an
    internal symlink there is audit's confinement problem to catch (when it
    actually copies the bytes), not load_recipe's to pre-empt."""
    if not isinstance(name, str) or not name:
        raise ClaimError(f"refuses an empty path: {name!r}")
    if os.path.isabs(name):
        raise ClaimError(f"refuses an absolute path: {name!r}")
    if any(part in ("", ".", "..") for part in name.split("/")):
        raise ClaimError(f"path escapes the claim: {name!r}")


def _parse_recipe(d: str) -> dict:
    """Parse and validate a claim's recipe exactly as `_recipe.load_recipe`
    does, except that a step whose own class is GENERATED is confined only
    lexically, not against symlinks -- a generated byte is never hashed, so
    a symlinked generated output is confinement's problem for `audit` (which
    actually copies it) rather than a reason to refuse the whole recipe."""
    path = _recipe.recipe_path(d)
    try:
        with open(path, "rb") as f:
            parsed = tomllib.load(f)
    except tomllib.TOMLDecodeError as exc:
        raise ClaimError(f"malformed recipe {path!r}: {exc}") from exc
    except OSError as exc:
        raise ClaimError(f"cannot read recipe {path!r}: {exc}") from exc

    claim = parsed.get("claim")
    if not isinstance(claim, dict):
        raise ClaimError(f"recipe {path!r} is missing a [claim] table")
    name = claim.get("name")
    if not isinstance(name, str) or not name:
        raise ClaimError(f"recipe {path!r}: [claim] name is required and must be a string")

    fmt = claim.get("format", 1)
    if isinstance(fmt, bool) or not isinstance(fmt, int) or fmt < 1:
        raise ClaimError(f"recipe {path!r}: [claim] format must be a positive integer")
    if fmt > _core.FORMAT:
        raise ClaimError(
            f"claim format {fmt} is newer than this kernel understands "
            f"(format {_core.FORMAT}); upgrade reticuli to read it"
        )

    inputs = claim.get("inputs", [])
    if not isinstance(inputs, list) or not all(isinstance(p, str) for p in inputs):
        raise ClaimError(f"recipe {path!r}: [claim] inputs must be a list of strings")
    for p in inputs:
        _core._safe(d, p)

    manifest_name = claim.get("inputs_manifest")
    if manifest_name is not None:
        if not isinstance(manifest_name, str) or not manifest_name:
            raise ClaimError(f"recipe {path!r}: inputs_manifest must be a string")
        _core._safe(d, manifest_name)

    environment = claim.get("environment")
    if environment is not None:
        if not isinstance(environment, str) or not environment:
            raise ClaimError(f"recipe {path!r}: environment must be a string")
        _core._safe(d, environment)

    envelope = claim.get("envelope")
    if envelope is not None:
        if not isinstance(envelope, dict) or not envelope:
            raise ClaimError(f"recipe {path!r}: [claim] envelope must be a non-empty table")
        unknown_units = set(envelope) - set(_core.COST_UNITS)
        if unknown_units:
            raise ClaimError(f"recipe {path!r}: envelope carries unknown unit(s): {sorted(unknown_units)}")
        for unit, ceiling in envelope.items():
            if isinstance(ceiling, bool) or not isinstance(ceiling, (int, float)) or ceiling <= 0:
                raise ClaimError(f"recipe {path!r}: envelope.{unit} must be a positive number")

    steps = parsed.get("step", [])
    if not isinstance(steps, list):
        raise ClaimError(f"recipe {path!r}: [[step]] must be an array of tables")
    for step in steps:
        if not isinstance(step, dict):
            raise ClaimError(f"recipe {path!r}: each step must be a table")
        kind = step.get("kind")
        if kind not in _core.KINDS:
            raise ClaimError(
                f"recipe {path!r}: step kind must be one of "
                f"{sorted(_core.KINDS)}, got {kind!r}"
            )
        output = step.get("output")
        if not isinstance(output, str) or not output:
            raise ClaimError(f"recipe {path!r}: every step needs a string output")
        effective_class = step.get("class", "generated" if kind == "produce" else "pinned")
        if effective_class == "generated":
            _safe_lexical(output)
        else:
            _core._safe(d, output)
        if kind == "gate" and not step.get("run"):
            raise ClaimError(f"recipe {path!r}: a gate step needs a run command")
        if "class" not in step:
            step["class"] = effective_class

    return parsed


def load_recipe(d: str) -> dict:
    return _in_band(_parse_recipe, d)


def root(recipe: dict, d: str) -> str:
    return _in_band(_identity.root, recipe, d)


def build_digest(d: str) -> str:
    return _in_band(_identity.build_digest, d)


def seal(d: str) -> dict:
    recipe = load_recipe(d)
    name = recipe["claim"]["name"]
    r = root(recipe, d)
    manifest = {"name": name, "root": r}
    path = os.path.join(d, _core.MANIFEST)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    _core._write_json(path, manifest)
    return manifest


def read_manifest(d: str) -> dict:
    return _in_band(_seal.read_manifest, d)


def verify(d: str) -> dict:
    recipe = load_recipe(d)
    manifest = read_manifest(d)
    recomputed = root(recipe, d)
    return {"ok": recomputed == manifest["root"], "root": manifest["root"],
            "recomputed": recomputed, "name": manifest["name"]}


_hash_file = _core._hash_file

# --------------------------------------------------------------- cost/env --
cost = _run.cost
ledger = _run.ledger
ledger_events = _run.ledger_events
preflight = _run.preflight

# ------------------------------------------------------------------ record --
record_canonical = _attest.record_canonical
record_digest = _attest.record_digest
record_validate = _attest.record_validate
record_read = _crosscheck.record_read
record_signer = _attest.record_signer

# ------------------------------------------------------- crosscheck layer --
gate_deciders = _crosscheck.gate_deciders
vacuous_gates = _crosscheck.vacuous_gates
mutation_score = _crosscheck.mutation_score
crosscheck = _crosscheck.crosscheck
record_proof = _crosscheck.record_proof
sign_node = _crosscheck.sign_node
independence = _crosscheck.independence


# --------------------------------------------------------------- sandbox --

def _scrub_env(d: str, recipe: dict, backend: str, scratch: str = None) -> dict:
    """The gate's own environment: a minimal host allowlist, with
    `RETICULI_JAILED` named as the backend *only* when this call is the one
    applying a real sandbox -- an inherited or absent signal passes through
    untouched, so a kernel already inside one never re-announces."""
    env = {k: os.environ[k] for k in _core._KEEP_ENV if k in os.environ}
    if backend not in ("none", "inherited"):
        env[_core._JAILED] = backend
    if scratch is not None:
        env["TMPDIR"] = scratch
        env["HOME"] = scratch
    return env


def _run_gate(cmd: str, d: str, recipe: dict, extra_path: str = None) -> dict:
    backend = _run.sandbox_backend()
    timeout = _run.gate_timeout(recipe)
    scratch = None
    if backend not in ("none", "inherited"):
        scratch_root = os.path.join(d, _core.STORE, "scratch")
        os.makedirs(scratch_root, exist_ok=True)
        scratch = tempfile.mkdtemp(dir=scratch_root)
    env = _scrub_env(d, recipe, backend, scratch)
    if extra_path:
        env["PATH"] = extra_path + os.pathsep + env.get("PATH", os.defpath)
    argv = _run._sandbox_argv(backend, cmd, d, scratch if scratch is not None else d)
    returncode, timed_out = _run._run(argv, d, env, timeout)
    if timed_out:
        status = "timeout"
    elif returncode == 0:
        status = "ok"
    else:
        status = "failed"
    return {"status": status, "quarantine": backend}


def run_gate(cmd: str, d: str, recipe: dict) -> dict:
    """Run one gate command inside `d`: scrubbed environment, sandboxed
    under whatever backend is actually functional, bounded by the
    declared (or default) wall-clock ceiling."""
    return _run_gate(cmd, d, recipe)


def sandbox(cmd: str, d: str):
    """A functional probe of the host sandbox: run `cmd` inside `d` under
    whatever confinement applies, returning `(status, backend)`."""
    result = _run_gate(cmd, d, {})
    return (result["status"], result["quarantine"])


def _produce(into: str, recipe: dict, step: dict, outs: list, producer: str,
             *, guidance: bool = True, producer_env: dict = None) -> dict:
    """Run `producer` once for one produce step. The producer's environment
    is the same scrubbed allowlist a gate gets -- an inherited host secret
    never reaches it unhanded -- plus the room's own control variables and
    whatever `producer_env` the caller deliberately hands over past the
    scrub (spec/claim-format.md: the room's environment is a boundary, both
    ways)."""
    output = step["output"]
    target = _core._safe(into, output)
    os.makedirs(os.path.dirname(target) or into, exist_ok=True)

    env = {k: os.environ[k] for k in _core._KEEP_ENV if k in os.environ}
    env[_core._ENV_OUTPUT] = target
    env[_core._ENV_OUTPUTS] = json.dumps(outs)
    env[_core._ENV_CLAIM] = recipe.get("claim", {}).get("name", "")
    if guidance:
        hint = _build._step_guidance(step)
        if hint is not None:
            env[_core._ENV_REQUEST] = hint

    fd, usage_path = tempfile.mkstemp(prefix=".reticuli-usage-", suffix=".json")
    os.close(fd)
    env[_core._ENV_USAGE] = usage_path
    if producer_env:
        env.update(producer_env)

    try:
        start = time.monotonic()
        result = subprocess.run(
            [_core._SHELL, "-c", producer], cwd=into, env=env,
            capture_output=True, text=True, timeout=_core.PRODUCER_TIMEOUT,
        )
        elapsed = time.monotonic() - start
        if result.returncode != 0:
            raise ClaimError(
                f"producer failed for {output!r}: exit {result.returncode}: "
                f"{(result.stderr or result.stdout).strip()[-300:]}"
            )
        usage = _build._read_usage(usage_path)
        usage["seconds"] = elapsed
        return usage
    finally:
        try:
            os.unlink(usage_path)
        except OSError:
            pass


# --------------------------------------------------------------- rebuild --

def _hash_tree(root_dir: str) -> dict:
    """Every regular file under `root_dir`, outside the store, by its
    sha256 -- the baseline a producer's own bytes are checked against."""
    snap = {}
    store_abs = os.path.realpath(os.path.join(root_dir, _core.STORE))
    for dirpath, dirnames, filenames in os.walk(root_dir):
        dirnames[:] = [dn for dn in dirnames
                       if not (os.path.realpath(os.path.join(dirpath, dn)) == store_abs
                               or os.path.realpath(os.path.join(dirpath, dn))
                               .startswith(store_abs + os.sep))]
        for fn in filenames:
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, root_dir)
            try:
                snap[rel] = _core._hash_file(full)
            except ClaimError:
                pass
    return snap


def rebuild(d: str, producer: str, into: str, *, produce_from: dict = None,
            input_from: dict = None, guidance: bool = True,
            producer_env: dict = None) -> dict:
    """Regrow `d`'s generated outputs into the fresh directory `into`.

    `produce_from` supplies bytes for a named generated output directly,
    bypassing the producer for that one output, whether or not its step
    declares a `from` component. `input_from` threads a replacement source
    file for a named pinned input, overriding the one carried from `d`.
    `guidance` withholds every producer hint from the room's environment
    when false. `producer_env` is merged into the producer's own
    environment past the host's -- the one road an inherited credential may
    travel, by the caller's deliberate hand.
    """
    recipe = load_recipe(d)
    if os.path.isdir(into) and os.listdir(into):
        raise ClaimError(f"refuses a non-empty rebuild target: {into!r}")

    missing = _run.preflight(recipe)
    if missing:
        raise ClaimError(f"environment: host is missing {missing}")

    _build._materialize(d, into, recipe)
    for name, replacement in (input_from or {}).items():
        _core._copy_into(replacement, _core._safe(into, name))

    before = _hash_tree(into)

    outs = _recipe.generated_outputs(recipe)
    usage_total = {}
    produced_calls = 0
    produce_from = produce_from or {}
    for step in _recipe.produces(recipe):
        if step.get("class", "generated") != "generated":
            continue
        output = step["output"]
        supplied = produce_from.get(output) or step.get("from")
        if supplied and os.path.isfile(supplied):
            _core._copy_into(supplied, _core._safe(into, output))
            _run.ledger(into, {"event": "reuse", "output": output})
            continue
        usage = _produce(into, recipe, step, outs, producer,
                          guidance=guidance, producer_env=producer_env)
        produced_calls += 1
        for key, value in usage.items():
            usage_total[key] = usage_total.get(key, 0) + value

    after = _hash_tree(into)
    for rel, digest in before.items():
        if after.get(rel) != digest:
            raise ClaimError(f"a producer rewrote a pinned byte: {rel!r}")

    quarantine = "none"
    gates_result = []
    ok = True
    for step in _recipe.gates(recipe):
        output = step["output"]
        path = _core._safe(into, output)
        if os.path.isfile(path):
            os.remove(path)
        result = _run_gate(step["run"], into, recipe)
        quarantine = result["quarantine"]
        gates_result.append({"output": output, "status": result["status"],
                              "quarantine": quarantine})
        _run.ledger(into, {"event": "gate", "output": output,
                            "status": result["status"], "quarantine": quarantine})
        if result["status"] != "ok":
            ok = False

    if not ok:
        raise ClaimError(f"rebuild did not earn its gates: {gates_result!r}")

    manifest = seal(into)
    if produced_calls:
        usage_total["calls"] = usage_total.get("calls", 0) + produced_calls
    _run.ledger(into, {
        "event": "environment",
        "when": _core._now(),
        "quarantine": quarantine,
        "python": platform.python_version(),
        "platform": sys.platform,
        **usage_total,
    })
    vendor = os.environ.get(_core._ENV_VENDOR)
    model = os.environ.get(_core._ENV_MODEL)
    if vendor or model:
        _run.ledger(into, {"event": "producer", "vendor": vendor, "model": model,
                            "blind": not bool(produce_from)})
    return {"root": manifest["root"], "name": manifest["name"],
            "quarantine": quarantine, "gates": gates_result}


def _furnish(d: str, recipe: dict) -> str:
    """Build (or reuse a cached) private venv for the claim's pinned
    `environment` file, same as `_run.furnish`, except the install runs
    with its `cwd` set to the claim directory -- a relative local wheel
    path in the requirements file resolves against the claim, not against
    whatever directory happened to call `audit`."""
    claim = (recipe or {}).get("claim", {}) if recipe else {}
    env_file = claim.get("environment")
    if not env_file:
        return None
    path = _core._safe(d, env_file)
    if not os.path.isfile(path):
        raise ClaimError(f"environment file is gone: {env_file!r}")
    digest = _core._hash_file(path)
    key = f"{digest}-{platform.python_version()}-{sys.platform}-{platform.machine()}"
    venv_dir = os.path.join(_run._env_cache_dir(), key)
    bin_name = "Scripts" if sys.platform == "win32" else "bin"
    bin_dir = os.path.join(venv_dir, bin_name)
    if os.path.isdir(venv_dir):
        return bin_dir

    tmp_dir = venv_dir + ".tmp"
    shutil.rmtree(tmp_dir, ignore_errors=True)
    subprocess.run([sys.executable, "-m", "venv", tmp_dir], check=True,
                    capture_output=True, text=True, timeout=_core.FURNISH_TIMEOUT)
    pip = os.path.join(tmp_dir, bin_name, "pip")
    result = subprocess.run(
        [pip, "install", "--require-hashes", "--only-binary=:all:", "-r", path],
        cwd=d, capture_output=True, text=True, timeout=_core.FURNISH_TIMEOUT,
    )
    if result.returncode != 0:
        shutil.rmtree(tmp_dir, ignore_errors=True)
        raise ClaimError(f"cannot furnish environment {env_file!r}: {result.stderr.strip()}")
    os.replace(tmp_dir, venv_dir)
    return bin_dir


# ----------------------------------------------------------------- audit --

def _restore_substitution(d: str, substituted: dict) -> None:
    for output, backup in substituted.items():
        path = _core._safe(d, output)
        if backup is not None:
            shutil.move(backup, path)
        elif os.path.isfile(path):
            os.remove(path)


def audit(d: str, *, produce_from: dict = None) -> dict:
    """Re-earn every gate's verdict cold, in place, then re-check identity.

    Where the claim declares `[claim] environment`, the room is furnished
    first (a private venv from exactly the hash-pinned artifacts); a room
    that cannot be furnished is an `environment` failure, never a verdict.
    `produce_from` substitutes bytes for a named generated output before
    judging -- a dependent re-earning a component's gate on its own shipped
    bytes -- and restores the claim's own bytes afterward regardless of the
    outcome.
    """
    recipe = load_recipe(d)
    manifest = read_manifest(d)

    for step in _recipe.produces(recipe):
        if step.get("class", "generated") == "generated":
            out_path = os.path.join(d, step["output"])
            if os.path.lexists(out_path):
                _core._safe(d, step["output"])

    missing = _run.preflight(recipe)
    if missing:
        gates_result = [{"output": s["output"], "status": "environment", "quarantine": None}
                         for s in _recipe.gates(recipe)]
        return {"ok": False, "root": manifest["root"], "recomputed": None,
                "gates": gates_result, "environment": missing, "verdict": "environment"}

    # THE ROOM MATCHES THE NAME: a gate that reads its own recipe file must
    # find exactly what the root names. format >= 3 strips guidance from
    # the preimage, so the on-disk recipe is temporarily replaced with that
    # same stripped form while gates run here -- in place, not a fresh
    # room -- and restored afterward regardless of outcome.
    recipe_path = _recipe.recipe_path(d)
    original_recipe_bytes = None
    if _identity._claim_format(recipe) >= 3:
        with open(recipe_path, "rb") as f:
            original_recipe_bytes = f.read()
        _build._write_recipe_toml(recipe_path, _identity._preimage_recipe(recipe))

    substituted = {}
    for output, src in (produce_from or {}).items():
        path = _core._safe(d, output)
        if os.path.isfile(path):
            backup = path + ".audit-orig"
            shutil.copy2(path, backup)
            substituted[output] = backup
        else:
            substituted[output] = None
        _core._copy_into(src, path)

    try:
        try:
            bin_dir = _furnish(d, recipe)
        except ClaimError as exc:
            gates_result = [{"output": s["output"], "status": "environment", "quarantine": None}
                             for s in _recipe.gates(recipe)]
            return {"ok": False, "root": manifest["root"], "recomputed": None,
                    "gates": gates_result, "environment": [str(exc)], "verdict": "environment"}

        gates_result = []
        ok = True
        for step in _recipe.gates(recipe):
            output = step["output"]
            path = _core._safe(d, output)
            before = _core._hash_file(path) if os.path.isfile(path) else None
            if os.path.isfile(path):
                os.remove(path)

            result = _run_gate(step["run"], d, recipe, extra_path=bin_dir)
            quarantine = result["quarantine"]

            if result["status"] != "ok":
                ok = False
                gates_result.append({"output": output, "status": result["status"],
                                      "quarantine": quarantine})
                continue
            if not os.path.isfile(path):
                ok = False
                gates_result.append({"output": output, "status": "failed",
                                      "quarantine": quarantine})
                continue
            if before is not None and _core._hash_file(path) != before:
                ok = False
                gates_result.append({"output": output, "status": "mismatch",
                                      "quarantine": quarantine})
                continue
            gates_result.append({"output": output, "status": "ok", "quarantine": quarantine})

        try:
            recomputed = root(recipe, d)
        except ClaimError:
            # a gate that failed to recreate a pinned output (status
            # already failed/mismatch above) can leave a pinned byte
            # missing -- the claim is already broken; recompute is
            # informational, not a second way to raise.
            recomputed = None
        if recomputed != manifest["root"]:
            ok = False

        return {
            "ok": ok, "root": manifest["root"], "recomputed": recomputed,
            "gates": gates_result, "verdict": "earned" if ok else "broken",
        }
    finally:
        _restore_substitution(d, substituted)
        if original_recipe_bytes is not None:
            with open(recipe_path, "wb") as f:
                f.write(original_recipe_bytes)


# ------------------------------------------------------------------ phase --

def _is_signed(d: str, current_root: str) -> bool:
    manifest = _seal.read_manifest(d)
    if not manifest.get("proof"):
        return False
    anchor = os.environ.get(_core._ENV_SIGNERS)
    if not anchor:
        return False
    sign_dir = os.path.join(d, _core.SIGN_DIR)
    if not os.path.isdir(sign_dir):
        return False

    for fn in sorted(os.listdir(sign_dir)):
        if not fn.endswith(".sign.json"):
            continue
        stmt_path = os.path.join(sign_dir, fn)
        sig_path = stmt_path + ".sig"
        if not os.path.isfile(sig_path):
            continue
        try:
            with open(stmt_path, "rb") as f:
                stmt_bytes = f.read()
            stmt = json.loads(stmt_bytes)
        except (OSError, ValueError):
            continue
        if not isinstance(stmt, dict):
            continue
        signer = stmt.get("identity")
        if not signer or not _build._authorized(anchor, signer):
            continue
        if not _build._ssh_verify(stmt_bytes, sig_path, anchor, _core.SIGN_NAMESPACE, signer):
            continue
        if stmt.get("root") != current_root:
            continue
        if not stmt.get("proof_recorded"):
            continue

        prefix = fn[: -len(".sign.json")]
        packet_path = os.path.join(sign_dir, prefix + ".packet.json")
        if not os.path.isfile(packet_path):
            continue
        try:
            with open(packet_path, "r", encoding="utf-8") as f:
                packet = json.load(f)
        except (OSError, ValueError):
            continue
        if not isinstance(packet, dict):
            continue
        packet_digest = hashlib.sha256(
            json.dumps(packet, sort_keys=True).encode("utf-8")).hexdigest()
        if packet_digest != stmt.get("packet_digest"):
            continue
        if packet.get("proof") != manifest.get("proof"):
            continue
        if packet.get("build_digest") != build_digest(d):
            continue
        return True
    return False


def phase(d: str) -> str:
    """`draft` (no manifest yet) / `sealed` (identity holds) / `signed`
    (a trusted signature over a coherent, proven packet, on undrifted
    bytes)."""
    load_recipe(d)
    manifest_path = os.path.join(d, _core.MANIFEST)
    if not os.path.isfile(manifest_path):
        return "draft"

    v = verify(d)
    if not v["ok"]:
        raise ClaimError(f"claim {d!r} does not verify: sealed root does not match recomputed bytes")

    if _is_signed(d, v["root"]):
        return "signed"
    return "sealed"
