"""Launcher: run software that exists only latently in a claim (spec/layers.md).

A runnable claim's pinned inputs include `package.toml`, naming the file to
run as `[package] entrypoint`. `run` checks a cached build or regrows a
fresh one with a producer (`RETICULI_PRODUCER`), then executes the
entrypoint with the claim root as cwd; `strip` deletes the generated bytes
back to latency; `ls` reports identity, phase, and whether a claim is
materialized. Freshly regrown bytes stay unaccepted (`run` exits 4) until a
`run --accept-generated` records their digests; an accepted build whose
bytes later change is refused as drift (exit 6) rather than silently
re-accepted. A build the launcher never generated or accepted (packed by
hand) runs directly -- the launcher guards only what it itself accepted.

Verbs: `run <claim> [--accept-generated] [--signed-only] [--no-sandbox]
[-- args...]`, `strip <claim>`, `ls <claim>...`. Launcher state lives under
`<claim>/.launcher/` and is removed by `strip`.
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile
import tomllib

from . import _util
from . import kernel

LAUNCHER_DIR = ".launcher"
STATE_FILE = "state.json"
PACKAGE_RECIPE = "package.toml"

_SEATBELT = "/usr/bin/sandbox-exec"
_BWRAP_OK = None
_ENV_ALLOW = ("PATH", "HOME", "TMPDIR", "LANG", "LC_ALL", "TZ")

HELP = """\
usage: python3 -m reticuli.launcher <verb> ...

  run   <claim> [--accept-generated] [--signed-only] [--no-sandbox] [-- args...]
  strip <claim>
  ls    <claim>...

exit codes:
  3  not runnable (no/unpinned package.toml, escaping entrypoint or path)
  4  newly generated bytes, consent required (pass --accept-generated)
  5  trust refused (--signed-only on a claim not signed to you)
  6  drifted build (audit failed; nothing executed, nothing modified)
  7  latent and no producer configured (RETICULI_PRODUCER unset)
"""


def err(msg: str) -> None:
    print(msg, file=sys.stderr)


# ---------------------------------------------------------------- state --

def _state_path(d: str) -> str:
    return os.path.join(d, LAUNCHER_DIR, STATE_FILE)


def _load_state(d: str) -> dict:
    path = _state_path(d)
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}


def _save_state(d: str, state: dict) -> None:
    path = _state_path(d)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(state, f, sort_keys=True)
    os.replace(tmp, path)


# -------------------------------------------------------------- package --

def _generated_outputs(recipe: dict) -> list:
    return [s["output"] for s in recipe.get("step", [])
            if s.get("kind") == "produce" and s.get("class", "generated") == "generated"]


def _package_entrypoint(d: str, recipe: dict) -> str:
    claim = recipe.get("claim", {})
    inputs = claim.get("inputs", [])
    step = next((s for s in recipe.get("step", []) if s.get("output") == PACKAGE_RECIPE), None)

    if PACKAGE_RECIPE not in inputs and step is None:
        raise kernel.ClaimError(
            "not runnable: no package.toml declared as a pinned input -- "
            "a runnable claim pins [package] entrypoint"
        )
    if step is not None and step.get("class", "generated") == "generated":
        raise kernel.ClaimError(
            "not runnable: package.toml is a generated output; it must be "
            "a pinned input, not generated"
        )

    path = os.path.join(d, PACKAGE_RECIPE)
    if not os.path.isfile(path):
        raise kernel.ClaimError(f"not runnable: {PACKAGE_RECIPE} is missing from disk")
    try:
        with open(path, "rb") as f:
            pkg = tomllib.load(f)
    except tomllib.TOMLDecodeError as exc:
        raise kernel.ClaimError(f"malformed {PACKAGE_RECIPE}: {exc}") from exc

    entry = (pkg.get("package") or {}).get("entrypoint")
    if not isinstance(entry, str) or not entry:
        raise kernel.ClaimError(f"{PACKAGE_RECIPE} names no [package] entrypoint")

    _util.safe_path(d, entry)
    return entry


# --------------------------------------------------------------- regrow --

def _regrow(d: str, recipe: dict, producer: str) -> None:
    into = tempfile.mkdtemp(prefix="reticuli-launch-")
    try:
        kernel.rebuild(d, producer, into)
        for output in _generated_outputs(recipe):
            src = os.path.join(into, output)
            if os.path.isfile(src):
                dst = os.path.join(d, output)
                os.makedirs(os.path.dirname(dst) or d, exist_ok=True)
                shutil.copy2(src, dst)
    finally:
        shutil.rmtree(into, ignore_errors=True)


# -------------------------------------------------------------- sandbox --

def _seatbelt_usable() -> bool:
    try:
        result = subprocess.run(
            [_SEATBELT, "-p", "(version 1)(allow default)", "/bin/sh", "-c", "true"],
            capture_output=True, timeout=5)
        return result.returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def _bwrap_usable() -> bool:
    global _BWRAP_OK
    if _BWRAP_OK is not None:
        return _BWRAP_OK
    bwrap = shutil.which("bwrap")
    if not bwrap:
        _BWRAP_OK = False
        return False
    try:
        result = subprocess.run(
            [bwrap, "--ro-bind", "/", "/", "--unshare-net", "--die-with-parent", "true"],
            capture_output=True, timeout=5)
        _BWRAP_OK = result.returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        _BWRAP_OK = False
    return _BWRAP_OK


def _sandbox_backend() -> str:
    if os.environ.get(kernel._JAILED):
        return "inherited"
    if sys.platform == "darwin" and os.path.exists(_SEATBELT):
        return "seatbelt" if _seatbelt_usable() else "none"
    if shutil.which("bwrap"):
        return "bubblewrap" if _bwrap_usable() else "none"
    return "none"


def _quote_sb(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _seatbelt_profile(workspace: str) -> str:
    return "\n".join([
        "(version 1)",
        "(allow default)",
        "(deny network*)",
        '(deny file-write* (require-not (subpath "%s")))' % _quote_sb(workspace),
        '(allow file-write* (literal "/dev/null"))',
    ])


def _sandbox_argv(backend: str, argv: list, d: str) -> list:
    if backend == "seatbelt":
        profile = _seatbelt_profile(os.path.realpath(d))
        return [_SEATBELT, "-p", profile] + argv
    if backend == "bubblewrap":
        bwrap = shutil.which("bwrap")
        return [bwrap, "--ro-bind", "/", "/", "--dev", "/dev", "--proc", "/proc",
                "--bind", d, d, "--unshare-net", "--die-with-parent",
                "--chdir", d] + argv
    return argv


def _execute(d: str, entrypoint: str, args: list, no_sandbox: bool) -> int:
    backend = "off" if no_sandbox else _sandbox_backend()
    scratch_root = os.path.join(d, LAUNCHER_DIR, "scratch")
    os.makedirs(scratch_root, exist_ok=True)
    scratch = tempfile.mkdtemp(dir=scratch_root)
    try:
        env = {k: os.environ[k] for k in _ENV_ALLOW if k in os.environ}
        env.setdefault("PATH", os.defpath)
        env["HOME"] = scratch
        env["TMPDIR"] = scratch
        if os.environ.get(kernel._JAILED):
            env[kernel._JAILED] = os.environ[kernel._JAILED]
        if backend not in ("none", "off", "inherited"):
            env[kernel._JAILED] = backend

        argv = [sys.executable, entrypoint] + list(args)
        if backend not in ("none", "off", "inherited"):
            argv = _sandbox_argv(backend, argv, d)

        err(f'quarantine = "{backend}"')
        result = subprocess.run(argv, cwd=d, env=env)
        return result.returncode
    finally:
        shutil.rmtree(scratch, ignore_errors=True)


# ----------------------------------------------------------------- run --

def cmd_run(opts: dict) -> int:
    d = os.path.abspath(opts["claim"])
    try:
        recipe = kernel.load_recipe(d)
        entrypoint = _package_entrypoint(d, recipe)
    except kernel.ClaimError as exc:
        err(str(exc))
        return 3

    try:
        ph = kernel.phase(d)
    except kernel.ClaimError as exc:
        err(str(exc))
        return 3
    err(f'phase = "{ph}"')

    if opts["signed_only"] and ph != "signed":
        err(f'--signed-only refuses: claim is not signed to you (phase = "{ph}")')
        return 5

    generated = _generated_outputs(recipe)
    missing = [o for o in generated if not os.path.isfile(os.path.join(d, o))]

    regrown_now = False
    if missing:
        producer = os.environ.get("RETICULI_PRODUCER")
        if not producer:
            err("latent: no generated bytes on hand and RETICULI_PRODUCER is "
                "unset; set RETICULI_PRODUCER to a producer command to regrow "
                "this claim")
            return 7
        try:
            _regrow(d, recipe, producer)
        except kernel.ClaimError as exc:
            err(f"regrow failed: {exc}")
            return 1
        regrown_now = True

    current = {o: kernel._hash_file(os.path.join(d, o)) for o in generated}
    state = _load_state(d)
    pending = state.get("pending")
    accepted = state.get("accepted")

    if regrown_now:
        pending = dict(current)
        _save_state(d, {"pending": pending})

    if pending is not None:
        if not opts["accept_generated"]:
            err("newly generated bytes are not yet accepted; pass "
                "--accept-generated to execute and accept them")
            return 4
        _save_state(d, {"accepted": dict(current)})
    elif accepted is not None and accepted != current:
        err("drifted build: the accepted implementation no longer matches "
            "these bytes; nothing executed. Recover with "
            "`python3 -m reticuli.launcher strip` and regrow.")
        return 6

    return _execute(d, entrypoint, opts["entry_args"], opts["no_sandbox"])


def cmd_strip(claim_arg: str) -> int:
    d = os.path.abspath(claim_arg)
    try:
        recipe = kernel.load_recipe(d)
    except kernel.ClaimError as exc:
        err(str(exc))
        return 3

    for output in _generated_outputs(recipe):
        path = os.path.join(d, output)
        if os.path.islink(path) or os.path.isfile(path):
            os.remove(path)
        elif os.path.isdir(path):
            shutil.rmtree(path)

    launcher_dir = os.path.join(d, LAUNCHER_DIR)
    if os.path.isdir(launcher_dir):
        shutil.rmtree(launcher_dir)
    err("stripped: claim is latent")
    return 0


def cmd_ls(claims: list) -> int:
    for arg in claims:
        d = os.path.abspath(arg)
        try:
            recipe = kernel.load_recipe(d)
        except kernel.ClaimError as exc:
            err(f"{arg}: {exc}")
            continue
        name = recipe.get("claim", {}).get("name", "")
        try:
            root = kernel.read_manifest(d).get("root", "")
        except kernel.ClaimError:
            root = ""
        try:
            ph = kernel.phase(d)
        except kernel.ClaimError:
            ph = "draft"
        generated = _generated_outputs(recipe)
        materialized = all(os.path.isfile(os.path.join(d, o)) for o in generated)
        print(f"{name}  {root[:8]}  {ph}  "
              f"{'materialized' if materialized else 'latent'}")
    return 0


# ---------------------------------------------------------------- main --

def _parse_args(argv: list):
    if not argv or argv[0] in ("-h", "--help"):
        return "help", None

    verb, rest = argv[0], argv[1:]
    if verb == "run":
        if not rest:
            raise ValueError("run needs a claim path")
        opts = {"claim": None, "accept_generated": False, "signed_only": False,
                 "no_sandbox": False, "entry_args": []}
        past_dashdash = False
        for tok in rest:
            if past_dashdash:
                opts["entry_args"].append(tok)
            elif tok == "--":
                past_dashdash = True
            elif tok == "--accept-generated":
                opts["accept_generated"] = True
            elif tok == "--signed-only":
                opts["signed_only"] = True
            elif tok == "--no-sandbox":
                opts["no_sandbox"] = True
            elif opts["claim"] is None:
                opts["claim"] = tok
            else:
                opts["entry_args"].append(tok)
        if opts["claim"] is None:
            raise ValueError("run needs a claim path")
        return "run", opts

    if verb == "strip":
        if not rest:
            raise ValueError("strip needs a claim path")
        return "strip", {"claim": rest[0]}

    if verb == "ls":
        if not rest:
            raise ValueError("ls needs at least one claim path")
        return "ls", {"claims": rest}

    raise ValueError(f"unknown verb: {verb!r}")


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    try:
        verb, opts = _parse_args(argv)
    except ValueError as exc:
        err(str(exc))
        err(HELP)
        return 2

    if verb == "help":
        err(HELP)
        return 0
    if verb == "run":
        return cmd_run(opts)
    if verb == "strip":
        return cmd_strip(opts["claim"])
    return cmd_ls(opts["claims"])


if __name__ == "__main__":
    sys.exit(main())
