"""Deterministic transfer: export a claim to one tar, import it elsewhere.

`export` walks only a claim's DECLARED content -- its recipe, its pinned
inputs, its step outputs, its manifest, its attestations and signatures --
never the directory tree, so a stray file dropped beside a claim does not
ride along and two exports of one claim are byte for byte identical. A
`blind` export additionally withholds the top claim's own generated bytes
(the room a rebuilder is meant to regrow). A declared component staged at
`.reticuli/sealed/<name>` travels too, but repackaged under `.reticuli/deps/`
and stripped of ITS generated bytes unconditionally: a component's CLAIM
travels (recipe, inputs, pins), never its implementation.

`import_` is the inverse: it extracts into a fresh directory, folding
`.reticuli/deps/<name>` back into the ordinary `.reticuli/sealed/<name>`
shape, then verifies identity on the bytes received.
"""
import os
import tarfile

from . import kernel
from . import attest as attest_module

_DEPS = f"{kernel.STORE}/deps"
_SEALED = f"{kernel.STORE}/sealed"


def _recipe_name(d: str) -> str:
    if os.path.isfile(os.path.join(d, kernel.RECIPE)):
        return kernel.RECIPE
    if os.path.isfile(os.path.join(d, kernel.LEGACY_RECIPE)):
        return kernel.LEGACY_RECIPE
    raise kernel.ClaimError(f"no recipe found in {d!r}")


def _claim_paths(d: str, recipe: dict, *, blind: bool, top: bool) -> list:
    """Every declared, present path of this claim's own content: pinned
    inputs and step outputs, excluding a component's generated bytes
    always, and the top claim's own generated bytes when `blind`."""
    claim = recipe.get("claim", {}) or {}
    paths = []
    for p in claim.get("inputs", []):
        if os.path.isfile(os.path.join(d, p)):
            paths.append(p)
    env = claim.get("environment")
    if env and os.path.isfile(os.path.join(d, env)):
        paths.append(env)
    manifest_name = claim.get("inputs_manifest")
    if manifest_name and os.path.isfile(os.path.join(d, manifest_name)):
        paths.append(manifest_name)

    for step in recipe.get("step", []):
        output = step.get("output")
        if not output:
            continue
        kind = step.get("kind")
        klass = step.get("class", "generated" if kind == "produce" else "pinned")
        if klass == "generated":
            if not top or blind:
                continue
        if os.path.isfile(os.path.join(d, output)):
            paths.append(output)
    return sorted(set(paths))


def _dep_entries(comp_dir: str, prefix: str) -> list:
    """One claim's own content, repackaged under `prefix` -- its recipe,
    pinned content, and manifest, never its generated bytes -- plus its
    own nested components, recursively, under the same scheme."""
    recipe = kernel.load_recipe(comp_dir)
    recipe_name = _recipe_name(comp_dir)
    entries = [(f"{prefix}/{recipe_name}", os.path.join(comp_dir, recipe_name))]
    for rel in _claim_paths(comp_dir, recipe, blind=False, top=False):
        entries.append((f"{prefix}/{rel}", os.path.join(comp_dir, rel)))
    manifest_path = os.path.join(comp_dir, kernel.MANIFEST)
    if os.path.isfile(manifest_path):
        entries.append((f"{prefix}/{kernel.MANIFEST}", manifest_path))

    nested = os.path.join(comp_dir, _SEALED)
    if os.path.isdir(nested):
        for name in sorted(os.listdir(nested)):
            nd = os.path.join(nested, name)
            if os.path.isdir(nd):
                entries.extend(_dep_entries(nd, f"{prefix}/{kernel.STORE}/deps/{name}"))
    return entries


def export(d: str, tar_path: str, *, blind: bool = False) -> None:
    """Write a deterministic tar of `d`'s declared content."""
    recipe = kernel.load_recipe(d)
    recipe_name = _recipe_name(d)
    entries = [(recipe_name, os.path.join(d, recipe_name))]
    for rel in _claim_paths(d, recipe, blind=blind, top=True):
        entries.append((rel, os.path.join(d, rel)))

    manifest_path = os.path.join(d, kernel.MANIFEST)
    if os.path.isfile(manifest_path):
        entries.append((kernel.MANIFEST, manifest_path))

    attest_dir = os.path.join(d, attest_module.ATTEST)
    if os.path.isdir(attest_dir):
        for fn in sorted(os.listdir(attest_dir)):
            full = os.path.join(attest_dir, fn)
            if os.path.isfile(full):
                entries.append((f"{attest_module.ATTEST}/{fn}", full))

    sign_dir = os.path.join(d, kernel.SIGN_DIR)
    if os.path.isdir(sign_dir):
        for fn in sorted(os.listdir(sign_dir)):
            full = os.path.join(sign_dir, fn)
            if os.path.isfile(full):
                entries.append((f"{kernel.SIGN_DIR}/{fn}", full))

    sealed_dir = os.path.join(d, _SEALED)
    if os.path.isdir(sealed_dir):
        for name in sorted(os.listdir(sealed_dir)):
            comp_dir = os.path.join(sealed_dir, name)
            if os.path.isdir(comp_dir):
                entries.extend(_dep_entries(comp_dir, f"{_DEPS}/{name}"))

    entries = sorted(set(entries), key=lambda e: e[0])
    os.makedirs(os.path.dirname(os.path.abspath(tar_path)) or ".", exist_ok=True)
    with tarfile.open(tar_path, "w") as tar:
        for arcname, abspath in entries:
            info = tar.gettarinfo(abspath, arcname=arcname)
            info.mtime = 0
            info.uid = 0
            info.gid = 0
            info.uname = ""
            info.gname = ""
            info.mode = 0o644
            with open(abspath, "rb") as f:
                tar.addfile(info, f)


def import_(tar_path: str, dest: str) -> dict:
    """Extract `tar_path` into the fresh directory `dest`, folding
    `.reticuli/deps/<name>` back into `.reticuli/sealed/<name>`, then
    verify identity on the bytes received."""
    os.makedirs(dest, exist_ok=True)
    with tarfile.open(tar_path, "r") as tar:
        for member in tar.getmembers():
            if not member.isfile():
                continue
            name = member.name
            if name.startswith(_DEPS + "/"):
                rest = name[len(_DEPS) + 1:]
                target_rel = f"{_SEALED}/{rest}"
            else:
                target_rel = name
            target_path = os.path.join(dest, target_rel)
            os.makedirs(os.path.dirname(target_path), exist_ok=True)
            src = tar.extractfile(member)
            try:
                with open(target_path, "wb") as out:
                    out.write(src.read())
            finally:
                src.close()

    try:
        verified = kernel.verify(dest)
        return {"ok": verified["ok"], "root": verified["root"]}
    except kernel.ClaimError as exc:
        return {"ok": False, "root": None, "error": str(exc)}
