"""Cold audits and independent rebuilds of a sealed claim."""

from __future__ import annotations

import json
import math
import os
import shutil
import subprocess
import tempfile
import time
from pathlib import Path

from . import core, identity, recipe, run, seal

sandbox_backend = run.sandbox_backend


def _step_guidance(step: dict, enabled: bool = True) -> str:
    """Return the producer hint under either supported spelling."""
    if not enabled:
        return ""
    return str(step.get("guidance", step.get("request", "")))


def _compare_pin(source: str | os.PathLike[str], room: str | os.PathLike[str],
                 name: str) -> bool:
    """Compare one newly earned output with the recorded pinned bytes."""
    try:
        return (core._hash_file(core._safe(source, name))
                == core._hash_file(core._safe(room, name)))
    except core.ClaimError:
        return False


def _materialize(source: str | os.PathLike[str], room: str | os.PathLike[str],
                 claim_recipe: dict | None = None, *, generated: bool = False) -> None:
    """Make a clean judging room from the recipe and declared source files."""
    claim_recipe = claim_recipe or recipe.load_recipe(source)
    os.makedirs(room, exist_ok=True)
    source_recipe = recipe.recipe_path(source)
    core._copy_into(source_recipe, core._safe(room, os.path.basename(source_recipe)))
    for name in recipe._inputs(claim_recipe, source):
        core._copy_into(core._safe(source, name), core._safe(room, name))
    for step in recipe._steps(claim_recipe):
        name = step["output"]
        classification = step.get("class", "generated" if step["kind"] == "produce" else "pinned")
        if step["kind"] == "produce" and (generated or classification != "generated"):
            path = core._safe(source, name)
            if os.path.isfile(path):
                core._copy_into(path, core._safe(room, name))


def _gate_rows(source: str | os.PathLike[str], room: str | os.PathLike[str],
               claim_recipe: dict) -> list[dict]:
    missing = run.preflight(claim_recipe)
    try:
        environment = run.furnish(room, claim_recipe) if not missing else None
    except core.ClaimError as error:
        missing = [str(error)]
        environment = None
    rows = []
    for step in recipe.gates(claim_recipe):
        name = step["output"]
        if missing:
            rows.append({"output": name, "status": "environment",
                         "quarantine": run.sandbox_backend(),
                         "error": ", ".join(missing)})
            continue
        gate_env = None
        if environment:
            gate_env = {"PATH": os.path.join(environment, "bin") + os.pathsep + os.environ.get("PATH", "")}
        result = run.run_gate(step["run"], room, claim_recipe, env=gate_env)
        status = result["status"]
        if status == "ok":
            status = "reproduced" if _compare_pin(source, room, name) else "mismatch"
        rows.append({"output": name, "status": status,
                     "quarantine": result["quarantine"],
                     "stdout": result.get("stdout", ""),
                     "stderr": result.get("stderr", "")})
    return rows


def audit(directory: str | os.PathLike[str], *, shallow: bool = False) -> dict:
    """Re-earn every gate against present generated bytes in a clean room."""
    try:
        verified = seal.verify(directory)
        if not verified["ok"]:
            return {"ok": False, "root": verified["root"], "gates": [],
                    "verdict": "identity mismatch"}
        claim_recipe = recipe.load_recipe(directory)
        with tempfile.TemporaryDirectory(prefix="reticuli-audit-") as room:
            _materialize(directory, room, claim_recipe, generated=True)
            rows = _gate_rows(directory, room, claim_recipe)
        good = all(row["status"] in ("ok", "reproduced") for row in rows)
        return {"ok": good, "root": verified["root"], "gates": rows,
                "verdict": "earned" if good else "carried or broken"}
    except (core.ClaimError, OSError) as error:
        return {"ok": False, "gates": [], "verdict": str(error)}


def _read_usage(directory: str | os.PathLike[str]) -> dict:
    """Read optional producer reported usage, excluding measured wall time."""
    path = core._safe(directory, core.USAGE)
    try:
        with open(path, encoding="utf-8") as source:
            data = json.load(source)
    except (OSError, ValueError):
        return {}
    if not isinstance(data, dict):
        return {}
    return {key: value for key in ("usd", "tokens", "calls")
            if isinstance((value := data.get(key)), (int, float))
            and not isinstance(value, bool) and math.isfinite(value) and value >= 0}


def _produce(command: str, room: str | os.PathLike[str], *,
             environment: dict[str, str] | None = None) -> dict:
    """Run the caller's producer without gate confinement, retaining HOME."""
    env = {key: os.environ[key] for key in core._KEEP_ENV if key in os.environ}
    if environment:
        env.update({str(key): str(value) for key, value in environment.items()})
    # The producer is the caller's oracle. Keep its credentials and ordinary
    # process environment; only the judging gate receives a scratch HOME.
    env["HOME"] = os.environ.get("HOME", "")
    start = time.monotonic()
    result = run._run([core._SHELL, "-c", command], os.fspath(room), env,
                      core.PRODUCER_TIMEOUT)
    result["seconds"] = time.monotonic() - start
    return result


def rebuild(directory: str | os.PathLike[str], producer: str,
            into: str | os.PathLike[str], *, produce_from: str | None = None,
            input_from: str | None = None, guidance: bool = True,
            producer_env: dict[str, str] | None = None) -> dict:
    """Regrow generated bytes from pinned inputs, then earn every gate."""
    verified = seal.verify(directory)
    if not verified["ok"]:
        raise core.ClaimError("cannot rebuild a claim with mismatched identity")
    claim_recipe = recipe.load_recipe(directory)
    if os.path.exists(into) and os.listdir(into):
        raise core.ClaimError(f"rebuild target is not empty: {into}")
    _materialize(input_from or directory, into, claim_recipe)
    outputs = recipe.generated_outputs(claim_recipe)
    environment = dict(producer_env or {})
    environment.update({core._ENV_CLAIM: claim_recipe["claim"]["name"],
                        core._ENV_OUTPUTS: os.pathsep.join(outputs),
                        core._ENV_OUTPUT: outputs[0] if outputs else ""})
    hints = [_step_guidance(step, guidance) for step in recipe.produces(claim_recipe)]
    if guidance:
        environment[core._ENV_REQUEST] = "\n".join(hint for hint in hints if hint)
    produced = _produce(producer, into, environment=environment)
    if produced["status"] != "ok":
        raise core.ClaimError("producer " + produced["status"] + ": " + produced.get("stderr", ""))
    rows = _gate_rows(directory, into, claim_recipe)
    if any(row["status"] not in ("ok", "reproduced") for row in rows):
        raise core.ClaimError(f"rebuilt gates did not reproduce: {rows!r}")
    manifest = seal.seal(into)
    if manifest["root"] != verified["root"]:
        raise core.ClaimError("rebuilt claim root differs from source")
    event = {"seconds": produced["seconds"], "quarantine": run.sandbox_backend(),
             **_read_usage(into)}
    if os.environ.get(core._ENV_VENDOR):
        event["vendor"] = os.environ[core._ENV_VENDOR]
    if os.environ.get(core._ENV_MODEL):
        event["model"] = os.environ[core._ENV_MODEL]
    run.ledger(into, event)
    return {"root": manifest["root"], "gates": rows,
            "quarantine": run.sandbox_backend(), "build_digest": identity.build_digest(into)}


def _ssh_verify(signature: str, data: bytes, signers: str, namespace: str = core.SIGN_NAMESPACE) -> bool:
    """Verify an SSH detached signature against an allowed-signers file."""
    try:
        completed = subprocess.run(
            ["ssh-keygen", "-Y", "verify", "-f", signers, "-I", "reticuli",
             "-n", namespace, "-s", signature], input=data,
            capture_output=True, check=False, timeout=15)
        return completed.returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def _authorized(directory: str | os.PathLike[str], anchor: str | None = None) -> bool:
    """Whether a local signature can be verified with the supplied anchor."""
    if not anchor:
        return False
    try:
        manifest = seal.read_manifest(directory)
        signatures = Path(core._safe(directory, core.SIGN_DIR))
        return any(_ssh_verify(str(path), manifest["root"].encode(), anchor)
                   for path in signatures.glob("*.sign") if path.is_file())
    except (core.ClaimError, OSError):
        return False
