"""Run, list, and return sealed packages to their latent form."""

from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
import tomllib

from . import kernel
from ._util import declared_inputs, safe_path


STATE = ".launcher"


class LaunchRefusal(Exception):
    def __init__(self, code: int, message: str):
        super().__init__(message)
        self.code = code


def _recipe(claim: str) -> dict:
    document = kernel.load_recipe(claim)
    # Validate every path before touching any output, including paths in a
    # tampered recipe. The kernel validates these too; this makes the launcher's
    # own file operations explicitly use the same confinement boundary.
    for name in declared_inputs(claim):
        safe_path(claim, name)
    for step in document.get("step", []):
        safe_path(claim, step["output"])
    return document


def _generated(document: dict) -> list[str]:
    return [step["output"] for step in document.get("step", [])
            if step.get("class", "generated" if step["kind"] == "produce" else "pinned")
            == "generated" and "from" not in step]


def _package(claim: str, document: dict) -> str:
    if "package.toml" not in declared_inputs(claim):
        raise LaunchRefusal(3, "package.toml must be a pinned input")
    path = safe_path(claim, "package.toml")
    try:
        with open(path, "rb") as stream:
            package = tomllib.load(stream)
        entry = package["package"]["entrypoint"]
    except (OSError, ValueError, KeyError, TypeError) as exc:
        raise LaunchRefusal(3, f"invalid package.toml: {exc}") from exc
    if not isinstance(entry, str):
        raise LaunchRefusal(3, "package.toml entrypoint must be a path")
    try:
        safe_path(claim, entry)
    except kernel.ClaimError as exc:
        raise LaunchRefusal(3, f"invalid package.toml entrypoint: {exc}") from exc
    return entry


def _state_path(claim: str) -> str:
    return os.path.join(claim, STATE, "consent.json")


def _read_state(claim: str) -> dict:
    try:
        with open(_state_path(claim), encoding="utf-8") as stream:
            state = json.load(stream)
        if isinstance(state, dict):
            return state
    except FileNotFoundError:
        pass
    except (OSError, ValueError) as exc:
        raise LaunchRefusal(6, f"launcher state is unreadable; strip to recover: {exc}") from exc
    return {}


def _write_state(claim: str, state: dict) -> None:
    folder = os.path.join(claim, STATE)
    os.makedirs(folder, exist_ok=True)
    path = _state_path(claim)
    temporary = path + ".tmp"
    with open(temporary, "w", encoding="utf-8") as stream:
        json.dump(state, stream, sort_keys=True)
        stream.write("\n")
    os.replace(temporary, path)


def strip(claim: str) -> int:
    document = _recipe(claim)
    for name in _generated(document):
        path = safe_path(claim, name)
        if os.path.isfile(path):
            os.unlink(path)
    shutil.rmtree(os.path.join(claim, STATE), ignore_errors=True)
    print("stripped generated bytes", file=sys.stderr)
    return 0


def _environment(claim: str, backend: str) -> dict[str, str]:
    scratch = os.path.join(claim, STATE, "tmp")
    os.makedirs(scratch, exist_ok=True)
    env = {key: os.environ[key] for key in ("PATH", "LANG", "LC_ALL", "TZ")
           if key in os.environ}
    env.setdefault("PATH", os.defpath)
    env["HOME"] = scratch
    env["TMPDIR"] = scratch
    if backend in ("seatbelt", "bubblewrap", "inherited"):
        env[kernel._JAILED] = os.environ.get(kernel._JAILED, "1")
    return env


def _execute(claim: str, entry: str, args: list[str], no_sandbox: bool) -> int:
    command = " ".join(shlex.quote(part) for part in [sys.executable, entry, *args])
    if no_sandbox:
        argv, backend = ["/bin/sh", "-c", command], "off"
    else:
        argv, backend = kernel.sandbox(command, claim)
    print(f'quarantine = "{backend}"', file=sys.stderr)
    done = subprocess.run(argv, cwd=claim, env=_environment(claim, backend),
                          check=False)
    return done.returncode


def run_claim(claim: str, *, accept: bool, signed_only: bool,
              no_sandbox: bool, args: list[str]) -> int:
    document = _recipe(claim)
    entry = _package(claim, document)
    checked = kernel.verify(claim)
    if not checked["ok"]:
        raise LaunchRefusal(6, "claim identity drifted; strip is the recovery path")
    phase = kernel.phase(claim)
    if signed_only and phase != "signed":
        raise LaunchRefusal(5, "claim is not signed to you")
    outputs = _generated(document)
    state = _read_state(claim)
    digest = kernel.build_digest(claim)
    if state.get("status") == "accepted" and state.get("digest") != digest:
        raise LaunchRefusal(6, "accepted build drifted; strip to recover")
    missing = [name for name in outputs if not os.path.isfile(safe_path(claim, name))]
    if missing:
        # A partial build is evidence to preserve for inspection.
        if len(missing) != len(outputs):
            raise LaunchRefusal(6, "partial build drifted; strip to recover")
        producer = os.environ.get("RETICULI_PRODUCER")
        if not producer:
            raise LaunchRefusal(7, "latent claim needs RETICULI_PRODUCER")
        with tempfile.TemporaryDirectory(prefix="reticuli-launch-") as room:
            result = kernel.rebuild(claim, producer, room)
            if not result.get("ok") or result.get("root") != checked["root"]:
                raise LaunchRefusal(6, "rebuild failed audit or root check; strip to recover")
            for name in outputs:
                source = safe_path(room, name)
                target = safe_path(claim, name)
                os.makedirs(os.path.dirname(target), exist_ok=True)
                shutil.copy2(source, target)
        digest = kernel.build_digest(claim)
        _write_state(claim, {"status": "fresh", "digest": digest,
                             "root": checked["root"]})
        state = _read_state(claim)
    if state.get("status") == "fresh" and not accept:
        raise LaunchRefusal(4, "newly generated bytes need --accept-generated")
    audited = kernel.audit(claim)
    if not audited.get("ok"):
        raise LaunchRefusal(6, "build failed audit; strip to recover")
    if state.get("status") == "fresh":
        _write_state(claim, {"status": "accepted", "digest": digest,
                             "root": checked["root"]})
    print(f"{phase} claim", file=sys.stderr)
    return _execute(claim, entry, args, no_sandbox)


def list_claims(claims: list[str]) -> int:
    for claim in claims:
        document = _recipe(claim)
        manifest = kernel.read_manifest(claim)
        outputs = _generated(document)
        material = all(os.path.isfile(safe_path(claim, name)) for name in outputs)
        print(f"{manifest['name']} {manifest['root'][:12]} "
              f"{kernel.phase(claim)} {'materialized' if material else 'latent'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        epilog="run options: --accept-generated --signed-only --no-sandbox",
    )
    verbs = parser.add_subparsers(dest="verb", required=True)
    run_parser = verbs.add_parser("run", help="run a package entrypoint")
    run_parser.add_argument("claim")
    run_parser.add_argument("--accept-generated", action="store_true")
    run_parser.add_argument("--signed-only", action="store_true")
    run_parser.add_argument("--no-sandbox", action="store_true")
    verbs.add_parser("strip", help="delete generated outputs").add_argument("claim")
    verbs.add_parser("ls", help="list claim status").add_argument("claims", nargs="+")
    raw = list(sys.argv[1:] if argv is None else argv)
    if raw and raw[0] == "run" and "--" in raw:
        index = raw.index("--")
        args = raw[index + 1:]
        raw = raw[:index]
    else:
        args = []
    parsed = parser.parse_args(raw)
    try:
        if parsed.verb == "run":
            return run_claim(os.path.abspath(parsed.claim),
                             accept=parsed.accept_generated,
                             signed_only=parsed.signed_only,
                             no_sandbox=parsed.no_sandbox, args=args)
        if parsed.verb == "strip":
            return strip(os.path.abspath(parsed.claim))
        return list_claims([os.path.abspath(path) for path in parsed.claims])
    except LaunchRefusal as exc:
        print(str(exc), file=sys.stderr)
        return exc.code
    except (kernel.ClaimError, OSError, ValueError) as exc:
        print(f"not runnable: {exc}", file=sys.stderr)
        return 3


if __name__ == "__main__":
    raise SystemExit(main())
