"""Local cache for previously earned verdicts, keyed by bytes and host."""

from __future__ import annotations

import hashlib
import json
import os
import platform
import sys
import tempfile
from datetime import datetime, timezone

from . import kernel
from ._util import copy_into, safe_path


def _host():
    return {"platform": platform.platform(), "python": sys.version}


def _cache_dir():
    return os.environ.get("RETICULI_CACHE", os.path.join(os.path.expanduser("~"),
                                                        ".cache", "reticuli", "verdicts"))


def _key(value):
    data = json.dumps(value, sort_keys=True).encode("utf-8")
    return hashlib.sha256(data).hexdigest()


def _path(fingerprint):
    return os.path.join(_cache_dir(), _key(fingerprint) + ".json")


def _read(fingerprint):
    try:
        with open(_path(fingerprint), encoding="utf-8") as stream:
            entry = json.load(stream)
    except (OSError, ValueError):
        return None
    if not isinstance(entry, dict) or entry.get("fingerprint") != fingerprint:
        return None
    verdict = entry.get("verdict")
    return entry if isinstance(verdict, dict) and verdict.get("ok") is True else None


def _write(fingerprint, verdict, source):
    if not isinstance(verdict, dict) or verdict.get("ok") is not True:
        return None
    entry = {"fingerprint": fingerprint, "verdict": verdict,
             "source": source,
             "when": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}
    destination = _path(fingerprint)
    os.makedirs(os.path.dirname(destination), exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=".verdict-", dir=os.path.dirname(destination))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            json.dump(entry, stream, sort_keys=True)
            stream.write("\n")
        os.replace(temporary, destination)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)
    return entry


def fingerprint(path):
    """Key a claim verdict by sealed identity, generated bytes, and host."""
    checked = kernel.verify(path)
    if not checked["ok"]:
        raise kernel.ClaimError("claim identity mismatch")
    return {"root": checked["root"], "build": kernel.build_digest(path), **_host()}


def lookup(path):
    """Return a passing cached verdict, or None when none matches."""
    entry = _read(fingerprint(path))
    return entry["verdict"] if entry else None


def remember(path, verdict):
    """Remember only a passing verdict for the current claim bytes."""
    return _write(fingerprint(path), verdict, os.path.abspath(path))


def _layer_fingerprint(layer):
    files = dict(layer["files"])
    check_name, check_source = layer["check"]
    if check_name in files:
        raise kernel.ClaimError("layer check duplicates a source file")
    sources = {**files, check_name: check_source}
    parts = {name: kernel._hash_file(source) for name, source in sorted(sources.items())}
    root = _key({"files": parts, "gate": layer["gate"], "verdict": layer["verdict"]})
    build = _key({name: parts[name] for name in sorted(files)})
    return {"root": root, "build": build, **_host()}


def layered_audit(layers):
    """Earn each layer cold or explicitly cite the cached verdict it uses."""
    rows = []
    for layer in layers:
        name = layer["name"]
        fp = _layer_fingerprint(layer)
        cached = _read(fp)
        if cached:
            rows.append({"name": name, "ok": True, "status": "reused",
                         "reused": cached["when"], "source": cached["source"],
                         "fingerprint": fp})
            continue
        with tempfile.TemporaryDirectory(prefix="reticuli-layer-audit-") as room:
            for target, source in {**layer["files"], layer["check"][0]: layer["check"][1]}.items():
                copy_into(source, safe_path(room, target))
            outcome = kernel.run_gate(layer["gate"], room)
            ok = outcome["status"] == "ok"
        row = {"name": name, "ok": ok, "status": "earned" if ok else "failed",
               "gate": outcome, "fingerprint": fp}
        if ok:
            saved = _write(fp, {"ok": True, "gate": outcome["status"]},
                           os.path.abspath(layer["check"][1]))
            row["source"] = saved["source"]
            row["when"] = saved["when"]
        rows.append(row)
    return {"ok": all(row["ok"] for row in rows), "layers": rows}
