"""DRAFT: the acceptance battery for records -- written before the code exists.

spec/record.md is sealed; this check is the request that implements it, and it
stages itself: batteries A-E turn green the moment `reticuli.record` answers
them, and battery F stays red until the kernel's `crosscheck` accepts a record
in place of a directory -- kernel behavior, which lands with the v2.2
revision. The draft lives in scripts/ so nothing runs or pins it by accident:
gate.py globs only criteria/, and reticuli.toml does not declare this file.

Where the batteries land when the code arrives:

    A-E  -> criteria/exchange_check.py   records are authored and signed in
            the exchange layer: emission, the document discipline, signing
    F    -> criteria/kernel_check.py     crosscheck CONSUMES records; that is
            kernel behavior, so pinning it belongs to the v2.2 revision,
            batched with the symlink rule and finding 12 -- one suite change,
            one re-earned proof

Two decisions taken here that spec/record.md left implicit:

  * `record_proof` REFUSES a record whose signature does not verify against
    the caller's anchor. A proof embeds the digests and signer identities of
    the records it consumed, and embedding "unverified" would poison the walk.
    Comparison stays free -- `crosscheck` judges whatever it is handed, as it
    always has for directories -- but durable evidence requires an anchor.
    The boundary is the TRANSPORT: directory legs are the caller's own
    executions and stay anchor-free forever; record legs are relayed
    statements and are strict everywhere, even when the caller wrote them.
  * The first machine of a recorded proof must be a DIRECTORY: the proof is
    residue on M1's manifest, and a frozen record has no manifest to land on.

    python3 scripts/record_check.py        (from the repository root)
"""
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

from reticuli import kernel

SIGNERS = "RETICULI_SIGNERS"          # the well-known anchor name, as a literal


def _now() -> str:
    import time
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


# A minimal claim: one pinned check, one generated file, one gate. The gate
# reads the generated file, so different generated bytes can carry one root.
CHECK = '''\
text = open("x.py", encoding="utf-8").read()
assert int(text.split("#")[0].strip()) > 0, "x.py must hold a positive integer"
with open("OK", "w", encoding="utf-8") as f:
    f.write("ok\\n")
print("x-ok")
'''

RECIPE = '''\
[claim]
name = "probe"
inputs = ["check_x.py"]

[[step]]
kind = "produce"
output = "x.py"
class = "generated"

[[step]]
kind = "gate"
output = "OK"
class = "validated"
run = "python3 check_x.py"
'''

REQUIRED = {"record", "name", "root", "build_digest", "gates", "environment", "when"}
HEX64 = re.compile(r"^[0-9a-f]{64}$")
WHEN = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")


def make_claim(where, x=b"7\n", usd=None, producer=None, seal=True):
    os.makedirs(where)
    with open(os.path.join(where, "reticuli.toml"), "w", encoding="utf-8") as f:
        f.write(RECIPE)
    with open(os.path.join(where, "check_x.py"), "w", encoding="utf-8") as f:
        f.write(CHECK)
    with open(os.path.join(where, "x.py"), "wb") as f:
        f.write(x)
    with open(os.path.join(where, "OK"), "w", encoding="utf-8") as f:
        f.write("ok\n")
    if seal:
        kernel.seal(where)
    if usd is not None:
        kernel.ledger(where, {"event": "oracle", "when": _now(),
                              "calls": 1, "seconds": 3.0, "usd": usd})
    if producer:
        kernel.ledger(where, dict({"event": "producer", "when": _now()},
                                  **producer))
    return where


def refuses(what, fn, *args, **kwargs):
    try:
        fn(*args, **kwargs)
    except kernel.ClaimError:
        return
    raise AssertionError(f"not refused in band: {what}")


def battery_emission(record, work):
    # A record exists only if identity holds: unsealed and drifted both refuse.
    refuses("emit from an unsealed claim", record.emit,
            make_claim(os.path.join(work, "unsealed"), seal=False))
    drifted = make_claim(os.path.join(work, "drifted"))
    with open(os.path.join(drifted, "check_x.py"), "a", encoding="utf-8") as f:
        f.write("# drift\n")
    refuses("emit from a drifted claim", record.emit, drifted)

    fresh = make_claim(os.path.join(work, "fresh"))
    doc = record.emit(fresh)
    assert REQUIRED <= set(doc), f"missing members: {REQUIRED - set(doc)}"
    assert doc["record"] == 1 and doc["name"] == "probe"
    assert HEX64.match(doc["root"]) and doc["root"] == kernel.verify(fresh)["root"]
    assert doc["build_digest"] == kernel.build_digest(fresh)
    assert WHEN.match(doc["when"]), f"bad when: {doc['when']!r}"
    for key in ("platform", "machine", "runtime"):
        value = doc["environment"].get(key)
        assert isinstance(value, str) and value, f"environment.{key} missing"

    # Verdicts are earned at emission: the gate ran, and per-gate wall-clock
    # is deliberately not a member (spec/record.md, Decisions).
    (gate,) = doc["gates"]
    assert gate["output"] == "OK" and gate["status"] == "ok"
    assert gate["sandbox"] in ("none", "seatbelt", "bubblewrap", "inherited")
    assert "seconds" not in gate, "per-gate wall-clock is outside the document"

    # No ledger: cost is absent, because absent means unmeasured, never zero.
    assert "cost" not in doc and "producer" not in doc

    # The file on disk IS the canonical bytes, and the digest is over them.
    assert record.canonical(doc) == json.dumps(doc, sort_keys=True).encode("utf-8")
    assert record.digest(doc) == hashlib.sha256(record.canonical(doc)).hexdigest()
    path = os.path.join(work, "fresh.record.json")
    record.write(doc, path)
    with open(path, "rb") as f:
        assert f.read() == record.canonical(doc)
    assert record.read(path) == doc

    # A failing gate still emits -- a failed rebuild is evidence -- and says so.
    sick = make_claim(os.path.join(work, "sick"), x=b"-1\n")
    said = record.emit(sick)
    assert said["gates"][0]["status"] == "failed"
    print("ok    A emission: earned, canonical, refusals in band")
    return doc


def battery_cost(record, work):
    measured = make_claim(os.path.join(work, "measured"), usd=2.5,
                          producer={"vendor": "acme", "model": "m-1", "blind": True})
    doc = record.emit(measured)
    # Exactly the units the ledger held -- oracle events carry calls/seconds
    # here -- and never a zero-fill for the ones it did not.
    assert doc["cost"]["usd"] == 2.5 and doc["cost"]["calls"] == 1
    assert "tokens" not in doc["cost"], "unmeasured must stay absent"
    assert doc["producer"]["vendor"] == "acme" and doc["producer"]["blind"] is True
    print("ok    B cost: ledger totals relayed, absent means unmeasured")
    return doc


def battery_validation(record, doc):
    good = json.loads(json.dumps(doc))
    record.validate(good)

    def broken(mutate):
        bad = json.loads(json.dumps(good))
        mutate(bad)
        return bad

    cases = {
        "an unknown top-level member": lambda d: d.update(extra=1),
        "a version newer than understood": lambda d: d.update(record=2),
        "a missing required member": lambda d: d.pop("root"),
        "a root that is not 64 lowercase hex": lambda d: d.update(root="XYZ"),
        "an unknown gate status": lambda d: d["gates"][0].update(status="great"),
        "per-gate seconds smuggled back in": lambda d: d["gates"][0].update(seconds=1.0),
        "a boolean cost": lambda d: d.update(cost={"usd": True}),
        "a negative cost": lambda d: d.update(cost={"usd": -1}),
        "an unknown cost unit": lambda d: d.update(cost={"gpu_hours": 1}),
        "an unknown producer member": lambda d: d.update(producer={"lab": "x"}),
    }
    for what, mutate in cases.items():
        refuses(what, record.validate, broken(mutate))
    print(f"ok    C validation: {len(cases)} refusals, all in band")


def battery_signing(record, work, doc):
    assert shutil.which("ssh-keygen"), "this battery needs ssh-keygen"
    key = os.path.join(work, "key")
    subprocess.run(["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C", "tester",
                    "-f", key], check=True)
    anchor = os.path.join(work, "allowed_signers")
    with open(key + ".pub", encoding="utf-8") as f:
        pub = f.read().split()
    with open(anchor, "w", encoding="utf-8") as f:
        f.write(f"tester {pub[0]} {pub[1]}\n")

    path = os.path.join(work, "signed.record.json")
    record.write(doc, path)
    record.sign(path, key)
    assert record.signer(path, anchor) == "tester"

    # Domain separation: a signature minted in another namespace over the very
    # same bytes must not verify as a record signature. The stale signature is
    # removed first -- ssh-keygen PROMPTS before overwriting one, and a prompt
    # answered by whatever sits on stdin is how this check once fooled itself
    # into asserting against the old signature.
    os.remove(path + ".sig")
    subprocess.run(["ssh-keygen", "-Y", "sign", "-f", key, "-n",
                    kernel.SIGN_NAMESPACE, path], check=True,
                   capture_output=True)
    assert record.signer(path, anchor) is None, "a mint signature is not a record's"
    record.sign(path, key)
    assert record.signer(path, anchor) == "tester"

    # Tamper with one byte and the signature dies with it.
    with open(path, "ab") as f:
        f.write(b" ")
    assert record.signer(path, anchor) is None
    print("ok    D signing: reticuli.record namespace, separated, tamper-fatal")
    return key, anchor


def battery_crosscheck(record, work, key, anchor):
    # Three machines: an original with a ledger, a byte copy, and a redo whose
    # generated bytes differ but whose root does not.
    m1 = make_claim(os.path.join(work, "m1"), usd=2.5)
    m2 = shutil.copytree(m1, os.path.join(work, "m2"))
    m3 = make_claim(os.path.join(work, "m3"), x=b"7  # regrown\n", usd=3.0,
                    producer={"vendor": "acme", "model": "m-1", "blind": True})

    over_dirs = kernel.crosscheck(m1, m2, m3)
    assert over_dirs["satisfied"] and over_dirs["reuse"] and over_dirs["equivalence"]

    # THE BOUNDARY IS THE TRANSPORT, NOT THE PLACE. Directory legs are the
    # caller's own executions -- there is nothing to authenticate, so a proof
    # records without any anchor, exactly as it always has. Record legs are
    # relayed statements whose only provenance is a signature, so they are
    # strict below, even when the records are the caller's own.
    proven_local = kernel.record_proof(m1, m2, m3)
    assert proven_local["proof_recorded"]
    assert "records" not in kernel.read_manifest(m1)["proof"]

    paths = {}
    for label, claim in (("M1", m1), ("M2", m2), ("M3", m3)):
        doc = record.emit(claim)
        paths[label] = os.path.join(work, f"{label}.record.json")
        record.write(doc, paths[label])
        record.sign(paths[label], key)

    # ONE PREDICATE, TWO TRANSPORTS: frozen legs reach the directory verdict.
    over_records = kernel.crosscheck(paths["M1"], paths["M2"], paths["M3"])
    for field in ("satisfied", "equivalence", "reuse", "audited", "roots"):
        assert over_records[field] == over_dirs[field], f"{field} diverged"
    assert over_records["cost"]["comparable"] == over_dirs["cost"]["comparable"]

    # And mixed: a directory, a record, a directory.
    mixed = kernel.crosscheck(m1, paths["M2"], m3)
    assert mixed["satisfied"] == over_dirs["satisfied"]

    # A fabricated machine that shares the root but whose gates failed does
    # not crosscheck -- frozen or not.
    forged = record.read(paths["M3"])
    forged["gates"][0]["status"] = "failed"
    forged_path = os.path.join(work, "forged.record.json")
    record.write(forged, forged_path)
    record.sign(forged_path, key)
    told = kernel.crosscheck(paths["M1"], paths["M2"], forged_path)
    assert not told["satisfied"] and not told["audited"]["M3"]

    # A recorded proof needs a manifest to land on and anchored evidence to
    # embed: M1 must be a directory, and unanchored records refuse.
    refuses("a proof landing on a frozen record",
            kernel.record_proof, paths["M1"], paths["M2"], paths["M3"])
    had = os.environ.pop(SIGNERS, None)
    try:
        refuses("a proof from unanchored records",
                kernel.record_proof, m1, paths["M2"], paths["M3"])
        os.environ[SIGNERS] = anchor
        proven = kernel.record_proof(m1, paths["M2"], paths["M3"])
        assert proven["proof_recorded"]
        proof = kernel.read_manifest(m1)["proof"]
        assert {r["signer"] for r in proof["records"]} == {"tester"}
        assert {r["digest"] for r in proof["records"]} == \
            {record.digest(record.read(paths[m])) for m in ("M2", "M3")}
    finally:
        if had is None:
            os.environ.pop(SIGNERS, None)
        else:
            os.environ[SIGNERS] = had
    print("ok    F crosscheck: one predicate, two transports, proofs anchored")


def main() -> int:
    try:
        from reticuli import record
    except ImportError:
        print("record-check: RED by design -- reticuli.record does not exist "
              "yet.\nThis draft is the request; the module is the answer.",
              file=sys.stderr)
        return 1
    work = tempfile.mkdtemp(prefix="record-check-")
    try:
        doc = battery_emission(record, work)
        measured = battery_cost(record, work)
        battery_validation(record, doc)
        key, anchor = battery_signing(record, work, measured)
        try:
            battery_crosscheck(record, work, key, anchor)
        except kernel.ClaimError as why:
            # A refusal here means the kernel does not yet take a record as a
            # leg -- the staged half of this draft. An assertion failure, by
            # contrast, is a real finding and is not caught.
            print(f"RED   F crosscheck: a record is not yet a leg ({why}); "
                  "this battery lands with the v2.2 revision", file=sys.stderr)
            return 1
    finally:
        shutil.rmtree(work, ignore_errors=True)
    print("record-ok (draft battery; graft A-E into exchange_check, F into "
          "kernel_check at v2.2)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
