"""STAGED DRAFT: battery F -- a record as a crosscheck leg. Red until v2.2.

Batteries A-E (emission, cost, the document discipline, signing) were adopted
into criteria/exchange_check.py when `reticuli.record` landed; the exchange
layer pins them now, and keeping a second copy here would only let the two
drift. What remains is the kernel's half: `crosscheck` accepting a record
file wherever it accepts a claim directory, and `record_proof` holding the
trust boundary. Pinning kernel behavior means a kernel-claim revision, so
this battery rides v2.2, batched with the symlink rule and finding 12 -- one
suite change, one re-earned proof. Graft it into criteria/kernel_check.py
then, and delete this file.

The decisions this battery pins:

  * ONE PREDICATE, TWO TRANSPORTS. Crosscheck over records reaches exactly
    the verdict it reaches over the directories the records were made from,
    and the transports mix freely.
  * THE BOUNDARY IS THE TRANSPORT, NOT THE PLACE. Directory legs are the
    caller's own executions and record proofs anchor-free, as they always
    have; record legs are relayed statements whose only provenance is a
    signature, so `record_proof` refuses one that does not verify against
    the caller's anchor -- a durable proof embeds the digests and signer
    identities of the records it consumed, and "unverified" would poison
    the walk.
  * A proof is residue on M1's manifest, so M1 must be a directory: a frozen
    record has no manifest to land on.

    python3 scripts/record_check.py        (from the repository root)
"""
import os
import shutil
import subprocess
import sys
import tempfile
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

from reticuli import kernel, record

SIGNERS = "RETICULI_SIGNERS"          # the well-known anchor name, as a literal

CHECK = '''\
text = open("x.py", encoding="utf-8").read()
assert int(text.split("#")[0].strip()) > 0, "x.py must hold a positive integer"
with open("OK", "w", encoding="utf-8") as f:
    f.write("ok\\n")
print("x-ok")
'''

RECIPE = '''\
[claim]
name = "probe"
inputs = ["check_x.py"]

[[step]]
kind = "produce"
output = "x.py"
class = "generated"

[[step]]
kind = "gate"
output = "OK"
class = "validated"
run = "python3 check_x.py"
'''


def _now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def make_claim(where, x=b"7\n", usd=None, producer=None):
    os.makedirs(where)
    with open(os.path.join(where, "reticuli.toml"), "w", encoding="utf-8") as f:
        f.write(RECIPE)
    with open(os.path.join(where, "check_x.py"), "w", encoding="utf-8") as f:
        f.write(CHECK)
    with open(os.path.join(where, "x.py"), "wb") as f:
        f.write(x)
    with open(os.path.join(where, "OK"), "w", encoding="utf-8") as f:
        f.write("ok\n")
    kernel.seal(where)
    if usd is not None:
        kernel.ledger(where, {"event": "oracle", "when": _now(),
                              "calls": 1, "seconds": 3.0, "usd": usd})
    if producer:
        kernel.ledger(where, dict({"event": "producer", "when": _now()},
                                  **producer))
    return where


def refuses(what, fn, *args, **kwargs):
    try:
        fn(*args, **kwargs)
    except kernel.ClaimError:
        return
    raise AssertionError(f"not refused in band: {what}")


def battery_crosscheck(work):
    assert shutil.which("ssh-keygen"), "this battery needs ssh-keygen"
    key = os.path.join(work, "key")
    subprocess.run(["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C", "tester",
                    "-f", key], check=True)
    anchor = os.path.join(work, "allowed_signers")
    with open(key + ".pub", encoding="utf-8") as f:
        pub = f.read().split()
    with open(anchor, "w", encoding="utf-8") as f:
        f.write(f"tester {pub[0]} {pub[1]}\n")

    # Three machines: an original with a ledger, a byte copy, and a redo whose
    # generated bytes differ but whose root does not.
    m1 = make_claim(os.path.join(work, "m1"), usd=2.5)
    m2 = shutil.copytree(m1, os.path.join(work, "m2"))
    m3 = make_claim(os.path.join(work, "m3"), x=b"7  # regrown\n", usd=3.0,
                    producer={"vendor": "acme", "model": "m-1", "blind": True})

    over_dirs = kernel.crosscheck(m1, m2, m3)
    assert over_dirs["satisfied"] and over_dirs["reuse"] and over_dirs["equivalence"]

    # THE BOUNDARY IS THE TRANSPORT, NOT THE PLACE. Directory legs are the
    # caller's own executions -- there is nothing to authenticate, so a proof
    # records without any anchor, exactly as it always has. Record legs are
    # relayed statements whose only provenance is a signature, so they are
    # strict below, even when the records are the caller's own.
    proven_local = kernel.record_proof(m1, m2, m3)
    assert proven_local["proof_recorded"]
    assert "records" not in kernel.read_manifest(m1)["proof"]

    paths = {}
    for label, claim in (("M1", m1), ("M2", m2), ("M3", m3)):
        doc = record.emit(claim)
        paths[label] = os.path.join(work, f"{label}.record.json")
        record.write(doc, paths[label])
        record.sign(paths[label], key)

    # ONE PREDICATE, TWO TRANSPORTS: frozen legs reach the directory verdict.
    over_records = kernel.crosscheck(paths["M1"], paths["M2"], paths["M3"])
    for field in ("satisfied", "equivalence", "reuse", "audited", "roots"):
        assert over_records[field] == over_dirs[field], f"{field} diverged"
    assert over_records["cost"]["comparable"] == over_dirs["cost"]["comparable"]

    # And mixed: a directory, a record, a directory.
    mixed = kernel.crosscheck(m1, paths["M2"], m3)
    assert mixed["satisfied"] == over_dirs["satisfied"]

    # A fabricated machine that shares the root but whose gates failed does
    # not crosscheck -- frozen or not.
    forged = record.read(paths["M3"])
    forged["gates"][0]["status"] = "failed"
    forged_path = os.path.join(work, "forged.record.json")
    record.write(forged, forged_path)
    record.sign(forged_path, key)
    told = kernel.crosscheck(paths["M1"], paths["M2"], forged_path)
    assert not told["satisfied"] and not told["audited"]["M3"]

    # A recorded proof needs a manifest to land on and anchored evidence to
    # embed: M1 must be a directory, and unanchored records refuse.
    refuses("a proof landing on a frozen record",
            kernel.record_proof, paths["M1"], paths["M2"], paths["M3"])
    had = os.environ.pop(SIGNERS, None)
    try:
        refuses("a proof from unanchored records",
                kernel.record_proof, m1, paths["M2"], paths["M3"])
        os.environ[SIGNERS] = anchor
        proven = kernel.record_proof(m1, paths["M2"], paths["M3"])
        assert proven["proof_recorded"]
        proof = kernel.read_manifest(m1)["proof"]
        assert {r["signer"] for r in proof["records"]} == {"tester"}
        assert {r["digest"] for r in proof["records"]} == \
            {record.digest(record.read(paths[m])) for m in ("M2", "M3")}
    finally:
        if had is None:
            os.environ.pop(SIGNERS, None)
        else:
            os.environ[SIGNERS] = had
    print("ok    F crosscheck: one predicate, two transports, proofs anchored")


def main() -> int:
    work = tempfile.mkdtemp(prefix="record-check-")
    try:
        try:
            battery_crosscheck(work)
        except kernel.ClaimError as why:
            # A refusal here means the kernel does not yet take a record as a
            # leg -- the staged half of this draft. An assertion failure, by
            # contrast, is a real finding and is not caught.
            print(f"RED   F crosscheck: a record is not yet a leg ({why}); "
                  "this battery lands with the v2.2 revision", file=sys.stderr)
            return 1
    finally:
        shutil.rmtree(work, ignore_errors=True)
    print("record-ok (battery F: graft into kernel_check.py at v2.2, then "
          "delete this file)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
