"""The launcher: run software that exists only latently in a claim.

A runnable claim is an ordinary Reticuli claim whose pinned inputs include
`package.toml` (`[package] entrypoint = "<file>"`). `run` checks a cached
build or regrows one with a producer, then executes the entrypoint; `strip`
deletes the generated bytes back to latency, because the claim -- not the
code -- is the identity. See `checks/launcher_check.py` for the pinned
contract this module implements.

Launcher state (consent over freshly regrown bytes) lives under
`<claim>/.launcher/` and is removed by `strip`. This module sits above the
kernel (`reticuli.kernel`) and never reaches into `reticuli._kernel`.
"""
import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile
import tomllib

from reticuli import kernel

_KEEP_ENV = ("PATH", "HOME", "TMPDIR", "LANG", "LC_ALL", "TZ", "RETICULI_JAILED")
_ENTRY_TIMEOUT = 120.0

_SEATBELT_OK = None
_BWRAP_OK = None


class Refusal(Exception):
    """A package-contract or path-confinement refusal, with an exit code."""

    def __init__(self, code: int, message: str):
        super().__init__(message)
        self.code = code
        self.message = message


# --------------------------------------------------------------- recipe --
# Small, free-standing readings of the parsed recipe dict `kernel.load_recipe`
# returns -- the launcher's own view, not a reach into `reticuli._kernel`.

def _generated_outputs(recipe: dict) -> list:
    out = []
    for step in recipe.get("step", []):
        if step.get("kind") != "produce":
            continue
        if step.get("class", "generated") == "generated" and "from" not in step:
            out.append(step["output"])
    return out


def _pinned_inputs(recipe: dict, d: str) -> list:
    claim = recipe.get("claim", {}) or {}
    manifest_name = claim.get("inputs_manifest")
    if manifest_name:
        entries = []
        try:
            with open(os.path.join(d, manifest_name), "r", encoding="utf-8") as f:
                text = f.read()
        except OSError:
            return [manifest_name]
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            head, _, rest = line.partition(" ")
            rest = rest.strip()
            if rest and len(head) == 64 and all(c in "0123456789abcdef" for c in head):
                entries.append(rest)
            else:
                entries.append(line)
        return [manifest_name] + entries
    inputs = claim.get("inputs", [])
    return list(inputs) if isinstance(inputs, list) else []


# ----------------------------------------------------------------- paths --

def _safe_join(base: str, name: str) -> str:
    """The same path boundary the kernel enforces: no absolute path, no
    `..` escape, no symlink escape."""
    if not name or not isinstance(name, str):
        raise Refusal(3, f"refuses an empty or non-string path: {name!r}")
    if os.path.isabs(name) or "\x00" in name:
        raise Refusal(3, f"refuses an absolute path: {name!r}")
    parts = name.replace("\\", "/").split("/")
    if any(p in ("", "..", ".") for p in parts):
        raise Refusal(3, f"refuses a path that escapes the claim: {name!r}")
    base_real = os.path.realpath(base)
    cur = base_real
    for part in parts:
        candidate = os.path.join(cur, part)
        if os.path.islink(candidate):
            raise Refusal(3, f"refuses a symlink component: {name!r}")
        cur = candidate
    resolved = os.path.normpath(os.path.join(base_real, *parts))
    if resolved != base_real and not resolved.startswith(base_real + os.sep):
        raise Refusal(3, f"refuses a path that escapes the claim: {name!r}")
    return resolved


# ------------------------------------------------------------- package --

def _package_contract(d: str, recipe: dict) -> str:
    """Validate the package contract; return the entrypoint's relative path."""
    pkg = "package.toml"
    generated = set(_generated_outputs(recipe))
    inputs = set(_pinned_inputs(recipe, d))

    if pkg in generated:
        raise Refusal(
            3, "package.toml is a generated output; it must be a pinned "
               "input, not produced by this claim")
    if pkg not in inputs:
        raise Refusal(
            3, "this claim has no pinned package.toml; a runnable claim's "
               "inputs must pin package.toml")

    path = os.path.join(d, pkg)
    if not os.path.isfile(path):
        raise Refusal(3, f"pinned package.toml is missing on disk: {path!r}")
    try:
        with open(path, "rb") as f:
            doc = tomllib.load(f)
    except tomllib.TOMLDecodeError as exc:
        raise Refusal(3, f"package.toml is malformed: {exc}") from exc

    table = doc.get("package")
    if not isinstance(table, dict):
        raise Refusal(3, "package.toml needs a [package] table")
    entry = table.get("entrypoint")
    if not isinstance(entry, str) or not entry:
        raise Refusal(3, "package.toml [package] needs a string entrypoint")

    _safe_join(d, entry)
    return entry


# ------------------------------------------------------------- sandbox --
# A self-contained reading of the host's functional sandbox, parallel to
# `reticuli._kernel.run`'s own probe -- the launcher's execution of the
# entrypoint is a different concern from the kernel's execution of a gate,
# so it keeps its own copy rather than reaching into the kernel's privates.

def _quote_sb(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _seatbelt_profile(writable) -> str:
    lines = [
        "(version 1)",
        "(deny default)",
        "(allow process-fork)",
        "(allow process-exec)",
        "(allow signal)",
        "(allow sysctl-read)",
        "(allow mach-lookup)",
        "(allow iokit-open)",
        "(allow file-read*)",
        '(allow file-write-data file-ioctl (subpath "/dev"))',
    ]
    for path in writable:
        lines.append('(allow file-write* (subpath "%s"))' % _quote_sb(path))
    return "\n".join(lines)


def _seatbelt_usable() -> bool:
    global _SEATBELT_OK
    if _SEATBELT_OK is not None:
        return _SEATBELT_OK
    if platform.system() != "Darwin" or not shutil.which("sandbox-exec"):
        _SEATBELT_OK = False
        return False
    probe = tempfile.mkdtemp(prefix="reticuli-launcher-sbprobe-")
    try:
        real = os.path.realpath(probe)
        profile = _seatbelt_profile([real])
        try:
            allowed = subprocess.run(
                ["/usr/bin/sandbox-exec", "-p", profile, "/bin/sh", "-c",
                 "printf x > ok"],
                cwd=real, capture_output=True, timeout=10)
            denied = subprocess.run(
                ["/usr/bin/sandbox-exec", "-p", profile, "/bin/sh", "-c",
                 "printf x > /denied-by-reticuli-launcher-probe"],
                cwd=real, capture_output=True, timeout=10)
            _SEATBELT_OK = (
                allowed.returncode == 0
                and os.path.isfile(os.path.join(real, "ok"))
                and denied.returncode != 0)
        except (OSError, subprocess.TimeoutExpired):
            _SEATBELT_OK = False
    finally:
        shutil.rmtree(probe, ignore_errors=True)
    return _SEATBELT_OK


def _bwrap_usable() -> bool:
    global _BWRAP_OK
    if _BWRAP_OK is not None:
        return _BWRAP_OK
    if not shutil.which("bwrap"):
        _BWRAP_OK = False
        return False
    try:
        r = subprocess.run(
            ["bwrap", "--unshare-net", "--ro-bind", "/", "/", "--", "/bin/true"],
            capture_output=True, timeout=10)
        _BWRAP_OK = (r.returncode == 0)
    except (OSError, subprocess.TimeoutExpired):
        _BWRAP_OK = False
    return _BWRAP_OK


def _in_band() -> bool:
    return bool(os.environ.get("RETICULI_JAILED"))


def _sandbox_backend() -> str:
    if _in_band():
        return "inherited"
    system = platform.system()
    if system == "Darwin" and _seatbelt_usable():
        return "seatbelt"
    if system == "Linux" and _bwrap_usable():
        return "bubblewrap"
    return "none"


def _bwrap_argv(real, home, tmp) -> list:
    return [
        "bwrap", "--unshare-net", "--die-with-parent",
        "--dev", "/dev", "--proc", "/proc",
        "--ro-bind", "/", "/",
        "--bind", real, real, "--bind", home, home, "--bind", tmp, tmp,
        "--chdir", real, "--",
    ]


def _sandbox_argv(backend, argv, d, home, tmp) -> list:
    real = os.path.realpath(d)
    if backend == "seatbelt":
        profile = _seatbelt_profile([real])
        return ["/usr/bin/sandbox-exec", "-p", profile] + list(argv)
    if backend == "bubblewrap":
        return _bwrap_argv(real, home, tmp) + list(argv)
    return list(argv)


def _scrub_env(home=None, tmp=None) -> dict:
    env = {k: os.environ[k] for k in _KEEP_ENV if k in os.environ}
    if home is not None:
        env["HOME"] = home
    if tmp is not None:
        env["TMPDIR"] = tmp
    return env


def _run_entrypoint(d: str, entry: str, args: list, backend: str) -> int:
    real = os.path.realpath(d)
    real_jail = backend in ("seatbelt", "bubblewrap")
    home = tmp = None
    if real_jail:
        room = os.path.join(real, ".launcher", "room")
        home = os.path.join(room, "home")
        tmp = os.path.join(room, "tmp")
        os.makedirs(home, exist_ok=True)
        os.makedirs(tmp, exist_ok=True)
    env = _scrub_env(home, tmp)
    if real_jail:
        env["RETICULI_JAILED"] = backend
    argv = ["python3", entry] + list(args)
    wrapped = _sandbox_argv(backend, argv, real, home, tmp)
    try:
        proc = subprocess.run(wrapped, cwd=real, env=env, timeout=_ENTRY_TIMEOUT)
        return proc.returncode
    except subprocess.TimeoutExpired:
        sys.stderr.write("launcher: entrypoint timed out\n")
        return 1


# ---------------------------------------------------------------- state --

def _digest_map(d: str, outputs: list) -> dict:
    out = {}
    for name in outputs:
        path = os.path.join(d, name)
        if os.path.isfile(path):
            h = hashlib.sha256()
            with open(path, "rb") as f:
                for chunk in iter(lambda: f.read(1 << 20), b""):
                    h.update(chunk)
            out[name] = h.hexdigest()
    return out


def _read_state(path: str) -> dict:
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}


def _write_state(path: str, obj: dict) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(obj, f, sort_keys=True)
    os.replace(tmp, path)


def _clear_state(path: str) -> None:
    try:
        os.remove(path)
    except OSError:
        pass


def _regrow(d: str, producer_cmd: str, outputs: list) -> None:
    """Rebuild into a scratch room, then land the generated outputs on `d`."""
    tmp_root = tempfile.mkdtemp(prefix="reticuli-launcher-rebuild-")
    try:
        into = os.path.join(tmp_root, "room")
        kernel.rebuild(d, producer=producer_cmd, into=into)
        for name in outputs:
            src = os.path.join(into, name)
            if os.path.isfile(src):
                dst = os.path.join(d, name)
                os.makedirs(os.path.dirname(dst) or d, exist_ok=True)
                shutil.copyfile(src, dst)
    finally:
        shutil.rmtree(tmp_root, ignore_errors=True)


def _refuse(code: int, message: str) -> int:
    sys.stderr.write(f"launcher: {message}\n")
    sys.stderr.flush()
    return code


# ----------------------------------------------------------------- run --

def cmd_run(rest: list) -> int:
    if "--" in rest:
        idx = rest.index("--")
        head, entry_args = rest[:idx], rest[idx + 1:]
    else:
        head, entry_args = rest, []

    flags = {t for t in head if t.startswith("--")}
    positional = [t for t in head if not t.startswith("--")]
    known = {"--accept-generated", "--signed-only", "--no-sandbox"}
    if (flags - known) or len(positional) != 1:
        sys.stderr.write(
            "launcher: usage: run <claim> [--accept-generated] "
            "[--signed-only] [--no-sandbox] [-- args...]\n")
        return 2

    claim_arg = positional[0]
    accept_generated = "--accept-generated" in flags
    signed_only = "--signed-only" in flags
    no_sandbox = "--no-sandbox" in flags
    d = os.path.abspath(claim_arg)

    try:
        recipe = kernel.load_recipe(d)
    except kernel.ClaimError as exc:
        return _refuse(3, str(exc))

    try:
        entry = _package_contract(d, recipe)
    except Refusal as r:
        return _refuse(r.code, r.message)

    try:
        ph = kernel.phase(d)
    except kernel.ClaimError as exc:
        return _refuse(6, f"claim does not verify: {exc}")

    if signed_only and ph != "signed":
        return _refuse(5, "--signed-only refuses a claim that is not signed to you")

    outputs = _generated_outputs(recipe)
    present = [o for o in outputs if os.path.isfile(os.path.join(d, o))]
    latent = bool(outputs) and len(present) < len(outputs)

    launcher_dir = os.path.join(d, ".launcher")
    pending_path = os.path.join(launcher_dir, "pending.json")
    accepted_path = os.path.join(launcher_dir, "accepted.json")

    if latent:
        producer_cmd = os.environ.get("RETICULI_PRODUCER")
        if not producer_cmd:
            return _refuse(
                7, "claim is latent and no producer is configured; "
                   "set RETICULI_PRODUCER to regrow it")
        try:
            _regrow(d, producer_cmd, outputs)
        except kernel.ClaimError as exc:
            return _refuse(1, f"rebuild refused: {exc}")

        digests = _digest_map(d, outputs)
        _clear_state(accepted_path)
        _write_state(pending_path, digests)
        if not accept_generated:
            return _refuse(
                4, "freshly generated bytes materialized but not executed; "
                   "pass --accept-generated to execute and accept them")
        _write_state(accepted_path, digests)
        _clear_state(pending_path)
    else:
        digests_now = _digest_map(d, outputs)
        if os.path.isfile(pending_path):
            if digests_now != _read_state(pending_path):
                return _refuse(
                    6, "drifted build: the freshly generated bytes changed "
                       "before being accepted; strip and regrow to recover")
            if not accept_generated:
                return _refuse(
                    4, "freshly generated bytes materialized but not "
                       "executed; pass --accept-generated to execute and "
                       "accept them")
            _write_state(accepted_path, digests_now)
            _clear_state(pending_path)
        elif os.path.isfile(accepted_path):
            if digests_now != _read_state(accepted_path):
                return _refuse(
                    6, "drifted build: the accepted implementation's bytes "
                       "have changed since they were accepted; strip is "
                       "the recovery path")
        else:
            try:
                audit_result = kernel.audit(d)
            except kernel.ClaimError as exc:
                return _refuse(6, f"audit refuses: {exc}")
            if not audit_result.get("ok"):
                return _refuse(
                    6, "drifted build: the implementation on hand does not "
                       "re-earn its gates; strip is the recovery path")

    backend = "off" if no_sandbox else _sandbox_backend()
    sys.stderr.write(f"launcher: phase={ph}\n")
    sys.stderr.write(f'launcher: quarantine = "{backend}"\n')
    sys.stderr.flush()
    return _run_entrypoint(d, entry, entry_args, backend)


# --------------------------------------------------------------- strip --

def cmd_strip(rest: list) -> int:
    positional = [t for t in rest if not t.startswith("--")]
    if len(positional) != 1:
        sys.stderr.write("launcher: usage: strip <claim>\n")
        return 2
    d = os.path.abspath(positional[0])

    try:
        recipe = kernel.load_recipe(d)
    except kernel.ClaimError as exc:
        return _refuse(3, str(exc))

    outputs = _generated_outputs(recipe)
    removed = 0
    for name in outputs:
        path = os.path.join(d, name)
        if os.path.islink(path) or os.path.isfile(path):
            os.remove(path)
            removed += 1
        elif os.path.isdir(path):
            shutil.rmtree(path)
            removed += 1
    shutil.rmtree(os.path.join(d, ".launcher"), ignore_errors=True)
    sys.stderr.write(
        f"launcher: stripped {removed} generated output(s); the claim is latent\n")
    sys.stderr.flush()
    return 0


# ----------------------------------------------------------------- ls --

def cmd_ls(rest: list) -> int:
    claims = [t for t in rest if not t.startswith("--")]
    if not claims:
        sys.stderr.write("launcher: usage: ls <claim>...\n")
        return 2

    exit_code = 0
    lines = []
    for claim_arg in claims:
        d = os.path.abspath(claim_arg)
        try:
            recipe = kernel.load_recipe(d)
            manifest = kernel.read_manifest(d)
            ph = kernel.phase(d)
        except kernel.ClaimError as exc:
            lines.append(f"{claim_arg}  error: {exc}")
            exit_code = 1
            continue
        outputs = _generated_outputs(recipe)
        present = [o for o in outputs if os.path.isfile(os.path.join(d, o))]
        status = "materialized" if (not outputs or len(present) == len(outputs)) else "latent"
        root = manifest.get("root", "")
        name = manifest.get("name", claim_arg)
        lines.append(f"{name}  {root[:8]}  {ph}  {status}")
    sys.stdout.write("\n".join(lines) + "\n")
    return exit_code


# ---------------------------------------------------------------- main --

HELP = """usage: python3 -m reticuli.launcher <verb> [options]

verbs:
  run   <claim> [--accept-generated] [--signed-only] [--no-sandbox] [-- args...]
  strip <claim>
  ls    <claim>...

flags:
  --accept-generated   execute and accept freshly regrown generated bytes
  --signed-only        refuse a claim that is not signed to you
  --no-sandbox         run the entrypoint unconfined (reports quarantine = "off")
"""


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if not argv or argv[0] in ("-h", "--help"):
        sys.stdout.write(HELP)
        return 0
    verb, rest = argv[0], argv[1:]
    if verb == "run":
        return cmd_run(rest)
    if verb == "strip":
        return cmd_strip(rest)
    if verb == "ls":
        return cmd_ls(rest)
    sys.stderr.write(f"launcher: unknown verb {verb!r}\n")
    return 2


if __name__ == "__main__":
    sys.exit(main())
