"""heldout: measure a claim's strength by regrowing it blind (spec/verification.md).

`assess.py` measures how much a claim's own gates prove, from the inside,
with mutation testing. This module measures the same claim from the
outside: it hands an independent producer nothing but the pinned inputs
-- the generated bytes are held out of its view entirely, the same
posture `spec/verification.md` calls M3, "spec sufficiency" -- and
compares what that producer grows against the sealed original, gate by
gate. Two implementations that pass the same gates on the same pinned
data are the same claim (`spec/identity.md`); this module is where that
equivalence gets checked instead of assumed.

Stdlib only.
"""
import os
import shutil
import tempfile

from . import kernel


def measure(d: str, producer: str, *, into: str = None) -> dict:
    """Rebuild claim `d` blind with `producer`; report, per gate, whether
    the regrowth reproduces `d`'s own current verdict.

    `into`, if given, must not exist or must be empty (`kernel.rebuild`'s
    own rule); a caller-supplied room is left in place for inspection, a
    room this function created itself is cleaned up.
    """
    own_room = into is None
    room = into or tempfile.mkdtemp(prefix="heldout-")
    try:
        kernel.rebuild(d, producer, room)
        original = kernel.audit(d)
        blind = kernel.audit(room)

        orig_gates = {g["output"]: g["status"] for g in original["gates"]}
        blind_gates = {g["output"]: g["status"] for g in blind["gates"]}

        reproduced, diverged = [], []
        for output, status in orig_gates.items():
            other = blind_gates.get(output)
            if other == status:
                reproduced.append(output)
            else:
                diverged.append({"output": output, "original": status, "blind": other})

        return {
            "root_matches": original["root"] == blind["root"],
            "original_ok": original["ok"],
            "blind_ok": blind["ok"],
            "reproduced": reproduced,
            "diverged": diverged,
        }
    finally:
        if own_room:
            shutil.rmtree(room, ignore_errors=True)
