"""reticuli.launcher: run software that exists only latently in a claim
(spec/layers.md).

A runnable claim is an ordinary claim whose pinned inputs include
`package.toml` (`[package] entrypoint = "<file>"`). `run` checks a cached
build or regrows a fresh one with a producer (`RETICULI_PRODUCER`), then
executes the entrypoint with the claim root as cwd; `strip` deletes the
generated bytes back to latency; `ls` reports identity, phase, and whether
the bytes are on hand.

Freshly regrown bytes stay unaccepted -- refused with the consent flag
offered -- until a `run --accept-generated` records their digest; an edit to
an already-accepted implementation is drift, refused even if it would still
pass the gate. Launcher state (which digest was accepted, or is pending) is
residue under `<claim>/.launcher/`, and `strip` removes it along with the
generated bytes. An implementation the launcher never generated or accepted
carries no state at all and simply runs.

Only `reticuli.kernel`'s public surface and `reticuli._util`'s shared
helpers are used here -- no kernel private is reached from this layer.
Stdlib only.
"""
import json
import os
import shlex
import shutil
import subprocess
import sys
import tempfile

import tomllib

from . import _util, kernel

_STATE_DIR = ".launcher"
_STATE_FILE = "state.json"
_PACKAGE = "package.toml"

HELP = """\
usage: python3 -m reticuli.launcher <verb> [options]

verbs:
  run   <claim> [--accept-generated] [--signed-only] [--no-sandbox] [-- args...]
  strip <claim>
  ls    <claim>...

options:
  --accept-generated   accept freshly regrown bytes and execute them
  --signed-only        refuse a claim that is not signed to the caller
  --no-sandbox         execute the entrypoint without sandbox confinement
"""


def _eprint(msg: str) -> None:
    sys.stderr.write(msg.rstrip("\n") + "\n")


def _generated_outputs(parsed: dict) -> list:
    return [s["output"] for s in parsed.get("step", [])
            if s.get("kind") == "produce" and s.get("class") in ("generated", "free")]


def _package_entrypoint(d: str, parsed: dict) -> str:
    """The claim's declared entrypoint, confined to the claim root.

    Refuses (`kernel.ClaimError`) a claim with no `package.toml`, one whose
    `package.toml` is not a pinned input, or an entrypoint that escapes the
    claim root.
    """
    inputs = parsed.get("claim", {}).get("inputs", [])
    pkg_path = os.path.join(d, _PACKAGE)
    if _PACKAGE not in inputs:
        if os.path.isfile(pkg_path):
            raise kernel.ClaimError(
                f"{_PACKAGE} must be a pinned input (declared in [claim] "
                f"inputs) to be runnable, not a generated output")
        raise kernel.ClaimError(
            f"claim is not runnable: no {_PACKAGE} (a pinned input "
            f"declaring [package] entrypoint) is present")
    if not os.path.isfile(pkg_path):
        raise kernel.ClaimError(
            f"{_PACKAGE} is declared as a pinned input but is missing on disk")
    try:
        with open(pkg_path, "rb") as f:
            doc = tomllib.load(f)
    except tomllib.TOMLDecodeError as e:
        raise kernel.ClaimError(f"malformed {_PACKAGE}: {e}") from e
    package = doc.get("package")
    if not isinstance(package, dict):
        raise kernel.ClaimError(f"{_PACKAGE} must have a [package] table")
    entrypoint = package.get("entrypoint")
    if not isinstance(entrypoint, str) or not entrypoint:
        raise kernel.ClaimError(
            f"{_PACKAGE} [package] entrypoint must be a non-empty string")
    _util.safe_path(d, entrypoint)  # raises on an entrypoint escaping the claim root
    return entrypoint


# --- launcher state: which build was accepted, or is pending accept --------

def _state_path(d: str) -> str:
    return os.path.join(d, _STATE_DIR, _STATE_FILE)


def _read_state(d: str):
    path = _state_path(d)
    if not os.path.isfile(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return None


def _write_state(d: str, state: dict) -> None:
    path = _state_path(d)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(state, f)


def _clear_state(d: str) -> None:
    shutil.rmtree(os.path.join(d, _STATE_DIR), ignore_errors=True)


# --- regrowing latent bytes --------------------------------------------------

def _regrow(d: str, parsed: dict, producer: str) -> None:
    """Regrow every generated output into a scratch room, via the kernel's
    own `rebuild`, then land only the generated bytes onto `d` -- `d`'s
    pinned inputs, recipe, and verdicts are never touched."""
    into = tempfile.mkdtemp(prefix="reticuli-launcher-")
    try:
        kernel.rebuild(d, producer, into)
        for output in _generated_outputs(parsed):
            src = os.path.join(into, output)
            if not os.path.isfile(src):
                continue
            dst = _util.safe_path(d, output)
            os.makedirs(os.path.dirname(dst) or d, exist_ok=True)
            shutil.copy2(src, dst)
    finally:
        shutil.rmtree(into, ignore_errors=True)


# --- executing the entrypoint -------------------------------------------------

def _no_sandbox_env(scratch: str) -> dict:
    env = {k: os.environ[k] for k in ("PATH", "LANG", "LC_ALL", "TZ") if k in os.environ}
    env["HOME"] = scratch
    env["TMPDIR"] = scratch
    if os.environ.get("RETICULI_JAILED"):
        env["RETICULI_JAILED"] = os.environ["RETICULI_JAILED"]
    return env


def _run_no_sandbox(d: str, cmd: str) -> dict:
    scratch_root = os.path.join(d, _STATE_DIR)
    os.makedirs(scratch_root, exist_ok=True)
    scratch = tempfile.mkdtemp(prefix="run-", dir=scratch_root)
    try:
        proc = subprocess.run(["/bin/sh", "-c", cmd], cwd=d, env=_no_sandbox_env(scratch),
                              capture_output=True, text=True, check=False)
        return {"quarantine": "off", "returncode": proc.returncode,
                "stdout": proc.stdout, "stderr": proc.stderr}
    finally:
        shutil.rmtree(scratch, ignore_errors=True)


def _execute(d: str, parsed: dict, entrypoint: str, args: list, no_sandbox: bool) -> int:
    cmd = shlex.join([sys.executable, entrypoint] + list(args))
    if no_sandbox:
        result = _run_no_sandbox(d, cmd)
    else:
        gate = kernel.run_gate(cmd, d, parsed)
        result = {"quarantine": gate["quarantine"], "returncode": gate["returncode"],
                  "stdout": gate["stdout"], "stderr": gate["stderr"]}
    sys.stdout.write(result["stdout"])
    sys.stdout.flush()
    if result["stderr"]:
        sys.stderr.write(result["stderr"])
    _eprint(f'quarantine = "{result["quarantine"]}"')
    return result["returncode"]


# --- verbs -------------------------------------------------------------------

def _parse_run_args(args: list):
    accept_generated = signed_only = no_sandbox = False
    claim_arg = None
    passthrough = []
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--":
            passthrough = args[i + 1:]
            break
        if a == "--accept-generated":
            accept_generated = True
        elif a == "--signed-only":
            signed_only = True
        elif a == "--no-sandbox":
            no_sandbox = True
        elif claim_arg is None:
            claim_arg = a
        else:
            raise kernel.ClaimError(f"unexpected argument: {a!r}")
        i += 1
    if claim_arg is None:
        raise kernel.ClaimError("run requires a claim path")
    return claim_arg, accept_generated, signed_only, no_sandbox, passthrough


def cmd_run(args: list) -> int:
    try:
        claim_arg, accept_generated, signed_only, no_sandbox, passthrough = \
            _parse_run_args(args)
        d = os.path.abspath(claim_arg)
        parsed = kernel.load_recipe(d)
        entrypoint = _package_entrypoint(d, parsed)
        phase = kernel.phase(d)
    except kernel.ClaimError as e:
        _eprint(f"not runnable: {e}")
        return 3

    if signed_only and phase != "signed":
        _eprint(f"--signed-only refuses claim at {d!r}: not signed (phase={phase})")
        return 5

    generated = _generated_outputs(parsed)
    missing = [o for o in generated if not os.path.isfile(os.path.join(d, o))]

    if missing:
        producer = os.environ.get("RETICULI_PRODUCER")
        if not producer:
            _eprint(f"claim at {d!r} is latent and no producer is configured: "
                    f"set RETICULI_PRODUCER to regrow it")
            return 7
        try:
            _regrow(d, parsed, producer)
        except kernel.ClaimError as e:
            _eprint(f"regrow failed: {e}")
            return 3
        digest = kernel.build_digest(d)
        if accept_generated:
            _write_state(d, {"status": "accepted", "digest": digest})
        else:
            _write_state(d, {"status": "fresh", "digest": digest})
            _eprint("newly generated bytes materialized but not executed; "
                    "pass --accept-generated to execute and accept them")
            return 4
    else:
        state = _read_state(d)
        if state is not None:
            digest = kernel.build_digest(d)
            if state.get("status") == "accepted":
                if state.get("digest") != digest:
                    _eprint(f"drifted build: the accepted implementation at {d!r} "
                            f"no longer matches the bytes accepted for it; run "
                            f"`strip` to recover")
                    return 6
            else:
                if accept_generated:
                    _write_state(d, {"status": "accepted", "digest": digest})
                else:
                    _write_state(d, {"status": "fresh", "digest": digest})
                    _eprint("newly generated bytes materialized but not executed; "
                            "pass --accept-generated to execute and accept them")
                    return 4
        # state is None: an implementation the launcher never generated or
        # accepted runs on audit alone.

    _eprint(f"claim {parsed['claim']['name']!r} is {phase}")
    return _execute(d, parsed, entrypoint, passthrough, no_sandbox)


def cmd_strip(args: list) -> int:
    if len(args) != 1:
        _eprint("strip requires exactly one claim path")
        return 3
    d = os.path.abspath(args[0])
    try:
        parsed = kernel.load_recipe(d)
        for output in _generated_outputs(parsed):
            path = _util.safe_path(d, output)
            if os.path.lexists(path):
                os.remove(path)
    except kernel.ClaimError as e:
        _eprint(f"not runnable: {e}")
        return 3
    _clear_state(d)
    return 0


def _ls_one(d: str) -> None:
    try:
        parsed = kernel.load_recipe(d)
    except kernel.ClaimError as e:
        print(f"{d}  error: {e}")
        return
    name = parsed["claim"]["name"]
    try:
        root = kernel.read_manifest(d).get("root", "")
    except kernel.ClaimError:
        root = ""
    try:
        phase = kernel.phase(d)
    except kernel.ClaimError:
        phase = "draft"
    generated = _generated_outputs(parsed)
    present = all(os.path.isfile(os.path.join(d, o)) for o in generated)
    state = "materialized" if present else "latent"
    print(f"{name}  {root[:8]}  {phase}  {state}  {d}")


def cmd_ls(args: list) -> int:
    if not args:
        _eprint("ls requires at least one claim path")
        return 3
    for claim_arg in args:
        _ls_one(os.path.abspath(claim_arg))
    return 0


def main(argv: list) -> int:
    try:
        if not argv or argv[0] in ("-h", "--help"):
            print(HELP)
            return 0
        verb, rest = argv[0], argv[1:]
        if verb == "run":
            return cmd_run(rest)
        if verb == "strip":
            return cmd_strip(rest)
        if verb == "ls":
            return cmd_ls(rest)
        _eprint(f"unknown verb: {verb!r}")
        return 3
    except Exception as e:  # a refusal with a reason, never a raw crash
        _eprint(f"internal error: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
