"""pack: a project as a self-claim (spec/layers.md).

The implementation is generated; the check is the claim. `pack` writes a
recipe declaring `generated` (glob patterns over the implementation,
outside the root) and `inputs` (the acceptance check, pinned), runs `gate`
through `kernel.run_gate` -- scrubbed, sandboxed, bounded, never
`kernel.sandbox` directly -- to earn `gate_output`, and seals. A gate whose
every decider is itself generated is refused as vacuous
(`kernel.vacuous_gates`): the README flow where an agent writes both the
solver and its own test must not seal a vacuous check at the same root as a
real one.

`component=` layers one claim on another: a named output travels `from` a
component rather than being produced locally, the component's own criteria
(recipe, inputs, pinned outputs -- never its generated bytes) are copied
into this claim's own store, and the manifest records the link.

Stdlib only.
"""
import glob as _glob
import os

from . import kernel, registry, render

_WILDCARD = frozenset({"*", "?", "["})


def _has_wildcard(pattern: str) -> bool:
    return any(ch in pattern for ch in _WILDCARD)


def _expand(root: str, patterns: list) -> list:
    """Every pattern in `patterns` resolved to files under `root`: glob
    expansion for a wildcarded pattern, and a required literal match
    otherwise -- a typo in a bare filename refuses rather than silently
    packing nothing."""
    out = []
    for pattern in patterns:
        full = os.path.join(root, pattern)
        if _has_wildcard(pattern):
            matches = _glob.glob(full)
        else:
            matches = [full] if os.path.isfile(full) else []
            if not matches:
                raise kernel.ClaimError(f"no such file: {pattern!r}")
        for m in matches:
            if os.path.isfile(m):
                out.append(os.path.relpath(m, root).replace(os.sep, "/"))
    return sorted(set(out))


def pack(root: str, name: str, generated: list, inputs: list, gate: str,
          gate_output: str, *, envelope: dict = None, claim_format: int = None,
          component: dict = None) -> dict:
    """Seal `root` as a self-claim: `generated` (glob patterns, outside the
    root) is the implementation, `inputs` (glob patterns, pinned) is the
    check, `gate` is run to earn `gate_output`.

    `envelope` and `claim_format` are declared verbatim into `[claim]`.
    `component`, if given (`{"name", "claim", "outputs"}`), layers `root`
    on a sealed claim at `component["claim"]`: every path in
    `component["outputs"]` is declared `from` that component instead of
    produced locally, and the component's own criteria travel into
    `root`'s own store.
    """
    generated_paths = _expand(root, generated)
    input_paths = _expand(root, inputs)

    claim_table = {"name": name, "inputs": input_paths}
    if envelope is not None:
        claim_table["envelope"] = envelope
    if claim_format is not None:
        claim_table["format"] = claim_format

    comp_name = component["name"] if component else None
    from_outputs = set(component.get("outputs", [])) if component else set()

    steps = []
    for p in sorted(set(generated_paths) | from_outputs):
        step = {"kind": "produce", "output": p, "class": "generated"}
        if p in from_outputs:
            step["from"] = comp_name
        steps.append(step)
    steps.append({"kind": "gate", "output": gate_output, "run": gate, "class": "validated"})

    parsed = {"claim": claim_table, "step": steps}

    vacuous = kernel.vacuous_gates(parsed)
    if vacuous:
        raise kernel.ClaimError(
            f"gate(s) {vacuous} are vacuous: every decider is a generated output")

    with open(os.path.join(root, kernel.RECIPE), "w", encoding="utf-8") as f:
        f.write(render.toml(parsed))

    result = kernel.run_gate(gate, root, parsed)
    if result["status"] != "ok":
        raise kernel.ClaimError(f"gate {gate_output!r} did not pass: {result['status']}")

    if component is not None:
        dest = os.path.join(root, kernel.STORE, "sealed", comp_name)
        registry._copy_claim_criteria(component["claim"], dest)
        kernel.seal(dest)
        manifest = registry.seal_with(root, components={comp_name: os.path.relpath(dest, root)})
    else:
        manifest = kernel.seal(root)

    return {"ok": True, **manifest}
