"""record: authoring the one document other programs may parse (spec/record.md).

The kernel owns the record FORMAT -- it consumes records as crosscheck legs
(`kernel.record_validate`, `record_canonical`, `record_digest`, `record_read`,
`record_signer`), which this module simply carries forward. What only this,
the exchange layer, does is EARN one: `emit` re-runs a claim's gates fresh
and states what it found, in the record's own signed namespace
(`reticuli.record`), distinct from an attestation's or a ceremony's.

Stdlib only, plus the system `ssh-keygen` for signing.
"""
import json
import os
import platform
import subprocess
import sys

from . import _util, kernel

validate = kernel.record_validate
canonical = kernel.record_canonical
digest = kernel.record_digest
read = kernel.record_read


def _environment() -> dict:
    return {"platform": sys.platform, "machine": platform.machine(),
            "runtime": f"CPython {platform.python_version()}"}


def _obligations(claim: dict) -> dict:
    return {k: claim[k] for k in ("tolerance", "envelope", "mutation_floor") if k in claim}


def _ledger_events(d: str) -> list:
    path = os.path.join(d, kernel.LEDGER)
    if not os.path.isfile(path):
        return []
    events = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                events.append(json.loads(line))
    return events


def _declared_producer(d: str):
    found = False
    vendor = model = blind = cutoff = None
    for event in _ledger_events(d):
        if any(k in event for k in ("vendor", "model", "blind", "cutoff")):
            found = True
            vendor = event.get("vendor", vendor)
            model = event.get("model", model)
            blind = event.get("blind", blind)
            cutoff = event.get("cutoff", cutoff)
    if not found:
        return None
    out = {}
    if vendor is not None:
        out["vendor"] = vendor
    if model is not None:
        out["model"] = model
    if blind is not None:
        out["blind"] = blind
    if cutoff is not None:
        out["cutoff"] = cutoff
    return out or None


def emit(d: str) -> dict:
    """State what this machine establishes about claim `d` right now: its
    identity, the generated bytes present, and every gate re-run fresh.

    Refuses (never a raw crash) unless the claim's identity currently holds
    -- a record is ABOUT a root, and there is nothing to be about if the
    bytes do not hash to one. A failing gate still emits: a failed rebuild
    is evidence.
    """
    v = kernel.verify(d)
    if not v["ok"]:
        raise kernel.ClaimError(
            f"cannot emit a record for {d!r}: sealed root {v['root']} != "
            f"recomputed {v['recomputed']}")
    parsed = kernel.load_recipe(d)

    gates = []
    for step in parsed.get("step", []):
        if step["kind"] != "gate":
            continue
        result = kernel.run_gate(step["run"], d, parsed)
        gates.append({"output": step["output"], "status": result["status"],
                      "sandbox": result["quarantine"]})

    doc = {
        "record": 2,
        "name": parsed["claim"]["name"],
        "root": v["root"],
        "build_digest": kernel.build_digest(d),
        "claim": _obligations(parsed["claim"]),
        "gates": gates,
        "environment": _environment(),
        "when": _util.stamp(),
    }
    cost = kernel.cost(d)
    if cost:
        doc["cost"] = cost
    producer = _declared_producer(d)
    if producer:
        doc["producer"] = producer
    return doc


def write(doc: dict, path: str) -> None:
    """Write a record's canonical bytes to `path` -- no prettying, no
    trailing newline: the file on disk IS the canonical bytes."""
    with open(path, "wb") as f:
        f.write(canonical(doc))


def sign(path: str, keypath: str) -> None:
    """Sign a record file's canonical bytes with the existing ssh mechanism,
    in the record's own namespace (`reticuli.record`) -- distinct from an
    attestation's or an authorization ceremony's, so a signature made for
    one purpose is never presentable for another."""
    sig_path = path + ".sig"
    if os.path.isfile(sig_path):
        os.remove(sig_path)  # ssh-keygen prompts before overwriting one
    subprocess.run(["ssh-keygen", "-Y", "sign", "-f", keypath, "-n",
                    kernel.RECORD_NAMESPACE, path], check=True, capture_output=True)


def signer(path: str, anchor: str):
    """The principal in `anchor` whose key verifies the record at `path` --
    `None`, never a raise, when nothing verifies (a mint signature over the
    same bytes, a tampered file, a missing signer)."""
    try:
        return kernel.record_signer(path, anchor)
    except kernel.ClaimError:
        return None
