"""reuse: cache a verdict, keyed by identity + build + host (spec/verification.md).

A crosscheck's verdict is expensive to earn -- it can mean running every
gate, cold and sandboxed, plus mutation testing -- and cheap to key: which
claim (`root`), which concrete bytes (`build_digest`), and which host and
interpreter ran the gates. The same root, the same build digest, and the
same platform/interpreter pair will always re-earn the same verdict a gate
already earned, so remembering it is safe reuse, not a shortcut past
verification.

A *failing* verdict is never remembered. A failure can be a fluke of this
one run (a flaky gate, a host hiccup); freezing it into the cache would let
one bad run veto every later, honest redo. A passing verdict has no such
failure mode -- the gates ran clean on these exact bytes on this exact
host -- so only passing verdicts are cached.

Stdlib only.
"""
import hashlib
import json
import os
import platform
import sys

from . import kernel

RESIDUE = os.path.join(kernel.STORE, "reuse.json")


def fingerprint(d: str) -> dict:
    """The cache key's components for claim `d`: its identity (`root`), the
    generated bytes present (`build`), and the host that would run the
    gates (`platform`, `python`) -- the same quadruple that decides whether
    a verdict earned once still applies now."""
    manifest = kernel.read_manifest(d)
    return {
        "root": manifest["root"],
        "build": kernel.build_digest(d),
        "platform": sys.platform,
        "python": platform.python_version(),
    }


def _key(fp: dict) -> str:
    return hashlib.sha256(json.dumps(fp, sort_keys=True).encode("utf-8")).hexdigest()


def _residue_path(d: str) -> str:
    return os.path.join(d, RESIDUE)


def _load(d: str) -> dict:
    path = _residue_path(d)
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            cache = json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}
    return cache if isinstance(cache, dict) else {}


def remember(d: str, verdict: dict) -> None:
    """Cache `verdict` under `d`'s current fingerprint, unless it is a
    failure (`verdict["ok"]` is not truthy) -- a failing verdict is never
    remembered, so a fluke never freezes a later, honest redo out."""
    if not verdict.get("ok"):
        return
    path = _residue_path(d)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    cache = _load(d)
    cache[_key(fingerprint(d))] = verdict
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(cache, f, sort_keys=True)
    os.replace(tmp, path)


def lookup(d: str):
    """The verdict remembered for `d`'s current root+build+host, or `None`
    if nothing was ever remembered for this exact fingerprint."""
    return _load(d).get(_key(fingerprint(d)))
