"""transfer: deterministic export and verify-on-import (spec/layers.md).

A claim's DECLARED content only -- its recipe, its pinned inputs, its
present outputs, and (if it has any) its own exchange-layer residue
(attestations, authorization ceremonies) -- ever travels; the tar is built
by walking the recipe, never the directory, so a stray file dropped beside
a claim cannot ride along. Volatile local history (the ledger) never
travels. A declared component's own claim -- recipe, inputs, pins -- travels
too, nested under a canonical `.reticuli/deps/<name>/`, but never its
generated bytes: "GATES COMPOSE, VERDICTS NEVER CARRY" applies to transfer
as much as to a rebuild. Import extracts, then calls `kernel.verify` to
recompute identity from the received bytes -- trust is never assumed, only
confirmed.

Stdlib only.
"""
import io
import json
import os
import tarfile

from . import _util, kernel

_DEPS_PREFIX = ".reticuli/deps"
_RESIDUE_DIRS = ("attest", "mint")


def _own_members(d: str, blind: bool) -> dict:
    """`{archive_path: bytes}` for `d`'s OWN declared content: its recipe,
    its pinned inputs, and its present step outputs -- generated ones
    included unless `blind`."""
    parsed = kernel.load_recipe(d)
    claim = parsed.get("claim", {})
    out = {}

    rname = _util.recipe_name(d)
    out[rname] = _read(os.path.join(d, rname))

    for inp in claim.get("inputs", []):
        out[inp] = _read(os.path.join(d, inp))
    env_file = claim.get("environment")
    if env_file and env_file not in out:
        out[env_file] = _read(os.path.join(d, env_file))

    for step in parsed.get("step", []):
        generated = step["class"] in ("generated", "free")
        if generated and blind:
            continue
        path = os.path.join(d, _util.step_output(step))
        if os.path.isfile(path):
            out[step["output"]] = _read(path)
    return out


def _residue_members(d: str) -> dict:
    """Exchange-layer residue that travels WITH a claim: attestations and
    authorization ceremonies, never the ledger (volatile local history)."""
    out = {}
    for sub in _RESIDUE_DIRS:
        base = os.path.join(d, _util.STORE, sub)
        if not os.path.isdir(base):
            continue
        for root, dirs, files in os.walk(base):
            dirs.sort()
            for fname in sorted(files):
                full = os.path.join(root, fname)
                out[os.path.relpath(full, d)] = _read(full)
    return out


def _read(path: str) -> bytes:
    with open(path, "rb") as f:
        return f.read()


def _collect(d: str, blind: bool) -> dict:
    """Every archive member for `d`, recursively including its declared
    components -- each nested under `.reticuli/deps/<name>/...`, always
    stripped of its own generated bytes regardless of `blind`."""
    archive = {}
    archive.update(_own_members(d, blind))
    archive.update(_residue_members(d))

    try:
        manifest = kernel.read_manifest(d)
    except kernel.ClaimError:
        manifest = None

    if manifest is not None:
        rewritten = dict(manifest)
        components = manifest.get("components") or {}
        if components:
            rewritten["components"] = {name: f"{_DEPS_PREFIX}/{name}" for name in components}
        archive[kernel.MANIFEST] = json.dumps(rewritten, sort_keys=True).encode("utf-8")
        for name, rel in components.items():
            comp_dir = os.path.join(d, rel)
            comp_archive = _collect(comp_dir, blind=True)
            prefix = f"{_DEPS_PREFIX}/{name}/"
            for sub_path, data in comp_archive.items():
                archive[f"{prefix}{sub_path}"] = data
    return archive


def export(d: str, tar_path: str, blind: bool = False) -> dict:
    """Write a deterministic tar of `d`'s declared content to `tar_path`.

    `blind=True` withholds every generated output of `d` itself -- the same
    claim minus its implementation, so the identity still verifies on
    import and a rebuilder's room is exactly what a producer is asked to
    regrow. Two exports of the same content are byte-identical: members are
    sorted, and every `TarInfo` is normalized (fixed mtime, mode, owner).
    """
    archive = _collect(d, blind)
    with tarfile.open(tar_path, "w") as tar:
        for name in sorted(archive):
            data = archive[name]
            info = tarfile.TarInfo(name=name)
            info.size = len(data)
            info.mtime = 0
            info.mode = 0o644
            info.uid = 0
            info.gid = 0
            info.uname = ""
            info.gname = ""
            info.type = tarfile.REGTYPE
            tar.addfile(info, io.BytesIO(data))
    return {"path": tar_path, "members": sorted(archive)}


def import_(tar_path: str, into: str) -> dict:
    """Extract `tar_path` into fresh directory `into`, then recompute
    identity from the received bytes -- verify-on-import, never a trusted
    copy."""
    os.makedirs(into, exist_ok=True)
    with tarfile.open(tar_path, "r") as tar:
        for member in tar.getmembers():
            if not member.isfile():
                raise kernel.ClaimError(f"refusing non-file tar member: {member.name!r}")
            _util.safe_path(into, member.name)
            dest = os.path.join(into, member.name)
            os.makedirs(os.path.dirname(dest) or into, exist_ok=True)
            with open(dest, "wb") as f:
                f.write(tar.extractfile(member).read())
    _util.backfill_components(into)
    return kernel.verify(into)
