"""Local cache for successful claim verdicts.

The cache is residue: it never participates in claim identity.  A different
realization or judging host gets a different fingerprint.
"""

from __future__ import annotations

import json
import os
import platform
import sys
import tempfile

from . import kernel


_CACHE = "reuse.json"


def fingerprint(directory: str) -> dict[str, str]:
    """Identify the claim, its present generated bytes, and this interpreter."""
    verification = kernel.verify(directory)
    if not verification["ok"]:
        raise kernel.ClaimError("claim identity changed")
    return {
        "root": verification["root"],
        "build": kernel.build_digest(directory),
        "platform": platform.platform(),
        "python": sys.version,
    }


def _path(directory: str) -> str:
    return os.path.join(directory, kernel.STORE, _CACHE)


def lookup(directory: str) -> dict | None:
    """Return a cached passing verdict only for the current fingerprint."""
    key = fingerprint(directory)
    try:
        with open(_path(directory), encoding="utf-8") as source:
            entry = json.load(source)
    except (FileNotFoundError, OSError, ValueError):
        return None
    if (isinstance(entry, dict) and entry.get("fingerprint") == key
            and isinstance(entry.get("verdict"), dict)
            and entry["verdict"].get("ok") is True):
        return entry["verdict"]
    return None


def remember(directory: str, verdict: dict) -> bool:
    """Store a passing verdict atomically; failures are never cached."""
    if not isinstance(verdict, dict) or verdict.get("ok") is not True:
        return False
    entry = {"fingerprint": fingerprint(directory), "verdict": verdict}
    folder = os.path.join(directory, kernel.STORE)
    os.makedirs(folder, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=".reuse-", dir=folder)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as target:
            json.dump(entry, target, sort_keys=True)
            target.write("\n")
        os.replace(temporary, _path(directory))
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)
    return True
