"""Exchange conformance gate — the acceptance check of the `exchange` layer.

Claims meeting claims — and other parties: the registry (claim stores,
content-addressed component links, DAG-aware rebuild), transfer (deterministic
tar, verify-on-import, volatile history stays home), attestation (a
keyholder's signed statement of a build: signs only claims whose verdicts
reproduce from their own bytes — never a carried verdict — refuses tampered
statements, anchors identity to allowed signers), and records (spec/record.md:
the one document other programs may parse — emitted by re-earning the gates,
canonical in its bytes, closed in its vocabulary, signed in a namespace of its
own). Layers on the kernel; knows nothing of authoring or the CLI. Writes
EXCHANGE_OK iff the layer conforms. Stdlib only, so it runs in any clean
workspace.

    python3 checks/exchange_check.py       (from the repository root)
"""
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile

# the package ships from src/; inside a sealed claim's workspace it sits at the
# root beside this check
sys.path.insert(0, "src" if os.path.isdir("src/reticuli") else ".")
from reticuli import attest, kernel, record, registry, transfer

LIB = '''[claim]
name = "lib"

[[step]]
kind = "gate"
output = "lib.txt"
run = "printf LIBDATA > lib.txt"
class = "validated"
'''

APP = '''[claim]
name = "app"
inputs = ["dep.txt"]

[[step]]
kind = "produce"
output = "app.txt"
request = "any note"
class = "generated"

[[step]]
kind = "gate"
output = "V"
run = "grep -qi implementation app.txt && grep -q LIBDATA dep.txt && printf ok > V"
class = "validated"
'''


LIBCODE = '''[claim]
name = "libcode"
inputs = ["lib_check.py"]

[[step]]
kind = "produce"
output = "lib.py"
request = "val() returns 42"
class = "generated"

[[step]]
kind = "gate"
output = "LIB_OK"
run = "python3 lib_check.py"
class = "validated"
'''

APPCODE = '''[claim]
name = "appcode"
inputs = ["app_check.py"]

[[step]]
kind = "produce"
output = "lib.py"
class = "generated"
from = "libcode"
request = "supplied by the libcode component"

[[step]]
kind = "produce"
output = "app.py"
request = "answer() returns val()"
class = "generated"

[[step]]
kind = "gate"
output = "APP_OK"
run = "python3 app_check.py"
class = "validated"
'''

# the kernel hands a producer the ABSOLUTE path of the output it wants next
# ($RETICULI_OUTPUT), so a dispatching producer matches on the tail
CODE_PRODUCER = (
    'case "$RETICULI_OUTPUT" in '
    '*/lib.py|lib.py) printf "def val(): return 42\\n" > lib.py ;; '
    '*/app.py|app.py) printf "from lib import val\\ndef answer(): return val()\\n" > app.py ;; '
    'esac'
)
# A producer that can ONLY write app.py -- it has no rule for lib.py. It can
# still rebuild the composed claim IFF lib.py is reused from the sealed
# component and never asked of the producer (the incremental-build path).
APP_ONLY_PRODUCER = (
    'case "$RETICULI_OUTPUT" in '
    '*/app.py|app.py) printf "from lib import val\\ndef answer(): return val()\\n" > app.py ;; '
    'esac'
)


# A minimal claim for the record battery: one pinned check, one generated
# file, one gate. Different generated bytes carry one root, so a record can
# state an identity while the implementation beneath it stays free.
PROBE = '''[claim]
name = "probe"
inputs = ["check_x.py"]

[[step]]
kind = "produce"
output = "x.py"
class = "generated"

[[step]]
kind = "gate"
output = "OK"
class = "validated"
run = "python3 check_x.py"
'''

PROBE_CHECK = '''text = open("x.py", encoding="utf-8").read()
assert int(text.split("#")[0].strip()) > 0
with open("OK", "w", encoding="utf-8") as f:
    f.write("ok\\n")
'''


def _write(d: str, files: dict) -> None:
    os.makedirs(d, exist_ok=True)
    for name, content in files.items():
        with open(os.path.join(d, name), "w") as f:
            f.write(content)


def _digest(path: str) -> str:
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()




# ==== seam block for exchange_check.py ====
# Paste into the check; call _seam() from its battery()/main.

# --- _util.py: 7 seam names (0 value, 0 kind, 7 callable) ---
# _util's FULL public surface, not just the names current importers reach
# directly: STORE/LEDGER/RECIPE and trace_append/ledger_add/stamp/locked_append
# are exposed here too, but current code reaches them via the kernel facade, so
# the import-graph seam missed them -- and an independently regrown consumer that
# imports them straight from _util then breaks (the 2026-09-22 assembled rebuild
# hit exactly this). Pin the whole public surface so the provider is complete.
_SEAM__util_VALUES = {
    'STORE': '.reticuli',
    'LEDGER': '.reticuli/ledger.jsonl',
    'RECIPE': 'claim.toml',
}
_SEAM__util_KINDS = {}
_SEAM__util_CALLABLES = ('copy_into', 'declared_inputs', 'hash_bytes', 'ledger_add', 'locked_append', 'read_json', 'safe_path', 'stamp', 'step_output', 'trace_append', 'write_json')

# --- attest.py: 1 seam names (1 value, 0 kind, 0 callable) ---
_SEAM_attest_VALUES = {
    'ATTEST': '.reticuli/attest',
}
_SEAM_attest_KINDS = {}
_SEAM_attest_CALLABLES = ()

def _seam() -> None:
    from reticuli import _util as _m__util
    for _n, _v in _SEAM__util_VALUES.items():
        assert getattr(_m__util, _n) == _v, f'_util.py seam {_n} changed'
    for _n in _SEAM__util_KINDS:
        assert hasattr(_m__util, _n), f'_util.py must export {_n}'
    for _n in _SEAM__util_CALLABLES:
        assert callable(getattr(_m__util, _n, None)), f'_util.py must export callable {_n}'
    from reticuli import attest as _m_attest
    for _n, _v in _SEAM_attest_VALUES.items():
        assert getattr(_m_attest, _n) == _v, f'attest.py seam {_n} changed'
    for _n in _SEAM_attest_KINDS:
        assert hasattr(_m_attest, _n), f'attest.py must export {_n}'
    for _n in _SEAM_attest_CALLABLES:
        assert callable(getattr(_m_attest, _n, None)), f'attest.py must export callable {_n}'


def battery() -> None:
    _seam()
    d = tempfile.mkdtemp()
    try:
        ws = os.path.join(d, "ws")
        lib = os.path.join(ws, ".reticuli", "sealed", "lib")
        _write(lib, {"claim.toml": LIB, "lib.txt": "LIBDATA"})
        kernel.seal(lib)

        # a pinned input that content-matches a claim's output is a dependency
        _write(ws, {"dep.txt": "LIBDATA"})
        links = registry.detect_components(ws, ["dep.txt"])
        assert any(x["component"] == "lib" for x in links), "content-addressed link"

        app = os.path.join(ws, ".reticuli", "sealed", "app")
        _write(app, {"claim.toml": APP, "dep.txt": "LIBDATA",
                     "app.txt": "one implementation\n", "V": "ok"})
        registry.seal_with(app, components=links)
        names = {r["name"] for r in registry.claims(ws)}
        assert names == {"app", "lib"}, "the claim store"
        edges = registry.deps(ws)["claims"]
        assert any(e["status"] == "ok" for n in edges for e in n["depends_on"]), "the DAG"

        # DAG-aware rebuild: the chain reproduces from the leaves
        m3 = os.path.join(d, "m3")
        out = registry.rebuild_chain(app, "printf 'another implementation' > app.txt", m3, ws=ws)
        assert out["root"] == kernel.verify(app)["root"], "chain reproduces"
        assert any(c["component"] == "lib" for c in out["rebuilt_components"]), "leaf first"
        # a rebuilt claim must keep its provenance: the manifest carries the
        # component links it was rebuilt from (else its component tree is blind)
        assert kernel.read_manifest(m3).get("components"), "rebuild preserves provenance"

        # pull: a claim becomes a dependency of a fresh workspace
        ws2 = os.path.join(d, "ws2")
        os.makedirs(ws2)
        pulled = registry.pull(app, ws2)
        assert pulled["materialized"] and os.path.isfile(os.path.join(ws2, "V")), "pull"

        # transfer: deterministic tar, verify-on-import, ledger stays home
        tar_path = os.path.join(d, "m3.tar")
        transfer.export(m3, tar_path)
        with tarfile.open(tar_path) as t:
            assert ".reticuli/ledger.jsonl" not in t.getnames(), "events don't travel"
        back = transfer.import_(tar_path, os.path.join(d, "back"))
        assert back["ok"] and back["root"] == out["root"], "identity travels"

        # declared content ONLY: a stray file dropped in the claim's directory
        # must not ride along, and two exports of one claim are byte-identical.
        # (An export that walks the tree instead of the recipe leaks the workspace.)
        with open(os.path.join(m3, "stray-residue.txt"), "w") as f:
            f.write("laptop junk that is not part of the claim\n")
        leak_tar = os.path.join(d, "leak.tar")
        transfer.export(m3, leak_tar)
        with tarfile.open(leak_tar) as t:
            assert "stray-residue.txt" not in t.getnames(), "undeclared bytes must not travel"
        det_tar = os.path.join(d, "det.tar")
        transfer.export(m3, det_tar)
        assert _digest(leak_tar) == _digest(det_tar), "export is byte-deterministic"
        os.remove(os.path.join(m3, "stray-residue.txt"))

        # a BLIND export is the rebuilder's room: the same claim minus its
        # generated outputs. The identity travels whole -- the root never
        # covered the implementation -- so the room verifies on import, and
        # what the tar withholds is exactly what a producer is asked to regrow.
        blind_tar = os.path.join(d, "blind.tar")
        transfer.export(m3, blind_tar, blind=True)
        with tarfile.open(blind_tar) as t:
            blind_names = set(t.getnames())
        assert "app.txt" not in blind_names, "generated bytes stay home"
        assert "claim.toml" in blind_names and "dep.txt" in blind_names \
            and "V" in blind_names, "criteria, inputs, and the verdict travel"
        blind_room = transfer.import_(blind_tar, os.path.join(d, "blind-room"))
        assert blind_room["ok"] and blind_room["root"] == out["root"], \
            "the room carries the identity the rebuild must land on"

        # attestation: a signed statement of this build, for other parties
        key = os.path.join(d, "key")
        subprocess.run(["ssh-keygen", "-t", "ed25519", "-N", "", "-q", "-f", key], check=True)
        a = attest.attest(m3, key, "checker@basin")
        assert os.path.isfile(os.path.join(m3, a["signature"])), "signed"
        assert attest.check(m3)["ok"], "intact and naming this root"
        # an attestation is residue ABOUT the claim that travels WITH it
        att_tar = os.path.join(d, "attested.tar")
        transfer.export(m3, att_tar)
        with tarfile.open(att_tar) as t:
            assert any(n.startswith(".reticuli/attest/") for n in t.getnames()), \
                "attestations travel with the claim"
        signers = os.path.join(d, "allowed_signers")
        with open(key + ".pub") as f:
            keytype, blob = f.read().split()[:2]
        with open(signers, "w") as f:
            f.write(f"checker@basin {keytype} {blob}\n")
        checked = attest.check(m3, signers)
        assert checked["ok"] and checked["attestations"][0]["verdict"] == "signed", "identity anchored"
        # an attestation speaks for a BUILD, not just a claim: regenerating after
        # signing keeps the root (that freedom is the equivalence class) but is a
        # different build — the signed output hashes no longer match the disk,
        # and the old attestation must refuse. Restore the exact bytes and it
        # holds again.
        with open(os.path.join(m3, "app.txt")) as f:
            app_bytes = f.read()
        with open(os.path.join(m3, "app.txt"), "w") as f:
            f.write("a drifted implementation\n")
        drifted = attest.check(m3)
        assert not drifted["ok"] and drifted["attestations"][0]["drifted"], \
            "a drifted build refuses the old attestation"
        with open(os.path.join(m3, "app.txt"), "w") as f:
            f.write(app_bytes)
        assert attest.check(m3)["ok"], "the frozen bytes restored, the attestation holds"
        st_path = os.path.join(m3, a["statement"])
        with open(st_path, "a") as f:
            f.write("\n")                                        # tamper the statement
        assert not attest.check(m3, signers)["ok"], "a tampered statement refuses"
        imported = os.path.join(d, "back")
        with open(os.path.join(imported, "app.txt"), "w") as f:
            f.write("no longer satisfies the gate\n")            # generated: root still fresh
        assert kernel.verify(imported)["ok"], "identity survives a generated tamper"
        try:
            attest.attest(imported, key, "checker@basin")
            raise AssertionError("attest must never notarize a carried verdict")
        except kernel.ClaimError:
            pass
        with open(os.path.join(imported, "V"), "w") as f:
            f.write("tampered")                                  # and a broken pin refuses too
        try:
            attest.attest(imported, key, "checker@basin")
            raise AssertionError("attest must refuse a broken claim")
        except kernel.ClaimError:
            pass

        # the signature chain: signed identity folds bottom-up over the DAG, and
        # localizes — a change at one layer moves its node and every node above,
        # never one below (the lowest node that moves names the floor).
        lib_s = registry.sign_root(lib, ws)
        app_s = registry.sign_root(app, ws)
        assert app_s == kernel.sign_node(kernel.verify(app)["root"],
                                         kernel.build_digest(app), [lib_s]), \
            "app's node folds lib's node (bottom-up)"
        with open(os.path.join(app, "app.txt"), "w") as f:
            f.write("one implementation, differently\n")          # regenerate app
        assert registry.sign_root(app, ws) != app_s, "editing a layer's bytes moves its node"
        assert registry.sign_root(lib, ws) == lib_s, "the floor's node held (localization)"
        # a chain root over an incomplete DAG is not a chain root: a declared
        # component missing from the registry must refuse the fold, not elide.
        lib_aside = os.path.join(d, "lib-aside")
        shutil.move(lib, lib_aside)
        try:
            registry.sign_root(app, ws)
            raise AssertionError("sign_root must refuse a missing declared component")
        except kernel.ClaimError:
            pass
        shutil.move(lib_aside, lib)
        assert registry.sign_root(lib, ws) == lib_s, "restored, the fold holds again"

        # the signing ceremony: accountable authorization over the chain. Refuses
        # a claim whose verdicts do not reproduce (audit), signs the chain root
        # and the review packet, and verifies against a recomputed chain. SIGNED
        # means AUTHORIZED (by a trusted signer) AND PROVEN (a recorded proof) —
        # the two facts are coupled, and both are verifier-relative through the
        # anchor.
        mm = os.path.join(d, "mm")                                 # a fresh, clean build
        registry.rebuild_chain(app, "printf 'yet another implementation' > app.txt", mm, ws=ws)
        pkt = attest.review_packet(mm, ws=ws)
        assert pkt["sign_root"] and pkt["root"] and pkt["audit"]["ok"], "the review packet is assembled"
        assert "proof" in pkt, "the packet carries proof status — the reviewer sees the ladder"
        signed = attest.sign(mm, key, "checker@basin", ws=ws)
        assert signed["ceremony"] == "RETICULI_CLAIM_BASIN_V1", "the ceremony is named"
        assert os.path.isfile(os.path.join(mm, signed["signature"])), "the statement is signed"
        checked = attest.sign_check(mm, ws=ws, signers=signers)
        assert checked["authorizations"][0]["verdict"] == "authorized", "authorizer identity anchored"
        row = checked["authorizations"][0]
        assert row["packet_holds"], "the signed digest binds the stored review packet"
        assert row["proof_recorded"] is False, \
            "the statement says whether a proof was recorded (none here) — " \
            "authorization is never mistaken for proof"
        os.environ["RETICULI_SIGNERS"] = signers                   # anchor: trust checker@basin
        try:
            assert kernel.phase(mm) == "sealed", "authorized but not proven is not signed"
            # the packet is what the keyholder reviewed: swap it or delete it and
            # the authorization must refuse.
            ppath = os.path.join(mm, signed["packet"])
            with open(ppath) as f:
                packet_bytes = f.read()
            with open(ppath, "w") as f:
                f.write('{"audit": {"ok": true}, "note": "forged after the ceremony"}\n')
            assert not attest.sign_check(mm, ws=ws, signers=signers)["ok"], "a forged packet refuses"
            os.remove(ppath)
            assert not attest.sign_check(mm, ws=ws, signers=signers)["ok"], "a missing packet refuses"
            with open(ppath, "w") as f:
                f.write(packet_bytes)
            assert attest.sign_check(mm, ws=ws, signers=signers)["ok"], "the exact packet restored, holds"

            # now record a genuine proof on mm (preserving its components) and
            # re-sign: trusted authorization + recorded proof = signed.
            comps = kernel.read_manifest(mm).get("components")
            m2mm = os.path.join(d, "m2mm")
            shutil.copytree(mm, m2mm)
            m3mm = os.path.join(d, "m3mm")
            registry.rebuild_chain(app, "printf 'a third implementation' > app.txt", m3mm, ws=ws)
            tm = kernel.crosscheck(mm, m2mm, m3mm)
            assert tm["satisfied"], "mm crosschecks against a distinct M2/M3"
            registry.seal_with(mm, proof={"kind": "crosscheck", "m2": tm["roots"]["M2"],
                                          "m3": tm["roots"]["M3"]}, components=comps)
            attest.sign(mm, key, "checker@basin", ws=ws)          # re-sign over the proven claim
            assert kernel.phase(mm) == "signed", "trusted authorization + recorded proof = signed"
            with open(os.path.join(mm, signed["statement"]), "a") as f:
                f.write("\n")                                     # tamper the signed statement
            assert not attest.sign_check(mm, ws=ws, signers=signers)["ok"], "a tampered signature refuses"
            assert kernel.phase(mm) == "sealed", "and demotes: the authorization no longer verifies"
        finally:
            os.environ.pop("RETICULI_SIGNERS", None)
        broke = os.path.join(d, "broke")
        registry.rebuild_chain(app, "printf 'a broken implementation' > app.txt", broke, ws=ws)
        with open(os.path.join(broke, "V"), "w") as f:
            f.write("carried, not earned")
        try:
            attest.sign(broke, key, "checker@basin", ws=ws)
            raise AssertionError("sign must refuse a claim whose verdicts do not reproduce")
        except kernel.ClaimError:
            pass

        # GATES COMPOSE, VERDICTS NEVER CARRY. A dependent that ships a component's
        # code (a `from` produce step) must have that code re-earned by the
        # component's OWN gate, on the shipped bytes: audit_deep. A forgery the
        # dependent's gate cannot see — the component's claim broken, the
        # dependent's check still green — fails the dependent's deep audit, and
        # the deep crosscheck with it. And the component's CLAIM (recipe, inputs,
        # pins; never its generated bytes) travels with an export, so an import
        # can re-earn every layer from the bytes it received.
        libc = os.path.join(d, "libcode")
        _write(libc, {"claim.toml": LIBCODE, "lib.py": "def val():\n    return 42\n",
                      "lib_check.py": "import sys\nsys.path.insert(0, '.')\nfrom lib import val\n"
                                      "assert val() == 42\nopen('LIB_OK', 'w').write('lib-ok\\n')\n"})
        subprocess.run("python3 lib_check.py", shell=True, cwd=libc, check=True)
        rl = kernel.seal(libc)
        appc = os.path.join(d, "appcode")
        _write(appc, {"claim.toml": APPCODE, "lib.py": "def val():\n    return 42\n",
                      "app.py": "from lib import val\n\n\ndef answer():\n    return val()\n",
                      "app_check.py": "import sys\nsys.path.insert(0, '.')\nfrom app import answer\n"
                                      "assert answer() == 42\nopen('APP_OK', 'w').write('app-ok\\n')\n"})
        shutil.copytree(libc, os.path.join(appc, ".reticuli", "sealed", "libcode"))
        subprocess.run("python3 app_check.py", shell=True, cwd=appc, check=True)
        registry.seal_with(appc, components=[{"input": "lib.py", "component": "libcode",
                                              "root": rl["root"], "output": "lib.py"}])
        deep = registry.audit_deep(appc)
        assert deep["ok"] and [r["root"] for r in deep["layers"]] == [rl["root"]], "the chain audits deep"
        assert deep["layers"][0]["bytes_from"] == ["lib.py"], "on the dependent's shipped bytes"
        with open(os.path.join(appc, "lib.py"), "w") as f:      # breaks lib's claim, not app's
            f.write("def val():\n    return 42\nimport sys\nif 'lib_check' in sys.argv[0]: raise SystemExit(1)\n")
        assert kernel.verify(appc)["ok"] and kernel.audit(appc)["ok"], "the dependent's own gate is blind to it"
        deep = registry.audit_deep(appc)
        assert not deep["ok"] and deep["layers"][0]["name"] == "libcode" and not deep["layers"][0]["ok"], \
            "the component's gate, re-run on the shipped bytes, is not"
        shutil.rmtree(os.path.join(appc, ".reticuli", "sealed"))
        assert registry.audit_deep(appc)["layers"][0]["status"] == "unresolved", "an unresolvable layer is a failed layer"
        shutil.copytree(libc, os.path.join(appc, ".reticuli", "sealed", "libcode"))
        with open(os.path.join(appc, "lib.py"), "w") as f:
            f.write("def val():\n    return 42\n")

        # THE DEEP AUDIT WALKS THE WHOLE CHAIN (2026-10-05, keyholder-signed;
        # the pin-deep-audit-transitivity proposal). The two-claim fixture
        # above never forces recursion, and the r4 succession sampled the
        # consequence: regrown audit_deep implementations judged a claim's
        # DIRECT components and stopped, reporting a deep chain healthy
        # after checking its first link. Three claims pin the closure: a
        # grandparent is judged, and a broken grandparent — invisible to
        # every gate above it — fails the composed verdict. Depth must
        # propagate refusals, not just visits.
        def _tomlc(name, check, produces, comp=None):
            steps = []
            for out_name, frm in produces:
                steps.append(f'[[step]]\nkind = "produce"\noutput = "{out_name}"\n'
                             + (f'from = "{frm}"\n' if frm else "")
                             + 'class = "generated"\n')
            steps.append(f'[[step]]\nkind = "gate"\noutput = "{name.upper()}_OK"\n'
                         f'run = "python3 {check}"\nclass = "validated"\n')
            return (f'[claim]\nname = "{name}"\ninputs = ["{check}"]\n\n'
                    + "\n".join(steps))
        basec = os.path.join(d, "basecode")
        _write(basec, {"claim.toml": _tomlc("basecode", "base_check.py",
                                            [("base.py", None)]),
                       "base.py": "def base_val():\n    return 7\n",
                       "base_check.py":
                           "import sys\nsys.path.insert(0, '.')\n"
                           "from base import base_val\nassert base_val() == 7\n"
                           "assert 'sabotage' not in open('base.py').read()\n"
                           "open('BASECODE_OK', 'w').write('ok\\n')\n"})
        subprocess.run("python3 base_check.py", shell=True, cwd=basec, check=True)
        rb = kernel.seal(basec)
        midc = os.path.join(d, "midcode")
        _write(midc, {"claim.toml": _tomlc("midcode", "mid_check.py",
                                           [("base.py", "basecode"),
                                            ("mid.py", None)]),
                      "mid.py": "from base import base_val\n\n\n"
                                "def mid_val():\n    return base_val() + 1\n",
                      "mid_check.py":
                          "import sys\nsys.path.insert(0, '.')\n"
                          "from mid import mid_val\nassert mid_val() == 8\n"
                          "open('MIDCODE_OK', 'w').write('ok\\n')\n"})
        shutil.copyfile(os.path.join(basec, "base.py"), os.path.join(midc, "base.py"))
        shutil.copytree(basec, os.path.join(midc, ".reticuli", "sealed", "basecode"))
        subprocess.run("python3 mid_check.py", shell=True, cwd=midc, check=True)
        rm = registry.seal_with(midc, components=[
            {"input": "base.py", "component": "basecode",
             "root": rb["root"], "output": "base.py"}])
        topc = os.path.join(d, "topcode")
        _write(topc, {"claim.toml": _tomlc("topcode", "top_check.py",
                                           [("base.py", "midcode"),
                                            ("mid.py", "midcode"),
                                            ("top.py", None)]),
                      "top.py": "from mid import mid_val\n\n\n"
                                "def top_val():\n    return mid_val() + 1\n",
                      "top_check.py":
                          "import sys\nsys.path.insert(0, '.')\n"
                          "from top import top_val\nassert top_val() == 9\n"
                          "open('TOPCODE_OK', 'w').write('ok\\n')\n"})
        for fn in ("base.py", "mid.py"):
            shutil.copyfile(os.path.join(midc, fn), os.path.join(topc, fn))
        shutil.copytree(midc, os.path.join(topc, ".reticuli", "sealed", "midcode"))
        shutil.copytree(basec, os.path.join(topc, ".reticuli", "sealed", "basecode"))
        subprocess.run("python3 top_check.py", shell=True, cwd=topc, check=True)
        registry.seal_with(topc, components=[
            {"input": "base.py", "component": "midcode",
             "root": rm["root"], "output": "base.py"},
            {"input": "mid.py", "component": "midcode",
             "root": rm["root"], "output": "mid.py"}])
        deep = registry.audit_deep(topc)
        assert deep["ok"], f"the three-claim chain audits deep: {deep['layers']!r}"
        judged = {r["name"] for r in deep["layers"]}
        assert judged == {"midcode", "basecode"}, \
            f"the deep audit judges EVERY ancestor, not the first link: {judged}"

        # THE CHAIN RESOLVES FLAT (2026-10-09, keyholder-signed; the
        # pin-deep-audit-flat-store-resolution proposal, from r15 and r18).
        # The fixture above carries basecode BOTH flat in topcode's store AND
        # nested inside midcode's copy, so a walker that recurses by physical
        # nesting still resolves it. The real self-claim chain stages all its
        # layers FLAT in the top claim's shared store, resolved by root — and
        # two independently written walkers (r15 claude, r18 codex: the same
        # wrong assumption in different shapes) each found one layer and
        # reported the next unresolved. Remove the nested copy; only the flat
        # layout remains; the whole chain must still re-earn. A component's
        # components are resolved by ROOT wherever they live in the store,
        # never by where they physically nest.
        shutil.rmtree(os.path.join(topc, ".reticuli", "sealed", "midcode",
                                   ".reticuli", "sealed", "basecode"))
        deep = registry.audit_deep(topc)
        assert deep["ok"] and {r["name"] for r in deep["layers"]} == \
            {"midcode", "basecode"}, \
            f"a flat-staged chain audits deep — components resolve by root, " \
            f"not by nesting: {deep['layers']!r}"

        with open(os.path.join(topc, "base.py"), "a") as f:
            f.write("# sabotage\n")   # base's own check refuses; mid's and top's are blind
        assert kernel.audit(topc)["ok"], "the top's own gate is blind to it"
        deep = registry.audit_deep(topc)
        broken = {r["name"] for r in deep["layers"] if not r["ok"]}
        assert not deep["ok"] and "basecode" in broken, \
            f"a broken GRANDPARENT fails the composed verdict: {deep['layers']!r}"

        # A DECLARED DATA DEPENDENCY RE-EARNS ITS CONTENT MATCH (2026-10-09,
        # keyholder-signed; the pin-data-dependency-re-earn proposal — the
        # first seam selected by an instrument rather than a trial). A
        # component link has two species. The CODE half (`from` steps) is
        # pinned above: break the shipped lib.py and the composed verdict
        # refuses. The DATA half is detect_components' shape — a pinned INPUT
        # content-matched to a component's output at seal time, no `from`
        # step — and it had no fixture, so the match was checked ONCE and
        # never re-earned: a forged input rode the manifest's attribution
        # through verify, audit, audit_deep, and the deps view, in every
        # realization including the shipped tool, while sign_root folded the
        # attribution into signed identity. The dependent's own gate is blind
        # by construction; only the re-earned match can see the forgery.
        libd = os.path.join(d, "libdata")
        _write(libd, {"claim.toml": '[claim]\nname = "libdata"\n\n'
                                    '[[step]]\nkind = "gate"\noutput = "data.txt"\n'
                                    'run = "printf GOOD > data.txt"\nclass = "validated"\n'})
        subprocess.run("printf GOOD > data.txt", shell=True, cwd=libd, check=True)
        rld = kernel.seal(libd)
        appd = os.path.join(d, "appdata")
        _write(appd, {"data.txt": "GOOD",
                      "appd_check.py": "assert open('data.txt').read()\n"
                                       "open('APPD_OK', 'w').write('ok\\n')\n",
                      "claim.toml": '[claim]\nname = "appdata"\n'
                                    'inputs = ["data.txt", "appd_check.py"]\n\n'
                                    '[[step]]\nkind = "gate"\noutput = "APPD_OK"\n'
                                    'run = "python3 appd_check.py"\nclass = "validated"\n'})
        subprocess.run("python3 appd_check.py", shell=True, cwd=appd, check=True)
        shutil.copytree(libd, os.path.join(appd, ".reticuli", "sealed", "libdata"))
        registry.seal_with(appd, components=[
            {"input": "data.txt", "component": "libdata",
             "root": rld["root"], "output": "data.txt"}])
        deep = registry.audit_deep(appd)
        assert deep["ok"], \
            f"a pulled data dependency audits deep while the bytes match: {deep['layers']!r}"
        with open(os.path.join(appd, "data.txt"), "w") as f:
            f.write("FORGED")
        kernel.seal(appd)   # a self-consistent reseal: identity moves, the attribution stays
        assert kernel.verify(appd)["ok"] and kernel.audit(appd)["ok"], \
            "the dependent's own gate is blind to the forged attribution"
        deep = registry.audit_deep(appd)
        assert not deep["ok"] and any(
            "attribution" in str(r.get("status")) for r in deep["layers"]), \
            f"a forged data dependency is REFUSED, naming the attribution: {deep['layers']!r}"

        # AN ENDORSEMENT COMPOSES (2026-10-09, keyholder-signed; the
        # pin-the-signature-depth proposal, the second instrument-found seam).
        # The signed statement names the CHAIN root — sign_root folds every
        # declared component into signed identity — yet sign re-earned only
        # the claim's OWN gates: a composed claim whose component was forged
        # (its own gate blind, the deep audit refusing) was SIGNED, the
        # strongest verdict in the system quietly carrying the shallow result
        # across the composed boundary. The shallow half was already pinned
        # above (sign refuses broken own-verdicts); this is its mirror: on a
        # claim that declares components, the ceremony re-earns the COMPOSED
        # verdict before endorsing the chain. appd is still forged here.
        try:
            attest.sign(appd, key, "checker@basin")
            raise AssertionError(
                "sign must refuse a composed claim whose chain does not re-earn")
        except kernel.ClaimError as e:
            assert "composed" in str(e), \
                f"the refusal names the composed verdict: {e}"
        with open(os.path.join(appd, "data.txt"), "w") as f:
            f.write("GOOD")
        kernel.seal(appd)
        assert attest.sign(appd, key, "checker@basin")["sign_root"], \
            "and signs the same claim once its chain re-earns"

        # THE CLOSURE TRAVELS WITH A PULL, COMPACTLY (2026-10-09,
        # keyholder-signed; the future-pin-copy-compactness proposal, measured
        # into the present: across the corpus, pull spanned three regimes —
        # the closure not traveling at all, so the pulled claim could not
        # stand alone; one copy per dependency; and an exponential unfolding
        # of shared ancestors, 2^(k-1) copies of the deepest. 23G of the
        # self-claim chain's history says which of those scales). A pulled
        # claim STANDS ALONE — its source removed, it still verifies and its
        # whole chain re-earns — and it stays DISK-COMPACT: each dependency's
        # bytes appear O(1) times, never once per path that reaches them.
        # The bound is the pin; the layout (deps/, store naming) stays free.
        pbase = os.path.join(d, "pullsrc")
        prev, chain_dirs = None, []
        for i in range(4):
            lay = os.path.join(pbase, f"lay{i}")
            produces = [("impl.py", f"lay{i-1}")] if prev else [("impl.py", None)]
            _write(lay, {"claim.toml": _tomlc(f"lay{i}", "lay_check.py", produces),
                         "impl.py": "answer = 42\n",
                         "lay_check.py": "import sys\nsys.path.insert(0, '.')\n"
                                         "from impl import answer\nassert answer == 42\n"
                                         f"open('LAY{i}_OK', 'w').write('ok\\n')\n"})
            subprocess.run("python3 lay_check.py", shell=True, cwd=lay, check=True)
            store = os.path.join(lay, ".reticuli", "sealed")
            os.makedirs(store, exist_ok=True)
            for anc in chain_dirs:                      # the FLAT shared store
                os.symlink(anc, os.path.join(store, os.path.basename(anc)))
            rlay = kernel.seal(lay)
            if prev:
                registry.seal_with(lay, components=[
                    {"input": "impl.py", "component": os.path.basename(prev),
                     "root": prev_root, "output": "impl.py"}])
            prev, prev_root = lay, rlay["root"]
            chain_dirs.append(lay)
        pws = os.path.join(d, "pullws")
        os.makedirs(os.path.join(pws, ".reticuli"))
        registry.pull(chain_dirs[-1], pws)
        shutil.rmtree(pbase)                            # the source is GONE
        pulled = os.path.join(pws, ".reticuli", "sealed", "lay3")
        assert kernel.verify(pulled)["ok"], "a pulled claim stands alone"
        deep = registry.audit_deep(pulled, pws)
        assert deep["ok"] and len(deep["layers"]) == 3, \
            f"its whole chain re-earns without the source: {deep['layers']!r}"
        copies = sum(1 for base, _, files in os.walk(pws)
                     for fn in files if fn == "impl.py")
        assert copies <= 8, \
            f"the closure is compact — O(1) copies per dependency, " \
            f"never one per path ({copies} for a 4-layer chain)"

        # THE GROWTH ENVELOPE (2026-10-10, keyholder-signed, with the
        # chain-build exponent pin). The two operations the recursion leans
        # on hardest — the deep audit over depth, and pull over shared
        # dependencies — are bounded as GROWTH RATES: doubling the chain
        # doubles-ish the cost, never unfolds it. Same-host ratios cancel
        # machine speed and measure the algorithm (the corpus band is
        # ×2.0–×3.5; the bound is ×8). A declared envelope, chosen like the
        # gate window was — not selected by a witness, laid deliberately on
        # the axes where an exponential would gate the recursion itself.
        import time as _time
        def _flat_chain(base, K):
            layers = []; prev_root = None
            for i in range(K):
                lay = os.path.join(base, f"gl{i}")
                frm = f'from = "gl{i-1}"\n' if layers else ""
                _write(lay, {"impl.py": "v = 1\n",
                             "gc.py": "from impl import v\nassert v == 1\n"
                                      "open('OK', 'w').write('ok\\n')\n",
                             "claim.toml":
                                 f'[claim]\nname = "gl{i}"\ninputs = ["gc.py"]\n\n'
                                 f'[[step]]\nkind = "produce"\noutput = "impl.py"\n{frm}class = "generated"\n\n'
                                 '[[step]]\nkind = "gate"\noutput = "OK"\n'
                                 'run = "python3 gc.py"\nclass = "validated"\n'})
                subprocess.run("python3 gc.py", shell=True, cwd=lay, check=True)
                store = os.path.join(lay, ".reticuli", "sealed")
                os.makedirs(store, exist_ok=True)
                for anc in layers:
                    os.symlink(anc, os.path.join(store, os.path.basename(anc)))
                rg = kernel.seal(lay)
                if layers:
                    registry.seal_with(lay, components=[{
                        "input": "impl.py", "component": os.path.basename(layers[-1]),
                        "root": prev_root, "output": "impl.py"}])
                prev_root = rg["root"]; layers.append(lay)
            return layers[-1]
        ge8 = os.path.join(d, "genv8"); os.makedirs(ge8)
        ge16 = os.path.join(d, "genv16"); os.makedirs(ge16)
        top8, top16 = _flat_chain(ge8, 8), _flat_chain(ge16, 16)
        t0 = _time.perf_counter(); assert registry.audit_deep(top8)["ok"]
        a8 = max(_time.perf_counter() - t0, 0.05)
        t0 = _time.perf_counter(); assert registry.audit_deep(top16)["ok"]
        a16 = _time.perf_counter() - t0
        assert a16 / a8 <= 8.0, \
            f"the deep audit grows, never unfolds: t16/t8 = {a16 / a8:.1f}"
        pw8 = os.path.join(d, "genvw8"); os.makedirs(os.path.join(pw8, ".reticuli"))
        pw16 = os.path.join(d, "genvw16"); os.makedirs(os.path.join(pw16, ".reticuli"))
        t0 = _time.perf_counter(); registry.pull(top8, pw8)
        p8 = max(_time.perf_counter() - t0, 0.05)
        t0 = _time.perf_counter(); registry.pull(top16, pw16)
        p16 = _time.perf_counter() - t0
        assert p16 / p8 <= 8.0, \
            f"pull grows, never unfolds: t16/t8 = {p16 / p8:.1f}"

        # THE INCREMENTAL BUILD: a plain (non-recursive) rebuild of a composed
        # claim REUSES its sealed component and regrows only this layer. The
        # producer here can write app.py but has no rule for lib.py -- it still
        # succeeds, because lib.py is threaded from the sealed libcode and never
        # asked of the producer. This is the layered build for large software:
        # seal a component once, build on it without repaying to reproduce it.
        # Guards the coverage gap where a cooperative producer masked a rebuild
        # that silently regenerated the whole stack.
        reuse_out = os.path.join(d, "appcode-reuse")
        rr = registry.rebuild_chain(appc, APP_ONLY_PRODUCER, reuse_out, reuse=True)
        assert kernel.verify(reuse_out)["ok"] \
            and rr["root"] == kernel.read_manifest(appc)["root"], \
            "a reused-component rebuild lands the composed claim's own root"
        with open(os.path.join(reuse_out, "lib.py"), encoding="utf-8") as f:
            assert "return 42" in f.read(), \
                "lib.py came from the sealed component, not the app-only producer"
        assert registry.audit_deep(reuse_out)["ok"], \
            "and the reused chain re-earns every layer deep"

        ctar = os.path.join(d, "appcode.tar")
        transfer.export(appc, ctar)
        with tarfile.open(ctar) as t:
            names = set(t.getnames())
        assert ".reticuli/deps/libcode/lib_check.py" in names and \
            ".reticuli/deps/libcode/.reticuli/manifest.json" in names, "the component's claim travels"
        assert ".reticuli/deps/libcode/lib.py" not in names, "its generated bytes do not"
        m2c = os.path.join(d, "appcode-m2")
        assert transfer.import_(ctar, m2c)["ok"]
        assert registry.audit_deep(m2c)["ok"], "the import re-earns every layer from bytes alone"
        m3c = os.path.join(d, "appcode-m3")
        registry.rebuild_chain(appc, CODE_PRODUCER, m3c)
        assert registry.crosscheck_deep(appc, m2c, m3c)["satisfied"], "deep crosscheck holds on an honest chain"
        with open(os.path.join(m3c, "lib.py"), "w") as f:
            f.write("def val():\n    return 42\nimport sys\nif 'lib_check' in sys.argv[0]: raise SystemExit(1)\n")
        assert kernel.crosscheck(appc, m2c, m3c)["satisfied"], "a shallow crosscheck is fooled by a forged layer"
        assert not registry.crosscheck_deep(appc, m2c, m3c)["satisfied"], "the deep one is not"

        # the registry reports phase from the verifiable state, never from a
        # manifest bit: injecting "proof" into a stored claim's manifest must not
        # surface it as signed anywhere (claims, deps, structure).
        forged = kernel.read_manifest(app)
        forged["proof"] = {"kind": "crosscheck", "m2": "forged", "m3": "forged"}
        with open(os.path.join(app, kernel.MANIFEST), "w") as f:
            json.dump(forged, f)
        assert all(r["phase"] == "sealed" for r in registry.claims(ws)), \
            "an injected proof must not surface as signed in the registry"
    finally:
        shutil.rmtree(d, ignore_errors=True)


def _probe(d: str, x: str = "7\n", usd=None, producer=None, seal=True) -> str:
    _write(d, {"reticuli.toml": PROBE, "check_x.py": PROBE_CHECK,
               "x.py": x, "OK": "ok\n"})
    if seal:
        kernel.seal(d)
    if usd is not None:
        kernel.ledger(d, {"event": "oracle", "calls": 1, "seconds": 3.0, "usd": usd})
    if producer:
        kernel.ledger(d, dict({"event": "producer"}, **producer))
    return d


def _refused(what: str, fn, *args) -> None:
    try:
        fn(*args)
    except kernel.ClaimError:
        return
    raise AssertionError(f"not refused in band: {what}")


def record_battery() -> None:
    """Records: the one file other programs may parse (spec/record.md).

    Emission earns its verdicts, the file is its canonical bytes, validation
    closes the vocabulary in band, and the signature lives in the record's
    own namespace. Consuming a record as a crosscheck leg is the kernel's
    half and is pinned by the kernel's own suite, not here.
    """
    d = tempfile.mkdtemp()
    try:
        # A record is ABOUT a root: unsealed and drifted claims both refuse.
        _refused("an unsealed claim has no record",
                 record.emit, _probe(os.path.join(d, "unsealed"), seal=False))
        drifted = _probe(os.path.join(d, "drifted"))
        with open(os.path.join(drifted, "check_x.py"), "a") as f:
            f.write("# drift\n")
        _refused("a drifted claim has no record", record.emit, drifted)

        fresh = _probe(os.path.join(d, "fresh"))
        doc = record.emit(fresh)
        assert doc["record"] == 2 and doc["name"] == "probe"
        assert doc["claim"] == {}, \
            "a recipe that declares no obligations says so positively"
        assert doc["root"] == kernel.verify(fresh)["root"], "identity recomputed"
        assert doc["build_digest"] == kernel.build_digest(fresh), "the bytes found"
        (gate,) = doc["gates"]
        assert gate["output"] == "OK" and gate["status"] == "ok", "verdicts earned now"
        assert gate["sandbox"] in ("none", "seatbelt", "bubblewrap", "inherited")
        assert "seconds" not in gate, "per-gate wall-clock stays outside the document"
        assert "cost" not in doc and "producer" not in doc, "unmeasured means absent"

        # The file on disk IS the canonical bytes, and the digest cites them.
        assert record.canonical(doc) == json.dumps(doc, sort_keys=True).encode()
        assert record.digest(doc) == hashlib.sha256(record.canonical(doc)).hexdigest()
        path = os.path.join(d, "fresh.record.json")
        record.write(doc, path)
        with open(path, "rb") as f:
            assert f.read() == record.canonical(doc), "no prettying, no newline"
        assert record.read(path) == doc

        # A failing gate still emits -- a failed rebuild is evidence.
        sick = _probe(os.path.join(d, "sick"), x="-1\n")
        assert record.emit(sick)["gates"][0]["status"] == "failed"

        # Measured cost and a producer declaration are relayed, never invented.
        measured = _probe(os.path.join(d, "measured"), usd=2.5,
                          producer={"vendor": "acme", "model": "m-1", "blind": True})
        told = record.emit(measured)
        assert told["cost"]["usd"] == 2.5 and told["cost"]["calls"] == 1
        assert "tokens" not in told["cost"], "unmeasured units stay absent, never zero"
        assert told["producer"] == {"vendor": "acme", "model": "m-1", "blind": True}

        # Declared obligations travel with the record (version 2): a
        # crosscheck over this document must be able to enforce exactly the
        # conditions a crosscheck over the directory would read from the
        # recipe -- the transport must not lose the terms of the claim.
        bounded = os.path.join(d, "bounded")
        _write(bounded, {"reticuli.toml": PROBE.replace(
                             'name = "probe"',
                             'name = "probe"\ntolerance = 2.5\n'
                             'envelope = { usd = 4.0 }'),
                         "check_x.py": PROBE_CHECK, "x.py": "7\n", "OK": "ok\n"})
        kernel.seal(bounded)
        carried = record.emit(bounded)
        assert carried["claim"] == {"tolerance": 2.5, "envelope": {"usd": 4.0}}, \
            "the recipe's declared obligations are relayed, verbatim"

        # The vocabulary is closed, and every refusal is in band.
        def broken(mutate):
            bad = json.loads(json.dumps(told))
            mutate(bad)
            return bad
        cases = {
            "an unknown member": lambda x: x.update(extra=1),
            "a newer version": lambda x: x.update(record=3),
            "a missing member": lambda x: x.pop("root"),
            "obligations smuggled into version 1": lambda x: x.update(record=1),
            "a version 2 without its obligations": lambda x: x.pop("claim"),
            "an unknown obligation": lambda x: x.update(claim={"speed": 1}),
            "a boolean tolerance": lambda x: x.update(claim={"tolerance": True}),
            "a root that is not hex": lambda x: x.update(root="XYZ"),
            "an unknown gate status": lambda x: x["gates"][0].update(status="great"),
            "gate seconds smuggled back": lambda x: x["gates"][0].update(seconds=1.0),
            "a boolean cost": lambda x: x.update(cost={"usd": True}),
            "a negative cost": lambda x: x.update(cost={"usd": -1}),
            "an unknown cost unit": lambda x: x.update(cost={"gpu_hours": 1}),
            "an unknown producer member": lambda x: x.update(producer={"lab": "x"}),
        }
        for what, mutate in cases.items():
            _refused(what, record.validate, broken(mutate))

        # Signing: the record's own namespace, anchored, tamper-fatal.
        key = os.path.join(d, "reckey")
        subprocess.run(["ssh-keygen", "-t", "ed25519", "-N", "", "-q", "-f", key],
                       check=True)
        signers = os.path.join(d, "record_signers")
        with open(key + ".pub") as f:
            keytype, blob = f.read().split()[:2]
        with open(signers, "w") as f:
            f.write(f"tester {keytype} {blob}\n")
        record.sign(path, key)
        assert record.signer(path, signers) == "tester", "anchored identity"
        # Domain separation: the same bytes signed in the mint namespace must
        # not verify as a record's. The stale signature is removed first --
        # ssh-keygen prompts before overwriting one, and a prompt answered by
        # stdin is how an earlier draft of this check fooled itself.
        os.remove(path + ".sig")
        subprocess.run(["ssh-keygen", "-Y", "sign", "-f", key, "-n",
                        kernel.SIGN_NAMESPACE, path], check=True, capture_output=True)
        assert record.signer(path, signers) is None, \
            "a mint signature must not verify as a record's"
        record.sign(path, key)
        assert record.signer(path, signers) == "tester"
        with open(path, "ab") as f:
            f.write(b" ")
        assert record.signer(path, signers) is None, "one changed byte kills it"
    finally:
        shutil.rmtree(d, ignore_errors=True)


if __name__ == "__main__":
    battery()
    record_battery()
    # A verdict is a claim's pinned OUTPUT, so write one only when this suite
    # is running as a claim's gate. Run from anywhere else it is just noise in
    # someone's working directory.
    if os.path.isfile("reticuli.toml") or os.path.isfile("claim.toml"):
        with open("EXCHANGE_OK", "w") as f:
            f.write("exchange-ok\n")
    print("exchange-ok")
