"""Execution conformance gate -- the acceptance check of the launcher layer.

The launcher runs software that exists only latently in a claim.  A runnable
claim keeps only its claim durable (pinned inputs + gate + verdicts); the
implementation is a cache entry.  `run` makes the claim executable -- checking
a cached build or regrowing a fresh one with a producer -- and `strip` deletes
the generated bytes back to latency.  Deleting is always safe because the
claim, not the code, is the identity.

This check IS the launcher's definition.  What it gates is
`src/reticuli/launcher.py` (generated bytes); any module answering `python3 -m
reticuli.launcher` and satisfying every claim below is the launcher.  The
verification layer beneath it (verify / audit / rebuild, `kernel.py`) is what
it stands on.

THE PACKAGE CONTRACT (interchange currency, pinned):

  A runnable claim is an ordinary Reticuli claim whose PINNED INPUTS include
  `package.toml`:

      [package]
      entrypoint = "hello.py"     # a file inside the claim

  Entrypoints run as `python3 <entrypoint> <args...>` with the claim root as
  cwd.  package.toml must be a PINNED INPUT -- an entrypoint declaration that
  could drift from what the gate exercised would divorce "what was proven"
  from "what runs"; the launcher refuses package.toml offered as a generated
  output, refuses claims without one, and refuses an entrypoint that escapes
  the claim root.

THE VERBS (pinned surface, `python3 -m reticuli.launcher ...`):

  run   <claim> [--accept-generated] [--signed-only] [--no-sandbox] [-- args...]
  strip <claim>
  ls    <claim>...

EXIT CODES (interchange currency -- orchestrators depend on these):

  when the entrypoint runs, the launcher's exit code IS the entrypoint's.
  3 = not runnable (no/unpinned package.toml, escaping entrypoint or path)
  4 = newly generated bytes, consent required (materialized but not executed;
      pass --accept-generated to execute and accept them)
  5 = trust refused (--signed-only on a claim that is not signed to you)
  6 = drifted build (audit failed; nothing executed, nothing modified --
      the evidence is preserved; strip is the recovery path)
  7 = latent and no producer configured (RETICULI_PRODUCER unset)

CHANNEL DISCIPLINE (pinned): the launcher speaks ONLY on stderr.  stdout
belongs entirely to the entrypoint (claims test byte-exact stdout).  The
stderr metadata includes `quarantine = "<seatbelt|bubblewrap|inherited|
none|off>"` for every execution; `--no-sandbox` reports "off".  The launcher
must REPORT its execution sandbox honestly; the *enforcement* strength of any
backend is the kernel's claim, not re-proven here.

EXECUTION HYGIENE (pinned; both clauses are red-team carves, round 1): the
entrypoint runs with a SCRUBBED environment -- PATH and locale plus a
claim-local HOME/TMPDIR, the already-sandboxed signal when sandboxed, and
never the caller's secrets (the same hygiene the kernel gives gates; without
this clause BOTH vendors' independently written launchers leaked a canary --
a basin-wide hole, because the cage is exactly as tight as the spec).  And
every recipe-derived path (produce outputs) is CONFINED to the claim root: a
recipe naming an absolute or climbing path is refused with exit 3 before
anything is deleted, written, or executed (without this clause one honest
draw deleted a file outside its claim on `strip` -- unpinned freedom where
safety must not be left to the draw).

Round-2 pins, from the validation rebuilds: the claim argument may be a
RELATIVE path from any working directory (one landed draw doubled relative
paths -- the surface was untested); and where the platform provides a sandbox
(sandbox-exec or bwrap on PATH), default execution must USE one -- reporting
`quarantine = "none"` while a sandbox sits available is refused (one landed
draw declined the sandbox while reporting honestly; honest declining is still
declining).

STATE: freshly generated bytes stay unaccepted across invocations until a
`run` with --accept-generated executes them -- consent is a durable human act,
not per-invocation friction.  Launcher state lives under `<claim>/.launcher/`
and is removed by strip.

FRESHNESS vs DRIFT: fresh = the launcher generated these bytes and no one has
accepted them (refuse politely, offer the flag).  Accepting an implementation
(--accept-generated) RECORDS ITS BYTE DIGESTS -- consent binds bytes, not a
mood; the launcher's miniature of the signature chain's build digest, at the
sealed layer.  Drift = an ACCEPTED implementation whose bytes no longer match
what was accepted, even if the new bytes still pass the gate (an edit inside
the equivalence class is still an unreviewed substitution): refuse loudly,
execute nothing, modify nothing.  An implementation the launcher never
generated or accepted (packed by hand, imported) runs on audit alone -- the
launcher guards what the launcher accepted.

Editing `src/reticuli/launcher.py` keeps this claim's root; editing this check
moves it.  Stdlib only, so it runs in any clean room; it drives the launcher
by subprocess (`python3 -m reticuli.launcher`) with the package directory on
PYTHONPATH, so the package under test is the one shipped beside this check.

    python3 checks/launcher_check.py           (from the repository root)
"""
import hashlib
import json
import os
import shutil
import subprocess
import sys

# The package lives in `src/` in the repository and beside the check inside a
# sealed claim room; one line covers both.
sys.path.insert(0, "src" if os.path.isdir("src/reticuli") else ".")
PKG_PATH = os.path.abspath(sys.path[0])

from reticuli import kernel

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORK = os.path.join(ROOT, ".checkwork")
LAUNCHER_MODULE = os.path.join(PKG_PATH, "reticuli", "launcher.py")
PY = sys.executable
LCMD = [PY, "-m", "reticuli.launcher"]

HELLO = '''import sys
if "--fail" in sys.argv:
    sys.exit(9)
who = next((a for a in sys.argv[1:] if not a.startswith("-")), "void")
print("hello, " + who)
'''

PACKAGE_GATE = '''import subprocess, sys
p = subprocess.run([sys.executable, "hello.py", "world"],
                   capture_output=True, text=True)
sys.exit(0 if p.returncode == 0 and p.stdout == "hello, world\\n" else 1)
'''

PACKAGE = '[package]\nentrypoint = "hello.py"\n'
GATE = "python3 check_package.py && printf ok > PACKAGE_OK"

PRODUCER = '''#!/usr/bin/env python3
import os
SRC = {!r}
out = os.environ["RETICULI_OUTPUT"]
with open(out, "w") as f:
    f.write(SRC[os.path.basename(out)])
'''.format({"hello.py": HELLO})

failures = []


def claim(cid, ok, detail):
    if not ok:
        failures.append((cid, detail))
    print(("PASS " if ok else "FAIL ") + cid + "  " + detail)


def sha(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def launcher(args, env=None, cwd=ROOT):
    e = os.environ.copy()
    e.pop("RETICULI_PRODUCER", None)
    if env:
        e.update(env)
    return subprocess.run(LCMD + args, capture_output=True,
                          text=True, env=e, cwd=cwd, timeout=300, check=False)


def write_recipe(d, name, inputs, generated, gate_run, gate_output):
    """The v2 recipe: [claim], claim.toml, explicit step classes."""
    q = json.dumps                      # JSON string escaping is TOML-basic
    lines = ["[claim]",
             f"name = {q(name)}",
             "inputs = [" + ", ".join(q(i) for i in inputs) + "]",
             ""]
    for out in generated:
        lines += ["[[step]]",
                  'kind = "produce"',
                  f"output = {q(out)}",
                  'class = "generated"',
                  f"request = {q('regenerate ' + out + ' to pass the gate')}",
                  ""]
    lines += ["[[step]]",
              'kind = "gate"',
              f"output = {q(gate_output)}",
              'class = "validated"',
              f"run = {q(gate_run)}",
              ""]
    with open(os.path.join(d, kernel.RECIPE), "w") as f:
        f.write("\n".join(lines))


def seal_fixture(d, gate_run):
    """Earn the gate verdict, then seal the claim.

    v1 packed its fixtures by shelling out to `ret pack` -- the CLI, a layer
    ABOVE the one under test.  Here the check writes the recipe itself, earns
    the verdict through the kernel's own gate runner, and seals with the
    kernel's `seal`, so the launcher's acceptance check depends on nothing but
    the layer beneath the launcher.
    """
    recipe = kernel.load_recipe(d)
    outcome = kernel.run_gate(gate_run, d, recipe)
    assert outcome["status"] == "ok", "fixture gate failed:\n" + \
        (outcome["stderr"] or outcome["stdout"])
    return kernel.seal(d)


def build_package(name, package_as, package_text=PACKAGE):
    """Pack a hello fixture; package_as is 'input', 'generated', or None."""
    d = os.path.join(WORK, name)
    os.makedirs(d)
    for fn, body in (("hello.py", HELLO), ("check_package.py", PACKAGE_GATE)):
        with open(os.path.join(d, fn), "w") as f:
            f.write(body)
    if package_as:
        with open(os.path.join(d, "package.toml"), "w") as f:
            f.write(package_text)
    generated = ["hello.py"] + (["package.toml"]
                                if package_as == "generated" else [])
    inputs = ["check_package.py"] + (["package.toml"]
                                     if package_as == "input" else [])
    write_recipe(d, name, inputs, generated, GATE, "PACKAGE_OK")
    seal_fixture(d, GATE)
    return d


def build_claim(name, files, generated, inputs, gate, output):
    d = os.path.join(WORK, name)
    os.makedirs(d)
    for fn, body in files.items():
        with open(os.path.join(d, fn), "w") as f:
            f.write(body)
    write_recipe(d, name, inputs, generated, gate, output)
    seal_fixture(d, gate)
    return d


def manifest_root(d):
    try:
        return kernel.read_manifest(d).get("root", "")
    except kernel.ClaimError:
        return ""


def main():
    # The package directory is on PYTHONPATH, so `python3 -m reticuli.launcher`
    # binds the package shipped beside this check from any cwd (L12 runs a
    # claim from elsewhere).
    os.environ["PYTHONPATH"] = PKG_PATH + os.pathsep + \
        os.environ.get("PYTHONPATH", "")
    if os.path.exists(WORK):
        shutil.rmtree(WORK)
    os.makedirs(WORK)

    # L0 -- the surface: the module exists and its verbs and flags are named.
    claim("L0-exists", os.path.isfile(LAUNCHER_MODULE),
          "reticuli/launcher.py present")
    if not os.path.isfile(LAUNCHER_MODULE):
        return report()
    h = launcher(["--help"])
    tokens = ["run", "strip", "ls", "--accept-generated", "--signed-only",
              "--no-sandbox"]
    claim("L0-help", h.returncode == 0 and
          all(t in h.stdout + h.stderr for t in tokens),
          "--help exits 0 and names " + ", ".join(tokens))

    # Fixtures.
    good = build_package("hello-package", "input")
    nopackage = build_package("no-package", None)
    genpackage = build_package("generated-package", "generated")
    escape = build_package("escape-package", "input",
                           '[package]\nentrypoint = "../evil.py"\n')
    root_hash = manifest_root(good)
    claim("L0-fixture", len(root_hash) == 64, "hello-package packed and fresh")

    # L1 -- the package contract: what is refused is refused by name.
    r = launcher(["run", nopackage])
    claim("L1-nopackage", r.returncode == 3 and "package.toml" in r.stderr,
          "no package.toml -> exit 3, message names it")
    r = launcher(["run", genpackage])
    claim("L1-unpinned", r.returncode == 3 and
          ("input" in r.stderr or "pinned" in r.stderr),
          "package.toml as generated output -> exit 3, names the pinning rule")
    r = launcher(["run", escape])
    claim("L1-escape", r.returncode == 3 and r.stdout == "",
          "escaping entrypoint -> exit 3, nothing executed")

    # L2 -- a standing build executes: stdout pure, args pass, exit propagates.
    r = launcher(["run", good, "--", "reviewer"])
    claim("L2-runs", r.returncode == 0 and r.stdout == "hello, reviewer\n",
          "stdout is byte-exactly the entrypoint's")
    claim("L2-banner", "sealed" in r.stderr,
          "a sealed claim banners its phase on stderr")
    r = launcher(["run", good, "--", "--fail"])
    claim("L2-exit", r.returncode == 9,
          "the entrypoint's exit code is the launcher's")

    # L4 (before L3 so the claim is latent for the regrowing claims) --
    # strip deletes only the generated bytes.
    kept = {p: sha(os.path.join(good, p))
            for p in ("package.toml", "check_package.py", "PACKAGE_OK",
                      "claim.toml")}
    r = launcher(["strip", good])
    claim("L4-strip", r.returncode == 0 and
          not os.path.exists(os.path.join(good, "hello.py")),
          "strip removes the generated implementation")

    def sha_or_none(p):
        return sha(p) if os.path.exists(p) else None
    claim("L4-keeps", all(sha_or_none(os.path.join(good, p)) == h
                          for p, h in kept.items()),
          "inputs, verdicts, recipe byte-identical after strip")
    try:
        vok = kernel.verify(good).get("ok") is True
    except kernel.ClaimError:
        vok = False
    claim("L4-identity", vok,
          "a stripped claim still verifies -- the claim is the identity")
    r = launcher(["strip", good])
    claim("L4-idempotent", r.returncode == 0, "stripping latency is a no-op")

    # L5 -- latency needs a producer, and says so.
    r = launcher(["run", good])
    claim("L5-no-producer",
          r.returncode == 7 and "RETICULI_PRODUCER" in r.stderr,
          "latent + no producer -> exit 7, names the variable")

    # L3 -- regrowing and consent: fresh is a durable state until accepted.
    prod = os.path.join(WORK, "producer.py")
    with open(prod, "w") as f:
        f.write(PRODUCER)
    env = {"RETICULI_PRODUCER": PY + " " + prod}
    r = launcher(["run", good], env=env)
    claim("L3-consent", r.returncode == 4 and "--accept-generated" in r.stderr
          and r.stdout == "",
          "the rebuild lands but does not execute; the flag is offered")
    claim("L3-lands", os.path.exists(os.path.join(good, "hello.py"))
          and manifest_root(good) == root_hash,
          "the regrown bytes land on the sealed root")
    r = launcher(["run", good], env=env)
    claim("L3-durable", r.returncode == 4,
          "freshness survives invocations -- consent is not retry friction")
    r = launcher(["run", good, "--accept-generated", "--", "consenter"],
                 env=env)
    claim("L3-accept", r.returncode == 0 and r.stdout == "hello, consenter\n",
          "--accept-generated executes and accepts the bytes")
    r = launcher(["run", good, "--", "again"])
    claim("L3-accepted", r.returncode == 0 and r.stdout == "hello, again\n",
          "an accepted build is standing -- no flag needed after consent")

    # L6 -- drift: an accepted implementation whose bytes changed is refused
    # even when the new bytes would still pass the gate (edits inside the
    # equivalence class are unreviewed substitutions once consent bound bytes).
    with open(os.path.join(good, "hello.py"), "a") as f:
        f.write("# tampered\n")
    drifted = sha(os.path.join(good, "hello.py"))
    r = launcher(["run", good, "--", "attacker"])
    claim("L6-refuse", r.returncode == 6 and r.stdout == "",
          "drifted build -> exit 6, nothing executed")
    claim("L6-forensics", sha(os.path.join(good, "hello.py")) == drifted
          and "strip" in r.stderr,
          "drifted bytes preserved; strip suggested as the recovery path")
    launcher(["strip", good])
    r = launcher(["run", good, "--accept-generated", "--", "healed"], env=env)
    claim("L6-recover", r.returncode == 0 and r.stdout == "hello, healed\n",
          "strip + regrow + consent recovers the claim")

    # L7 -- the trust ladder gates execution. (The signed-positive path needs
    # a signed fixture and is deliberately NOT claimed here; it lands with
    # the first signed package.)
    r = launcher(["run", good, "--signed-only", "--", "boss"])
    claim("L7-signed", r.returncode == 5 and r.stdout == "" and
          ("signed" in r.stderr or "sign" in r.stderr),
          "--signed-only refuses a sealed claim by name")

    # L8 -- sandbox honesty: every execution reports its confinement.
    r = launcher(["run", good, "--", "sandboxed"])
    vocab = ("seatbelt", "bubblewrap", "inherited", "none", "off")
    reported = [t for t in vocab if f'quarantine = "{t}"' in r.stderr]
    claim("L8-report", r.returncode == 0 and len(reported) == 1,
          f"execution reports one sandbox backend (got {reported})")
    claim("L8-vocab", not reported or reported[0] != "off",
          "default execution never reports the opt-out")
    # available means FUNCTIONAL: bwrap on a PATH where user namespaces are
    # blocked (GitHub's ubuntu-24.04 runners) is not a sandbox anyone declined
    has_sandbox = bool(
        (sys.platform == "darwin" and shutil.which("sandbox-exec")) or
        (shutil.which("bwrap") and subprocess.run(
            ["bwrap", "--ro-bind", "/", "/", "--unshare-net", "true"],
            capture_output=True, check=False).returncode == 0))
    claim("L8-strength", (not has_sandbox) or
          (bool(reported) and reported[0] != "none"),
          "a functional sandbox is used, never declined (an honest 'none' "
          "with a working sandbox on the host is still declining)")
    r = launcher(["run", good, "--no-sandbox", "--", "free"])
    claim("L8-optout", 'quarantine = "off"' in r.stderr,
          "--no-sandbox is honest about itself")

    # L9 -- ls: identity, phase, and whether the bytes are on hand.
    r = launcher(["ls", good, nopackage])
    out = r.stdout
    claim("L9-lists", r.returncode == 0 and "hello-package" in out
          and root_hash[:8] in out,
          "ls names the claim and its root prefix")
    claim("L9-materialized", "materialized" in out and "sealed" in out,
          "a whole implementation shows materialized + phase")
    launcher(["strip", good])
    r = launcher(["ls", good])
    claim("L9-latent", "latent" in r.stdout,
          "a stripped claim shows latent")

    # L10 -- execution hygiene: the entrypoint never inherits the caller's
    # environment. Red-team round 1 found this hole BASIN-WIDE: both vendors'
    # independently written launchers leaked the canary, because no claim
    # asked otherwise. The cage is exactly as tight as the spec; this is it.
    canary = build_claim(
        "canary-package",
        {"canary.py": 'import os\n'
                      'print(os.environ.get("LAUNCHER_CHECK_CANARY", '
                      '"absent"))\n',
         "check_canary.py": 'import subprocess, sys\n'
                            'p = subprocess.run([sys.executable, "canary.py"],'
                            ' capture_output=True, text=True)\n'
                            'sys.exit(0 if p.returncode == 0 else 1)\n',
         "package.toml": '[package]\nentrypoint = "canary.py"\n'},
        ["canary.py"], ["package.toml", "check_canary.py"],
        "python3 check_canary.py && printf ok > CANARY_OK", "CANARY_OK")
    r = launcher(["run", canary],
                 env={"LAUNCHER_CHECK_CANARY": "sekrit-424242"})
    claim("L10-scrub", r.returncode == 0 and r.stdout == "absent\n",
          "a planted secret is invisible to the entrypoint")
    claim("L10-no-leak", "sekrit-424242" not in r.stdout + r.stderr,
          "the secret appears on no channel")

    # L11 -- path confinement: recipe-derived paths stay inside the claim or
    # the launcher refuses before touching anything. Red-team round 1: a
    # tampered recipe naming "../VICTIM" made one honest draw's strip delete
    # outside its claim; the rival draw confined -- unpinned freedom, now
    # pinned.
    esc = build_claim(
        "escape-recipe",
        {"canary2.py": 'print("hi")\n',
         "check_canary2.py": 'import subprocess, sys\n'
                             'p = subprocess.run([sys.executable, '
                             '"canary2.py"])\n'
                             'sys.exit(p.returncode)\n',
         "package.toml": '[package]\nentrypoint = "canary2.py"\n'},
        ["canary2.py"], ["package.toml", "check_canary2.py"],
        "python3 check_canary2.py && printf ok > C2_OK", "C2_OK")
    victim = os.path.join(WORK, "L11_VICTIM.txt")
    with open(victim, "w") as f:
        f.write("guard me\n")
    rpath = os.path.join(esc, kernel.RECIPE)
    with open(rpath) as f:
        m = f.read()
    with open(rpath, "w") as f:
        f.write(m.replace('"canary2.py"', '"../L11_VICTIM.txt"', 1))
    r = launcher(["strip", esc])
    claim("L11-strip", r.returncode == 3 and os.path.exists(victim),
          "escaping recipe: strip refuses, the outside file is intact")
    r = launcher(["run", esc])
    claim("L11-run", r.returncode == 3 and r.stdout == ""
          and os.path.exists(victim),
          "escaping recipe: run refuses before regrowing or executing")

    # L12 -- the claim argument may be relative, from any cwd. A landed
    # validation draw doubled relative paths ("claim/claim/entry.py"): the
    # spec had only ever exercised absolute paths, so the invocation surface
    # was free. Pinned: a claim runs the same from anywhere.
    r = launcher(["run", "canary-package"], cwd=WORK)
    claim("L12-relative", r.returncode == 0 and r.stdout == "absent\n",
          "a relative claim path from a different cwd runs identically")

    return report()


def report():
    print()
    if failures:
        print(f"LAUNCHER CHECK: FAIL ({len(failures)})")
        for cid, detail in failures:
            print("  " + cid + "  " + detail)
        return 1
    print("LAUNCHER CHECK: PASS")
    return 0


if __name__ == "__main__":
    rc = main()
    # A verdict is a claim's pinned OUTPUT: write one only when running as a
    # claim's gate, never into whatever directory someone invoked this from.
    if rc == 0 and os.path.isfile("claim.toml"):
        with open("LAUNCHER_OK", "w") as f:
            f.write("launcher-ok\n")
    sys.exit(rc)
