"""Kernel-recipe conformance gate — parsing an untrusted recipe.

`load_recipe` reads a claim's recipe under either name (reticuli.toml, or
claim.toml for older claims), exposes its steps (`gates`, `produces`,
`generated_outputs`), and refuses hostile or malformed bytes in band (a
ClaimError, never a raw traceback). Writes RECIPE_OK.

    python3 criteria/recipe_check.py        (from the repository root)
"""
import os
import sys
import tempfile

SRC = "src" if os.path.isdir("src/reticuli") else "."
sys.path.insert(0, SRC)
from reticuli._kernel import core, recipe

GOOD = ('[claim]\nname = "fx"\ninputs = ["spec.txt"]\n\n[[step]]\n'
        'kind = "produce"\noutput = "impl.py"\nclass = "generated"\n'
        'request = "x"\n\n[[step]]\nkind = "gate"\noutput = "V"\n'
        'class = "validated"\nrun = "printf v > V"\n')


def _claim(d: str, toml: str, name: str = "reticuli.toml") -> str:
    room = os.path.join(d, name.replace(".", "_"))
    os.makedirs(room, exist_ok=True)
    with open(os.path.join(room, name), "w", encoding="utf-8") as f:
        f.write(toml)
    return room


def battery() -> None:
    d = tempfile.mkdtemp()
    try:
        r = _claim(d, GOOD)
        parsed = recipe.load_recipe(r)
        assert [s["kind"] for s in recipe._steps(parsed)] == ["produce", "gate"], \
            "the steps are read in order"
        assert [g["output"] for g in recipe.gates(parsed)] == ["V"], "gates() names the gate"
        assert [p["output"] for p in recipe.produces(parsed)] == ["impl.py"], \
            "produces() names the produce steps"
        assert recipe.generated_outputs(parsed) == ["impl.py"], \
            "generated_outputs() names the generated bytes"

        # the older recipe name still reads
        r2 = _claim(d, GOOD, "claim.toml")
        assert recipe.load_recipe(r2)["claim"]["name"] == "fx", \
            "claim.toml is read under its legacy name"

        # malformed or hostile recipes refuse IN BAND, never a raw traceback
        bad_recipes = (
            'not = [valid\n',
            ('[claim]\nname = "x"\n\n[[step]]\n'
             'kind = "explode"\noutput = "V"\nclass = "validated"\n'),
        )
        for bad in bad_recipes:
            rb = _claim(d, bad, "reticuli.toml")
            # reuse one dir: overwrite
            with open(os.path.join(rb, "reticuli.toml"), "w", encoding="utf-8") as f:
                f.write(bad)
            try:
                recipe.load_recipe(rb)
            except core.ClaimError:
                pass
            else:
                raise AssertionError(f"a malformed recipe must refuse in band: {bad!r}")
    finally:
        import shutil
        shutil.rmtree(d, ignore_errors=True)


if __name__ == "__main__":
    battery()
    if os.path.isfile("reticuli.toml") or os.path.isfile("claim.toml"):
        with open("RECIPE_OK", "w", encoding="utf-8") as f:
            f.write("recipe-ok\n")
    print("recipe-ok")
