"""Kernel-seal conformance gate — freezing identity, and confirming it.

`seal` records the root onto the manifest; `verify` recomputes it from the bytes
present and reports whether they still hash to the sealed value. The invariant
that IS the equivalence class: the root is a function of the pinned inputs and
independent of the generated bytes — editing a generated output keeps it,
editing a pinned input moves it. Writes SEAL_OK.

    python3 criteria/seal_check.py        (from the repository root)
"""
import os
import subprocess
import sys
import tempfile

SRC = "src" if os.path.isdir("src/reticuli") else "."
sys.path.insert(0, SRC)
from reticuli._kernel import seal

SEEDED = ('[claim]\nname = "seeded"\ninputs = ["spec.txt"]\n\n[[step]]\n'
          'kind = "produce"\noutput = "impl.txt"\nclass = "generated"\n'
          'request = "x"\n\n[[step]]\nkind = "gate"\noutput = "V"\n'
          'class = "validated"\nrun = "grep -q PASS impl.txt && printf v > V"\n')


def _write(d: str, files: dict) -> None:
    for name, content in files.items():
        with open(os.path.join(d, name), "w", encoding="utf-8") as f:
            f.write(content)




# ==== seam block for seal_check.py ====
# Paste into the check; call _seam() from its battery()/main.

# --- _kernel/seal.py: 4 seam names (0 value, 0 kind, 4 callable) ---
_SEAM__kernel_seal_VALUES = {
}
_SEAM__kernel_seal_KINDS = {}
_SEAM__kernel_seal_CALLABLES = ('_changed_parts', 'read_manifest', 'seal', 'verify')

def _seam() -> None:
    from reticuli._kernel import seal as _m__kernel_seal
    for _n, _v in _SEAM__kernel_seal_VALUES.items():
        assert getattr(_m__kernel_seal, _n) == _v, f'_kernel/seal.py seam {_n} changed'
    for _n in _SEAM__kernel_seal_KINDS:
        assert hasattr(_m__kernel_seal, _n), f'_kernel/seal.py must export {_n}'
    for _n in _SEAM__kernel_seal_CALLABLES:
        assert callable(getattr(_m__kernel_seal, _n, None)), f'_kernel/seal.py must export callable {_n}'


def battery() -> None:
    _seam()
    d = tempfile.mkdtemp()
    try:
        s = os.path.join(d, "seeded")
        os.makedirs(s)
        _write(s, {"claim.toml": SEEDED, "spec.txt": "acceptance criteria: v1\n",
                   "impl.txt": "PASS — implementation one\n"})
        subprocess.run("grep -q PASS impl.txt && printf v > V",
                       shell=True, cwd=s, check=True)
        seal.seal(s)
        v = seal.verify(s)
        assert v["ok"] and len(v["root"]) == 64, "the seeded claim seals and verifies"
        r_seed = v["root"]

        _write(s, {"impl.txt": "PASS — implementation two, wholly rewritten\n"})
        v = seal.verify(s)
        assert v["ok"] and v["root"] == r_seed, \
            "editing a generated output keeps the root"

        _write(s, {"spec.txt": "acceptance criteria: v2 (stricter)\n"})
        v = seal.verify(s)
        assert not v["ok"] and v["recomputed"] != r_seed, \
            "editing a pinned input moves the claim and breaks identity"

        # a manifest that reads back is what seal wrote
        m = seal.read_manifest(s)
        assert m["name"] == "seeded" and len(m["root"]) == 64, \
            "the manifest carries name and root"
    finally:
        import shutil
        shutil.rmtree(d, ignore_errors=True)


if __name__ == "__main__":
    battery()
    if os.path.isfile("reticuli.toml") or os.path.isfile("claim.toml"):
        with open("SEAL_OK", "w", encoding="utf-8") as f:
            f.write("seal-ok\n")
    print("seal-ok")
