"""The repository seals itself: six layered claims, and the roots are a lockfile.

`scripts/selfclaim.py` builds the chain — each layer carrying everything below it
as component outputs, gated by that layer's own acceptance check. This check
runs that build and holds it to three claims:

  * every layer seals and verifies fresh;
  * the outermost layer's DEEP audit re-earns every layer beneath it, on the
    bytes the outer claim ships (not on each layer's own sealed copy);
  * the six roots are exactly the values pinned below.

The third is the interesting one. These roots are a hash over each layer's
recipe, its check's bytes, and its verdict's bytes — nothing about the host, the
interpreter, or the clock. So they are a lockfile over this repository's own
behavior: change a layer's implementation and they hold; change what a layer is
CHECKED for and they move, loudly, here.

    python3 criteria/self_check.py        (from the repository root)
"""
import os
import shutil
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

import selfclaim
from reticuli import kernel, registry

# The lockfile. Recompute with: python3 scripts/selfclaim.py
PINNED = {
    # The kernel root moved once, deliberately: the v2.1 revision pinned seven
    # measured under-specifications, superseding d64cc301…. The five layers
    # above it moved when their
    # suites stopped writing a verdict outside a claim — a change to what each
    # layer is checked for, which is exactly what this lockfile exists to
    # notice. Surface moved again when `assess` joined it: a new verb means a
    # new module in the layer and a new entry in its check. And again when
    # `heldout.py` joined it — a module in a layer is a produce step in that
    # layer's recipe, and the recipe text is inside the root, so composition
    # moves a root even though every module's BYTES stay generated. The same
    # revision edited `render.py` in the authoring layer and moved nothing,
    # which is the other half of the same fact.
    #
    # 2026-09-16: the five moved again when the recipe file was renamed
    # claim.toml -> reticuli.toml. The FILENAME is not in the root preimage, so
    # the rename alone moved nothing -- every example root is byte-identical
    # across it. What moved these is that each suite guarded writing its verdict
    # on `isfile("claim.toml")`, meaning "am I running as a claim's gate?", and
    # had to learn the second name. A criterion changed, so the roots it defines
    # changed. The kernel stayed at 4b90feef because its suite never asked.
    #
    # 2026-09-16, later: exchange and everything above it moved when the layer
    # grew record.py (spec/record.md's authoring side) and its suite grew the
    # record batteries -- a new module is a produce step in the layer's recipe,
    # and a wider criterion is a stronger claim. The kernel, one layer below,
    # did not move; consuming a record as a crosscheck leg is its side and
    # waits for the v2.2 revision.
    #
    # 2026-09-16, the v2.2 revision: the kernel moved alone -- e650b524… --
    # when its suite pinned three more behaviors (no symlink or `..`
    # component in a declared path; records as crosscheck legs, one
    # predicate, two transports; a complete audit report on a claim whose
    # gate is itself a kernel, finding 12). The five layers above held:
    # their criteria did not change, and a layer's root covers its own
    # criterion, not its component's.
    #
    # 2026-09-17: exchange and surface moved, and only they. exchange_check
    # gained the blind export (the rebuilder's room: generated bytes stay
    # home, identity travels whole); surface_check gained `ret record` and
    # `export --blind` at the CLI. The four other layers' criteria did not
    # change, so their roots did not either -- two edits, two moved lines.
    #
    # 2026-09-17, later: surface moved alone when its suite pinned the
    # authoring on-ramp -- `pack --pytest` and `pack --environment` at the
    # grammar, with the refusal when neither gate form is given. The pytest
    # end-to-end lives in tests/, because criteria are stdlib-only and
    # pytest is not stdlib.
    #
    # 2026-09-17, the v2.3 revision: the kernel moved alone -- 82a81357… --
    # when its suite pinned the recipe's two names (finding 13: twins under
    # claim.toml and reticuli.toml share one root, and both names read),
    # the declared envelope with the THREE-VALUED VERDICT (accept, reject,
    # incomplete: a declared-but-unmeasured condition can never accept),
    # and the declared environment (the room furnished from hash-named
    # artifacts, with an offline hand-rolled wheel as the fixture).
    #
    # 2026-09-17, the command regrammar: surface moved alone -- first to
    # 40b94f38… when its suite pinned the fourteen-verb grammar (one concept
    # per verb, grouped help, older spellings as unlisted aliases), the
    # three output levels (terse default, -v, the {command, ok, status,
    # root, data} envelope), the 0/1/2 exit codes, two-level help, and the
    # folds: pack as the one authoring boundary (zero-flag over a declared
    # recipe), init carrying agent wiring, status as the one view, and
    # crosscheck materializing a real byte-copy M2 for a pair. Then to
    # dca69ba5… when a leaf-by-leaf walk of every verb x outcome pinned the
    # rest: the observed/declared/evidence triad in status (draft counts,
    # the --all table, dashes for untraced files), refusals with reasons
    # where raw tracebacks had hidden (a deleted traced file, a missing
    # import archive), invalid values exiting 2, status --all exiting by
    # what it demonstrated, and a closing glyph ban over every output the
    # battery sees. The five layers beneath kept their roots: the CLI is
    # contact, not depth.
    #
    # 2026-09-17, the maturity pass: surface moved alone -- 12749cb3… --
    # when its suite pinned the written style contract: the silence rule (a
    # passing check says nothing; makers print only the unknowable; views
    # speak), every diagnostic on stderr with class-first wording and hint
    # lines, a broken verify NAMING the moved files from the sealed parts
    # residue, color as ls does it (auto by tty, always/never overrides, the
    # label word returning wherever color is off), full hashes under -v,
    # --version, `-` as the standard stream for export/import/record, and
    # completion generated from the parser itself.
    #
    # 2026-09-17, maturity II: surface moved alone -- 3022eacf… -- when its
    # suite pinned the unknown-command answer (name the mistake, suggest the
    # near miss, exit 2), the one-voice refusal (`ret: <verb>: <fact>` from
    # every layer), the environment help topic, and the DECIDING set closing
    # the authoring triad: assess leaves root-stamped measurements as store
    # residue, and status --all renders them -- only while the root still
    # matches -- replacing its "strength unknown" line exactly then.
    #
    # 2026-09-18, the cost story: surface moved alone -- f7e65c08… -- when
    # its suite pinned the shipped producers answering to their names
    # (--producer openai[:model], the matched vendor key forwarded on the
    # user's naming, a missing SDK or credential refused in one line
    # BEFORE any money moves, a raw command passing through verbatim) and
    # the discovery bill: hooks remember the harness transcript as session
    # meta, and pack prices C1 from its usage entries over the session's
    # own window -- tokens always, usd only when the harness reported one,
    # because a price table would drift. Testimony, stamped as such.
    #
    # 2026-09-18, the import shape: surface moved alone -- 3d68a512… --
    # when its suite pinned coverage seeing the canonical Python flow
    # (`python3 check.py` where check.py says `from primes import ...`
    # covers primes.py through one level of import) and executed scripts
    # reading as deciders, never as gate outputs. Found live: the first
    # user to run the tutorial against a real Python project hit both in
    # one screenshot.
    #
    # 2026-09-18, the pure view: surface moved alone -- 99fc4d61… -- and
    # for the first time by SUBTRACTION: inspect.py left the layer.
    # status became the pure view (reads and reports, never executes, all
    # forms instant, every view ending with the confidence ladder's
    # `next`), audit inherited inspect's strict-jail posture as the CLI
    # default and now leaves a dated receipt as store residue, and the
    # receiving flow became `ret audit theirclaim` -- what it honestly
    # always was. A verb was retired because every distinction it held
    # found a truer home; the suite pins the ladder's rungs advancing,
    # the receipt's date, the strict default by capture, and the ledger.
    "kernel":    "82a813574c5f231d4e8be277da5dace4d79add8c6025171589a48f2f825e5ebc",
    "exchange":  "94cb93b544590cf07cbcc6847e4c2b45e0f68f40491c52fbfc96dc3d11987f39",
    "authoring": "63237fd5b2f2cbb727d0b953bc0b78d066589f75ce15e9f4890a88f4238b4b19",
    "agents":    "96ad9b75cedf4b020ff3ec9509e1ada3bf14bd692a72e219487f558b32ab22fe",
    "launcher":  "c19ff3a9760866abb035e3b1972cf5791924a81ed73eaa4343d7d7443cc56b03",
    "surface":   "99fc4d611a2671fd900fcf048a98bf6199fd368c4f5a9fec5c246ef23b8fd857",
}


def battery() -> None:
    work = tempfile.mkdtemp(prefix="selfclaim-")
    try:
        roots = selfclaim.build(os.path.join(work, "chain"), quiet=True)

        assert list(roots) == [layer for layer, *_ in selfclaim.LAYERS], \
            "the chain has every layer, in order"

        for layer in roots:
            claim = os.path.join(work, "chain", layer)
            assert kernel.verify(claim)["ok"], f"{layer} verifies fresh"

        # The kernel layer is not merely *like* the sealed kernel claim: built
        # from src/ by a different path, it lands on the same root the blind
        # rebuild earned and `examples/kernel/` holds. Identity is the claim, not the code.
        # Cross-check the chain's base layer against the sealed claim itself,
        # not just against the literal in PINNED. Conditional because
        # examples/kernel/ is deliberately NOT pinned into the repository's root
        # claim -- pinning it would hand a working kernel to a rebuilding
        # producer -- so it is absent when this suite runs inside an audit
        # workspace. PINNED still holds the root there; this adds an independent
        # artifact to compare against wherever one exists.
        sealed = os.path.join(ROOT, "examples", "kernel")
        if os.path.isfile(os.path.join(sealed, kernel.MANIFEST)):
            assert roots["kernel"] == kernel.read_manifest(sealed)["root"], \
                "the chain's base layer IS the sealed kernel claim"

        # A deep audit judges each layer's check against the bytes the OUTER
        # claim ships, so an inner layer cannot pass on its own sealed copy
        # while shipping something else.
        deep = registry.audit_deep(os.path.join(work, "chain", "surface"))
        assert deep["ok"], f"the whole chain re-earns: {deep.get('verdict')}"
        assert len(deep["layers"]) == len(selfclaim.LAYERS) - 1, "every layer beneath is judged"
        assert all(r["ok"] for r in deep["layers"]), \
            f"every layer earned: {[(r['name'], r.get('status')) for r in deep['layers']]}"

        drift = {k: (PINNED[k], v) for k, v in roots.items() if PINNED.get(k) != v}
        assert not drift, (
            "the self-claim roots moved — a layer's CHECK or its verdict changed, "
            f"not just its implementation: {drift}. If intended, re-pin from "
            "`python3 scripts/selfclaim.py`.")

        print(f"self-ok ({len(roots)} layers sealed, {len(deep['layers'])} re-earned deep)")
    finally:
        shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    battery()
