"""reticuli._kernel.build -- re-earning a claim's gates, cold.

`audit` is the deep verb (`spec/verification.md`): it trusts no verdict
sitting on disk. It first checks identity -- the root recomputed from
present bytes must match the sealed manifest, exactly what `verify` does
-- and only then re-derives every gate's pinned output by materializing a
fresh scratch room (pinned inputs, the guidance-stripped recipe, and
either a producer's fresh output or the generated bytes present in the
claim) and running the gate there. A pinned byte is **reproduced** only
when the fresh run writes the same bytes the claim already carries; a
claim that fails this without failing `verify` is carrying a verdict it
never re-earned.

The other names here are the pieces that composition needs: `_materialize`
builds the room, `_produce` hands one produce step to a producer callback
(guidance over `RETICULI_REQUEST`, never through the room's recipe --
`spec/identity.md`), `_compare_pin` is byte equality between two files,
`_read_usage` reads a producer's self-reported cost, and `_authorized` /
`_ssh_verify` check a producer's ssh-signed authorization against an
allowed-signers file. Stdlib only.
"""
import json
import os
import shutil
import subprocess
import tempfile

from . import core
from . import identity
from . import recipe as _recipe
from . import run as _run
from . import seal as _seal


# ---------------------------------------------------------------------------
# Rendering a stripped recipe back to TOML, for a materialized room
# ---------------------------------------------------------------------------
def _toml_key(key: str) -> str:
    if key and all(c.isalnum() or c in "_-" for c in key):
        return key
    return _toml_string(key)


def _toml_string(s: str) -> str:
    escaped = (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
        .replace("\r", "\\r")
    )
    return f'"{escaped}"'


def _toml_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, str):
        return _toml_string(v)
    if isinstance(v, list):
        return "[" + ", ".join(_toml_value(x) for x in v) + "]"
    if isinstance(v, dict):
        inner = ", ".join(f"{_toml_key(k)} = {_toml_value(x)}" for k, x in v.items())
        return "{" + inner + "}"
    raise core.ClaimError(f"cannot render {v!r} as TOML")


def _toml_dumps(doc: dict) -> str:
    """Render a parsed recipe (`[claim]` table, `[[step]]` array) as TOML text."""
    lines = []
    for key, value in doc.items():
        if isinstance(value, dict):
            lines.append(f"[{key}]")
            for k2, v2 in value.items():
                lines.append(f"{_toml_key(k2)} = {_toml_value(v2)}")
            lines.append("")
        elif isinstance(value, list) and all(isinstance(x, dict) for x in value):
            for item in value:
                lines.append(f"[[{key}]]")
                for k2, v2 in item.items():
                    lines.append(f"{_toml_key(k2)} = {_toml_value(v2)}")
                lines.append("")
        else:
            lines.append(f"{_toml_key(key)} = {_toml_value(value)}")
    return "\n".join(lines).rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# Producer guidance
# ---------------------------------------------------------------------------
def _step_guidance(step: dict):
    """A produce step's guidance for a rebuilder, either key spelling.

    `guidance` is the current name, `request` the older one
    (`spec/claim-format.md`); a step may carry only one. `None` if absent.
    """
    guidance = step.get("guidance")
    if guidance is not None:
        return guidance
    return step.get("request")


# ---------------------------------------------------------------------------
# Materializing a judging room
# ---------------------------------------------------------------------------
def _materialize(d: str, room: str, recipe: dict) -> str:
    """Build a fresh room: pinned inputs and the guidance-stripped recipe.

    The room's recipe is exactly the recipe serialized into the root
    preimage (`spec/identity.md`) -- a gate that reads its own recipe
    reads what the root names, never a producer's guidance.
    """
    os.makedirs(room, exist_ok=True)
    stripped = identity._preimage_recipe(recipe)
    with open(os.path.join(room, core.RECIPE), "w", encoding="utf-8") as f:
        f.write(_toml_dumps(stripped))
    for path in recipe.get("claim", {}).get("inputs", []):
        core._copy_into(room, path, core._safe(d, path))
    return room


# ---------------------------------------------------------------------------
# Handing one produce step to a producer
# ---------------------------------------------------------------------------
def _produce(step: dict, room: str, producer, **kwargs) -> str:
    """Invoke `producer(step, room)` for one `produce` step; write its
    result -- bytes or str -- to the step's output inside `room`.

    Guidance reaches the producer over `RETICULI_REQUEST`, never through
    the room's recipe (`spec/identity.md`).
    """
    guidance = _step_guidance(step) or ""
    saved = os.environ.get(core._ENV_REQUEST)
    os.environ[core._ENV_REQUEST] = guidance
    try:
        body = producer(step, room, **kwargs)
    finally:
        if saved is None:
            os.environ.pop(core._ENV_REQUEST, None)
        else:
            os.environ[core._ENV_REQUEST] = saved

    dest = core._safe(room, step["output"])
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    if isinstance(body, bytes):
        with open(dest, "wb") as f:
            f.write(body)
    elif isinstance(body, str):
        with open(dest, "w", encoding="utf-8") as f:
            f.write(body)
    else:
        raise core.ClaimError(
            f"producer for {step['output']!r} returned {type(body).__name__}, "
            "want bytes or str"
        )
    return dest


# ---------------------------------------------------------------------------
# Comparing a re-earned pinned output against the one the claim carries
# ---------------------------------------------------------------------------
def _compare_pin(original_path: str, candidate_path: str) -> bool:
    """Whether two files hold byte-identical content; False if either is absent."""
    if not (os.path.isfile(original_path) and os.path.isfile(candidate_path)):
        return False
    return core._hash_file(original_path) == core._hash_file(candidate_path)


# ---------------------------------------------------------------------------
# A producer's self-reported cost
# ---------------------------------------------------------------------------
def _read_usage(d: str) -> dict:
    """Read `d`'s self-reported usage file (`.reticuli/usage.json`); `{}` if absent."""
    path = core._safe(d, core.USAGE)
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            usage = json.load(f)
    except json.JSONDecodeError as exc:
        raise core.ClaimError(f"malformed usage {path!r}: {exc}") from exc
    if not isinstance(usage, dict):
        raise core.ClaimError(f"usage {path!r} is not a JSON object")
    return usage


# ---------------------------------------------------------------------------
# Producer authorization: an ssh-signed statement, verified against an
# allowed-signers file. Never enforced by content -- only checked when a
# caller asks.
# ---------------------------------------------------------------------------
def _ssh_verify(data: bytes, sig_path: str, signers_path: str, namespace: str,
                signer: str = "*") -> bool:
    """Verify a detached ssh signature over `data` in `namespace`.

    `signers_path` is an ssh `allowed_signers` file. False on any missing
    file or a non-zero `ssh-keygen -Y verify` -- never an exception, since
    an absent signature is simply not proof of anything.
    """
    if not (os.path.isfile(sig_path) and os.path.isfile(signers_path)):
        return False
    try:
        done = subprocess.run(
            ["ssh-keygen", "-Y", "verify", "-f", signers_path, "-I", signer,
             "-n", namespace, "-s", sig_path],
            input=data, capture_output=True, timeout=30, check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return done.returncode == 0


def _authorized(producer_id: str, signers_path) -> bool:
    """Whether `producer_id` appears in `signers_path`, an allowed-signers file."""
    if not signers_path or not os.path.isfile(signers_path):
        return False
    with open(signers_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and producer_id in line:
                return True
    return False


# ---------------------------------------------------------------------------
# audit: the deep re-earning verb
# ---------------------------------------------------------------------------
def audit(d: str, **kwargs) -> dict:
    """Re-earn `d`'s gates cold; distinguish verdicts earned from carried.

    First identity (`spec/verification.md`, `verify`): the root recomputed
    from bytes present must match the sealed manifest. Only if it does are
    the gates re-run, in a scratch room, cold -- a producer callback
    (`kwargs["producer"]`) regrows each generated output if given,
    otherwise the bytes present in `d` are reused as-is. Every pinned
    output the gates write must reproduce byte-for-byte; a clean run that
    writes different bytes is `mismatch`, not `ok`. Returns `{ok, verdict,
    name, root, recomputed, gates}`; `gates` has one entry per gate step,
    `{output, status, quarantine}`.
    """
    manifest = _seal.read_manifest(d)
    recipe = _recipe.load_recipe(d)
    recomputed = identity.root(recipe, d)
    if recomputed != manifest["root"]:
        return {
            "ok": False,
            "verdict": "identity mismatch",
            "name": manifest["name"],
            "root": manifest["root"],
            "recomputed": recomputed,
            "gates": [],
        }

    producer = kwargs.get("producer")
    room = tempfile.mkdtemp(prefix="reticuli-audit-")
    try:
        _materialize(d, room, recipe)

        missing = _run.preflight(recipe)
        if missing:
            return {
                "ok": False,
                "verdict": "environment",
                "name": manifest["name"],
                "root": manifest["root"],
                "recomputed": recomputed,
                "gates": [],
                "missing": missing,
            }

        gate_results = []
        earned = True
        for step in recipe.get("step", []):
            kind = step.get("kind")
            if kind == "produce":
                if producer is not None:
                    _produce(step, room, producer)
                else:
                    src = core._safe(d, step["output"])
                    if os.path.isfile(src):
                        core._copy_into(room, step["output"], src)
                continue
            if kind != "gate":
                continue

            declared_timeout = recipe.get("claim", {}).get("gate_timeout")
            result = _run.run_gate(step["run"], room, timeout=declared_timeout)
            output = step["output"]
            original_path = core._safe(d, output)
            candidate_path = core._safe(room, output)

            if result["status"] != "ok":
                status = result["status"]
                earned = False
            elif _compare_pin(original_path, candidate_path):
                status = "reproduced"
            else:
                status = "mismatch"
                earned = False

            gate_results.append({
                "output": output,
                "status": status,
                "quarantine": result["quarantine"],
            })

        return {
            "ok": earned,
            "verdict": "earned" if earned else "broken",
            "name": manifest["name"],
            "root": manifest["root"],
            "recomputed": recomputed,
            "gates": gate_results,
        }
    finally:
        shutil.rmtree(room, ignore_errors=True)
