"""reticuli._kernel.crosscheck -- the three-machine test, and the mutation
engine that gives the equivalence class a measured width.

`crosscheck(m1, m2, m3, mutants=None)` is the three-machine test
(`spec/verification.md`): one root across all three legs, byte reuse between
M1 and M2, every verdict re-earned (audit), the cost envelope and band, and
-- where the claim declares one -- the mutation floor. A leg is either a
claim directory (judged on the spot) or a record file (`spec/record.md`,
a frozen statement); the two transports mix freely and reach the same
verdict. The result is three-valued: `accept` only when every hard
condition the claim declares is both measured and true; a declared
condition nobody measured is `incomplete`, never a silent accept; anything
definitely false is `reject`.

`mutation_score(d, max_mutants=None)` measures how many deterministic
mutants of the claim's generated Python source the claim's own gate can
tell apart from the original -- kill rate, residue on `.reticuli/`, never
the root. `gate_deciders` / `vacuous_gates` are the claim-boundary check: a
gate whose every decider is itself generated bytes decides nothing a claim
can be blamed for.

Stdlib only. Never the network.
"""
import ast
import io
import json
import os
import random
import re
import shutil
import subprocess
import tempfile
import tokenize

from . import attest as _attest
from . import build as _build
from . import core
from . import identity
from . import recipe as _recipe
from . import run as _run
from . import seal as _seal

# ---------------------------------------------------------------------------
# Gate-decider parsing: which files a gate's run command actually executes,
# as opposed to merely names as an argument.
# ---------------------------------------------------------------------------
_INTERPRETERS = frozenset({'Rscript', 'awk', 'lua', 'python', 'python3', 'python2',
                           'node', 'ruby', 'perl', 'dash', 'deno', 'py.test', 'zsh',
                           'tclsh', 'php', 'sh', 'bash', 'py', 'pytest'})
_OPERATORS = frozenset({'&', '\n', '|', '||', '&&', ';'})
_SKIP_VALUE = frozenset({'-m', '-p', '--module', '-X', '-c', '-e'})
_COMPARISON = ('>', '<', '>=', '<=', '==', '!=')

_OP_SPLIT = re.compile('|'.join(re.escape(op) for op in sorted(_OPERATORS, key=len, reverse=True)))


def gate_deciders(run: str) -> list:
    """The files a gate's `run` command executes as a script or module --
    not merely names as a plain argument (`grep pattern file` names no
    decider; `python3 -m pytest tests` or `./check` does)."""
    segments = [s.strip() for s in _OP_SPLIT.split(run or "") if s.strip()]
    deciders = []
    for seg in segments:
        tokens = seg.split()
        if not tokens:
            continue
        first = tokens[0]
        if first in _INTERPRETERS:
            i, found = 1, None
            while i < len(tokens):
                tok = tokens[i]
                if tok in _SKIP_VALUE:
                    i += 2
                    continue
                if tok.startswith("-"):
                    i += 1
                    continue
                found = tok
                break
            if found:
                deciders.append(found)
        elif first.startswith("./"):
            deciders.append(first[2:])
        elif first.startswith("/") and len(first) > 1:
            deciders.append(first)
    return deciders


def vacuous_gates(recipe: dict) -> list:
    """Gates whose every decider is itself generated (never claimed) bytes:
    the verdict depends on no pinned claim, so any implementation that
    prints the passing verdict satisfies it."""
    inputs = set(recipe.get("claim", {}).get("inputs", []))
    generated = set(_recipe.generated_outputs(recipe))
    result = []
    for step in recipe.get("step", []):
        if step.get("kind") != "gate":
            continue
        deciders = gate_deciders(step.get("run", ""))
        if deciders and all(dec in generated and dec not in inputs for dec in deciders):
            result.append(step["output"])
    return result


# ---------------------------------------------------------------------------
# Producer independence: recorded, never enforced.
# ---------------------------------------------------------------------------
def independence(d: str) -> dict:
    """The producer declaration (`vendor`, `model`, `blind`) most recently
    recorded on `d`'s ledger; every field is `None` if nothing was declared."""
    vendor = model = blind = None
    for event in _run.ledger_events(d):
        if "vendor" in event or "model" in event:
            vendor = event.get("vendor", vendor)
            model = event.get("model", model)
            blind = event.get("blind", blind)
    return {"vendor": vendor, "model": model, "blind": blind}


def _independence_string(producer: dict) -> str:
    vendor = (producer or {}).get("vendor")
    if not vendor:
        return "unestablished: no producer declared"
    model = producer.get("model")
    blind_txt = "blind workspace" if producer.get("blind") else "workspace of undeclared blindness"
    return (f"declared: {vendor}/{model}, {blind_txt}, not proven "
            "(content cannot prove blindness)")


# ---------------------------------------------------------------------------
# Cost comparison: the strongest shared unit decides.
# ---------------------------------------------------------------------------
_COST_LADDER = ("usd", "tokens", "calls", "seconds")
_DEFAULT_TOLERANCE = 2.0


def _strongest_shared(c1, c3):
    if not c1 or not c3:
        return None, None, None
    for unit in _COST_LADDER:
        if unit in c1 and unit in c3:
            return unit, c1[unit], c3[unit]
    return None, None, None


# ---------------------------------------------------------------------------
# The record reader, version 2 (spec/record.md). `attest.py` implements
# only version 1 (`RECORD_FORMAT = 1`, and its member set has no room for
# `claim`); version 2 adds the required `claim` member -- the recipe's
# declared obligations (tolerance/envelope/mutation_floor), relayed so a
# crosscheck whose M1 is a frozen record can enforce exactly what one over
# the directory would. `record_canonical` / `record_digest` are version-
# agnostic (plain canonical-bytes serialization) and are reused as given.
# ---------------------------------------------------------------------------
RECORD_FORMAT = 2
RECORD_NAMESPACE = _attest.RECORD_NAMESPACE
_RECORD_MEMBERS_V2 = _attest._RECORD_MEMBERS | frozenset({"claim"})
_RECORD_CLAIM_KEYS = frozenset({"tolerance", "envelope", "mutation_floor"})
_RECORD_COST_UNITS = frozenset({"usd", "tokens", "calls", "seconds"})


def _check_claim_obligations(claim) -> None:
    _attest._require(isinstance(claim, dict), "claim must be an object")
    extra = set(claim) - _RECORD_CLAIM_KEYS
    _attest._require(not extra, f"claim has unknown key(s): {sorted(extra)}")
    for key in ("tolerance", "mutation_floor"):
        if key in claim:
            v = claim[key]
            _attest._require(
                isinstance(v, (int, float)) and not isinstance(v, bool) and v >= 0,
                f"claim.{key} must be a non-negative number, got {v!r}")
    if "envelope" in claim:
        env = claim["envelope"]
        _attest._require(isinstance(env, dict) and len(env) > 0,
                         "claim.envelope must be a non-empty object")
        for unit, ceiling in env.items():
            _attest._require(unit in _RECORD_COST_UNITS,
                             f"claim.envelope has an unknown unit: {unit!r}")
            _attest._require(
                isinstance(ceiling, (int, float)) and not isinstance(ceiling, bool) and ceiling > 0,
                f"claim.envelope.{unit} must be a positive number, got {ceiling!r}")


def record_validate(doc) -> None:
    """Refuse, in band and with a reason, any document not shaped exactly
    like a record at its declared version (`spec/record.md`)."""
    _attest._require(isinstance(doc, dict), "a record must be a JSON object")

    version = doc.get("record")
    _attest._require(isinstance(version, int) and not isinstance(version, bool),
                     f"record must be an integer, got {version!r}")
    _attest._require(version >= 1, f"record version must be positive, got {version!r}")
    _attest._require(
        version <= RECORD_FORMAT,
        f"record version {version} is newer than this kernel understands "
        f"(format {RECORD_FORMAT}); upgrade reticuli to read it")

    members = _RECORD_MEMBERS_V2 if version >= 2 else _attest._RECORD_MEMBERS
    extra = set(doc) - members
    _attest._require(not extra, f"record has unknown member(s): {sorted(extra)}")
    required = _attest._RECORD_REQUIRED | ({"claim"} if version >= 2 else set())
    missing = required - set(doc)
    _attest._require(not missing, f"record is missing required member(s): {sorted(missing)}")

    _attest._require(isinstance(doc["name"], str), "name must be a string")
    _attest._require(
        isinstance(doc["root"], str) and bool(_attest._RECORD_HEX.match(doc["root"])),
        "root must be 64 lowercase hex characters")
    _attest._require(
        isinstance(doc["build_digest"], str) and bool(_attest._RECORD_HEX.match(doc["build_digest"])),
        "build_digest must be 64 lowercase hex characters")
    _attest._require(
        isinstance(doc["when"], str) and bool(_attest._RECORD_WHEN.match(doc["when"])),
        "when must be YYYY-MM-DDTHH:MM:SSZ")

    _attest._require(isinstance(doc["gates"], list), "gates must be an array")
    for gate in doc["gates"]:
        _attest._check_gate(gate)

    _attest._check_environment(doc["environment"])

    if "cost" in doc:
        _attest._check_cost(doc["cost"])
    if "producer" in doc:
        _attest._check_producer(doc["producer"])
    if "tool" in doc:
        _attest._require(isinstance(doc["tool"], str), "tool must be a string")
    if "claim" in doc:
        _check_claim_obligations(doc["claim"])


def record_read(path: str) -> dict:
    """Read and validate a record from `path`. The file must be its own
    canonical bytes (`spec/record.md`) -- a reformatted (pretty-printed,
    reordered) copy of an otherwise-valid record is not a record, since
    a signature covers exactly one serialization and a reformatter would
    silently break every signature over it."""
    try:
        with open(path, "rb") as f:
            raw = f.read()
    except OSError as exc:
        raise core.ClaimError(f"no record at {path!r}: {exc}") from exc
    try:
        doc = json.loads(raw.decode("utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise core.ClaimError(f"malformed record {path!r}: {exc}") from exc
    record_validate(doc)
    if raw != _attest.record_canonical(doc):
        raise core.ClaimError(
            f"record {path!r} is not stored as its own canonical bytes")
    return doc


def record_signer(path: str, anchor: str, signer: str = "*") -> str:
    """Verify `path`'s detached ssh signature over its record's canonical
    bytes, in the `reticuli.record` namespace, against `anchor`. Returns
    the signer identity on success; refuses with a reason otherwise."""
    doc = record_read(path)
    sig_path = path + ".sig"
    if not os.path.isfile(sig_path):
        raise core.ClaimError(f"no signature found for record {path!r}")
    if not os.path.isfile(anchor):
        raise core.ClaimError(f"no allowed-signers file at {anchor!r}")
    data = _attest.record_canonical(doc)
    try:
        done = subprocess.run(
            ["ssh-keygen", "-Y", "verify", "-f", anchor, "-I", signer,
             "-n", RECORD_NAMESPACE, "-s", sig_path],
            input=data, capture_output=True, timeout=30, check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise core.ClaimError(f"could not verify signature for {path!r}: {exc}") from exc
    if done.returncode != 0:
        raise core.ClaimError(f"signature verification failed for record {path!r}")
    return signer


# ---------------------------------------------------------------------------
# A leg: a claim directory (judged on the spot) or a record file (frozen).
# ---------------------------------------------------------------------------
def _leg_view(path: str) -> dict:
    if os.path.isdir(path):
        v = _seal.verify(path)
        recipe = _recipe.load_recipe(path)
        aud = _build.audit(path)
        obligations = {k: recipe.get("claim", {})[k]
                       for k in ("tolerance", "envelope", "mutation_floor")
                       if k in recipe.get("claim", {})}
        return {
            "kind": "dir", "path": path,
            "root": v["root"], "build_digest": identity.build_digest(path),
            "audited": bool(aud["ok"]), "gates": aud["gates"],
            "cost": _run.cost(path) or None,
            "producer": independence(path),
            "obligations": obligations, "obligations_known": True,
        }
    doc = record_read(path)
    audited = bool(doc["gates"]) and all(g["status"] == "ok" for g in doc["gates"])
    known = "claim" in doc
    return {
        "kind": "record", "path": path,
        "root": doc["root"], "build_digest": doc["build_digest"],
        "audited": audited, "gates": doc["gates"],
        "cost": doc.get("cost"),
        "producer": doc.get("producer") or {},
        "obligations": doc.get("claim", {}) if known else {},
        "obligations_known": known,
    }


# ---------------------------------------------------------------------------
# The three-machine test
# ---------------------------------------------------------------------------
def crosscheck(m1: str, m2: str, m3: str, mutants=None) -> dict:
    paths = [os.path.realpath(p) for p in (m1, m2, m3)]
    if len(set(paths)) < 3:
        raise core.ClaimError("crosscheck requires three distinct machines")

    v1, v2, v3 = _leg_view(m1), _leg_view(m2), _leg_view(m3)

    roots = {"M1": v1["root"], "M2": v2["root"], "M3": v3["root"]}
    equivalence = len(set(roots.values())) == 1
    reuse = v1["build_digest"] == v2["build_digest"]
    audited = {"M1": v1["audited"], "M2": v2["audited"], "M3": v3["audited"]}

    rejected, incomplete = [], []
    if not equivalence:
        rejected.append("root")
    if not reuse:
        rejected.append("reuse")
    for key in ("M1", "M2", "M3"):
        if not audited[key]:
            rejected.append(f"audit:{key}")

    if v1["obligations_known"]:
        obligations = v1["obligations"]
    else:
        obligations = {}
        incomplete.append("declared_conditions")

    tolerance = obligations.get("tolerance")
    tol_in_force = tolerance if tolerance is not None else _DEFAULT_TOLERANCE
    unit, c1v, c3v = _strongest_shared(v1["cost"], v3["cost"])
    if unit is None:
        comparable = None
    else:
        lo, hi = min(c1v, c3v), max(c1v, c3v)
        comparable = (lo == 0 == hi) or (lo != 0 and hi / lo <= tol_in_force)
    if tolerance is not None:
        if comparable is None:
            incomplete.append("cost band")
        elif not comparable:
            rejected.append("cost band")

    envelope = obligations.get("envelope") or {}
    envelope_report = {}
    for unit_name, ceiling in envelope.items():
        measured = (v3["cost"] or {}).get(unit_name)
        if measured is None:
            within = None
            incomplete.append(f"envelope {unit_name}")
        else:
            within = measured <= ceiling
            if not within:
                rejected.append(f"envelope {unit_name}")
        envelope_report[unit_name] = {"declared": ceiling, "measured": measured, "within": within}

    floor = obligations.get("mutation_floor")
    mutation_report = None
    if floor is not None:
        if mutants is not None and v3["kind"] == "dir":
            ms = mutation_score(v3["path"], max_mutants=mutants)
            ok = ms["rate"] >= floor
            mutation_report = {**ms, "floor": floor, "ok": ok}
            if not ok:
                rejected.append("mutation_floor")
        else:
            incomplete.append("mutation_floor")

    if rejected:
        verdict = "reject"
    elif incomplete:
        verdict = "incomplete"
    else:
        verdict = "accept"

    return {
        "satisfied": verdict == "accept",
        "verdict": verdict,
        "rejected": rejected,
        "incomplete": incomplete,
        "equivalence": equivalence,
        "reuse": reuse,
        "audited": audited,
        "roots": roots,
        "cost": {"comparable": comparable, "envelope": envelope_report},
        "mutation_score": mutation_report,
        "independence": _independence_string(v3["producer"]),
    }


# ---------------------------------------------------------------------------
# Mutation testing: deterministic mutants of generated Python source, drawn
# from the claim's own root, re-audited against the claim's own gate.
# ---------------------------------------------------------------------------
_ARITHMETIC = (ast.Add, ast.Sub, ast.Mult, ast.Div, ast.FloorDiv, ast.Mod, ast.Pow)
_COMPARE_OPS = (ast.Gt, ast.Lt, ast.GtE, ast.LtE, ast.Eq, ast.NotEq)
_BOOL_OPS = (ast.And, ast.Or)

_SYMBOL = {
    ast.Add: "+", ast.Sub: "-", ast.Mult: "*", ast.Div: "/",
    ast.FloorDiv: "//", ast.Mod: "%", ast.Pow: "**",
    ast.Gt: ">", ast.Lt: "<", ast.GtE: ">=", ast.LtE: "<=",
    ast.Eq: "==", ast.NotEq: "!=", ast.And: "and", ast.Or: "or",
}
_OP_ALTS = {
    ast.Add: ["-"], ast.Sub: ["+"], ast.Mult: ["/"], ast.Div: ["*"],
    ast.FloorDiv: ["/"], ast.Mod: ["*"], ast.Pow: ["*"],
    ast.Gt: [s for s in _COMPARISON if s != ">"],
    ast.Lt: [s for s in _COMPARISON if s != "<"],
    ast.GtE: [s for s in _COMPARISON if s != ">="],
    ast.LtE: [s for s in _COMPARISON if s != "<="],
    ast.Eq: ["!="], ast.NotEq: ["=="],
    ast.And: ["or"], ast.Or: ["and"],
}
_OP_KIND = {cls: "arithmetic" for cls in _ARITHMETIC}
_OP_KIND.update({cls: "comparison" for cls in _COMPARE_OPS})
_OP_KIND.update({cls: "boolean" for cls in _BOOL_OPS})

_WORD_ALTS = {"True": "False", "False": "True", "and": "or", "or": "and", "is": "is not"}
_STRING_LITERAL = re.compile(r"""(?P<q>'''|\"\"\"|'|")(?P<body>.*?)(?P=q)""", re.DOTALL)


def _named(cls) -> str:
    """A short, human name for an AST operator class: its mutation kind
    (arithmetic/comparison/boolean) and its own class name."""
    return f"{_OP_KIND.get(cls, 'operator')}:{cls.__name__}"


def _line_offsets(source: str) -> list:
    offsets = [0]
    for line in source.splitlines(keepends=True):
        offsets.append(offsets[-1] + len(line))
    return offsets


def _node_span(source: str, node) -> tuple:
    """A node's absolute character span in `source`."""
    offsets = _line_offsets(source)
    start = offsets[node.lineno - 1] + node.col_offset
    end = offsets[node.end_lineno - 1] + node.end_col_offset
    return (start, end)


def _span_text(source: str, span: tuple) -> str:
    return source[span[0]:span[1]]


def _splice(source: str, span: tuple, replacement: str) -> str:
    return source[:span[0]] + replacement + source[span[1]:]


def _edit(source: str, mutant: dict) -> str:
    """Apply one mutant descriptor (`{span, replacement}`) to `source`."""
    return _splice(source, mutant["span"], mutant["replacement"])


def _label(mutant: dict, output: str) -> str:
    return (f"{output}:{mutant.get('kind', 'operator')}:{mutant['span'][0]}:"
            f"{mutant.get('before', '?')}->{mutant['replacement']}")


def _docstring_spans(source: str) -> list:
    """Spans of module/function/class docstrings, so token mutants can
    leave documentation alone."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    spans = []
    candidates = [tree] + [n for n in ast.walk(tree)
                           if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))]
    for node in candidates:
        body = getattr(node, "body", None)
        if (body and isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant)
                and isinstance(body[0].value.value, str)):
            spans.append(_node_span(source, body[0].value))
    return spans


def _op_span(source: str, left, right, symbols, word: bool = False):
    """The span of the operator token lexically between two AST nodes."""
    _, le = _node_span(source, left)
    rs, _ = _node_span(source, right)
    if rs <= le:
        return None
    chunk = source[le:rs]
    syms = sorted(symbols, key=len, reverse=True)
    if word:
        pattern = re.compile("|".join(r"\b" + re.escape(s) + r"\b" for s in syms))
    else:
        pattern = re.compile("|".join(re.escape(s) for s in syms))
    m = pattern.search(chunk)
    if not m:
        return None
    return (le + m.start(), le + m.end())


def _structural_mutants(source: str) -> list:
    """AST-level mutants: comparison, arithmetic, and boolean operators
    flipped to each of their declared alternatives."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    mutants = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Compare):
            operands = [node.left] + node.comparators
            for i, op in enumerate(node.ops):
                alts = _OP_ALTS.get(type(op))
                if not alts:
                    continue
                span = _op_span(source, operands[i], operands[i + 1], list(_SYMBOL.values()))
                if span is None:
                    continue
                for alt in alts:
                    mutants.append({"span": span, "replacement": alt,
                                    "kind": _named(type(op)), "before": _SYMBOL.get(type(op), "?")})
        elif isinstance(node, ast.BinOp):
            alts = _OP_ALTS.get(type(node.op))
            if alts:
                span = _op_span(source, node.left, node.right, list(_SYMBOL.values()))
                if span is not None:
                    for alt in alts:
                        mutants.append({"span": span, "replacement": alt,
                                        "kind": _named(type(node.op)),
                                        "before": _SYMBOL.get(type(node.op), "?")})
        elif isinstance(node, ast.BoolOp):
            alts = _OP_ALTS.get(type(node.op))
            if alts:
                for i in range(len(node.values) - 1):
                    span = _op_span(source, node.values[i], node.values[i + 1],
                                    [_SYMBOL[ast.And], _SYMBOL[ast.Or]], word=True)
                    if span is not None:
                        for alt in alts:
                            mutants.append({"span": span, "replacement": alt,
                                            "kind": _named(type(node.op)),
                                            "before": _SYMBOL.get(type(node.op), "?")})
    return mutants


def _token_mutants(source: str) -> list:
    """Token-level mutants: boolean/word keywords, and string literals
    (outside docstrings)."""
    mutants = []
    try:
        tokens = list(tokenize.generate_tokens(io.StringIO(source).readline))
    except Exception:
        tokens = []
    offsets = _line_offsets(source)
    for tok in tokens:
        if tok.type == tokenize.NAME and tok.string in _WORD_ALTS:
            start = offsets[tok.start[0] - 1] + tok.start[1]
            end = offsets[tok.end[0] - 1] + tok.end[1]
            mutants.append({"span": (start, end), "replacement": _WORD_ALTS[tok.string],
                            "kind": "word", "before": tok.string})
    doc_spans = _docstring_spans(source)
    for m in _STRING_LITERAL.finditer(source):
        span = m.span()
        if any(s <= span[0] and span[1] <= e for s, e in doc_spans):
            continue
        mutants.append({"span": span,
                        "replacement": m.group("q") + m.group("body") + "_MUT" + m.group("q"),
                        "kind": "string", "before": m.group(0)})
    return mutants


def _mutants(source: str) -> list:
    """Every mutant candidate for one source file, in deterministic order."""
    return _structural_mutants(source) + _token_mutants(source)


def _mutant_order(seed, n: int) -> list:
    """A deterministic permutation of `range(n)`, seeded from `seed`."""
    order = list(range(n))
    random.Random(seed).shuffle(order)
    return order


def _draw_order(items: list, seed) -> list:
    """`items` reordered deterministically from `seed`."""
    order = _mutant_order(seed, len(items))
    return [items[i] for i in order]


def _machine(d: str, recipe: dict, output: str, source: str, mutant: dict) -> bool:
    """Run one mutant trial in a fresh room: `True` if the claim's own
    gate tells the mutant apart from the original (killed)."""
    room = tempfile.mkdtemp(prefix="reticuli-mutant-")
    try:
        _build._materialize(d, room, recipe)
        for name in _recipe.generated_outputs(recipe):
            src = core._safe(d, name)
            if os.path.isfile(src):
                core._copy_into(room, name, src)
        mutated = _edit(source, mutant)
        with open(core._safe(room, output), "w", encoding="utf-8") as f:
            f.write(mutated)
        declared_timeout = recipe.get("claim", {}).get("gate_timeout")
        for step in recipe.get("step", []):
            if step.get("kind") != "gate":
                continue
            result = _run.run_gate(step["run"], room, timeout=declared_timeout)
            original_output = core._safe(d, step["output"])
            candidate_output = core._safe(room, step["output"])
            if result["status"] != "ok" or not _build._compare_pin(original_output, candidate_output):
                return True
        return False
    finally:
        shutil.rmtree(room, ignore_errors=True)


def mutation_score(d: str, max_mutants=None) -> dict:
    """Deterministic mutants of `d`'s generated Python source, drawn from
    its sealed root, re-audited against its own gate. Returns
    `{mutants, killed, rate, survivors}`; residue on `.reticuli/`, never
    the root."""
    recipe = _recipe.load_recipe(d)
    manifest = _seal.read_manifest(d)
    seed = manifest["root"]

    candidates = []
    for name in _recipe.generated_outputs(recipe):
        path = core._safe(d, name)
        if not (os.path.isfile(path) and name.endswith(".py")):
            continue
        with open(path, encoding="utf-8") as f:
            source = f.read()
        for m in _mutants(source):
            candidates.append((name, source, m))

    total = len(candidates)
    if max_mutants is not None and total > max_mutants:
        chosen = _draw_order(candidates, seed)[:max_mutants]
    else:
        chosen = candidates

    killed = 0
    survivors = []
    for output, source, mutant in chosen:
        if _machine(d, recipe, output, source, mutant):
            killed += 1
        else:
            survivors.append(_label(mutant, output))

    n = len(chosen)
    rate = (killed / n) if n else 1.0
    result = {"mutants": n, "killed": killed, "rate": rate, "survivors": survivors}
    core._write_json(core._safe(d, core.MUTATION_RESIDUE), result)
    return result
