"""reticuli._kernel.identity -- the root hash and the build digest.

A claim's identity (`root`) is a SHA-256 digest over what the claim *is*:
its parsed recipe, the bytes of its pinned inputs, and the bytes of every
non-generated step output. Generated outputs never enter it, so an
implementation can be deleted and regrown byte-different without moving
the root. See `spec/identity.md`.

The build digest (`build_digest`) is the complementary digest over the
concrete generated bytes present on disk -- what a signature over a
particular realization binds.
"""
import datetime
import hashlib
import json
import os

from . import core
from . import recipe as _recipe


def _claim_format(recipe: dict) -> int:
    """The recipe's declared `[claim] format`; absent means 1."""
    fmt = recipe.get("claim", {}).get("format", 1)
    if isinstance(fmt, bool) or not isinstance(fmt, int) or fmt < 1:
        raise core.ClaimError(f"claim format must be a positive integer, got {fmt!r}")
    if fmt > core.FORMAT:
        raise core.ClaimError(
            f"claim format {fmt} is newer than this kernel understands "
            f"(format {core.FORMAT}); upgrade reticuli to read it"
        )
    return fmt


def _preimage_recipe(recipe: dict) -> dict:
    """The recipe as it enters the root preimage.

    At format 3+, every step's `guidance` and `request` keys are stripped:
    a hint for a rebuilder cannot decide acceptance, so it does not name
    the claim. Formats 1 and 2 serialize the whole recipe unchanged.
    """
    if _claim_format(recipe) < 3 or "step" not in recipe:
        return recipe
    stripped = dict(recipe)
    stripped["step"] = [
        {k: v for k, v in step.items() if k not in ("guidance", "request")}
        for step in recipe["step"]
    ]
    return stripped


def _json_default(obj):
    if isinstance(obj, (datetime.date, datetime.time, datetime.datetime)):
        raise core.ClaimError(
            "TOML date/time values cannot be sealed: no canonical JSON form"
        )
    raise TypeError(f"object of type {type(obj).__name__} is not JSON serializable")


def _canonical_json(obj) -> str:
    """The canonical serialization: sorted keys, default separators, ASCII."""
    return json.dumps(obj, sort_keys=True, ensure_ascii=True, default=_json_default)


def _step_class(step: dict) -> str:
    cls = step.get("class")
    if cls is not None:
        return cls
    return "generated" if step.get("kind") == "produce" else "pinned"


def _parts(recipe: dict, d: str) -> dict:
    """The string-to-string map the root is hashed from."""
    parts = {
        "digest": core.DIGEST,
        "recipe": _canonical_json(_preimage_recipe(recipe)),
    }
    for path in recipe.get("claim", {}).get("inputs", []):
        try:
            parts[f"input:{path}"] = core._hash_file(core._safe(d, path))
        except OSError as exc:
            raise core.ClaimError(f"missing declared input {path!r}: {exc}") from exc
    for step in recipe.get("step", []):
        if _step_class(step) == "generated":
            continue
        output = step["output"]
        try:
            parts[f"pinned:{output}"] = core._hash_file(core._safe(d, output))
        except OSError as exc:
            raise core.ClaimError(f"missing pinned output {output!r}: {exc}") from exc
    return parts


def root(recipe: dict, d: str) -> str:
    """The claim's identity: a SHA-256 hex digest over `_parts`."""
    return hashlib.sha256(_canonical_json(_parts(recipe, d)).encode("utf-8")).hexdigest()


def build_digest(d: str) -> str:
    """The digest of the generated bytes present in `d`.

    Only `produce` steps of class `generated` with no `from` key
    contribute, and only if their output file is present on disk; an
    absent generated output is omitted, never an error. The digest of no
    entries is the digest of the empty list.
    """
    recipe = _recipe.load_recipe(d)
    entries = []
    for step in recipe.get("step", []):
        if step.get("kind") != "produce" or _step_class(step) != "generated":
            continue
        if "from" in step:
            continue
        output = step["output"]
        path = core._safe(d, output)
        if not os.path.isfile(path):
            continue
        entries.append([output, core._hash_file(path)])
    entries.sort(key=lambda e: e[0])
    return hashlib.sha256(_canonical_json(entries).encode("utf-8")).hexdigest()
